### ISSUE TITLE
What is the proper way to specify min version of setuptools to handle the package.

### ISSUE THREAD

**Issue by Kentzo** [pypa/setuptools#1004]
With setuptools having releases so often it'd be nice to be able to "require" certain setuptools version in the package.

Is it currently possible via `install_requires` / `setup_requires`? Or some other option needs to be added?

**Comment by jaraco** [comment]
Unfortunately no. See #1002. The solution, when available, will be PEP 518 support in pip and other installers.

**Comment by Kentzo** [comment]
@jaraco With PEP 518 being [merged](https://github.com/pypa/pip/issues/3691) into pip, is it possible to specify required version now?

For setuptools-only, can this feature be backported to support setup.cfg-style configuration?

**Comment by jaraco** [comment]
Although I haven't been following the pip development (and I really need to try out this functionality), I think the way it works is that in your project which requires a specific version of setuptools, you declare that in the project.toml. So if you need Setuptools 30.3 or later, you have `setuptools>=30.3` in the toml file. I don't yet know the specifics, but that's the intention. Then when building/installing the package from source, it's the responsibility of pip to ensure that's satisfied before setup.py is executed. I use 30.3 as that's the first version that supported declarative config.

**Comment by jaraco** [comment]
Of course, this requirement will demand that your users have this late version of pip installed or that they otherwise prepare the environment in advance to satisfy the requirements that the toml declares.

**Comment by Kentzo** [comment]
Is there a solution for a case when I install everything with setuptools, without pip?

**Comment by jaraco** [comment]
You could write your own installer, but you'd essentially be replicating what's in pip. It would read the .toml file, determine the build dependencies, resolve, download, build and install them to a temporary location, and then build the target package.

It's conceivable that Setuptools could be updated to enforce a minimum version, based on some declaration in the target package, but such a feature doesn't yet exist, so would only work for future releases of Setuptools.

Do you have something else in mind?

**Comment by Kentzo** [comment]
What about a case when min version is needed for other command than install?

Perhaps future versions of setuptools should try to parse pyproject.toml to check if current version satisfies the requirement.
