### ISSUE TITLE
Make --*-requires options to print package dependencies to stdout

### ISSUE THREAD

**Issue by cooperlees** [pypa/setuptools#1019]
How do people feel about adding —*-requires so that we can extract the kwargs of a setup.py and print to stdout:

e.g.
prompt# python setup.py —install-requires
click >= 5.0
aiohttp
jinja2
prompt# python setup.py —extras-requires NAME
...

Thoughts?

Side note: if I add a version into requires=['click >= 6.9'] I get a 'ValueError: expected parenthesized list: '>= 6.9'
Full Trace: https://pastebin.com/icT8CUaU
- I would look to fix this too

**Comment by cooperlees** [comment]
Going through the code I see that this would need disutils diffs, or quite a decent change to setuptools. Thus why we are here I guess.

**Comment by cooperlees** [comment]
I don't think this is worth the time. Sorry for the noise.

**Comment by jaraco** [comment]
Thanks for the interest and the follow-up. I note you can list the dependencies for an installed package. See [jaraco.packaging](/jaraco/jaraco.packaging) for a routine that does just that.

Would you add one more detail - what is the use-case that's led you to wanting this feature?

**Comment by cooperlees** [comment]
I'm writing a system to automate building pypi pacakges in our environment (with our specific GCC etc.) and was looking to make it all asyncio, as pip is pretty slow (even with a local mirror). It was a nice to have, so I went back to wrapping pip, as reading how it deals with versioning + requirements etc. was very interesting and error prone to try and replicate.

I look forward to pipfile and warehouse making this more standards enforcing.
