### ISSUE TITLE
bdist_egg doesn't run 2to3 if use_2to3=True

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#102]
Originally reported by: **Anonymous**

---

When setup.py has use_2to3=True, if you run python setup.py bdist_egg, 2to3 is not run, even though it is if you run setup.py build.

It's easy enough to work around, just by calling setup.py build befiore setup.py bdist_egg.

As an example, use the attached setup.py as a replacement for the one supplied with docutils 0.11 and run bdist_egg.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/102

**Comment by jaraco** [comment]
This issue was reported also in #1120, now obsolete.
