### ISSUE TITLE
metadata race condition causes bad version metadata in editable installs

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/setuptools#1023]
this is in order to resolve pypa/setuptools_scm#137

when using setuptools_scm to determine version numbers,
doing an editable install will in fact not use the old version at first
a double installation is needed, in order to build the correct metadata

**Comment by jaraco** [comment]
Hi @RonnyPfannschmidt. Can you help distill the issue? What is the race condition? What behavior in setuptools is unexpected?

**Comment by RonnyPfannschmidt** [comment]
the workflow is as follows

1. install package editable on branch a
2. switch branch to branch b (that would result in a different version)
3. editable install again
4. observe wrong version metadata
5. editable install a second time
6. observe correct version metadata again

**Comment by RonnyPfannschmidt** [comment]
@jaraco ping?

**Comment by jaraco** [comment]
I don't have any insight. I'd have to research the issue to try to understand it. I welcome others to dive into the code and try to characterize the issue.

**Comment by pganssle** [comment]
@RonnyPfannschmidt Any chance you'd be interested in writing an `xfail` test for this?

That would probably make solving the issue a lot easier.

**Comment by RonnyPfannschmidt** [comment]
@pganssle any hints on how to do so?

**Comment by pganssle** [comment]
Not terribly familiar with how `develop` works, but it seems the tests for it are in [`test_develop.py`](https://github.com/pypa/setuptools/blob/master/setuptools/tests/test_develop.py).

Possibly create one that creates a project in a temporary directory, installs with `develop`, then updates the metadata, and check to see if the metadata is updated appropriately. That said, it's possible that writing the failing test is 90% of the work of fixing this.

**Comment by RonnyPfannschmidt** [comment]
with the switch to editable wheels this no longer seems to be a issue, at least i couldn't replicate anymore
