### ISSUE TITLE
There appears to be no way to tell use_2to3 to *not* convert docstrings

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#103]
Originally reported by: **Anonymous**

---

When you specify use_2to3=True in setup.py, setuptools will convert code and docstrings (assuming they are doctests).

There appears to be no way to tell it _not_ to convert doctests, which is a problem if the code contains docstrings not intended to be doctests which, for example, contains text that looks like a doctest but will not convert cleanly (for example, it contains syntax errors).

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/103

**Comment by jaraco** [comment]
This issue is obsolete now that use_2to3 is removed.
