### ISSUE TITLE
Need labels to triage/filter issues related to `setup.py test`

### ISSUE THREAD

**Issue by techtonik** [pypa/setuptools#1031]
This repository doesn't make use of labels. It should be.

**Comment by jaraco** [comment]
> This repository doesn't make use of labels.

It does. It just doesn't have labels for what you're expecting. What are you expecting (more generally)? Can you propose a scheme that the project could use that would help?

I'm a little reluctant to add a `command-<name>` label for each command. `test` is too generic and could easily be confused with setuptools' tests.

Plus, I'd like to deprecate the test command.

**Comment by techtonik** [comment]
I think that every part of `setuptools` functionality is an `area` that deserves a separate keyword. Even it `testing` means mixing both `test` command and setuptools tests, but I'd like to concentrate on `setup.py test` only as it is more valuable for users.

**Comment by jaraco** [comment]
I think the mention of `setup.py test` or `test command` is sufficient to free-text search for a feature that's largely deprecated. Thanks for the suggestion.
