### ISSUE TITLE
Deprecate --test-suite and --test-module in favor of --single

### ISSUE THREAD

**Issue by techtonik** [pypa/setuptools#1034]
`setup.py test -h` still shows `--test-module`, which is replaced by extended `-s` functionality.

https://setuptools.readthedocs.io/en/latest/setuptools.html#test-build-package-and-run-a-unittest-suite

#1032 is about documenting `-s` behavior. However, now `--test-suite` naming for a long option is confusing. It would be nice to deprecate it and replace with `--single` test(module|suite|case|test) run.

**Comment by jaraco** [comment]
I've always found those parameters awkward. But I'm inclined to deprecate and remove the whole test command instead. Are there use-cases that setuptools satisfies that can't be readily migrated to other approaches?

**Comment by techtonik** [comment]
`tox` is slow - it takes 5 seconds here to run a single test. Good for CI, completely unacceptable for watcher. `tox` doesn't conflict with current usage, so no need to switch to it. `rwt` - https://pypi.python.org/pypi/rwt - this is the first time I've seen it. On the first look it requires additional boilerplate and more for managing dependencies than for actual testing.

**Comment by techtonik** [comment]
I like how `npm` defines test command in single `package.json`, and with `tox` and friends there is no end to additional config files.

**Comment by jaraco** [comment]
Closing in favor of #931. Also, today `tox` is very fast and the [coherent system](https://bit.ly/coherent-system) promises an end to additional config files.
