### ISSUE TITLE
upload_docs: AttributeError with Sphinx 1.6

### ISSUE THREAD

**Issue by eli-collins** [pypa/setuptools#1041]
I'm not entirely positive if this should be filed as a Sphinx bug, or a setuptools bug...

Running `python setup.py build_sphinx upload_docs` with Sphinx 1.6 causes [upload_docs.py line 65](https://github.com/pypa/setuptools/blob/master/setuptools/command/upload_docs.py#L65) to throw `AttributeError: builder_target_dir`. *(Tested with python 3.5.2, setuptools 35.0.2, sphinx 1.6.2)*

It looks like Sphinx 1.6 changed things to support multiple builders, and renamed the attribute to ``build_sphinx.builder_target_dirs`.  

I know upload_docs is deprecated for pypi, but it's still quite useful for staging using alternate package repos such as devpi.  

I'm happy to try and help, though I don't know the internals here very well; or refile this with Sphinx if it's something they should fix on their end.

**Comment by jaraco** [comment]
I ran into this today also. At first blush, this change strikes me as an unintended backward-incompatible change in Sphinx. Given that the change was in Sphinx, I suggest the issue should be filed there. If there's something that should be done in Setuptools, then revive this discussion here.

Incidentally, I do intend to remove the deprecation of `upload_docs` except for PyPI.
