### ISSUE TITLE
error "must be a string containing valid version specifiers" when providing a valid version specifier

### ISSUE THREAD

**Issue by mbdevpl** [pypa/setuptools#1049]
Python 3.6.0, setuptools 36.0.0.

In my `setup.py` I have the following:
```
setuptools.setup(
    name='my-package', ...,
    python_requires='3.5', ...,
    ...)
```

And when running `python3.6 setup.py sdist` (or other `*dist*`) I get the following error:

```
error in my-package setup command: 'python_requires' must be a string
containing valid version specifiers; Invalid specifier: '3.5'
```

But `3.5` is valid according to: https://www.python.org/dev/peps/pep-0345/#requires-python

> This field specifies the Python version(s) that the distribution is guaranteed to be compatible with.
>
> Version numbers must be in the format specified in Version Specifiers .
>
> Examples:
>
> ```
> Requires-Python: 2.5
> Requires-Python: >2.1
> Requires-Python: >=2.3.4
> Requires-Python: >=2.5,<2.7
> ```

When I specify `>=3.5` or `>3.5` or `==3.5` or `<3.5` or `<=3.5` setuptools don't complain. But they somehow can't tolerate plain version number. I also checked some other version numbers, like `3` or `3.6`. Getting same results.

I'm not sure if the problem is limited to `python_requires` field, but that's the only place I've seen it so far.

**Comment by jaraco** [comment]
Indeed. It looks like a bug, but the bug is probably upstream in the [packaging](/pypa/packaging) project. Can you file the issue there and link back here so the fix can be applied here once released in packaging?

**Comment by mbdevpl** [comment]
@jaraco Roger that. I've created https://github.com/pypa/packaging/issues/107

**Comment by cipherML** [comment]
Sorry.! I don't understand can you specify how to solve this problem I'm getting similar issue here.
Collecting smart-open==3.0.0 (from -r installables/requirements.txt (line 78))
  Downloading smart_open-3.0.0.tar.gz (113 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.0/113.0 kB 14.4 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in smart_open setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.5.*'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by abravalheri** [comment]
Hi @cipherML, please note that the `.*` notation is only defined for the `==` and `!=` operators, see specs in https://packaging.python.org/en/latest/specifications/version-specifiers/#version-matching.

This means you cannot use it with `>=`, `<=` and co.

**Comment by cfloressuazo** [comment]
Same issue here, I haven't done anything besides running `pip install smart-open==4.0.1` and the output:
```
Collecting smart-open==4.0.1
  Using cached smart_open-4.0.1.tar.gz (117 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in smart_open setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.6.*'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Seems like a bug deffinetely

**Comment by abravalheri** [comment]
Hi @cfloressuazo, yes indeed, this is a bug in `smart-open==4.0.1`: https://inspector.pypi.io/project/smart-open/4.1.0/packages/18/9c/a16951b5a66c86f0ea8ff5aca8d5c700138e708a76412ee7a2ec7fbd4b44/smart_open-4.1.0.tar.gz/smart_open-4.1.0/setup.py#line.90. We can see that the authors of the package are trying to use the `.*` notation with the `>=` operator, which is not something defined in the packaging standard (see discussion in https://github.com/pypa/setuptools/issues/1049#issuecomment-1923673398).

I recommend trying the latest version of `smart-open`, which might already include the fix for the problem. If that persists even in the latest version, the best would be contacting the maintainer of `smart-open`.

**Comment by cfloressuazo** [comment]
Thank you, @abravalheri, installing the latest version solves the problem.
