### ISSUE TITLE
setup.cfg metadata doesnt correctly support setup_requires

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/setuptools#1054]
while experimenting with pushing all metadata into setup.cfg i noticed that when using setup_requires - the packages only seem to be considered when preinstalled or listed in `setup.py`

**Comment by FRidh** [comment]
Isn't this documented behavior?
> (Note: projects listed in setup_requires will NOT be automatically installed on the system where the setup script is being run. They are simply downloaded to the ./.eggs directory if they’re not locally available already. If you want them to be installed, as well as being available when the setup script is run, you should add them to install_requires and setup_requires.)

https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords

**Comment by RonnyPfannschmidt** [comment]
@FRidh please excuse - i made a misstake when writing the issue

`setuptools 30.3.0` added support for putting `setup.py` supplied metadata into `setup.cfg`
i experimented with that and stumbled uppon various issues

**Comment by FRidh** [comment]
Could you share a `setup.cfg`? So you added the package to both `setup_requires` and `install_requires`, in either `setup.cfg` or `setup.py`?

**Comment by RonnyPfannschmidt** [comment]
@FRidh it didnt work when i added it only to `setup.cfg` - it worked when i added it to `setup.py`

the experiment is still on pytest-dev/apipkg#2

**Comment by althonos** [comment]
+1, I am also having trouble with extension command (pytest-runner) in `setup_requires` being ignored from my `setup.cfg`, but works when defined in `setup.py`.
