### ISSUE TITLE
Allow 'file:' for tests_require and install_require in setup.cfg

### ISSUE THREAD

**Issue by althonos** [pypa/setuptools#1074]
Hi !

Most of the people use a `requirements.txt` file for managing their dependencies. Unfortunately, `setuptools` does not support reading from those files for the requirements tags, which means that devs have to either duplicate their requirements file in the `install_requires` parameter, or not use a requirement file at all. Since `setuptools` already supports reading some metadata from a file, it should probably be allowed to read those parameters as well.

**Comment by jaraco** [comment]
What should happen if the requirements.txt includes syntax other than simple lists of requirements (perhaps with environment markers)? Presumably comments could be ignored, but what about options to pip like `-i` or `-e`?

Already, the [guidance by the python packaging user's guide](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires-vs-requirements-files) describes the distinct purposes intended for requirements.txt versus 'install_requires' and similar. By referencing a requirements.txt file for a package's declared minimum required versions, it violates some of the goals of a requirements.txt (showing pinned versions for an environment).

How do we reconcile these challenges?

**Comment by techtonik** [comment]
Write user stories? I'd just paste requirements spec into `setup.py` as is.

**Comment by jaraco** [comment]
I don't see a viable proposal here.
