### ISSUE TITLE
sys.path ordering differences between 18.7.1 to 36.0.1 

### ISSUE THREAD

**Issue by yegorich** [pypa/setuptools#1076]
I'm a Buildroot user and after bumping setuptools to 36.0.1 we now experience issues with Python 2.7.x and packages that need a CFFI backend. You can find more details on the [CFFI mailing list](https://groups.google.com/d/msg/python-cffi/ttSTbCpnDEo/7dkPw8fOAQAJ).

Buildroot (BR) has so called host-python, that is compiled for the host BR is running on and target-python, that is part of the target root file system. During target package setup we augment PYTHONPATH with target/usr/lib/python2.7/sysconfigdata and target/usr/lib/python2.7/site-packages, so that setup.py could have access to other target python packages.

In the case of CFFI it is important, that _cffi_backend will be imported in the host-variant otherwise we get:

ImportError: /home/peko/autobuild/instance-2/output/target/usr/lib/python2.7/site-packages/_cffi_backend.so: wrong ELF class: ELFCLASS32

In setuptools version 18.7.1 put cffi-1.10.0-py2.7-linux-x86_64.egg before our target/usr/lib/python2.7/site-packages, so that host-variant could be imported, but setuptools 36.0.1 makes sys.path ordering differently and cffi-1.10.0-py2.7-linux-x86_64.egg lands at the end of the list.  The ordering can be taken from the above mentioned discussion on the CFFI mailing list.

How can one enforce another sys.path order?

**Comment by jaraco** [comment]
This change was likely in [25.0](http://setuptools.readthedocs.io/en/latest/history.html#v25-0-0) per #674. One possible option is to bring back the rewrite behavior by setting an environment variable. Probably better, though, if you want to control the sys.path order is to install your own `.pth` file or other hook that manipulates sys.path to suit the specific needs of your application.

**Comment by yegorich** [comment]
@jaraco thanks for the hints. I think we've got this issue solved by not augmenting `PYTHONPATH` with at least `target/usr/lib/python2.7/site-packages`.
