### ISSUE TITLE
Deploys failing due to bootstrapping issues

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#1084]
Since the acceptance of #1053, the tagged commits are now [failing to deploy thus](https://travis-ci.org/pypa/setuptools/jobs/253451649).

@webknjaz Can you take a look and propose a fix?

**Comment by benoit-pierre** [comment]
I believe this should fix it:
```diff
diff --git a/.travis.yml b/.travis.yml
index 08834232..cbf49da6 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -19,6 +19,7 @@ jobs:
     python: *latest_py3
     install: skip
     script: skip
+    before_deploy: python bootstrap.py
     deploy:
       provider: pypi
       on:
```

**Comment by jaraco** [comment]
I'll try that...

**Comment by jaraco** [comment]
If that works, [this build](https://travis-ci.org/pypa/setuptools/builds/253459176) should release v36.2.0.

**Comment by jaraco** [comment]
[Confirmed](https://pypi.python.org/pypi/setuptools)!

**Comment by webknjaz** [comment]
Sorry, missed that. I'd also suggest adding check for `$TRAVIS_TAG` to reduce the job running time.

**Comment by benoit-pierre** [comment]
@webknjaz: `before_deploy` is already called only if there's a deployment.

**Comment by webknjaz** [comment]
Yeah, I've already noticed that. Then it's fine for now I think :)
