### ISSUE TITLE
'extras_require' requirements cannot include environment markers

### ISSUE THREAD

**Issue by sashkab** [pypa/setuptools#1087]
I just upgraded to the latest setuptools by accident, and now get following error:

```
 'extras_require' requirements cannot include environment markers, in 'notebook': 'enum34==1.1.6; python_version < "3.4"'
```

Portion of my `extras_notebook_requirement` file:

```
enum34==1.1.6; python_version < '3.4'
```

This is probably related to the #1081.

**Comment by benoit-pierre** [comment]
Can you give more information about your exact use-case? The thing is, while this was previously allowed, this would result in wheels that don't work as expected.

For example:
```bash
> cat setup.py
import sys

from setuptools import setup

setup(
    name='foo',
    extras_require={
        'test': 'barbazquux; "foobar" in sys_platform',
    },
)
> python ./setup.py -q bdist_wheel
> unzip -p dist/foo-0.0.0-py3-none-any.whl foo-0.0.0.dist-info/metadata.json | json_pp
{
   "extensions" : {
      "python.details" : {
         "document_names" : {
            "description" : "DESCRIPTION.rst"
         }
      }
   },
   "version" : "0.0.0",
   "name" : "foo",
   "summary" : "UNKNOWN",
   "metadata_version" : "2.0",
   "run_requires" : [
      {
         "extra" : "test",
         "requires" : [
            "barbazquux"
         ]
      }
   ],
   "extras" : [
      "test"
   ],
   "generator" : "bdist_wheel (0.29.0)"
}
> pip install --user dist/foo-0.0.0-py3-none-any.whl'[test]'
Processing ./dist/foo-0.0.0-py3-none-any.whl
Collecting barbazquux; extra == "test" (from foo==0.0.0)
  Could not find a version that satisfies the requirement barbazquux; extra == "test" (from foo==0.0.0) (from versions: )
No matching distribution found for barbazquux; extra == "test" (from foo==0.0.0)
```
As you can see, the environment marker was stripped, and `barbarzquux` will always be installed.

**Comment by erikwright** [comment]
We use `extras_require` to define a list of `dev` requirements, including `mypy`. `mypy` does not install on Python 2.

**Comment by benoit-pierre** [comment]
The valid syntax is:
```bash
> cat setup.py
import sys

from setuptools import setup

setup(
    name='foo',
    extras_require={
        'test:"foobar" in sys_platform': ['barbazquux'],
    },
)
> python ./setup.py -q bdist_wheel
> unzip -p dist/foo-0.0.0-py3-none-any.whl foo-0.0.0.dist-info/metadata.json | json_pp
{
   "name" : "foo",
   "metadata_version" : "2.0",
   "generator" : "bdist_wheel (0.29.0)",
   "summary" : "UNKNOWN",
   "extensions" : {
      "python.details" : {
         "document_names" : {
            "description" : "DESCRIPTION.rst"
         }
      }
   },
   "version" : "0.0.0",
   "run_requires" : [
      {
         "extra" : "test",
         "requires" : [
            "barbazquux"
         ],
         "environment" : "\"foobar\" in sys_platform"
      }
   ],
   "extras" : [
      "test"
   ]
}
> pip install --user dist/foo-0.0.0-py3-none-any.whl'[test]'
Processing ./dist/foo-0.0.0-py3-none-any.whl
Installing collected packages: foo
Successfully installed foo-0.0.0
```

**Comment by sashkab** [comment]
My problem wasn't with the change -- it is clearly bug fix, but with the fact that breaking change was introduced in the maintenance release.

I'd expect first deprecation warning, and then removed in follow up release.

**Comment by benoit-pierre** [comment]
But it does not break a valid case. It was already broken, you just did not know it because setuptools was silently allowing it.

**Comment by erikwright** [comment]
@benoit-pierre So if I understand correctly, we will define two separate `extras_require` sections, one for Python 2 and one for Python 3. They will both be named `test` and they will both be complete lists of packages, and one *or* the other will be installed. Is that right?

**Comment by benoit-pierre** [comment]
Just to clarify, this would work as expected:
```python
    extras_require={
        'test': ['flake8'],
        'test:python_version >= "3.4"': ['mypy'],
    },
```
installing both `flake8` and `mypy` when using Python 3.4+.

**Comment by benoit-pierre** [comment]
@sashkab: honestly, I did not even know a syntax like `'test:python_version >= "3.4"': ['mypy'],` was valid when I make the PR (I never saw it documented anywhere). Maybe I can make a new PR to automatically convert something like `'test': ['mypy; python_version >= "3.4"],` to `'test:python_version >= "3.4"': ['mypy'],`.

**Comment by sashkab** [comment]
> `'test:python_version >= "3.4"': ['mypy'],`

No, syntax was:

```
extras_require={ 
   'notebook': ["enum34==1.1.6; python_version < '3.4'"]
}
```

**Comment by benoit-pierre** [comment]
OK, but this would not work as expected, `enum34` would be installed no matter the Python version. While this would have worked (and still does):
```
extras_require={ 
   'notebook: python_version < "3.4"': ['enum34==1.1.6']
}
```

**Comment by benoit-pierre** [comment]
I just tested with Python 3.6 and `setuptools==33.1.1`, and when installing from wheel `enum34` definitively get installed too as the environment marker was stripped in the wheel metadata.

**Comment by sashkab** [comment]
Interesting: I'm positive, that package in question wasn't installed:

```sh
.tox/py36-macos/bin (develop) $ pip list --format=columns | grep -E 'setuptools|enum34'
setuptools (33.1.1)
.tox/py36-macos/bin (develop) $ python -V
Python 3.6.1
```

My tox environment installs all extras.

**Comment by sashkab** [comment]
I don't want to waist your time -- my main complain was ERROR instead of DeprecationWarning. I fixed my code to work correctly in 20 minutes, and as I did not see this reported -- reported to have a discussion.

**Comment by benoit-pierre** [comment]
@sashkab: thanks for reporting, see #1088 for a PR that would allow both syntax.

**Comment by sashkab** [comment]
Thank you, @benoit-pierre!
