### ISSUE TITLE
Environment marker support is not documented

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#109]
Originally reported by: **ncoghlan (Bitbucket: [ncoghlan](http://bitbucket.org/ncoghlan), GitHub: [ncoghlan](http://github.com/ncoghlan))**

---

setuptools supports PEP 345 style environment markers for dependency declarations, but this isn't documented in http://pythonhosted.org/setuptools/setuptools.html#declaring-dependencies

Explaining how this works is important for adoption of the wheel format, as projects like IPython need it in order to replace the conditional dependency logic in their setup.py files with the appropriate environment markers.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/109

**Comment by tuukkamustonen** [comment]
While not very thorough description, looks like it's at least touched in http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies. Also https://packaging.python.org/specifications/dependency-specifiers also points to PEPs that specify the markers.

I assume this ticket could be closed?

**Comment by ncoghlan** [comment]
Aye, this is covered now, so the ticket can be closed.
