### ISSUE TITLE
Merge "wheel" into setuptools

### ISSUE THREAD

**Issue by agronholm** [pypa/setuptools#1096]
Seeing as wheels are now a fundamental part of the Python packaging ecosystem and the "wheel" library seems unmaintained, it would make sense to merge the code into setuptools itself.

**Comment by agronholm** [comment]
There needs to be some discussion about replacing things like:
```
[metadata]
license_file = LICENSE
```
This isn't even documented anywhere, but I could not find any other way to do this.

**Comment by benoit-pierre** [comment]
Latest commit on [Bitbucket](https://bitbucket.org/pypa/wheel) is from 2017-07-08, what make you think it's unmaintained?

**Comment by agronholm** [comment]
Guess I should've checked again, but as you can see, there was a long period of inactivity after 2016-09--15. The question remains: shouldn't `bdist_wheel` be part of setuptools if `bdist_egg` is?

**Comment by FRidh** [comment]
The `wheel` package provides general utilities for working with wheels. Its not only `setuptools` that builds and handles wheels, there's other backends and frontends as well that could use the package.

I agree with you that development has been quite inactive. There are some important PR's regarding reproducibility and its very annoying they're not getting any attention at all.

**Comment by agronholm** [comment]
Ok, so is the consensus that wheel needs a new maintainer? That would work too.

**Comment by leorochael** [comment]
> Ok, so is the consensus that wheel needs a new maintainer? That would work too.

I'd say so, can we close this issue?

**Comment by agronholm** [comment]
Indeed.
