### ISSUE TITLE
extras_require behaving differently in setuptools 36.2.1, breaking Twisted test

### ISSUE THREAD

**Issue by rodrigc** [pypa/setuptools#1098]
This Twisted test started failing this morning with setuptools 36.2.1:

https://github.com/twisted/twisted/blob/trunk/src/twisted/python/test/test_setup.py#L76

```
    def test_distributeTakesExtrasRequire(self):
        """
        Setuptools' Distribution object parses and stores its C{extras_require}
        argument as an attribute.
        """
        extras = dict(im_an_extra_dependency="thing")
        attrs = dict(extras_require=extras)
        distribution = Distribution(attrs)
        self.assertEqual(
            extras,
            distribution.extras_require
        )
```

With this:

```
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/Users/crodrigues/twisted1/src/twisted/python/test/test_setup.py", line 86, in test_distributeTakesExtrasRequire
    distribution.extras_require
  File "/Users/crodrigues/twisted1/src/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 837, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
twisted.trial.unittest.FailTest: {'im_an_extra_dependency': 'thing'} != {'im_an_extra_dependency': ['thing']}
- {'im_an_extra_dependency': 'thing'}
+ {'im_an_extra_dependency': ['thing']}
?                            +       +


twisted.python.test.test_setup.OptionalDependenciesTests.test_distributeTakesExtrasRequire
-------------------------------------------------------------------------------
```

Looks like the value in the dictionary is now being converted to a list,
whereas before it was not.

**Comment by rodrigc** [comment]
Looks like this behavior was introduced by @benoit-pierre in https://github.com/pypa/setuptools/commit/2328be3cc556076b91c8ec74da7b85b178dbc574

@dstufft Can you take a look?

**Comment by benoit-pierre** [comment]
Requirements in this case (or for `install_requires`/`setup_requires`):
* a single requirement as a string
* a series of requirements as a list
* a series of requirements as a multi-line strings

So those are all equivalent:
```python
{'im_an_extra_dependency': 'thing'}
{'im_an_extra_dependency': ['thing']}
{'im_an_extra_dependency': '''
thing
'''}
```

**Comment by benoit-pierre** [comment]
Maybe the assert should be changed to:
```python
self.assertEqual(
            pkg_resources.parse_requirements(extras),
            pkg_resources.parse_requirements(distribution.extras_require)
)
```
?

**Comment by rodrigc** [comment]
That doesn't seem to work.  I get:

```
twisted.trial.unittest.FailTest: <generator object parse_requirements at 0x1024b01e0> != <generator object parse_requirements at 0x1024b0410>
```

**Comment by rodrigc** [comment]
This works though:

```
        self.assertEqual(
            list(parse_requirements(extras)),
            list(parse_requirements(distribution.extras_require))
        )
```

**Comment by benoit-pierre** [comment]
Right, forgot it's a generator, but it's still wrong, because it's comparing the keys of each dictionary, and not the values:
```python
canonicalize_extras = lambda d: dict((k, list(pkg_resources.parse_requirements(v))) for k, v in d)
self.assertEqual(
            canonicalize_extras(extras),
            canonicalize_extras(distribution.extras_require),
)
```

**Comment by rodrigc** [comment]
That doesn't work for me, I'm getting:

{{{
Traceback (most recent call last):
  File "/Users/crodrigues/twisted1/src/twisted/python/test/test_setup.py", line 90, in test_distributeTakesExtrasRequire
    canonicalizeExtras(extras),
  File "/Users/crodrigues/twisted1/src/twisted/python/test/test_setup.py", line 88, in <lambda>
    for k, v in d)
  File "/Users/crodrigues/twisted1/src/twisted/python/test/test_setup.py", line 86, in <genexpr>
    canonicalizeExtras = lambda d: dict((k,
exceptions.ValueError: too many values to unpack

twisted.python.test.test_setup.OptionalDependenciesTests.test_distributeTakesExtrasRequire
-------------------------------------------------------------------------------
}}}

**Comment by benoit-pierre** [comment]
Yep sorry, I updated my comment above, it's `d.items()` in the lambda.

**Comment by alex** [comment]
I think this can be closed in favor of fixing twisted itself? https://github.com/twisted/twisted/pull/847

**Comment by rodrigc** [comment]
I'll close this for now, because https://github.com/twisted/twisted/pull/847 seems to work.
I don't know if other setuptools users will hit this, but keep an eye out for it.
