### ISSUE TITLE
finish pulling in d2to1 features

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/setuptools#1125]
as per https://twitter.com/jaraco/status/893578846372581378 we should add the rest of the features of d2tod1

CC @embray

**Comment by embray** [comment]
Or at least some of them would be useful.  I think the most compelling features are hooks--both hooks that allow modifying the metadata read from the config, and pre/post command hooks.

Less compelling features (that were originally brought over from distutils2) might be the ability to specify new custom compiler classes.  I don't think this has every been used--very few projects provide their own custom Compiler classes, and those that do (e.g. Numpy) have other huge piles of custom build code written on top of distutils...

**Comment by RonnyPfannschmidt** [comment]
@embray @jaraco while at that, should we also consider pyproject.toml support

embracing a `tool.setuptools.metadata` and `tool.setuptools.options` sections

**Comment by RonnyPfannschmidt** [comment]
closing as modern pyproject metadata is supported now
