### ISSUE TITLE
pip skips fetching package from "install_requires" section

### ISSUE THREAD

**Issue by rohit-jamuar** [pypa/setuptools#1138]
Hi,

I have a package (**testRecord1**) hosted on PyPi. I'm able to `pip install` the package on Linux platform. If I add this package in `install_requires` section of another package's setup.py and try to create a wheel for it, the wheel creation fails with the following : 
```
 Analyzing links from page https://pypi.python.org/simple/testrecord1/
    Skipping link https://pypi.python.org/packages/ec/d6/a70e8a40358e05a41269feecfcb231d0f42680ddddab9dcdbe911e6310f0/testRecord1-2018.0.0-py2.py3-none-manylinux1_x86_64.whl#md5=b440157247b4d09102ab450b70b4b3ce (from https://pypi.python.org/simple/testrecord1/); No binaries permitted for testRecord1
 Could not find a version that satisfies the requirement testRecord1 (from testRecord2==0.2) (from versions: )
```

Would really appreciate some feedback on how to circumvent this. I've also tried creating **testRecord1**'s wheel with :
```
class BinaryDistribution(dist.Distribution):
    def is_pure(self):
      return False

setup(...
distclass=BinaryDistribution
)
```
Still no luck.

Thanks,
Rohit
(p.s. wheel for **testRecord1** was created with the following `setup.cfg`:
```
[bdist_wheel]
universal = 1
```
)

**Comment by benoit-pierre** [comment]
Your `testrecord1` project only has a wheel, and no source distribution, available on PyPi; and according to your log, wheels are disabled (`No binaries permitted`), so pip cannot install it.

**Comment by rohit-jamuar** [comment]
Thanks. I'm not sure what I can change in **testRecord2**'s `setup.py` to ensure that the wheel is downloaded? I've used multiple projects, that are hosted as wheels with dependencies on other Python wheels. Not sure what I'm missing from my end.

**Comment by benoit-pierre** [comment]
What is the pip command line you are using? That's where you normally tell pip to only install from certain source types.

**Comment by benoit-pierre** [comment]
Also: you're `distrecord1` wheel is targeted at a specific platform (since it includes binary libraries), so creating an universal wheel is not possible/applicable in this case.

**Comment by benoit-pierre** [comment]
Also, you might want to use the test instance of PyPy until you get things sorted out: `https://testpypi.python.org/pypi`.

**Comment by rohit-jamuar** [comment]
Actually, the reason behind creating `testRecord1` as a universal wheel was to ensure that one is able to install it on Py2 and Py3 - the contents of this wheel are not reliant on the version of Python and  are ABI compatible with both Py2 and Py3. Without `universal = 1` entry in `setup.cfg`, `pip` was adding an extra 'py(2|3)' tag in the name of the wheel. The following was used for creating the wheel for `testRecord1` : `pip wheel bdist_wheel --p manylinux1_x86_64 .`
Alright, I'd host these on `testpypi` in the meantime.

**Comment by benoit-pierre** [comment]
Universal wheel are for pure python projects: https://packaging.python.org/tutorials/distributing-packages/#universal-wheels

**Comment by rohit-jamuar** [comment]
Thanks, I can ensure that it is not created as a universal wheel. Am I missing something in the wheel creation stage that could fix my problem?

**Comment by benoit-pierre** [comment]
No, again, I think the problem seems to be the command line being used. Please share the exact command line.

**Comment by rohit-jamuar** [comment]
This is the command-line used for creating `testRecord1`'s whl : 
`pip wheel --global-option bdist_wheel --global-option -p --global-option manylinux1_x86_64 .`
`.` contains a minimal `setup.py` which fetches all the contents to be stored in the whl.

**Comment by benoit-pierre** [comment]
I meant the call to `pip install`.

**Comment by benoit-pierre** [comment]
Just to be clear, the problem is not the well, nor is it `testRecord2`'s `setup.py`. I can install `testRecord1` locally with no issue:
```shell
> pip install -t tmp testrecord1
Collecting testrecord1
  Downloading testRecord1-2018.0.0-py2.py3-none-manylinux1_x86_64.whl (628kB)
    100% |████████████████████████████████| 634kB 2.5MB/s
Installing collected packages: testrecord1
Successfully installed testrecord1-2018.0.0
```
It only fails if for example I tell pip to only install from source:
```shell
> pip install --no-binary :all: -t tmp testrecord1
Collecting testrecord1
  Could not find a version that satisfies the requirement testrecord1 (from versions: )
No matching distribution found for testrecord1
```

**Comment by rohit-jamuar** [comment]
I think I figured out the problem, invoking `pip wheel` with `--global-option` (while building `testRecord2`) was explicitly disabling fetching of binaries from PyPi, leading to the reported error.   I ought to ensure that when I try to create a wheel for `testRecord2` which had `testRecord1` as a install-time dependency, `pip wheel`  isn't invoked with `--global-option`. Major **DUH** moment! Sorry to have wasted your time.

**Comment by benoit-pierre** [comment]
Why don't you create the wheels by using `python ./setup.py bdist_wheel ...` directly, instead of going through pip?

**Comment by rohit-jamuar** [comment]
I'm actually using conda-build to create wheels, the nicer thing about using `pip` as opposed to setup.py is that `pip` does a clean-up of temporary files post creation of wheel. "setup.py bdist_wheel" leaves behind meta files that are eventually tarball-ed into a conda-package with the wheel, which I want to avoid. But, "setup.py bdist_wheel" might be a better option in the long run.
