### ISSUE TITLE
$ `setup.py --requires` appears not to work

### ISSUE THREAD

**Issue by kennethreitz** [pypa/setuptools#1153]
using latest, on any package i try. Simply returns nothing. 

all other similar flags work, like `--url`.

**Comment by benoit-pierre** [comment]
I think this is normal as `requires` is a deprecated field for an old version of the metadata: https://www.python.org/dev/peps/pep-0345/#summary-of-differences-from-pep-314

**Comment by kennethreitz** [comment]
that's a shame. Can it be updated to reflect what's in `install_requires`?

**Comment by benoit-pierre** [comment]
What's the use case? Support for it is actually provided by distutils itself, not setuptools.

**Comment by kennethreitz** [comment]
pipenv wants to resolve a dependency graph for setup.py files, basically.

**Comment by benoit-pierre** [comment]
Do you want the requirements that needs to be installed for this environment? Or all requirements (even if their requirement markers don't match) ? What about extras?

For the former, you can use `pkg_resources` after running `./setup.py egg_info`:

```python
import pkg_resources

dist = next(pkg_resources.find_distributions('.'))
print('\n'.join(sorted(map(str, dist.requires()))))
```

To get all requirements you could use a custom distutil command:
```python
from distutils.core import Command

import pkg_resources


class show_requires(Command):

    description = "show project requirements"
    user_options = []

    def initialize_options(self):
        pass

    def finalize_options(self):
        pass

    def run(self):
        requires = []
        install_requires = getattr(self.distribution, 'install_requires', [])
        requires.extend(pkg_resources.parse_requirements(install_requires))
        extras_require = getattr(self.distribution, 'extras_require', {})
        for extra, reqs in extras_require.items():
            if not extra.startswith(':'):
                continue
            marker = extra[1:]
            e = pkg_resources.invalid_marker(marker)
            if e:
                raise e
            for r in pkg_resources.parse_requirements(reqs):
                assert not r.marker
                r.marker = marker
                requires.append(r)
        print('\n'.join(sorted(map(str, requires))))
```

**Comment by kennethreitz** [comment]
we ended up with a custom solution. thanks for the help!
