### ISSUE TITLE
Logical OR for version specifiers

### ISSUE THREAD

**Issue by dmtucker** [pypa/setuptools#1158]
According to [PEP 440](https://www.python.org/dev/peps/pep-0440/#version-specifiers),
> The comma (",") is equivalent to a logical `and` operator: a candidate version must match all given version clauses in order to match the specifier as a whole.

There does not seem to be an equivalent for logical `or`.

For example, if slash ("/") was used for this,
```
>=2.7,!=3.0.*,!=3.1.*,!=3.2.*
```
could be simplified using compatible release operators:
```
~=2.7/~=3.3
```

**Comment by xoviat** [comment]
We need PEP for this, since it affects the wheel standard.

**Comment by xoviat** [comment]
If you're up for this, then submit a PR on python/peps and join distutils-sig. It's not for the faint of heart though.

**Comment by gst** [comment]
@dmtucker 

I would have said your example resolve to:

`~=2.7/>=3.3`

?

but what about using `|` for the OR operator ? if it's usable / not restricted..

**Comment by dmtucker** [comment]
@gst Ah, good point! This is exactly why the OR is desirable... I was going for "compatible with 2.7 or compatible with 3.3". Using AND, I (and [`pip`](https://github.com/pypa/pip/blob/95bcf8c5f6394298035a7332c441868f3b0169f4/setup.py#L83)) forgot to add "and less than 4.0".

So really, this should be the example:
```
>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,<4.0
```
```
~=2.7/~=3.3
```

@xoviat I'm usually up for a new Python challenge :) I will look into this further.

**Comment by xoviat** [comment]
@dmtucker

On second thought, I have a better idea for implementation. Since proposing
and implementing a PEP will take at the very minimum a month, a better idea
would be implement a logical-equivalent generator (De Morgan's laws) that
translates the "or" expression into an equivalent "and" expression. That is
something that could be implemented and tested within an hour. I would
recommend hooking the translator into the Distribution class.

**Comment by dmtucker** [comment]
@xoviat I spent some time with this last night, and there are a couple problems with that.
One is that operators can't apply to specifiers, only clauses (e.g. `!(!A,!B)` - `!()` isn't a thing AFAIK).
Another is negating the compatible release operator. `~= V.N` is the same as `>= V.N, == V.*`, which can technically be negated, but De Morgan re-introduces the OR: `!(< V.N | != V.*)`.

**Comment by xoviat** [comment]
>  `~= V.N` is the same as `>= V.N, == V.*`. 

I'm sorry, but I don't understand this. That means that a version that specified `~3.3` would require `3.3` as the major version because of `==V.*`. That seems to contradict the fact that `3.6` is compatible with `3.3`. Am I reading this correctly?

**Comment by xoviat** [comment]
After some more consideration, I don't think that we need to go that far. Because version specifiers don't have parentheses, we should just be able to "walk the version number line" and exclude/include major versions. The transition points to check (similar to limit graphs in calculus) should be the root versions at and above, and the major versions in the expression.

For example, `~=2.7/~=3.3` has transition points at 2.0, 2.7, 3.0, 3.3, and 4.0. At each transition point, we can check slightly above/below whether the version is excluded. This approach works for parentheses too, if you are proposing them?

**Comment by xoviat** [comment]
Here's some scrappy "solution" that I put together that doesn't yet work.
It somewhat illustrates what I was describing, but the solution is slightly
more difficult to implement than I thought it would be:

```python
TEST_VERSION_STRING = "~=2.7/~=3.3"

import math

from typing import List
from pkg_resources import Requirement, Distribution

# Note: this doesn't work because versions cannot be represented
# by floats. That will be resolved in the future.


def find_critical_points(version_string: str) -> List[float]:
"""Find all of the critical points in a version string

A "critical version" is a version at which a higher
or lower distribution version will not satisfy
the requirement. For example, "~2.7" has critical
versions at "2.0", "2.7", and "3.0". We need to exclude
or include ranges between these critical points
"""

# Filter out characters we don't care about
for c in ['<', '>', '=', '~']:
version_string = version_string.replace(c, '')

# Split the string along and/or operators
substrings = version_string.replace('/', ',').split(',')
critical_points = [float(version) for version in substrings]
# Add the root versions
upper_bound = math.ciel(max(critical_points))
lower_bound = math.floor(min(critical_points))
critical_points += list(range(lower_bound, upper_bound))
return list(sorted(set(critical_points)))


def get_or_expressions(version_string: str) -> List[str]:
"""Split the version string by the "or" delimeter
Note that we assume here that that a version_string with
"or" expression cannot have "and" expressions because parentheses
are not allowed at this time.
"""
assert ',' not in version_string
return version_string.split('/')


def convert_version_string(version_string: str) -> str:
"""Convert a version_string with "or" expressions to "and"
Note that the expression cannot have "or" and "and"
"""

critical_points = find_critical_points(version_string)
or_expressions = get_or_expressions(version_string)
and_expressions = []
or_requirements = [Requirement.parse(e) for e in or_expressions]

root_version_floor = 0
major_version_floor = 0
for critical_point in critical_points:
# First, test slightly below
test_point = critical_point - 0.1
for or_expression in or_expressions:
if test_point in or_expression:
break
else:  # elif?
# Exclude the root versions from major_version_floor
if root_version_floor < test_point_major_version:
and_expressions += [
"!={}.*".format(v) for v in range(
major_version_floor,
test_point_major_version)]
```

**Comment by xoviat** [comment]
A little better:

```python
TEST_VERSION_STRING = "~=2.7/~=3.3"

from typing import List, Tuple
from operator import itemgetter
from pkg_resources import Requirement, Distribution


def get_version_tuple(version_string: str) -> Tuple[int, int, int]:
root, major, minor = version_string.split('.')
return (root, major, minor)


def find_critical_points(version_string: str) -> List[Tuple[int, int, int]]:
"""Find all of the critical points in a version string

A "critical version" is a version at which a higher
or lower distribution version will not satisfy
the requirement. For example, "~2.7" has critical
versions at "2.0", "2.7", and "3.0". We need to exclude
or include ranges between these critical points
"""

# Filter out characters we don't care about
for c in ['<', '>', '=', '~']:
version_string = version_string.replace(c, '')

# Split the string along and/or operators
substrings = version_string.replace('/', ',').split(',')
critical_points = [get_version_tuple(v) for v in substrings]
# Add the root versions
upper_bound = max(critical_points, key=itemgetter(1))[0] + 1
lower_bound = min(critical_points, key=itemgetter(1))[0]
critical_points += [
(v, 0, 0) for v in range(lower_bound, upper_bound)]
return list(sorted(set(critical_points), key=itemgetter(1)))


def get_or_expressions(version_string: str) -> List[str]:
"""Split the version string by the "or" delimeter
Note that we assume here that that a version_string with
"or" expression cannot have "and" expressions because parentheses
are not allowed at this time.
"""
assert ',' not in version_string
return version_string.split('/')


def get_version_below(version: Tuple[int, int, int]) -> Tuple[int, int,
int]:
"""Get the version slightly below the given verion"""
root, major, minor = version

if minor != 0:
return (root, major, minor - 1)
elif major != 0:
return (root, major - 1, 99)
elif root != 0:
return (root - 1, 99, 99)
else:
raise NotImplementedError()
def generate_exclusions_for(
lower: Tuple[int, int, int], upper: Tuple[int, int, int]) -> List[str]:
"""
Generate "and" expressions to exclude all versions between
the lower and upper bound
"""
expressions = []
lower_root, lower_major, lower_minor = lower
upper_root, upper_major, upper_minor = upper
for root in range(lower_root, upper_root):
expressions += ["!={}.*".format(lower)]
# We should technically cover major versions under
# the lower root version, but I will leave that out
# for now, as that has ill-defined behavior
for major in range(0, upper_major):
expressions += ["!={}.{}.*".format(upper_root, major)]

# And we won't even touch minor versions at this points
return expressions


def convert_version_string(version_string: str) -> str:
"""Convert a version_string with "or" expressions to "and"
Note that the expression cannot have "or" and "and"
"""

critical_points = find_critical_points(version_string)
or_expressions = get_or_expressions(version_string)
and_expressions = []
or_requirements = [Requirement.parse(e) for e in or_expressions]

version_floor = (0, 0, 0)
for critical_point in critical_points:
# First, test slightly below
test_point = get_version_below(critical_point)
for or_expression in or_expressions:
if test_point in or_expression:
break
else:  # elif?
# Exclude the root versions from major_version_floor
if root_version_floor < test_point_major_version:
and_expressions += generate_exclusions_for(
version_floor, test_point)
```

**Comment by xoviat** [comment]
​Actually this idea is not possible because the requirement specifier is
not a logically complete system (parentheses are not supported). So a PEP
will be required; I would recommend that you join distutils-sig and propose
this idea there.

**Comment by jaraco** [comment]
Thanks both for the discussion. Feel free to come back here if a concrete implementation can be devised that fits in with accepted designs (PEPs or similar).

**Comment by warsaw** [comment]
I've run into this now too.  We do need an OR operator in order to properly support libraries that support Python 2.7 and some combination (but not all of) Python 3 versions.

**Comment by xoviat** [comment]
Why don't you create a PEP then?

**Comment by warsaw** [comment]
On Dec 13, 2017, at 20:59, xoviat <notifications@github.com> wrote:
> 
> Why don't you create a PEP then?

Why wouldn’t PEP 566, which is still in Draft status, suffice?

**Comment by xoviat** [comment]
I don't think the json metadata is moving forward.
