### ISSUE TITLE
Merge setup.cfg spec with pyproject.toml one and deprecate setup.py and setup.cfg

### ISSUE THREAD

**Issue by KOLANICH** [pypa/setuptools#1160]
Now we have a bunch of files. It's a mess:
1 python packages metadata is in fact generated by ```setup.py``` script. This means if you need to parse it you'll have to execute the script. 
2 Recently ```pyproject.toml``` was introduced, which contains for now only the description of the packages needed to build a package and data in backend-specific formay. Why don't we have the things which are part of `setup.cfg` standardized too?

So I propose to
0 ship setuptools with python
1 merge setup.cfg into pyproject.toml and publish a PEP
2 setuptools should be workable without setup.py, only with pyproject.toml in a repo
3 pyproject.toml is the primary source of metainfo. setup.py should be executed if and only if pyproject.toml uses any variables from it.
4 Write a warning in red that setup.py is deprecated each time ```setuptools.setup``` is used

**Comment by xoviat** [comment]
> 0 ship setuptools with python

Not going to happen. In fact, we're discussing moving distutils into setuptools (@jaraco, see disttutils-sig).

**Comment by tuukkamustonen** [comment]
> 1 merge setup.cfg into pyproject.toml and publish a PEP

Just noting that `setup.cfg` is being used by several tools like flake8, pytest, etc.

> 4 pyproject.toml is the primary source of metainfo. setup.py should be executed if and only if it pyproject.toml uses some variables from it.

Care to elaborate how would pyproject.toml use variables from setup.py?

**Comment by RonnyPfannschmidt** [comment]
as things currently are, setup.py is the entrypoint and could use variables from `pyproject.toml`

i propose starting with a `tool.setuptools.opptions` section for putting plain setup.py parameters

a `tool.setuptools.metadata` for the plain metadata sections and `tool.setuptools.comands` for commands/aliases

**Comment by pganssle** [comment]
I'm going to close this in favor of #1688. We are not going to deprecate `setup.py`, and Nathaniel is probably right that any deprecation period for `setup.cfg` would probably be "forever" (though it's certainly possible).
