### ISSUE TITLE
IpmportError No module named killerbee

### ISSUE THREAD

**Issue by Hshehri** [pypa/setuptools#1173]
Hi guys.

The tools shows below that work with the default firmware of Zigbee Wireless:

zbid – List available devices
zbfind – GUI for Zigbee location tracking – Never got this working 
zbopenear - ZigBee/802.15.4 many channel listener (need 1 RZUSB per channel)
zbwireshark - Sends sniffed ZigBee packets to Wireshark via a named pipe
zbdump – tcpdump clone (libpcap or commercial Daintree SNA format)
zbconvert – Convert capture file formats (libpcap -> Daintree)
zbdsniff – Scans capture files for Zigbee encryption keys (takes a capture file)
zbgoodfind – Search a binary file to identify encryption key for encrypted .

The tools that require the killerbee firmware:
zbreplay – Replay network traffic from libpcap or Daintree files
zbscapy – scapy for ZigBee
zbkey – Attempts to retrieve a key by fake association and request/response
zbassocflood – Transmit a flood of associate requests to a target network
Killerbee comes pre-installed with most Kali distributions, however your success will vary.  Here was our out-of-the-box experience:

the first problem I have faced is:
Exception: Unable to open device.  Ensure the device is free and plugged-in

and the second: 
usb.core.USBError: [Errno 110] Operation timed out !!

The setup I was used is:

# mkdir tools; cd tools
# git clone https://github.com/riverloopsec/killerbee.git
# apt-get install libgcrypt-dev
# cd killerbee
# python setup.py install

# sudo rm -rf /usr/lib/pymodules/python2.7/killerbee
# python setup.py install
----------------------
Unfortunately, when I tried to type "Zbid" or other command -- I got this wrong message !!
 [IpmportError No module named killerbee]

**Comment by pganssle** [comment]
This does not appear to be a bug in setuptools. Possibly it is a bug in `killerbee`, or more likely it's a mismatch between various install paths. Or possibly you are installing `killerbee` for Python 2.7 and `Zbid` invokes Python 3.X.

In general, `killerbee`'s advice of invoking `python setup.py install` is bad advice. You should be using `pip install`. Either `pip install killerbee` (or `pip3 install killerbee`) if they have a package on PyPI, or if you want to install from source, use `pip(3) install .` from the repository root.
