### ISSUE TITLE
Elevate `entry_points.txt` to being a PyPA interoperability specification

### ISSUE THREAD

**Issue by ncoghlan** [pypa/setuptools#1179]
@jaraco, @takluyver has proposed that we elevate the `entry_points.txt` file format to being a PyPA interoperability specification, rather than being an internal implementation detail of `setuptools`: https://github.com/pypa/python-packaging-user-guide/pull/390

I'm inclined to say yes, since it will better allow new publishing tools like `flit` to declare plugins for existing applications that use `pkg_resources` for plugin management, and also allow new projects like `entrypoints` to experiment with alternate approaches to reading and caching the runtime lookup entry point metadata, without risking any compatibility breaks for current `pkg_resources` users.

However, I'd like to get an explicit +1 from you before we go ahead and do that. The main consequence is that if you later decided you wanted to change the entry points file format, that would now have to go through the PEP process, rather than being a purely internal setuptools design discussion.

**Comment by takluyver** [comment]
The background is that flit already allows specifying entry points. I figured that the format was unlikely to suddenly change underneath me. But now that flit is gradually shifting from my experimental guerilla packaging tool to a serious piece of software that people recommend to other people, I felt the need to make it a bit more official that entry points could be written and read by different tools.

At present, entry points are also almost required to make packages with command-line interfaces that work across platforms, so packaging tools like flit have little choice but to write them. Donald is keen to redefine scripts into standard metadata, but popular tools like pytest and pygments use entry points to find plugins, so I'd still want to support them.

**Comment by jaraco** [comment]
I'm enthusiastically +1. IMO, entry points are the single most valuable contribution that setuptools has brought to the ecosystem. The offer inversion of control at a very important layer (packaging). I'm happy to accept the consequences of elevating it to an interoperability standard. I believe this elevation was intended anyway when pkg_resources was separated and prepared for inclusion in the stdlib.
