### ISSUE TITLE
data_files support in setup.cfg

### ISSUE THREAD

**Issue by micahculpepper** [pypa/setuptools#1189]
Hello,

I work on a Python project that uses [data_files](https://docs.python.org/2/distutils/setupscript.html#installing-additional-files) in its `setup.py`. While I've moved most of my `setup.py` arguments over to a `setup.cfg` file, I still have `data_files` in `setup.py` because `setup.cfg` doesn't seem to support it.

I could take a stab at a PR to add this support in, but I just wanted to check first. Is this feature missing on purpose, or just hasn't been implemented yet?

**Comment by jaraco** [comment]
@idlesign might know the answer.

**Comment by idlesign** [comment]
Hi. I missed that out indeed. 
It seems that we only can go with separate `section` to cover `data_files`.

**Comment by micahculpepper** [comment]
OK, so I'll work on getting a PR together to add this feature in. So in the new `setup.cfg`, `data_files` would look something like this:

```ini
[options.data_files]
share/man/man1 = 
    docs/man/my_script.1.gz
```
