### ISSUE TITLE
Extension ignores CXXFLAGS

### ISSUE THREAD

**Issue by matt-chan** [pypa/setuptools#1192]
(I'm not sure if I should report this here, or at the Cython project.)

When using Extension (I used it for Cython, not sure about other cases), the CXXFLAGS variable is ignored during compile. This is a problem because it is normally set as an environmental variable for OSX/clang instead of CFLAGS (which is the norm for linux/gcc). For example, conda will not build C++11 code at all without the extra options present in CXXFLAGS.

I had to write a workaround to insert the CXXFLAGS into the Extension through the extra_compile_args parameter. Example code below:

```
def get_cxxflags():
    """If the CXXFLAGS variable is defined (clang/osx) then get it"""
    return os.environ.get("CXXFLAGS", "").split()

....

    ext_modules=[Extension(
        "x.cext",
        sources=["x/cext.pyx"] + glob.glob("x/*.cpp"),
        depends=glob.glob("x/*.hpp"),
        extra_compile_args=get_cxxflags(),
        language="c++",
        ),

```

Software tested (from conda):
```
cython                    0.26.1           py36hd51f8eb_0
python                    3.6.3                h5ce8c04_4 
setuptools                36.5.0           py36h2134326_0
...
```

**Comment by jaraco** [comment]
Seems like maybe a reasonable thing to support, though I'm surprised it's only now coming to light. How is it that for so long there's been no need in distutils or setuptools for CXXFLAGS?

I suspect such a feature should first be implemented in distutils and then setuptools can support the backport.

**Comment by ryandesign** [comment]
> Seems like maybe a reasonable thing to support, though I'm surprised it's only now coming to light. How is it that for so long there's been no need in distutils or setuptools for CXXFLAGS?

It [came to light](https://bugs.python.org/issue1222585) *fifteen years ago* in distutils. Various patches were carried forward there for years but nothing was ever merged and distutils is dead now. Meanwhile we [continue to suffer](https://trac.macports.org/ticket/59950) from this problem.

**Comment by ryandesign** [comment]
See also #1732.

**Comment by ryandesign** [comment]
So what's going to happen with this? How many more decades do we need to wait for Python to properly support modules written in C++?

**Comment by McSinyx** [comment]
@ryandesign, could you please consider patching the feature yourself, either downstream or upstream here if it's urgent.  I understand that it's frustrating to not get the responses you expected but currently as you can see setuptools don't have a lot of human power.

**Comment by ryandesign** [comment]
I'm probably not the best person to do it. Besides being very busy with many other projects, I have no knowledge of the distutils/setuptools source code and only a very basic understanding of python. I would suggest that someone already familiar with those would be a better choice. Perhaps a good starting point is to look at the patches submitted to the [distutils bug report](https://bugs.python.org/issue1222585) to see if any of that code is still applicable to setuptools.
