### ISSUE TITLE
bit.ly link for disallowed host in package_index.py invalid

### ISSUE THREAD

**Issue by kurthindenburg** [pypa/setuptools#1197]
The link in the "Note: Bypassing %s (disallowed host:' is invalid

http://bit.ly/1dg9ijs -> https://pythonhosted.org/setuptools/easy_install.html#restricting-downloads-with-allow-hosts

Perhaps it should be https://setuptools.readthedocs.io/en/latest/easy_install.html#restricting-downloads-with-allow-hosts

**Comment by 3bsilversmiths** [comment]
K
