### ISSUE TITLE
Docs are unclear that package_data cannot refer to a directory

### ISSUE THREAD

**Issue by rgov** [pypa/setuptools#1198]
`package_data` does not appear to allow you to include a directory. The documentation seems to explicitly say that it should work:

> `package_data`: Specify additional patterns to match files **and directories** that may or may not be matched by MANIFEST.in or found in source control.

In fact, it silently ignores you when you pass it a directory, and leads to much tearing-out of hair.

There is a [test case](https://github.com/pypa/setuptools/blob/9d12348e26d8c143d0b675ed147094a9e54e1c97/setuptools/tests/test_build_py.py) that makes sure directories are not copied. So the documentation seems to be incorrect, and not the implementation.

(As an added bonus, the docs also do not mention that all paths must be relative to the `package_dir`.)

**Comment by djpugh** [comment]
I think that the docs could also clarify that in the example on http://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files:

```
setup.py
src/
    mypkg/
        __init__.py
        mypkg.txt
        data/
            somefile.dat
            otherdata.dat
```
the data subdirectory has to be included with `data/*.dat` as it is not a package so if you do:
```
from setuptools import setup, find_packages
setup(
    ...
    packages=find_packages('src'),  # include all packages under src
    package_dir={'':'src'},   # tell distutils packages are under src

    package_data={
        # If any package contains *.txt files, include them:
        '': ['*.txt', '*.dat'],
    }
)
```
It wouldn't work.

It's also probably worth highlighting that the package_data will also use the package data stored in the `SOURCES.txt`  (#112) as this can lead to more confusion if `package_data` is changed in `setup.py` but this isn't cleaned.

**Comment by jaraco** [comment]
Thanks for the report and the fix.
