### ISSUE TITLE
The top-level package appears repeatedly while importing.

### ISSUE THREAD

**Issue by zhanfengchen** [pypa/setuptools#1211]
I want to install my package. After execute command "python setup.py install", when i try to import my package in ipython ide, the top-level package appears repeatedly. like follows:
![image](https://user-images.githubusercontent.com/21272170/33157691-da49ec2e-d03e-11e7-855a-9c9b79964dc7.png)
The follows is my package and my setup.py.
```
bazapylib_common/
├── bazapylib/
│   ├── common_io/
│   │   ├── excelutils.py
│   │   ├── fileutils.py
│   │   ├── __init__.py
│   ├── core/
│   │   ├── BazaTrie/
│   │   │   ├── bazatrie.py
│   │   │   ├── __init__.py
│   │   ├── dataprocess.py
│   │   ├── __init__.py
│   │   └── stringutils.py
│   ├── __init__.py
└── setup.py
```
```
from setuptools import setup
setup(
      name="bazapylib",
      version="0.0.1",
      description="The base lib",
      license="LGPL",
      packages=['bazapylib', 'bazapylib.common_io', 'bazapylib.core', 'bazapylib.core.BazaTrie'],
      install_requires=['xlwt', 'xlrd'],
      )
```
I had try to write the setup.py by using distutils.core, and the problem didn't happen.
All ```__init__.py```  files just contain ```__all__ = ['core', 'common_io']``` line and have no "import" line.
Help, please！

**Comment by jaraco** [comment]
The issue may be an iPython bug. What happens if you:

```
import bazapylib.bazapylib
```

**Comment by zhanfengchen** [comment]
It get an error, as following:
```ImportError: No module named bazapylib```

**Comment by zhanfengchen** [comment]
It get an error, as following:
```python
ImportError: No module named bazapylib
```

**Comment by zhanfengchen** [comment]
The verison of my ipython is 5.4.1

**Comment by jaraco** [comment]
Everything you've shown looks right to me from a setuptools perspective. And because the issue doesn't seem to exhibit itself in the Python environment, I'd first investigate what it is that's causing iPython to infer the wrong packages. If your investigation leads you back to Setuptools, feel free to follow up here and we can re-open.
