### ISSUE TITLE
38.2.0 Breaks installs of several packages on 2.7 with UnicodeEncodeError parsing package METADATA

### ISSUE THREAD

**Issue by mgrdcm** [pypa/setuptools#1212]
Using `setuptools==38.2.0` on Python 2.7.14, this `setup.py` will fail on **any** of the packages under `install_requires` with errors such as `UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 4258: ordinal not in range(128)`.  None of these happened under `38.1.0` for instance.  Error is happening on this line: https://github.com/pypa/setuptools/blob/97ff22f31ace57f4eabb6f1e77c9c553de0d1c24/setuptools/wheel.py#L59 

```python
from setuptools import setup, find_packages

setup(
    name="test-setuptools-encoding-problem",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "requests==2.18.4",
        "eventbrite==3.3.3",
        "django_mathfilters==0.4.0",
        "django-countries==5.0",
    ]
)
```

Verified it doesn't happen with Python `3.6.3` for instance.

**Comment by mgrdcm** [comment]
Thanks @benoit-pierre!  Let me know if I can help, for instance with testing.

**Comment by benoit-pierre** [comment]
Branch is here if you want to test  it: https://github.com/benoit-pierre/setuptools/tree/fix_wheels_metadata_handling

**Comment by mgrdcm** [comment]
@benoit-pierre Works great for me!

**Comment by thijstriemstra** [comment]
@benoit-pierre not sure if this is the right place but 38.2.0 also broke this:

```
install_requires = [
    'luma.core>=1.1.1',
    'rpi_ws281x;platform_machine=="armv7l" and platform_system=="Linux"',
    'ws2812;platform_machine=="armv7l" and platform_system=="Linux"'
]
```

Packages are always installed (not only for ARM) and not skipped.

**Comment by benoit-pierre** [comment]
OK, fix for original issue released in 36.2.1.

**Comment by mgrdcm** [comment]
Thank you so much for the quick work @benoit-pierre!

**Comment by benoit-pierre** [comment]
@thijstriemstra: can you open a new issue with more info please?

**Comment by thijstriemstra** [comment]
@benoit-pierre will do.
