### ISSUE TITLE
failing to install a postgresfixture with setuptools 38

### ISSUE THREAD

**Issue by battlemidget** [pypa/setuptools#1217]
We've started hitting this since setuptools 38 was released:

```
Collecting postgresfixture==0.4.0 (from -r requirements_test.txt (line 7))
  Downloading postgresfixture-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    error in postgresfixture setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-f03jemry/postgresfixture/

ERROR: could not install deps [-rrequirements.txt, -rrequirements_test.txt]; v = InvocationError('/run/code/.tox/py35/bin/pip install -rrequirements.txt -rrequirements_test.txt (see /run/code/.tox/py35/log/py35-1.log)', 1)
```

So far it's just for that postgresfixture package and was curious if there was a workaround to this or do we need to get in touch with their upstream to fix setup.py?

**Comment by benoit-pierre** [comment]
That's because for some reason this package's `setup.py` is using sets where list/tuples are normally expected (for `install_requires`, `test_requires`, even `packages`), and this is not allowed anymore starting with [38.0.0](https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v3800).

**Comment by battlemidget** [comment]
@benoit-pierre perfect, thank you. I'll take this up with upstream.
