### ISSUE TITLE
Better setup_requies

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#1218]
I realize that it's not the role of the backend, but since pip is taking their time, it would be nice if setuptools could (immediately when imported):

1. Check to determine whether there is a pyproject.toml in the setup.py directory
2. If there is, parse the requirements
3. Execute the following on importing setuptools

```
Distribution({'setup_requires': setup_requires})
```

**Comment by xoviat** [comment]
/cc @benoit-pierre 

If approved, l think we can have PEP 518 rolled out by tomorrow! It's trivial to implement this way and it wouldn't conflict at all with pip's implementation, since the build requirements would already be installed.

**Comment by benoit-pierre** [comment]
I don't think setuptools should be doing this kind of things on import. And this still would not allow for specifying a version of setuptools to be used that is different from the one currently installed.

**Comment by benoit-pierre** [comment]
Setuptools can't upgrade itself: yes, if the version currently being executed is not the right one, then the correct version will be installed to `.eggs` and activated, but that does not change the fact that the setuptools module as already been imported, and so the wrong version is currently in use.

**Comment by xoviat** [comment]
Okay, but setuptools is not the only build dependency and this would still be a measurable improvement.

**Comment by benoit-pierre** [comment]
Seems like a missed opportunity would have been to use something similar to pkg_resources' `__requires__`:
```diff
 setuptools/__init__.py | 7 +++++++
 1 file changed, 7 insertions(+)

diff --git i/setuptools/__init__.py w/setuptools/__init__.py
index 7da47fbe..a2719dcd 100644
--- i/setuptools/__init__.py
+++ w/setuptools/__init__.py
@@ -178,3 +178,10 @@ def findall(dir=os.curdir):
 
 
 monkey.patch_all()
+
+try:
+    from __main__ import __setup_requires__
+except ImportError:
+    pass
+else:
+    Distribution().fetch_build_eggs(__setup_requires__)
```

And then your example become:
```python
__setup_requires__ = '''
numpy
'''

import setuptools  # <-- numpy installed
import numpy

# Do numpy things

setup()
```

**Comment by xoviat** [comment]
LGTM, but can that be a list?

**Comment by xoviat** [comment]
@jaraco Would you be okay with the proposed patch?

**Comment by benoit-pierre** [comment]
Yes, like `__requires__`, a list would work too.

**Comment by jaraco** [comment]
This sounds reasonable to me... especially if there aren't issues that inhibit the implementation of PEP 518 support in pip, which I believe have been addressed herein.

**Comment by xoviat** [comment]
Implemented in gh-1235.

**Comment by pganssle** [comment]
Given that `pip` has PEP 518 support, I think we can close this, right?

**Comment by benoit-pierre** [comment]
Agreed.
