### ISSUE TITLE
sdist race condition and temp dir customization

### ISSUE THREAD

**Issue by rainwoodman** [pypa/setuptools#1222]
Currently if two sdist commands are ran at the same time there is a race condition. One sdist command can be purging the temp files under {packagename}-{packageversion} in the setup.py directory while the other is zipping it, causing error messages like this

```
Creating tar archive
removing 'cosmo4d-0.0.0' (and everything under it)
error removing cosmo4d-0.0.0: [Errno 2] No such file or directory: 'cosmo4d-0.0.0/setup.py'
error removing cosmo4d-0.0.0: [Errno 2] No such file or directory: 'cosmo4d-0.0.0/cosmo4d/tests/test_engine.py'
error removing cosmo4d-0.0.0: [Errno 2] No such file or directory: 'cosmo4d-0.0.0/cosmo4d/tests/test_pmesh.py'
error removing cosmo4d-0.0.0: [Errno 2] No such file or directory: 'cosmo4d-0.0.0/cosmo4d/tests/test_map2d.py'
error removing cosmo4d-0.0.0: [Errno 2] No such file or directory: 'cosmo4d-0.0.0/cosmo4d/tests'
error removing cosmo4d-0.0.0: [Errno 2] No such file or directory: 'cosmo4d-0.0.0/cosmo4d/iotools.py'
error removing cosmo4d-0.0.0: [Errno 2] No such file or directory: 'cosmo4d-0.0.0/cosmo4d/pmeshengine.py'
error removing cosmo4d-0.0.0: [Errno 2] No such file or directory: 'cosmo4d-0.0.0/cosmo4d/__init__.py'
error removing cosmo4d-0.0.0: [Errno 2] No such file or directory: 'cosmo4d-0.0.0/cosmo4d/version.py'
error removing cosmo4d-0.0.0: [Errno 2] No such file or directory: 'cosmo4d-0.0.0/cosmo4d/options.py'
Processing /tmp/VlnJRkP/cosmo4d-0.0.0.tar.gz
Skipping bdist_wheel for cosmo4d, due to binaries being disabled for it.
```

One possible solution to avoid the racing is to allow an argument --temproot to allow redirection of the temp directory to a different location. Then the caller to setup.py (or sdist itself) can use `mktemp -d` to avoid building sdist from the same temp dir; or at least to minimize the chances of racing.

**Comment by rainwoodman** [comment]
setuptools calls `make_distribution` of distutils, in which `base_dir` shall be modified to prefix the `temproot`. However, we cannot simply copy the code from distutils as an override, because the function changed in an incompatible way in python 3.4 (4 years ago)

https://github.com/python/cpython/blame/master/Lib/distutils/command/sdist.py#L481

Python 2.x the function hasn't changed for 8 years, so it's probably ok to override:

https://github.com/python/cpython/blame/2.7/Lib/distutils/command/sdist.py#L443

**Comment by xoviat** [comment]
In general, disutils is not thread safe. This is not something that could be fixed with patches to setuptools, because this project simply wraps code that could be up to decades old and which could use long forgotten distutils hacks. If you wanted to prevent abuse, I suppose we could implement a GIL for setuptools commands.

**Comment by rainwoodman** [comment]
Thanks but this is not about threads. It is about multiple invocations of setup.py from different processes. So any locks within Python won't help. The easiest workaround is to make setup.py reentrant by allowing it to work on a different tmpdir, postponing the responsibility of race-resolution to the caller of setup.py.

The current behaviour is problematic anyways -- what if basedir already exists and contains files useful but not below to the sdist?

In addition, I feel this may affect https://github.com/pypa/pip/issues/2195 or the sdist related workarounds.

**Comment by benoit-pierre** [comment]
I don't see how pypa/pip#2195 is related.

What is the use case for concurrent calls?

**Comment by rainwoodman** [comment]
I see one argument to avoid sdist is that it non-reentrant; but there may be other stronger arguments against using sdist.

**Comment by xoviat** [comment]
Threads aren't the only way to access and API concurrently (processes?).
The proposed "global setuptools lock" would be file-based to prevent
concurrent access by multiple processes as well. That said, this isn't
something that is going to even matter in setuptools because a frontend
will be doing the locking.

The point is that running any distutils command concurrently for the same
setup.py is not supported. In addition, there is no way that it could be
supported because setuptools is simply wrapping other people's scripts that
aren't thread-safe (which yes, includes "processes").

**Comment by xoviat** [comment]
> I see one argument to avoid sdist

Also, what does this even mean? The entire reason that sdist exists is to
generate source distributions that you can upload to pypi.

**Comment by rainwoodman** [comment]
I miss read your GIL -- the context of the phrase made me think you were really just talking of threads within a process.

Invoking sdist was mentioned as a viable workaround for the unnecessary copytree in pip installing from source. Now I see that even if sdist is not-reentrant pip is supposed to workaround it. And if I use setup.py sdist I shall implement my own locking mechanism.

I am using sdist to create a tarball for installation to avoid the slowness bug I referred to, just as several commentors there have suggested. The use case is to deploy a developing software package from source tree to the computing nodes in a super computer at job launch, where multiple jobs can be launched at the same time. 

If setup.py doesn't allow me to use an alternative tmpdir, I will have to follow your suggestion, implement a lock and let the jobs wait for each other during the launching step -- and it won't scale as well. Ideally I'd like to change the temp dir to a space local for the job. 

I suppose this is not an intended use of sdist because I am not uploading to pypi, and there are alternative approaches to the problem I am trying to solve. (e.g. wait till the pip slowness bug is fixed.) 

Nevertheless I still want to point out that insisting a hard coded temporary directory smells bad. I thought it could be an easy fix but didn't know it turns out to be so complicated.

**Comment by xoviat** [comment]
You only need to use sdist once though. So if you want to optimize
deployment, you should check the time stamps on the files and then call
setup.py sdist if they have changed from the last run. Otherwise, use the
cached sdist.

**Comment by rainwoodman** [comment]
Thanks for the suggestions. I'll do something along the lines. But this issue I'll close as it is a wont fix.
