### ISSUE TITLE
requires-python not working

### ISSUE THREAD

**Issue by ailjushkin** [pypa/setuptools#1228]
Can anybody explain why does that happen?

**Version of pip**

```
pip -V
pip 9.0.1 from c:\python27\lib\site-packages (python 2.7)
```

**Error**
Error while installing my package:

`pip install mypackage -v -v -v`

```
(requires-python:==2.7.*, ==3.6.*) is incompatible with the pythonversion in use. Acceptable python versions are:==2.7.*, ==3.6.*
```

**Python version**

`python --version`
`Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32`

**Setuptools version**

`pip show setuptools`

```
Name: setuptools
Version: 38.2.3
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: c:\python27\lib\site-packages
Requires:
```

**Comment by jaraco** [comment]
That `requires-python` requires the Python to be both equal to 2.7.x **and** equal to 3.6.x. You'll be hard-pressed to find a Python version that satisfies that requirement ;).

The syntax I've seen used is: `>=2.7.*, !=3.0.*, !=3.1.*, ..., !=3.5.*`.

**Comment by ailjushkin** [comment]
@jaraco Awesome, thank you very much indeed.
