### ISSUE TITLE
description-content-type metadata field is not documented

### ISSUE THREAD

**Issue by cmcginty** [pypa/setuptools#1236]
I can't find any docs that explicitly state what the kwarg value for "description-content-type" is supposed to be. If I find it i'll close the ticket.

==========

`long_description_content_type`

I guess this is the value, but where are the docs for this?

https://github.com/pypa/setuptools/blob/f012485e4767f3be81493c93ad534a02c6f14f14/setuptools/dist.py#L63

**Comment by xnuinside** [comment]
@cmcginty , if you look at documentation for Metadata section of setup.cfg (http://setuptools.readthedocs.io/en/latest/setuptools.html#metadata ) , you can find that

long_description_content_type mast be a 'str', it is a string with description

**Comment by xnuinside** [comment]
@cmcginty, http://setuptools.readthedocs.io/en/latest/setuptools.html#metadata - inside this doc info about type of this variable `long_description_content_type`

what is this you can find: 
 https://packaging.python.org/specifications/core-metadata/#description-content-type-optional (link to this page was provided inside https://github.com/pypa/setuptools/pull/1075

**Comment by cmcginty** [comment]
Thanks for the links.

Setup tools has a `description` and `long_description` field, so I think it's still ambiguous that `Description-Content-Type` applies to `long_description_content_type` in setuptools. Can the setuptools docs be modified to link to packaging docs you provided?

IMO I think the distinction between summary and description is clear enough. Why does setuptools deviate from the PyPA guidelines?

**Comment by jaraco** [comment]
> Can the setuptools docs be modified to link to PyPA packaging docs you provided?

Yes. Please send a PR.

> Why does setuptools deviate from the PyPA guidelines?

Mainly for historical reasons. It probably evolved this way, refining the purpose as the use-cases were clarified. And while the naming in the metadata has evolved more rapidly, the API for Setuptools has evolved less so.

> Should I open another bug for this one?

Perhaps, and especially if you wish to develop a PR to help transition the project from the current naming to a new one. The trick becomes doing that without breaking every build. There's probably a 2 year transition period where both names would need to be supported. If you have the patience for an effort like that, or have other ideas on how this change could be made with less trouble, then by all means, let's do it!

**Comment by brainwane** [comment]
A contributor added info in https://github.com/pypa/python-packaging-user-guide/pull/457 to https://packaging.python.org/tutorials/distributing-packages/ that may be helpful here.

**Comment by vitoace** [comment]
I will be working on it with Gene.

**Comment by genemat** [comment]
Hi I'm Gene this is my first github project

**Comment by jaraco** [comment]
That links to #1075.

**Comment by pganssle** [comment]
Closed in #1539
