### ISSUE TITLE
extras_require: are installed by default

### ISSUE THREAD

**Issue by FRidh** [pypa/setuptools#1242]
Installing [jupyter_client](https://files.pythonhosted.org/packages/bf/c7/6a2fabf67d396fe0e77f2e895f7b2058699b1c5cb761ed3520755cd9ec71/jupyter_client-5.2.0.tar.gz) with
```
python setup.py bdist_wheel
pip install *.whl
```
will attempt to install the `extras_require` listed in the `setup.py`.

- setuptools 38.2.5
- pip 9.0.1
- wheel 0.30.0

The same actually happens when using
```
pip install jupyter_client
```
where it uses wheels.

**Comment by benoit-pierre** [comment]
If you're referring to the fact that pytest is installed too, I think this is a bug in the wheel package.

This:
```python
        'test:python_version >= "3.4" or python_version == "2.7"': ['pytest'],
```
get converted to:
```shell
> unzip -p dist/jupyter_client-5.2.0-py2.py3-none-any.whl '*/METADATA' | grep 'pytest;'
Requires-Dist: pytest; python_version >= "3.4" or python_version == "2.7" and extra == 'test'
```

IMHO, the wheel package should automatically parenthesize the original environment marker so the metadata becomes:
```shell
Requires-Dist: pytest; (python_version >= "3.4" or python_version == "2.7") and extra == 'test'
```

And jupyter_client' `setup.py` should also be patched as a workaround:
```diff
--- jupyter_client-5.2.0/setup.py       2017-12-18 13:24:57.000000000 +0100
+++ jupyter_client/setup.py     2017-12-30 15:02:21.711695601 +0100
@@ -86,7 +86,7 @@
     extras_require   = {
         'test': ['ipykernel', 'ipython', 'mock'],
         'test:python_version == "3.3"': ['pytest<3.3.0'],
-        'test:python_version >= "3.4" or python_version == "2.7"': ['pytest'],
+        'test:(python_version >= "3.4" or python_version == "2.7")': ['pytest'],
     },
     cmdclass         = {
         'bdist_egg': bdist_egg if 'bdist_egg' in sys.argv else bdist_egg_disabled,
```

**Comment by FRidh** [comment]
Thanks @benoit-pierre!

cc maintainer of wheel @agronholm 
cc maintainer of jupyter_client @takluyver @minrk @Carreau

**Comment by Carreau** [comment]
Thanks for the ping and tracking that down, I've opened https://github.com/jupyter/jupyter_client/issues/324 to track this, we'll fix this soon (when on a better network) and release a 5.2.1 of Jupyter_client soon.
