### ISSUE TITLE
Extras not getting installed when the package that includes the extras has already been installed

### ISSUE THREAD

**Issue by eeshangarg** [pypa/setuptools#1247]
A [similar issue](https://github.com/pypa/pip/issues/3189) was reported and fixed [here](https://github.com/pypa/pip/pull/3198) for `pip`.

In our case:

1. We have a [repo](https://github.com/zulip/python-zulip-api) with multiple packages in it.
2. We have [the `zulip_bots` package](https://github.com/zulip/python-zulip-api/tree/master/zulip_bots) that [depends on `requests` and `simple_salesforce`](https://github.com/zulip/python-zulip-api/blob/master/zulip_bots/setup.py#L48). `simple_salesforce` further depends on `requests[security]`.
3. [The `zulip_bots` package](https://github.com/zulip/python-zulip-api/tree/master/zulip_bots) also depends on [the `zulip` package in the same repo](https://github.com/zulip/python-zulip-api/tree/master/zulip) which **also** depends on/installs `requests`. So, it is clear that `requests` *does* get installed whether you install `zulip` or `zulip_bots`.
4. We usually use [our provision script](https://github.com/zulip/python-zulip-api/blob/master/tools/provision) to set up a dev env and install the `zulip` and `zulip_bots` packages.
5. But recently, when we ran [this executable (part of the `zulip_bots` package)](https://github.com/zulip/python-zulip-api/blob/master/zulip_bots/setup.py#L38), we ran into:

```.py
pkg_resources.DistributionNotFound: The 'cryptography>=1.3.4; extra == "security"' distribution was not found and is required by requests
```

The above error led us to conclude that for some reason, `requests[security]` was not getting satisfied as expected.

It would mean a lot to us if someone could please shed some light on whether this is a manifestation of https://github.com/pypa/pip/issues/3189 and https://github.com/pypa/pip/pull/3198 or simply a quirk in our understanding of how extra dependencies are resolved! Thanks! :)

**Comment by jaraco** [comment]
Since you're using pip to install the packages and since the issue you're experiencing seems to match closely with the reported issue and fix, I think your instinct is right that there's nothing involving setuptools here. Perhaps you should try installing the pip from the repo and see if that addresses your concern, and if not, report an issue with pip.
