### ISSUE TITLE
resource_stream does not work correctly for lib2to3 + pip install -e .

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#1255]
Consider the following module:

```
from pkg_resources import resource_stream

resource_stream(__name__, 'test_data')
```

With the following `setup.py`:

```
setup(

use_2to3=True,
)
```

When `pip install -e .` is run, modules are copied into `build\libXXX`, but `test_data` is not. `pkg_resources` will then attempt to load the resource relative to the module path, but will fail.

**Comment by jaraco** [comment]
Is the `test_data` installed when the package is installed to an environment?

**Comment by jaraco** [comment]
If so, can you create a git repo that replicates the failure?

**Comment by jaraco** [comment]
This issue is stale and also obsolete now that use_2to3 is removed.
