### ISSUE TITLE
_NamespacePath sort bug

### ISSUE THREAD

**Issue by BMaxV** [pypa/setuptools#1269]
Hello,

https://github.com/pypa/setuptools/issues/885

in the past few days I broke my system (Ubuntu 16.04) python with the above bug. I have already fixed my system, but it's really more of a hack than a fix. I don't know what caused it. 

This is what I tried to fix it:

 * the whole apt package remove install reinstall. Didn't work.

 * next step was uninstalling and then tracking down and rm/deleting every version of the related packages, pip, pkg_resources and setuptools that I could find my in my system path.

 * Because I still had everything else, I thought I could run the get-pip.py to get pip back, which surprisingly also didn't work, despite the file being last edited in November 2016 and the above issue was closed earlier, so I assumed whatever fix was devised was in there. It threw the same error anyway, except the trace was pointing to some tmp directory which I assume is where the unpacked contents of get pip go.

## What worked:

* cloning the repos for setuptools and pip

* setuptools' bootstrap.py installing setuptools and pkg_resources

* installing pip manually with the setup.py in the pip repo

The obvious disadvantage is that by installing manually apt is not aware of these packages now. That's the hacky part I'm a bit worried about.

Everything else seems to work perfectly now, so props to the people designing that modularity.

If you kind devs could double check that the get-pip.py is working correctly and maybe that the apt packages install the correct setuptools version with the fix (I think my old one was 20. something), that would be great.

I hope you don't consider this spam. Have a great day!

**Comment by benoit-pierre** [comment]
Why not install to your user site-packages instead? Also, `get-pip` will not update pip/setuptools/wheels if those are already installed.

**Comment by jaraco** [comment]
Thanks for sharing your experience.

I don’t see any actionable info here. In every case I’ve encountered, this issue can be corrected by getting later builds of setuptools and pip and the packages (also in any venv). As a maintainer of namespace packages, I have encountered this issue several times when the package was misconfigured (mixed use of pkgutil and pkg_resources in the same package) or when the package was built on older setuptools.

If you can find a repeatable scenario that happens on the latest setuptools, I can help troubleshoot.
