### ISSUE TITLE
Field in setup.py for where to donate or say thanks

### ISSUE THREAD

**Issue by phildini** [pypa/setuptools#1276]
Hi there! Inspired by https://github.com/feross/thanks, I'm trying to make it easier for 1) users to find information on supporting developers and 2) developers to add thanks/donation information to their packages.

To that end, I have created https://github.com/phildini/thanks, and would love for the data I'm using to not come from a central database `thanks` maintains, but from the packages themselves.

Here is my proposal: add a `thanks_url` and/or `donation_url` to the arguments for `setuptools.setup` where developers can put the place they want to be supported.

If this idea should go somewhere else, I'm happy to move it there; and I recognize that there will be follow-on work in pypa/warehouse. I want to make it clear I'm happy to do the work, but I wanted to "vet" the idea first. Thoughts?

Supporting documents:
https://github.com/phildini/thanks/issues/7
https://github.com/feross/thanks/issues/2
https://github.com/npm/npm/pull/16300

**Comment by jaraco** [comment]
Sounds like a great idea. I support it. The best way to go about it is to define first where and how this information should be presented in metadata. I don't know off the top of my head if there's a formal approval process for new metadata fields or if there a less formal mechanism... but that's where we'd want to start the conversation. @ncoghlan Where should someone go to propose a new metadata field?

Once the new metadata field is approved, then setuptools (and other package build tools) can add support for soliciting and supplying that field.

**Comment by ncoghlan** [comment]
Our current view in PyPA is that this kind of thing should use the existing "Project-URL" metadata field: https://packaging.python.org/specifications/core-metadata/#project-url-multiple-use

What could stand to be improved is the documentation around recommended URL labels within that field, as we had for https://www.python.org/dev/peps/pep-0459/#project-urls.

Changing that would involve:

- a thread on distutils-sig to propose rewording the description of that field to include more examples
- a PR to change the field description
- a PR to update the tutorial at https://packaging.python.org/tutorials/distributing-packages/#setup-args to cover the `project_urls` argument to setup() (along with a related PR to update the PyPA sample project)

**Comment by phildini** [comment]
@ncoghlan thanks! I'm going to poke at starting that process.

**Comment by phildini** [comment]
Now that https://github.com/pypa/python-packaging-user-guide/pull/441 is merged and https://packaging.python.org/tutorials/distributing-packages/#project-urls exists, I feel pretty ok closing this issue.
