### ISSUE TITLE
install_data doesn't respect "--prefix"

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#130]
Originally reported by: **iElectric (Bitbucket: [iElectric](http://bitbucket.org/iElectric), GitHub: Unknown)**

---

Changing following line in https://bitbucket.org/pypa/setuptools/src/735202ca6848d58bc59022f85cde10af64a61a7e/setuptools/command/bdist_egg.py?at=default#cl-155:

```
self.call_command('install_data', force=0, root=None)
```

to 

```
self.call_command('install_data', force=0, root=self.bdist_dir)
```

Makes data installation respect prefix directory

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/130

**Comment by jaraco** [comment]
@jdemeyer: Do you have any comment on @sdh4's concern? Would you be willing to put together a pull request with your patch and the doc updates offered?

**Comment by a1an77** [comment]
From the setup.py help it seems the correct way of handling data files would be using the --install-data option for the install command. The actual bug is then that that parameter is also not honoured since the files listed in the data_files parameter end up in the package even if the option is specified

just tested with version 28.0.0

**Comment by jaraco** [comment]
> What's wrong with putting them relative to sys.prefix as distutils does?

The main problem with allowing `easy_install` to install files other than to a single location is that violates that explicit expectation. `easy_install` was designed to put an egg in a single location such that deleting the egg would readily delete the package (much in the same way that deleting a directory in /Applications on a Mac will uninstall that application). There has been the one long-standing exception that scripts would additionally be installed to `bin`, but even those were wrappers linking to the functionality in the package, such that no meaningful content remains after removing an egg.

I'm happy to allow a package to install arbitrary files to arbitrary directories (perhaps under `$prefix`) but it should be clear that one cannot expect `easy_install` to facilitate the uninstall and that one _must_ use pip (or another tool) to keep track of installed files.

**Comment by kitterma** [comment]
Since it's been a few years, I thought I'd check in and see if setuptools was usable for a project that needs to install man pages and I see it's not.  dstuft's comment from nearly two years ago is exactly right for the problem I have: https://github.com/pypa/setuptools/issues/130#issuecomment-202911425 - I see all these recommendations to use setuptools instead of distutils, but then this basic requirement is still not supported.

**Comment by jdemeyer** [comment]
> I see all these recommendations to use setuptools instead of distutils, but then this basic requirement is still not supported.

Use `pip install` instead to install your project. You can still use `setuptools` inside the `setup.py` script, but `pip` changes some default installation directories such that `data_files` becomes supported just like it was with `distutils`.

**Comment by jaraco** [comment]
I like that. This is in line with the plan to deprecate easy_install and setuptools' mechanisms for installing packages.

I think that means there's no additional work required for this ticket.

**Comment by kitterma** [comment]
Not particularly helpful.

I can use pip to install it myself, but having setup.py install not work is not useful.

I know not everyone cares about things like distribution packaging, but the pip "solution" is useless in that context.

**Comment by jaraco** [comment]
@kitterma What about `setup.py install --single_version_externally_managed`? That's what pip uses.

**Comment by jdemeyer** [comment]
> I know not everyone cares about things like distribution packaging, but the pip "solution" is useless in that context.

What you are trying to do precisely? As @jaraco said, you can always use `setup.py install --single-version-externally-managed --record=/dev/null` which installs projects the same way that `pip` does.

**Comment by kitterma** [comment]
I'm trying to do what dstuft used as an example in https://github.com/pypa/setuptools/issues/130#issuecomment-202911425 - install a man page.  setup.py install --single-version-externally-managed --record=/dev/null works, but is certainly not at all intuitive.  I don't understand why the insistence on deviating from what distutils does in this case, but at least that sort of solves the problem.

Thanks.

**Comment by Alexander-Shukaev** [comment]
Checked again today as well and the issue is still there.  This is ridiculous.  Simply had to `os.path.join` the `sys.prefix` in front of every entry in `data_files` to achieve consistent behavior between all tools.

**Comment by Alexander-Shukaev** [comment]
Another (and perhaps better) possibility is to

```
if __name__ == "__main__":
  try:
    from setuptools     import setup
    opt = '--single-version-externally-managed'
    if not opt in sys.argv:
      try:
        sys.argv.insert(sys.argv.index('install') + 1, opt)
      except ValueError:
        pass
    opt = '--record='
    if not [arg for arg in sys.argv if arg.startswith(opt)]:
      try:
        sys.argv.insert(sys.argv.index('install') + 1, opt + os.devnull)
      except ValueError:
        pass
  except ImportError:
    from distutils.core import setup
  setup(**args)
```

**Comment by Profpatsch** [comment]
Sadly, it looks like we are not going to be able to fix our packaging this way, c.f. https://github.com/NixOS/nixpkgs/issues/4968
