### ISSUE TITLE
Test suite failing on wheel tests

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1318]
[Example here](https://travis-ci.org/pypa/setuptools/jobs/362236950#L767)

I can reproduce this locally with master and jumping back to known good commits, so I think maybe some dependency has changed behavior.

**Comment by benoit-pierre** [comment]
I know `metadata.json` was removed from latest `wheel`, that might be it.

**Comment by benoit-pierre** [comment]
Yep, no `metadata.json` starting with wheel 0.31.0.

**Comment by benoit-pierre** [comment]
That and `DESCRIPTION.rst` was dropped too.

**Comment by benoit-pierre** [comment]
Maybe we should drop all extraneous metadata? Only keep:
```
entry_points.txt
PKG-INFO
requires.txt
top_level.txt
zip-safe
```

**Comment by pganssle** [comment]
@benoit-pierre Drop in the test? Or drop from the wheel?

I think we probably should try to include at least the `LICENSE`, but I doubt the extra metadata is doing much harm.

**Comment by benoit-pierre** [comment]
It can be problematic if people start relying on it. My first version of wheel support would use `metadata.json` because it's easier to parse, but it's not always present, even when not using the latest `wheel` package (e.g.: the PyQt5 never included it).
