### ISSUE TITLE
latest setuptools link broken

### ISSUE THREAD

**Issue by exFalso** [pypa/setuptools#1329]
https://pypi.org/simple/setuptools/ -> https://files.pythonhosted.org/packages/20/d7/04a0b689d3035143e2ff288f4b9ee4bf6ed80585cc121c90bfd85a1a8c2e/setuptools-39.0.1-py2.py3-none-any.whl#sha256=8010754433e3211b9cdbbf784b50f30e80bf40fc6b05eb5f865fab83300599b8

404s

**Comment by lgh2** [comment]
The 404s on pythonhosted are a known issue, we are working on fixing it. Please see [here](https://status.python.org/incidents/1y1f44q6srh2) for status updates.

**Comment by pganssle** [comment]
Looks like the central GH ticket for this is: pypa/warehouse#3705

I'm going to close this as this is not a setuptools issue.

Thanks @exFalso for the report and @lgh2 for the quick response!
