### ISSUE TITLE
package_dir and setup.cfg version attr: <foo> mutually exclusive?

### ISSUE THREAD

**Issue by dstufft** [pypa/setuptools#1333]
I was messing around with the new ``setup.cfg`` support for metadata, and it looks like there is a poor interaction with ``package_dir`` and the version field support, specifically if you have a ``setup.cfg`` like:

```
[metadata]
version = attr: foobar.__version__

[options]
package_dir =
    = src
```

You'll get an error trying to import foobar. This is because it simply appends the current directory to ``sys.path`` and then attempts to import the above.

**Comment by pganssle** [comment]
@jmbowman Another one you can look into.

Is it possible that #1358 and #1359 already solve this problem?

**Comment by jmbowman** [comment]
This may be a separate issue, but shouldn't be hard to fix if so; I'll take a look and create a test case for it.
