### ISSUE TITLE
CmdClass and PBR are causing issues.

### ISSUE THREAD

**Issue by AaronV77** [pypa/setuptools#1348]
Hello,

So I have the following setup.py file here:

```python
from setuptools import setup, find_packages
from setuptools.command.install import install
from setuptools.command.develop import develop
import subprocess

class My_Install(install):
    def run(self):
        print("Check-1")
        install.run(self)
        subprocess.run(['python', 'install_plugins.py', 'install'])

class My_Develop(develop):
    def run(self):
        print("Check-2")
        develop.run(self)
        subprocess.run(['python', 'install_plugins.py', 'develop'])

setup( 
    name='Titan',
    version='0.0.0',
    packages = find_packages(exclude=['build', 'docs', 'templates']),
    setup_requires=['pbr', 'pytest-runner'], 
    pbr=True,     
    cmdclass={
        'install': My_Install,
        'develop': My_Develop,
    },
)
```

It is a very simple setup.py, but what I'm trying to do is have scripts run at the end of the setup and they are not running with what I have pasted here. Here is my output.

(Titan) Something-Something:Titan aaron$ python setup.py install
running install
[pbr] Writing ChangeLog
[pbr] Generating ChangeLog
[pbr] ChangeLog complete (0.0s)
[pbr] Generating AUTHORS
[pbr] AUTHORS complete (0.0s)
running build
running build_py
running egg_info
writing quest.egg-info/PKG-INFO
writing dependency_links to quest.egg-info/dependency_links.txt
writing entry points to quest.egg-info/entry_points.txt
writing requirements to quest.egg-info/requires.txt
writing top-level names to quest.egg-info/top_level.txt
writing pbr to quest.egg-info/pbr.json
[pbr] Processing SOURCES.txt
[pbr] In git context, generating filelist from git
warning: no previously-included files found matching '.gitignore'
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.rst'
writing manifest file 'quest.egg-info/SOURCES.txt'
running install_lib
running install_egg_info
removing '/Users/aaron/anaconda3/envs/Titan/lib/python3.6/site-packages/quest-0.0.1.dev4-py3.6.egg-info' (and everything under it)
Copying quest.egg-info to /Users/aaron/anaconda3/envs/Titan/lib/python3.6/site-packages/quest-0.0.1.dev4-py3.6.egg-info
running install_scripts

If I have a setup.py file that doesn't include the "pbr=True" so as the following:

```
from setuptools import setup, find_packages
from setuptools.command.install import install
from setuptools.command.develop import develop
import subprocess

class My_Install(install):
    def run(self):
        print("Check-1")
        install.run(self)
        subprocess.run(['python', 'install_plugins.py', 'install'])

class My_Develop(develop):
    def run(self):
        print("Check-2")
        develop.run(self)
        subprocess.run(['python', 'install_plugins.py', 'develop'])

setup( 
    name='Titan',
    version='0.0.0',
    packages = find_packages(exclude=['build', 'docs', 'templates']),
    setup_requires=['pbr', 'pytest-runner'],    
    cmdclass={
        'install': My_Install,
        'develop': My_Develop,
    },
)
```

Everything seems to run fine, here is my output:

(Titan) Something-Something:Titan aaron$ python setup.py install
running install
Check-1
running build
running build_py
running install_lib
running install_egg_info
running egg_info
writing Titan.egg-info/PKG-INFO
writing dependency_links to Titan.egg-info/dependency_links.txt
writing top-level names to Titan.egg-info/top_level.txt
reading manifest file 'Titan.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.rst'
writing manifest file 'Titan.egg-info/SOURCES.txt'
removing '/Users/aaron/anaconda3/envs/Titan/lib/python3.6/site-packages/Titan-0.0.0-py3.6.egg-info' (and everything under it)
Copying Titan.egg-info to /Users/aaron/anaconda3/envs/Titan/lib/python3.6/site-packages/Titan-0.0.0-py3.6.egg-info
running install_scripts
************** STARTING BUILD FOR PLUGINS **************
running install
running bdist_egg
running egg_info
writing cuahsi_hs.egg-info/PKG-INFO
writing dependency_links to cuahsi_hs.egg-info/dependency_links.txt
writing top-level names to cuahsi_hs.egg-info/top_level.txt
reading manifest file 'cuahsi_hs.egg-info/SOURCES.txt'
writing manifest file 'cuahsi_hs.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.9-x86_64/egg
creating build/bdist.macosx-10.9-x86_64/egg/plugins
copying build/lib/plugins/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/plugins
creating build/bdist.macosx-10.9-x86_64/egg/plugins/cuahsi-hydroshare
copying build/lib/plugins/cuahsi-hydroshare/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/plugins/cuahsi-hydroshare
copying build/lib/plugins/cuahsi-hydroshare/cuahsi-hydroshare.py -> build/bdist.macosx-10.9-x86_64/egg/plugins/cuahsi-hydroshare
copying build/lib/plugins/cuahsi-hydroshare/cuahsi_hs.py -> build/bdist.macosx-10.9-x86_64/egg/plugins/cuahsi-hydroshare
byte-compiling build/bdist.macosx-10.9-x86_64/egg/plugins/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/plugins/cuahsi-hydroshare/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/plugins/cuahsi-hydroshare/cuahsi-hydroshare.py to cuahsi-hydroshare.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/plugins/cuahsi-hydroshare/cuahsi_hs.py to cuahsi_hs.cpython-36.pyc
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying cuahsi_hs.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying cuahsi_hs.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying cuahsi_hs.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying cuahsi_hs.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/cuahsi_hs-0.0.0-py3.6.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing cuahsi_hs-0.0.0-py3.6.egg
Removing /Users/aaron/anaconda3/envs/Titan/lib/python3.6/site-packages/cuahsi_hs-0.0.0-py3.6.egg
Copying cuahsi_hs-0.0.0-py3.6.egg to /Users/aaron/anaconda3/envs/Titan/lib/python3.6/site-packages
cuahsi-hs 0.0.0 is already the active version in easy-install.pth

Installed /Users/aaron/anaconda3/envs/Titan/lib/python3.6/site-packages/cuahsi_hs-0.0.0-py3.6.egg
Processing dependencies for cuahsi-hs==0.0.0
Finished processing dependencies for cuahsi-hs==0.0.0
************** ENDING BUILD FOR PLUGINS **************

Why does including the "pbr=True" not allowing my scripts to run? Am I doing something to oblivious? 

Thanks!

**Comment by benoit-pierre** [comment]
My experience trying to use pbr is that you can't override command classes that are overriden by pbr too, see this [bug report](https://bugs.launchpad.net/pbr/+bug/1300381) for reference.

**Comment by AaronV77** [comment]
Hmmm alright, I found other people trying to do the same thing in their applications, but didn't know if it was actually working. Also didn't know if I was doing a simple mistake.

**Comment by pganssle** [comment]
@benoit-pierre Can we close this issue as a bug in pbr?
