### ISSUE TITLE
bdist_egg doesn't run 2to3 after bdist_egg with python-2.x

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#135]
Originally reported by: **shimizukawa (Bitbucket: [shimizukawa](http://bitbucket.org/shimizukawa), GitHub: [shimizukawa](http://github.com/shimizukawa))**

---

If the source directory have `build/lib` that was created by `python-2.x setup.py bdist_egg`, bdist_egg (and bdist_wheel) with python3 does not invoke 2to3 process.

A similar issue #102 's workaround doesn't work for me.

bdist_egg with python3 generate egg successfully:

```
#!bash

$ cd sphinx-1.2  #or some kind of source that have 2to3
$ rm -Rf build
$ python-3.3 setup.py bdist_egg
...(with 2to3 and generate 2to3ed egg in successfully)...

```

bdist_egg with python2 and python3 generate broken py3-egg:

```
#!bash

$ rm -Rf build
$ python-2.7 setup.py bdist_egg
...(success)...
$ python-3.3 setup.py bdist_egg
...(without 2to3 and generate non-2to3ed egg)...

```

bdist_egg with python3 and python2 generate broken py2-egg:

```
#!bash

$ rm -Rf build
$ python-3.3 setup.py bdist_egg
...(with 2to3 and generate 2to3ed egg in successfully)...
$ python-2.7 setup.py bdist_egg
...(use 2to3ed source to generate egg)...

```

IMO, setuptools should separate `build/lib` directory for 2to3 and non-2to3.

And there are my current workarounds:
1. use different build directory like `setup.py build -b build.py33 bdist_egg`
2. remove build directory before packaging with another python version
3. don't use 2to3
4. don't use bdist_\* (egg, wheel, ...)

FYI: this issue's behavior is confirmed with distribute-0.6.49, setuptools-0.9.8, 1.4.2, 2.1.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/135

**Comment by jaraco** [comment]
This issue is now obsolete. See #1120.
