### ISSUE TITLE
Deprecate requires keyword

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1374]
See pypa/packaging-problems#3

If I understand correctly, at least the `requires` keyword can be safely deprecated, with its functions distributed (for now) to `setup_requires`, `install_requires` and `test_requires` as appropriate.

**Comment by jaraco** [comment]
The `requires` directive is part of [PEP 314](https://www.python.org/dev/peps/pep-0314/) and implemented primarily in distutils/dist.py. My instinct is if we deprecate `requires`, we may also wish to deprecate `obsoletes` and `provides`, as they were implemented at around the same time... although they don't run into the issue of being in conflict with install_requires.

**Comment by smenon8** [comment]
I want to work on this at the Bloomberg PyPa sprint.

**Comment by smenon8** [comment]
Should we create another issue to address `obsoletes` and `provides` params? 
@pganssle @jaraco

**Comment by pganssle** [comment]
Yes, I think that would be prudent. Probably a single issue can handle both of them. Thanks @smenon8!

Though actually I'm not sure if there's a *replacement* for the other two, per se, so it's less straightforward to implement than `requires`.
