### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#1378]
I think we're ready to cut a new release. @jmbowman was working on that, so I'll start with assigning to him, but feel free to hand unassign yourself if it's something that you won't be able to get to soon.

**Comment by jmbowman** [comment]
Sure, I should have time to do that tomorrow.

**Comment by jmbowman** [comment]
39.2.0 has been released: https://pypi.org/project/setuptools/39.2.0/ .  I created #1379 to capture the minor hiccups I encountered in the process.
