### ISSUE TITLE
URL to Visual Studio download is dead

### ISSUE THREAD

**Issue by zooba** [pypa/setuptools#1394]
The url in this message is no longer active:

https://github.com/pypa/setuptools/blob/818ba40529993d8f318fe282bdb8420455dbf926/setuptools/msvc.py#L232-L236

The current best URL is `https://visualstudio.microsoft.com/downloads/` and the title is "Build Tools for Visual Studio"

**Comment by carlajiji** [comment]
Please can you post us an active  url since this one is no longer active ?

**Comment by thorade** [comment]
Maybe this URL is even better?
https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by pganssle** [comment]
@zooba Has the URL changed again?

@thorade I tend to trust Steve on this since he works at Microsoft and I'm assuming he's giving us the official Right Answer (TM)

**Comment by zooba** [comment]
I wasn't actually aware of that page (maybe it's new?). Really just a question of how stable the URL is, and I would expect the downloads one to last longer (and at worst, there are also links to full VS on that page too, in case the build tools ever disappear completely).
