### ISSUE TITLE
`pkg_resources.resource_filename` does not respect PEP 420 namespace packages

### ISSUE THREAD

**Issue by paternal** [pypa/setuptools#1407]
I have the following package, where `foo` is a [PEP 420](https://www.python.org/dev/peps/pep-0420/) namespace package (there is no `foo/__init__.py` file).

~~~shell
$ tree
.
└── foo
    ├── bar.py
    └── data
~~~

I want to get the filename of `foo/data`:

~~~python
>>> import pkg_resources
>>> pkg_resources.resource_filename("foo", "data")
'data'
~~~

The returned value is wrong.

However, if I add an empty `foo/__init__.py` package, I get:

~~~python
>>> import pkg_resources
>>> pkg_resources.resource_filename("foo", "data")
'/home/paternal/foo/data'
~~~

Which is correct.

Expected value: I should get the correct value with PEP 420 namespace packages.

Tested on debian buster, with:
- Python 3.6.5rc1
- setuptools-39.2.0

-- Louis

**Comment by jaraco** [comment]
Probably this isn't going to be fixed. The 'package resource file' functionality of pkg_resources has been superseded by [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources) and [its backport](https://pypi.org/project/importlib_resources/).

I'll welcome patches for pkg_resources to support PEP 420 packages, but I recommend the stdlib implementation now.

Let us know how it goes and good luck!

**Comment by paternal** [comment]
I did not know about `importlib.resources`. I will give it a try.

Thanks,
Louis
