### ISSUE TITLE
easy_install from Python 3.7 (Win64) cannot install modules

### ISSUE THREAD

**Issue by P403n1x87** [pypa/setuptools#1409]
When trying to install a module (pycrypto in this case), easy_install fails with the following error (run via Git Bash)

```
$ easy_install pycrypto-2.6.win-amd64-py3.3.exe
Processing pycrypto-2.6.win-amd64-py3.3.exe
error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\<uid>\\AppData\\Local\\Temp\\easy_install-z4dfyyqo\\pycrypto-2.6-py3.7-win32.egg.tmp\\Crypto\\Cipher\\__pycache__\\AES.cpython-33.pyc'

```
The version of easy_install that ships with Python 3.6 works as expected.

**Comment by pganssle** [comment]
@P403n1x87 I think this is specific to your setup, though I'm fairly certain that anything involving `easy_install` is not a supported workflow these days, so you should use `pip` instead.

I also think you want to use `cryptography` instead of `pycrypto`.
