### ISSUE TITLE
setup_requires feature does not handle multiple versions

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#141]
Originally reported by: **marscher (Bitbucket: [marscher](http://bitbucket.org/marscher), GitHub: [marscher](http://github.com/marscher))**

---

This seems somehow related to [issue323 in distribute](https://bitbucket.org/tarek/distribute/issue/323/versionconflict-on-setup_requires).

Why is a not met requirement not simply installed local as an egg and then inserted to path, if it is required via setup_requires?

Scenario:
system wide installation of package A, version 1.0 (which can not be upgraded as non administrative user)
setup_requires=[('A > 1.0')]

Instead of building A > 1.0 before the build process starts, pkg_resources throws a VersionConflict:

```
#!python

 File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 576, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
pkg_resources.VersionConflict: (numpy 1.6.2 (/usr/lib/pymodules/python2.7), Requirement.parse('numpy>=1.8'))

```

Is this behaviour intended? And if that is the case it should be somehow documented, because it is not intuitive.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/141

**Comment by jaraco** [comment]
Based on the changelog and commit history, I believe this was fixed and released in 19.4.
