### ISSUE TITLE
Use six to determine Python version wherever possible

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1415]
This issue came up in #1413 - there are a number of places in `setuptools` and `pkg_resources` where we check `sys.version.major`, which is apparently not portable to Jython 2.7.0. While I don't think we have to go out  of our way to support Jython 2.7.0, I think that given that we use `six` in many other places for its compatibility shim, we should also use `six.PY2` and `six.PY3` to determine whether we're in Python 2 or Python 3. We can assume that `six` will do a better job than us at handling edge cases in general for the parts of 2/3 compatibility that they support.

**Comment by carlajiji** [comment]
I did it but i've got no result.
