### ISSUE TITLE
Support find_packages_ns from setup.cfg

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1419]
Now that #1312 has been merged, closing #97, we support the `find_packages_ns` function in `setup.py`. We should also enable this functionality in `setup.cfg`.

I suggest adding a `find_namespace:` directive. The current `find:` directive is implemented [here](https://github.com/pypa/setuptools/blob/cca86c7f1d4040834c3265ccecdd9e21b4036df5/setuptools/config.py#L512), so I think that would probably be the place to add support for  namespace packages.

Brought to my attention by @agronholm  in https://github.com/pypa/setuptools/issues/97#issuecomment-404195899

**Comment by silkentrance** [comment]
I can create a PR for this as well if you like.
