### ISSUE TITLE
Deprecation warnings with Python3.6 

### ISSUE THREAD

**Issue by winash12** [pypa/setuptools#1426]
I am getting these errors with Python3.6 on Ubuntu 18.04
Are they OK or there is a version mismatch ? 
/usr/local/lib/python3.6/dist-packages/setuptools-40.0.0-py3.6.egg/pkg_resources/_vendor/appdirs.py:130: DeprecationWarning: invalid escape sequence \D
/usr/local/lib/python3.6/dist-packages/setuptools-40.0.0-py3.6.egg/pkg_resources/_vendor/appdirs.py:235: DeprecationWarning: invalid escape sequence \P
/usr/local/lib/python3.6/dist-packages/setuptools-40.0.0-py3.6.egg/pkg_resources/_vendor/appdirs.py:130: DeprecationWarning: invalid escape sequence \D
/usr/local/lib/python3.6/dist-packages/setuptools-40.0.0-py3.6.egg/pkg_resources/_vendor/appdirs.py:235: DeprecationWarning: invalid escape sequence \P
/usr/local/lib/python3.6/dist-packages/setuptools-40.0.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:147: DeprecationWarning: invalid escape sequence \d
/usr/local/lib/python3.6/dist-packages/setuptools-40.0.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:832: DeprecationWarning: invalid escape sequence \d
/usr/local/lib/python3.6/dist-packages/setuptools-40.0.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:2736: DeprecationWarning: invalid escape sequence \d
/usr/local/lib/python3.6/dist-packages/setuptools-40.0.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:2914: DeprecationWarning: invalid escape sequence \g
/usr/local/lib/python3.6/dist-packages/setuptools-40.0.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:147: DeprecationWarning: invalid escape sequence \d
/usr/local/lib/python3.6/dist-packages/setuptools-40.0.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:832: DeprecationWarning: invalid escape sequence \d
/usr/local/lib/python3.6/dist-packages/setuptools-40.0.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:2736: DeprecationWarning: invalid escape sequence \d
/usr/local/lib/python3.6/dist-packages/setuptools-40.0.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:2914: DeprecationWarning: invalid escape sequence \g
Traceback (most recent call last)

**Comment by daa** [comment]
Seems that setuptools need to vendor newer versions of at least these packages where deprecation warnings are fixed.

**Comment by winash12** [comment]
@daa What are those packages ?

**Comment by daa** [comment]
``appdirs`` and ``pyparsing``

**Comment by hugovk** [comment]
https://github.com/pypa/setuptools/pull/1450 should fix the PyParsing ones.

**Comment by hugovk** [comment]
I think this can be closed, #1450 and #1451 have been merged.

**Comment by pganssle** [comment]
Still a bunch more warnings running the test suite, but not related to this. Thanks @hugovk for the PR and @winash12 for the report!

**Comment by winash12** [comment]
@pganssle Do I need to reinstall setuptools to remove the warnings ?

**Comment by pganssle** [comment]
@winash12 Yes, but the change is not yet released. The warnings will not be present in `setuptools > 40.0.0`.

**Comment by mpoGIT** [comment]
/lib/python3.7/site-packages/sage/calculus/functional.py:149: DeprecationWarning: invalid escape sequence \d
