### ISSUE TITLE
find_packages_ns not present in 40.0.0, but added to documentation

### ISSUE THREAD

**Issue by GoelJatin** [pypa/setuptools#1435]
Hi,

I see that the method **find_pacakges_ns** has been added to the documentation for the latest version.

[find_packages_ns](https://setuptools.readthedocs.io/en/latest/setuptools.html#find-packages-ns)

But the code is not included in the 40.0.0 release, although it is part of the **master** branch.

`>>> import setuptools`
`>>>`
`>>> setuptools.__version__`
`'40.0.0'`
`>>>`
`>>>`
`>>> setuptools.find_packages_ns()`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`AttributeError: module 'setuptools' has no attribute 'find_packages_ns'`
`>>>`

[__init__.py - 40.0.0](https://github.com/pypa/setuptools/blob/v40.0.0/setuptools/__init__.py)

[__init__.py - master](https://github.com/pypa/setuptools/blob/master/setuptools/__init__.py)

[find_packages_ns - Line: 121](https://github.com/pypa/setuptools/blob/master/setuptools/__init__.py#L121)

Support for **find_packages_ns** is the latest commit on this branch 19 days ago.

And 40.0.0 was released 14 days ago.

Seems like this commit was missed to be included in the release.

**_-jatin_**

**Comment by pganssle** [comment]
I think the commits were added to a branch before the release and merged into master after it.

We are investigating changing the name, so it's not really prudent to make a new release until those changes are merged.

**Comment by pganssle** [comment]
Sorry, I'll wrap up the PRs related to this this week and make a new release.

**Comment by thebalaa** [comment]
Temporary workaround:
```
from setuptools import setup, PEP420PackageFinder
PEP420PackageFinder().find(include=['foo.*'])
```

**Comment by pganssle** [comment]
With the release of 40.1.0, `find_namespace_packages` is now available. Sorry for the delay y'all.
