### ISSUE TITLE
Custom build step without hooking and replacing

### ISSUE THREAD

**Issue by KOLANICH** [pypa/setuptools#1437]
All the code I have seen in the Net don't add a custom build step, instead they wrap own code around setuptools one. I guess it's not very good. 

Also I wanna add some files, but don't want to pollute the source tree. I mean that the files should be generated as a part of build process, only if the -ackage is built, not on every invocation.

Is there any API to plug my own stage without hooking?
Should we introduce such API, if it is missing?

**Comment by pganssle** [comment]
It's kinda unclear what you are asking for here. I think that the distutils API allows you to override individual build commands and add your own custom build commands. That seems sufficient for any sort of custom code generation step. Can you give a specific example of something you want to be able to do and why you can't do it with the current version of setuptools?

**Comment by KOLANICH** [comment]
There is [a programming language](kaitai-io/kaitai_strucr) transpiled into python. I have created an addon for `setuptools` using entry points transpiling the files when building a package. The problem is that it is executed when `setup` is called (even if the command line doesn't say it to build the package) and puts the compiled files into the tree. Instead it should be executed when wheel creation is started and the transpiled files should be put into the dir used to create a wheel.

**Comment by pganssle** [comment]
@KOLANICH I don't understand why you can't use build commands for this. There is already a very mature plugin system for this. See, for example, [this blog post](https://jichu4n.com/posts/how-to-add-custom-build-steps-and-commands-to-setuppy/). Is there some reason the existing build command infrastructure doesn't work for what you want to do?

**Comment by KOLANICH** [comment]
This is what I meant under `instead they wrap own code around setuptools one`. I wanna writte an extension for setuptools, not a dirty hack (and all the times I encountered this approach it worked extremily glitchy) , so the approach used in the blog post is unsuitable for me. 

I need a better approach, something like

1. I register my extension via entry points mechanism
2. when a package using the registered keyword argumet is built, my extension is activated
3. it is activated in the configurable stage of the pipeline. more precisely, for my addon I need the stage when all the files are already copied into the dir which will be later archived into wheel
4. my code is provided with the path to that folder, to the sdist folder and to the temporary folder used for the building of that wheep which is not to be archived
5. my code + compiler transpile the `ksy`s into python and place them to the folder which  goes into the wheel
6. my code can also add some metadata calling the api injected.
7. the build continues and the files are archived.

**Comment by pganssle** [comment]
I think this can be done by overriding any of the *standard* commands, like `build`, `build_ext` or `build_py`, etc, depending on where in the pipeline you want to inject your extension.

If you are asking for a whole new way of building setuptools extensions, I think we don't have the bandwidth to build and/or maintain such a system, particularly when it is in parallel to the existing system.

**Comment by DylanYoung** [comment]
I think the question is how do authors of packages do this?  How can I create a python module of which any users can simply declare that they're using the package (setup_requires),  possibly with some additional arguments,  and the custom steps are automatically run at the right stage of build, install, develop... 

I tried declaring a command entry_point for install for example and it didn't seem to override the original version...

**Comment by DylanYoung** [comment]
@pganssle  If this isn't currently possible,  I vote to reopen this as it seems pretty essential and would save users of packages a deal of headache.
