### ISSUE TITLE
`pkg_resources` thinks PyQt5 is not installed

### ISSUE THREAD

**Issue by paternal** [pypa/setuptools#1445]
(Not sure who is guilty here: setuptools, pyqt5, debian, or me?)

# Minimum working example

I set up a dummy project for this issue : [paternal/helloworld-qt](https://github.com/paternal/helloworld-qt). Once cloned/downloaded, you can build the debian package by running `make deb` (the package is located in the `dist` directory).

# Problem

I am trying to create a .deb package from a python package which depends on pyqt5. I can create the wheel/sdist package; I can create the .deb package; I can install the .deb package. But when I run the program (installed by the .deb package), I get the following exception:

~~~shell
$ helloworld-qt
Traceback (most recent call last):
  File "/usr/bin/helloworld-qt", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3103, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3087, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3116, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyQt5>=5.10' distribution was not found and is required by helloworld-qt
~~~

However, the [`python3-pyqt5`](https://packages.debian.org/buster/python3-pyqt5) debian package *is* installed:

~~~shell
$ apt-cache policy python3-pyqt5
python3-pyqt5:
  Installed: 5.11.2+dfsg-1
  …
$ python3
Python 3.6.6 (default, Jun 27 2018, 14:44:17) 
[GCC 8.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5
>>> PyQt5.__file__
'/usr/lib/python3/dist-packages/PyQt5/__init__.py'
>>> 
$ ls /usr/lib/python3/dist-packages/PyQt5
__init__.py 
…
~~~

# Explanation (kind of)

(I do not know the internals of `pkg_resources`: I learned everything I am describing here less than two hours ago by reading the `pkg_resources` source code.)

In my repository, there is no script: it is defined by an entrypoint in setup.py:

https://github.com/paternal/helloworld-qt/blob/98936f08c4caa8cd8836d3eca556b45f334181c2/setup.py#L16

So, when creating the wheel package, or creating and installing the debian package, setuptools automatically creates a `/usr/bin/helloworld-qt` binary containing:

~~~python
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'helloworld-qt==1.0.0','gui_scripts','helloworld-qt'
__requires__ = 'helloworld-qt==1.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('helloworld-qt==1.0.0', 'gui_scripts', 'helloworld-qt')()
    )
~~~

When running this script, before launching my actual application, `pkg_resources` first checks that the dependencies are installed (hence the exception message: `pkg_resources.DistributionNotFound: The 'PyQt5>=5.10' distribution was not found and is required by helloworld-qt`).

So `pkg_resources` (wrongly) thinks that pyqt5 is not installed.

I may have managed to pinpoint the function where the pyqt5 is considered, then dropped (I added traces to this file before calling `helloworld-qt`). In [`find_on_path`](https://github.com/pypa/setuptools/blob/e0433cf32dfdf39c0c14a3740c3920c496f09486/pkg_resources/__init__.py#L1938), `PyQt5` is a member of list [`entries`](https://github.com/pypa/setuptools/blob/e0433cf32dfdf39c0c14a3740c3920c496f09486/pkg_resources/__init__.py#L1950), but it is filtered out [a few lines later](https://github.com/pypa/setuptools/blob/e0433cf32dfdf39c0c14a3740c3920c496f09486/pkg_resources/__init__.py#L1955-L1959).

# Question

Once again, you can see a dummy project that illustrates the problem in [helloworld-qt](https://github.com/paternal/helloworld-qt):
* clone or download project;
* build the debian package: `make deb`;
* install the package: `sudo dpkg -i dist/helloworld-qt_1.0.0-1.1_all.deb`;
* run the binary `helloworld-qt`;
* marvel at the exception.

My question is:

* Is this a setuptools bug, which excludes a correctly installed python package?
* Is this a PyQt5 bug, which failed to register itself properly as a python package?
* Is this a Debian bug, which messed up installation of setuptools/pyqt5?
* Is this my fault, who failed to build a valid debian package?

Thanks for your work,
Louis

**Comment by benoit-pierre** [comment]
Probably 2 / 3: PyQt5 only very recently started to provide package metadata when installed from source (see https://www.riverbankcomputing.com/pipermail/pyqt), so distributions' packages don't include it.

**Comment by jrollins** [comment]
I am seeing this exact issue with a debian package of a pyqt5 app that uses an entry_point terminal script.  It's not a 2->3 issue, since the app is purely python3 with python3-pyqt5.  Can we re-open this issue?
