### ISSUE TITLE
easy_install: use --depth 1 with git clone when downloading requirements

### ISSUE THREAD

**Issue by ubunatic** [pypa/setuptools#1446]
Currently, when fetching requirements via `git`, `easy_install` fetches the complete git history. This can take very long for large repos.

To fix this, we can use `--depth 1` when doing `git clone` and subsequently do a `git fetch --depth 1 origin <rev>` to download a specific revision.

I already prepared a [branch](https://github.com/pypa/setuptools/compare/master...ubunatic:shallow-git-clone?expand=1) to fix this, and I am preparing a PR just now (following the PR instructions).

I tested my branch already with a private repo using
- `python3.6 -m easy_install --user -v git+ssh://git@github.com/private/repo.git@master`
- `python3.6 -m easy_install --user -v git+ssh://git@github.com/private/repo.git`

to check the `rev is None` and `rev is not None` code-paths.

**Comment by benoit-pierre** [comment]
`easy_install` is deprecated, use pip. Cloning with `--depth 1` would break `git describe`, which could be problematic in some cases, see [discussion](https://github.com/pypa/pip/issues/2432) on pip's tracker.

**Comment by ubunatic** [comment]
OK. I thought we need to fix this in `pip` and here too. I will close the PR and read how this works in pip.
