### ISSUE TITLE
Clarity around version strings

### ISSUE THREAD

**Issue by dfee** [pypa/setuptools#1449]
I couldn't find any formal documentation for how setuptools interprets `install_requires` versions – and frankly, I'm not clear if setuptools is doing anything with `install_requires` or passing that array along to another tool.

But alas, how is `"six~=1.0` interpreted? Seemingly that means `six >= 1.0, < 2.0`, but consensus on `#python` is that it should mean `six >= 1.0, < 1.1`.

**Comment by benoit-pierre** [comment]
See [PEP 440](https://www.python.org/dev/peps/pep-0440/#version-specifiers).

**Comment by dfee** [comment]
Thanks @benoit-pierre! I definitely searched that PEP before posting this, but missed it.

The word "tilde" only shows up [here](https://www.python.org/dev/peps/pep-0440/#adding-local-version-identifiers): "The plus was chosen instead of a tilde because of the significance of the tilde in Debian's version ordering algorithm.".
