### ISSUE TITLE
Yowsup-master setup.py fails

### ISSUE THREAD

**Issue by Aruloli** [pypa/setuptools#1452]
Hi, I was trying to build and install setup.py from Yowsup-master.   It got built but failed to install with following error. 
Python35\lib\site-packages\setuptools\dist.py:331: UserWarning: Normalizing '0.4.1-2' to '0.4.1.post2'
  normalized_version,
error: Setup script exited with error: [WinError 2] The system cannot find the file specified.
Pl advice me how to go about

**Comment by pganssle** [comment]
This sounds like an issue with Yowsup (googling seems to indicate it's something to do with Whatsapp) rather than with setuptools.

**Comment by Aruloli** [comment]
I am new to yowsup and dont know how to proceed further

**Comment by Aruloli** [comment]
Shall i find from another blog?
