### ISSUE TITLE
Tests broken on master due to missing setuptools.tests.fixtures

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1453]
Not sure what's going on here. I can replicate this locally only after doing `git clean -idx` followed by a new `python boostrap.py`.

**Comment by benoit-pierre** [comment]
I can reproduce the issue. `tox-3.2.1` is the problem, latest successful Travis build was using `3.1.2`.

**Comment by jaraco** [comment]
It's something about the way tox 3.2 creates the venv; because after creating the env, invoking `.tox/python/bin/pytest` manually, replicates the error.

**Comment by pganssle** [comment]
For now we can pin to 3.1.2 (#1454) until we can figure out what's going on.

I'm guessing the issue is that `tox` is starting to test by default against an as-installed version of the packages that it uses, rather than as-seen-by-the-repo-root. Since we don't install the tests, `setuptools.tests.fixtures` shouldn't be importable in that case.

I imagine the solution is to start using some sort of relative imports to pull in the fixtures, or something like that.

**Comment by jaraco** [comment]
This is interesting. The tests only fail if invoked with the console script (`pytest`), but don't fail if invoked by runpy (`python -m pytest`).

**Comment by benoit-pierre** [comment]
I think it's because in the newer tox, pip is called with `python -m pip`, and this result in setuptools being already present in the environment.

**Comment by pganssle** [comment]
@jaraco That strengthens my suspicion. If you invoke `pytest` directly, it deliberately removes the current working directory from your `PYTHONPATH`. `python -m pytest` doesn't do that for whatever reason.

**Comment by benoit-pierre** [comment]
```shell
> ls -d .tox.good/python/lib/python3.7/site-packages/setuptools*                                                                      
.tox.good/python/lib/python3.7/site-packages/setuptools.egg-link
.tox.good/python/lib/python3.7/site-packages/setuptools.pth
> ls -d .tox.bad/python/lib/python3.7/site-packages/setuptools*                                                                                                                                            
.tox.bad/python/lib/python3.7/site-packages/setuptools/
.tox.bad/python/lib/python3.7/site-packages/setuptools.egg-link
.tox.bad/python/lib/python3.7/site-packages/setuptools-39.0.1.dist-info/
.tox.bad/python/lib/python3.7/site-packages/setuptools.pth
```

**Comment by benoit-pierre** [comment]
@pganssle: This is to be expected, no? https://docs.python.org/3/library/sys.html?highlight=sys%20path#sys.path

**Comment by jaraco** [comment]
Similarly the pip uninstall command behaves differently whether invoked by script or runpy:

```
setuptools master $ .tox/python/bin/python -m pip uninstall setuptools
Uninstalling setuptools-40.0.0.post20180811.post-20180811:
  Would remove:
    /Users/jaraco/Dropbox/code/main/setuptools/.tox/python/bin/easy_install
    /Users/jaraco/Dropbox/code/main/setuptools/.tox/python/bin/easy_install-3.7
    /Users/jaraco/Dropbox/code/main/setuptools/.tox/python/lib/python3.7/site-packages/setuptools.egg-link
Proceed (y/n)? ^COperation cancelled by user
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
setuptools master $ .tox/python/bin/pip uninstall setuptools
Uninstalling setuptools-39.0.1:
  Would remove:
    /Users/jaraco/Dropbox/code/main/setuptools/.tox/python/bin/easy_install
    /Users/jaraco/Dropbox/code/main/setuptools/.tox/python/bin/easy_install-3.7
    /Users/jaraco/Dropbox/code/main/setuptools/.tox/python/lib/python3.7/site-packages/easy_install.py
    /Users/jaraco/Dropbox/code/main/setuptools/.tox/python/lib/python3.7/site-packages/pkg_resources/*
    /Users/jaraco/Dropbox/code/main/setuptools/.tox/python/lib/python3.7/site-packages/setuptools-39.0.1.dist-info/*
    /Users/jaraco/Dropbox/code/main/setuptools/.tox/python/lib/python3.7/site-packages/setuptools/*
Proceed (y/n)? ^COperation cancelled by user
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by pganssle** [comment]
I actually think it's a good thing to test against the installed version. I think we should temporarily pin `tox`, then get our house in order so that the tests can be run against an installed version - maybe move `setuptools/tests` to a sibling directory of `setuptools`.

I've had enough bugs in the past that would have been found by testing against the installed version that I prefer to do the tests that way.

**Comment by jaraco** [comment]
I've encountered other issues where testing against a non-development version leads to other problems (such ImportMismatchErrors or other conflicts). My preference would be to continue to test the code as it sits rather than requiring it to go through an install step before each test run (to keep the two copies in sync).

**Comment by benoit-pierre** [comment]
Changing the install/freeze commands is one way to make it work again with newer tox:
```ini
install_command={envbindir}/pip install {opts} {packages}
list_dependencies_command={envbindir}/pip freeze
```

**Comment by jaraco** [comment]
Here's something interesting - after creating a fresh venv, when invoked with runpy, pip doesn't know it has a setuptools installed if the current directory is the working copy.

```
setuptools master $ python -m venv .tox/env
setuptools master $ ls .tox/env/lib/python3.7/site-packages/
__pycache__                 pip                         pkg_resources               setuptools-39.0.1.dist-info
easy_install.py             pip-10.0.1.dist-info        setuptools
setuptools master $ .tox/env/bin/python -m pip uninstall setuptools
Not uninstalling setuptools at /Users/jaraco/Dropbox/code/main/setuptools, outside environment /Users/jaraco/Dropbox/code/main/setuptools/.tox/env
Can't uninstall 'setuptools'. No files were found to uninstall.
```

**Comment by jaraco** [comment]
Relevant is [python issue31874](https://bugs.python.org/issue31874).

**Comment by jaraco** [comment]
If only there were some way to instruct Python not to add the current directory to sys.path. I don't think that's possible, and #1455 may be our best path forward for now.
