### ISSUE TITLE
rpm: -ba: unknown option with setuptools

### ISSUE THREAD

**Issue by ankitbhatia8993** [pypa/setuptools#1456]
Running below command in venv(Python-3.6) 
> python setup.py bdist_rpm

Error logs:
> copying dist/abc-api-0.0.1.tar.gz -> build/bdist.macosx-10.6-intel/rpm/SOURCES
> building RPMs
> rpm -ba --define __python python3 --define _topdir abc-api/build/bdist.macosx-10.6-intel/rpm --clean build/bdist.macosx-10.6-intel/rpm/SPECS/abc-api.spec
> rpm: -ba: unknown option
> error: command 'rpm' failed with exit status 1

Versions:

> Python 3.6.4
> RPM version 4.14.1
> setuptools-40.0.0

This is working for zip packaging but not for RPM. Please check.

Thanks in advance.

**Comment by xrmx** [comment]
I confirm that on my machine a recent rpm version (4.14.2) does not have the -b switch anymore. It looks nowadays rpm packageds are built with rpmbuild which is already supported by python distutils. So installing rpmbuild should make bidst_rpm work.

**Comment by pganssle** [comment]
Thanks for digging into this @xrmx.

@jaraco @benoit-pierre Should we deprecate `bdist_rpm`? It seems to be broken without the `rpmbuild` package.

**Comment by xrmx** [comment]
On debian and brew the rpmbuild command is inside the rpm package, on fedora AFAICT is in a separate package rpm-build. Problem with brew on MacOS is that it gets installed in /usr/local/bin which is not a path searched by CPython distutils code for rpmbuild.

**Comment by benoit-pierre** [comment]
+1 for deprecating.
