### ISSUE TITLE
Can pathlib be used for pkg_resources

### ISSUE THREAD

**Issue by thechief389** [pypa/setuptools#1457]
In Python version 3.4 and higher, there's a new [pathlib module](https://docs.python.org/3/library/pathlib.html) that does things similar to how pkg_resources does it.

This could be a good approach to dropping versions 2 and lower. I could've made a pull request instead, but I made this issue in case someone had any opinions about this.

**Comment by benoit-pierre** [comment]
With [Python 2.7 EOL set to 2020](https://www.python.org/dev/peps/pep-0373/#id2), there's currently no plan to drop support for it.

**Comment by jaraco** [comment]
I'm interested in dropping support for new releases on Python 2.7. I can imagine maintaining support for Python 2.7 in a bugfix-only branch. My main worry would be breaking the expectation that the latest version of setuptools is generally viable in all supported versions. But there are features now that would mitigate that issue -- the `python_version` declaration and PEP 518 support in pip, I'm thinking systems admins and app developers would _still_ be able to install the "latest" version of setuptools, even in Python 2.7, but they would only get the maintenance versions. Presumably the same thing happened for Python 2.6. I'd really like to drop support for Python 2.7 earlier than later if possible.

**Comment by jaraco** [comment]
We might consider revisiting this issue in the future once Python 2.7 is no longer supported (on the latest master branch).
