### ISSUE TITLE
Possibility of having a tar.gz release on pypi?

### ISSUE THREAD

**Issue by aduskett** [pypa/setuptools#1464]
Buildroot automatically handles extracting tarball packages but does not with zip packages.
Would it be possible to upload a tar.gz to pypi?

Thanks!

Adam

**Comment by pganssle** [comment]
IIRC it is no longer possible to upload two source dists, you can only do `tar.gz` *or* `zip`, so we have to choose one or the other. I don't have a strong preference. I think `.zip` has some technical advantages but tarballs are more commonly used.

**Comment by di** [comment]
> IIRC it is no longer possible to upload two source dists [for the same release]

This is correct.
