### ISSUE TITLE
bdist_wheel is not idempotent

### ISSUE THREAD

**Issue by dkamm** [pypa/setuptools#1468]
If I run python setup.py build bdist_wheel twice without changing any files, the resulting wheels have binary differences. This seems a bit unexpected given that other archive tools like tar are idempotent. Is there a reason for this? I tested on python 2 and 3.

**Comment by pganssle** [comment]
In what way are the wheels different?

I'm guessing this is just a "reproducible builds" issue. For the most part, up until fairly recently, I don't think most people cared much about reproducible builds, so things like the [order of a manifest](https://github.com/pypa/setuptools/pull/1305) or including timestamps or other things like that in builds has not been considered important (and there are lots of fiddly differences).

I think there's a low-grade effort by some people to start making the build/packaging stack reproducible, but I think that's a long ways off.

Does `pip wheel` do any better?

**Comment by dkamm** [comment]
It looks like it differs by 1 byte at various offsets.  Here's the output I got from running `cmp -l` on my two wheels:
```
 93656236 102 206
187119801 102 206
342386707 102 207
342386792 102 207
342387062 102 207
342387742 102 207
342387829 102 207
342387984 102 207
342388374 104 211
342400966 102 206
342402960 102 206
342418185 102 207
342418274 102 207
342418364 102 207
342418451 102 207
342418538 102 207
342418617 102 207
342418699 104 211
```
So some sort of fiddly difference makes sense.

I think having reproducible builds usually doesn't matter but I can provide some context for my use case.  I have a large wheel with c extensions that I want to install in a docker image.  I have an `ADD` line in my Dockerfile which adds the wheel to the image. When you have an `ADD` line in a Dockerfile, it will invalidate the cache if the file contents are differ.  So I have to re-run/push that layer and subsequent ones whenever I rebuild the wheel, even if I didn't make any changes to the package.  I have a way to get around it but it would simplify things if the builds were reproducible.  Not sure if this and "it seems like the right thing to do" are reason enough to make the change.

Still get a difference with `pip wheel` as well.

**Comment by Code0x58** [comment]
This issue was also raised in [wheel](https://github.com/pypa/wheel/issues/248). You could do something like `SOURCE_DATE_EPOCH=315532800 python setup.py bdist_wheel` which seems to keep things the same, but the hash will still change if you upgrade your installed version of wheel.

I think those 1 byte differences were zip time fields (comprised of two bytes).

**Comment by benoit-pierre** [comment]
Closing this issue, as this should be addressed by the use of `SOURCE_DATE_EPOCH`.
