### ISSUE TITLE
How to write a plugin with similar functionality to use_2to3=True

### ISSUE THREAD

**Issue by mbarkhau** [pypa/setuptools#1469]
I'm trying to do something very similar to what is triggered by `use_2to3=True`. I've been digging through the setuptools code and would just like to confirm that there is no approved way to do this kind of thing, such as a plugin system?

At this point I think the best thing for me to do is to monkeypatch [command.build_py.build_py.run](https://github.com/pypa/setuptools/blob/master/setuptools/command/build_py.py#L23).

**Comment by daa** [comment]
There is plugin system. Look for ``'distutils.commands'`` and ``'distutils.setup_keywords'`` entry points.

**Comment by mbarkhau** [comment]
Thanks I'll take a look.
