### ISSUE TITLE
setuptools adding hyphen to beginning and ending of version

### ISSUE THREAD

**Issue by jolespin** [pypa/setuptools#1470]
I'm trying to upload my package onto PyPI but it will not work.  It looks like `PyPi` or `setuptools` is adding `-` before and after my version name.  Originally, I had the following version: `ß-2018.8` but I don't think unicode characters work.  I then moved it to `beta-2018.8` but that didn't work either.  I even tried a basic `2018.8` but still the same error?!

Can anyone help me figure out what is happening? 

My pip version:

    pip 18.0 from /Users/mu/anaconda/envs/py3_clone/lib/python3.6/site-packages/pip (python 3.6)

My command:

    python setup.py register sdist upload

My error:

    Submitting dist/thisismypackagename--2018.08-.tar.gz to 

    https://upload.pypi.org/legacy/
    Upload failed (400): '-2018.08-' is an invalid value for Version. Error: Start and end with a letter or numeral containing only ASCII numeric and '.', '_' and '-'. See https://packaging.python.org/specifications/core-metadata
    error: Upload failed (400): '-2018.08-' is an invalid value for Version. Error: Start and end with a letter or numeral containing only ASCII numeric and '.', '_' and '-'. See https://packaging.python.org/specifications/core-metadata

My `__init__.py`:

    # =======
    # Version
    # =======
    __version__="beta-2018.08"

My `setup.py`

    import re
    from setuptools import setup
    
    # Version
    version = None
    with open("./thisismypackagename/__init__.py", "r") as f:
        for line in f.readlines():
            line = line.strip()
            if line.startswith("__version__"):
                version = line.split("=")[-1].strip()
    
    setup(name='thisismypackagename',
          version=version,
          description='package description',
          author='Josh L. Espinoza',
          packages=["thisismypackagename"],
          zip_safe=False)

This is my directory structure:

    thisismypackagename
        | thisismypackagename
        | thisismypackagename | __init__.py
        | setup.py

**Comment by di** [comment]
Your version is literally `"beta-2018.08"` including the quotation marks, which are turned into `-` characters when the version is normalized.

**Comment by jolespin** [comment]
changing it to a float:
`2018.08`
fixed the problem.  thank you.

**Comment by di** [comment]
@jolespin I wouldn't recommend turning it into a float, this might cause problems if you eventually cast it to a string somewhere, e.g.:

```
>>> str(2018.10)
'2018.1'
>>> str(2018.1)
'2018.1'
```

If you really need your version to exist somewhere other than inside of `setup.py`, I'd recommend doing something similar to what `pip` does here: https://github.com/pypa/pip/blob/master/setup.py#L18-L28
