### ISSUE TITLE
pkg_resources/safe_listdir exceptions if a filename is too long.

### ISSUE THREAD

**Issue by bryder** [pypa/setuptools#1472]
We had a bug in some code where the entire python path was added to sys.path
instead of components of the path.

Instead of setuptools ignoring it becuase the directory didn't exist - it exceptioned with:

```
OSError: [Errno 36] File name too long:
```

Here is a santised stack trace (I've replaced our install location and cut out the caller
information).

```
from pkg_resources import resource_stream
File "/some/path/pkg_resources/__init__.py", line 3095, in
@_call_aside
File "/some/path/pkg_resources/__init__.py", line 3079, in callaside
f(*args, **kwargs)
File "/some/path/pkg_resources/__init__.py", line 3108, in initializemaster_working_set
working_set = WorkingSet.buildmaster()
File "/some/path/pkg_resources/__init__.py", line 561, in buildmaster
ws = cls()
File "/some/path/pkg_resources/__init__.py", line 554, in init
self.add_entry(entry)
File "/some/path/pkg_resources/__init__.py", line 610, in add_entry
for dist in find_distributions(entry, True):
File "/some/path/pkg_resources/__init__.py", line 1942, in find_on_path
entries = safe_listdir(path_item)
File "/some/path/pkg_resources/__init__.py", line 2001, in safe_listdir
return os.listdir(path)
OSError: [Errno 36] File name too long:
```

I think safe_listdir should include ```errno.ENAMETOOLONG``` here:

https://github.com/pypa/setuptools/blob/01fd232d95ad51f784de53c0993a7b91868d269d/pkg_resources/__init__.py#L2015

Should I make a pull request for this?

Is it possible to get a 39.2.x release to include it?

**Comment by pganssle** [comment]
@bryder I cannot reproduce this, any way you can come up with a [minimal bug report](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) reproducing this issue?

I tried:

```python
import sys
sys.path.append('A' * 10000)
from pkg_resources import resource_stream
```

No errors so far. A minimal bug report of a PR with a failing test would be great.

**Comment by bryder** [comment]
I'll give that a go this weekend.  Sorry for the late reply!

**Comment by bryder** [comment]
Hi,

I've been going through old tickets and found this. I had completely forgotten about it. 

The problem does not occur with setuptools 50.3.2 so it's no longer a problem.

For the record you can reproduce it by setting the environment variable before starting python. Using sys.path.append will not create the error.

This is with version 44.1.1. 


```bash
/usr/bin/env PYTHONPATH=${PYTHONPATH}:/$(perl -e 'print "A"x5000') python -c 'import pkg_resources' |& grep --before=1 Error
    return os.listdir(path)
OSError: [Errno 36] File name too long: '/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA etc etc etc
```
