### ISSUE TITLE
build_sdist expects only .tar.gz

### ISSUE THREAD

**Issue by gaborbernat** [pypa/setuptools#1473]
PEP 517 requires that build_sdist always generate a .tar.gz file. However, the tool allows the user to pass parameters to the builder, such as with ``{ "--global-option": ["--formats=zip"]}``, causing the emitted file to have a ``.zip`` extension, violating the protocol. https://github.com/pypa/setuptools/blob/d39791489ce78d16e0238f60c429f0be08f4a994/setuptools/build_meta.py#L181

Setuptools' PEP 517 builder should disallow this behavior.

**Comment by serjx86** [comment]
Looking into it...

**Comment by adamRogerson** [comment]
I posed a question about this on the mail list but ask here as well. 

https://mail.python.org/archives/list/distutils-sig@python.org/thread/R6ZVL75MWAR2P6DAXCSV6JZQ7MVBBXU4/

I am unclear what is going wrong  running: (python3 setup.py sdist --formats zip) gives what i would expect to be the desired result.

[setup-tools-tes ~ 04:17] $ python3 setup.py sdist --formats zip
running sdist
running egg_info
writing HelloWorld.egg-info/PKG-INFO
writing dependency_links to HelloWorld.egg-info/dependency_links.txt
writing top-level names to HelloWorld.egg-info/top_level.txt
reading manifest file 'HelloWorld.egg-info/SOURCES.txt'
writing manifest file 'HelloWorld.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst,
README.txt, README.md

running check
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and
maintainer_email) must be supplied

creating HelloWorld-0.1
creating HelloWorld-0.1/HelloWorld.egg-info
copying files to HelloWorld-0.1...
copying setup.py -> HelloWorld-0.1
copying HelloWorld.egg-info/PKG-INFO -> HelloWorld-0.1/HelloWorld.egg-info
copying HelloWorld.egg-info/SOURCES.txt -> HelloWorld-0.1/HelloWorld.egg-info
copying HelloWorld.egg-info/dependency_links.txt -> HelloWorld-0.1/HelloWorld.egg-info
copying HelloWorld.egg-info/top_level.txt -> HelloWorld-0.1/HelloWorld.egg-info
Writing HelloWorld-0.1/setup.cfg
creating 'dist/HelloWorld-0.1.zip' and adding 'HelloWorld-0.1' to it
adding 'HelloWorld-0.1'
adding 'HelloWorld-0.1/HelloWorld.egg-info'
adding 'HelloWorld-0.1/setup.py'
adding 'HelloWorld-0.1/PKG-INFO'
adding 'HelloWorld-0.1/setup.cfg'
adding 'HelloWorld-0.1/HelloWorld.egg-info/SOURCES.txt'
adding 'HelloWorld-0.1/HelloWorld.egg-info/top_level.txt'
adding 'HelloWorld-0.1/HelloWorld.egg-info/dependency_links.txt'
adding 'HelloWorld-0.1/HelloWorld.egg-info/PKG-INFO'
removing 'HelloWorld-0.1' (and everything under it)

[setup-tools-tes ~ 04:17] $ ls dist/
HelloWorld-0.1.zip

**Comment by jaraco** [comment]
@adamRogerson There's nothing wrong with what you've posted. The command you ran is intended to produce a zip file and that's what it did. If you have other expectations, please file a separate ticket and describe what you expected to happen differently.

**Comment by jaraco** [comment]
@gaborbernat The code has changed a lot since this issue was reported... and I see that `--formats gztar` is now hard-coded into the build_sdist command.

https://github.com/pypa/setuptools/blob/297f2adceda3af402fc08311e42505c8cdc9c54b/setuptools/build_meta.py#L211-L214

 I suspect that would cause errors if someone tried to use the `--global-option` to specify a zip. Does that address the issue? I'm assuming yes and closing the issue, but if the issue remains, please reopen and describe how one could replicate it.
