### ISSUE TITLE
PEP 517 interface (build_meta) should not specify setuptools in build dependencies

### ISSUE THREAD

**Issue by uranusjr** [pypa/setuptools#1498]
From pypa/pep517#15.

Quoting @takluyver’s [comment](https://github.com/pypa/pep517/pull/15#issuecomment-422805613):

> I think that what you hit is a bug in the setuptools build backend: I don't think it should be returning the values from build-system.requires at all. The spec says that the get_requires_for_build_* hooks should return:
>
>> an additional list of strings containing PEP 508 dependency specifications, above and beyond those specified in the pyproject.toml file
>
> To me, that means that the backend shouldn't include the build-system.requires values, because the frontend should have already found those before calling the hook.

**Comment by gaborbernat** [comment]
Setuptools at the moment does not have a TOML parser. To resolve this though we would need to vendor one into it though.

**Comment by takluyver** [comment]
I don't think this needs setuptools to parse TOML. The frontend gets the `build-system.requires` from the TOML file and installs those. Then it calls the build system to ask for *additional* build requirements. In setuptools' case, that should be whatever is specified in `setup_requires`.

**Comment by takluyver** [comment]
(Though if setuptools isn't currently reading the TOML file, I must have misunderstood where this issue is coming from)

**Comment by gaborbernat** [comment]
setuptools does not read the file, so always responds with setuptools and wheel. It's hardcoded. To be able to know what additional it needs to specify it would need to do so though.

**Comment by uranusjr** [comment]
What happens if `setup_requires` lists `setuptools` itself? Does setuptools automatically drop it? What happens if the currently-installed setuptools does not match it?

**Comment by SpecLad** [comment]
Wasn't this effectively fixed by #1594? It removed `setuptools` from the list of build dependencies, and while it didn't remove `wheel`, I don't think `wheel` should be removed anyway, as it _is_ a requirement for building wheels.
