### ISSUE TITLE
Python 3.8 urllib.parse.splituser DeprecationWarning

### ISSUE THREAD

**Issue by tirkarthi** [pypa/setuptools#1499]
Using setuptools on CPython master (Python 3.8) generates below warning. Just wanted to give a heads up on this.

Relevant commit : https://github.com/python/cpython/commit/0250de481

```
/home/karthi/requests-html-env/lib/python3.8/site-packages/setuptools/package_index.py:1049: DeprecationWarning: urllib.parse.splituser() is deprecated as of 3.8, use urllib.parse.urlparse() instead
  auth, host = urllib.parse.splituser(netloc)
```

Relevant code : 

https://github.com/pypa/setuptools/blob/e0433cf32dfdf39c0c14a3740c3920c496f09486/setuptools/package_index.py#L1057

Thanks

**Comment by pganssle** [comment]
PR #1501 solves this, but it is blocked on #1501.
