### ISSUE TITLE
PEP 517 backend: get_requires_for_build_wheel shouldn't include setuptools

### ISSUE THREAD

**Issue by pfmoore** [pypa/setuptools#1511]
See https://github.com/pypa/pip/pull/5743#issuecomment-431394680.

As the backend is part of setuptools, it doesn't need to request that setuptools is installed in `get_requires_for_build_wheel`. (And it certainly shouldn't be allowing any version - at a minimum it needs a version that supports the PEP 517 backend, but that's not important as it shouldn't be there in the first place :wink: )

**Comment by pfmoore** [comment]
#1594 created for the fix. I also corrected the same mistake in `get_requires_for_build_sdist`.

**Comment by jaraco** [comment]
Thanks for the patch, @pfmoore . This is releasing as 40.6.3.
