### ISSUE TITLE
Update setup.cfg documentation to include data_files

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1522]
After the implementation of `data_files` support in `setup.cfg` in #1520, we still need to [add it to the documentation](https://github.com/pypa/setuptools/pull/1520#issuecomment-432726077). Specifically, [this table](https://deploy-preview-1520--ecstatic-morse-dada75.netlify.com/setuptools.html#options) should be updated in the following ways:

1. Add a `data_files` row, of type `list-comma`
2. Add an "added in" or "minimum version" column, with `data_files` set to `40.5.0`

Unfortunately I think it's not clear whether the next feature version will be 40.5.0 or 41.0.0, but let's go with 40.5.0 for now and if we decide that there will never be a 40.5.0 release, we'll do a search-and-replace for it.

**Comment by DanGolding** [comment]
Working on this as part of the sprint

**Comment by benoit-pierre** [comment]
Another good first issue: add minimum version fields for other settings.

**Comment by pganssle** [comment]
@benoit-pierre Can you spawn a new issue for that?
