### ISSUE TITLE
Use pip to install packages specified in install_requires; otherwise use easy_install

### ISSUE THREAD

**Issue by thechief389** [pypa/setuptools#1523]
When running `python setup.py install`, easy_install is used to install required dependancies.

This means that you can't install wheels for dependancies. easy_install can only install eggs.

**Comment by benoit-pierre** [comment]
Actually, wheels are supported since 38.2.0, but as `easy_install` is deprecated, please use `pip install .` instead.

**Comment by benoit-pierre** [comment]
What do you mean?

**Comment by thechief389** [comment]
There's a program called [pyconfigure](https://www.gnu.org/software/pyconfigure/) which uses auto tools to build python packages.

**Comment by benoit-pierre** [comment]
No idea, sorry, that's something you'll have to ask the authors/maintainers of pyconfigure.
