### ISSUE TITLE
Document how to use setup.cfg with find_packages and the src layout

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1524]
When trying to create an MWE for #1436, I found it very hard to find the right syntax for using the `src` layout from `setup.cfg`. Here's what I landed on:

```
[options]
package_dir=
 =src
packages=find:
        where=src
```

It would be nice to see this in the documentation somewhere as it's a pretty common layout (and I daresay [probably should be the preferred layout](https://hynek.me/articles/testing-packaging/)).

**Comment by pganssle** [comment]
Hm, actually, I don't know why I thought that was working, it seems to be failing for me now, so this is actually now a two-step ticket:

1. figure out how to create a package with a layout like this:

```
$ tree .
.
├── setup.cfg
├── setup.py
└── src
    ├── mypkg.egg-info
    │   ├── dependency_links.txt
    │   ├── PKG-INFO
    │   ├── SOURCES.txt
    │   └── top_level.txt
    └── pkg
        └── __init__.py
```
 and a `setup.py` like this:

```python
from setuptools import setup

setup()
```

2. Document how to do it.

If it turns out to not be possible, we can turn this into a bugfix ticket.

**Comment by madig** [comment]
I can't get pip/setuptools to install my package if I just use "find:". I have the minimal setup.py you pasted and this setup.cfg:
```
[metadata]
name=xxxyyy
version=0.0.1

[options]
package_dir=
    =src
packages=find:
```
Also an empty `src/xxxyyy/__init__.py`. Pip will install the package metadata fine, but not the actual `xxxyyy/__init__.py` 🤔 I'm using
```
pip        18.1
setuptools 40.5.0
```
Writing `packages=xxxyyy` in setup.cfg works and installs the actual package.

**Comment by madig** [comment]
Got it, setup.cfg must look like this:
```
[metadata]
name=xxxyyy
version=0.0.1

[options]
package_dir=
    =src
packages=find:

[options.packages.find]
where=src
```

**Comment by pganssle** [comment]
Thanks for digging into this @madig!
