### ISSUE TITLE
easy_install warning renders incorrectly

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1525]
The warning at the top of the [easy_install](https://setuptools.readthedocs.io/en/stable/easy_install.html#id6) page is not rendering correctly because the RST is malformed.

Currently [the relevant line](https://github.com/pypa/setuptools/blob/73503dfd7476752d0a0ebffc9a7205ef1b22f751/docs/easy_install.txt#L5) is:

```rst
..warning::
```

But it should be:

```rst
.. warning::
```

(Note the space between the `..` and `warning`).

**Comment by LaimeJesus** [comment]
Hello, can I help you with this one?
