### ISSUE TITLE
Developer's Guide should not refer to ez_setup.py

### ISSUE THREAD

**Issue by robinjhuang** [pypa/setuptools#1540]
While attempting to figure out how to run the test suite, I ran "manual_test.py" in the test directory. This threw an assertion error saying I needed to have setuptools installed from the "dev" distribution.

Documentation here refers to using ez_setup.py to install dev version

https://setuptools.readthedocs.io/en/latest/setuptools.html#installing-setuptools

**Comment by pganssle** [comment]
I think this should be changed to a version that uses `pip`. I am inclined to drop the "install the dev version of setuptools" language and say that setuptools can be installed with `pip install setuptools`.

**Comment by varunkamath18** [comment]
has anyone picked this up yet? I'm interested if this is up for grabs @pganssle

**Comment by Cheukting** [comment]
I tried on it. I think the problem is can we download dev version using pip?

**Comment by varunkamath18** [comment]
Another question to ask is whether there is reason for anyone to use the dev version?

**Comment by pganssle** [comment]
The problem is that `ez_setup.py` is way, waaaay deprecated. I also think that the concept of installing the "dev version" may be outdated. I'm a bit confused as to why this is being recommended anyway, but let's start by replacing it with `pip install`.

If we're adjudicating who does it, @varunkamath18 did comment first, but feel free to work out between you who fixes it.

**Comment by Cheukting** [comment]
Well, @varunkamath18 it's all yours. Give me a shout if you want me to do it :-)

**Comment by varunkamath18** [comment]
I'll take it, thanks!

**Comment by Cheukting** [comment]
Great! Now I can head to the pub ;-)

**Comment by varunkamath18** [comment]
Turns out ez_setup is also referred to [here](https://setuptools.readthedocs.io/en/latest/developer-guide.html). Will include that as a part of the PR.

**Comment by varunkamath18** [comment]
I'm assuming we want to remove that reference too.
