### ISSUE TITLE
html_sidebars with dict deprecated in Sphinx

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1565]
Running `make html` with the latest version of the docs gives the following warning:

> sphinx/builders/html.py:1095: RemovedInSphinx20Warning: Now html_sidebars only allows list of sidebar templates as a value. Support for a string value will be removed at Sphinx-2.0.

This is because we're specifying [html_sidebars](https://github.com/pypa/setuptools/blob/29f9cb087fd107f412e2a2f0df877e3b14a75be9/docs/conf.py#L72) as a `dict`.

We should fix this soon.

**Comment by webknjaz** [comment]
Also mentioned in #1736

**Comment by adamRogerson** [comment]
I had a look at resolving this but it does not seem to be an issue at least on my machine. 
I understand from #1736 tox can enter other packet versions but i am confident its using sphinx 2. 
Is there some other way of running this that would produce the error ? 

> [pip pip 09:36] tox -e docs
> GLOB sdist-make: /root/pip/setup.py
> docs inst-nodeps: /root/pip/.tox/.tmp/package/1/pip-19.2.dev0.zip
> docs installed: alabaster==0.7.12,Babel==2.7.0,certifi==2019.6.16,chardet==3.0.4,docutils==0.14,idna==2.8,imagesize==1.1.0,Jinja2==2.10.1,MarkupSafe==1.1.1,packaging==19.0,pip==19.2.dev0,Pygments==2.4.2,pypa-docs-theme==0.0.1,pyparsing==2.4.0,python-docs-theme==2018.7,pytz==2019.1,requests==2.22.0,setuptools==41.0.1,six==1.12.0,snowballstemmer==1.9.0,Sphinx==2.0.1,sphinxcontrib-applehelp==1.0.1,sphinxcontrib-devhelp==1.0.1,sphinxcontrib-htmlhelp==1.0.2,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.2,sphinxcontrib-serializinghtml==1.1.3,urllib3==1.25.3,wheel==0.33.4
> docs run-test-pre: PYTHONHASHSEED='4186122816'
> docs run-test-pre: commands[0] | python -c 'import shutil, sys; shutil.rmtree(sys.argv[1], ignore_errors=True)' /root/pip/tests/data/common_wheels
> docs run-test-pre: commands[1] | python /root/pip/tools/tox_pip.py wheel -w /root/pip/tests/data/common_wheels -r /root/pip/tools/tests-common_wheels-requirements.txt
> Collecting setuptools>=40.8.0 (from -r tools/tests-common_wheels-requirements.txt (line 8))
>   Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl
>   Saved ./tests/data/common_wheels/setuptools-41.0.1-py2.py3-none-any.whl
> Collecting wheel (from -r tools/tests-common_wheels-requirements.txt (line 9))
>   Using cached https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
>   Saved ./tests/data/common_wheels/wheel-0.33.4-py2.py3-none-any.whl
> Skipping setuptools, due to already being wheel.
> Skipping wheel, due to already being wheel.
> docs run-test: commands[0] | sphinx-build -W -d /root/pip/.tox/docs/tmp/doctrees/html -b html docs/html docs/build/html
> Running Sphinx v2.0.1
> 19.2
> loading intersphinx inventory from https://packaging.python.org/objects.inv...
> loading intersphinx inventory from https://www.pypa.io/en/latest/objects.inv...
> building [mo]: targets for 0 po files that are out of date
> building [html]: targets for 27 source files that are out of date
> updating environment: 27 added, 0 changed, 0 removed
> reading sources... [  3%] cookbook
> reading sources... [  7%] development/configuration
> reading sources... [ 11%] development/contributing
> reading sources... [ 14%] development/getting-started
> reading sources... [ 18%] development/index
> reading sources... [ 22%] development/release-process
> reading sources... [ 25%] development/vendoring-policy
> reading sources... [ 29%] index
> reading sources... [ 33%] installing
> reading sources... [ 37%] logic
> reading sources... [ 40%] news
> reading sources... [ 44%] quickstart
> reading sources... [ 48%] reference/index
> reading sources... [ 51%] reference/pip
> reading sources... [ 55%] reference/pip_check
> reading sources... [ 59%] reference/pip_config
> reading sources... [ 62%] reference/pip_download
> reading sources... [ 66%] reference/pip_freeze
> reading sources... [ 70%] reference/pip_hash
> reading sources... [ 74%] reference/pip_install
> reading sources... [ 77%] reference/pip_list
> reading sources... [ 81%] reference/pip_search
> reading sources... [ 85%] reference/pip_show
> reading sources... [ 88%] reference/pip_uninstall
> reading sources... [ 92%] reference/pip_wheel
> reading sources... [ 96%] usage
> reading sources... [100%] user_guide
> 
> looking for now-outdated files... none found
> pickling environment... done
> checking consistency... done
> preparing documents... done
> writing output... [  3%] cookbook
> writing output... [  7%] development/configuration
> writing output... [ 11%] development/contributing
> writing output... [ 14%] development/getting-started
> writing output... [ 18%] development/index
> writing output... [ 22%] development/release-process
> writing output... [ 25%] development/vendoring-policy
> writing output... [ 29%] index
> writing output... [ 33%] installing
> writing output... [ 37%] logic
> writing output... [ 40%] news
> writing output... [ 44%] quickstart
> writing output... [ 48%] reference/index
> writing output... [ 51%] reference/pip
> writing output... [ 55%] reference/pip_check
> writing output... [ 59%] reference/pip_config
> writing output... [ 62%] reference/pip_download
> writing output... [ 66%] reference/pip_freeze
> writing output... [ 70%] reference/pip_hash
> writing output... [ 74%] reference/pip_install
> writing output... [ 77%] reference/pip_list
> writing output... [ 81%] reference/pip_search
> writing output... [ 85%] reference/pip_show
> writing output... [ 88%] reference/pip_uninstall
> writing output... [ 92%] reference/pip_wheel
> writing output... [ 96%] usage
> writing output... [100%] user_guide
> 
> generating indices...
> writing additional pages... search
> copying static files... done
> copying extra files... done
> dumping search index in English (code: en) ... done
> dumping object inventory... done
> build succeeded.
> 
> The HTML pages are in docs/build/html.
> docs run-test: commands[1] | sphinx-build -W -d /root/pip/.tox/docs/tmp/doctrees/man -b man docs/man docs/build/man -c docs/html
> Running Sphinx v2.0.1
> 19.2
> loading intersphinx inventory from https://packaging.python.org/objects.inv...
> loading intersphinx inventory from https://www.pypa.io/en/latest/objects.inv...
> building [mo]: targets for 0 po files that are out of date
> building [man]: all manpages
> updating environment: 13 added, 0 changed, 0 removed
> reading sources... [  7%] commands/check
> reading sources... [ 15%] commands/config
> reading sources... [ 23%] commands/download
> reading sources... [ 30%] commands/freeze
> reading sources... [ 38%] commands/hash
> reading sources... [ 46%] commands/help
> reading sources... [ 53%] commands/install
> reading sources... [ 61%] commands/list
> reading sources... [ 69%] commands/search
> reading sources... [ 76%] commands/show
> reading sources... [ 84%] commands/uninstall
> reading sources... [ 92%] commands/wheel
> reading sources... [100%] index
> 
> looking for now-outdated files... none found
> pickling environment... done
> checking consistency... done
> writing... pip.1 { } done
> build succeeded.
> 
> The manual pages are in docs/build/man.
> _______________________________________________________ summary _______________________________________________________
>   docs: commands succeeded
>   congratulations :)

**Comment by adamRogerson** [comment]
@pganssle @webknjaz any help on moving this forward would be appreciated.

**Comment by webknjaz** [comment]
If you're looking for requirements, they are here: https://github.com/pypa/setuptools/blob/67344c9/docs/requirements.txt#L1

**Comment by webknjaz** [comment]
@adamRogerson judging from your log, it looks like it's fixed.

cc @pganssle

**Comment by pganssle** [comment]
This is definitely still not fixed, since `html_sidebar` is still using a `dict`. You can see the failure [in this Travis job](https://travis-ci.org/pypa/setuptools/jobs/562311523).

I recommend trying to reproduce it locally with:

```
rm -rf .tox
tox -e docs
```

@adamRogerson It seems that you have a weird dev version of `pip` installed. I can't say I understand exactly why that log seems to succeed with Sphinx >= 2.0, but I'd try with a vanilla Python 3 environment without any dev versions of anything installed.
