### ISSUE TITLE
Cutting a new release

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1585]
I would like to cut a new release on Monday or Tuesday, preferably one that will include #1576.

I think most changes in the changelog are backwards-compatible, so we could do `40.5.0`, but depending on your view, #1554 or #1545 may be considered backwards-incompatible. I'd also like to get #1559 merged, and I consider that a bugfix, but it's possible that people might consider it backwards incompatible. Anyone have thoughts on whether we should do `40.5.0` or `41.0.0`?

Also, is there anything that anyone wants to get prioritized for inclusion in the next release?

**Comment by jaraco** [comment]
I agree that some of those do seem like they _could_ cause incompatibilities. My rule of thumb on when to bump the major version is if the incompatibility is likely to require user intervention to accommodate the change, it should have a major bump and the changelog should describe _what_ intervention is expected. If the likelihood of intervention is negligible, then no docs are needed and no major bump is indicated.

I think #1559 in particular qualifies as backward-incompatible.

**Comment by pganssle** [comment]
I think I will cut a 40.5.0 first, since #1559 is not merged yet. For the record I agree whole-heartedly with that version scheme.
