### ISSUE TITLE
Install from wheel not preserving execute bit on script.

### ISSUE THREAD

**Issue by niall-byrne** [pypa/setuptools#1587]
I have an example setup.py file, where I'm building a bdist that has a script keyword.

When I use pip to install the package, even though the script was set with it's execute bit on during packaging, it's not unpacked with it's execute bit.

```python
import os
import setuptools

# read the contents of your README file
from os import path
this_directory = path.abspath(path.dirname(__file__))
with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    long_description = f.read()

setuptools.setup(
    name="mongomash",
    version="0.0.1",
    author="Niall Byrne",
    author_email="niall.byrne@instant.co",
    description="Mongo Database Manipulation Tool",
    scripts=['bin/mongomash'],
    install_requires=['pymongo==3.7.1'],
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/pypa/sampleproject",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)
```

The script has execute permissions:
```
niall@svs:~/workspace/instant/tooling/mongomash$ ll bin/mongomash
-rwxr-xr-x  1 niall  staff  149 12 Nov 14:25 bin/mongomash
```

The wheel is built with:
```python setup.py bdist_wheel```

And installed with:
```pip3 install mongomash-0.0.1-py3-none-any.whl```

The script file ends up with the following permissions:
```You should consider upgrading via the 'pip install --upgrade pip' command.
[root@localhost]# ll /usr/bin/mongomash
-rw-r--r--. 1 root root 147 Nov 12 20:07 /usr/bin/mongomash
[root@localhost]# ll /bin/mongomash
-rw-r--r--. 1 root root 147 Nov 12 20:07 /bin/mongomash
[root@localhost]#```

**Comment by benoit-pierre** [comment]
Isn't that a pip issue?

**Comment by jaraco** [comment]
The problem (if valid) may exist in a couple of places. It may be that setuptools loses the executable bit on binaries, the `bdist_wheel` command doesn't capture that setting during the zipfile creation, or pip doesn't honor that bit when extracting the wheel.

@niall-byrne Can you help us identify where the problem goes awry and determine if the zip file has an executable bit for that file ([this may help](https://stackoverflow.com/a/39296577/70170))? If it does, then it's definitely a (potential) pip issue.

If not, we can investigate further and see where the executable bit is lost during the creation of a wheel.

**Comment by bsolomon1124** [comment]
Also seeing this exact issue in the case of installing with `-r requirements.txt` where `requirements.txt` specifies a VCS URL:

```
# requirements.txt
git+ssh://git@gitlab.abc.def/team_name/project_name.git@branch-name#egg=project_name
```

In this case, `project_name` looks like:

```
project_name/
  project/
    # python files
  bin/
    my_script
  setup.cfg
```

Above, `my_script` has permission `-rw-r--r--.` with a `#!/usr/bin/env python2.7` shebang.

Additionally, in `setup.cfg`:

```
[install]
prefix = /usr
```

Then, `ls -la /usr/bin/my_script` shows that the execute bits have disappeared, with permission now `-rw-r--r--.`.

**Comment by bsolomon1124** [comment]
**Update**: this seems to have little to do with using a VCS URL.  I see the exact same issue with a 'standard' install:

```bash
# yum install gcc python-devel
# pip install uwsgi
# ls -la /usr/bin/uwsgi
-rw-r--r--. 1 root root 1369984 Jan 28 18:53 /usr/bin/uwsgi
```

**Comment by niall-byrne** [comment]
I can confirm I was using a downloaded wheel from S3 and the same thing was happening.  Let me see if I can check that zip file.

**Comment by bsolomon1124** [comment]
Filed an issue under pip as it was pointed out above that may be the more appropriate place:

> https://github.com/pypa/pip/issues/7666

**Comment by niall-byrne** [comment]
I'm closing this ticket, as the new thread has testing details, and I can't recreate the original scenario any longer.
