### ISSUE TITLE
Question: Where is the code for determining Type and Installer?

### ISSUE THREAD

**Issue by E3V3A** [pypa/setuptools#1593]
I'm digging through your sources trying to understand how the `pip list -q -v` fields labelled as **`Type`** and **`Installer`** is generated, but I can't find it. Here's how it looks:

```bash
# pip list -q -v --outdated

Package      Version       Latest Type  Location                         Installer
------------ ------------- ------ ----- -------------------------------- ---------
binwalk      2.1.2-f31a06c 2.1.0  sdist /usr/lib/python3.6/site-packages
coverage     4.5.1         4.5.2  sdist /usr/lib/python3.6/site-packages pip
cryptography 2.3.1         2.4.1  sdist /usr/lib/python3.6/site-packages
```

**Where are they generated and are these accessible from the `pkg_resources` API?**

PS. Also note the **bug** that latest development version of *binwalk* is wrongly categorized as *outdated*.

**Comment by benoit-pierre** [comment]
FWIU, `Type` is only present when using outdated, and is the type of the latest distribution on PyPI. `Installer` is only filled in by pip, you should be able to get it with something along those lines:
```python
import pkg_resources
for dist in sorted(pkg_resources.working_set.by_key.values()):
    print(dist, 'was installed by',
          next(dist.get_metadata_lines('INSTALLER'), None)
          if dist.has_metadata('INSTALLER') else '???')
```

As for the issue with `binwalk`, `2.1.2-f31a06c` is not a PEP compliant version number, so all bets are off with respect to comparing with other versions.

**Comment by E3V3A** [comment]
@benoit-pierre 

> Installer is only filled in by pip, you should be able to get it with

Great! Thanks for super quick reply!
And how could I also get the `Type`?

> As for the issue with binwalk, 2.1.2-f31a06c is not a PEP compliant version number

I guess this is also related to:
https://github.com/pypa/pip/issues/5828

**Comment by benoit-pierre** [comment]
>  And how could I also get the `Type`?
I don't believe you can: it's not part of the metadata, only present when using `--outdated`, and filled from PyPI by pip. It's not the type of distribution that was used at installation.
