### ISSUE TITLE
should a package refuse to install on platforms not listed in setup.py?

### ISSUE THREAD

**Issue by petersilva** [pypa/setuptools#1602]
I had a package, and I ran it on linux, and it required the xattr.py package.  I then tried to pip install it on windows.  the xattr package tried to build and  failed to install with messages looking like this:

```
build\temp.win-amd64-3.4\Release\build\temp.win-amd64-3.4\Release
     C:\Program Files (x86)\Microsoft Visual Studio 
10.0\VC\BIN\amd64\cl.exe /c /
nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python34\include 
-Ic:\python34\include /Tc
build\temp.win-amd64-3.4\Release\_lib.c 
/Fobuild\temp.win-amd64-3.4\Release\buil
d\temp.win-amd64-3.4\Release\_lib.obj
     _lib.c
     build\temp.win-amd64-3.4\Release\_lib.c(433) : fatal error C1083: 
Cannot ope
n include file: 'sys/xattr.h': No such file or directory
     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 
10.0\\VC\\B
IN\\amd64\\cl.exe' failed with exit stat

```

It now fails on any pip activity because it is constantly trying to set up xattr, but since xattr isn´t installed, uninstall does not work either.  So stuck in an weird state.

If I look at the setup.py for xattr/xattr.py

```
    ...
    platforms=['MacOS X', 'Linux', 'FreeBSD', 'Solaris'],
    ...
```
So my question is, why didn´t distutils notice that this package doesn´t work on windows and refuse to try?

**Comment by petersilva** [comment]
See https://github.com/xattr/xattr/issues/17

**Comment by 29039** [comment]
I just wasted 2 hours trying to get it working only to eventually find this. Guys, would it hurt just to throw an error "xattr is not supported on Windows" to save us the headache

**Comment by abravalheri** [comment]
> I just wasted 2 hours trying to get it working only to eventually find this. Guys, would it hurt just to throw an error "xattr is not supported on Windows" to save us the headache

At this stage setuptools is no longer working as an installer (at least not in a way it is not deprecated). It would make more sense to discuss this in the context of an installer like `pip`.

**Comment by 29039** [comment]
> > I just wasted 2 hours trying to get it working only to eventually find this. Guys, would it hurt just to throw an error "xattr is not supported on Windows" to save us the headache
> 
> At this stage setuptools is no longer working as an installer (at least not in a way it is not deprecated). It would make more sense to discuss this in the context of an installer like `pip`.

It's not the point. There is a lot of out of date info floating around on the internet where we are all trying to go down various rabbit holes looking for answers, so would it hurt you just to put in a little note in there "xattr will fail on windows" just to save someone else from a headache. 

I don't even remember what I was even doing at the time anymore.

**Comment by abravalheri** [comment]
> so would it hurt you just to put in a little note in there \"xattr will fail on windows\" just to save someone else from a headache.

Hi @29039 , please feel free to discuss this idea on https://discuss.python.org/c/packaging/14 as indicated by `@merwok`.

For now, I will close this issue because I think this is not the right forum (`setuptools` does not even run if you are installing the package from wheels).
