### ISSUE TITLE
Test failure in develop on all platforms

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1612]
The CI for [this trivial fix](https://github.com/pypa/setuptools/pull/1611) is failing on all interpreters for Appveyor and Travis. Fails locally as well with this error:

```
_____ [doctest] setuptools.command.develop.VersionlessRequirement __
200 
201     Adapt a pkg_resources.Distribution to simply return the project
202     name as the 'requirement' so that scripts will work across
203     multiple versions.
204 
205     >>> dist = Distribution(project_name='foo', version='1.0')
UNEXPECTED EXCEPTION: NameError("name 'Distribution' is not defined")
Traceback (most recent call last):

  File "~/.pyenv/versions/3.7.1/lib/python3.7/doctest.py", line 1329, in __run
    compileflags, 1), test.globs)

  File "<doctest setuptools.command.develop.VersionlessRequirement[0]>", line 1,
     in <module>

NameError: name 'Distribution' is not defined
```

Seems like it's a doctest failing.

**Comment by pganssle** [comment]
Looks like this commit is the problem: 0902f02d9d68f18e906e727cbafa4a05fe5c9c91, because `Distribution` is no longer in the namespace of the doctest.

**Comment by jaraco** [comment]
Gah. Sorry about that. Thanks for chasing this down. I probably missed that usage because I was relying on the linter for finding the names.

**Comment by pganssle** [comment]
@jaraco No harm no foul, though I think it would be best to go through the motions of a PR next time, even if you just do a self-merge. It's helpful for catching stuff like this.

**Comment by pganssle** [comment]
Closed by #1613

**Comment by jaraco** [comment]
> I think it would be best to go through the motions of a PR next time.

The problem I have with this is it does increase the burden of making a contribution often to the point of making it infeasible in the time allotted. I usually have an implicit, manual check, where I'll notice if tests start failing after pushing a falsely-presumed error-free commit.

I agree with the concept though.

If I could create a command that could automate this operation, I'd be all in favor of it.

I've started looking into using [hub](https://hub.github.com). It looks like it can create a pull request but not set it for merge automatically. It's also not yet clear to me if it can correctly automatically detect the correct fork/branch for the source and target. But if it can, that almost streamlines the process.

**Comment by jaraco** [comment]
I successfully created #1615 from the command-line with a simple `hub pull-request` invocation after pushing the branch. Hmm. Looks like GitHub [doesn't support automatic merges](https://github.com/isaacs/github/issues/586), but there is a [service called mergify](https://mergify.io), which I've enabled on this repo.

It's going to take some work to understand what the implications are of this - can mergify be readily installed on repos? Can it discern which pull requests should be automatically merged (and how)?

**Comment by jaraco** [comment]
I've created a new rule that will automatically merge any PR with the auto-merge tag present. I still see two issues with this workflow. First, it would allow any user to use this feature (I think I can restrict it to a team). Second, it leaves the branch in the remote and local repos, and I don't see a way to mechanize the removal of either... so you'll start to get lots of stale, merged branches.

**Comment by jaraco** [comment]
Huh. For some reason, it seems the `setuptools-developers` team [isn't a team login](https://github.com/pypa/setuptools/runs/45015895). Only a team login is suitable for designating the allowed authors. So I've just set it to jaraco instead. ...until that issue can be sorted out. I've spent way too much time on this already.

**Comment by pganssle** [comment]
> The problem I have with this is it does increase the burden of making a contribution often to the point of making it infeasible in the time allotted. I usually have an implicit, manual check, where I'll notice if tests start failing after pushing a falsely-presumed error-free commit.

Generally I find that my contributions are not time-sensitive, so "make a PR" and "push to master" are roughly equivalent - both put the code on github and since it's very rare for me to not hit the "merge" button before a new release is cut, the effect is about the same. I personally prefer to let my PRs act as "drafts" that I can look at with fresh eyes before the merge if I have time and also that anyone can review.

That said, occasionally my changes are blocking stuff on master (like PR #1613, which was blocking the CI for everyone), so in that situation I can see how the PR workflow would just get in the way (though usually I still need a PR because the stuff blocking on master is almost always something *about the CI itself* that I need to fix).

In any case, everyone has their own way of working, and I don't think there's a single "right way". I think your solution of adding an auto-merge bot that just merges PRs that pass the CI is a great solution. It gives us the quality assurance of CI, the notification mechanism of a PR (I don't think people watching the repo get notifications of pushes to master - I certainly don't), and facilitates your contributions to the project, so it's a win all around! 🎉
