### ISSUE TITLE
namespace_packages and package_dir

### ISSUE THREAD

**Issue by guludo** [pypa/setuptools#1627]
Hello,

I have the following layout for my project:

```
.
├── setup.py
└── src
    └── a
        ├── __init__.py
        └── b
            └── __init__.py
```

Where `a` is a namespace package (with ``__import__('pkg_resources').declare_namespace(__name__)`` in ``a/__init__.py``) and `b` is a regular one.

I have the following in my setup call:

```python
setup(
    ...,
    namespace_packages=['a'],
    package_dir={'': 'src'},
    packages=find_packages(),
    ...
)
```

When I try to call `python setup.py`, I get the following error:

```
error in <my-projects-name> setup command: Distribution contains no modules or packages for namespace package 'a'
```

Is that expected to happen?

Thanks!

**Comment by guludo** [comment]
If I move `src/a` to my project's root directory and remove the `package_dir` keyword, then things work. However, I'd rather have my package source files under `src`.

**Comment by jaraco** [comment]
@guludo I've not tried using 'package_dir' along with namespace packages. There may be a bug there. What is `find_packages()` returning? You need for the value to `packages=` to be the list of packages (`['a', 'a.b']`). If it's not, that's your problem. Perhaps you should be calling `find_packages('src')`?

**Comment by jaraco** [comment]
By the way, if you're looking to do namespace packages and you don't already have packages defined under that namespace, you don't want to use the pkg_resources style, but rather you should use the [pkgutil or native namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages).

**Comment by guludo** [comment]
Hi @jaraco 

`find_packages()` is returning `['a', 'a.b']`. So, is this a bug?

**Comment by guludo** [comment]
Argh, yes. I should've used `find_packages('src')` along with `package_dir={'': 'src'}` (as explained in https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=package_dir#using-find-packages)!

It turns out it has nothing to do with namespace_packages, but rather with me not paying much attention to the docs. Sorry about the noise.

And thanks for the tips regarding the other styles of defining namespace packages!
