### ISSUE TITLE
build_meta breaks some setup.py scripts (e.g. numpy and pygame)

### ISSUE THREAD

**Issue by aimileus** [pypa/setuptools#1628]
Setup:
* Setuptools 40.6.2
* Python 3.7.2

Some build scripts use `sys.argv[0]` to change the working directory to the parent directory of setup.py. For example, the setup.py script of numpy-1.15.4 contains the following code: 

```
src_path = os.path.dirname(os.path.abspath(sys.argv[0]))
old_path = os.getcwd()
os.chdir(src_path)
```

However,`sys.argv[0]` is an empty string, setup.py is called from setuptools.build_meta. Then `os.path.abspath()`, is the working directory and `os.path.dirname()`  its parent directory. This changes the current directory to the parent directory of the current path and breaks relative paths in the setup.py script.

While manually running `python3 setup.py bdist_wheel` succedes, calling `setuptools.build_meta.build_wheel()` in the Python REPL then gives the following error:
```
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/setuptools/build_meta.py", line 158, in build_wheel
    _run_setup()
  File "/usr/local/lib/python3.7/site-packages/setuptools/build_meta.py", line 85, in _run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 403, in <module>
  File "setup.py", line 349, in setup_package
  File "setup.py", line 147, in write_version_py
FileNotFoundError: [Errno 2] No such file or directory: 'numpy/version.py'
``` 

A similar error occurs for pygame-1.9.4. Maybe I overlooked something, but it seems that the problem originates from the way setuptools.build_meta calls setup.py.

**Comment by pganssle** [comment]
I think we can try to fix this in `setuptools.build_meta:__legacy__`, but not in `setuptools.build_meta`.
