### ISSUE TITLE
pyproject.toml should be included in sdist by default

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1632]
An issue came up at work recently where installing [python-daemon](https://pagure.io/python-daemon) with `pip` was hitting the `easy_install` path. I assumed it was because `python-daemon` didn't have a `pyproject.toml`, but it turns out they do - it's just not included in the `Manifest.in`, so it didn't get included in the `sdist`. To verify this I created a super basic example project and it does seem that the default is to exclude `pyproject.toml`.

Given that `pyproject.toml` is one of the most important files to have when executing a build, it should be included in the sdist unless explicitly excluded.

**Comment by daa** [comment]
I think the same issue should be put into Python bugtracker for ``distutils`` to include ``pyproject.toml`` by default.

**Comment by pganssle** [comment]
@daa I think at this point new changes like this are not likely to be accepted in `distutils`, but you are welcome to open an issue. Generally the guidance is to use `setuptools`.

**Comment by uranusjr** [comment]
From [PEP 517](https://www.python.org/dev/peps/pep-0517/):

> ### `build_sdist`
>
> […] A .tar.gz source distribution (sdist) contains a single top-level directory […]. This directory must also contain the pyproject.toml from the build directory, and a PKG-INFO file containing metadata in the format described in PEP 345.

So at least sdists built through `build_meta` must contain pyproject.toml. It is still debatable whether `setup.py sdist` (which is not restricted by PEP 517) should do this by default though.

Should I file a PR to special-case `build_meta.build_sdist`? As it stands Setuptools is not technically compliant to PEP 517.
