### ISSUE TITLE
Start testing installation against pip on master

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1649]
I think the problem in #1644 and possibly the problem in #1642 would have been detected *way* earlier and possibly fixed before a release if we had been testing against master on `pip`. I know `pandas` tests against master on all their dependencies, and that's a reliable source of pre-release bugs for `dateutil`. In `dateutil` I also [test against master for the tzdata repo](https://github.com/dateutil/dateutil/blob/master/tox.ini#L52).

Considering that we have fairly unusual build requirements, we're very likely to be missed in `pip`'s normal testing, so I think it's reasonable for us to run some intermittent tests where we're using the master branch of `pip`, just as an early warning.

I suspect this will be a bit more complicated than other "build against master" type builds, particularly because we need to make sure it's built against master in all the virtualenvs, but if we can do this I think we should.

**Comment by jaraco** [comment]
I'm generally in favor. I think I'd like separate tests for latest stable pip plus pip on master. Whether this should happen as a pytest fixture or possibly as a separate tox env or some other mechanism I'm not yet sure.
