### ISSUE TITLE
`python setup.py install` re-installs dependencies already present.

### ISSUE THREAD

**Issue by stefanseefeld** [pypa/setuptools#1651]
I'm working on a Ubuntu 18.04 platform, with `python3` and `python3-pyqt5` packages installed using the system package manager. (PyQt is installed in `/usr/lib/python3/dist-packages/PyQt5`.)

I'm writing a project `setup.py` file with `install_requires=['PyQt5']`. Running `python3 setup.py install` for some reason doesn't recognize the installed PyQt5 version, and installs it again (from PyPi). Worse, the newly installed PyQt5 version doesn't work, as one of its own prerequisites (`sip`) isn't found.

While the latter might be an issue with the PyQt5 package on PyPi, the former (the fact that `setuptools` ignores the existing `PyQt5` package) is clearly a bug with setuptools itself.

**Comment by benoit-pierre** [comment]
Does the distribution version of PyQt5 include the necessary package metadata? This has historically not been the case.

**Comment by stefanseefeld** [comment]
I do not know, and as an end-user I'd rather prefer `setuptools` to add some heuristics to detect the presence of a (working !) PyQt5 package, even if meta-data are missing.

**Comment by benoit-pierre** [comment]
There's no way for setuptools to know what modules would be part of PyQt5, that's actually part of the information provided by said metadata.

**Comment by benoit-pierre** [comment]
As for checking if the metadata is present, does the package include a `.dist-info` or `.egg-info` directory?

**Comment by stefanseefeld** [comment]
Nope. FWIW, here is more info about the package: https://packages.ubuntu.com/bionic/python3-pyqt5
(in particular the list of files it contains: https://packages.ubuntu.com/bionic/amd64/python3-pyqt5/filelist).

So perhaps some workaround could be designed: setuptools could certainly detect the presence of such a package (just see whether importing it generates an ImportError). And if it is present, **and** the metadata is missing, offer the user to skip the normal (re-)installation of the package from PyPi.

**Comment by benoit-pierre** [comment]
I'm sorry, but no, adding complicated heuristics for this particular case, to fix what is essentially a distribution bug, is not feasible. You'll have to open a bug on the Ubuntu bug tracker.

Also note that even if the metadata was present, distribution like Ubuntu like to morsel some libraries/programs into multiple (distribution) packages, so there's no guarantee that you'd get the same modules as with a PyPI install or full install of PyQt5 from source.
