### ISSUE TITLE
v40.7.1 omits port in index download

### ISSUE THREAD

**Issue by kokoska69** [pypa/setuptools#1663]
In this commit https://github.com/pypa/setuptools/commit/3a351aa00e2110c3b3df0302b1ed6bcf66a1f8d8 is used host instead of netloc, but host does not contain port. Version 40.6.3 works OK.

**Comment by jaraco** [comment]
Sorry about the regression. After re-reading the diff, I can see the issue, which was probably brought on by the naming of 'host' when it meant 'netloc'. Fix should be straightforward.
