### ISSUE TITLE
Include location of bad METADATA files in errors

### ISSUE THREAD

**Issue by pradyunsg** [pypa/setuptools#1664]
`pkg_resources` should probably be including the location of the errant METADATA (e.g. path to the file) in the `ValueError` message to make troubleshooting easier. Maybe someone can file an issue there.

_Originally posted by @cjerdonek in https://github.com/pypa/pip/issues/6194#issuecomment-458878882_

**Comment by cjerdonek** [comment]
By the way, what is the purpose of this repo? https://github.com/pypa/pkg_resources Is it still being used?

**Comment by jaraco** [comment]
> What is the purpose of the pkg_resources repo?

I was planning to extract pkg_resources as a separate package and vendor it in setuptools (#863), but my work stalled on that and that repo is now stale. Presumably it wouldn't take much to merge it with recent changes found authoritatively in the setuptools repo. The one thing I want to avoid is maintaining the functionality in two places, so any transition should be clear-cut.

Instead, I've been focusing my energy on [importlib_resources](https://gitlab.com/python-devs/importlib_resources/), which promises to obviate many if not most of the use-cases of pkg_resources... and is planned to become part of the stdlib in Python 3.8.

Funny (not funny) how my goal not to maintain the functionality in two places led me to just that approach.

**Comment by cjerdonek** [comment]
@zooba had a good suggestion here https://github.com/pypa/pip/issues/6251#issuecomment-463713318 to make a custom type for these errors. That would let callers like pip provide more information to the user without having to expose an exception object or traceback. The exception could have as attributes the expected path of the METADATA file and, if applicable, the name of the attribute being accessed.

**Comment by cjerdonek** [comment]
I posted PR #1706 to address this.
