### ISSUE TITLE
setuptools does not recognize --tag-build for sdist and bdist_wheel

### ISSUE THREAD

**Issue by Sebi2020** [pypa/setuptools#1680]
If you try to tag binary or source distributions setuptools complains "error: option --tag-build not recognized".

According to the documentation this flag should be at least supported by the egg_info and sdist commands.

**Comment by benoit-pierre** [comment]
I can not reproduce the issue with `python setup.py egg_info --tag-build=foo sdist bdist_wheel` (which is how `--tag-build` is used, not as an argument to the `sdist`/`bdist_wheel` commands).
