### ISSUE TITLE
easy_install does not handle -f option correctly with paths containing spaces

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#169]
Originally reported by: **jurko (Bitbucket: [jurko](http://bitbucket.org/jurko), GitHub: [jurko](http://github.com/jurko))**

---

Running `easy_install` using its `-f` option and passing it a folder path containing spaces as in:

```
#!text
easy_install -f "C:\I am a\path containing\spaces" pip
```

does not seem to work. `easy_install` seems to interpret the given string as a space separated sequence of paths.

Using such paths in other locations, e.g. in `--install-dir` or `--download-cache` arguments works fine.

This has been tested using:
- Windows 7 SP1 x64
- CPython `2.4.3`, `2.4.4`, `2.5.4`, `2.6.6`, `2.7.6`, `3.1.3`, `3.2.5`, `3.3.3`, `3.3.5` & `3.4.0` (both 32 & 64-bit versions).
- setuptools `1.4`, `1.4.2`, `3.1`, `3.3`

Hope this helps.

Best regards,
  Jurko Gospodnetić

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/169

**Comment by abravalheri** [comment]
Hello, I suppose we can close this issue now that `easy_install` has been deprecated and widely replace by other installation means, such as `pypa/pip`.

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
