### ISSUE TITLE
Setuptools does not copy package data

### ISSUE THREAD

**Issue by nonatomiclabs** [pypa/setuptools#1691]
Hi,

I can't solve what seems to be a relatively simple problem, I have asked the question [on StackOverflow](https://stackoverflow.com/questions/54653928/copying-top-level-data-files-to-site-packages) but it didn't get interest/answers and I'm sure some of you have the answer.

My project has the following folder structure:

~~~
mypkg/
   -- setup.py
  |
   -- src/
       |
        -- mypkg/
             |
              -- actual source files (.py)
  |
   -- supporting_files/
  |
   -- ...
~~~

I want the `supporting_files` to be copied next to the package's source files after installation.  
In other words, I want to end up with the following folder structure:

~~~
lib/
  |
   -- site-packages/
     |
      -- mypkg/
           |
            -- actual source files (.py)
           |
            -- supporting_files/
~~~

I have tried two things:

- `package_data = {'': ['supporting_files']}`
- `data_files = [('supporting_files', [os.path.join("supporting_files", f) for f in os.listdir("supporting_files")])]`

but none of these did the trick.

To be clear, I have no issue getting the `supporting_files` copied in the egg or the wheel, just copying it at install time doesn't work.

What am I missing here? 😃

----
> I'm running Python 2, if that helps

**Comment by cvanelteren** [comment]
I have a similar issue. Either using `MANIFEST.in` or `package_data` lists the files under `SOURCES.txt` but no files are actually copied. Only when `data_files` are explicitly used.

**Comment by abravalheri** [comment]
Hi @nonatomiclabs and @cvanelteren, `package_data` will only work for files that are placed **inside** the package directory (currently there is no support for files outside of it)

So in your example, the best would be moving `supporting_files` inside `src/mypkg`.

Please also notice that `data_files` is no longer recommended and will not work on `wheel`s.
