### ISSUE TITLE
Move simple constants from setup.py into setup.cfg

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1697]
Currently we specify a lot of string literals in our `setup.py`. We're trying to encourage people to use declarative build configurations wherever possible, so we might as well start off at home move as much as we can over to `setup.cfg`. Should be almost everything that is a simple string literal.

So [in our `setup.py`](https://github.com/pypa/setuptools/blob/master/setup.py#L91), I would say we can move everything *except*:

1. `dependency_links` (Though I actually have no idea why those are in there in the first place)
2. `entry_points`: which dynamically reads the possible commands from some location somewhere.
3. `package_data`: Not sure what is going on with [this](https://github.com/pypa/setuptools/blob/master/setup.py#L71), but it actually seems dangerous for our universal wheels produced on Linux... For now let's leave it alone.

**Comment by hpandeycodeit** [comment]
@pganssle I will work on this
