### ISSUE TITLE
Remove unwritten sections of the documentation

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#1701]
There are apparently [unwritten sections of the documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#subclassing-command).

It looks to me like they only refer to deprecated things, so we can just remove them entirely.

**Comment by DumbMachine** [comment]
Does it involve [this](https://github.com/pypa/setuptools/blob/master/docs/setuptools.txt#L2682) file? If so I can change it.

**Comment by pganssle** [comment]
@DumbMachine Yes. That is the correct file to change.

**Comment by ErikPohl-Lot49-Projects** [comment]
@pganssle @DumbMachine 
Let me know if you are taking it on.  If not, I can.  I'll look through other items to see if there is something else I can attend to!  Thanks!

**Comment by DumbMachine** [comment]
I have made the suggested changes in #1705 . If there's anything else I could help with, please let me know.
