### ISSUE TITLE
get_distribution() will give you wrong version number in a case

### ISSUE THREAD

**Issue by SummerShoohaw** [pypa/setuptools#1711]
`get_distribution()` will return a wrong version number if accidently you are in a directory that has another version of the same package. <br>e.g. say you want to do `get_distribution('my_package')` which is installed in your environment with version 1.0. and you are inside `my_package` source directory and it has version 2.0 (which is not installed), then if you do `get_distribution('my_package')`, it returns 2.0

**Comment by benoit-pierre** [comment]
That's not a bug: that's how the Python path works; if the current directory is part of it, and contains a valid distribution metadata (like an egg-info directory), then that's the active version as far as `pkg_resources` is concerned (because that's the version that will be imported).
