### ISSUE TITLE
README refers to distutils-sig for questions, but isn't discuss.python.org used now?

### ISSUE THREAD

**Issue by JonasT** [pypa/setuptools#1715]
The readme says: `Questions and comments should be directed to the distutils-sig mailing list. Bug reports and especially tested patches may be submitted directly to the bug tracker.` However on the mailing list I can find prodding to move a packaging related to https://discuss.python.org/ instead - which looks like it's taking things over regarding packaging discussions.

So is distutils-sig still used? If not, maybe the readme should be changed!

**Comment by cjerdonek** [comment]
It's still used.
