### ISSUE TITLE
ez_setup.py accepts unused 'delay' parameters in several of its functions

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#173]
Originally reported by: **jurko (Bitbucket: [jurko](http://bitbucket.org/jurko), GitHub: [jurko](http://github.com/jurko))**

---

setuptools project's ez_script.py script contains several functions taking a `delay` or a similar delay-like parameter that effectively gets ignored in the end.
- `download_delay` in `use_setuptools()` --> forwarded to `_do_download()`
- `download_delay` in `_do_download()` --> forwarded to `download_setuptools()`
- `delay` in `download_setuptools()` --> ignored

My suggestion would be to either remove those parameters or at least mark them as deprecated and scheduled for removal in some future setuptools version.

Best regards,
  Jurko Gospodnetić

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/173

**Comment by abravalheri** [comment]
Hello, I think we should be able to close this considering the fact that `ez_setup` has been deprecated and superseded by `pip` (or other mechanisms)...

If anyone would like to reopen this issue, please feel free to comment bellow with more information or other use cases that we might be missing 😄
