### ISSUE TITLE
Decide what to do with the legacy setuptools tracker on bugs.python.org

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#174]
Originally reported by: **ncoghlan (Bitbucket: [ncoghlan](http://bitbucket.org/ncoghlan), GitHub: [ncoghlan](http://github.com/ncoghlan))**

---

MvL pointed out that http://bugs.python.org/setuptools/ is currently still live and needs to be dealt with so people don't get confused about where to report setuptools issues.

@pje pointed out that there is some info on issues there that hasn't yet been replicated in the docs or migrated to this issue tracker, so it likely needs to be reviewed before the instance can be terminated.

MvL suggested making it read-only for the time being. That sounds like a good idea to me, but a better long term resolution is needed.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/174

**Comment by abravalheri** [comment]
It seems that the old bug tracker was disabled and is no longer accessible from the old URL... so time might have solved this issue for us...

I think we can close this issue now, considering that the entire community is already used to the new GitHub system, but if anyone would like to keep it open please feel free to comment here...
