### ISSUE TITLE
"manually" installing setuptools

### ISSUE THREAD

**Issue by pipje2001** [pypa/setuptools#1755]
I am trying to use setuptools inside world of tanks (a game), but it has its own python (2.7.X) and doesn't allow pip, so is it possible to manually install it. So actually not installing it but just calling the needed files independently?

**Comment by benoit-pierre** [comment]
Manually installing setuptools can be done from sources using `python bootstrap.py` and `python setup.py install ..`.  Another alternative would be to add setuptools' source directory to the Python path (after generating the metadata with `python bootstrap.py`). But without more information about world of tanks' embedded Python and how it's managed, there's no way to know if that will work... Sorry, you'll have to investigate yourself.
