### ISSUE TITLE
AssertionError when running "pip install -e ." with no main entry point / no setup() call

### ISSUE THREAD

**Issue by kprzybyla** [pypa/setuptools#1768]
Setup:
- pip 19.0.3 (same error is also present in 19.1.1)
- setuptools 41.0.1

I believe I reproduced the error that was mentioned in https://github.com/pypa/setuptools/issues/1221 while trying to create minimal example for other potential pip / setuptools bug related to PEP 517. The assertion is raised when `setup.py` does not have main entry point definition or/and `setup()` call when calling pip with `--editable` flag:

```python
if __name__ == '__main__':
    ...
```

Having `setup.py` without main entry point is of course wrong but it would be nice to have  better description for that kind of error because right now it's hard to tell what's wrong with the configuration.

Here's how to reproduce the issue:

1. Create new project directory
2. Create `pyproject.toml` inside the project directory with any content (even empty)
3. Create `setup.py` inside the project directory with any content but without main entry point definition (even empty)
4. Execute `pip install -e .` inside the project directory

```python
Running command /home/krprzyby/PycharmProjects/pep517/venv/bin/python /home/krprzyby/PycharmProjects/pep517/venv/lib/python3.7/site-packages/pip-19.0.3-py3.7.egg/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmphz8950lk
    Traceback (most recent call last):
      File "/home/krprzyby/PycharmProjects/pep517/venv/lib/python3.7/site-packages/pip-19.0.3-py3.7.egg/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/home/krprzyby/PycharmProjects/pep517/venv/lib/python3.7/site-packages/pip-19.0.3-py3.7.egg/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/krprzyby/PycharmProjects/pep517/venv/lib/python3.7/site-packages/pip-19.0.3-py3.7.egg/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-1x54qvxt/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 169, in prepare_metadata_for_build_wheel
        assert len(dist_infos) == 1
    AssertionError
```

This is the minimal `setup.py` content that you have to have to get rid of the AssertionError:

```python
from setuptools import setup

if __name__ == '__main__':
    setup()
```

If `setup()` function is not called inside entry point, AssertionError is also raised.

**Comment by benoit-pierre** [comment]
Yes, if you provide a `setup.py`, it's your responsibility to make sure `setuptools.setup` is actually called. From the look of the traces in #1221, I don't think this is a reproducer (you can see `setup` is called).
