### ISSUE TITLE
Install requires using PEP 508 URL reference + environment markers

### ISSUE THREAD

**Issue by zoomorph** [pypa/setuptools#1770]
Using this requirement:
`numpypy@git+ssh://bitbucket.org/pypy/numpy.git; platform_python_implementation == "PyPy"`

Gives the following error:
`'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'platform'"`

Install requires seems to work with URL reference _or_ environment markers, but not when both are combined.

**Comment by benoit-pierre** [comment]
Please provide more info: setuptools version? Sample setup.py? Note that `easy_install` does not support PEP 508 direct URLs, so if you're not using `pip install` this won't work anyway.

**Comment by zoomorph** [comment]
setuptools==41.0.1

Sample setup.py:

```
from setuptools import setup, find_packages

setup(name='test',
      install_requires=['numpypy@git+ssh://bitbucket.org/pypy/numpy.git; platform_python_implementation == "PyPy"'])
```

Error:
`$ python setup.py sdist
error in test setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'platform'"`

**Comment by benoit-pierre** [comment]
You're requirement is not valid: you're missing at least one space between the URL and `;` (see PEP 508 [grammar specification](https://www.python.org/dev/peps/pep-0508/#grammar)):
> url_req       = name wsp* extras? wsp* urlspec wsp+ quoted_marker?

Try:
```python
['numpypy@git+ssh://bitbucket.org/pypy/numpy.git ; platform_python_implementation == "PyPy"']
```

**Comment by zoomorph** [comment]
Ugh you are right. Thank you. -.-
