### ISSUE TITLE
.pypirc/pip.ini location on windows vs distutils

### ISSUE THREAD

**Issue by thebjorn** [pypa/setuptools#1771]
This:
```
python -c "import distutils.dist as dist; import distutils.config as cfg; print(cfg.PyPIRCCommand(dist.Distribution())._get_rc_file())"
```
outputs
```
C:\Users\thebjorn\.pypirc
```
ie. `%USERPROFILE%\.pypirc` and I can only upload to pypi if my credentials are listed here.

However, if I want to add a private repo, i.e.
```
[install]
index-url = https://TOKEN@pypi.fury.io/USERNAME/
```
then this only works when added to `c:\programdata\pip\pip.ini`.

It's a wee bit confusing...

**Comment by benoit-pierre** [comment]
That's 2 different usages, with 2 different programs: `~/.pypirc` is used by the setuptools `upload` command (deprecated) and twine, while `pip.ini` is for configuring pip (and you only did so for the `install` command, so `wheel` will still hit the standard PyPI index).
