### ISSUE TITLE
The 'python_requires' field is ignored in setup.cfg (not in setup.py).

### ISSUE THREAD

**Issue by Steap** [pypa/setuptools#1787]
I'm using setuptools version '41.0.1.post20190616' (commit 8aeff6b2c9a64e47ad2a22533d7e65c08cd4103f). 

$ cd /tmp/setup/py
$ cat setup.py
from setuptools import setup
setup(python_requires='invalid')
$ python setup.py install
error in setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: 'invalid'

$ cd /tmp/setup/cfg
$ cat setup.cfg 
[metadata]
python_requires=invalid
$ python setup.py install
running install
running bdist_egg
running egg_info
writing UNKNOWN.egg-info/PKG-INFO
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing top-level names to UNKNOWN.egg-info/top_level.txt
reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/UNKNOWN-0.0.0-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing UNKNOWN-0.0.0-py3.7.egg
Copying UNKNOWN-0.0.0-py3.7.egg to /tmp/setup/cfg/v/lib/python3.7/site-packages
Adding UNKNOWN 0.0.0 to easy-install.pth file

Installed /tmp/setup/cfg/v/lib/python3.7/site-packages/UNKNOWN-0.0.0-py3.7.egg
Processing dependencies for UNKNOWN==0.0.0
Finished processing dependencies for UNKNOWN==0.0.0
$ echo $?
0

I thing "python setup.py install" should also fail when using setup.cfg.

**Comment by jayvdb** [comment]
https://github.com/pypa/setuptools/issues/999 was about a similar thing, so maybe this is a regression.

**Comment by benoit-pierre** [comment]
Note that `python_requires` belong in the `[options]` section. Still the same issue though.

It's not a regression, but something that should have been taken into account when implementing #999.

**Comment by benoit-pierre** [comment]
Related: #1633.
