### ISSUE TITLE
The post install class (setuptools.command.install) doesn't work in editable mode (pip install -e .)

### ISSUE THREAD

**Issue by prahladyeri** [pypa/setuptools#1789]
I'm [working on a python project](https://github.com/prahladyeri/gar-cron/blob/master/setup.py) that requires custom actions through the post install command as follows:

```python
from setuptools.command.install import install

class PostInstallCommand(install):
	"""Post-installation for installation mode."""
	def run(self):
		install.run(self)
		fpath = os.path.join(self.install_lib, pkg_name)
		fpath = os.path.join(fpath, "cfg.json")
		cfg_dir = os.path.join(os.path.expanduser("~"), ".config/%s" % pkg_name)
		if not os.path.isdir(cfg_dir): os.makedirs(cfg_dir)
		tpath = os.path.join(cfg_dir, "cfg.json")
		shutil.move(fpath, tpath)
```

Now, in order to test this on my local machine, I'm running:

    pip install -e .

However, only the app is installed to my python installation folder after this but the custom actions in `setup.py` aren't firing at all. How do I ensure that post install class is run in this case?

**Comment by mabulgu** [comment]
Hi @prahladyeri. It's been a while, but let me ask you if you tried "develop" command?

Pls refer to this: https://stackoverflow.com/questions/20288711/post-install-script-with-python-setuptools

**Comment by abravalheri** [comment]
I believe that this feature is not planned to be supported by setuptools.

A better forum for discussing post-install hooks would be [Python discourse](https://discuss.python.org/c/packaging/14).
