### ISSUE TITLE
Install ignores altered PREFIX

### ISSUE THREAD

**Issue by limburgher** [pypa/setuptools#1808]
When rebuilding Fedora RPMs for use in flatpaks, PREFIX is changed from /usr to /app.

Most of some Python modules is installed in /app, but parts are still installed in /usr, and I've worked around it my manually moving them. 

Is there something I'm missing, or is this a bug?

**Comment by abravalheri** [comment]
Hi @limburgher, thank you very much for opening this issue.

I believe that lots of things have changed recently, which includes the deprecation of calling `python setup.py` and the fact that now fedora is using some other tooling for packaging/installing Python projects.

Could you confirm if the situation you described is still an issue?
If the rebuilding of RPMs into flatpaks is using `python setup.py`, could you please consider adopt some other tooling (such as https://github.com/pradyunsg/installer)?

**Comment by limburgher** [comment]
I know RPM builds still use setup.py, but I'm no longer actively building flatpaks, so I can't say for sure.
