### ISSUE TITLE
HTTPError: 403 Client Error: Invalid or non-existent authentication information

### ISSUE THREAD

**Issue by chinmayshah99** [pypa/setuptools#1809]
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/ as well as https://test.pypi.org/legacy/
As mentioned in the https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives, there is no need for .pypirc file, but the error still persists. 

```
twine upload --repository-url https://test.pypi.org/legacy/ dist/* --verbose
Enter your username: xxxx
Enter your password:
Uploading distributions to https://test.pypi.org/legacy/
Uploading greedybfs-0.1.0-py2.py3-none-any.whl
100%|██████████████████████████████████████████████████████████████| 7.76k/7.76k [00:00<00:00, 29.0kB/s]
Content received from server:
<html>
 <head>
  <title>403 Invalid or non-existent authentication information.</title>
 </head>
 <body>
  <h1>403 Invalid or non-existent authentication information.</h1>
  Access was denied to this resource.<br/><br/>
Invalid or non-existent authentication information.


 </body>
</html>
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://test.pypi.org/legacy/
```

**Comment by di** [comment]
@chinmayshah99 Can you verify that these credentials work when logging in to https://test.pypi.org? Note that PyPI and TestPyPI are completely separate and require different credentials.

**Comment by chinmayshah99** [comment]
Hey @di, it's working post rebooting my system. weird :)
