### ISSUE TITLE
Automated releases failing

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#1817]
In #1745, I made note of a [build of 41.1](https://travis-ci.org/pypa/setuptools/builds/571329988), which was later seen to fail.

It probably failed because I enabled token-based authentication (42bd00ada0e0f47c2446d6d1b750eb97eba45640).

In the [configparser 3.8.1 release](https://travis-ci.org/jaraco/configparser/builds/570518875), I also use the token with success. So the question is - why did the token not work for setuptools?

**Comment by benoit-pierre** [comment]
Using Travis' PyPI support instead of custom deploy script maybe? Different twine versions (1.13.0 vs master).

**Comment by jaraco** [comment]
In e40a6035, I've reverted the change to use the token. I expect that will work around the issue.
