### ISSUE TITLE
Unzipped egg support - setuptools fails to install from a local folder it itself prepared

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#182]
Originally reported by: **jurko (Bitbucket: [jurko](http://bitbucket.org/jurko), GitHub: [jurko](http://github.com/jurko))**

---

When setuptools is asked to 'download a package into a local folder', e.g. using

```
#!cmd
python -m easy_install --zip-ok --multi-version --always-copy --exclude-scripts --install-dir local_folder
```

it does the following:
1. If the package is not already installed, it downloads the package distribution, prepares a zipped egg distribution from it and stores that in the download folder.
2. If the package is already installed, it simply copies the installed egg into the download folder, which may result in the download folder containing an unzipped egg folder.

In the first case, you can run `easy_install` using the `-f` command-line option to make setuptools install the downloaded package from the download folder without additional downloads from the net. (N.B. The folder must be specified as a local file URL similar to `file:///local_folder/`, including the trailing slash character.)

However, in the second case, setuptools will not recognize the downloaded unzipped egg folder and will complain that the requested package can not be found there.

This can be worked around by manually zipping the unzipped egg folder (under the same name), but it seems wrong that setuptools would construct a download folder it can not later use as an installation source.

Hope this helps.

Best regards,
  Jurko Gospodnetić

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/182

**Comment by abravalheri** [comment]
Hello, I suppose we can close this issue now that `easy_install` has been deprecated and widely replace by other installation means, such as `pypa/pip`.

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
