### ISSUE TITLE
Metadata 2.1 PEP 566 is not present in distutils 

### ISSUE THREAD

**Issue by techtonik** [pypa/setuptools#1845]
Why there are no fields like `Description-Content-Type` from 2.1 metadata in `distutils`?

https://github.com/python/cpython/blob/d8c93aa5d29d3cab537357018d5806a57452a8fe/Lib/distutils/dist.py#L1023

**Comment by pganssle** [comment]
@techtonik `distutils` is part of CPython, not part of `setuptools`. The reason it does not support 2.1 metadata has to do with the fact that for backwards compatibility reasons, `distutils` is mostly frozen in amber and the recommendation is to move to `setuptools`, which is actively supporting the latest metadata.

The eventual goal is to [move `distutils` into `setuptools`](https://github.com/pypa/packaging-problems/issues/127) and out of the standard library.

**Comment by techtonik** [comment]
@pganssle can you add a comment clarifying these things into the `distutils` class above?

**Comment by pganssle** [comment]
@techtonik `distutils` is not part of this project yet, and when it is the comment will be obsolete.  The state of the documentation between the two projects is generally a bit of a mess and an active effort. I think a comment *in the distutils code* is probably just throwing a glass of water into a brushfire so I'm not inclined to take the time to do so.

Feel free to start an issue on bugs.python.org.

**Comment by techtonik** [comment]
@pganssle right now `setuptools` codebase inherits classes from this lib, so making a comment there will increase the chances of that new contributors can understand what is going on.

I don't see where to create an issue on https://bugs.python.org

![image](https://user-images.githubusercontent.com/515889/64437222-95686d00-d0ce-11e9-82c6-aca65bf98d4b.png)

I thought that CPython repository still accepts PRs from proprietary GitHub, and passing a glass of water through https://github.com/python/cpython/blob/master/Lib/distutils/dist.py should not be very complicated. Please.
