### ISSUE TITLE
Files from package not being include on site-packages

### ISSUE THREAD

**Issue by williamjamir** [pypa/setuptools#1852]
I want to include within my package a custom file (C header) inside the `site_packages` folder when my package is installed with pip.

I managed to create the package correctly, I checked the tar.gz file and the C header is contained in the compressed file, but when I execute `pip install`  nothing is placed inside the `site-package` folder.

I have a minimal example with which "this error" can reproduce.
[Link for the sample package](https://github.com/williamjamir/sample_package)
(I'm using Python 3.7 with Windows 10)

The repo from the mentioned example above has the following structure
```console 
|   MANIFEST.in
|   setup.py
+---dist
|       sample-package-0.1.dev0.tar.gz
|
+---sample_package
|   |   cli.py
|   |
|   +---include
|   |       file.h
```

I generated a package with the command  `python setup.py sdist`, the output file `sample-package-0.1.dev0.tar.gz` is created normally and has the following content.
``` console
|   MANIFEST.in
|   PKG-INFO
|   setup.cfg
|   setup.py
|
+---sample_package
|   \---include
|           file.h
|
\---sample_package.egg-info
        dependency_links.txt
        entry_points.txt
        not-zip-safe
        PKG-INFO
        requires.txt
        SOURCES.txt
        top_level.txt
```

But installing the package with pip does not include the `file.h` inside the `site-package` folder.

``` console
>>> pip install dist\sample-package-0.1.dev0.tar.gz
>>> where sample_package
W:\Miniconda\envs\p\Scripts\sample_package.exe
```

The `site_package` has only a folder named `sample_package-0.1.dev0.dist-info\`
and do not contain the header file =/

``` console
ls W:\Miniconda\envs\p\Lib\site-packages\sample_package-0.1.dev0.dist-info\
>>> ls
entry_points.txt  INSTALLER  METADATA  RECORD  top_level.txt  WHEEL
```

I've used `poetry` instead of `setuptools` for a quick test and everything worked fine, the "include" folder with the "C header file" was correctly placed on `site-packages`.

So I'm wondering what I'm doing wrong here since the `sample-package-0.1.dev0.tar.gz` contains the files mentioned from `MANIFEST.in`. I'm missing some config from `setup.py` or some parameter during the build process?

**Comment by maphew** [comment]
Chiming in with a "me too". I have a similar setup. It was working Dec 2017 and isn't now. I haven't tracked down exactly when it stopped working yet, but I'll drop a note here if/when I do.

**Comment by maphew** [comment]
well I found the problem in your sample project if not mine!

Typo in `packages=find_packages(include=["sample-package"])` should be `sample_package` (underscore), plus there needs to be `__init__.py` in sample_package folder. After these 2 changes the folder is created in `PYTHONHOME\lib\site-packages` with pip install, and contains the include file.

**Comment by abravalheri** [comment]
Hi @williamjamir, thank you very much for bringing this issue up.
I tried to find your reproduction repository but I think you have removed it. As some time has passed -- sorry for that 😅 -- I assume you have already solved this issue, so I will go ahead and press the close button 😝.

Please let me know if it still persists, I can re-open the issue and investigate.

---
P.S.: @maphew comment is very relevant, with setuptools you can either use `find_namespace_package` (for implicit namespaces) or you will need a `__init__.py` file in `sample_package/include`
