### ISSUE TITLE
41.4.0 breaks setup.cfg convention

### ISSUE THREAD

**Issue by andyhasit** [pypa/setuptools#1859]
A Jenkins build which worked on Friday fails today, and only thing which has changed is version of setuptools:

Error:

```
setuptools._vendor.packaging.specifiers.InvalidSpecifier: Invalid specifier: '>=2.7
    <3'
```

Excerpt from setup.cfg which worked on Friday:

```
python_requires =
    >=2.7
    <3
```

**Comment by andyhasit** [comment]
Fixed by pure magic:
```
python_requires = >=2.7, <3
```
However I feel this shouldn't have broken...

**Comment by benoit-pierre** [comment]
That's because of #1847. Valid format is: `python_requires = >=2.7,<3`

**Comment by benoit-pierre** [comment]
Your previous multi-line declaration was invalid, and (silently) generated invalid metadata.

**Comment by andyhasit** [comment]
There is still an issue:

This works:
`python_requires = >=3.5,<3`

This doesn't work:
`python_requires = >=3.5,<3.6`

It gives **Invalid specifier: '<3.6**

The docs on cfg files say nothing about this: https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files

These docs suggest I can https://www.python.org/dev/peps/pep-0345/#requires-python

How am I supposed to:

1. Know what the correct syntax is
2. Specify that I want any version of 3.5, but not 3.6?
