### ISSUE TITLE
Entry points require setuptools at runtime

### ISSUE THREAD

**Issue by encukou** [pypa/setuptools#1872]
Consider the following `setup.py` (silly minimal reproducer):
```python
import setuptools

setuptools.setup(
    name = 'print-nl',
    version = '1.0',
    entry_points = {
        'console_scripts': ['print-nl=builtins:print'],
    }
)
```

This generates a command that requires `setuptools`, yet doesn't declare the dependency:
```console
$ print-nl
Traceback (most recent call last):
  File ".../bin/print-nl", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

It isn't clear at all that a fix/workaround for the error about missing `pkg_resources` is to add `setuptools` to `install_requires`. The entry script is, IMO, an implementation detail the user shouldn't care about.

**Comment by pfmoore** [comment]
I'm not entirely clear what is being flagged here, but note that if the project is installed from a wheel using pip, the resulting entry point script does *not* depend on pkg_resources, and in that case a runtime dependency on pkg_resources would be wrong.

**Comment by FRidh** [comment]
Using `pip wheel` to build the wheel (ensure you have `setuptools`) and `pip install` to install the wheel (no need for `setuptools` here) results in a functioning entry point. 

If instead using `wheel unpack` I do not get any entry point, but that is expected. How did you obtain this entry point?

**Comment by pfmoore** [comment]
I'm assuming either `setup.py install` or `pip install` from source, which uses a non-PEP 517 build and so runs `setup.py install` behind the scenes.

The point (as best I can understand it) of this ticket is that it's difficult to know what to do to handle an installer that adds a runtime dependency to a project (that the project can't know about).

Of course, if you do `setup.py install` then you by definition have setuptools already present on the target system. But I think that the RPM build process does something like install to a temporary location, then *copy* the installed files into the RPM for later deployment on a different environment. That's a special case that may need to be handled by the RPM build process (as "copy an installation somewhere else" isn't a typical use case).

**Comment by FRidh** [comment]
Indeed, this uses `setup.py install` or `pip install` which then adds a runtime dependency on `pkg_resources` in case an entry point is used.

In this case I think `setuptools` should *not* be added to `install_requires` because the `import pkg_resources` is generated and is indeed an implementation detail of the build system.

**Comment by FRidh** [comment]
Relevant discussion that led to this ticket https://discuss.python.org/t/build-system-and-undeclared-dependency-on-it-during-runtime

**Comment by jayvdb** [comment]
Avoiding the dependency is best for `setup.py install` due to the very bad performance of `pkg_resources` which does not scale -- its performance gets worse as the size of site-packages increases.  A hack (https://pypi.org/project/fastentrypoints/) to avoid it was noted at https://github.com/pypa/setuptools/issues/510

**Comment by encukou** [comment]
I see. It looks like we are indeed using an unsupported combination tools (which we'll try to improve by moving to pip directly), and the bug isn't in setuptools.

Thanks for your patience here, and sorry for the noise!
