### ISSUE TITLE
allow setuptools plugins to provide setup options when used as setup_requires dependencies or build_requires dependencies

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/setuptools#1873]
Problem: setuptools_scm cant auto-enable by just being part of the build dependencies

Possible Solution: allow build dependencies to trigger setup integration without needing a keyword argument in `setup.py`

inspired by pytest-dev/pytest-forked#26

but in the end i want to be able to drop setup.py and keep setuptools_scm working

**Comment by pganssle** [comment]
I am not entirely sure what this ticket is asking for (minimal examples would *really* help), but I gather that this is related to, or another approach to #1055?

It seems like what you want is for it to be possible for a plugin to be triggered without any keywords specified in `setup()` (which is the same as #1055), and you would like "this plugin is present in one of the setup keys" as a trigger for this.

I think that `setup_requires` is not a good trigger for this kind of thing. I think we'd like to ease people out of using `setup_requires` and into them using the `build-system.requires` key in `pyproject.toml` and even if `setuptools.build_meta` has access to that information, I don't think it's intended to be any kind of configuration for the backends, it seems like a problem with separation of concerns. I much prefer the approach in #1055.

I don't really understand the relevance of the linked ticket, so maybe I've misunderstood the request.

**Comment by RonnyPfannschmidt** [comment]
@pganssle as the plugins are now listed in `build-system.requires` it seems like it might be helpful to pass their details over in some way, 
so to enable the default behaviours of setuptools_scm, one would only have to let it be considered as build requirement

right now even with #1055, users have to touch 2 places to enable the basic default behaviour,
making things a tiny bit harder on users and a tiny bit less friendly

the reference to setup_requires was my mistake

**Comment by pganssle** [comment]
> right now even with #1055, users have to touch 2 places to enable the basic default behaviour,
> making things a tiny bit harder on users and a tiny bit less friendly

Yeah, but "I have a build dependency on this library" and "I want to use this library's hooks" are two different things. It's expected that you'd specify them in two different places. Having hooks enabled by default works well for something like `setuptools_scm`, but works less well for something that offers some build-time hooks but *also* some useful functionality, or build hooks that don't have a reasonable default behavior.

Add to this that the `build-system.requires` function is really intended for use by the *front-end* and not the *back-end* and I am -1 on this change. A good hint that we probably shouldn't be keying features off of its contents is that [backends aren't actually passed that information](https://www.python.org/dev/peps/pep-0517/#build-backend-interface).

I'd rather just move along with #1055 and work to support plugins in the declarative configuration.

**Comment by RonnyPfannschmidt** [comment]
based on the provided details, i agree
