### ISSUE TITLE
Python2 is broken after 41.5.0 [Windows]

### ISSUE THREAD

**Issue by jgsogo** [pypa/setuptools#1891]
In PR #1811 a [non-python2 statement was introduced](https://github.com/pypa/setuptools/pull/1811/files#diff-ebddaa1b649ef567c2534a012ba25913R627) (`encoding` argument is not available in Python2):

```python
with open(state_path, 'rt', encoding='utf-8') as state_file:
```

This breaks any installation in Windows py2 that requires to generate a package

**Comment by jgsogo** [comment]
Yes, it will, that's one of the _classic_ workarounds. I'd submit the PR... but I'm not sure how to add a test for that :S

**Comment by benoit-pierre** [comment]
To clarify, the issue only occurs when building a package with a C extension?

**Comment by benoit-pierre** [comment]
41.5.1 should be available shortly.
