### ISSUE TITLE
TestDepends.testRequire regression in 41.6.0 (py3)

### ISSUE THREAD

**Issue by mgorny** [pypa/setuptools#1896]
While trying to build the new release of setuptools, I get the following test failure:

```
==================================================================== FAILURES =====================================================================
_____________________________________________________________ TestDepends.testRequire _____________________________________________________________

self = <setuptools.tests.test_setuptools.TestDepends object at 0x7fbfae31d710>

    @needs_bytecode
    def testRequire(self):
        req = Require('Json', '1.0.3', 'json')
    
        assert req.name == 'Json'
        assert req.module == 'json'
        assert req.requested_version == '1.0.3'
        assert req.attribute == '__version__'
        assert req.full_name() == 'Json-1.0.3'
    
        from json import __version__
        assert req.get_version() == __version__
        assert req.version_ok('1.0.9')
        assert not req.version_ok('0.9.1')
        assert not req.version_ok('unknown')
    
        assert req.is_present()
        assert req.is_current()
    
        req = Require('Json 3000', '03000', 'json', format=LooseVersion)
        assert req.is_present()
        assert not req.is_current()
        assert not req.version_ok('unknown')
    
        req = Require('Do-what-I-mean', '1.0', 'd-w-i-m')
        assert not req.is_present()
        assert not req.is_current()
    
        req = Require('Tests', None, 'tests', homepage="http://example.com")
        assert req.format is None
        assert req.attribute is None
        assert req.requested_version is None
        assert req.full_name() == 'Tests'
        assert req.homepage == 'http://example.com'
    
        from setuptools.tests import __path__
        paths = [os.path.dirname(p) for p in __path__]
>       assert req.is_present(paths)
E       AssertionError: assert False
E        +  where False = <bound method Require.is_present of <setuptools.depends.Require object at 0x7fbfae0d0b38>>(['/tmp/portage/dev-python/setuptools-41.6.0/work/setuptools-41.6.0-python3_5/setuptools'])
E        +    where <bound method Require.is_present of <setuptools.depends.Require object at 0x7fbfae0d0b38>> = <setuptools.depends.Require object at 0x7fbfae0d0b38>.is_present

setuptools/tests/test_setuptools.py:120: AssertionError
```

I can reproduce it reliably with at least pypy3.6 (7.2.0) & python3.5 (3.5.7). I haven't tested other versions yet.

Full build log: [dev-python:setuptools-41.6.0:20191030-083347.log](https://github.com/pypa/setuptools/files/3787797/dev-python.setuptools-41.6.0.20191030-083347.log)

**Comment by mgorny** [comment]
In 41.5.1 all tests pass.

**Comment by torsava** [comment]
We have the same problem when trying to update to the new release in Fedora.

**Comment by torsava** [comment]
I have checked that `paths` are equivalent on both versions:

Old, 41.5.1:

    DEBUG: __path__ = ['/builddir/build/BUILD/setuptools-41.5.1/setuptools/tests']
    DEBUG: paths = ['/builddir/build/BUILD/setuptools-41.5.1/setuptools']

New, 41.6.0:

    DEBUG: __path__ = ['/builddir/build/BUILD/setuptools-41.6.0/setuptools/tests']
    DEBUG: paths = ['/builddir/build/BUILD/setuptools-41.6.0/setuptools']

Yet the test passes on 41.5.1 and fails on 41.6.0.

**Comment by mimi1vx** [comment]
looks like this part is buggy:

https://github.com/pypa/setuptools/blob/master/setuptools/_imp.py#L22-L24

```
imp.find_module(self.module, paths)
(None, '/home/abuild/rpmbuild/BUILD/setuptools-41.6.0/setuptools/tests', ('', '', 5))
```

but `importlib.findspec(self.module, paths)` returns `None` and throws Importerror

**Comment by jaraco** [comment]
Thank you for this report. I stumbled on this issue today when I tried to remove the `./tests/` directory from the repo. Apparently, the presence of that directory masks this error for the CI runs or other runs from the repo.

**Comment by mgorny** [comment]
For the record, the solution from #1905 works for me and we're (Gentoo) carrying it for a few releases now.

**Comment by jaraco** [comment]
It's somewhat surprising to me that no users complained about this regression. Apparently the test suite is guaranteeing behavior that no one uses.
