### ISSUE TITLE
Setuptools with entry-point

### ISSUE THREAD

**Issue by Sebastiencreoff** [pypa/setuptools#1901]
Hello,

I have a folder with several modules to setup. Each module has the same architecture:

-manager
   -scripts
  - src
  - name of the module
  - tests
  -setup.py
  -MANIFEST.in
-front
   -scripts
  - src
  - name of the module
  - tests
  -setup.py
  -MANIFEST.in

Inside my manager/setup.py, this is what I have:
```python
setup(
    name="manager",
    version=FINAL_VERSION,
    packages=find_packages(exclude=['tests']),
    author='Me',
    author_email='my_email',
    description="my description ",
    include_package_data=True,
    data_files=[
        ('share/my_module/scripts', [
            'scripts/my_scripts',
        ])
    ],
    entry_points={
        'console_scripts': [
            'manager=src.manager.main:main',
            'manager-worker=src.manager.worker:main',
        ]
    },
    install_requires=[
        'setuptools',
        'circus==0.15.0',
        'futures==3.0.5',
        'ipython==5.8.0',
    ],
    tests_require=[
        'pytest==3.6.3'
    ],
    extras_require={
        'shell': ['ipython']
    },
)
```

It is nearly the same file for front module.

The issue that I have is when I try to launch one of my console-script, for example, manager. It is has if setuptools is trying to find the folder path in front module instead of manager.

Python used: 2.7
setuptools: 41.6.0

Thanks

**Comment by abravalheri** [comment]
Hi @Sebastiencreoff, thank you very much for reporting this problem.

I don't fully understand the error here... Would it be possible for you to provide the error logs (and maybe a simple git repository with code that replicates what you are trying to do, in a simplified way)?

**Comment by abravalheri** [comment]
Please also notice Python 2.7 is no longer supported.

**Comment by abravalheri** [comment]
Hi @Sebastiencreoff, I think I will go ahead and close this issue for now, but please let us know if you have any other information about the problem.
