### ISSUE TITLE
include_dirs should come after setup_require

### ISSUE THREAD

**Issue by Didou09** [pypa/setuptools#1910]
When creating a pip sdist for a library that uses cython and numpy, one needs to configure the setup with:

```
setup_requires=['numpy', 'cython']
include_dirs=[numpy.get_include()]
```
But this means that numpy has to be imported in the setup.py.
This means that a user installing the library **would have to install numpy before running the pip install**.
Which breaks down the whole idea of pip and setup automatically handling the dependencies and of the install being possible from a fresh clean environment.

Any way that setuptools would **force install of numpy (and all setup_requires dependencies) prior to calling include_dirs ?**
This could be done by allowing a **function** (instead of a str) to be passed to include_dirs ?

So far there seem to be only hacky ways to go around this:

https://stackoverflow.com/questions/19919905/how-to-bootstrap-numpy-installation-in-setup-py/21621689#21621689

https://stackoverflow.com/questions/54117786/add-numpy-get-include-argument-to-setuptools-without-preinstalled-numpy

https://stackoverflow.com/questions/21605927/why-doesnt-setup-requires-work-properly-for-numpy/21621493#21621493

**Comment by benoit-pierre** [comment]
Look at [PEP 518](https://www.python.org/dev/peps/pep-0518/).

**Comment by benoit-pierre** [comment]
Supported starting with pip 18.0.
