### ISSUE TITLE
error: The 'requests' distribution was not found and is required by koji

### ISSUE THREAD

**Issue by osoukup** [pypa/setuptools#1911]
Hello **setuptools** developers,

I am facing an issue resolving **requests** dependency by **setuptools** working on latest **Fedora** (31) in **docker**. I have found the following minimal working reproducer

```
sudo docker run -it fedora:latest
dnf install python3-pip python3-devel krb5-devel gcc -y
printf "from setuptools import setup\nsetup(install_requires=['requests', 'requests-gssapi', 'koji'])\n" >setup.py
python3 setup.py install
```

Executing this I get the error in the **$subject**. When I change the order of requirements to

```
install_requires=['requests-gssapi', 'requests', 'koji']
```

everything is setup just fine without any error. I am only intermediate Pythonista but I think the order should not matter here. Using **pip** I have no dependency resolving problem putting dependencies in any order.

Ondřej

**Comment by osoukup** [comment]
I was informed that this is actually no issue any more in the latest version of **setuptools** but the reason is that **Fedora 31** still uses version **41.2.0**. I filed a bug against Fedora instead

https://bugzilla.redhat.com/show_bug.cgi?id=1775656

**Comment by benoit-pierre** [comment]
You're hitting #498.

**Comment by benoit-pierre** [comment]
AFAIK, it's still an issue with `install_requires`, but was fixed for `tests_require`/`setup_requires`.
