### ISSUE TITLE
Handling of find_links in setup.cfg in 42.0.0

### ISSUE THREAD

**Issue by neuroid** [pypa/setuptools#1920]
Hi,

I have a couple of `setup_requires` dependencies in my setup.py and my setup.cfg looks like this:

```
[easy_install]
find_links = https://example.com
```

Looking at: https://github.com/pypa/setuptools/blob/e84f616a6507ec9115fad68b221cbf5333d9d2d9/setuptools/installer.py#L119

The `cmd` ends up being:

```python
['python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpWyNzjZ', '--quiet', '--find-links', 'h', '--find-links', 't', '--find-links', 't', '--find-links', 'p', '--find-links', 's', '--find-links', ':', '--find-links', '/', '--find-links', '/', '--find-links', 'e', '--find-links', 'x', '--find-links', 'a', '--find-links', 'm', '--find-links', 'p', '--find-links', 'l', '--find-links', 'e', '--find-links', '.', '--find-links', 'c', '--find-links', 'o', '--find-links', 'm', 'babel; extra == "i18n"']
```
It seems the assumption was that `find_links` is a list but it ends up being a string.

Additionally, since pip is unable to build/fetch a wheel, the following line throws an IndexError:
https://github.com/pypa/setuptools/blob/e84f616a6507ec9115fad68b221cbf5333d9d2d9/setuptools/installer.py#L122

Perhaps this could be caught and a more user-friendly error displayed instead.

**Comment by benoit-pierre** [comment]
See #1921 for the `find_links` issue.

As for the `IndexError`, this should not happen, as the expectation is that the pip command will return with non-zero exit code in case of failure. This is probably related to the `extra == "i18n"` marker, which I think should have been stripped.

Can you provide the full `setup.py`?

**Comment by neuroid** [comment]
Here's a relevant excerpt:

```python
from setuptools import find_packages
from setuptools import setup

setup(name='templates',
      version='0.0.1',
      description='Templates',
      packages=find_packages(),
      setup_requires=[
          'setup[i18n]',
      ])
```

The `setup` package has a very similar setup.py, but with the following extras definition:

```python
      ...
      extras_require={
          'i18n': ['babel'],
      },
      ...
```

**Comment by benoit-pierre** [comment]
Thanks, but from my tests it's more complicated, and only happen if `setup` is already installed, but not `babel`, otherwise, the call to `fetch_build_req` for `babel` happen with a requirement with no marker (which works).

Anyway, looking into it.

**Comment by neuroid** [comment]
That sounds about right. I can confirm that `setup` was already installed, but not with the `i18n` extra.

**Comment by benoit-pierre** [comment]
See #1922.
