### ISSUE TITLE
error: option --no-deps not recognized

### ISSUE THREAD

**Issue by s-m-e** [pypa/setuptools#1936]
- pip 19.3.1
- setuptools 42.0.2

I am experimenting with post-install scripts. My `setup.py`for `mypackage` contains the following sections:

```python
from setuptools.command.develop import develop
from setuptools.command.install import install
# [...]
class PostInstallCommand(install):
	def run(self):
		def _post_install():
			import mypackage
			mypackage.something_from_my_package()
		import atexit
		atexit.register(_post_install)
		install.run(self)
PostDevelopCommand = PostInstallCommand
# [...]
setup(
# [...]
	cmdclass = {
		'develop': PostDevelopCommand,
		'install': PostInstallCommand,
		},
# [...]
    )
```

The above is loosely based on ideas from [here](https://stackoverflow.com/a/36902139/1672565).

My problem is that I need to run a post-install code contained within the package that the corresponding `setup.py` file tries to install. I experimented with many code snippeds, but all had in common that `mypackage` could not be imported when the post-install routine would run. The above snipped is different: It crashes when executed in the development folder like `pip install -U -e .[dev]` with the following output:

```python
Installing collected packages: mypackage
  Running setup.py develop for mypackage
    ERROR: Command errored out with exit status 1:
     command: /project/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/project/setup.py'"'"'; __file__='"'"'/project/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /project/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --no-deps not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /project/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/project/setup.py'"'"'; __file__='"'"'/project/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

Instead of this traceback, I'd expect that `_post_install()` runs, is able to import `mypackage` and run some method from it.

I can not make any sense of it. My fault or a bug in setuptools?

**Comment by benoit-pierre** [comment]
For issue with your your custom `develop` command class is that it's the same as your `install` one, and missing support for the `--no-deps` option.

And this kind of hack is not a good idea: expect issues with pip' standard install path (build a wheel and then install it).

**Comment by s-m-e** [comment]
@benoit-pierre I see ... dumb mistake. Thank you very much.
