### ISSUE TITLE
Note about Python 2.4 still feasible?

### ISSUE THREAD

**Issue by guettli** [pypa/setuptools#1939]
From [Automatic Script Creation](https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation):

>  And even in Python 2.4, using the -m option only works for actual .py files that aren’t installed in a package.

do you really want text about Python 2.4 in the current docs?

I think this confused new comers.

And freaks still running Python 2.4 know how to help themself.

**Comment by abravalheri** [comment]
Hi @guettli, thank you very much for pointing this out!

The mention about Python 2.4 seems to have been removed from the current docs 🎉 
So I guess we can close this issue now 😄, but please let me know if I am missing something.
