### ISSUE TITLE
error: unknown file type '.o' when compile .o with other .cpp files

### ISSUE THREAD

**Issue by alanzhai219** [pypa/setuptools#1940]
I have a .o file, which was compiled in other machine. When I try to compile .o with other .cpp files in setup.py, it reports 'error: unknown file type '.o''.
How could I compile .o and .cpp at the same time? Thanks.

**Comment by alanzhai219** [comment]
I have solved with 'extra_objects'

**Comment by shubhamkshatriya33** [comment]
@alanzhai219  could you please explain your solution?
