### ISSUE TITLE
Docs: dead link

### ISSUE THREAD

**Issue by gpotter2** [pypa/setuptools#1943]
Hi,
https://github.com/pypa/setuptools/blob/1d03fdc94c3676a5b675ec7d818d48c6a772fb49/docs/setuptools.txt#L1007
This link is dead.

**Comment by jaraco** [comment]
Thanks for reporting this. Can you update the link to point to [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources)?

**Comment by gpotter2** [comment]
See https://github.com/pypa/setuptools/pull/1954
