### ISSUE TITLE
Setuptools 45.0.0 breaks pip 2.7 installs

### ISSUE THREAD

**Issue by toastomatic** [pypa/setuptools#1971]
It appears that setuptools 45.0.0 has broken pip 2.7 installs for any module with a setuptools dependency.

Is there a work around for this? I've tried downgrading to 44.0.0, however when pip runs it attempts to upgrade setuptools to 45.0.0. Which according to the error output is no longer compatible with python 2.7. 

`# pip --version` 
`pip 19.3.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)`

`# pip install fabric`
`(..SNIP..)`
`Using cached https://www.piwheels.org/simple/setuptools/setuptools-45.0.0-py2.py3-none-any.whl
      ERROR: Package 'setuptools' requires a different Python: 2.7.13 not in '>=3.5'`

**Comment by pganssle** [comment]
Where are you installing this from? It `pip` should not pick setuptools 45.x on Python 2 because of the `python_requires` metadata, but some PyPI mirrors strip this out.

**Comment by toastomatic** [comment]
@pganssle That was the exact info I needed to fix this, thank you!
The problem was with the mirror I was using. I changed the mirror (in `/etc/pip.conf`) and was able to install fabric.

**Comment by shaoshouping** [comment]
@toastomatic hi, i face the same issue, and i also use mirror, could you help show your modification? thanks!
