### ISSUE TITLE
Netlify builds failing

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#1992]
Our netlify config is pretty straightforward, with [no mention of Python versions](https://github.com/pypa/setuptools/blob/7326ff2a919a1b98262c10e618bfa524d0a14d5f/netlify.toml), yet, the [build fails](https://app.netlify.com/sites/ecstatic-morse-dada75/deploys/5e436ddc99bc630008ae0b43) with lots of warnings about Python 2. We're coming on the 10 year anniversary of Python 2. It's probably time to sunset it as the default.

**Comment by pganssle** [comment]
Looks like [this](https://github.com/netlify/build-image) is where we'd maybe complain about Python 2 being the default, but I think it's just that they deploy some docker container with Ubuntu defaulting to 14.x (6 years old) and maybe upgradable to 16.x (4 years old)?

I don't know much about the netlify configuration, but if there's an option to supply our own Dockerfile or something equivalent I'm sure we could come up with something quite simple, but I'm not seeing that option.

**Comment by jaraco** [comment]
Looks like someone with access to our netlify instance can update us to Xenial with [these instructions](https://www.netlify.com/blog/2019/03/14/a-more-flexible-build-architecture-with-updated-linux/). @ewdurbin I think the Netlify account that's running is yours. Are you able to make that change?

**Comment by ewdurbin** [comment]
The project on netlify was configured with both @jaraco and @pganssle as collaborators when it was set up. If you’re unable to access, let me know and I can look closer monday

**Comment by jaraco** [comment]
Thanks Ernest. I was able to make the change.

![image](https://user-images.githubusercontent.com/308610/76157094-51ccdb00-60d2-11ea-9ea1-da1aec4c3ba5.png)
