### ISSUE TITLE
Emit less cryptic error message for a missing namespace package declaration

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#2]
Originally reported by: **ncoghlan (Bitbucket: [ncoghlan](http://bitbucket.org/ncoghlan), GitHub: [ncoghlan](http://github.com/ncoghlan))**

---

The error message received when a system installed package is missing a "namespace package" declaration is _really_ cryptic. I encountered this for http://beaker-project.org when our common library was missing the namespace package declaration (it originally didn't seem necessary, since that package is the one that _owns_ that namespace, and _does_ have its `__init__.py` file installed as part of the OS package)

When running from a source checkout, we don't actually care that the system version is present, because sys.path ensures the installed released version is ignored. This also holds true for `bkr.__path__`.

However, because of the missing declaration, pkg_resources interprets this as an attempt to import a conflicting version of a top level module and ends up emitting a totally inappropriate error message from check_version_conflict() (see the final warning in 
https://bitbucket.org/pypa/setuptools/src/6aa3034bc297e98ed1a8422d96754cc0d6734667/pkg_resources.py?at=default#cl-2545)

There should be something in declare_namespace() that checks for this and emits a less cryptic error message that makes it clear:
1. It found some metadata for that package (and where it found it)
2. The metadata doesn't say anything about this being a namespace package

See http://stackoverflow.com/questions/13915269/why-do-i-get-userwarning-module-dap-was-already-imported-from-none/ for some background

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/2

**Comment by silkentrance** [comment]
@pganssle This might have been fixed with #1312

**Comment by silkentrance** [comment]
@pganssle This might have been resolved by PEP420 and #1312.

**Comment by pganssle** [comment]
Really hard for me to tell without an MWE.

@ncoghlan Should we close this?

**Comment by ncoghlan** [comment]
I'd say close it - so much has changed with namespace handling since I first filed this that I don't think it's relevant any more, regardless of whether the original misbehaviour has been fixed or not.

**Comment by pganssle** [comment]
Sounds good. We can re-open or open a new issue if something like this comes up again.
