### ISSUE TITLE
jython 2.71 b1 install issues

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#200]
Originally reported by: **strannik19 (Bitbucket: [strannik19](http://bitbucket.org/strannik19), GitHub: [strannik19](http://github.com/strannik19))**

---

Fresh install of jython 2.71b1 on Oracle Java7u55 on Mac OS X 10.9.2

```
$ jython ez_setup.py 
Downloading http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg
Traceback (most recent call last):
  File "ez_setup.py", line 278, in <module>
    main(sys.argv[1:])
  File "ez_setup.py", line 212, in main
    from setuptools.command.easy_install import main
ImportError: No module named setuptools
```

If i download the mentioned egg file, the installation finishes, but then easy_install fails on every installation of anything.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/200

**Comment by abravalheri** [comment]
Hello, I suppose we can close this issue now that `ez_setup` and `easy_install` have been deprecated and widely replace by other installation means, such as `pypa/pip`.

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
