### ISSUE TITLE
Installing multiple `extras` in the same project

### ISSUE THREAD

**Issue by hjpotter92** [pypa/setuptools#2010]
I have a module called `lybre` which has multiple set of `extras` available. Usually, they are independent, and a project usually installs one of them.

However, recently, I had to create a project which would need to use multiple of these extras. I put the following in my requirements file:

```
lybre[A]
lybre[B]
```

and did a `pip install -r requirements.txt`. This only goes on to install the dependencies for `lybre[A]` and completely ignores the 2nd one.

Is this by design, or a bug? How to install multiple versions together?

**Comment by xavfernandez** [comment]
This is mainly due to https://github.com/pypa/pip/issues/988 .

But in your case, a single line with `lybre[A,B]` should work fine.

**Comment by hjpotter92** [comment]
> This is mainly due to [pypa/pip#988](https://github.com/pypa/pip/issues/988) .
> 
> But in your case, a single line with `lybre[A,B]` should work fine.

Thank you. That does work.
