### ISSUE TITLE
setuptools.readthedocs.io History missing 46.0.0

### ISSUE THREAD

**Issue by hroncok** [pypa/setuptools#2020]
https://setuptools.readthedocs.io/en/latest/history.html doesn't list 46.0.0

Is some integration with RTD broken?

**Comment by browniebroke** [comment]
Builds appears to be failing https://readthedocs.org/projects/setuptools/builds/10574350/

**Comment by jaraco** [comment]
Here is [the last successful build](https://readthedocs.org/projects/setuptools/builds/10574340/).

**Comment by jaraco** [comment]
Comparing the tree between the [successful and failing build](https://github.com/pypa/setuptools/compare/dfd59c2a10e1fd74a9f9c719eaffe2b7ebeb414e...50f3575da42ce5b7c013c28ff623ce16c231455d), there's nothing meaningful there that should have caused the build to start failing.

**Comment by jaraco** [comment]
I see the same error when attempting to build docs locally (`tox -e docs`).

**Comment by jaraco** [comment]
Even going back to the checkout for the last successful build, that code now fails, so probably it's some interaction with another internal factor, perhaps the release of Setuptools itself.

**Comment by jaraco** [comment]
The error seems to be another bootstrapping/race condition related to the removal of `Distribution._finalize_feature_opts`. It seems that although the entry point was removed, the reference to it lingers.

**Comment by jaraco** [comment]
It seems that for whatever reason, the egg-info remains pinned to an old version:

```
setuptools master $ grep ^Version: setuptools.egg-info/PKG-INFO                                                                                                           
Version: 45.3.0.post20200308
setuptools master $ grep finalize_feature setuptools.egg-info/entry_points.txt                                                                                            
features = setuptools.dist:Distribution._finalize_feature_opts
```

After running `git clean -fdx`, the docs build is now working reliably again (locally).

**Comment by jaraco** [comment]
After resetting the build environments for `latest` and `stable` builds, the builds are now working and the docs are up-to-date. This issue was transient and probably safe to ignore.

**Comment by hroncok** [comment]
Thanks for the fix!
