### ISSUE TITLE
UTF-8 Charset in README.md

### ISSUE THREAD

**Issue by Jalkhov** [pypa/setuptools#2042]
Good afternoon, community. When I upload a package to [TestPyPi](https://test.pypi.org) in the project description the characters with accents are shown to me like this.

- InstalaciÃ³n
- continuaciÃ³n.
- MenÃº

It should be clarified that I am a Spanish speaker, therefore I have placed the accent on some words. I have placed this doubt in **setuptools** because I feel it has to do with the configuration of the **setup.py** file. I will try to offer as much information as I can.

My **setup.py** file has the following settings with respect to the **README.md** file:

```
with open('README.md') as f:
    long_description = f.read()

setup(name = 'package',
    #...
    description = 'Description',
    long_description = long_description,
    long_description_content_type = 'text/markdown; charset=UTF-8;',
    #...
)
```

To create the **README.md** file I used a tool called **MarkdownPad 2**.

**Comment by alvyjudy** [comment]
Hi @Jalkhov , I tried to replicate your issues with just some random characters but the UTF-8 parsing seems to work perfectly for me.

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/53921639/82940516-f688e700-9f62-11ea-8fd4-4521b42322a2.png">

Could there be something missing on your system?

**Comment by Jalkhov** [comment]
Well, just so this doesn't remain open, I've solved it like this:

```
with open("README.md", encoding="utf-8") as f:
    long_description = f.read()
```
