### ISSUE TITLE
Building RPM Subpackages with bdist_rpm

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#205]
Originally reported by: **vitalyisaev2 (Bitbucket: [vitalyisaev2](http://bitbucket.org/vitalyisaev2), GitHub: [vitalyisaev2](http://github.com/vitalyisaev2))**

---

Hello everybody,

Unfortunately I didn't manage to find out in the documentation if setuptools module supports the building of [RPM subpackages](http://www.rpm.org/max-rpm/s1-rpm-subpack-spec-file-changes.html). Subpackages are really useful things when you maintain the big project and you need to sparse them to the several differing packages (_<main_package>_, _-libs_, _-devel_, _-debuginfo_). 

It would be convenient to do the same in a purely Pythonic projects (i mean to place something in setup.py and to obtain the output _spec_-file with a corresponding number of 

```
#!spec

%package <subpackage_name>
```

 sections). Thank you.

.  

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/205

**Comment by abravalheri** [comment]
Hello, I suppose we can close this issue now that `bdist_rpm` has been deprecated. Moreover, it seems that the Python packaging ecosystem has moved into a different direction and the recent PEPs indicate that each individual package will require its own `pyproject.toml`.

Maybe some clever trick with `tox/nox` and file templates could be used to achieve the desired results?

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
