### ISSUE TITLE
 generate package in root level

### ISSUE THREAD

**Issue by amrit123** [pypa/setuptools#2050]
I am trying to generate the package for my python project. My project structure looks like this:

    src
     -controller
       -handlers
         -subfolder1
           -file1
         -subfolder2
           -file2
         -setup.py
         -init.py
         

handlers is a python package. i ommited `__init__.py` just for asking question, and the setup.py has the following code:

    setup(name='handlers',
    	version='1.0',
        description='AWS Lambda ',
        packages=find_packages(),
        install_requires=['structlog==19.2.0', 'python-json-logger==0.1.10'],
        include_package_data=True,
        zip_safe=False)

I am trying to generate the package called handlers as in parent level. eg: package name handlers that contain both subfolder1 and subfolder2. I am using AWS sam toolkit in pycharm to build the lambda for local deployment and testing.

    handlers
     -subfolder1
     -subfolder2

 but it generates package with its subfolders individually like 

    -subfolder1
    -subfolder2

 
there should be a way to generate the package in the root/parent level for similar project directory setup

**Comment by jaraco** [comment]
Typically, you should have your `setup.py` outside of your Python package structure, and then for `find_packages` to work, you need `__init__.py` in each Python package (`handlers`, `handlers/subfolder` and `handlers/subfolder2`).

```
draft $ mkdir -p handlers/subfolder1 handlers/subfolder2
draft $ touch handlers/__init__.py
draft $ touch handlers/subfolder1/__init__.py
draft $ touch handlers/subfolder2/__init__.py
draft $ cat > setup.py
import setuptools
setuptools.setup(name='handlers', version='1.0', packages=setuptools.find_packages())
draft $ tree
.
├── handlers
│   ├── __init__.py
│   ├── subfolder1
│   │   └── __init__.py
│   └── subfolder2
│       └── __init__.py
└── setup.py

3 directories, 4 files
draft $ python setup.py sdist
running sdist
running egg_info
creating handlers.egg-info
writing handlers.egg-info/PKG-INFO
writing dependency_links to handlers.egg-info/dependency_links.txt
writing top-level names to handlers.egg-info/top_level.txt
writing manifest file 'handlers.egg-info/SOURCES.txt'
reading manifest file 'handlers.egg-info/SOURCES.txt'
writing manifest file 'handlers.egg-info/SOURCES.txt'
running check
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating handlers-1.0
creating handlers-1.0/handlers
creating handlers-1.0/handlers.egg-info
creating handlers-1.0/handlers/subfolder1
creating handlers-1.0/handlers/subfolder2
copying files to handlers-1.0...
copying setup.py -> handlers-1.0
copying handlers/__init__.py -> handlers-1.0/handlers
copying handlers.egg-info/PKG-INFO -> handlers-1.0/handlers.egg-info
copying handlers.egg-info/SOURCES.txt -> handlers-1.0/handlers.egg-info
copying handlers.egg-info/dependency_links.txt -> handlers-1.0/handlers.egg-info
copying handlers.egg-info/top_level.txt -> handlers-1.0/handlers.egg-info
copying handlers/subfolder1/__init__.py -> handlers-1.0/handlers/subfolder1
copying handlers/subfolder2/__init__.py -> handlers-1.0/handlers/subfolder2
Writing handlers-1.0/setup.cfg
creating dist
Creating tar archive
removing 'handlers-1.0' (and everything under it)
```
