### ISSUE TITLE
cannot import name 'feature_dict' from 'features'

### ISSUE THREAD

**Issue by billx93** [pypa/setuptools#2056]
i am facing this   problem any body help me plx

**Comment by jaraco** [comment]
The name 'feature_dict' doesn't appear anywhere in setuptools code base. Probably you're trying to install some project and that project has a bug. Contact that project for more information.

Note that setuptools did drop support for "Features" in v46.0, released recently, so it's possible the project you're using is trying to use that.

As reported, there's nothing setuptools can do to help. Good luck.
