### ISSUE TITLE
Add  always-unzip and no-deps options to install command

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#206]
Originally reported by: **jaraco (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

In [pip 1749](https://github.com/pypa/pip/issues/1749), it appears that setuptools could better support the use cases of pip by providing two new options, `--always-unzip` and `--no-deps`, to the `install` command.

What are the implications of adding such options? Would they simply fall through to easy_install? Could the same behavior be invoked using existing behavior, such as through setopt, e.g.:

```
python setup.py setopt -c easy_install -o always-unzip -s 1 install
```

While ugly, I believe that behavior would work today.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/206

**Comment by asmodehn** [comment]
I also have a usecase where I would like to be able to do
`setup.py install --single-version-externally-managed --root --no-deps`.

I am currently using `--single-version-externally-managed` and `--root` as well but it is not clear to me if these bring in dependencies or not (I would like them not to). The documentation doesn't say anything about it.

I think I have seen them bringing in dependencies (Cant be sure, I have been switching a lot between different versions of setuptools) but it seems they don't (https://github.com/pypa/setuptools/issues/570) ?

**Comment by benoit-pierre** [comment]
Pip non longer support `--egg`.
