### ISSUE TITLE
Incompatible install in Python3 (Setuptools warns about Python 2 incompatibility)

### ISSUE THREAD

**Issue by brobr** [pypa/setuptools#2066]
## Other notes
The reason to submit this is because this warning came up when building a package for a program (HTSeq: https://github.com/htseq/htseq ) via `python3 setup.py install`:
The program compiled fine, but -as said- I get this in the output:
>...
htseq-release_0.11.4/todo.txt
symlinking folders for python3
running install
running build
running build_py
running preprocess
cythonizing
\/usr/lib64/python2.7/site-packages/pkg_resources/py2_warn.py:22: UserWarning: Setuptools will stop working on Python 2
\************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
\>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
\..
\..
SWIGging
correcting SWIG for python3

I do not understand why this popped up, not calling `python` at all, nor using `pip` or `pip3` for creating the HTSeq package.

## Environment Details

- Operating System and version: Slackware64-current
- Python versions on the system: 2.7.17 and 3.8.2
- Python installed how: via packages build by 'setup.py install' route
[https://packages.slackware.com/?r=slackware64-current&p=python-2.7.17-x86_64-2.txz](url)
[https://packages.slackware.com/?r=slackware64-current&p=python3-3.8.2-x86_64-1.txz](url)
[https://packages.slackware.com/?r=slackware64-current&p=python-pip-20.0.2-x86_64-1.txz](url)
[https://packages.slackware.com/?r=slackware64-current&p=python-setuptools-45.3.0-x86_64-1.txz](url)

Output of `pip --version` from commandline:
bash-5.0$ pip --version
/usr/lib64/python2.7/site-packages/pkg_resources/py2_warn.py:22: UserWarning: Setuptools will stop working on Python 2
\************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
\>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
`https://github.com/pypa/setuptools/issues/1458`
about the steps that led to this unsupported combination.
\************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
pip 20.0.2 from /usr/lib64/python2.7/site-packages/pip (python 2.7)
bash-5.0$ pip3 --version
pip 20.0.2 from /usr/lib64/python3.8/site-packages/pip (python 3.8)
bash-5.0$ 

```
```

**Comment by jaraco** [comment]
It's apparent to me that there's a bug in the package you're trying to install. It seems that even though you're invoking `setup.py` under `python3`, something about the setup script is invoking Python 2. Furthermore, in your Python 2 environment, you have a too-new version of setuptools installed. I'm not sure how you installed setuptools for Python 2, but however it happened, you want to make sure to use `pip 9` or later to install it or ensure it's pinned to `setuptools<45`.

**Comment by jaraco** [comment]
That project [invokes a command](https://github.com/htseq/htseq/blob/f5db08d206107a05e1224921d553a831b6daa207/setup.py#L143-L169) "cython", which I'm guessing was installed into the Python 2 environment. I'm pretty sure that's where the warning is coming from. Just make sure that on Python 2 that you don't install setuptools 45 or later and you should be fine.

**Comment by brobr** [comment]
These are distribution packages, so that's what's there to use:
`PACKAGE NAME:     python-setuptools-45.3.0-x86_64-1`
>usr/bin/
usr/bin/easy_install
usr/bin/easy_install-2.7
usr/bin/easy_install-3.8
..
usr/lib64/python2.7/site-packages/easy_install.py
..
usr/lib64/python3.8/site-packages/easy_install.py

and
`PACKAGE NAME:     Cython-0.29.16-x86_64-1`

>usr/bin/cython
usr/bin/cython3
..
usr/lib64/python2.7/site-packages/Cython/
..
usr/lib64/python3.8/site-packages/Cython/

These are 'unadultered' packages; installed as the software comes.
Pip is not always the preferable way to install python modules; the 'old' `python setup.py install` route is still used by distributions to create their packages. 

So, it seems ia python bug

**Comment by McSinyx** [comment]
> So, isn't it a python bug due to the mixed usage of p/cython vs p/cython3 etc.?

AFAIK the more canonical way to do it is to call Cython with `sys.executable` (that's how Cython performs functional tests), however I think it might be a better idea to avoid calling the shell command and use the Python function `cythonize`.

**Comment by brobr** [comment]
Thanks, I've pointed the developers of HTSeq to this post again; maybe they can take this on board.
