### ISSUE TITLE
Incorrect value of constant NAMESPACE_PACKAGE_INIT

### ISSUE THREAD

**Issue by Cykooz** [pypa/setuptools#2070]
"Python Packaging User Guide" does not recommend to use namespace `__init__.py` with code like this:
```python
try:
    __import__('pkg_resources').declare_namespace(__name__)
except ImportError:
    __path__ = __import__('pkgutil').extend_path(__path__, __name__)
```
https://packaging.python.org/guides/packaging-namespace-packages/#pkg-resources-style-namespace-packages

But constant NAMESPACE_PACKAGE_INIT contains this version of code.
https://github.com/pypa/setuptools/blob/53c284b325959a6fd177e9d37d8b5dd5824db2b3/setuptools/wheel.py#L30-L35

At least, this affects the "namespace-detector" in PyCharm. PyCharm does not support this method of namespace definition (because it is not recommended) - https://youtrack.jetbrains.com/issue/PY-38434).

Need to replace value of this constant with:
```python
__path__ = __import__('pkgutil').extend_path(__path__, __name__)
```

**Comment by jaraco** [comment]
Thanks for the report. I believe the code can be replaced by just the `pkg_resources` declaration. That's the form that's meant to go along with packages that declare "namespace_packages". Is this change needed for Python 2 environments, or is the change in the master, Python-3-only branch okay?

**Comment by jaraco** [comment]
Also, this code is only used when setuptools converts a wheel to an egg, which should only really happen with `setup_requires` compatibility installations, which I wouldn't expect to be installed in a user's environment. Is this an actual issue or a just a potential one based on code search?
