### ISSUE TITLE
should the shebang be removed?

### ISSUE THREAD

**Issue by sandy-lcq** [pypa/setuptools#2076]
Hi,
 command/easy_install.py has shebang "#!/usr/bin/env python", on some host, like fedora31 docker image,only python3 installed, and no python link to python3, in this case, maybe error like "python: command not found" will repored when run it.

same problem with "pkg_resources/_vendor/appdirs.py" , have reported to https://github.com/ActiveState/appdirs/issues/145

**Comment by jaraco** [comment]
That file isn't meant to be executed. The shebang was there as a signal that the file's content is Python code. Perhaps it should be removed.
