### ISSUE TITLE
How to get data files in the right director 

### ISSUE THREAD

**Issue by abdjava** [pypa/setuptools#2084]
Hi i am new to useing setuptools to make python packages . 
I got a project i need to turn into a package . 
Currently its in the stored in 
```
project/
         setup.py 
          mo/ 
                some code
          extensions /
                 other extensions to the code 
          requriments.txt
.
```
here my setup.py 
```python
from setuptools import setup, find_packages
setup(
    name="name",
    version="version",
    packages=find_packages(),
	package_data={'': ['*.txt']},
	include_package_data=True,
	entry_points ={ 
            'console_scripts': [ 
                'mo_onnx = mo.mo_onnx:main'
            ] 
        }
)


```
when i run  ``` python setup.py install ``` the package is installed  as

python3.7/site-packages/name-version-py3.7.egg/mo
python3.7/site-packages/name-version-py3.7.egg/extensions 

but the  requriments.txt if placed inside the mo direcotr not inside name-version-py3.7.egg .
Is it possible for me to place is there instead of inside mo if so how .

**Comment by McSinyx** [comment]
A few general comments, until you clarify what you mean by `mo` and `extensions` (gettext translation and C/C++ code?):
1. There's no reason to install `requriments.txt` to sites, and with setuptools you can put the install requirements to `install_requires`.
2. IIRC `package_data` is to provide data for packages, so it should refer to data inside a package.  Since I can't see what's in `mo` and `extensions`, there's no way I can tell what's found by `find_packages` but I think `mo` is one (also from the entry point).
3. Usually posting your actual configuration would make it easier for others to help, which in this case mean the actual tree at the root of your project as well as the real content of `setup.py`.

Cheers.

**Comment by abdjava** [comment]
Hi sorry about not giveing full information . I was trying to avoid giveing infomation about something not yet released.
Both MO and extensions  contains Python modules . 

Due to the fact the trees for both directors are really big i attached txt files with them below 
[extensions_tree.txt](https://github.com/pypa/setuptools/files/4573833/extensions_tree.txt)
[mo_tree.txt](https://github.com/pypa/setuptools/files/4573834/mo_tree.txt)

```
from setuptools import setup, find_packages
setup(
    name= "mo",
    version="2020.1",  
    packages=find_packages(),
	package_data={'': ['*.txt']},
	include_package_data=True,
	entry_points ={ 
            'console_scripts': [ 
                'mo_onnx = mo.mo_onnx:main'
            ] 
        }
)
```
Currently the system reads the requirements.txt to ensure all the correct version of python packages are installed before running . As i understand this is not necessary I want to avoid changeing the code forverification reasons . 


Thanks for you help and comments .

**Comment by McSinyx** [comment]
> Currently the system reads the requirements.txt to ensure all the correct version of python packages are installed before running . As i understand this is not necessary I want to avoid changeing the code forverification reasons .

I don't think it is necessary at all.  IMHO you should list the requirements as `install_requires` in `setup.py` with version range included.  Then the package manager installing your package will make sure that everything are of the right version.  Slightly related, `pip` 20.1 now have (experimental) dependency resolution which can ensure that installing/upgrading one package won't break another (in this case, your package).

**Comment by abdjava** [comment]
Ok thats fair  ill have a look at it . 
Thank for your help
