### ISSUE TITLE
lib2to3 will be removed in Python 3.10

### ISSUE THREAD

**Issue by hroncok** [pypa/setuptools#2086]
See also https://github.com/pypa/setuptools/issues/2081

The standard library module lib2to3 is deprecated and will be removed in Python 3.10. 

https://bugs.python.org/issue40360

lib2to3 will likely become an external library available from PyPI, but my guess is that setuptools don't want to have more dependencies.

**Comment by hroncok** [comment]
Here is what I think might be a path forward:

In the next setuptools release, using [use_2to3](https://setuptools.readthedocs.io/en/latest/python3.html) will become deprecated as well (with no set removal date). On Python 3.10, setuptools will have optional dependency (e.g. via `setuptools[use_2to3]`) on the 3rd party lib2to3 module to keep supporting installing old packages.

**Comment by jaraco** [comment]
> On Python 3.10, setuptools will have optional dependency (e.g. via `setuptools[use_2to3]`) on the 3rd party lib2to3 module to keep supporting installing old packages.

I'd prefer simply to drop support for building with 2to3 support and to require those old packages to be built on old versions of setuptools (or not at all). Regardless, let's get the deprecation in ASAP as possible to signal to users to stop using it.

**Comment by graingert** [comment]
I'm getting build failures because of this lib2to3 use https://github.com/twisted/ldaptor/runs/1205572060#step:12:103 so I'm in favour of it being removed.

note, you could use `fissix` instead of lib2to3, if you still wanted to support on the fly translation

**Comment by graingert** [comment]
lib2to3 is still in Python3.10 as of `Python 3.10.0b4 (default, Jul 12 2021, 22:16:23) [GCC 9.3.0] on linux`
