### ISSUE TITLE
VendorImporter doesn’t have `find_spec()` method

### ISSUE THREAD

**Issue by manueljacob** [pypa/setuptools#2104]
[`sys.meta_path`](https://docs.python.org/3/library/sys.html#sys.meta_path) entries should have a `find_spec()` method. As a fallback, `importlib` calls `find_module()`, but other users might not.

**Comment by jaraco** [comment]
Thanks manueljacob. Would you consider putting together a patch?

**Comment by jaraco** [comment]
Actually, let's put this effort on hold until #2052 is resolved, as that may remove the VendorImporter entirely.

**Comment by manueljacob** [comment]
Thanks. For now, I worked around the problem. For reference: https://www.mercurial-scm.org/pipermail/mercurial-devel/2020-May/141648.html
