### ISSUE TITLE
Generated launchers won't launch if there is a space in the path

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#216]
Originally reported by: **stevedower (Bitbucket: [stevedower](http://bitbucket.org/stevedower), GitHub: Unknown)**

---

(This is related to https://bitbucket.org/pypa/setuptools/issue/188/nt-escaping-in-shebang-in-easy_install, but that one is now being treated as a feature request and I believe the two changes would be unrelated anyway.)

The latest setuptools generates .exe launchers that include a shebang line pointing to the python.exe. If there is a space in this path, the path is quoted.

However, when the launcher runs, it will add a second set of quotes to the path leading to an error like this:

``` text
Fatal error in launcher: Unable to create process using '""D:\...\Test VEnv\Scripts\python.exe"" "D:\...\Test VEnv\Scripts\easy_install.exe" '
```

I believe the issue is in the launcher rather than the shebang line, since quoting that path is the only way you could support arguments as well as spaces on Windows. IMO, the launcher should not add more quotes to the shebang line when launching.

My repro steps (run at the command prompt):

``` text
C:\Python27\python.exe -m virtualenv "Test VEnv"
cd Test VEnv
Scripts\python.exe -m pip install -U setuptools==4.0.1

rem The current easy_install.exe was generated with setuptools 3.something and it works fine

rem The next line generates a new easy_install.exe with setuptools 4.0.1 and it doesn't work
Scripts\python.exe -m pip install -U setuptools==4.0.0
Scripts\easy_install.exe
```

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/216

**Comment by kz26** [comment]
This is still a problem on setuptools 20.10.1 on Windows (I guess that's the version included with CPython 3.5.2). My Python path is `C:\Program Files\Python35`. The `*-script.py` file contains a shebang line that is NOT quoted; manually adding the quotes allows the generated EXE launcher to work.

**Comment by set-soft** [comment]
I get the same prooblem using:

- Python 2.7.18
- setuptools 44.1.1

The problem is the following line of code:

https://github.com/pypa/setuptools/blob/2234e88b7b820c40f29d7ddadc182b0f130eaa1d/setuptools/command/easy_install.py#L2027

Removing the call to `CommandSpec._strip_quotes` creates usable launchers. For some reason the new launchers doesn't use the `*-script.py` strategy, just embed the code in the .exe.

**Comment by set-soft** [comment]
I got the same problem with Python 2.7.18 and the last setuptools for it: 44.1.1

The problem is with the following code:

https://github.com/pypa/setuptools/blob/2234e88b7b820c40f29d7ddadc182b0f130eaa1d/setuptools/command/install_scripts.py#L45

Comparing two file names directly is a **very bad idea**.  Changing it to:

```python
if os.path.abspath(exec_param) == os.path.abspath(sys.executable): 
```

Solves the problem for my case. The root of the problem is that `sys.executable` is returning forward slashes and `exec_param` getting back slashes.

**Comment by jaraco** [comment]
The repro instructions as reported are no longer valid. I believe since this report was filed in 2014, pip added support for creating its own launcher executables. `easy_install` is no longer provided, but there are other applications exposing console_scripts entry poinst, such as `twine`. With `pip install twine`, even with the latest setuptools installed, pip generates the entry scripts.

**Comment by jaraco** [comment]
The only code path that still produces scripts is the one for "editable" (aka "develop") installs, so I created a Dockerfile to attempt to capture the issue using an editable install of twine:

```
from jaraco/windows

RUN python -m venv 'Test Env'
WORKDIR Test Env

RUN Scripts\python -m pip install -q -U setuptools
RUN git clone https://github.com/pypa/twine /src/twine
RUN Scripts\python -m pip install -q -e /src/twine
RUN Scripts\twine --help
RUN cat Scripts\twine-script.py
```

Building that Dockerfile runs to completion with the output:

```
draft $ docker build .
Sending build context to Docker daemon  61.39MB
Step 1/8 : from jaraco/windows
 ---> 87cd4b12531f
Step 2/8 : RUN python -m venv 'Test Env'
 ---> Using cache
 ---> 1dbd648fdf03
Step 3/8 : WORKDIR Test Env
 ---> Using cache
 ---> a63898e81c15
Step 4/8 : RUN Scripts\python -m pip install -q -U setuptools
 ---> Running in 193c57cfcff2
WARNING: You are using pip version 21.1.1; however, version 21.1.3 is available.
You should consider upgrading via the 'C:\Test Env\Scripts\python.exe -m pip install --upgrade pip' command.
Removing intermediate container 193c57cfcff2
 ---> e33a6594202a
Step 5/8 : RUN git clone https://github.com/pypa/twine /src/twine
 ---> Running in 3145b39da8cc
Cloning into '/src/twine'...
Removing intermediate container 3145b39da8cc
 ---> 80fd527545a9
Step 6/8 : RUN Scripts\python -m pip install -q -e /src/twine
 ---> Running in 9bcd43da18ed
WARNING: You are using pip version 21.1.1; however, version 21.1.3 is available.
You should consider upgrading via the 'C:\Test Env\Scripts\python.exe -m pip install --upgrade pip' command.
Removing intermediate container 9bcd43da18ed
 ---> 522bf8b2ee1d
Step 7/8 : RUN Scripts\twine --help
 ---> Running in e7bad1439a8b
usage: twine [-h] [--version] [--no-color] {upload,register,check}

positional arguments:
  {upload,register,check}

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --no-color            disable colored output
Removing intermediate container e7bad1439a8b
 ---> 434ae190ca37
Step 8/8 : RUN cat Scripts\twine-script.py
 ---> Running in c9d33f01cef9
#!"C:\Test Env\Scripts\python.exe"
# EASY-INSTALL-ENTRY-SCRIPT: 'twine','console_scripts','twine'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'twine'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('twine', 'console_scripts', 'twine')())
Removing intermediate container c9d33f01cef9
 ---> 7a9987a6850f
Successfully built 7a9987a6850f
```

So it seems that although the quotes are present and there are spaces in the filename, the launcher is able to launch the script just fine. I tested also with Setuptools 44.1.1, but the results are the same.

I was testing with Python 3.9. It's possible the issue somehow exists with Python 2.7 only, but if that's the case, that Python is no longer supported. Still, I believe you have good options on Python 2.7 by installing packages with recent versions of pip.

I'm going to close this issue.

@set-soft It sounds like your issue may be different from the one reported by the OP. Can you provide more detail on how I might be able to replicate the issue? Can you confirm that it only happens in Python 2.7 but not 3.x? If the issue you have produces a different error message or requires a different mode to trigger the error and it still fails on Python 3.x, please open a new issue. If it's the same issue, we can continue to explore here, but I'll need more information to reproduce the failure.
