### ISSUE TITLE
Incompatible install in (summarize your environment)

### ISSUE THREAD

**Issue by hokd2905** [pypa/setuptools#2187]
## Prerequisites

- [x] Read [Python 2 Sunset docs](https://setuptools.readthedocs.io/en/latest/python%202%20sunset.html).
- [x] Python 2 is required for this application.
- [x] I maintain the software that installs Setuptools (if not, please contact that project).
- [x] Setuptools installed with pip 9 or later.
- [x] Pinning Setuptools to `setuptools<45` in the environment was unsuccessful.

## Environment Details

- Operating System and version:
- Python version:
- Python installed how:
- Virtualenv version (if using virtualenv): n/a

Command(s) that triggered the warning/error (and output):

```python netattack2.py 
```

Command(s) used to install setuptools (and output):

```
```

Output of `pip --version` when installing setuptools:

```/usr/share/python-wheels/pkg_resources-0.0.0-py3-none-any.whl/pkg_resources/py2_warn.py:21: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please follow up at
https://bit.ly/setuptools-py2-warning.
************************************************************
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 20.0.2 from /usr/lib/python2.7/dist-packages/pip (python 2.7)

```

**Comment by jaraco** [comment]
Hi hokd2905. It looks to me like you got the warning about aging setuptools while invoking `pip --version`. That just means that you have the incorrect version of setuptools installed. Just `pip uninstall setuptools` followed by `pip install setuptools`. Should fix you right up. If not, please see http://bit.ly/setuptools-py2-sunset for more guidance.
