### ISSUE TITLE
Emit metadata 1.2 data

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#219]
Originally reported by: **Ivoz (Bitbucket: [Ivoz](http://bitbucket.org/Ivoz), GitHub: [Ivoz](http://github.com/Ivoz))**

---

pep - http://legacy.python.org/dev/peps/pep-0345/

1.2 provides a number of very useful info, foremost: Requires-Dist, Requires-Python, [requirement-markers](http://legacy.python.org/dev/peps/pep-0345/#environment-markers)

which will be great for enabling dependency statistics on pypi, and ahead-of-time dependency resolution in pip, if/when this was enabled in a future setuptools, people started to use it, and started uploading 1.2 metadata to pypi.

Additional thought - we'll probably want to test pypi can actually accept newer metadata versions if it's still the old one and not warehouse by the time this is release-ready.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/219

**Comment by pganssle** [comment]
This is done, though I suspect support for the full spec is patchy. I'm going to close this in favor of individual tickets for missing support.
