### ISSUE TITLE
setup.cfg long_description needs the ability to read from a file (such as the README)

### ISSUE THREAD

**Issue by gpshead** [pypa/setuptools#2222]
This is one of the primary remaining reasons `setup.py` need exist at all. To open the README.md file, read it as utf-8 and call:

```python
import pathlib
here = pathlib.Path(__file__).parent.resolve()
long_description = (here / 'README.md').read_text(encoding='utf-8')
setup(
    long_description = long_description,
)
```

Having the ability to specify that common kind of action from setup.cfg's [metadata] long_description = setting would be convenient.

Neat but less explicit, if no long_description is supplied at all, should it default to the README?  (and infer the long_description_content_type from the file extension?)

**Comment by McSinyx** [comment]
Hi there, [the field you mention can actually take a file](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files).  I hope that helps :smile:

**Comment by gpshead** [comment]
Oh, sweet.  Navigating the documentation has been a challenge.   =)

The prominently placed docs linked from PyPI:
  https://packaging.python.org/tutorials/packaging-projects/ ->
  https://packaging.python.org/guides/distributing-packages-using-setuptools/ ->
  https://github.com/pypa/sampleproject

is still setup.py based rather than using setup.cfg, I never found my way to that doc.

Via your link, this does indeed work:
```
[metadata]
...
long_description = file: README.md
long_description_content_type = text/markdown
...
```

Dealing with updating the documentation to cover these "I just wanna package a 50 line module.py" user stories is a out of scope here.  Closing this one as the feature does exist.
