### ISSUE TITLE
Adopt a logo

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#2227]
Setuptools could have a logo.

Thinking about the elements of design, I’d want to discourage elements of “installer” and focus on elements that hint at “builder” or “compiler” or “tool”. If one draws inspiration from the [Warehouse](https://pypi.org) logo, note that Setuptools is one of many tools that creates each of those blocks. Probably, something more abstract and without much relation to the Python or Warehouse logos would be best.

**Comment by cajhne** [comment]
This is what came to mind... though admittedly it's python-centric... but since the tools are for Python, I think it's probably a good idea to show some relation to python. Can come up with other designs if you want.

-C
![setuptools_logo](https://user-images.githubusercontent.com/12825551/86488651-ab2fd880-bd59-11ea-9488-9d4def731631.png)

**Comment by jaraco** [comment]
I absolutely love it.

Would you be willing to send a pull request with the source asset and a few renderings to the docs/images directory? I'm thinking these formats would be handy to have, each in SVG and PNG:

- logo over text (as above)
- logo only
- logo + text (banner-style)
- text only

If you're not familiar or comfortable sending a PR, let me know and I'll send a dropbox link where you can send the assets.

Also, can you add a note (README or similar) suitable for attribution? It can just be a name or moniker or it can include a link to a site where someone could contact you for similar work, whatever you'd like. I'm not sure yet where it will go in the docs, so you're welcome to propose a location or I'll figure out something.

Thanks!!!

**Comment by cajhne** [comment]
Great. :) 
Yes, I can provide those formats. I'll also include the font I used: Josefin Sans, which is a free Open Font (OFL) which you can use for headlines and documents from your project without paying any font license fees. I'll try a PR. I'm used to GitLab though, so we will see how this goes. :)

**Comment by pganssle** [comment]
I'm also impressed by this. Really fast work!

We may want to run this by the PSF trademark working group before adopting it: https://www.python.org/psf/trademarks/

**Comment by cajhne** [comment]
Thanks! I thought up the design while making this FFS banner for the SetupTools interview:
![FOSS_for_science_podcast_template_FFS029_Setup_Tools_750x500](https://user-images.githubusercontent.com/12825551/86493411-61e78500-bd69-11ea-80ce-5ed4d40d9b72.png)

Good interview. It's here btw, if you have not had a chance to hear it yet:
https://flossforscience.com/podcast/season3-episode-6

And yes, good idea running it past the PSF. I think it falls under the projects fair use policy regarding projects which are built for python, but IANAL. :) Do let me know if they want it changed. We can make changes.

-C

**Comment by cajhne** [comment]
Sorry, I don't have time to figure out the changelog.d thingy. If someone could do that bit if it's important. :) It's not a code change, so maybe it's fine?

Thanks.

**Comment by hugovk** [comment]
The logo looks great!

However, I have a feeling, from reading https://github.com/pytition/Pytition/issues/37#issuecomment-450913013, that the PSF Trademarks Committee would consider it "dilutive" and not allowed, like the Pycon Thailand example in that issue.

"Inspired by but not derived from" is acceptable, like the PyCon China example. As is "derived but not dilutive", like PyCon Israel.

> As a guideline, modifications that leave the shape -- but not necessarily the colors -- unaltered are likely to be approved. Inclusion of other visual elements at an offset to the logo is generally acceptable (subject to other terms of this policy). Modifications that modify or obscure any part of the shape of the logo will not be approved.

https://www.python.org/psf/trademarks/

**Comment by jaraco** [comment]
Excellent feedback. Thanks for the pointers! I'll send an e-mail (the prescribed contact method) and report back.

**Comment by jaraco** [comment]
Unfortunately, you're right. This derivation is unacceptable:

> I'm afraid that the logo you show, with a "hammer inside a snake" is not an acceptable derived version of the Python "two snakes" logo.  In general, any derived version must maintain the intact outline of the "two snakes."  You are free to change colors of it, and are free to add additional visual elements that are nearby the Python logo, surround it, or that fall entirely within the bodies of the "snakes" (but not obstructing the "eyes").
>
> We cannot allow shape modifications, even for attractive designs, because that constitutes dilution of our protected trademark.  That is, if we allowed such derived versions, we would lose the legal right to protect the trademarked Python logo.
> 
> Yours, David Mertz
> Co-chair Python Software Foundation Trademarks Committee

We'll need to revisit the design :(

@cajhne: Does that rationale make sense? As much as I dislike the world in which that's the case, I also cannot fault their rationale. To retain a defensive posture on their trademark, they cannot allow derivative works for any project, regardless of its stature in the Python ecosystem. Would you consider drafting other design that avoids deriving from the Python trademark?

**Comment by hroncok** [comment]
Two followups:

 1. Apart from the trademark problem, the logo is stated simply as `(c) the Setuptools developers` -- what license is it?
 2. The sdist contains the logo folder, but only the license file for the font is in it (which is good fro now, because I don't need to worry whether I can use the sdist in Fedora, but probably is not the intentional behavior).

**Comment by cajhne** [comment]
Hi. Sorry for the radio silence, been snowed under with work and
preparations for my GUADEC talk. I'll revise the logo as requested, and
present alternative options in August, when things get sane again. In the
meantime, I recommend taking the logo out of the repo entirely. Regarding
the license, please advise what license you would like, and I'll include
that in the README for the logo package.

Thanks for your patience.
-C

**Comment by jaraco** [comment]
>     1. Apart from the trademark problem, the logo is stated simply as `(c) the Setuptools developers` -- what license is it?

Like any other contribution to the project, I'd expect it to follow under the MIT license, unless there are issues with that. Do other projects license their logos and fonts separately?

>     2. The sdist contains the logo folder, but only the license file for the font is in it (which is good for now, because I don't need to worry whether I can use the sdist in Fedora, but probably is not the intentional behavior).

That's because setuptools doesn't use setuptools_scm so files get missed. We'll consider fixing that with the next contrib.

**Comment by hroncok** [comment]
> Do other projects license their logos and fonts separately?

Some do, some don't.

See for example

 - https://flask.palletsprojects.com/en/1.1.x/license/#artwork-license
 - https://github.com/astropy/astropy-logo/blob/master/LICENSE
 - https://en.wikipedia.org/wiki/File:Bottle-logo.svg

**Comment by abravalheri** [comment]
Hi guys, since there was a problem with PSF and the previous design, what would you think about something like this:

![setuptools](https://user-images.githubusercontent.com/320755/140125808-e77bf824-6156-474f-81c4-2ea44928329b.png)

(obviously inspired in the previous work)

I started with something very flat and minimal (the black-and-white one) and them added some colours just to see how it works out (I have to bee sincere the monochromatic choices look the best for me)

Again, there is a snake, so it is related to Python (although not incorporating elements related to the PSF). The shape of the snake is inspired by a "wheel" (¡!), and also resembles the common cog icon people use for "setup".

Some people might even see a "ouroboros-like" loop, to which I would reply: "a package to build packages", where the end (the installed setuptools package) and the beginning (your package during development) meet.


---
Disclaimer: not a professional designer here 😝

**Comment by jaraco** [comment]
Very nice and inspired. I say let’s take it. I like the blue yellow combo best with color split in the word. But I’m fine with monochrome too. Would you care to put together a pull request implementing the same changes as before but with the new assets?
