### ISSUE TITLE
setuptools 45.2.0-1 ignoring --user flag on WSL Ubuntu

### ISSUE THREAD

**Issue by phetdam** [pypa/setuptools#2252]
I recently started foraying into trying to build C extensions in Python, but this ended in catastrophic failure since I had been using MSYS2 and MinGW-w64 on a Windows 10 machine, but that's a story for another time.

Soon after I learned about WSL and got pretty excited, so I enabled it and promptly downloaded Ubuntu for it. I tried to build a toy C extension just to make sure everything worked, which has very simple code as follows.

```c
#include "Python.h"

// short module description
#define SHORT_MOD_DESC "A test module to play with some Python stuff."

/**
 * Returns "hello" when called.
 */
static PyObject* hello(PyObject *self, PyObject *args) {
    if (!PyArg_ParseTuple(args, "")) {
        Py_INCREF(Py_None);
        return Py_None;
    }
    return PyUnicode_FromString("hello");
}

// module functions
PyMethodDef module_methods[] = {
    {"hello",  hello, METH_VARARGS, "Returns hello."},
    {NULL, NULL, 0, NULL}
};

// define module
struct PyModuleDef my_test_def = {
    PyModuleDef_HEAD_INIT,
    "my_test", // name of module
    SHORT_MOD_DESC, // module docstring
    -1, // module state (-1 does not support subinterpreters)
    module_methods
};

// initialize module
PyMODINIT_FUNC PyInit_my_test(void) {
    return PyModule_Create(&my_test_def);
}
```

I used a standard `setup.py` file to install, i.e.

```python
from setuptools import setup, Extension

my_test = Extension("my_test", sources = ["my_test.c"])

def _setup():
    setup(name = "my_test",
          author = "phetdam",
          description = "Another attempt at building a C extension module",
          version = "0.0.1",
          ext_modules = [my_test])

if __name__ == "__main__":
    _setup()
```

Here's the problem. Since I didn't want to use `virtualenv` or install globally, I had installed my Python packages locally, i.e. in `~/.local/lib/python3.8/site-packages`. Since `setuptools` is supposed to (at least according to `python3 setup.py install --help`) install in `~/.local/lib/python3.8/site-packages` if I give `install` the `--user` flag, that's what I did. To my surprise, I got

```
error: [Errno 1] Operation not permitted
```

Obviously `setuptools` is trying to write somewhere it's not supposed to, but I (stupidly) decided to tried again by prepending `sudo` to the call, and then watched `setuptools` install the package directory to `/root/.local/lib/python3.8/site-packages`, having **created** a new directory to do so. This behavior is nonsensical, and it's also not any of the directories listed in `sys.path`. 

However, when I changed `setuptools` to `distutils.core` in my `setup.py` as shown above, voila: my dumb package installed in `~/.local/lib/python3.8/site-packages/my_test-0.0.1.egg-info`, exactly what I wanted. Then in the Python interpreter, I was able to `from my_test import hello` and call `hello()` just fine.

The `setuptools` I'm using is 45.2.0, and it's the system-wide `setuptools`, as `pip3 show setuptools` gives 

```
Name: setuptools
Version: 45.2.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /usr/lib/python3/dist-packages
Requires:
Required-by: Sphinx, ipython, launchpadlib
```

Maybe this issue has been fixed in later versions of `setuptools`? Either way, I can't really upgrade `setuptools` using `apt` since 45.2.0 is the latest version available on Ubuntu. Is this a bug in `setuptools`, am I just being dumb, or should I just stick with `distutils`? I don't really want to use with `distutils` since it's no longer recommended for packaging, but it looks like I might not have a choice in this case. Thoughts?

**Comment by jaraco** [comment]
Indeed, use of `distutils` is discouraged. So also is `setup.py install`.

What is recommended instead is to use `pip install --user .` I'd expect that to have the intended effect. Please report back if you find that's not the case.

**Comment by phetdam** [comment]
Sure, but I probably won't be uploading anything to PyPI soon. `pip3 install --user` is fine, but it is concerning that `setuptools` is not behaving the way that it is supposed to behave. So I guess in the meantime I should be doing `python3 setup.py build` and `python3 setup.py build_ext --inplace` then if I need to build a package for testing purposes?
