### ISSUE TITLE
Incompatible install in (summarize your environment)

### ISSUE THREAD

**Issue by Stupid1000** [pypa/setuptools#2267]
pip  install command is not been support(issue use it)  by the kali linux 2020 operation system how should fix the problem is let me know

**Comment by jaraco** [comment]
Your best option is to use pip. If you are maintainer of Kali Linux, please reach out to the pip team with any issues. If you are a user of Kali Linux, please reach out to the Kali Linux for help.

Good luck.

**Comment by Stupid1000** [comment]
thanks Pypa/Setuptools
i using python -m pip instal ..
it is helpful for time been
