### ISSUE TITLE
Incompatible install in (summarize your environment)

### ISSUE THREAD

**Issue by Yugraj-Atul-Chauhan** [pypa/setuptools#2277]
![Screenshot_2020-07-24_00-09-48](https://user-images.githubusercontent.com/68708515/88325129-4eb14f00-cd42-11ea-8199-72ce3a9736fb.png)

Please suggest..!!

**Comment by jaraco** [comment]
Please see the [Python 2 sunset docs](https://setuptools.readthedocs.io/en/latest/python%202%20sunset.html) for guidance.
