### ISSUE TITLE
Error running either python3 setup.py install "TypeError: must be str, not NoneType"

### ISSUE THREAD

**Issue by marlon-shiftone** [pypa/setuptools#2283]
I just installed an API pyunicorn and when I import it I get an error. It tells me that it cannot import setup. Therefore, I went to install setup.py. My steps were:
First:

`cd /home/user/python-3.7.2/`

Second:

`python3 setup.py install`
or
`pip3 install .`

It gives the following error:

```
Obtaining file:///home/user/Python-3.7.2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/marlon/Python-3.7.2/setup.py", line 30, in <module>
        set_compiler_flags('LDFLAGS', 'PY_LDFLAGS_NODIST')
      File "/home/marlon/Python-3.7.2/setup.py", line 27, in set_compiler_flags
        sysconfig.get_config_vars()[compiler_flags] = flags + ' ' + py_flags_nodist
    TypeError: must be str, not NoneType
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/user/Python-3.7.2/
```

How to solve it?

**Comment by McSinyx** [comment]
Hello there, could you please point us to the `setup.py` script, since it doesn't seems to be [pyunicorn's](https://github.com/pik-copan/pyunicorn/blob/master/setup.py)?

**Comment by marlon-shiftone** [comment]
Hello, 

Thanks for your answer. Here is the scritp:

import sys, os, importlib.machinery, re, optparse
from glob import glob
import importlib._bootstrap
import importlib.util
import sysconfig

from distutils import log
from distutils.errors import *
from distutils.core import Extension, setup
from distutils.command.build_ext import build_ext
from distutils.command.install import install
from distutils.command.install_lib import install_lib
from distutils.command.build_scripts import build_scripts
from distutils.spawn import find_executable

cross_compiling = "_PYTHON_HOST_PLATFORM" in os.environ

# Set common compiler and linker flags derived from the Makefile,
# reserved for building the interpreter and the stdlib modules.
# See bpo-21121 and bpo-35257
def set_compiler_flags(compiler_flags, compiler_py_flags_nodist):
    flags = sysconfig.get_config_var(compiler_flags)
    py_flags_nodist = sysconfig.get_config_var(compiler_py_flags_nodist)
    sysconfig.get_config_vars()[compiler_flags] = flags + ' ' + py_flags_nodist

set_compiler_flags('CFLAGS', 'PY_CFLAGS_NODIST')
set_compiler_flags('LDFLAGS', 'PY_LDFLAGS_NODIST')

**Comment by McSinyx** [comment]
The code you provided seems to be a potion of [CPython](https://github.com/python/cpython)'s setup.py.  Normally, your GNU/Linux distribution should already provide a Python interpreter; and the build instruction (just in case one wants to compile it oneself) is available under CPython's README.

However, could you please clarify what you are trying to do and what you expect to happen by executing the script, since it isn't clear what it has to do with pyunicorn?

**Comment by marlon-shiftone** [comment]
Thanks for your comment. I just installed the API pyunicorn:
```
Requirement already satisfied: pyunicorn in /usr/local/lib/python3.6/dist-packages (0.6.1)
Requirement already satisfied: numpy>=1.14 in /usr/local/lib/python3.6/dist-packages (from pyunicorn) (1.15.4)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.6/dist-packages (from pyunicorn) (1.1.0)
Requirement already satisfied: python-igraph>=0.7 in /usr/local/lib/python3.6/dist-packages (from pyunicorn) (0.8.2)
Requirement already satisfied: texttable>=1.6.2 in ./.local/lib/python3.6/site-packages (from python-igraph>=0.7->pyunicorn) (1.6.2)
```
But when I import it, have this error:
```
File "/usr/local/lib/python3.6/dist-packages/spyder_kernels/customize/spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "/usr/local/lib/python3.6/dist-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/marlon/Shift One/Projeto Engie/projeto_engie/testes.py", line 14, in <module>
    import pyunicorn as pu

  File "/usr/local/lib/python3.6/dist-packages/pyunicorn/__init__.py", line 43, in <module>
    from setup import __version__

  File "/usr/local/lib/python3.6/dist-packages/setup.py", line 27, in <module>
    'Topic :: Utilities',

  File "/usr/lib/python3.6/distutils/core.py", line 136, in setup
    raise SystemExit(gen_usage(dist.script_name) + "\nerror: %s" % msg)

SystemExit: usage: testes.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: testes.py --help [cmd1 cmd2 ...]
   or: testes.py --help-commands
   or: testes.py cmd --help

error: no commands supplied
```
Then I've followed the instructions elsewhere to install setup.py, which seems to be the source of bug.

**Comment by McSinyx** [comment]
Given the following import

    File "/usr/local/lib/python3.6/dist-packages/pyunicorn/__init__.py", line 43, in <module>
      from setup import __version__

I strongly suggest you to file an issue over pyunicorn to report that

1. Their `setup.py` does not install itself to be available for import.
2. It is conventionally discouraged to install the setup script to site packages and import it.

From the content of your `/usr/local/lib/python3.6/dist-packages/setup.py`, it is hinted that some other project also tries to do (2) and it might be helpful for them if you file an issue over there as well.  Moreover, you might want to avoid installing packages from PyPI (which are not audited) to your root filesystem: using `pip --user` might be a safer solution and a virtual environment may even be a better practice.

**Comment by marlon-shiftone** [comment]
Hello, thanks for your comment, once again. In a nutshell:

a) the procedure to install setup.py is not correct;
b) the problem is with pyunicorn code.
(?)

**Comment by McSinyx** [comment]
setup.py is used to install things, not to be installed, so yes, the issue is with pyunicorn

**Comment by marlon-shiftone** [comment]
Thank you so much. I've never thought it would be so hard to use an API. :/

**Comment by McSinyx** [comment]
You're welcome.  We humans make mistakes all the time (I'd argue that it is one of the things that makes us humans :smile:), so don't let others' mistake let you down, take it as opportunity to learn from (e.g. about Python packaging in this case :wink:).  In your very case you might want to install an older version (0.6.0.post1) until it gets fixed.

**Comment by marlon-shiftone** [comment]
Hey I just fixed it. I have to thank you very much. 

The source of error was:
"[T]he line in question is referring to __version__ from the setup.py file [..] doesn't exist in the site-packages package." from [https://github.com/pik-copan/pyunicorn/issues/129](url). 

Solution:

I've copied the script in `setup.py` and remove the line containing  `from setup import __version__` by creating a new file `__init__py`. Then I've removed the old one and replace by the one I've create. And it worked! :D

Happy!
