### ISSUE TITLE
Incompatible install in (summarize your environment)

### ISSUE THREAD

**Issue by PriyankaR80** [pypa/setuptools#2285]
My ansible server does not have these modules to run on palo alto firewall GUI for automation. For that i tried installing this, but getting this error. Please help me how do i get py packages for the below modules.

1) panos_zone_facts
2) panos_ip_registered_facts

$ pip install --user pan-python
/usr/lib/python2.7/site-packages/pkg_resources/py2_warn.py:21: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please follow up at
https://bit.ly/setuptools-py2-warning.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
Requirement already satisfied (use --upgrade to upgrade): pan-python in /usr/lib/python2.7/site-packages
You are using pip version 19.1.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by McSinyx** [comment]
Hi, I think this is a warning rather than an error.  For more information, please refer to the [Python 2 Sunset](https://setuptools.readthedocs.io/en/latest/python%202%20sunset.html) page in the documentation.
