### ISSUE TITLE
SetupTools

### ISSUE THREAD

**Issue by Vinod3003** [pypa/setuptools#2290]
/usr/lib/python3/dist-packages/pkg_resources/py2_warn.py:21: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please follow up at
https://bit.ly/setuptools-py2-warning.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)

**Comment by McSinyx** [comment]
This is strange, somehow Python < 3 is recognized on Python 3.  Could you please provide more information about your platform, including (but not exclusive to, the more the merrier) the OS and its version, Python version and how it was installed, setuptools version and how it was installed.

**Comment by Vinod3003** [comment]
> This is strange, somehow Python < 3 is recognized on Python 3. Could you please provide more information about your platform, including (but not exclusive to, the more the merrier) the OS and its version, Python version and how it was installed, setuptools version and how it was installed.
