### ISSUE TITLE
include/exclude for find_namespace_packages doesn't work for sdists

### ISSUE THREAD

**Issue by kgreav** [pypa/setuptools#2292]
What the title says. Works as expected for bdist_wheel, but for sdist the include and exclude params for find_namespace_packages appear to be completely ignored. This may also effect find_packages(); I didn't test.

This repository https://github.com/kgreav/broken_setuptools has an example project - run either of the setup.py files with sdist and compare with a bdist_wheel

**Comment by pganssle** [comment]
The `packages`  argument only refers to what gets installed, not what gets included in distributions. If you want to exclude something from an sdist, you do it in `MANIFEST.in`, though it seems like a rare situation to me to want to only ship a subset of the stuff in your `src/` directory.

**Comment by kgreav** [comment]
A bit of background:
My use case is that I want to split a single source repository into several namespace packages. This wasn't previously a problem because they were all in separate repositories, but that was cumbersome and unnecessary so we chose to amalgamate them into a single repo; however I still want to package each namespace separately. I don't really mind that sdist doesn't work because I plan on distributing wheels anyway, but this discrepancy cost me a bit of time debugging. I don't think MANIFEST.in works here, as I'd require a specific MANIFEST.in for each package, which would amount to splitting out everything into separate repositories again anyway.

There are a few problems I can see here, I think, but at a base if we assume everything is working as expected, then at the very least I would argue that include/exclude shouldn't be silently ignored for sdist, and/or documentation should be updated accordingly (I'd even go as far as saying a formal definition of sdist should be documented, which it seems it's [currently not](https://discuss.python.org/t/purpose-of-an-sdist/4639)).

However, it seems to me that find_[namespace]_packages defines what the package and distribution is and that it's perfectly acceptable to have one source that creates multiple distributions and packages (especially in the context of namespaces).
Given peoples current definition of a source distribution as being "whatever is required to build a wheel and meet the distribution requirements of any included third party code", then having the complete source for all other packages that are potentially built alongside it (but not necessary to build the package itself) in the equivalent source distribution seems excessive.

**Comment by pganssle** [comment]
@kgreav That use case is not really supported. If you want to use `setuptools`, you have a single `setu.cfg` and/or `setup.py` in the repository root. You'll have to come up with your own solutions for unorthodox package configurations.
