### ISSUE TITLE
develop mode does not respect src structure

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#230]
Originally reported by: **marscher (Bitbucket: [marscher](http://bitbucket.org/marscher), GitHub: [marscher](http://github.com/marscher))**

---

Assume you have project with a src folder:

```
#!python

root/
root/setup.py
root/src/my_pkg/__init__.py
....
```

in setup.py one have mapped the src folder, so it can be found during installation.

```
#!python

setup( ....
   package_dir = { 'my_pkg' : 'src' } 
)
```

If one tries to install an egg link to the pkg via setup.py develop, this mapping is happily ignored. I'am not sure, if this is an issue either with setuptools or distutils. Symlinking my_pkg to the root fixes the problem.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/230

**Comment by jaraco** [comment]
@RonnyPfannschmidt has suggested a few options:
- symlink the packages during develop install
- create shim file
- create meta import hook

All of these run into challenges thinking about the total workflow (how are they registered/uninstalled).

If someone could put together a routine or package that demonstrates a technique for installing such a hook, then we can work to devise a workflow around it to use within the develop command and installers.

**Comment by RonnyPfannschmidt** [comment]
i documented some of it in https://mail.python.org/pipermail/distutils-sig/2017-September/031498.html

i made a prior implementation in https://github.com/RonnyPfannschmidt/gumby_elf/blob/03391bdf0cc66faaa2a5e034769e557c31974fd9/src/packing.py#L34-L43

i believe the best prospect is building/installing the dist info alongside a bootstrapped and a altered record file

**Comment by nthienan** [comment]
Hi there,

Any updates on this?

**Comment by jaraco** [comment]
No updates, although the packaging standard have developed and now there is some standards for supporting editable installs. Perhaps supporting that PEP could open up opportunities for this use case.

**Comment by abravalheri** [comment]
I believe v64.0.3+ solves the problem with `package_dir` and editable installs reported here.

**Comment by gnaggnoyil** [comment]
I'm sorry I tried setuptools 65.5.0 with python 3.10.9 with the case provided by OP and the problem still seems to exist. I ran `python setup.py develop` and then ran `import my_pkg` in a python interpreter. I still got the "ModuleNotFoundError: No module named 'my_pkg'" error here.

**Comment by abravalheri** [comment]
Hi @gnaggnoyil please note that it is impossible to fix this problem if you are using `python setup.py develop`. This is well known limitation of `develop`.

If you want to give it a try to editable install, please use `pip install -e .`

**Comment by gnaggnoyil** [comment]
@abravalheri Hello, I also tried `pip install -e .` and the result was the same. I also tried to inspect the files that pip installed in my venv and the files seems to be same as those installed through `setup.py develop`.

**Comment by abravalheri** [comment]
In this case, pip might be treating your project with the legacy procedure.

You can try adding `pyproject.toml` or run pip with the `--use-pep517` flag (this is going to be the default in pip 23.1).

If that does not work. Please open a new issue with a [minimal example that reproduces your error](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by DaanVanVugt** [comment]
Using the `--use-pep517` flag fixed this problem for me.
