### ISSUE TITLE
Update vendored packaging to 20.4 (latest release)

### ISSUE THREAD

**Issue by mattip** [pypa/setuptools#2310]
In the interests of moving PEP 600 (xref tracking issue pypa/manylinux#542) forward, what is "protocol" for updating the vendored version of packaging to 20.4 (which includes parsing for the PEP 600 manylinux spec)? Are there checks or tests that need updating as well?

**Comment by jaraco** [comment]
The protocol is mostly ad-hoc, but it's basically:

- check for any backward-incompatible changes advertised by the vendored package and account for those in the codebase.
- update the vendored package declaration (both in pkg_resources and setuptoools)
- run the `paver update_vendored` routine.
- commit the changes, run the tests, fix any issues, submit a PR.
