### ISSUE TITLE
Remove linting checks from the test suite

### ISSUE THREAD

**Issue by pganssle** [pypa/setuptools#2317]
Currently the linting checks are run with `pytest-flake8` or whatever. This causes problems because it prevents a very common workflow, which is to iterate until you have something that works, then run the linter over it and clean up all linting failures. I've found it incredibly frustrating ever since it was introduced.

It also means something like `git bisect run tox -e py38` will *probably* fail pointlessly in a bunch of places, because we don't do squash merges and we don't do anything to enforce that the test suite passes on every commit. This is already *something* of a problem because the tests themselves might fail in intermediate commits, but it's made much worse by the fact that trailing whitespace or something can cause the test suite to fail.

We should just move linting checks into their own separate `tox` environment [like so](https://github.com/pganssle/zoneinfo/blob/4299bfd7623934acc6f27b32744b02a147912120/tox.ini#L87-L97) and add a required CI job to enforce it.

**Comment by jaraco** [comment]
I'm -1 on this change. If delinting is something that should be done by a human, then it should be presented to the human in the basic case. It should be possible to do most of the work by running the tests on a single, supported environment and only rarely find edge cases on other platforms. By deferring linting, you're almost certainly going to encourage pushing of broken code only to re-write history to make it look as if that code never failed. That is, you'll create the problem you're trying to prevent (intermediate commits with linter errors).

More importantly, this change causes setuptools to diverge from the best practices that I'm working to develop in jaraco/skeleton which I'd like to be able to apply to this project also. While I'm out-voted here, I'd hate to capitulate to a workflow that I know to cause me trouble.

Why not instead run the linter by default and have an option to disable it? It's annoying that pytest doesn't offer such an option, but if it did, you could run `tox -- --no-flake8` for your fast-iterating tests or bisect operations to avoid the annoying failures while still enabling test-the-things-the-project-cares-about by default.

WDYT?

**Comment by pganssle** [comment]
This is not deferring linting, it just makes it a second, required action. We can / should also add pre-commit configuration for this as well.

**Comment by jaraco** [comment]
This request comes at a particularly bad time as this past weekend I worked on [a project](/pypa/twine) that separates out linting and type checks into separate environments. I drafted a very small fix for a pending PR, ran the tests, then pushed it to another user's repo, only to have the linter fail. I fixed the lint error only to have the type checks fail. I spent more time fussing with the order of imports and adding redundant type declarations than I did working out the change. It was an unpleasant experience that I want to avoid in the projects I spend a lot of time on.

I've found that you can currently use `-k 'not flake8'` (e.g. `tox -- -k 'not flake8'`) to bypass the flake8 checks. That should suit the workflows you described while also keeping the tests in the default workflow. Does that satisfy the need you've described? I'm going to start using it in my projects when I want to suppress linter checks temporarily while working out more essential concerns.

**Comment by pganssle** [comment]
No, that doesn't especially help, and I think the mixing of linting and tests is a very unfortunate workflow (not to mention many of the things excluded from coverage measurement are also now being excluded from linting, which I fixed in #2320). But you are much more active on this project than I am, and I am certainly not volunteering to take on the lion's share of the work here, so I will leave you to do whatever you want.

**Comment by jaraco** [comment]
With #2388, you have new options to disable the linter(s):

- remove/omit the plugins from the test environment (i.e. `.tox/python/bin/pip uninstall pytest-flake8 pytest-cov`).
- disable the plugins at runtime (e.g. `tox -- -p no:flake8` or `PYTEST_ADDOPTS=-p no:flake8`).
