### ISSUE TITLE
imoprt beautifulshop failed

### ISSUE THREAD

**Issue by mark463** [pypa/setuptools#2323]
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45

**Comment by jaraco** [comment]
Doesn't look like `beautifulshop` is a package:

```
~ $ pip install beautifulshop
ERROR: Could not find a version that satisfies the requirement beautifulshop (from versions: none)
ERROR: No matching distribution found for beautifulshop
```

Please see http://bit.ly/setuptools-py2-sunset for more details.
