### ISSUE TITLE
Guidance requested: setuptools doesnt find my .py file in CI but does on local builds

### ISSUE THREAD

**Issue by drewmullen** [pypa/setuptools#2325]
I'm looking for some guidance on how to approach a problem im seeing while building an `sdist`. Specifically, under what circumstances would `python setup.py sdist` skip over python files?

**Summary:**
I have a script that we use to package all our python code intended to be used for AWS Lambda and publishes it to s3. We run it from a container in CI that is sourced from a SHA (meaning it is the **exact same container image** every time). When i run the container locally to test the build / publication it works fine. However, when I run it from github actions, it mysteriously skips over **only** the python package we're trying to publish.

Unfortunately this code isn't public so I cannot share but... Here is what the repo directory looks like
![image](https://user-images.githubusercontent.com/3812162/90056481-f15b4e80-dcac-11ea-8a44-2a6e8995b93f.png)

```bash
$ cat setup.py
...
setup(
    name='replication_report',
    packages=find_packages(exclude=('tests')),
    include_package_data=True,
    install_requires=requirements
)

$ cat MANIFEST.in
recursive-include templates *.j2
prune tests
```

output of sdist install when running container **locally** (notice the last line i show is the replication_report.py file):
```
+ /host/awslambda/replication_report/.build/virtualenv/bin/python /host/awslambda/replication_report/setup.py sdist --formats=zip --dist-dir /host/awslambda/replication_report/.build
running sdist
running egg_info
writing replication_report.egg-info/PKG-INFO
writing dependency_links to replication_report.egg-info/dependency_links.txt
writing requirements to replication_report.egg-info/requires.txt
writing top-level names to replication_report.egg-info/top_level.txt
reading manifest file 'replication_report.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tests'
writing manifest file 'replication_report.egg-info/SOURCES.txt'
running check
creating replication_report-0.1.0
creating replication_report-0.1.0/replication_report.egg-info
creating replication_report-0.1.0/templates
copying files to replication_report-0.1.0...
copying MANIFEST.in -> replication_report-0.1.0
copying README.md -> replication_report-0.1.0
copying replication_report.py -> replication_report-0.1.0
...
```

output of sdist when install running in CI (and an `ls` to prove the files are there before packaging):
notice the replication_report.py file doesnt appear in the sdist build
```
+ ls -la /__w/CloudInfra/CloudInfra/awslambda/replication_report
total 76
drwxr-xr-x 9 root root 4096 Aug 12 18:49 .
drwxr-xr-x 9 root root 4096 Aug 12 18:49 ..
drwxr-xr-x 3 root root 4096 Aug 12 18:49 build
drwxr-xr-x 3 root root 4096 Aug 12 18:49 .build
drwxr-xr-x 2 root root 4096 Aug 12 18:49 data
drwxr-xr-x 2 root root 4096 Aug 12 18:49 dist
-rw-r--r-- 1 root root    0 Aug 12 18:49 __init__.py
-rw-r--r-- 1 root root   44 Aug 12 18:49 MANIFEST.in
-rw-r--r-- 1 root root    5 Aug 12 18:49 .python-version
-rw-r--r-- 1 root root 1101 Aug 12 18:49 README.md
drwxr-xr-x 2 root root 4096 Aug 12 18:49 replication_report.egg-info
-rw-r--r-- 1 root root 6343 Aug 12 18:49 replication_report.py
-rw-r--r-- 1 root root   86 Aug 12 18:49 requirements_dev.txt
-rw-r--r-- 1 root root  150 Aug 12 18:49 requirements.txt
-rw-r--r-- 1 root root 1238 Aug 12 18:49 setup.py
-rw-r--r-- 1 root root  434 Aug 12 18:49 shell.nix
drwxr-xr-x 2 root root 4096 Aug 12 18:49 templates
drwxr-xr-x 2 root root 4096 Aug 12 18:49 tests
-rw-r--r-- 1 root root  840 Aug 12 18:49 tox.ini
+ /__w/CloudInfra/CloudInfra/awslambda/replication_report/.build/virtualenv/bin/python /__w/CloudInfra/CloudInfra/awslambda/replication_report/setup.py sdist --formats=zip --dist-dir /__w/CloudInfra/CloudInfra/awslambda/replication_report/.build
running sdist
running egg_info
writing replication_report.egg-info/PKG-INFO
writing dependency_links to replication_report.egg-info/dependency_links.txt
writing requirements to replication_report.egg-info/requires.txt
writing top-level names to replication_report.egg-info/top_level.txt
reading manifest file 'replication_report.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tests'
writing manifest file 'replication_report.egg-info/SOURCES.txt'
running check
creating replication_report-0.1.0
creating replication_report-0.1.0/replication_report.egg-info
creating replication_report-0.1.0/templates
copying files to replication_report-0.1.0...
copying MANIFEST.in -> replication_report-0.1.0
copying README.md -> replication_report-0.1.0
copying setup.py -> replication_report-0.1.0
copying replication_report.egg-info/PKG-INFO -> replication_report-0.1.0/replication_report.egg-info
copying replication_report.egg-info/SOURCES.txt -> replication_report-0.1.0/replication_report.egg-info
copying replication_report.egg-info/dependency_links.txt -> replication_report-0.1.0/replication_report.egg-info
copying replication_report.egg-info/requires.txt -> replication_report-0.1.0/replication_report.egg-info
copying replication_report.egg-info/top_level.txt -> replication_report-0.1.0/replication_report.egg-info
copying templates/snapshot_template.html.j2 -> replication_report-0.1.0/templates
Writing replication_report-0.1.0/setup.cfg
creating '/__w/CloudInfra/CloudInfra/awslambda/replication_report/.build/replication_report-0.1.0.zip' and adding 'replication_report-0.1.0' to it
```

Again - I'm not asking yall to solve this issue since there are several items at play: a ci runner, a container, a script that executes this... If yall could help me with:
- advice on what might cause setup.py to **not** include python files
- any verbosity flags / debug flags i can include when its run in CI to help figure out is happening that it misses the file

**Comment by jaraco** [comment]
One thing that might be going on - are you using `setuptools_scm` or any other package that supplies a `setuptools.file_finders`? Those plugins can augment the list of files "found" in the source. If that's only present in your local builds but not in your CI, or even if it's present in your CI, but the underlying tool (like git) isn't present, that could cause files to be missed. The files setuptools [includes by default](https://github.com/pypa/setuptools/blob/fac13f0d9950b7c06de650bf4ea226cb2789afc3/setuptools/_distutils/command/sdist.py#L210-L230) does not include python modules in the root that aren't mentioned in the setup.py, so I would not expect that file to be included in the sdist by default. Indeed:

```
rr $ cat > setup.py
import setuptools
setuptools.setup()
rr $ touch foo.py
rr $ pip-run -q setuptools -- setup.py sdist
running sdist
running egg_info
creating UNKNOWN.egg-info
writing UNKNOWN.egg-info/PKG-INFO
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing top-level names to UNKNOWN.egg-info/top_level.txt
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
running check
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

warning: check: missing required meta-data: name, url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating UNKNOWN-0.0.0
creating UNKNOWN-0.0.0/UNKNOWN.egg-info
copying files to UNKNOWN-0.0.0...
copying setup.py -> UNKNOWN-0.0.0
copying UNKNOWN.egg-info/PKG-INFO -> UNKNOWN-0.0.0/UNKNOWN.egg-info
copying UNKNOWN.egg-info/SOURCES.txt -> UNKNOWN-0.0.0/UNKNOWN.egg-info
copying UNKNOWN.egg-info/dependency_links.txt -> UNKNOWN-0.0.0/UNKNOWN.egg-info
copying UNKNOWN.egg-info/top_level.txt -> UNKNOWN-0.0.0/UNKNOWN.egg-info
Writing UNKNOWN-0.0.0/setup.cfg
creating dist
Creating tar archive
removing 'UNKNOWN-0.0.0' (and everything under it)
```

Notice how "foo.py" doesn't get copied? That's the default behavior.

So your next step should be to try to figure out what is enabling setuptools to add that file. It's most likely that setuptools_scm and git are installed.

Regardless, your easiest course of action is probably to add an `include *.py` or similar to MANIFEST.in. If you want to rely on scm metadata, then I'd make sure that dependency is present everywhere.

**Comment by drewmullen** [comment]
thanks for your input! you proposed I think about the problem from the opposite perspective: instead of why _isnt_ ci grabbing the file... why _is_ my local env / docker container grabbing the file. that was an interesting way to think. unfortunately, i couldnt ever determine why **but** using the `MANIFEST.in` file with `include *.py` worked like a charm.

I did not have any setuptools-scm installed, i was in a pretty bare virtualenv. 

thanks again!

**Comment by EricBuist** [comment]
Same thing for me, except that setuptools never finds any .py files. I'm searching since one hour, seems I am the only one having the issue. I'm working at a company, so I cannot provide sample projects with proprietary information. This is really blocking me, as tools are too complex and/or fragile, requiring non-obvious micro-steps to get working.

**Comment by abravalheri** [comment]
Hi @EricBuist, if you have a problem and cannot disclose the code, please create a new issue with a dummy [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example) that shows a similar behaviour to what you are experiencing.

Ideally it is good to use a virtual environment or a docker container for that.
