### ISSUE TITLE
Create GitHub "releases"?

### ISSUE THREAD

**Issue by hugovk** [pypa/setuptools#2328]
Tags show up at https://github.com/pypa/setuptools/releases

When tagging and releasing, would it be possible to also publish a GitHub release of that tag?

This enables users to watch "Releases only" for this repo, and get notifications on new release via the GH UI.

How to do it:

1. https://github.com/pypa/setuptools/releases/new
   * or https://github.com/setuptools/setuptools/releases/ -> "Draft a new release"
2. Select tag in "Tag version" box (e.g. v40.0.0)
3. Click "Publish release"

There's no need to add a title or body text.

Example:

* https://github.com/hugovk/setuptools/releases
* https://github.com/hugovk/setuptools/releases/tag/v40.0.0

This can be automated using GitHub Actions:

* https://github.com/actions/create-release

Thanks!

**Comment by jaraco** [comment]
I'd like to have this feature. Is there a way that it can be made to work without adding any steps to the developer's workflow? That is, the current release workflow is to run `tox -e finalize`, which tags a commit. If the tests pass for that commit, a release is cut through CI through `tox -e release`. I'd like the process of creating a GitHub release to happen at the same time as the upload is made to PyPI (i.e. during the release), probably just after.

Preferably this behavior should be implemented at [jaraco/skeleton](/jaraco/skeleton) and then ported over here.

Would you be willing to work out the implementation?

**Comment by jaraco** [comment]
Extra credit if the release notes can be extracted from the changelog so they're actually published.

**Comment by hugovk** [comment]
Yep, I can have a look!

Here's the simplest, using GitHub Actions:

* https://github.com/hugovk/setuptools/commit/ec64870a325a836fea21dee116910c6720bdd0dd

It runs when a tag is pushed, for example in my fork:

* https://github.com/hugovk/setuptools/runs/992769824?check_suite_focus=true
* https://github.com/hugovk/setuptools/releases/tag/v49.6.0.3

Pros:

* runs automatically in the repo when tags pushed
* no need for any extra tokens or tools
* no extra steps for the developer

Cons:

* This doesn't quite fit the required flow: it creates the release as part of `tox -e finalize` (tag pushed), not `tox -e release` (after tests pass and developer decides to release)

---

To do it as part of `tox -e release`, I think the best thing to do is call the GitHub API. This'll need the developer to create a GH token and (probably) store it an an env var.

First question, would that be an acceptable requirement? (I see `tox -e release` uses `TWINE_PASSWORD` and `TIDELIFT_TOKEN`, so I'd guess so.)

There's a bunch of CLI tools that already exist for creating releases, or it should be pretty straightforward to call the API via requests or curl.

* https://github.com/github/hub
  * `+` made by GH
  * `-` wraps `git` command

* https://github.com/release-it/release-it
   * `+` 3.4k stars
   * `-` ? written in node

* https://github.com/github-release/github-release
   * `+` 1.3k stars
   * `-` ? written in Go

* https://github.com/j0057/github-release
  * `+` Python
  * `-` 48 stars: less popular, less well-maintained? 

* own Python script
  * eg. https://stackoverflow.com/q/38153418/724176
  * `+` written in Python
  * `-` needs maintaining
  * `+` probably easy enough

* own curl script
  * eg. https://www.barrykooij.com/create-github-releases-via-command-line/
  * `+` simple
  * `-` needs maintaining
  * `+` probably easy enough

**Comment by hugovk** [comment]
Well that's pretty easy:

```python
#!/usr/bin/env python3
import json
import os
import sys
from urllib.request import Request, urlopen

repo = sys.argv[1]
tag = sys.argv[2]

token = os.environ["GITHUB_TOKEN"]

url_template = "https://{}.github.com/repos/" + repo + "/releases"

json.loads(
    urlopen(
        Request(
            url_template.format("api"),
            json.dumps({"tag_name": tag, "name": tag}).encode(),
            headers={
                "Accept": "application/vnd.github.v3+json",
                "Authorization": "token " + token,
            },
        )
    )
    .read()
    .decode()
)
```

```sh
python create-release.py "hugovk/setuptools" v49.6.0.5
```

-> https://github.com/hugovk/setuptools/releases/tag/v49.6.0.5

Re: https://docs.github.com/en/rest/reference/repos#releases

**Comment by hugovk** [comment]
Please see PR https://github.com/pypa/setuptools/pull/2338.

**Comment by jaraco** [comment]
I've seen the proposed fix isn't working, because the mapping from `Github-token` to `GITHUB_TOKEN` wasn't present :(.

**Comment by hugovk** [comment]
I got the notification for https://github.com/pypa/setuptools/releases/tag/v50.1.0, thank you!
