### ISSUE TITLE
Add support for extra_index_url (config and/or option)

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#233]
Originally reported by: **myaskevich_kyriba (Bitbucket: [myaskevich_kyriba](http://bitbucket.org/myaskevich_kyriba), GitHub: Unknown)**

---

We've got both find-links and index-url config parameters available in user pydistutils config file. But none of them fit in my case.

Why not just mimic the pip behavior and try extra one and fall back if nothing's found there?

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/233

**Comment by sharksforarms** [comment]
Hello, is there any updates on this issue?

Here are the dependencies of my local package `foo`:
```
foo (local repo)
     \
       bar (remote repo)
```
Here is my `~/.pydistutils.cfg`
```
[easy_install]
index-url = http://pypi.local
find_links = http://pypi.remote
```
Here is my test case:
`easy-install foo`

I am getting the following output:
```
Searching for foo
Reading http://pypi.remote
Reading http://pypi.local
Downloading http://pypi.local/.../foo.whl
Best match: foo 0.0.0
Processing ....
Installing ...
...
Processing dependencies for foo
Searching for bar
Reading http://pypi.local/.../simple/bar/
Couldn't find index page for 'bar' (maybe misspelled?)
No local packages or working download links found for 'bar'
```

I would like to be able to specify multiple index-urls, as you can with pip.

**Comment by pganssle** [comment]
I think it's not unreasonable to do this, but I think it depends on how much longer we'll have easy_install around. The use case for this is a lot less compelling with PEP 518.

**Comment by abravalheri** [comment]
Hello, I suppose we can close this issue now that `easy_install` has been deprecated and widely replace by other installation means, such as `pypa/pip`.

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
