### ISSUE TITLE
50.0.0 release not on pypi

### ISSUE THREAD

**Issue by mgorny** [pypa/setuptools#2343]
The pypi project page lists 49.6.0 as the newest version. Is 50.0.0 usable?

**Comment by therealromster** [comment]
I would say no, I had to revert https://freenode.logbot.info/crux-devel/20200829#c4917932

**Comment by jaraco** [comment]
It looks like the [build of v50.0.0 failed for some spurious reason](https://dev.azure.com/jaraco/setuptools/_build/results?buildId=1193&view=results):

![image](https://user-images.githubusercontent.com/308610/91667984-91e7a600-ead6-11ea-9cff-4b17c045beb2.png)

**Comment by jaraco** [comment]
I tried to "Rerun failed jobs" and I get an error:

> No plan found for identifier 5e3649c7-a829-43d8-b77f-dbb194840cc7.

No idea what that's about.

I was able to ["Run new" the pipeline](https://dev.azure.com/jaraco/setuptools/_build/results?buildId=1219&view=results).

**Comment by jaraco** [comment]
> I would say no, I had to revert https://freenode.logbot.info/crux-devel/20200829#c4917932

This issue probably deserves its own issue.

**Comment by hugovk** [comment]
🚀 Now on PyPI!

* https://pypi.org/project/setuptools/50.0.0/
