### ISSUE TITLE
Vendored distutils incompatible with Python 3.5

### ISSUE THREAD

**Issue by sjoerdjob** [pypa/setuptools#2357]
As part of setuptools 50.0, the vendored ("local") distutils implementation has been chosen over the stdlib version.

Looking at https://github.com/pypa/setuptools/blob/17cb9d6bf249cefe653d3bdb712582409035a7db/setuptools/_distutils/util.py#L423 we see that `subprocess._optim_args_from_interpreter_flags()` is called. However, this is not present on Python 3.5.

**Comment by jaraco** [comment]
Indeed, running `tox -e py35` on the pypa/distutils repo, it fails tests... so yeah, that's a problem.

**Comment by jaraco** [comment]
pypa/distutils@cdcdda0405 fixes the NameError, but the tests still don't catch `subprocess._optim_args_from_interpreter_flags` :(

**Comment by jaraco** [comment]
Hilariously, there's a comment in subprocess that says "This function is only used by multiprocessing and the test suite".

**Comment by jaraco** [comment]
I've pushed a compatibility change for the reported issue. Can you test with [this patched build](https://m.devpi.net/jaraco/dev/setuptools/50.0.0.post20200831) in the environment that failed and report if there are any other incompatibilities?

**Comment by sjoerdjob** [comment]
Thank you for the patched build. The fix works insofar that it no longer fails on due to the AttributeError. It instead fails in a way that I believe to be issue https://github.com/pypa/setuptools/issues/2352
