### ISSUE TITLE
direct reference local module from pip freeze not being parsed with setuptool.setup

### ISSUE THREAD

**Issue by fenchu** [pypa/setuptools#2378]
I find that setuptools is not able to parse local modules with direct referencing generated from pip freeze:

If I uncomment the line below and install it afterwards with ```pip install C:/dist/work/api-testing/doc/python_ldap-3.3.1-cp38-cp38-win_amd64.whl``` it works fine.

I'm not sure this is an error in setuptools or pip, but according to PEP440 it is correct:
https://www.python.org/dev/peps/pep-0440/#direct-references

```
pip freeze | Select-String -Pattern 'python-ldap'
python-ldap @ file:///C:/dist/work/api-testing/doc/python_ldap-3.3.1-cp38-cp38-win_amd64.whl
```

```
>>> with open("requirements.txt") as f:
...     required_modules = f.read().splitlines()
... 
>>> required_modules
[..., 'python-ldap @ file:///C:/dist/work/api-testing/doc/python_ldap-3.3.1-cp38-cp38-win_amd64.whl', ...]

>>> import setuptools
>>> setuptools.setup(
...     name='apotek1-api-test',
...     url="<my gitlab repo path>",
...     version='0.1',
...     packages=setuptools.find_packages('tools'),
...     install_requires=required_modules,
...     scripts = [
...         'bin/zipreport.py',
...         'bin/jenkins.py',
...         'bin/status.py',
...         'bin/tag.py',
...         'bin/browserver.py'
...     ]
... )
error in apotek1-api-test setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid URL given

>>> setuptools.__version__
'41.2.0'
```

OS: windows10 2004
pip --version
pip 20.2.2 from c:\venv\apotek-api-testing\lib\site-packages\pip (python 3.8)
python --version
Python 3.8.5

**Comment by fenchu** [comment]
I upgraded setuptools to:
```
>>> setuptools.__version__ 
'50.1.0'
```

and it works:
```
Requirement already satisfied: python-ldap@ file:///C:/dist/work/api-testing/doc/python_ldap-3.3.1-cp38-cp38-win_amd64.whl from file:///C:/dist/work/api-testing/doc/python_ldap-3.3.1-cp38-cp38-win_amd64.whl in c:\venv\apotek-api-testing\lib\site-packages (from apotek1-api-test==0.1) (3.3.1)
```

So why do I drag around with setuptools 41.2 in python 3.8.5 ? there is no setuptools in my requirements.txt

Please close after a sane comment on this, we get warnings on pip all the time, but nothing on setuptools, I believed they were closely related.

**Comment by jaraco** [comment]
> So why do I drag around with setuptools 41.2 in python 3.8.5 ?

I don't understand the question.

> still no setuptools in my pip freeze

Try `pip freeze --all`. Pip excludes special packages. There are bugs proposing to change this special casing.
