### ISSUE TITLE
Incompatible install in SIFT Workstation v2020.7.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by amcap623** [pypa/setuptools#2384]
am getting this error trying to install SIFT workstation v2020.7.1 on Ubuntu 16.04. The install does not show me at the end Completed with Errors. It just stops. Below this error is the error from the saltstack.log

Running: sift-config-tools
Update returned exit code not zero
Error: Update returned exit code not zero
at ChildProcess. (/snapshot/sift-cli/sift-cli.js:529:23)
at ChildProcess.emit (events.js:196:13)
at maybeClose (internal/child_process.js:1011:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy.

Before opening an issue in GitHub, please check to see if
your apt system is healthy.

Try running 'apt-get update' then remove any packages that
aren't used by running 'apt-get autoremove'

sansforensics@siftworkstation: ~/Downloads
$
------------------------SALTSTACK.LOG ERROR--------------------------
Requirement already satisfied: pip in /opt/rekall/lib/python2.7/site-packages
(20.2.2)

  Requirement already satisfied: setuptools in /opt/rekall/lib/python2.7/site-packages
  (45.0.0)

  DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please
  upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop
  support for Python 2.7 in January 2021. More details about Python 2 support
  in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

  WARNING: The directory ''/home/sansforensics/.cache/pip'' or its parent directory
  is not owned or is not writable by the current user. The cache has been disabled.
  Check the permissions and owner of that directory. If executing pip with sudo,
  you may want sudo''s -H flag.

  ERROR: Package ''setuptools'' requires a different Python: 2.7.12 not in ''>=3.5'''
duration: 3512.975
name: /opt/rekall
result: false
start_time: '03:37:03.278404'

**Comment by jaraco** [comment]
I see the error `Requirement already satisfied: setuptools in /opt/rekall/lib/python2.7/site-packages
(45.0.0)` Setuptools dropped support for Python 2 at Setuptools 45. Please work with sift and/or salt stack to to identify why an incompatible version of Setuptools is being installed. If there's something Setuptools can do to help, feel free to write back or open a new issue.
