### ISSUE TITLE
Adopt the distutils documentation

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#2387]
In order to support deprecation of distutils in the stdlib, some project needs to host the documentation. As Setuptools is hosting the implementation with plans to merge it, Setuptools should host the documentation (with the intentions of also merging it).

**Comment by alvyjudy** [comment]
Since the [documentation for distutils](https://docs.python.org/3/library/distutils.html) has two parts (userguide and API reference), I'm thinking of putting the API reference into the references directory and slowly merge the tutorial part into our userguide. Would this be feasible?

**Comment by jaraco** [comment]
Yes. The first step will be importing the history from CPython. I've started that in the pypa/distutils project, but I don't believe I've merged that into master yet.

**Comment by jaraco** [comment]
In the [feature/distutils-docs branch](/pypa/setuptools/tree/feature/distutils-docs), I've started integrating the distutils docs, but I immediately run into problems with the new strict rendering:

```
Warning, treated as error:
/Users/jaraco/code/public/pypa/setuptools/docs/deprecated/distutils/apiref.rst:25:py:mod reference target not found: distutils.core
```

I tried replacing it with `setuptools._distutils.core` but the same error occurs.

@alvyjudy or @webknjaz Do either of you know what's the best way to change the `:mod:` and `:class:` and other references to work in the branch?

**Comment by webknjaz** [comment]
@jaraco I haven't checked that branch yet (will do) but here's what may be helpful to you. I was recently annoyed that intersphinx required using a CLI command with a not very well structured table output so I've made a simple autoupdated site with all the linkable objects in a few popular docs sites with usage examples: https://webknjaz.github.io/intersphinx-untangled/ (src: https://github.com/webknjaz/intersphinx-untangled -- if you want to add more sphinx sites there).

Back to the question: such errors occur if the module you're linking things that were not declared as targets of those types in Sphinx. And they would usually be declared if there's documents containing the markup. So can you tell me what page (and maybe subsection) are you trying to link against?

**Comment by webknjaz** [comment]
If I understand correctly, you're attempting to copy RST documents from CPython under the setuptools docs, right? Then maybe using https://webknjaz.github.io/intersphinx-untangled/docs.python.org/ and `Ctrl+F` would be helpful to find if the identifiers you wanted to use existed in the original docs.

**Comment by webknjaz** [comment]
> ```
> Warning, treated as error:
> /Users/jaraco/code/public/pypa/setuptools/docs/deprecated/distutils/apiref.rst:25:py:mod reference target not found: distutils.core
> ```
> 
> I tried replacing it with `setuptools._distutils.core` but the same error occurs.

Bear in mind, you're not linking the actual source code. You must link RST documents that have class/module definitions with such identifiers. Are those manually created or generated automatically?

I've already raised the questions of the missing setuptools autodocs @ https://github.com/pypa/setuptools/issues/1737. FWIW I've recently set up automatic refpages generation in cheroot and it's quite easy to do if that's what we want.

**Comment by webknjaz** [comment]
Also, these new docs may have link against docs.python.org. It's easy to make those work -- just enable intersphinx and add the site to the mapping.

**Comment by webknjaz** [comment]
Oh, I see. https://docs.python.org/3/distutils/apiref.html#module-distutils.core has `distutils.dist.Distribution` unlinked. So they probably use sphinx in a non-strict mode and ignore anything that doesn't have an existing target.

There are a few solutions to this:
1) Create a `.. class:: ` declaration for the missing target (example: https://github.com/pypa/setuptools/blob/109bde8/docs/deprecated/distutils/apiref.rst#L177) -- it'll be rendered as https://docs.python.org/3/distutils/apiref.html#distutils.core.Extension
2) Use `nitpick_ignore` in `conf.py`. Example: https://github.com/cherrypy/cheroot/blob/7268068/docs/conf.py#L104-L111
3) Drop the markup in favor of double backticks (I wouldn't go for this option)

**Comment by webknjaz** [comment]
I'll send a PR against that branch.

**Comment by webknjaz** [comment]
@jaraco https://github.com/pypa/setuptools/pull/2438 hope this helps

**Comment by jaraco** [comment]
I believe this work is done and the docs are adopted.
