### ISSUE TITLE
[TODO] Add PyPy3.7 to the CI matrix

### ISSUE THREAD

**Issue by webknjaz** [pypa/setuptools#2400]
It's been released today: https://twitter.com/pypyproject/status/1309419644340625409.

I think it should be added once at least one CI brings it on board. I've posted a few requests on their forums: https://github.com/actions/setup-python/issues/136 / https://travis-ci.community/t/add-pypy-7-3-2-support/10007?u=webknjaz.

**Comment by jaraco** [comment]
Sounds good. My preference is to focus on Github Actions, as they seem to have the most capability with the simplest design.

**Comment by abravalheri** [comment]
Hi @webknjaz, is the idea here to also add PyPy 3.8, or are we good with the current configuration?

**Comment by webknjaz** [comment]
Yep, add 3.8 too. This issue was filed before 3.8 even existed.

**Comment by webknjaz** [comment]
PyPy 3.10 is already in the CI.
