### ISSUE TITLE
Documentation of "Entry point" page has broken code sample formatting

### ISSUE THREAD

**Issue by ajnelson-nist** [pypa/setuptools#2404]
Hello,

I tried reviewing this page:
https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html

As it is today, there appear to be several broken sample code blocks.  Looking at the first example of this errant behavior, the page is rendering `.. code-block:: bash` and then what appears to be regular text of a file system hierarchy, but unfortunately does not have styling applied to its HTML:
```
<blockquote>
<div><dl class="docutils">
<dt>timmins/</dt>
<dd>timmins/__init__.py
timmins/__main__.py
setup.cfg # or setup.py
#other necessary files</dd>
</dl>
</div></blockquote>
```

Unfortunately, this makes the page difficult to read.

**Comment by hugovk** [comment]
Will be fixed by https://github.com/pypa/setuptools/pull/2410.

**Comment by ajnelson-nist** [comment]
Thank you for your attention to this!

**Comment by ajnelson-nist** [comment]
Thank you!  I'm glad to see the easier reading.
