### ISSUE TITLE
PEP517 pyproject.toml prevents project-local module from being imported during build

### ISSUE THREAD

**Issue by ktbarrett** [pypa/setuptools#2405]
## Background

A project I maintain, [cocotb](https://cocotb/cocotb), uses distutils to build several libraries and extension modules. Since there is quite a lot to it, we have most of build code partitioned off into a [separate module](https://github.com/cocotb/cocotb/blob/master/cocotb_build_libs.py) which is [imported](https://github.com/cocotb/cocotb/blob/master/setup.py) by setup.py. As mentioned in the comment above the import, this is okay since the build module is included the MANIFEST.in. This currently works.

## Problem

We have a pyproject.toml, but only for towncrier. I recently tried adding the following familiar lines necessary to make the project PEP517/518 compliant.

```toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
```

I get the following traceback

<details>

```
Using pip 20.2.2 from /home/kaleb/miniconda3/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-qzsqi0nm
Created temporary directory: /tmp/pip-req-tracker-tvat1n3p
Initialized build tracking at /tmp/pip-req-tracker-tvat1n3p
Created build tracker: /tmp/pip-req-tracker-tvat1n3p
Entered build tracker: /tmp/pip-req-tracker-tvat1n3p
Created temporary directory: /tmp/pip-install-pz90u3c3
Processing /home/kaleb/cocotb
  Created temporary directory: /tmp/pip-req-build-fq8xt9j6
  Added file:///home/kaleb/cocotb to build tracker '/tmp/pip-req-tracker-tvat1n3p'
    Created temporary directory: /tmp/pip-modern-metadata-quen39ee
    Running command /home/kaleb/miniconda3/bin/python /home/kaleb/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmppswbsf8w
    Traceback (most recent call last):
      File "/home/kaleb/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/home/kaleb/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/kaleb/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/home/kaleb/miniconda3/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/home/kaleb/miniconda3/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 59, in <module>
        from cocotb_build_libs import get_ext, build_ext
    ModuleNotFoundError: No module named 'cocotb_build_libs'
    Preparing wheel metadata ... error
```

</details>

## Reflection

It seems as though `setuptools.build_meta` does not have the same behavior as calling `python setup.py ...`, which is what I expect. Should `build_meta` handle the MANIFEST.in file? Or maybe just add the project root to `sys.path`? Is there some other `build-backend` entry point in setuptools I should be using? Is this bad practice in some way?

**Comment by ktbarrett** [comment]
Add the following line before the offending import prevents an issue. I'm just wondering why this is necessary?

```python
sys.path.append(path.dirname(__file__))
```

**Comment by pganssle** [comment]
Yes, this is known and desirable for build isolation. If you want to add additional local files to your path during the build, you should modify the path explicitly. It is better to fail loudly in a way that's easy to fix than to have confusing error messages or fragile configurations that are very hard to debug.
