### ISSUE TITLE
Hacktoberfest opt-in

### ISSUE THREAD

**Issue by abitrolly** [pypa/setuptools#2416]
This year https://hacktoberfest.digitalocean.com/ rules require a repository to have the `hacktoberfest` tag to participate. Mind adding it here?

**Comment by webknjaz** [comment]
I'm pretty sure this repo doesn't have the capacity to filter out spam adding that topic may generate. Instead, [if you have something meaningful to contribute](https://twitter.com/cherrypy/status/1311600792340701184), it's best to make a pull request and ask the maintainers to label it.

**Comment by jaraco** [comment]
Right - probably there's some underlying work that needs to happen more than having a hacktoberfest label. I suspect that someone needs to go through and triage bugs and identify ones suitable for hacktoberfest and tag those. It sounds like webknjaz' suggestion is workable, so let's go with that.
