### ISSUE TITLE
Sphinx setup should be stricter

### ISSUE THREAD

**Issue by webknjaz** [pypa/setuptools#2424]
I noticed that some of the docs pages are unreachable when navigating from the main RTD page. In particular, _I know_ that there's `history.rst` that is only accessible if one knows the URL upfront.

I tracked this to https://github.com/pypa/setuptools/pull/2097 which removes entries from the TOC but doesn't reintroduce them in other places.

Sphinx has a few toggles that make it nitpicky about warnings. I think this should be enabled in the CI to prevent such problems in the future. This should catch implicit orphan pages as well as dead references or typos.

**Comment by alvyjudy** [comment]
I take the blame for a lot of breaking links as I ran out of steam in the middle of the docs revamp. I think jaraco felt that the halfway efforts still made a readable documentation and decided to merge them anyways, and fix the issues subsequently. See (here)[https://github.com/pypa/setuptools/issues/2093#issuecomment-697985806] for the context

I do plan on making more changes here and there to fix those issues and am happy to see the doc is receiving more supports and attention:)

**Comment by webknjaz** [comment]
@alvyjudy please hold on with your PRs. I've got a huge change fixing many refs and enforcing the checks incoming. Let's merge it first so that the CI would verify any further changes automatically.

**Comment by webknjaz** [comment]
Here you go: https://github.com/pypa/setuptools/pull/2427.
