### ISSUE TITLE
Typo and missing link in quickstart

### ISSUE THREAD

**Issue by plattfot** [pypa/setuptools#2429]
Hi,
There is a typo in the [Entry points and automatic script creation section](https://setuptools.readthedocs.io/en/latest/userguide/quickstart.html#entry-points-and-automatic-script-creation). 

```
[options]
entry_points =
    [console_script]
    main = mypkg:some_func
```
`[console_script]` -> `[console_scripts]`.

And I'm assuming there should be a link to the entry_point documentation at the end of that section. Right now it just says "For detailed usage, including managing the additional or optional dependencies, go to entry_point."

This caused me some trouble when I was following [the quickstart guide](https://setuptools.readthedocs.io/en/latest/userguide/quickstart.html) to setup a python project of mine to use `setuptools` without a `setup.py`. As it wasn't installing any of my console scripts and I didn't see any errors or warnings about it when I ran `pip install . -U`. Changing `[console_script]` -> `[console_scripts]` fixed it for me.

Thanks

**Comment by jaraco** [comment]
Thanks for reporting this. Should be fixed now.
