### ISSUE TITLE
Unable to run 'setup.py bdist_rpm' target on CentOS 6.5 with setuptools-5.6

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#243]
Originally reported by: **Anonymous**

---

When trying to run the 'python setup.py bdist_rpm' command on a CentOS 6.5 host with an unpacked setuptools-5.6 tarball results in the following error:

<lots of output elided...>

running install_scripts
Installing easy_install script to /home/agooch/work/agooch-auspxdev01n00/3rdParty/setuptools/setuptools-5.6/build/bdist.linux-x86_64/rpm/BUILDROOT/setuptools-5.6-1.x86_64/usr/python-2.7.5/bin
Installing easy_install-2.7 script to /home/agooch/work/agooch-auspxdev01n00/3rdParty/setuptools/setuptools-5.6/build/bdist.linux-x86_64/rpm/BUILDROOT/setuptools-5.6-1.x86_64/usr/python-2.7.5/bin
writing list of installed files to 'INSTALLED_FILES'
- /usr/lib/rpm/brp-compress
- /usr/lib/rpm/brp-strip
- /usr/lib/rpm/brp-strip-static-archive
- /usr/lib/rpm/brp-strip-comment-note
  Processing files: setuptools-5.6-1.noarch
  error: Two files on one line: /usr/python-2.7.5/lib/python2.7/site-packages/setuptools/script
  error: File must begin with "/": (dev).tmpl

RPM build errors:
    Two files on one line: /usr/python-2.7.5/lib/python2.7/site-packages/setuptools/script
    File must begin with "/": (dev).tmpl
error: command 'rpmbuild' failed with exit status 1

Has anyone else encountered this?  Am I doing something wrong?  I tried it on several older versions with similar results.

Many thanks in advance.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/243

**Comment by abravalheri** [comment]
Hello, I suppose we can close this issue now that `bdist_rpm` has been deprecated.

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
