### ISSUE TITLE
Unable to build arm32 wheels on aarch64 kernel with 32bit userspace

### ISSUE THREAD

**Issue by aptalca** [pypa/setuptools#2443]
Hi, I'm with linuxserver.io and we build and publish various docker images. For our multi-arch builds, we try to use native builders as much as we can, but during a backlog, we spin up some aws builders to help.

We have no issues with `pip install cryptography` in a docker build on native hardware on x86_64, armhf and aarch64.

However, a unique situation arises when we do an armhf build on an aws graviton instance (arm64). Aws instances only come with aarch64 kernel and OS. We install the 32bit docker package, and we use a 32bit docker baseimage (32bit userspace) to build the final docker image. Unfortunately while building the wheel for cryptography in our 32bit docker image, it incorrectly detects the OS as aarch64 and pulls in the wrong dependencies, and as a result the build fails (I'm assuming setuptools is using `/proc` or something like that to determine arch)

Here's a log: https://pastebin.com/HFQ5en4e
This is on an arm64 device (odroid c2), inside a 32bit docker image. When the same image is built on an armhf device, no issues.

Here's an example multiarch repo for local testing:
https://github.com/linuxserver/docker-ldap-auth

Simple way to reproduce:

1. On an aarch64 device (aws graviton or odroid c2), clone the repo: git clone https://github.com/linuxserver/docker-ldap-auth, enter folder
2. Build the armhf image: `docker build -f Dockerfile.armhf .`
If the above steps are done on an armhf device, it builds successfully.

Most other pip wheels build fine on an arm64 device in an arm32 docker baseimage.

At first I wasn't sure if it was a pip issue so I opened an issue on their repo, but no replies so far: pypa/pip#8871
Then I tried https://github.com/pyca/cryptography/issues/5490 but it may be setuptools related instead. I would appreciate if you could let me know if this is not the right place.

Thanks

**Comment by doko42** [comment]
this is usually done in 32bit chroots, entering these with the linux32 (or setarch) command to set the 32bit personality.

**Comment by aptalca** [comment]
@doko42 You sir are a gentleman and a scholar.

Thanks so much for pointing me in the right direction. For others who may run into a similar issue, I prepended the systemd service `ExecStart`s of both `containerd` and `docker` with `setarch linux32 -B` and the docker service and the containers see the kernel as `armv8l` as opposed to `aarch64`. Pip install works just fine with cryptography inside a 32bit docker image on aws graviton. Also make sure you install the armhf docker package.
