### ISSUE TITLE
50.3.2 stopped including the documentation in the source distribution (50.3.0 still included it)

### ISSUE THREAD

**Issue by doko42** [pypa/setuptools#2449]
50.3.2 stopped including the documentation in the source distribution (50.3.0 still included it)

it's not mentioned ine changelog, I assume it's a bug.

**Comment by jaraco** [comment]
Actually, it was 50.3.1. The change was 73e379cc55ac1e9ec63c4ac30b75ecc82418f513 and it's fixed in d00fac7b86abd71664af6a28acd924eff7c79017.
