### ISSUE TITLE
Use of :sys_platform in extras_require fails when installed via source

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#245]
Originally reported by: **freakboy3742 (Bitbucket: [freakboy3742](http://bitbucket.org/freakboy3742), GitHub: [freakboy3742](http://github.com/freakboy3742))**

---

I have a setup.py file with the following declaration in it:

```
#!python
setup(
    name='mypackage'
    ...
    extras_require={
        ':sys_platform=="darwin"': ['mydependency']
    }
)
```

This is then packaged as a universal wheel, and as a source distribution, and uploaded to PyPI.

If I run `pip install mypackage` under OS X (which identifies as sys.platform == 'darwin'), the wheel distribution is used, both `mypackage` and `mydependency` are installed. 

However, if I run `pip install mypackage --no-use-wheel`, `mypackage` is installed, but `mydependency` is not.

For reference - the real package here is toga-demo 0.1.1; this has a dependency of `toga[cocoa]` under OS X. I've also been able to reproduce the problem with a dependency of just `toga`.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/245

**Comment by benoit-pierre** [comment]
This is a pip bug, and has been fixed.
