### ISSUE TITLE
Provides different major versions

### ISSUE THREAD

**Issue by SoniEx2** [pypa/setuptools#2454]
We do this GAnarchy stuff https://ganarchy.autistic.space/

And it's basically a tool for decentralized development. But decentralized development means different forks may add different features. So how do you work out decentralized versioning?

Our idea is that you'd generate an UUID and use that as your major (or rather mega) version. you'd then do the lower versions normally. when breaking compat with a fork, you take out its version from your provides, and when adding compat with another fork, you add its version.

This is the only reasonable approach for decentralized development. Would it be possible for setuptools to support it?

**Comment by jaraco** [comment]
Setuptools attempts to follow a standards process, including ones like [PEP 440](https://www.python.org/dev/peps/pep-0440/), which really only accommodates a narrow set of use-cases. You could probably convert your UUID into its numeric equivalent, although I'm unsure if a 128-bit number is acceptable for a PEP 440 major version number. `len(str(2**128)) == 39`. PEP 440 doesn't specify a limit, and it does appear as if packaging supports version numbers that large:

```
>>> packaging.version.parse(str(2**128) + '.1.0')
<Version('340282366920938463463374607431768211456.1.0')>
```

So maybe it would just work?

**Comment by SoniEx2** [comment]
we've been told the "correct" way of doing it would be to use provides with different names. but pip/setuptools/pypi don't support that...

(then again, it doesn't support providing multiple major versions either...)

**Comment by jaraco** [comment]
There's not much Setuptools can do here. I suggest you work with distutils-sig or pypa/packaging-problems, present the use-case you're trying to solve, the places where the current suite of tools is inadequate, and (preferably) a proposal for how to move forward.
