### ISSUE TITLE
Update .gitignore with extra rules

### ISSUE THREAD

**Issue by p4m-dev** [pypa/setuptools#2455]
Now  .gitignore is too simple. In my mind It would be cool to add ignore rules for `.idea`, `.vscode` , `.python-version`, `venv`. .gitignore files doesn't need to read always and there is no need to keep it so minimal.

**Comment by jaraco** [comment]
Thanks for the report, but I'd like to decline for the [reasons I stated here](https://github.com/pypa/setuptools/pull/1497#issuecomment-423323011). tl;dr there are countless user-specific changes that could go into any and every repo that exists, which is an unsustainable paradigm.
