### ISSUE TITLE
The old developer guide page should point readers to the new one

### ISSUE THREAD

**Issue by edlanglois** [pypa/setuptools#2456]
[The former developer guide page](https://setuptools.readthedocs.io/en/latest/setuptools.html) has largely been emptied of content but does not tell readers where to go to find [the new developer guide](https://setuptools.readthedocs.io/en/latest/userguide/index.html). [The python documentation](https://docs.python.org/3.9/distutils/setupscript.html) and [python packaging guide](https://packaging.python.org/guides/distributing-packages-using-setuptools/) both currently link to the old page and there are probably many other references to the old page out there on the internet so it would be helpful to point readers to the new one.

**Comment by jaraco** [comment]
Thanks for the feedback. Would you consider contributing the patch?

**Comment by theauk** [comment]
I'll have a look at this. The newest python documentation links to the updated version, but I can see that the python packaging guide still links to the old – I will try to change that too.
