### ISSUE TITLE
[RFC] Use pytest-xdist in setuptools' test suite

### ISSUE THREAD

**Issue by webknjaz** [pypa/setuptools#2458]
As I see it, there's two benefits of doing so:
1) Getting the test results faster. For example, on my laptop, a single pytest run takes 175s (2min 54s) but adding pytest-xdist makes it 52.04s. That's about x3.5 speedup. When talking about getting the CI reports, the speedup of a single run may be less significant (fewer CPU cores used) but if you multiply that per job number across all CIs, this may be [quite useful](https://twitter.com/annyamilo/status/1328433707921838081).
2) Identifying bugs in tests: when I added pytest-xdist locally, I've got one error and one failure. This may mean that some of the tests may be leaking state and aren't isolated which becomes visible in envs with race conditions. So adding xdist will also help us isolates tests better.

**Comment by webknjaz** [comment]
Demo PR: https://github.com/pypa/setuptools/pull/2459.

**Comment by jaraco** [comment]
In my experience on other projects, adding this plugin does add some complexity and additional failure modes and thus debt to a project. That said, I'm generally in favor of the concept. Perhaps it would be worthwhile to first use something like [pytest-randomly](https://pypi.org/project/pytest-randomly) to eliminate the test dependencies.

**Comment by webknjaz** [comment]
FWIW that PR fixes the problems with tests and makes the suite complete much faster. I'd say we need to explore the randomly plugin separately.
