### ISSUE TITLE
[TODO] Enable PR builds in RTD

### ISSUE THREAD

**Issue by webknjaz** [pypa/setuptools#2469]
@jaraco we've discussed this in comments to other PRs/issues and you seemed to be on board with the idea. Except that the only annoying part is that it cannot be done via a config file but only using the UI.
I thought I'd create a dedicated issue for this task so it wouldn't get lost again.

**Comment by webknjaz** [comment]
@jaraco we've faced an actual problem caused by not having this enabled. It happened 3 weeks ago (https://github.com/pypa/setuptools/pull/2584) but only got noticed 5 days ago (https://github.com/pypa/setuptools/issues/2614).
I think this checkbox should be enabled ASAP.

**Comment by jaraco** [comment]
The checkbox is already checked.

![image](https://user-images.githubusercontent.com/308610/112734772-35d6ea00-8f1e-11eb-9e6a-eae4e09e1967.png)

I did not change it. So there must be more work to be done.

**Comment by jaraco** [comment]
I've unchecked the box, hit save, checked the box, and hit save again. Maybe that will help.

**Comment by webknjaz** [comment]
Sometimes the GH webhooks break. There's a tab to resync them. Or check in the repo settings whether the corresponding hook actually sends PR events to RTD.

**Comment by webknjaz** [comment]
Check https://readthedocs.org/dashboard/setuptools/integrations/ (there's a resync button under the specific hook).

And also check https://github.com/pypa/setuptools/settings/hooks -> `Ctrl+F` for "readthedocs" and see if the `Pull Requests` checkbox is on.

**Comment by jaraco** [comment]
In the hooks settings, I changed "Just the 'push' event" to "send me everything" (even though I want them to send RTD everything). Let's see how that works.

**Comment by webknjaz** [comment]
I retriggered https://github.com/pypa/setuptools/pull/2601 and verified that the RTD status appeared in the list (the failed status is expected because that PR is old and does not have the workaround from `main`. Closing.
