### ISSUE TITLE
target directories in data_files are incorrectly changed to lowercase

### ISSUE THREAD

**Issue by rhertzog** [pypa/setuptools#2480]
Hello, I have this in setup.cfg:
```
[options.data_files]
share/perl5/Debian/Debhelper/Sequence = dh-kaboxer/Sequence/kaboxer.pm
```

But that file ends up installed in `/usr/share/perl5/debian/debhelper/sequence/`. Notice how the target directory is entirely lowercase while the configuration file had uppercase on some characters.

And here the case is meaningful.

This is with python 3.9 and setuptools 50.3.0-1 on a Debian Unstable system.

**Comment by melissa-kun-li** [comment]
Hopefully PR #2580 addresses this :)
