### ISSUE TITLE
[Maintenance] Remove AppVeyor GitHub App and webhook integration

### ISSUE THREAD

**Issue by webknjaz** [pypa/setuptools#2499]
@jaraco you dropped the AppVeyor config but their service still gets notified by GitHub and reports back via Status API that shows up in PRs as a failing check.
Example: https://ci.appveyor.com/project/pypa/setuptools/builds/36938917

There's a few things that can be done:
1) Remove the project on AppVeyor itself (I would keep it for history).
2) Go to https://github.com/pypa/setuptools/settings/hooks, <kbd>Ctrl+F</kbd> <kbd>AppVeyor</kbd>, click `Edit`, scroll down, untick the `✅ Active` checkbox and click `Update webhook`.
3) Go to https://github.com/pypa/setuptools/settings/installations and see if there's a GitHub App added. Don't blindly remove it at this point, since it's bound to the entire org and may affect other repos. But you can edit what repos it can access and remove this one if there's a list. It's a bit more complicated if there's `🔘 All repositories` selected: in this case you'd need to track down all the repos using AppVeyor and keep them in the list.

**Comment by jaraco** [comment]
Thanks for reporting this. Before I got around to reading your report, I've already enacted option 1, so I think we're good (even though we've lost the history).
