### ISSUE TITLE
Grand Children processes not killed

### ISSUE THREAD

**Issue by monteksingh** [pypa/setuptools#2512]
My app has a parent process which creates 3 child processes. Each child process inturn creates 4 subprocesses.

When parent process is terminated due to timeout, the child processes and the grandchild processes are not killed, they become orphans.
I am using stopasgroup=true and killasgroup=true in the configuration as well.
supervisor version is 3.2.0 and was installed using sudo apt install supervisor.

Pls help....

**Comment by mhsmith** [comment]
This is the issue tracker for setuptools, not supervisor. Since you've already created [an issue](https://github.com/Supervisor/supervisor/issues/1396) in the correct tracker, I suggest you close this one.
