### ISSUE TITLE
setuptools changes underscore to dash for package name

### ISSUE THREAD

**Issue by LorenLiu** [pypa/setuptools#2522]
After I pip install cx_oracle, I use python -m pip show cx_oracle command and it shows the package name is cx-Oracle
After discussed with cx_Oracle's author, it shows setuptools changed the underscore to dash for the package name.  Is that an issue for setuptools or is there any way to stop this auto-conversion? Thanks.

setup.cfg for cx_Oracle
[metadata]
name = cx_Oracle

PKG-INFO for cx_Oracle
Metadata-Version: 2.1
Name: cx-Oracle

setup.py used in cx_Oracel
# setup the extension
extension = setuptools.Extension(
        name = "cx_Oracle",
        include_dirs = includeDirs,
        extra_compile_args = extraCompileArgs,
        define_macros = [("CXO_BUILD_VERSION", BUILD_VERSION)],
        extra_link_args = extraLinkArgs,
        sources = sources + dpiSources,
        depends = depends,
        libraries = libraries,
        library_dirs = libraryDirs)

**Comment by jaraco** [comment]
It looks like when [Setuptools resolves the name for the metadata](https://github.com/pypa/setuptools/blob/6b44f948ca40ee490c59d216a0e859d17431742a/setuptools/command/egg_info.py#L124), it uses [pkg_resources.safe_name](https://github.com/pypa/setuptools/blob/6b44f948ca40ee490c59d216a0e859d17431742a/pkg_resources/__init__.py#L1304-L1309), referencing the "[unspecified] standard distribution name" that replaces underscores with dashes.

But looking at recent PEPs like PEP 508, it does look like [Names](https://www.python.org/dev/peps/pep-0508/#names) are allowed to contain underscores.

Probably egg_info needs to be updated to allow for underscores (and anything else allowed be the new standard). Who knows what havoc that will wreak.

**Comment by jaraco** [comment]
I can confirm that with #4159, the issue is addressed:

```
 setuptools bugfix/2522-retain-valid-name @ .tox/py/bin/pip install --no-cache --no-build-isolation cx-oracle
Collecting cx-oracle
  Downloading cx_Oracle-8.3.0.tar.gz (363 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.9/363.9 kB 8.8 MB/s eta 0:00:00
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cx-oracle
  Building wheel for cx-oracle (pyproject.toml) ... done
  Created wheel for cx-oracle: filename=cx_Oracle-8.3.0-cp312-cp312-macosx_14_0_arm64.whl size=178447 sha256=36d93f88ded91ec3726325bc9bb1c2de6493af624c9acecefbe22fadd5de3554
  Stored in directory: /private/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-ephem-wheel-cache-5slq_i5v/wheels/c2/36/74/ca03900db8246dfd872cb23f51299a034ff843b7c15e87b5dd
Successfully built cx-oracle
Installing collected packages: cx-oracle
Successfully installed cx-oracle-8.3.0
 setuptools bugfix/2522-retain-valid-name @ head -n 3 .tox/py/lib/python3.12/site-packages/cx_Oracle-8.3.0.dist-info/METADATA
Metadata-Version: 2.1
Name: cx_Oracle
Version: 8.3.0
```

**Comment by jaraco** [comment]
Releasing as v69.0.3.

**Comment by johannkm** [comment]
Just a heads up: we were accidentally relying on underscores becoming hyphens, I suspect other projects will hit this as well 🙂

**Comment by henryiii** [comment]
Build was checking metadata in its test suite, but happy to adapt to this.

By the way, I think this affects SDist naming (SDist names should be normalized, but setuptools doesn't seem to do that). We got a report of an SDist being made with spaces in the name, which is invalid. I'm suspecting this change might be related.

```ini
# setup.cfg
[metadata]
name = This is not cool
version = 0.0.1
```

```console
$ touch pyproject.toml
$ pipx run build .
...
Successfully built This is not cool-0.0.1.tar.gz and This_is_not_cool-0.0.1-py3-none-any.whl
```

I believe before this change, you'd have made `this-is-not-cool-0.0.1.tar.gz` (which should have been `this_is_not_cool-0.0.1.tar.gz`, normalized like wheels, IMO, and as far as I've been told, all other backends normalize that way).
