### ISSUE TITLE
Read Version Number from the Package in setup.cfg

### ISSUE THREAD

**Issue by ChihweiLHBird** [pypa/setuptools#2530]
Hi,

I am trying to make a project to be `setup.cfg` project. In the old version, we letted the `setup.py` read a version number from a file inside the package.
```
def get_version() -> dict:
    version = {}
    with open(Path(__file__).parent / 'sciunit' / 'version.py') as f:
        exec(f.read(), version)
    return version['__version__']

setup(
    ...
    version=get_version(),
    ...
    )
```

I am wondering how can I achieve the same thing in setup.cfg file? Is it possible?

**Comment by jaraco** [comment]
I'm pretty sure the docs answer your question. It's something like:

```
[metadata]
version = attr: sciunit.version.__version__
```

Please experiment, read the docs, and let us know if you find a suitable syntax.

**Comment by ChihweiLHBird** [comment]
> I'm pretty sure the docs answer your question. It's something like:
> 
> ```
> [metadata]
> version = attr: sciunit.version.__version__
> ```
> 
> Please experiment, read the docs, and let us know if you find a suitable syntax.

I am sorry about that. I did read the docs, but I didn't find it. Thank you for your answer and I will check the docs more carefully next time.

**Comment by jaraco** [comment]
To be sure, if it's hard to find or not there in the docs, that would be a bug, so feel free to provide more information or a PR to clarify the docs that would make it easier.

**Comment by homeworkprod** [comment]
Hi, I had the same question as well.

In the docs, there is the section ["Specifying Your Project’s Version"](https://setuptools.readthedocs.io/en/latest/userguide/distribution.html#specifying-your-project-s-version). But it didn't led me to the only spot I could find that includes the answer, which is ["Configuring setup() using setup.cfg files"](https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html?highlight=metadata#configuring-setup-using-setup-cfg-files) (specifically, the config example's `[metadata]` section). I guess it makes sense to link to there from the first section I mentioned?

As for the example itself, which is:
```ini
[metadata]
# …
version = attr: src.VERSION
```
Is this really a practical example? As I understand it, `src` here should be the name of an actual Python package. However, the whole example seems to be based on a `src/` project layout. But `src/` shouldn't include a `__init__.py` file to make it a package, right?

So I assume a better example would be:
```ini
version = attr: yourpackage.VERSION
```

**Comment by jaraco** [comment]
Good suggestions. I’ll convert them to a bug.

**Comment by jimratliff** [comment]
I've answered this question at https://stackoverflow.com/questions/72357031/set-version-of-module-from-a-file-when-configuring-setuptools-using-setup 

Method 1:
* Create a `__version__.py` file at the same level as `__init__` of your import package.
* Add to that file: `__version__ = '0.0.2'`
* In  `__init__.py`, add `from . __version__ import __version__`.
* In `setup.cfg`, use `version = attr: my_package.__version__`
Method 2:
* Create a `VERSION` file at the same level as `__init__` of your import package.
* Add to that file *only*: 0.0.2
*  * Importantly: Don't enclose in quotation marks. NO OTHER TEXT. No comments
* In `setup.cfg` use: `version = file: src/my_package/VERSION`
* * Note that the root for the relative path is the *project* directory.
