### ISSUE TITLE
Change in names in wheel

### ISSUE THREAD

**Issue by henryiii** [pypa/setuptools#2535]
I just noticed in the release about an hour ago that the following names have changed when you build a wheel:

```
E         Extra items in the left set:
E         'dist-info/top_level.txt'
E         'dist-info/WHEEL'
E         'dist-info/RECORD'
E         'dist-info/LICENSE'
E         'dist-info/METADATA'
E         Extra items in the right set:
E         'info/top_level.txt'
E         'info/RECORD'
E         'info/WHEEL'
E         'info/LICENSE'
E         'info/METADATA'
E         Use -v to get the full diff
```

Was this change intentional, and does it affect where this can be used? If it's fine, I'll adjust my output check. Just checking, thanks!

**Comment by henryiii** [comment]
Actually, the issue might be that this is no longer picking up the correct name of the package. This is for a split package build and only one of the two packages is broken. Investigating.

**Comment by jaraco** [comment]
I suspect what you've encountered is a symptom of #2536. Have a peek at 50.3.1 and let me know if that helps.

**Comment by henryiii** [comment]
Before example: `pybind11_global-2.6.2.dev1.dist-info/RECORD`
After example: `pybind11_global-2.6.2.dist-info/RECORD`

And updating to 52.3.1 fixes it! Thanks for a _quick_ fix!
