### ISSUE TITLE
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'--find-l'": Expected W:(abcd...)

### ISSUE THREAD

**Issue by dreamflasher** [pypa/setuptools#2549]
requirements.txt:

```
--find-links=https://download.pytorch.org/whl/torch_stable.html
torch==1.7.0+cu110
```

```
requirements = pkg_resources.parse_requirements(_REQUIREMENTS_PATH.open())
```

results in 

```
line 100, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'--find-l'": Expected W:(abcd...)
```

This is supposed to be a valid requirements.txt which does work with pip.

**Comment by benoit-pierre** [comment]
pip has its own requirements format, different from the standard: [PEP 508](https://www.python.org/dev/peps/pep-0508/); which specifies that:
> The language defined is a compact line based format which is already in widespread use in pip requirements files, **though we do not specify the command line option handling that those files permit**.

So the behavior you're seeing is correct.

**Comment by benoit-pierre** [comment]
Also note that dependency links are deprecated.

**Comment by julien-lecomte** [comment]
Bonjour @benoit-pierre ,

Would it be worth proposing to make this a warning and not an error?

I'm having the same issue but with the `--extra-index-url` option. After all, with `dependencies = {file = ["requirements.txt"]}`, if the file does not exist, it will only issue a UserWarning; but with the file existing and an incorrect line it fails.

It could be just tolerance: accept a `--extra-index-url` type line, and maybe some others, but a fully incorrect line would still be an error.
