### ISSUE TITLE
Expand and Pin Requirements

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#255]
Originally reported by: **herriojr (Bitbucket: [herriojr](http://bitbucket.org/herriojr), GitHub: [herriojr](http://github.com/herriojr))**

---

Setuptools itself already supports both deployment in "development" mode well as a "distribution" mode, but I've come to the conclusion that this needs to be broken down a bit further in terms of distribution.  Right now, "bdist_wheel", or "bdist_egg" are very naive in what they are told to do for dependencies.  They just list whatever you put in your setup.py without worrying about whether those packages exist or not and only validate the syntax.  For libraries, this is all good, but when it comes to "applications", things get a bit more hairy.  The problem at the application level is that in production you want to make sure every box is running the exact same version of all dependencies.

Most pyramid and any other web project always has a setup.py at the root directory of the project, however, deployment becomes a problem if you aren't pinning your versions during development.  Generally, I prefer not to pin in development as I want to make sure I keep up to date with any library changes as much as possible, however, once it goes out to QA/Production, I want it to be pinned.  This workflow allows me to keep up to date on breaking changes and minimize risk in production.  To follow this workflow, right now, what has to happen is a requirements.txt file has to be generated and have all packages pinned and then pass around that requirements.txt file to install from.  Why do this, when wheels and eggs are really meant to manage dependencies anyways?  Why not have them deal with it?

Basically, what I'm proposing is adding two new options for when generating the egg_info (since bdist_wheel just calls bdist_egg and converts it to wheel format):

--expand-requirements
  This expands all dependencies and transient dependencies to create one giant list

--pin-requirements
  This pins the requirements to specific versions, similar to a pip freeze

The only edge case I can think of is when pinning when you are working on other modules which are installed as "development".  In this case, I would argue that the build should fail if --pin-requirements is set as it is unable to pin it.  As part of this, it should also fail if two dependencies require two different versions of the same dependency which are incompatible (version ranges don't overlap).

I'm currently trying to work on this, but I wanted to get a discussion going around this as, to me, it seems like this would be a common problem.  If it isn't something that most people want, I'll opt to build this is a separate package which can be used to override the default commands for those that want it, however, my preference would be that this be part of the main setuptools ecosystem.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/255

**Comment by tuukkamustonen** [comment]
@herriojr Now that we have https://github.com/jazzband/pip-tools and https://github.com/kennethreitz/pipenv, do you think this issue can be solved by those tools, rather?

**Comment by herriojr** [comment]
@tuukkamustonen I'm so far removed from python development at this point that you can feel free to close this if you like.

**Comment by jaraco** [comment]
Indeed, I believe pip and other tools are the best place to materialize a requirements list at a point in time.
