### ISSUE TITLE
Why is 'setuptools' imported in setup.py?

### ISSUE THREAD

**Issue by hwkin** [pypa/setuptools#2551]
It is so interesting that setuptools installation scripts needs setuptools. I have a python without setuptools and I need it.

**Comment by webknjaz** [comment]
It's not an installation script, it's more like a build script for packages and `setuptools` can be omitted if you use some other PEP517 build backends.

**Comment by webknjaz** [comment]
> I have a python without setuptools and I need it.

It's unclear what you're asking about but I suppose you could adjust your `PYTHONPATH` during development if you're trying to import something. Also, you may want to consider using `pyproject.toml` which pip will then pick up. Just add
```toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
```
as per https://setuptools.readthedocs.io/en/latest/userguide/#transition-to-pep517 and https://setuptools.readthedocs.io/en/latest/build_meta.html.
Then, this will install setuptools in an isolated build env, build your package and discard that temporary env, it will then install the built package into your virtualenv:
```console
$ pip install .
```
