### ISSUE TITLE
Incorrect syntax for single-line entries in `setup.cfg` -> [options.extras_require] generates invalid `METADATA`

### ISSUE THREAD

**Issue by pwoolvett** [pypa/setuptools#2553]
I'm not clear just by reading [the docs](https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html) what is the correct way of specifying a single, "complex" dependency (eg with markers, example below).

I'm refering to [these lines here](https://github.com/kivy/kivy/blob/dedcb6bcabe3d8d6758dcee607e8c33b174d782b/setup.cfg#L72-L75): the `METADATA` file being generated  contains incorrect information.

NOTE: As a workaround, and by looking at the `setuptools` code [see here for explanation](https://github.com/kivy/kivy/pull/7362#issuecomment-772089309), changing it into multi-line solves the problem with the metadata. In the example, the following line is being split using `;`, which generates  invalid `METADATA`:

```ini
[options.extras_require]
gstreamer = kivy_deps.gstreamer~=0.3.1; sys_platform == "win32"
```

On the other hand, this is correctly parsed as the `\n` [overrides](https://github.com/pypa/setuptools/blob/c121d289da5d19cf6df2bf6b64ac28916a060161/setuptools/config.py#L251) the `;`, effectively gathering the whole line as a single entry.
```ini
[options.extras_require]
gstreamer =
    kivy_deps.gstreamer~=0.3.1; sys_platform == "win32"
```

The docuemntation contains [an example](https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html) including this:

```ini
[options.extras_require]
pdf = ReportLab>=1.2; RXP
rest = docutils>=0.3; pack ==1.1, ==1.3
```

* Would in this case a `,` be the right thing to use between the sependency and the marker instead of `;`?

BTW, I'm coming from here:
* https://github.com/kivy/kivy/pull/7362#issuecomment-772682833
* https://github.com/python-poetry/poetry/issues/3629

**Comment by webknjaz** [comment]
It's probably one of the quirks of the stdlib's configparser module. Not sure if setuptools can do anything about it.

**Comment by pwoolvett** [comment]
In the documentation it says `install_requires` is parsed as type`list-semi`, which causes the same "outcome": you cannot include a marker in a oneliner because this would cause it to incorrctly split (hence the `semi` in `list-semi`). The implementation here and the docs are on the same page (both literally and figuratively, as there's an example including a marker).

I guess the confusion arises from the fact that `extras_require` is parsed as type `section`, but its not stated what the sub-section values are parsed as (which also is `list-semi`).

Given the way `configparser` works, the current `setuptools` code must post-process the keys inside configuration (welcome, `pyproject.toml`). I have no problems with the implementation, but after going through this I think it would help having  an example / documentation for the case where an `extras_require` has markers.

**Comment by pwoolvett** [comment]
closed by https://github.com/pypa/setuptools/commit/aad7fde133bf1cf67a0c50645d27f6a2004da612
