### ISSUE TITLE
header files not included in tar.gz file

### ISSUE THREAD

**Issue by chmike** [pypa/setuptools#2565]
`python3 -m build` is using `sdist` to create the file containing the sources. 
Unfortunately, `.h` files are not included by default by sdist, though `.c` files are.
The `depends` member of `Extension` is ignored by sdist. 

This is really annoying since we are then required to create a MANIFEST.in file. 

Could `setuptools` do something to avoid this limitation of `sdist` ?

**Comment by abravalheri** [comment]
Hi @chmike, thank you very much for bringing this topic up!

Your problem description makes a lot of sense to me.
Would you be interested in providing a PR to add support for such a feature?

Just as a reference, these pieces of code might be relevant:

- [_distutils.command.sdist](https://github.com/pypa/setuptools/blob/1a1397a4ef0327ba09ddd4a3d0916af48d3be7ec/setuptools/_distutils/command/sdist.py#L210)
- [setuptools.command.sdist](https://github.com/pypa/setuptools/blob/1a1397a4ef0327ba09ddd4a3d0916af48d3be7ec/setuptools/command/sdist.py#L103)
- [setuptools.command.egg_info/manifest_maker](https://github.com/pypa/setuptools/blob/1a1397a4ef0327ba09ddd4a3d0916af48d3be7ec/setuptools/command/egg_info.py#L577)
