### ISSUE TITLE
Project specific .pypirc settings

### ISSUE THREAD

**Issue by stevecrox** [pypa/setuptools#2567]
For a traditional CI Build you have a main build instance which connects to build agents, connection protocol varies but a build doesn't spawn a unique user connection it is a straight connect this machine to the main CI instance.

When building projects and teams often want to restrict access to their SCM/Internally hosted PyPi instance, this means each project will want it's own user credentials/pypi index information. (a good reason for this is teams working on IP owned by different customers).

Currently .pypirc has to reside in the user home directory, so this means a build agent becomes tied to a specific project, this either locals a Server/VM/EC2/etc.. or means you have to craft a docker image for each project (obviously this is not great).

Other build systems such as Apache Ivy, Apache Maven, RubyGems & NPM allow us to either redirect their equivalent of .pypirc (e.g. Ivy/Maven)or allow for a file in the project directory which overrides the values in the central file (e.g. NPM).

This allows us to us a single build agent for multiple projects and just worry about injecting a pypirc specific to the project.

**Comment by stevecrox** [comment]
I should point out the reason to run a python project is so you can subject the code to anlaysis (flake8, pep8, etc..) capture test coverage, etc.. And have a standard release mechanism to allow you to control your Python project like another enterprise project.

**Comment by abravalheri** [comment]
Hi @stevecrox I will close this issue for now, but please let us know if you have any additional information on the matter that I am not considering.
