### ISSUE TITLE
Overwrite to-be-installed source file (without overwriting the orignal file in the source directory)

### ISSUE THREAD

**Issue by tdegeus** [pypa/setuptools#2572]
I want to encode the git hash of the lastest commit at the time of installing as the output of a function in my library.

I am using a structure
```
.git/
setup.py
|- mylib/
|  - __init__.py
|  - git.py
```

whereby `git.py` contains a dummy, unconfigured, function
```python
def git():
    return None
```

At the time of installing I want to overwrite `git.py` such that it returns the hash of the latest git commit, e.g.:
```python
def git():
    return "2d04d1a10f81d24183df7622c95398d60106dfff"
```
(whereby the hash is the output of `git rev-parse HEAD` at the time of installing).

So my question: 
*How can I overwrite the to-be-installed `git.py`, using setuptools, without overwriting the file in the source directory*?

---------

Current work-around `setup.py`

```python 
import subprocess

git_hash = subprocess.check_output(["git", "rev-parse", "HEAD"]).strip().decode('UTF-8')

cmd = '''def git():
    return "{0:s}"
'''.format(git_hash)

os.rename('mylib/git.py', 'mylib/git.py.bak')

with open('mylib/git.py', 'w') as f:
    f.write(cmd)

setup(
    name = 'mylib',
    version = __version__,
    # ...
    packages = find_packages(),
)

os.rename('mylib/git.py.bak', 'mylib/git.py')
```

Which has the down-sight of temporarily changing `git.py` in the source directory. I'd rather leave that file completely untouched.

See also: https://stackoverflow.com/questions/66265283/overwrite-to-be-installed-source-file-without-overwriting-the-orignal-file-in-t

**Comment by webknjaz** [comment]
@tdegeus you could use setuptools-scm. It is able to generate a version file on build. You could have a try-except import of that file with a fallback in some static module. I don't think the requested feature is necessary because it's already possible with the existing tools.

**Comment by tdegeus** [comment]
That's amazing! I came across [setuptools-scm](https://pypi.org/project/setuptools-scm/) but never really understood it... So this, extremely simple, solution works perfectly for me:

## File structure

```
setup.py
|- mylib/
|  - __init__.py
|  - version.py
```

## setup.py

```python
setup(
    name = 'mylib',
    packages = find_packages(),
    use_scm_version = {'write_to': 'mylib/version.py'},
    setup_requires = ['setuptools_scm'],
)
```

## __init__.py

```python
from .version import *
```

## version.py (dummy, overwritting at installation)

```python
version = "None"
version_tuple = (0, 0, 0, "None", "None")
```

----

A question that arrises is: what is the most robust way to get the version of the Python module? It seems that `__version__` is becoming outdated. Should one simply always use:

```python
from importlib.metadata import version
print(version('mylib'))
```
?

**Comment by tdegeus** [comment]
A second question: since this works so well... Can I using setuptools-scm also to get a version string for a non-Python package (specifically in CMake?)

**Comment by webknjaz** [comment]
Yes, you can use it externally. There's `setuptools_scm.parse()` or something like that you can call. Also, getting a version in your package is up to you and depends on what you need. Determining it dynamically gets it from the local Git repo while using `importlib_metadata` relies on what's in site-packages.

**Comment by tdegeus** [comment]
Thanks!

A surprise popped up: I distribute my code with conda-forge. However when building I don't have access to the git-repo, but I do have access explicitly to the version string. How can I use `setuptools_scm` to still write a version file, but now with my custom version string?

**Comment by webknjaz** [comment]
I think for conda you may have to commit the version but I'm not really familiar with how conda works.

**Comment by tdegeus** [comment]
Thanks for you reply. So I found a 'solution' (I'd call it more of work-around) : https://github.com/conda-forge/shelephant-feedstock/pull/18

What works is to download the code from PyPi. In PyPi package the version has already been defined upon upload and so `setuptools_scm` knows what to do. On the other hand, it a GitHub archive is taken as a source all hope is lost (obviously). So what I think would be a necessary feature to be put into `setuptools_scm` is the option to hand-specify the version in such a case. See : https://github.com/pypa/setuptools_scm/issues/522

**Comment by webknjaz** [comment]
@tdegeus I see you download git tarballs. In this case, make sure to integrate https://pypi.org/project/setuptools-scm-git-archive/

**Comment by tdegeus** [comment]
Thank a lot @webknjaz !! Does adding this dependency adds constraints when called from the actual git repository, or is the default versioning then based on the git repository ?

**Comment by webknjaz** [comment]
It is based on Git tags. This plugin makes sure that the version is sourced from a file that you're supposed to commit. It is a template git fills out when generating a git archive. This only works for tagged commits only, though. When running from a normal clone, it still uses the current repo.

**Comment by tdegeus** [comment]
Very clear, thanks once more!
