### ISSUE TITLE
It is needed to make sure the EntryPoint py file generated is written in utf-8 when installing

### ISSUE THREAD

**Issue by HaujetZhao** [pypa/setuptools#2577]
setuptools version: 53.0.0
pyhton version: Python 3.8.6
system: Windows10 64 19041.804 (Chinese Language)

Problem: If a EntryPoint in setup.py has Unicode characters, after installing the package with `python setup.py install`, the Unicode entry point would fail. 

The test package is below: 

[UnicodeTestPackage.zip](https://github.com/pypa/setuptools/files/6017355/UnicodeTestPackage.zip)

In the setup.py file, there are two entrypoints: 

```python
entry_points={  # Options: console_scripts gui_scripts
            'console_scripts': [
                'UnicodeTestPackage=UnicodeTestPackage.__main__:main', 
                'Unicode字符测试包=UnicodeTestPackage.__main__:main', 
            ]
    },
```

After running `python setup.py install`, a file  `~\AppData\Local\Programs\Python\Python38\ScriptsUnicode字符测试包-script.py` would be generated, but it's written in `gbk` encoding, not `utf-8` encoding. 

So, when using the `Unicode字符测试包` entry point to run the moduel, certainly an error popups: 

```
D:\Users\Haujet>Unicode字符测试包
  File "D:\Users\Haujet\AppData\Local\Programs\Python\Python38\Scripts\Unicode字符测试包-script.py", line 2
SyntaxError: Non-UTF-8 code starting with '\xd7' in file D:\Users\Haujet\AppData\Local\Programs\Python\Python38\Scripts\Unicode字符测试包-script.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

After manually convert the `Unicode字符测试包-script.py` into utf-8 codec, the error solved. 

So, I assume that this need to be issued: It is needed to make sure the EntryPoint py file generated is written in utf-8 when installing.

**Comment by jaraco** [comment]
`setup.py install` is discouraged. Does the script work if installed with pip?

**Comment by HaujetZhao** [comment]
Yes, `pip install .` would work with the script. But it is slower than 'setup.py install', so I prefer 'setup.py install'.

**Comment by jaraco** [comment]
> Yes, `pip install .` would work with the script. But it is slower than 'setup.py install', so I prefer 'setup.py install'.

I'm sorry that it's slower, but it's slower for good reasons (more sophisticated tooling, build dependency support, etc). You may wish to file an issue with pip and explore ways to make it faster (especially if the slowness is a serious impediment to your workflow), but since Setuptools is discouraging use of `easy_install` (and thus `setup.py install`), we won't be investing energy in solving these issues.

Thanks for reporting the issue.
