### ISSUE TITLE
gui_scripts entry point not working on Windows

### ISSUE THREAD

**Issue by cbrnr** [pypa/setuptools#2578]
I'm not entirely sure this is a `setuptools` issue, but it is currently my best bet. I suspect that the `gui_scripts` entry point is not working properly because (1) a console still needs to be running on macOS and Linux, and (2) I get an error message on Windows. When I replace `gui_scripts` with `console_scripts`, the behavior on macOS and Linux doesn't change, and starting an application on Windows does not result in an error.

I've asked this question on SO, but haven't received neither an answer nor a comment (so this is obviously a rather niche problem): https://stackoverflow.com/questions/66137439/python-gui-entry-point-not-working-on-windows

The full description of the problem is in that SO post, but I'll reiterate the steps to reproduce:

1. On Windows, open the Anaconda prompt and install all dependencies in a new environment:
    ```
    conda create -n mnelab python=3.9 numpy scipy matplotlib pyqt qtpy
    conda activate mnelab
    pip install --no-deps mne mnelab
    ```
2. Type `mnelab` and a dialog with the error message ("Fatal Error in Launcher" saying "stderr duplication failed") will appear. Typing `python -m mnelab` works though.

**Comment by abravalheri** [comment]
Hi @cbrnr, thank you very much for reporting this.

I believe `pip` (re-)generates wrappers on its own for both `console_scripts` and `gui_scripts` (see https://github.com/pypa/pip/issues/1067, https://github.com/pypa/pip/pull/1251), using [distlib](https://bitbucket.org/pypa/distlib).

So maybe it would be more appropriate reporting these issues there?
For the time being, I will close the ticket, but please feel free to re-open it if you have more information that associates setuptools to the error.

**Comment by cbrnr** [comment]
Thank you @abravalheri – this issue is currently being discussed in https://github.com/pypa/pip/issues/10444.
