### ISSUE TITLE
"Name" metadata keyword not recognized

### ISSUE THREAD

**Issue by gecrooks** [pypa/setuptools#2592]
Starting with v53.1.0 setuptools seems to no longer recognizes the "Name" key in the [metadata] section of setup.cfg. A "name" key is recognized. 

The metadata spec uses "Name". https://packaging.python.org/specifications/core-metadata/.

Possible related to issue #1937 that was merged in at that release.

**Comment by melissa-kun-li** [comment]
@jaraco If we'd like `metadata` keys to be case-insensitive, I've written a fix to make `metadata` keys all convert to lowercase as it was originally. I'll go ahead and submit PR

**Comment by jaraco** [comment]
> The metadata spec uses "Name". https://packaging.python.org/specifications/core-metadata/.

The metadata spec isn't relevant here. That spec also uses `Description` where Setuptools expects `long_description`.

@melissa-kun-li Thanks for helping here. I advise to restore compatibility, but deprecate the use of keys that are not lowercase (same as how dashes are deprecated).
