### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#260]
Originally reported by: **jaraco (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

I have been maintaining the distribute releases since 2010 and setuptools releases since the merge. I no longer have the time to effectively manage this project. A new primary maintainer is needed. The effort requires a few hours per month from somebody with a passion for quality, sympathy for compatibility, and respect for the community and the previous contributors. Good communications skills are also a plus.

I'm happy to mentor a maintainer or two and continue to contribute to discussions and make incidental code contributions, but I need a volunteer to take the role of primary maintainer.

If you're willing, please respond to the pypa-dev mailing list with your interest.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/260

**Comment by jaraco** [comment]
Thanks to the volunteer efforts of @benoit-pierre and @pganssle , we now have a more regular team of maintainers. We will continue to welcome contributions and maintainers for those interested, so don't hesitate to reach out, familiarize yourself with the project, and offer contributions.
