### ISSUE TITLE
[BUG] setup_requires ignore ~/pip/pip.conf setting but request https://pypi.org/, this is really silly

### ISSUE THREAD

**Issue by V0idk** [pypa/setuptools#2606]
### setuptools version

all

### Python version

all

### OS

all

### Description

when execute pip download --no-deps 。
setup_requires ignore ~/pip/pip.conf setting but request https://pypi.org/, this is really silly

see:https://github.com/pypa/pip/issues/1884

### Expected behavior

1

### How to Reproduce

1

### Output

```console

```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by wimglenn** [comment]
Accidental double-post https://github.com/pypa/setuptools/issues/2606 ?

**Comment by webknjaz** [comment]
`pip.conf` is a completely separate project. It would be unreasonable to rely on its config assuming that's what you wanted to ask. (with the expected result filed as "1" it's my best guess)

As for `setup_requires`, as @uranusjr already explained at https://github.com/pypa/pip/issues/9707#issuecomment-799363742, it's a discouraged and fragile feature that nobody should really be using in 2021. And the expectation is that people use PEP 517's `pyproject.toml` to populate their build environments.
