### ISSUE TITLE
[FR] attr: parsing should allow static modules that are not in root

### ISSUE THREAD

**Issue by Colin-b** [pypa/setuptools#2609]
### What's the problem this feature will solve?

I am trying to set the version in a dedicated file within my project. 
However, even if `__init__.py` is requiring some external dependencies, I would like to be able to extract the version from the dedicated file.

Here is what I am trying to achieve in my `setup.cfg` given the following project structure:

* setup.cfg
* my_module/
  *  __init__.py
  * version.py

```
[metadata]
version = attr:my_module.version.__version__
```

The problem is that if __init__.py requires additional dependencies to be imported, it fails. Even if `my_module.version` content does not relies on anything.

The reason why I am doing this is that:
* I would like to generate the version myself, so creating a new file containing only the version would be easier.
* I would like to be able to rely on this version within my project and avoid any circular dependency (so having it in a separate file).

### Describe the solution you'd like

I would like to able to keep my project structure (and external dependencies within `__init__.py`) and define the version as contained within `my_module.version` module.

### Alternative Solutions

Setting the version within __init__.py solves the issue (thanks to StaticModule I assume) but does not fit my use case as I would like to be able to generate the file containing the version.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @Colin-b, thank you very much for bringing this issue up.

Can you provide a simple git repository with a reproduction so we can investigate this use case?

**Comment by Colin-b** [comment]
Hello, 

I'm `a bit` late but here you go.
Version 54.1.2 (the one at the time of the issue) [had this issue](https://github.com/Colin-b/dedicated_version_file_demo/actions/runs/3226864489/jobs/5280915803)

However I noticed that version [61.0.0](https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v6100) fixed it:
* [build failure with the previous 60.10.0 version](https://github.com/Colin-b/dedicated_version_file_demo/actions/runs/3226880162/jobs/5280949892)
* [build success with the 61.0.0 version](https://github.com/Colin-b/dedicated_version_file_demo/actions/runs/3226886860/jobs/5280965475)
