### ISSUE TITLE
build_py does not handle package_data properly

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#261]
Originally reported by: **sa2ajj (Bitbucket: [sa2ajj](http://bitbucket.org/sa2ajj), GitHub: [sa2ajj](http://github.com/sa2ajj))**

----------------------------------------

In my project I use a pattern that would match directories as well:

```
#!python

package_data={
    '': ['path/*']
}
```

As a result, setuptools fails as it can't copy directories.

After a bit of investigation, I found that the problematic code is in [build_py](https://bitbucket.org/pypa/setuptools/src/b01dd795c870fab89ca1afda74dc8520d6cfeb75/setuptools/command/build_py.py?at=default#cl-98).  While checking the content of distutils (which is part of CPython), the corresponding [code looks different](https://hg.python.org/cpython/file/5313b4c0bb6c/Lib/distutils/command/build_py.py#l130) and it does not fail.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/261

**Comment by jaraco** [comment]
As you can see above, efecaf8 tests fail, capturing the error that presumably would have been observed in the OP's case, and demonstrating the fix in 8f0ac47.
