### ISSUE TITLE
[Docs] RTD changelog is out of date

### ISSUE THREAD

**Issue by jwodder** [pypa/setuptools#2614]
### Summary

[The changelog on the RTD site](https://setuptools.readthedocs.io/en/latest/history.html) is missing entries for the last four releases (v54.1.1, v54.1.2, v54.1.3, v54.2.0).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by webknjaz** [comment]
There's a bunch of failed builds on RTD: https://readthedocs.org/projects/setuptools/builds/. So it's not just the changelog but the whole docs site.

**Comment by webknjaz** [comment]
The first failed log from is from 3 weeks ago:
```python-traceback
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/setuptools/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/setuptools/envs/latest/lib/python3.7/site-packages/sphinx_inline_tabs/__init__.py", line 5, in <module>
    from ._impl import setup  # noqa
  File "/home/docs/checkouts/readthedocs.org/user_builds/setuptools/envs/latest/lib/python3.7/site-packages/sphinx_inline_tabs/_impl.py", line 8, in <module>
    from sphinx.transforms.post_transforms import SphinxPostTransform
ImportError: cannot import name 'SphinxPostTransform' from 'sphinx.transforms.post_transforms' (/home/docs/checkouts/readthedocs.org/user_builds/setuptools/envs/latest/lib/python3.7/site-packages/sphinx/transforms/post_transforms/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/setuptools/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/setuptools/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/setuptools/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/setuptools/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinx_inline_tabs (exception: cannot import name 'SphinxPostTransform' from 'sphinx.transforms.post_transforms' (/home/docs/checkouts/readthedocs.org/user_builds/setuptools/envs/latest/lib/python3.7/site-packages/sphinx/transforms/post_transforms/__init__.py))

Extension error:
Could not import extension sphinx_inline_tabs (exception: cannot import name 'SphinxPostTransform' from 'sphinx.transforms.post_transforms' (/home/docs/checkouts/readthedocs.org/user_builds/setuptools/envs/latest/lib/python3.7/site-packages/sphinx/transforms/post_transforms/__init__.py))
```
_(https://readthedocs.org/projects/setuptools/builds/13171300/)_

**Comment by webknjaz** [comment]
Looks like `sphinx_inline_tabs` tries to import things from the modern Sphinx versions that aren't present in v1.8.5. The solution could be setting the version in the requirements files of this repo.

cc @pradyunsg does the extension set any minimum version of Sphinx?

**Comment by webknjaz** [comment]
The PR that broke RTD is https://github.com/pypa/setuptools/pull/2584.
@jaraco with https://github.com/pypa/setuptools/issues/2469 this could've been prevented (because Netlify is clearly configured differently than RTD) — the status of the broken docs site would've appeared in the PR statuses.

**Comment by webknjaz** [comment]
Upstream bug: https://github.com/pradyunsg/sphinx-inline-tabs/issues/14

**Comment by jaraco** [comment]
> with #2469 this could've been prevented

Agreed. Also, if there were another publishing method that did not depend on RTD (Github-hosted docs), that might also have avoided the issue. I'm unsure how much energy I want to expend on RTD. I'd really like to have a near-zero workflow for docs publishing. Maybe RTD support in pull requests would be nice, but not if enabling that has a high enough barrier that it requires substantial manual intervention on every project.

Sorry if that sounded ranty; I just want to be careful about biting off more maintenance burden.

**Comment by webknjaz** [comment]
Sure. IIRC they've implemented API changes to support toggling this automatically: https://github.com/readthedocs/readthedocs.org/pull/7834.

**Comment by jaraco** [comment]
For now the workaround addresses this issue.

![image](https://user-images.githubusercontent.com/308610/112732476-89423b80-8f10-11eb-876b-ad931ac19507.png)

**Comment by pradyunsg** [comment]
The latest release of sphinx-inline-tabs should fix this issue. :)

**Comment by webknjaz** [comment]
Final fix: https://github.com/pypa/setuptools/pull/2622
