### ISSUE TITLE
[FR] Auto-include license files in source distributions

### ISSUE THREAD

**Issue by cdce8p** [pypa/setuptools#2616]
### What's the problem this feature will solve?

License files are only included in the source distribution if they are specified in either `license_file`, `license_files` or `MANIFEST.in`. `wheel` automatically adds a few common glob patterns if the `license_files` option isn't specified. https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file

The result is a situation where a license file is included in the wheel, but not in the source distribution.

### Describe the solution you'd like

Match the behavior of `wheel` and include the most common glob patterns automatically if neither `license_file` nor `license_files` is specified.

### Alternative Solutions

 --

### Additional context

PR that originally added support for `license_files`: https://github.com/pypa/setuptools/pull/1767
Commit that added glob patterns in `wheel`: https://github.com/pypa/wheel/commit/59976ab294e1b118f42cab404d95df66ed55f7e4

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Thanks for the description. It sounds reasonable.

I'm a little reluctant to add to the list of implicitly included files. In my experience, there's an endless long tail of files that a user might expect to be included implicitly, and wherever we draw the line, that's where users will get confused. I've been leaning toward not including any files implicitly (only those that are explicitly implicated, such as those indicated by 'license files').

On the other hand, I'd like users to be able to distribute projects with minimal boilerplate, so having some reasonable defaults seems acceptable. I'd accept a PR for this feature as long as it isn't complicated.
