### ISSUE TITLE
[BUG] version comparison

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#2618]
### setuptools version

setuptools==54.2.0

### Python version

Python 3.6.8

### OS

Windows

### Description

I'm confused about version comparison.
[Document](https://setuptools.readthedocs.io/en/latest/userguide/distribution.html#specifying-your-project-s-version) says

>  So, revisions like 2.4-1 and 2.4pl3 are newer than 2.4, but are older than 2.4.1 (which has a higher release number).

but

```console
>>> from pkg_resources import parse_version
>>> parse_version("2.4pl3") > parse_version("2.4")
False
```

### Expected behavior

I expected "2.4pl3" is newer than "2.4".

### How to Reproduce

Please see description above.

### Output

Please see description above.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Thanks for the report. Version number parsing has evolved over the years and now follows more closely [PEP 440](https://www.python.org/dev/peps/pep-0440/). Probably the docs should point to that instead.

To complicate matters, Setuptools still supports nonstandard versions, and that's what `2.4pl3` is parsed as:

```
>>> from pkg_resources import parse_version as pv
>>> pv('2.4pl3')
<LegacyVersion('2.4pl3')>
```

`LegacyVersions` always resolve as lower than non-legacy versions:

```
>>> pv('99999999pl1') > pv('1.0')
False
```

**Comment by isakamoto** [comment]
I understand. Thank you.

**Comment by DiddiLeija** [comment]
Hello @jaraco. How is this issue going? If no one has fixed it, I can do it.

**Comment by jaraco** [comment]
Thanks for offering to help. Please proceed with a patch for the docs.

**Comment by DiddiLeija** [comment]
Ok. I will start tomorrow.
