### ISSUE TITLE
[BUG] setuptools build pulls in data of pkg_resources.tests

### ISSUE THREAD

**Issue by stanislavlevin** [pypa/setuptools#2624]
### setuptools version

54.2.0

### Python version

3.9.2

### OS

ALTLinux

### Description

Build the setuptools results in the data of `pkg_resources.tests` is packaged into setuptools.

OS Distributions usually don't include tests in Python distro packages since they pull in extra tests dependencies. But at the same time it is unlikely that end users will run tests in production. In this case the tests data is packaged without tests.

### Expected behavior

The data of `pkg_resources.tests`(as well as any tests and their data) should not be packaged into setuptools distribution.

### How to Reproduce

```console
python3 setup.py build -v 2>/dev/null | grep 'tests'
```

### Output

```console
copying pkg_resources/tests/data/my-test-package-source/setup.py -> build/lib/pkg_resources/tests/data/my-test-package-source

```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Well that's annoying. I'd expect if I told `find` to `exclude` "*.tests", it would exclude "*.tests" and everything beneath it. After all, how can it include subpackages of an excluded package? I'm not sure the right fix here is to just get more aggressive with the excludes. Can we investigate further and see if there's a good reason Setuptools is including data for an excluded package?

**Comment by abravalheri** [comment]
Hi @jaraco, I investigated this in https://github.com/pypa/setuptools/pull/3018 and https://github.com/pypa/setuptools/issues/3017.

As noted in https://github.com/pypa/setuptools/issues/3017#issuecomment-1008202943, `find` and `find_namespace` will not automatically exclude sub-packages of a previously excluded parent package (this is explicitly mentioned in a code comment).

For the time being I think we can close this issue. If by any chance you think we should consider changing the default `exclude` behaviour, please let me know.
