### ISSUE TITLE
Resurrect reporting to codecov

### ISSUE THREAD

**Issue by webknjaz** [pypa/setuptools#2642]
### setuptools version

`main`

### Python version

N/A

### OS

N/A

### Description

I've been doing some security audit after the recent codecov supply chain attack and discovered that there's been no coverage updates on the service since Dec 20.

I tracked it down to this change: https://github.com/pypa/setuptools/pull/2486.

Funny enough, I've left a number of comments reviewing that but still missed this issue ;)

It used to be integrated in Travis CI and AppVeyor
- https://github.com/pypa/setuptools/pull/2486/files?file-filters%5B%5D=.ini&file-filters%5B%5D=.toml&file-filters%5B%5D=.yml#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485L60
- https://github.com/pypa/setuptools/pull/2486/files?file-filters%5B%5D=.ini&file-filters%5B%5D=.toml&file-filters%5B%5D=.yml#diff-92ab9a36df5d8e9f7076f2fdec59492d1ac2d9cf27ea046767a7fc4d542ef3dcL43

and the toxenv is still in place but its invocation never survives the migration to GHA and so this needs to be corrected.

Fixing this should be pretty straightforward — just integrate https://github.com/codecov/codecov-action.

### Expected behavior

Coverage to be actually reported to codecov.

### How to Reproduce

Look at https://app.codecov.io/gh/pypa/setuptools/commits — the last known report was 4 month ago.

### Output

N/A

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by tanvimoharir** [comment]
Hi,
I would like to work on this.
Thanks

**Comment by webknjaz** [comment]
Sure, feel free to send a PR.

**Comment by tanvimoharir** [comment]
hi @webknjaz ,
I have drafted a PR (#2693). I have not worked with codecov before (not very confident about it either) which is why I marked the PR as draft.
Let me know if the change looks correct or otherwise.
Thanks

**Comment by tanvimoharir** [comment]
I may have missed few things, checking the build failure and looking into it.
Thanks
