### ISSUE TITLE
pip traceback on cpython 3.6

### ISSUE THREAD

**Issue by dstromberg** [pypa/setuptools#2660]
### setuptools version

21.1

### Python version

CPython 3.6

### OS

Debian 10.9

### Description

I can't tell the version number with --version, because pip tracebacks.

After a pip3 --upgrade today, I consistently get tracebacks like:
+ /usr/local/cpython-3.6/bin/pip3 install pygments
Traceback (most recent call last):
  File "/usr/local/cpython-3.6/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/cpython-3.6/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/cpython-3.6/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/cpython-3.6/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/cpython-3.6/lib/python3.6/site-packages/pip/_internal/cli/cmdoptions.py", line 30, in <module>
    from pip._internal.utils.hashes import STRONG_HASHES
  File "/usr/local/cpython-3.6/lib/python3.6/site-packages/pip/_internal/utils/hashes.py", line 2, in <module>
    from typing import TYPE_CHECKING, BinaryIO, Dict, Iterator, List, NoReturn
ImportError: cannot import name 'NoReturn'

It doesn't appear to matter which pypi package I install - they all traceback like that.

I tried deleting python3-setuptools with Debian's package manager; it did not help.

I also tried deleting pip and reinstalling it; it did not help.

Thanks for the cool tools!

### Expected behavior

I tried to install pygments and treap. Both gave the traceback shown above.

### How to Reproduce
+ /usr/local/cpython-3.6/bin/pip3 install --upgrade pip
The directory '/home/dstromberg/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/dstromberg/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/ac/cf/0cc542fc93de2f3b9b53cb979c7d1118cffb93204afb46299a9f858e113f/pip-21.1-py3-none-any.whl (1.5MB)
    100% |################################| 1.6MB 672kB/s 
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-21.1

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @dstromberg thank you very much for reporting this issue!

I am not entirely sure I understood your message, there seems to be an error where `pip` tries to import `NoReturn` from `typing`, is that it?

If that is the case, this issue is not related to setuptools, is it?

**Comment by abravalheri** [comment]
For the time being, I think I will close it, since I cannot see what `setuptools` can do to solve this problem (moreover, Python 3.6 is not supported, and `NoReturn` should definitely be present in Python 3.7...).

But please feel free to ping again if you have any information that relates this problem to `setuptools` (specially if it persists in Python >= 3.7)
