### ISSUE TITLE
Map tests_require to extras_require['tests']

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#267]
Originally reported by: **remcohaszing (Bitbucket: [remcohaszing](http://bitbucket.org/remcohaszing), GitHub: [remcohaszing](http://github.com/remcohaszing))**

---

I often use the standalone `nosetests` command to run unittests instead of `./setup.py test` or `./setup.py nosetests`.

In order to do this, I need to install the `tests_require`. A common workaround is to use the following snippet in a `setup.py`:

```
#!python

tests_require=[...]

setup(
    extras_require={
        'tests': tests_require
    },
    tests_require=tests_require)
```

I suggest to add the `tests_require` to the `extras_require['tests']` in the setup function.

This allows us to just install `tests_require` by typing:

```
#!sh

$ pip install -e .\[tests\]
```

If this proposal is accepted, I am willing to implement it.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/267

**Comment by abravalheri** [comment]
Hello, I suppose that this proposal became obsolete now that `python setup.py tests` and `tests_require` were both deprecated... So I will close this issue for the time being.

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
