### ISSUE TITLE
[FR] Support package substitutes (alternatives)

### ISSUE THREAD

**Issue by SomeoneSerge** [pypa/setuptools#2696]
### What's the problem this feature will solve?

There are packages that provision same modules and same functionality, e.g. `opencv-python` vs `opencv-python-headless`. For many purposes, those packages are substitutable one for another. Some packages may need to declare a dependency on the union of those alternatives, e.g. `albumentations` is [trying to declare](https://github.com/albumentations-team/albumentations/blob/d1082f32a64b2083ba84bcaee1274e42715050bb/setup.py#L13) a dependency on any of a choice of opencv packages.

As there is no support for this situation in `setuptools` or any pep-517 backend, `albumentations` ends up reporting non-deterministic dependencies depending on the runtime environment: [by querying the installed distributions](https://github.com/albumentations-team/albumentations/blob/d1082f32a64b2083ba84bcaee1274e42715050bb/setup.py#L41). The `albumentations` is not an exceptional case, there is a public bad advice in top google's output for "setuptools alternative requirements": https://stackoverflow.com/a/44769537/9041156

This non-static and non-deterministic behaviour breaks the new (and any hypothetical) dependency solver:

```
$ pip install opencv-python albumentations
...
Installing collected packages: ... opencv-python-headless, opencv-python, albumentations
```

Note that for `pip` the effect is rather mild: as `pip` doesn't check for conflicts, whichever package happens to be installed later overwrites the contents of the last, and things seem to work.  This is not the case e.g. for [mach-nix](https://github.com/DavHau/mach-nix/issues/294), which (IIUC) builds its own dependency graph and checks things for conflicts before putting them together.

It seems to be already a consensus that python packages' metadata (like their direct dependencies) must be static and available without "computation": now tools need to allow package writers to declare their dependencies statically

### Describe the solution you'd like

1. I see there exists a `provides=` [keyword argument](https://setuptools.readthedocs.io/en/latest/references/keywords.html) in setuptools that is documented to be currently ignored. I believe this feature now needs to be implemented for pip's dependency solver to be useful.
2. Further, new options `conflicts=` and `replaces=`, as in e.g. [pacman's PKGBUILD](https://archlinux.org/pacman/PKGBUILD.5.html), would allow to rewrite `opencv-python` and `opencv-python-*` in a way that `pip` will know not to install them simultaneously and won't think it needs to install them simultaneously
3. One could also add support for "unions" on the depending site, i.e. requiring a `opencv-python|opencv-python-headles|...`, but I couldn't (in time) find any other actual package manager that went this way

### Alternative Solutions

In case of `albumentations`: perhaps move different `opencv`s into `extras` for the time being; this doesn't tackle the issue itself of course

In case of `opencv`: maybe it's possible to ship different options under the same name (`opencv-python`) and make specific choices available with some modifiers, perhaps `opencv-python[headless]`, etc. I don't know if this is possible right now, I'd need to do some search

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by FRidh** [comment]
Changes like these typically go through a PEP as it effects the entire ecosystem, and not just the setuptools backend. Topics such as these are primarily discussed on https://discuss.python.org/c/packaging. See also
- https://discuss.python.org/t/idea-selector-packages/4463/15
- https://discuss.python.org/t/options-to-build-the-same-package-in-different-ways-with-different-build-dependencies/4458/1

**Comment by abravalheri** [comment]
Hello, thank you very much for bringing this topic up.
As previously mentioned, the best place to discuss such change would be the https://discuss.python.org/c/packaging.

So I think I will close the issue for now, but please feel free to "re-open" it (or open a new one), if any action is needed from setuptools after some standardisation effort.
