### ISSUE TITLE
[FR] distutils.errors.* is not fully re-exported

### ISSUE THREAD

**Issue by QuLogic** [pypa/setuptools#2698]
### What's the problem this feature will solve?

The [Migration Advice in PEP 0632](https://www.python.org/dev/peps/pep-0632/#migration-advice) says that `setuptools` is a sufficient replacement for `distutils.errors`. However, only `DistutilsError` and `RemovedCommandError` exist there. In `distutils`, there are:
```
In [7]: [e for e in dir(distutils.errors) if e.endswith('Error')]
Out[7]: 
['CCompilerError',
 'CompileError',
 'DistutilsArgError',
 'DistutilsByteCompileError',
 'DistutilsClassError',
 'DistutilsError',
 'DistutilsExecError',
 'DistutilsFileError',
 'DistutilsGetoptError',
 'DistutilsInternalError',
 'DistutilsModuleError',
 'DistutilsOptionError',
 'DistutilsPlatformError',
 'DistutilsSetupError',
 'DistutilsTemplateError',
 'LibError',
 'LinkError',
 'PreprocessError',
 'UnknownFileError']
```
While all of the `Distutils`-prefixed ones derive from `DistutilsError`, the ones without the prefix are derived from `CCompilerError`, and so cannot be caught using anything exported by `setuptools`. Concretely, this makes it difficult to check for compiler flags, as [done here](https://github.com/matplotlib/matplotlib/blob/69395749a4e588eade55b90dbf095549258f4b16/setup.py#L62-L72).

### Describe the solution you'd like

Re-export all `distutils.errors.*` in `setuptools.errors`.

### Alternative Solutions

Currently, we use `distutils.errors`, but won't be able to after Python 3.12. One can use a generic `Exception` too, but that's not recommended.

Or as a complete alternative, if `setuptools` had a way to check whether a compiler supported a flag in a builtin way, then we wouldn't need to catch the `CompileError` ourselves.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by grlee77** [comment]
I had this same question regarding use of this in scikit-image's setup.py. What is the recommended path forward here?
