### ISSUE TITLE
[BUG] "Unknown MS Compiler version" when compiling with mingw32

### ISSUE THREAD

**Issue by hickford** [pypa/setuptools#2704]
From https://bugs.python.org/issue25251#msg251758

> Hi distutils. I previously used compiler=mingw32 with success. Today I installed Visual Studio 2015. Now compiler=mingw32 gives me an error
>
> File "c:\python35\lib\distutils\cygwinccompiler.py", line 86, in get_msvcr     raise ValueError("Unknown MS Compiler version %s " % msc_ver) ValueError: Unknown MS Compiler version 1900
>
> Any ideas? I don't understand why what msvc I have installed affects build with mingw32

This code still exists in https://github.com/pypa/setuptools/blob/main/setuptools/_distutils/cygwinccompiler.py

**Comment by hickford** [comment]
https://bugs.python.org/issue25251#msg251758 includes a fix. I'll share a pull request

**Comment by imba-tjd** [comment]
See my PR https://github.com/pypa/distutils/pull/41 and its discussion.

Though I don't have the experience to ensure it's OK

**Comment by imba-tjd** [comment]
This can be closed.

**Comment by kerneltravel** [comment]
may caused by 32bit / 64bit python and lib mis-match
