### ISSUE TITLE
[FR] replace use sphinx-inline-tabs module by something with less dependencies

### ISSUE THREAD

**Issue by kloczek** [pypa/setuptools#2705]
### What's the problem this feature will solve?

Currently setuptools documentation uses `sphinx-inline-tabs` which has very long list of dependencies because it depends on `myst-parser` and than this module depends on may more from notebook and jupiter project.

IMO something like `setuptools` on build and test module and generate documentation should rely only raw sphinx or at least building documentation should have.

### Describe the solution you'd like

From point of view of replacing  `sphinx-inline-tabs` I think that 
https://github.com/executablebooks/sphinx-tabs could be used. That module provides tabs extension which does not depend on anything else than just sphinx and pytest (on building module and documentation, installing, and testing).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Well, this doesn't seem relevant since `sphinx-inline-tabls` is not being used at this time.

https://github.com/pypa/setuptools/blob/a5ed0a8f7be889baba57c2f874ba32e5b09ecfd8/docs/conf.py#L1
