### ISSUE TITLE
Allow Python executable for scripts to be overridden by easy_install.

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#272]
Originally reported by: **genexp (Bitbucket: [genexp](http://bitbucket.org/genexp), GitHub: [genexp](http://github.com/genexp))**

---

I have multiple Python installs, and prefer not to use virtual env.  I have some simple environment configuration scripts that change which python is in my path as needed.  Unfortunately, setuptools (seems?) to hardcode the path to the python binary that was used during install for script locations.  As an example, I get:

```
$:cat /usr/local/bin/pm
#!/usr/bin/python
....
```

Rather than hardcode the path to the Python executable for scripts, I think we should use something like:

```
#!/usr/bin/env python
```

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/272

**Comment by abravalheri** [comment]
Hello, I suppose we can close this issue now that `easy_install` and direct invoking `python setup.py install` have been deprecated and widely replaced by other installation means, such as `pypa/pip`.

Moreover, the installer is now supposed to generate the wrappers (see https://github.com/pypa/pip/issues/1067)...

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
