### ISSUE TITLE
[BUG] setup.py install doesnt escape whitespaces

### ISSUE THREAD

**Issue by moonburnt** [pypa/setuptools#2752]
### setuptools version

setuptools==57.4.0

### Python version

Python 3.9

### OS

Manjaro Linux

### Additional environment information

Path to project/project's venv must contain whitespaces in it

### Description

Im using setuptools + venv on linux. If path to environment contains spaces in it, attempting to run "python setup.py install" for project with entry points finish successfully, but then Im unable to run any of these coz doing so cause crash with "bad interpreter: no such file or directory" error.

### Expected behavior

Code that generate launch scripts should escape whitespaces and other weird characters, if present. Coz its not user's responsibility to only have paths consisting of english A-Z.

### How to Reproduce

0. Create some project on path that contain spaces. Say, `/path/to/my project/project`
1. Create venv in there, `source .venv/bin/activate`, then install all required dependencies
2. Create valid setup.py with some entry point in it
3. `python setup.py install`
4. No errors will happen during installation, but attempting to run any launcher script generated from entry point will return `bash: path/to/my project/project/.venv/bin/runmyproject /path/to/my: bad interpreter: no such file or directory`.

E.g what exactly happens - code that generate launcher scripts didnt care if generated paths have whitespaces, which caused exec to only read path to first space.

### Output

```console
runmyproject

bash: path/to/my project/project/.venv/bin/runmyproject /path/to/my: bad interpreter: no such file or directory
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by moonburnt** [comment]
Poetry has the very same issue in specified (well, except everything is described in pyproject.toml instead of setup.py, of course) case (moreover - you cant even do "poetry shell" with said conditions). So maybe its not exactly fault of setuptools, idk

**Comment by jaraco** [comment]
Unfortunately, the [issue lies with Unix](https://blog.jaraco.com/unix-doesnt-support-spaces-in-filenames/). There's not much Setuptools (or any script generator) can do until Unix programmers figure out a syntax for shebangs that supports those (valid) file paths.

Moreover, Setuptools is deprecating `setup.py install`. You should use `pip install .` instead, though I don't expect that to solve your issue ; it will just push the issue to that project.

Actually, I just checked, and it looks like `pip`/`distlib` have a workaround for the Unix limitation:

```
draft $ python -m venv 'foo bar'
draft $ './foo bar/bin/pip' install -q -U pip pipx
draft $ bash
bash-5.1$ ./foo\ bar/bin/pipx --help | head -n 6
usage: pipx [-h] [--version] {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,completions} ...

Install and execute apps from Python packages.

Binaries can either be installed globally into isolated Virtual Environments
or run directly in a temporary Virtual Environment.
bash-5.1$ cat foo\ bar/bin/pipx
#!/bin/sh
'''exec' "/Users/jaraco/draft/foo bar/bin/python" "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from pipx.main import cli
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
```

So that should be your solution.
