### ISSUE TITLE
[BUG] source distributions do not preserve case in keys of setup.cfg

### ISSUE THREAD

**Issue by aerusso** [pypa/setuptools#2773]
### setuptools version

HEAD (58.0.2)

### Python version

(irrelevant)

### OS

(irrelevant)

### Description

When building a source `tar.gz` with `python -m build`, `edit_config` of `setuptools` is called to record information about the call in `setup.cfg`.  During the rewrite, the case of the keys in the file is lost -- most notably, `options.data_files` loses the case of destination paths.

### Expected behavior

The case of destination paths is preserved for `data_files`.  More generally, all keys have their case preserved when building source `tar.gz`s

### How to Reproduce

1. Create a `setup.cfg` with

```
[options.data_files]
cAsE=
  file
  file2
```
2. `touch file file2`
3. `python3 -m build`

### Output

`setup.cfg` in the tar.gz loses the case: (extract with `tar -xf dist/UNKNOWN-0.0.0.tar.gz && cat UNKNOWN-0.0.0/setup.cfg`)

```
[options.data_files]
case = 
        file
        file2

[egg_info]
tag_build = 
tag_date = 0
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Here's the stack when `edit_config` gets called:

```
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/command/sdist.py", line 473, in make_distribution
    self.make_release_tree(base_dir, self.filelist.files)
  File "/Users/jaraco/code/public/pypa/setuptools/setuptools/command/sdist.py", line 158, in make_release_tree
    self.get_finalized_command('egg_info').save_version_info(dest)
  File "/Users/jaraco/code/public/pypa/setuptools/setuptools/command/egg_info.py", line 195, in save_version_info
    edit_config(filename, dict(egg_info=egg_info))
  File "/Users/jaraco/code/public/pypa/setuptools/setuptools/command/setopt.py", line 40, in edit_config
```

**Comment by jaraco** [comment]
Configparser [converts keys to lowercase](https://docs.python.org/3/library/configparser.html#quick-start) unless `optionxform = lambda x: x`.

**Comment by jaraco** [comment]
Oh, shoot. I just noticed you'd created a PR :/
