### ISSUE TITLE
use_2to3 is invalid (suds-jurko)

### ISSUE THREAD

**Issue by qiyang0221** [pypa/setuptools#2784]
### setuptools version

setuptools==58.0.4

### Python version

Python 3.8

### OS

Ubuntu

### Description

try pip install suds-jurko==0.6 and fail

### Expected behavior

install suds-jurko==0.6 successfully

### How to Reproduce

pip install suds-jurko==0.6

### Output

```console


command: /usr/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wo48v30_/suds-jurko_a8f10ed41d294fe38d06258da053bec4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wo48v30_/suds-jurko_a8f10ed41d294fe38d06258da053bec4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-y09cg48r
--
  | [2021-09-12T03:10:20Z]          cwd: /tmp/pip-install-wo48v30_/suds-jurko_a8f10ed41d294fe38d06258da053bec4/
  | [2021-09-12T03:10:20Z]     Complete output (1 lines):
  | [2021-09-12T03:10:20Z]     error in suds-jurko setup command: use_2to3 is invalid.
  | [2021-09-12T03:10:20Z]     ----------------------------------------
  | [2021-09-12T03:10:20Z] WARNING: Discarding https://files.pythonhosted.org/packages/bd/6f/54fbf0999a606680d27c69b1ad12dfff62768ecb9fe48524cebda6eb4423/suds-jurko-0.6.tar.bz2#sha256=29edb72fd21e3044093d86f33c66cf847c5aaab26d64cb90e69e528ef014e57f (from https://pypi.org/simple/suds-jurko/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  | [2021-09-12T03:10:20Z] ERROR: Could not find a version that satisfies the requirement suds-jurko==0.6 (from versions: 0.4.1.jurko.1, 0.4.1.jurko.2, 0.4.1.jurko.3, 0.4.1.jurko.4, 0.4.1.jurko.5, 0.5, 0.6)
  | [2021-09-12T03:10:20Z] ERROR: No matching distribution found for suds-jurko==0.6


```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
This issue is an intentional change as a result of [version 58 release](https://setuptools.readthedocs.io/en/latest/history.html#v58-0-0). The issue should be fixed in the suds-jurko project.

**Comment by jaraco** [comment]
The [Homepage link from the PyPI project](https://bitbucket.org/jurko/suds) is 404, and the last release was in 2014, so it seems the project is abandoned. I vaguely remember working on that project. I may even have been the person who contributed the `use_2to3` usage (I can't recall). I've reached out to the author via email to see if I can take over maintenance of the project and unblock this issue. In the meantime, projects that depend on `suds-jurko` may need to pin to `setuptools<58` or build their own wheels of the package to avoid the issue.

If I don't hear back from Jurko or if he's unwilling to hand over maintenance or address the issue, I'll probably create yet another fork of the project.

**Comment by jaraco** [comment]
I found https://github.com/andersinno/suds-jurko, which not only contains the code history, but also seems to have changes that were previously unreleased.

**Comment by qiyang0221** [comment]
Totally make sense. Thanks, Jason!

**Comment by jaraco** [comment]
Update: I've been in contact with jurko and am working out a plan to update suds-jurko to work in a Setuptools 58 world.

**Comment by jaraco** [comment]
Being yet unable to find bandwidth to maintain the project, I've uploaded a wheel to https://m.devpi.net/jaraco/dev that consumers can use to bypass the issue:

```
$ pip-run -q wheel 'setuptools<58' -- -m pip wheel suds-jurko
Collecting suds-jurko
  Downloading suds-jurko-0.6.zip (255 kB)
     |████████████████████████████████| 255 kB 4.3 MB/s 
Building wheels for collected packages: suds-jurko
  Building wheel for suds-jurko (setup.py) ... done
  Created wheel for suds-jurko: filename=suds_jurko-0.6-py3-none-any.whl size=457381 sha256=a0b10c4a6e1e1ec96631a51e171837b26617cf66a51b57929f8ab6f08e6a9e10
  Stored in directory: /Users/jaraco/Library/Caches/pip/wheels/5b/fa/0c/9b96beb18b987215aa4611dcf3b2c3fd489c0f08c9c362a530
Successfully built suds-jurko
$ devpi upload *.whl
register suds-jurko-0.6 to https://m.devpi.net/jaraco/dev/
file_upload of suds_jurko-0.6-py3-none-any.whl to https://m.devpi.net/jaraco/dev/
```

As you can see, I downloaded the sdist directly from PyPI and uploaded it to devpi. Users can use that index to get that build:

```
$ pip install -i https://m.devpi.net/jaraco/dev suds
```

**Comment by jaraco** [comment]
I've forked suds-jurko into a new project, [suds-bis](https://pypi.org/project/suds-bis) with an 0.6 release matching the behavior of suds-jurko 0.6. This build includes wheels and will install on Python 2 and Python 3. Please use it in place of `suds-jurko`.

**Comment by jaraco** [comment]
Today, I learned that [suds-community](https://pypi.org/project/suds-community) exists and is actively maintained. Forget about suds-bis and use suds-community instead.
