### ISSUE TITLE
--script-dir being ignored

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#279]
Originally reported by: **charlie_x (Bitbucket: [charlie_x](http://bitbucket.org/charlie_x), GitHub: Unknown)**

---

Hi,

I'm trying to set up easy_install on a Haiku system and have to use different paths. I've managed to install libraries using the `--user` option but I'm having trouble with installing the scripts into the desired directory. It seems that whatever I do `--script-dir` is being ignored but I'm not getting any errors. Any pointers?

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/279

**Comment by abravalheri** [comment]
Hello, I suppose we can close this issue now that `easy_install` has been deprecated and widely replace by other installation means, such as `pypa/pip`.

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
