### ISSUE TITLE
egg_info command must write setup.cfg stanza idempotentally

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#280]
Originally reported by: **warsaw (Bitbucket: [warsaw](http://bitbucket.org/warsaw), GitHub: [warsaw](http://github.com/warsaw))**

----------------------------------------

The setup.py sdist command runs the egg_info command which will write an [egg_info] section to your existing setup.cfg file.  However, the keys in this file are not written in a predictable order, and are in fact written in "dictionary" order.

This can cause a problem for package development on Debian because of the following scenario:

Upstream creates a distribution tarball for PyPI using `python3 setup.py sdist`.  Upstream includes a setup.cfg that does not have an [egg_info] section.  The resulting tarball will have an [egg_info] section added, containing tag_svn_revision, tag_build, and tag_date keys.

Using Debian build tools may also run the egg_info command which will rewrite the [egg_info] stanza, but it may do so with the keys *in a different order*.  This will cause the build tools to see an unaccounted for change in the upstream file and will cause the source package build process to fail.  Because there order is unpredictable, there's no good way to ensure that the build process will produce the same setup.cfg file that the sdist command generated.

The egg_info command, whether run explicitly or implicitly as part of sdist, *must* write that stanza in a predictable order.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/280

**Comment by jaraco** [comment]
This was fixed in #553 and released as 20.10.0.
