### ISSUE TITLE
[FR] Implement PEP 660 -- Editable Installations

### ISSUE THREAD

**Issue by pradyunsg** [pypa/setuptools#2816]
### What's the problem this feature will solve?

PEP 660 standardises the mechanism that `setup.py develop` uses to make "editable" packages.

Currently, pip needs to implement fairly horrible hacks to make legacy `setup.py develop` builds work. It'd be great if setuptools could implement PEP 660, which would be the last item from setuptools' end before pip can start the process of removing the legacy directly-call-setup.py build system.

### Describe the solution you'd like

PEP 660's build_editable hook gets implemented in aetuptools.

### Alternative Solutions

Not doing this.

I imagine this will mean that either (a) pip continues to maintain editable installs for setuptools or (b) pip drops the legacy build system entirely and users of setuptools projects will no longer be able to make editable installations.

I don't think (b) is happening any time soon, and it'd likely be best to implement the hook here.

### Additional context

IIUC, this has been implemented in setuptools-pep660 already. It might not be a lot of work to migrate the work done there into seriptools directly.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
See [the discussion](https://discuss.python.org/t/implementing-pep-660-for-setuptools/9193) and dholth/setuptools-pep660#1.

**Comment by ichard26** [comment]
[I took a stab at this](https://github.com/ichard26/setuptools/commit/bbe070e735f2e4314da2228bdac1dd2c5c1705e7) but I can't seem to find a reliable way to [query the importable base](https://github.com/ichard26/setuptools/commit/bbe070e735f2e4314da2228bdac1dd2c5c1705e7#r59675825) of the packages / modules (i.e. the parent directory of {name}.dist-info generated from an in-tree build). For what it's worth this is my first time working in the setuptools codebase so there's probably something I'm missing :)

**Comment by ichard26** [comment]
**Status update**: after adding some more runtime patching of setuptools internals to query all of the information I need I got an implementation that can do an editable install for at least a simple single pure-Python module distribution and a src-style pure-Python multi-package distribution (psf/black, duh :slightly_smiling_face:) :tada:

https://github.com/pypa/setuptools/compare/main...ichard26:pep-660  

I need to test other situations and packaging configurations, but I've ran out of time for today :)

**Comment by tacaswell** [comment]
I think that preserving editable installs for packages with c / c++ / cython installations via some mechanism is cirtical (I say with my Matplotlib and h5py hats on).

I would be perfectly happy to absorb changes to our setup.py / pyproject.toml / built incantation, but there needs to be some path forward.

**Comment by ichard26** [comment]
> I think that preserving editable installs for packages with c / c++ / cython installations via some mechanism is cirtical (I say with my Matplotlib and h5py hats on).

Right, unfortunately I don't really have much experience in this domain. It is my understanding that PEP 660's way of handling extensions is by mandating a in-tree and in-place extension build (effectively `python setup.py build_ext -i`) before the editable wheel is produced. This obviously means the editable install / the in-place extension build will have to be redone to see changes in the extensions but other than that I don't see how using a root .pth file changes things as it's basically how `python setup.py develop` worked anyway, just codified ^^

**Comment by pradyunsg** [comment]
For completeness, making an update here with how I understand the state of affairs to be.

With #1688 closed, this is now a blocker for getting editable installs working for setuptools' new pyproject.toml only projects.

In https://github.com/pypa/setuptools/pull/2872, there has been extensive discussion about the implementation approach that setuptools can take for this. There seems to be no clear concensus about how to implement the PEP 660 hooks -- there's significant pushback from the maintainers for implementing the PEP 660 hooks (that enable editable installations, without a setup.py file) using a mechanism similar to `setup.py develop` today.

**Comment by EwoutH** [comment]
Thanks a lot for the effort so far! Is there any update it’s progress?

**Comment by abravalheri** [comment]
Hi @EwoutH I left a PR with a possible approach in https://github.com/pypa/setuptools/pull/3265 (so the other setuptools maintainers can see if it matches their expectation). Please feel free to have a look and even submit a review.

I just noticed that I got a little bit behind master so I will be rebasing it soon.

**Comment by pradyunsg** [comment]
This is now a blocker for pip (and ensurepip) excluding setuptools in new virtual environments. The latest version of pip is capable of using the build isolation when setuptools is not available within the environment, even when there’s no pyproject.toml file.

**Comment by pradyunsg** [comment]
Closing this out, since https://github.com/pypa/setuptools/pull/3265 implemented this.

It still has an experimental flag on it, but it works and that's the part that I care about. I've now seen multiple people point to this issue to say that editable installs are a mess in Python -- all the pieces have worked for quite some time now. :)

**Comment by samuelcolvin** [comment]
Thanks so much @pradyunsg.

**Comment by djhoese** [comment]
> which is going to be solved once that PR reaches main.

Is there a milestone or pull request for when that will happen? I see the PR was merged to the `feature/pep660`, but don't see anything else using that branch. I'm not familiar with the setuptools workflow so let me know if I'm missing something. I'm one of those people that would like to use pyproject.toml without a setup.py and it seems I need that PR.

**Comment by astrojuanlu** [comment]
I couldn't find an open PR for the `feature/pep660` branch either, however @abravalheri announced a month ago that they were conducting preliminary tests https://discuss.python.org/t/help-testing-pep-660-support-in-setuptools/16904?u=astrojuanlu

**Comment by abravalheri** [comment]
@djhoese, @astrojuanlu, you can track the progress in #3488. I am considering that the round of community feedback is reaching its end, so I plan to do a release soon (in another week or so).
