### ISSUE TITLE
[FR] Automatically include setup.cfg `file:` files into the sdist

### ISSUE THREAD

**Issue by Sinclert** [pypa/setuptools#2821]
### What's the problem this feature will solve?

When developers define a `setup.cfg` file instead of the _classic_ `setup.py` file for setting the metadata for their packages, they have a small set of [special directives](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#specifying-values) (i.e. `attr:`, `file:`...) to take advantage of.

These _directives_ cover a standardized use case of metadata building, which involves reading values from specific files in order to construct the package overall metadata. An example would be:
```INI
[metadata]
name = my-package
version = file: VERSION
```

All files being referenced with the `file:` directive are **absolutely mandatory** when building the package _built distribution_ (as it includes the complete metadata), and still, they are **not** automatically included into the _source distribution_ where they are supposed to be available for access.

This lack of "_automatic inclusion of `file:` referenced files in the source distribution_" forces developers to include those files to their projects `MANIFEST.in`, when it could be easily avoidable with a bit of intelligence on `setuptools` side.

### Describe the solution you'd like

When defining a certain file within the `file:` _setup.cfg_ directive, it should be automatically picked up when building the package's _source distribution_.

### Alternative Solutions

Due to the lack of this feature, developers need to include those files into the `MANIFEST.in`:

```
### NOTE:
### Necessary to build a valid source distribution
include VERSION
```

### Additional context

This issue comes from an internal conversation on the [IRIS-HEP](https://iris-hep.org/) Slack channel, where @henryiii confirmed that what I just described is, indeed, a _limitation_, and that this was the correct repository to state the suggestion.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Sinclert** [comment]
👋🏻 Hey @abravalheri!

Just saw there has been some discussion regarding the dynamic metadata directives (`attr:` / `file:`). I would love to contribute a PR improving `setup.cfg` case handling, but I lack context of where to start. Do you know any piece of documentation covering how these directives are processed?

**Comment by abravalheri** [comment]
Hi @Sinclert, the `attr:` and `file:` directives are handled in [setuptools/config/setupcfg.py](https://github.com/pypa/setuptools/blob/ac9d7d204f6a49db4e70a5880c420dcb5c509081/setuptools/config/setupcfg.py#L369) (for `setup.cfg`) and [setuptools/config/pyprojecttoml.py](https://github.com/pypa/setuptools/blob/ac9d7d204f6a49db4e70a5880c420dcb5c509081/setuptools/config/pyprojecttoml.py#L307) (for `pyproject.toml`).

The description of how they are processed is given in https://setuptools.pypa.io/en/latest/userguide/declarative_config.html and https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata.

Setuptools basically resolve them when reading the configuration file and sets the corresponding attributes of a `setuptools.dist.Distribution` object, which inherits from [`distutils.dist.Distribution`](https://setuptools.pypa.io/en/latest/deprecated/distutils/apiref.html#distutils.core.Distribution).

**Comment by Sinclert** [comment]
Thanks for working on this @abravalheri

**Comment by abravalheri** [comment]
Thank you very much for the initial push @Sinclert, I used a lot of your code/ideas in the process of creating this PR.
