### ISSUE TITLE
easy_install --quiet --dry-run -U package is not really quiet

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#284]
Originally reported by: **sorin (Bitbucket: [sorin](http://bitbucket.org/sorin), GitHub: [sorin](http://github.com/sorin))**

---

easy_install --quiet --dry-run -U packname
would still output at least the:
install_dir /usr/local/lib/python2.6/dist-packages/

This prevents us from properly running a quite update from crontab, where we are supposed to have output only if there are errors.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/284

**Comment by benoit-pierre** [comment]
No longer applicable.

**Comment by benoit-pierre** [comment]
Oops, wrong tab...

**Comment by abravalheri** [comment]
Hello, I suppose we can close this issue now that `easy_install` has been deprecated and widely replace by other installation means, such as `pypa/pip`...

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
