### ISSUE TITLE
[BUG] Deprecation warning when building wheels

### ISSUE THREAD

**Issue by domdfcoding** [pypa/setuptools#2847]
### setuptools version

setuptools==58.3.0 or setuptools==58.4.0

### Python version

Python 3.8

### OS

Ubuntu 20.04

### Description

Attempting to install or build a wheel of a project using setuptools results in the following warning:

```
venv/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
```

<details><summary>Full traceback:</summary>

```python
  Traceback (most recent call last):
    File "venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 20, in <module>
      setup(
    File "venv/lib/python3.8/site-packages/setuptools/__init__.py", line 159, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 301, in run
      install = self.reinitialize_command('install',
    File "/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 214, in reinitialize_command
      cmd = _Command.reinitialize_command(self, command, reinit_subcommands)
    File "/usr/lib/python3.8/distutils/cmd.py", line 305, in reinitialize_command
      return self.distribution.reinitialize_command(command,
    File "/usr/lib/python3.8/distutils/dist.py", line 938, in reinitialize_command
      command = self.get_command_obj(command_name)
    File "/usr/lib/python3.8/distutils/dist.py", line 858, in get_command_obj
      cmd_obj = self.command_obj[command] = klass(self)
    File "venv/lib/python3.8/site-packages/setuptools/__init__.py", line 178, in __init__
      _Command.__init__(self, dist)
    File "/usr/lib/python3.8/distutils/cmd.py", line 62, in __init__
      self.initialize_options()
    File "/venv/lib/python3.8/site-packages/setuptools/command/install.py", line 34, in initialize_options
      warnings.warn(
  setuptools._deprecation_warning.SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
```
</details>

This occurs with both build and pip (``pip install`` and ``pip wheel``).

### Expected behavior

No warning is emitted when building a wheel or installing using pip or build.

### How to Reproduce

1. Install setuptools 58.3.0 or 58.4.0
2. Run `PYTHONWARNINGS=error pip wheel domdf_python_tools==3.1.0 --no-binary domdf_python_tools -v --no-deps`

This also occurs with `whey` and `natsort`.

### Output

```console
Looking in indexes: http://localhost:3141/root/staging
Collecting domdf_python_tools==3.1.0
  Downloading http://localhost:3141/root/pypi/%2Bf/c55/b356a87d53841/domdf-python-tools-3.1.0.tar.gz (99 kB)
  Installing build dependencies: started
  Running command /tmp/venv/bin/python3 /tmp/pip-standalone-pip-7m38gblg/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-myy0rzw0/overlay --no-warn-script-location --no-binary domdf-python-tools --only-binary :none: -i http://localhost:3141/root/staging -- 'setuptools>=40.6.0' 'wheel>=0.34.2'
  Looking in indexes: http://localhost:3141/root/staging
  Collecting setuptools>=40.6.0
    Downloading http://localhost:3141/root/pypi/%2Bf/e8b/1d3127a0441fb/setuptools-58.4.0-py3-none-any.whl (946 kB)
  Collecting wheel>=0.34.2
    Downloading http://localhost:3141/root/pypi/%2Bf/210/14b2bd93c6d00/wheel-0.37.0-py2.py3-none-any.whl (35 kB)
  Installing collected packages: wheel, setuptools
  Successfully installed setuptools-58.4.0 wheel-0.37.0
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command /tmp/venv/bin/python3 /tmp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp32ew7q_j
  running egg_info
  writing domdf_python_tools.egg-info/PKG-INFO
  writing dependency_links to domdf_python_tools.egg-info/dependency_links.txt
  writing requirements to domdf_python_tools.egg-info/requires.txt
  writing top-level names to domdf_python_tools.egg-info/top_level.txt
  reading manifest file 'domdf_python_tools.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching '**/__pycache__'
  adding license file 'LICENSE'
  writing manifest file 'domdf_python_tools.egg-info/SOURCES.txt'
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Running command /tmp/venv/bin/python3 /tmp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpenyjg9hk
  running dist_info
  creating /tmp/pip-modern-metadata-2tke0rjw/domdf_python_tools.egg-info
  writing /tmp/pip-modern-metadata-2tke0rjw/domdf_python_tools.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-2tke0rjw/domdf_python_tools.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-modern-metadata-2tke0rjw/domdf_python_tools.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-2tke0rjw/domdf_python_tools.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-2tke0rjw/domdf_python_tools.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-2tke0rjw/domdf_python_tools.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching '**/__pycache__'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-modern-metadata-2tke0rjw/domdf_python_tools.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-2tke0rjw/domdf_python_tools.dist-info'
  adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: domdf-python-tools
  Building wheel for domdf-python-tools (pyproject.toml): started
  Running command /tmp/venv/bin/python3 /tmp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp_1m0sf3w
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/domdf_python_tools
  copying domdf_python_tools/bases.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/paths.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/secrets.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/dates.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/delegators.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/import_tools.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/versions.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/iterative.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/utils.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/__init__.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/terminal.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/typing.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/words.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/doctools.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/stringlist.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/_is_match.py -> build/lib/domdf_python_tools
  copying domdf_python_tools/pretty_print.py -> build/lib/domdf_python_tools
  creating build/lib/domdf_python_tools/pagesizes
  copying domdf_python_tools/pagesizes/sizes.py -> build/lib/domdf_python_tools/pagesizes
  copying domdf_python_tools/pagesizes/utils.py -> build/lib/domdf_python_tools/pagesizes
  copying domdf_python_tools/pagesizes/classes.py -> build/lib/domdf_python_tools/pagesizes
  copying domdf_python_tools/pagesizes/__init__.py -> build/lib/domdf_python_tools/pagesizes
  copying domdf_python_tools/pagesizes/units.py -> build/lib/domdf_python_tools/pagesizes
  creating build/lib/domdf_python_tools/compat
  copying domdf_python_tools/compat/importlib_metadata.py -> build/lib/domdf_python_tools/compat
  copying domdf_python_tools/compat/__init__.py -> build/lib/domdf_python_tools/compat
  copying domdf_python_tools/compat/importlib_resources.py -> build/lib/domdf_python_tools/compat
  running egg_info
  creating domdf_python_tools.egg-info
  writing domdf_python_tools.egg-info/PKG-INFO
  writing dependency_links to domdf_python_tools.egg-info/dependency_links.txt
  writing requirements to domdf_python_tools.egg-info/requires.txt
  writing top-level names to domdf_python_tools.egg-info/top_level.txt
  writing manifest file 'domdf_python_tools.egg-info/SOURCES.txt'
  reading manifest file 'domdf_python_tools.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching '**/__pycache__'
  adding license file 'LICENSE'
  writing manifest file 'domdf_python_tools.egg-info/SOURCES.txt'
  copying domdf_python_tools/google-10000-english-no-swears.txt -> build/lib/domdf_python_tools
  copying domdf_python_tools/py.typed -> build/lib/domdf_python_tools
  copying domdf_python_tools/compat/importlib_metadata.pyi -> build/lib/domdf_python_tools/compat
  copying domdf_python_tools/compat/importlib_resources.pyi -> build/lib/domdf_python_tools/compat
  Traceback (most recent call last):
    File "/tmp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/tmp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-myy0rzw0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-myy0rzw0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-myy0rzw0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 20, in <module>
      setup(
    File "/tmp/pip-build-env-myy0rzw0/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 159, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-myy0rzw0/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 301, in run
      install = self.reinitialize_command('install',
    File "/tmp/pip-build-env-myy0rzw0/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 214, in reinitialize_command
      cmd = _Command.reinitialize_command(self, command, reinit_subcommands)
    File "/usr/lib/python3.8/distutils/cmd.py", line 305, in reinitialize_command
      return self.distribution.reinitialize_command(command,
    File "/usr/lib/python3.8/distutils/dist.py", line 938, in reinitialize_command
      command = self.get_command_obj(command_name)
    File "/usr/lib/python3.8/distutils/dist.py", line 858, in get_command_obj
      cmd_obj = self.command_obj[command] = klass(self)
    File "/tmp/pip-build-env-myy0rzw0/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 178, in __init__
      _Command.__init__(self, dist)
    File "/usr/lib/python3.8/distutils/cmd.py", line 62, in __init__
      self.initialize_options()
    File "/tmp/pip-build-env-myy0rzw0/overlay/lib/python3.8/site-packages/setuptools/command/install.py", line 34, in initialize_options
      warnings.warn(
  setuptools._deprecation_warning.SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  Building wheel for domdf-python-tools (pyproject.toml): finished with status 'error'
  ERROR: Failed building wheel for domdf-python-tools
Failed to build domdf-python-tools
ERROR: Failed to build one or more wheels
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Agreed this should be suppressed when building wheels.

**Comment by mara004** [comment]
I am still experiencing this warning with setuptools 60.8.2 when using `bdist_wheel`.
(The project in question is [pypdfium2](https://github.com/pypdfium2-team/pypdfium2), just clone the project and call `pip3 install . -v` to reproduce)

**Comment by abravalheri** [comment]
@mara004, this seems to be related to the way `pip` is working internally.

I recon the project needs to adhere to PEP 517 and PEP 518, i.e. a `pyproject.toml` file needs to be present in the root of the project with contents similar to the following:

```toml
# pyproject.toml
[build-system]
requires = ["setuptools>=46.1.0", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"
```

`pypdfium2` in particular seems to depend on the `__legacy__` behaviour, and also explicitly require the `wheel` dependency to run.

**Comment by mara004** [comment]
@abravalheri First of all, thanks for the response.

> (I also recommend updating pip version).

I am already running the latest pip version 22.0.3

>  i.e. a `pyproject.toml` file needs to be present in the root of the project

In what way is `pyproject.toml` related to the said deprecation warning? Why should `setup.cfg` not be sufficient?

> pypdfium2 in particular seems to depend on the `__legacy__` behaviour

What would I have to change so that the project does not rely on legacy behaviour?

**Comment by mara004** [comment]
@abravalheri First of all, thanks for the response.

> (I also recommend updating pip version).

I am already running the latest pip version 22.0.3

>  i.e. a `pyproject.toml` file needs to be present in the root of the project

Adding the above `pyproject.toml` breaks the build with obscure errors. Anyway, I don't quite understand the background - why should `setup.cfg` not be sufficient?

> pypdfium2 in particular seems to depend on the `__legacy__` behaviour

What would I have to change so that the project does not rely on legacy behaviour?

**Comment by abravalheri** [comment]
Hi @mara004,

> Sorry, adding the above pyproject.toml breaks the build with obscure errors. Anyway, I don't quite understand the background - why should setup.cfg not be sufficient?

The thing `pyproject.toml` would do is to change the way `pip` is building the project.
It seems to me that `pip` tries to run `python setup.py` when it does not find `pyproject.toml`.
When `pyproject.toml` exists, it will run the functions in `setuptools.build_meta` instead.

Recently, `setuptools` reserved to itself the capacity of executing `setup.py` files directly ("demoted" it to an internal API), for the reasons explained in this [article](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html). So the warning is a heads up to developers saying that things might change in the future.

> What would I have to change so that the project does not rely on legacy behaviour?

The main difference between the legacy and the standard backend is that `__legacy__` automatically adds the directory that contains the `setup.py` script to `sys.path`. The standard backend does not do that.

**Comment by mara004** [comment]
Thanks for the help, this is really appreciated.
I'll have to look into `pyproject.toml` and the related PEPs more thoroughly to see if I can change my setup infrastructure. This will be quite complex since pypdfium2 has multiple setup files for different platforms, and it's totally built around some peculiarities of `setup.py`. (pypdfium2 uses external binaries, which is at thing that no other Python project I know of does.)

**Comment by abravalheri** [comment]
@mara004, there are 3 things to consider in the case of `pypdfium`.

* The `setup.py` script is importing from the `platform_setup` folder as if it was a package. However, it does not contain a `__init__.py` file.

* The `sdist` does not seem to contain the `platform_setup` folder.
  * The installers are very likely to consider the sdist as an intermediate step to obtain the wheel. So they will create the sdist first and then create the wheel from it, not from the original code.
  * Since the `platform_setup` is not part of the final package, setuptools will not include it by default in the sdist. You need to write your own `MANIFEST.in` or simply use a plugin such as `setuptools-scm`, for example:
 
  ```toml
  # pyproject.toml
  [build-system]
  requires = ["setuptools>=46.1.0", "setuptools-scm", "wheel"]
  build-backend = "setuptools.build_meta:__legacy__"
  ```

* If you don't want to use `__legacy__`, you either have to keep all your code inside `setup.py` or find a way to signal to Python's import system where to find the auxiliary packages.

**Comment by mara004** [comment]
> The sdist does not seem to contain the `platform_setup` folder.

You probably mean only if switching to the `pyproject.toml` build system? When I run `python3 platform_setup/setup_sdist.py sdist`, the `platform_setup` folder is included as expected, without the need for additional configuration.

**Comment by abravalheri** [comment]
Hi @mara004, please find my comments bellow:

> From what I have seen, sdist should automatically take all files in the repository.

When I run:

```bash
rm -rf dist build src/*.egg-info
python setup.py sdist
tar tf dist/pypdfium2-0.12.0.tar.gz
```
I cannot find the `platform_setup` folder inside the distribution.
When moving towards PEP 517, `python setup.py sdist` is what effectively runs, so I believe it will produce an `sdist` without the required files.

> Furthermore, MANIFEST.in is only relevant for packaging wheels

This statement is incorrect, please check https://setuptools.pypa.io/en/latest/deprecated/distutils/sourcedist.html#specifying-the-files-to-distribute (which also states which files are included by default).

---

I understand that your current workflow has been optimised for years to work with the previous behaviour of setuptools. However the packaging ecosystem for Python has been changing for a while now. There are new standards in place and the setuptools wants to rely on these standards to allow us to remove complexity and be able to focus in other aspects of the implementation. This is one of the reasons why running `setup.py` has been deprecated.

If you want to keep the way things are current implemented, that is fine too! Both setuptools and pip have a lot of stuff implemented to support legacy packages. But you will have to be aware and workaround the limitations that are implied by that approach.

One of them is seeing the warning. You can still get around that by defining a filter via `PYTHONWARNINGS`.

On the other hand, if you want to give it a try to PEP 517, it might be worthy to start with the `__legacy__` first to see how it goes. I also recommend looking how other projects (such as https://github.com/pybind/pybind11) deal with pre-built binaries and multiple `setup_*` files while still being able to rely on PEP 517.

You can always [wrap an existing PEP 517 backends](https://www.python.org/dev/peps/pep-0517/#in-tree-build-backends) to [tweak more deeply how they work for your package](https://setuptools.pypa.io/en/latest/build_meta.html#dynamic-build-dependencies-and-other-build-meta-tweaks).

**Comment by mara004** [comment]
> When I run:
> ```
> rm -rf dist build src/*.egg-info
> python setup.py sdist
> tar tf dist/pypdfium2-0.12.0.tar.gz
> ```
> I cannot find the platform_setup folder inside the distribution.

That is confusing. I cannot reproduce the behaviour you are experiencing, at least not with the latest state of the repository. When running your sequence of commands, I get a tarball including all directories and files that are not excluded in `.gitignore` (sample: [pypdfium2-0.13.1.tar.gz](https://github.com/pypa/setuptools/files/8074012/pypdfium2-0.13.1.tar.gz)).
However, as mentioned previously, `setup.py` is not intended for `sdist`, as it will copy platform-specific binary and bindings files into the `src/pypdfium2/` directory. You need to use `platform_setup/setup_source.py sdist` instead.

I'll investigarte the other mentioned points and reply later.

**Comment by mara004** [comment]
> If you want to keep the way things are current implemented, that is fine too! 

It is not, because it means the code will eventually stop working, should the setuptools comman-line really be removed some day.

> One of them is seeing the warning. You can still get around that by defining a filter via PYTHONWARNINGS.

The warning is there for a reason. Filtering it won't help anyone.

**Comment by mara004** [comment]
> There are new standards in place and the setuptools wants to rely on these standards to allow us to remove complexity and be able to focus in other aspects of the implementation. 

Sure, but the current approach of PEP 517 has serious limitations that cause a lot of problems for downstream packagers.
The rationale is very vague and theoretical; not sufficiently backed by practical use cases.

**Comment by abravalheri** [comment]
One pratical use case is the future removal of easy_install.

**Comment by mara004** [comment]
>  I also recommend looking how other projects (such as https://github.com/pybind/pybind11) deal with pre-built binaries and multiple setup_* files while still being able to rely on PEP 517.

What pybind does looks interesting, but from what I can see it's not about dealing with pre-built binaries.
In addition to its main `setup.py`, pybind has `setup_global.py.in` and `setup_main.py.in`, but I don't quite understand under which circumstances these take effect and how they play together with the main `setup.py`.

**Comment by mara004** [comment]
> There are new standards in place and the setuptools wants to rely on these standards to allow us to remove complexity and be able to focus in other aspects of the implementation. This is one of the reasons why running setup.py has been deprecated.

The problem is that this reduction in complexity of the setuptools codebase greatly increases the difficulty for downstream packagers. With the old `setup.py` approach, there was a lot of flexibility, and yet the interface could be kept relatively high-level so I only needed a small, easy to overview amount of code.
As PEP 517 essentially renders the high-level API unusable for cross-packaging, I will either have to resort to crude workarounds to be able to use the new tooling anyway, or I will have to use a low-level interface like [`Pep517HookCaller`](https://github.com/pypa/pep517) instead and write a lot of custom setup code.

**Comment by abravalheri** [comment]
Hi @mara004, locally I was able to use [`python -m build`](https://pypa-build.readthedocs.io/en/stable/) to create both a `.tar.gz` and `.whl` files for pypdfium2, by implementing the changes I discussed in https://github.com/pypa/setuptools/issues/2847#issuecomment-1038404625. Off course this does not imply that those artifacts are correct (I am a user of the project, not I have knowledge about its code base and tests), in fact they can be completely wrong and just because I managed to get `python -m build` to work, it does not mean it did the right thing...

Maybe it might be interesting for you to give it a try and see if the tests run correctly with artifacts built from `python -m build`?

Regarding the pitfalls of PEP 517, I recommend bringing any discussions about its pitfalls and improvement proposals to https://discuss.python.org/c/packaging/14.

**Comment by mara004** [comment]
That's very interesting, thanks for trying this! Could you please submit a PR so I can take a look?

The test suite should be fairly easy to use: Just install the artifact that corresponds to your platform and run `python3 -m pytest tests/`. You can also inspect the artifacts with an archiver tool and see if the `pypdfium2/` directory contains the files `_pypdfium.py` and one-of `pdfium` / `pdfium.dll` / `pdfium.dylib`.

**Comment by mara004** [comment]
Okay, I see. This means your changes do not solve the problem - I already tried your suggestions from https://github.com/pypa/setuptools/issues/2847#issuecomment-1038404625.
As outlined previously, I need to run the various setup files in `platform_setup` to create the 8 platform-specific wheels I upload to PyPI, but you created only a single wheel using `setup.py`, right?

> How does `pip install . -v` chooses the platform-specific setup files?

Well, this is the procedure that `setup.py` does:
* Ensures all dependencies are installed
* Determines the host platform using `sysconfig.get_platform()`
* Downloads the corresponding tarball from `pdfium-binaries` containing binaries and headers
* Generates bindings for the headers using `ctypesgen`
* Calls the shared setup function `mkwheel_install()` from `setup_base` with the platform data directory as argument.

However, the main point is that `setup.py` is only used for installation from git or for sourcebuild fallback. To PyPI, I upload platform wheels generated using the custom setup files, so `setup.py` is not running for end users who install a wheel.

> I guess `build` just followed the same process...

Yeah, but that misses the actual problem. Running the main `setup.py` using `python3 -m build` will work, that's out of question. The issue is that I need `build` to use the custom setup files to craft the release wheels in `utilities/setup_all.sh`:
```bash
python3 platform_setup/setup_sdist.py sdist
python3 platform_setup/setup_darwin_x64.py    bdist_wheel
python3 platform_setup/setup_darwin_arm64.py  bdist_wheel
python3 platform_setup/setup_linux_x64.py     bdist_wheel
python3 platform_setup/setup_linux_arm64.py   bdist_wheel
python3 platform_setup/setup_linux_arm32.py   bdist_wheel
python3 platform_setup/setup_windows_x64.py   bdist_wheel
python3 platform_setup/setup_windows_x86.py   bdist_wheel
python3 platform_setup/setup_windows_arm64.py bdist_wheel
```

**Comment by abravalheri** [comment]
> Yeah, but that misses the actual problem. Running the main `setup.py` using `python3 -m build` will work, that's out of question. The issue is that I need `build` to use the custom setup files to craft the release wheels in `utilities/setup_all.sh`:

This reminds me the way `pybind11` uses an environment variable to select which setup file to use. Maybe you could try that?

**Comment by mara004** [comment]
> This reminds me the way pybind11 uses an environment variable to select which setup file to use. Maybe you could try that?

How does that work?

**Comment by abravalheri** [comment]
Build will not do that *automatically* for you.
The guys in `pybind11` came up with this [strategy](https://github.com/pybind/pybind11/blob/009ffc336299f58dcb439fae278eb135150b71c1/setup.py#L50) of using the main `setup.py` to select another file to run. It is quite ingenious.

They are `exec-ing` the secondary files, because they are creating them dynamically from templates, but in your case, since the files are static, you could simply use `importlib.import_module` and find the right function to run.

**Comment by mara004** [comment]
FYI, I started working on PEP517-compliance in a branch: https://github.com/pypdfium2-team/pypdfium2/pull/68/files
The environment variables were a really nice idea.

**Comment by mara004** [comment]
Ah, yes. Sorry, I overlooked you already mentioned this. I will see what I can do with `importlib` or `sys.path`.
You're right that adding the CWD sys.path is not a nice solution, for it would include all the other files and subdirectories.
