### ISSUE TITLE
[BUG] Python3.5 compatibility problem

### ISSUE THREAD

**Issue by XDeviation** [pypa/setuptools#2852]
### setuptools version

setuptools===58.5.2

### Python version

Python 3.5

### OS

Ubuntu 16.04

### Description

I tried to import this package and got a syntax error, I think this error comes from commit 84b1cd8e7760a9b3c984a4edfc37dc7266952266 , here is the syntax f"{}" above Python 3.6 is introduced
code: pkg_resources/__init__.py:117 
f"{v} is an invalid version and will not be supported in "

### Expected behavior

I tried to import this package and import successfully

### How to Reproduce

Import setuptools===58.5.2 with python3.5 or lower version

### Output

```console
"./parse_logs.par/subpar/runtime/support.py", line 157, in _setup_pkg_resources
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 117
    f"{v} is an invalid version and will not be supported in "
                                                             ^
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by benoit-pierre** [comment]
Support for Python 3.5 was dropped in [51.0.0](https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v5100).

**Comment by benoit-pierre** [comment]
The discussion in #2541 might be relevant if you're wondering how you ended up with an incompatible version.
