### ISSUE TITLE
Deprecate use of ez_setup.py in user packages

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#286]
Originally reported by: **jaraco (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

In the early days of setuptools, when adoption was small, it made sense for package managers to give users an easy way to include setuptools in the installation, so that the packages themselves could depend on setuptools being present for the features supplied by setuptools.

Today, installation of setuptools is largely a given and can be considered an implicit requirement.

I'd like to officially deprecate the recommendation for packages to include ez_setup.py in their packages.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/286

**Comment by pganssle** [comment]
I see only two references to this in the documentation, [this one](https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=ez_setup#using-setuptools-without-bundling-it), which is deprecated in the documentation and [this one](https://setuptools.readthedocs.io/en/latest/easy_install.html#executables-and-launchers), which is under "Easy Install", and that whole **page** is listed as deprecated.

I'm going to close this, but @jaraco feel free to re-open it if you feel more action needs to be taken.
