### ISSUE TITLE
Release blocked by non-published test dependency pytest-virtualenv

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#2881]
I think there might be a problem with using:

```diff
[options.extras_require]
testing =
        ...
-	pytest-virtualenv>=1.2.7
+	pytest-virtualenv @ git+https://github.com/jaraco/pytest-plugins@distutils-deprecated#subdirectory=pytest-virtualenv
```

in `setup.cfg`.

I am almost sure PyPI forbid uploading packages with dependencies outside of PyPI.
`pypa/build` may also have problems when parsing the dependencies for PEP517 style builds...

_Originally posted by @abravalheri in https://github.com/pypa/setuptools/issues/2865#issuecomment-968325917_

**Comment by jaraco** [comment]
Confirmed. Good catch. I can see in https://github.com/pypa/setuptools/runs/4196605393?check_suite_focus=true this output:

> Error during upload. Retry with the --verbose option for more details.
> HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
> Invalid value for requires_dist. Error: Can't have direct dependency: "pytest-virtualenv @ git+https://github.com/jaraco/pytest-plugins@distutils-deprecated#subdirectory=pytest-virtualenv ; extra == 'testing'"

So the v59 release was rejected.

I'm not sure what to do with this other than to fork the project or port its functionality to another project.

I've noticed that this project (Setuptools) already is using jaraco.envs for some of the tests requiring isolated environments for testing. Perhaps the best thing would be to migrate the tests to jaraco.envs.

**Comment by abravalheri** [comment]
Hi @jaraco, I think the solution is to overwrite the test dependency via `tox.ini`. I am working in a PR that does that, right now.

Hopefully it will work

**Comment by jaraco** [comment]
Aha. I see this is now a dupe of #2880.

**Comment by abravalheri** [comment]
> I've noticed that this project (Setuptools) already is using jaraco.envs for some of the tests requiring isolated environments for testing. Perhaps the best thing would be to migrate the tests to jaraco.envs.

I think that would be a positive change. I usually avoid pytest-virtualenv because it is not straight forward to use sometimes...
