### ISSUE TITLE
[Docs] GitHub reference in changelog rendered as email

### ISSUE THREAD

**Issue by aphedges** [pypa/setuptools#2884]
### Summary

In [the changelog for v59.0.0](https://setuptools.pypa.io/en/latest/history.html#v59-0-0), a `distutils` commit is referenced using `pypa/distutils@f1b0a2b` in the RST source. Although it should link to pypa/distutils@f1b0a2b (`https://github.com/pypa/distutils/commit/f1b0a2b`) as GitHub automatically does, it instead renders the URL as `mailto:pypa/distutils@f1b0a2b`, which is incorrect.

### OS / Environment

N/a. This is in the source code.

### Additional Information

I would solve this myself, but I don't know the best solution. I can see that some things like GitHub issues are automatically linked, but I'm not sure if it should be added to the linking code in [`docs/conf.py`](https://github.com/pypa/setuptools/blob/4b980ef4072a817aae0da3643d0fa70c30fcb6cf/docs/conf.py) or just manually made a link.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Thanks for the report.

I'm not sure either. I'd first check to see if there's any prior art for linking to a revision in distutils. If not, the linker definitions in conf.py might work, so that's worth exploring. Those use `rst.linker`, which isn't particularly easy to understand.
