### ISSUE TITLE
[BUG] Setuptools makes a bad editable install when it's missing a configuration

### ISSUE THREAD

**Issue by NeilGirdhar** [pypa/setuptools#2886]
### setuptools version

59.0.1

### Python version

3.9

### OS

Linux

### Description

See https://github.com/pypa/pip/issues/10659 for a repro and explanation.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
This is a duplicate of #2329.
