### ISSUE TITLE
Broken links to EasyInstall docs on overview page

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#289]
Originally reported by: **Piotr_Dobrogost (Bitbucket: [Piotr_Dobrogost](http://bitbucket.org/Piotr_Dobrogost), GitHub: Unknown)**

---

On overview page in section "Unix (wget)" (https://pypi.python.org/pypi/setuptools#unix-wget) there are links to "EasyInstall manual" (https://pythonhosted.org/setuptools/EasyInstall) and " the section on custom installation locations." (https://pythonhosted.org/setuptools/EasyInstall#custom-installation-locations). Both are broken (I get 404 Not Found).

I guess proper link is https://pythonhosted.org/setuptools/easy_install.html which is used later on the same page ("The EasyInstall user's guide and reference manual").

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/289

**Comment by benoit-pierre** [comment]
No longer applicable.
