### ISSUE TITLE
Running "test" followed by "install" on a with_2to3 package causes duplicate egg-info to be installed

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#292]
Originally reported by: **marienz (Bitbucket: [marienz](http://bitbucket.org/marienz), GitHub: [marienz](http://github.com/marienz))**

---

Tested using setuptools-7.0 and current hg (48a23a037ea2), and urwid-1.2.2 as package to be installed. The problem probably occurs on any package using `setup.py test` provided by setuptools and `use_2to3=True`.

First run `python3.3 setup.py test`. Then run `python3.3 setup.py install --root=/tmp/urwid` (other install invocations probably also affected). This installs:

```
/tmp/urwid/usr/lib64/python3.3/site-packages/urwid-1.2.2-py3.3.egg-info
/tmp/urwid/usr/lib64/python3.3/site-packages/urwid.egg-info
```

That urwid.egg-info directory is unexpected. This is a problem because it triggers the following:

```
#!python
>>> pkg_resources.require('bdist_mpkg>=0.4.2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/setuptools/pkg_resources.py", line 741, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/tmp/setuptools/pkg_resources.py", line 611, in resolve
    env = Environment(self.entries)
  File "/tmp/setuptools/pkg_resources.py", line 798, in __init__
    self.scan(search_path)
  File "/tmp/setuptools/pkg_resources.py", line 828, in scan
    self.add(dist)
  File "/tmp/setuptools/pkg_resources.py", line 848, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
TypeError: unorderable types: str() < NoneType()
```

and that happens because it's comparing two `pkg_resources.Distribution` instances where one has a `py_version` while on the other it's `None`. This may need its own bug report, let me know if you want me to file that.

As for where that stray egg-info comes from: if 2to3 is used, the "test" command does this:

```
#!python
            # Build extensions
            self.reinitialize_command('egg_info', egg_base=build_path)
            self.run_command('egg_info')
```

which creates build/lib.linux-x86_64-3.3/urwid.egg-info. This egg-info directory then gets copied across by install_lib, in addition to the one created by install_egg_info. Unfortunately I have no idea what the correct fix for that is (use a directory other than build_lib? try to clean it up afterwards?).

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/292

**Comment by jaraco** [comment]
use_2to3 has been removed in v58
