### ISSUE TITLE
Make it possible for pip to take control over setup_requires

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#293]
Originally reported by: **dstufft (Bitbucket: [dstufft](http://bitbucket.org/dstufft), GitHub: [dstufft](http://github.com/dstufft))**

---

Right now when you do `pip install some-package` pip handles all of the network operations and selecting which versions of things to actually use _except_ for things that are specified in `setup_requires`. This causes a bunch of confusion because in order to configure things you have to configure them for both setuptools and for pip (like configuring a special index to use instead of PyPI). This ranges from annoyance (needing to specify in two files) to impossible (I don't believe setuptools makes it possible to change the CAbundle that is in use?).

To this end it would be great if setuptools provided some mechanism for pip to take control over installing the items in `setup_requires`. I have a few potentional ideas each with their own drawbacks.
1. Make the function which is used to resolve/install these dependencies and entrypoint which would make it possible for pip to take control over this.
   - Pro: Would degrade nicely to older versions of setuptools where setuptools would just ignore it.
   - Con: This is "installation-global", which means we more or less reverse the problem where instead of `setup_requires` being confusing on pip it's now confusing on `easy_install`.
2. Make a command line flag to all `setup.py` commands which allows passing an import path to a function that setuptools can use to resolve dependencies.
   - Pro: Makes it so that it's per invocation of setuptools so we can be assured that each invocation uses pip but that it doesn't affect other invocations.
     - Con: Since it uses a flag it'll fail on older versions of setuptools and there isn't a good way to "feature detect".
3. Make a separate command that will write out the `setup_requires` to it's own file so that pip can parse this file and ensure the items are available to the `setup.py` invocations.
   - Pro: Easier to feature detect than a flag.
   - Pro: Isn't an "installation global" so it doesn't affect other cases.
   - Con: Bugs in pip will be masked by the fact if we don't correctly setup the `setup_requires` prior to invoking the other commands setuptools will still reach out and do it's own downloads.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/293

**Comment by pganssle** [comment]
@dstufft Is this still a going concern, or has it been obviated by PEP 518?

**Comment by dstufft** [comment]
I'd say that PEP 518 is the implementation of this idea.

**Comment by pganssle** [comment]
Sounds great. Closing. Thanks!
