### ISSUE TITLE
[BUG] 60.1.0: Installing mpi4py fails with latest setuptools

### ISSUE THREAD

**Issue by EnricoMi** [pypa/setuptools#2969]
### setuptools version

60.1.0

### Python version

3.8

### OS

Linux (Ubuntu)

### Description

Installing mpi4py started to fail with the release of `setuptools==60.1.0`. It works with `setuptools==60.0.4`. Is `60.1.0` expected to be a breaking release version?

```
$ pip install -v mpi4py
Using pip 21.3.1 from .../venv-mpi4py/lib/python3.8/site-packages/pip (python 3.8)
Collecting mpi4py
  Using cached mpi4py-3.1.3.tar.gz (2.5 MB)
  Running command .../venv-mpi4py/bin/python /tmp/pip-standalone-pip-fmkquq0f/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-nun8azx9/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.9.0' wheel
  Collecting setuptools>=40.9.0
    Using cached setuptools-60.1.0-py3-none-any.whl (952 kB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Installing collected packages: wheel, setuptools
  Successfully installed setuptools-60.1.0 wheel-0.37.1
  Installing build dependencies ... done
  Running command .../venv-mpi4py/bin/python .../venv-mpi4py/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmputajppc5
  Traceback (most recent call last):
    File ".../venv-mpi4py/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File ".../venv-mpi4py/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File ".../venv-mpi4py/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-nun8azx9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-nun8azx9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-nun8azx9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 462, in <module>
      from mpidistutils import setup
    File "/tmp/pip-install-k7kbt967/mpi4py_fa187d0418384267943227507227365d/conf/mpidistutils.py", line 29, in <module>
      cygcc_get_versions = cygcc.get_versions
  AttributeError: module 'setuptools._distutils.cygwinccompiler' has no attribute 'get_versions'
  Getting requirements to build wheel ... error
```

Something must have changed in `setuptools` that broke [mpi4py/conf/mpidistutils.py](https://github.com/mpi4py/mpi4py/blob/master/conf/mpidistutils.py).

### Expected behavior

Installing the package `mpi4py` should work as with `setuptools` 60.0.x, given this is a minor version increment.

### How to Reproduce

pip install --upgrade pip setuptools
pip install mpi4py

### Output

```console
  AttributeError: module 'setuptools._distutils.cygwinccompiler' has no attribute 'get_versions'
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by spacexnasa** [comment]
macos 12.1 intel
python 3.10
pip3 list --outdated
Package    Version Latest Type
---------- ------- ------ -----
setuptools 59.5.0  60.1.0 wheel
if i update to 60.1.0, relogin terminal,display this error messate

Error processing line 1 of /usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'ensure_shim'

Remainder of file ignored

**Comment by jaraco** [comment]
> Is 60.1.0 expected to be a breaking release version?

No. The [changelog shows two changes](https://setuptools.pypa.io/en/latest/history.html#v60-1-0).

It looks like pypa/distutils#77 is the likely culprit for the AttributeError as that removed `get_versions`.

@naveen521kk It looks like there are users relying on `cygwincompiler.get_versions` and we probably need to restore it. Can you work on that?

**Comment by jaraco** [comment]
@spacexnasa Your error message seems unrelated, so I'm going to mark it as off-topic. If you have an issue, please report it separately.

**Comment by dalcinl** [comment]
@jaraco I'm the author of mpi4py. The only reason mpi4py had to use that API was to workaround an issue where distutils would fail if the path of the compiler command (`C:\<path>\gcc.exe`) contains spaces. [Look yourself to the current code (after a fix for this issue)](https://github.com/mpi4py/mpi4py/blob/master/conf/mpidistutils.py#L33). I'm not actually using `get_versions` for anything, but just monkeypatching it to prevent misbehaviors elsewhere related to the handling of filenames with spaces.

This code worked flawlessly for 15 years, but it broke after the removal of `get_versions()`. While I could make a new release with the hotfix for this setuptools change, users would not be able to install any of the previous mpi4py versions.

**Comment by naveen521kk** [comment]
> @naveen521kk It looks like there are users relying on cygwincompiler.get_versions and we probably need to restore it. Can you work on that?

Yeah sure. I will work on that later this week. I am planning to just add the `get_versions()` function in there but instead simply returning a couple of hardcoded values instead of actual values and also raising a `DeprecationWarning` when called. That should work, right? 

> This code worked flawlessly for 15 years, but it broke after the removal of get_versions().

Sorry!

**Comment by jaraco** [comment]
It sounds like the use-case for mpi4py is simply to monkeypatch, so I'd not bother restoring the implementation. I'd just create an attribute with a comment:

```python
get_versions = None
"""
A stand-in for the previous get_versions() function to prevent failures
when monkeypatched. See pypa/setuptools#2969.
"""
```

**Comment by dalcinl** [comment]
@jaraco @naveen521kk Will the new distutils code work fine if the MinGW compiler suite is installed in a directory with spaces in its name? These days mpi4py is not relying on MinGW for building its extension modules, but that could change in the future.

**Comment by jaraco** [comment]
> @jaraco @naveen521kk Will the new distutils code work fine if the MinGW compiler suite is installed in a directory with spaces in its name? These days mpi4py is not relying on MinGW for building its extension modules, but that could change in the future.

Reviewing the patch in pypa/distutils#77, I'm pretty sure the only change was for checking gcc versions. The rest should be the same, so Yes, I would expect things to continue to work as they work now. If you find that's not the case, please file a bug with pypa/distutils and we can work out a proper fix.

**Comment by jaraco** [comment]
I'm going to go ahead and apply the patch I proposed above.
