### ISSUE TITLE
Importing setuptools.dist executes a subprocess (8.0.x)

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#297]
Originally reported by: **tonyandrewmeyer (Bitbucket: [tonyandrewmeyer](http://bitbucket.org/tonyandrewmeyer), GitHub: [tonyandrewmeyer](http://github.com/tonyandrewmeyer))**

---

I'm not sure if you'll consider this a bug or not (your call, of course).

In 8.0 and 8.0.1 (and I assume 8.0.2, although I haven't checked) importing setuptools.dist imports setuptools.windows_support.  windows_support has a method hide_file, which is wrapped by a decorator windows_only, which calls platform.system().  platform.system() (at least in 2.7.8) calls platform.uname(), which (on some platforms) uses _syscmd_uname to get the processor information, which calls os.popen (for uname).

So what this means is that just importing setuptools.dist will result in a subprocess running uname (on various platforms, including Debian 7).

Philosophically, I don't really like an import executing a subprocess.  However, this caused issues for me, because I have processes that do not have permission to create child processes.  So this means that importing setuptools.dist results in an IOError ([Errno 10] No child processes).

It would be great if the pre 8.0 behaviour was restored where this didn't happen.  For example, the hide_file method could determine if it was running on Windows when called rather than when imported.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/297

**Comment by benoit-pierre** [comment]
No longer applicable, as `os.uname` should use [uname](http://man7.org/linux/man-pages/man2/uname.2.html) if available.
