### ISSUE TITLE
[BUG] SetuptoolsDeprecationWarning with poetry export

### ISSUE THREAD

**Issue by BKSteve** [pypa/setuptools#2985]
### setuptools version

setuptools >= 60.0.0

### Python version

Python 3.8.12

### OS

Synology Linux DSM 6.2.4-25556

### Additional environment information

Linux RStation 3.10.105 #25556 SMP Sat Aug 28 02:15:10 CST 2021 x86_64 GNU/Linux synology_cedarview_412+
SynoCommunity Python 3.8.12-6 and SickChill 20211110-4

Also confirmed to occur on 
OS: Linux on Raspberry Pi (Linux raspberrypi 5.10.63-v8+ \# 1488 SMP PREEMPT Thu Nov 18 16:16:16 GMT 2021 aarch64 GNU/Linux)

### Description

When restarting SickChill the code executes the poetry line followed by a pip install of each package.
`/volume1/@appstore/sickchill/env/bin/python -m poetry export -f requirements.txt --without-hashes`
which collects all the requirements and then it does a `pip` install of each package in sequence.

I tested each version of setuptools and with setuptools >= 60.0.0 the error is given.
```
/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
   warnings.warn(
```
This is the full execution with the error with the bash line initiation command.
```
/volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data
Found wheelhouse dir at /volume1/@appstore/sickchill/share/wheelhouse
pip args: /volume1/@appstore/sickchill/env/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU -f/volume1/@appstore/sickchill/share/wheelhouse importlib-metadata==4.8.2; python_version < "3.8" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.6") packaging==21.2; python_version >= "3.6" typing-extensions==3.10.0.2; python_version < "3.8" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.6") /volume1/@appstore/sickchill/env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.   warnings.warn(
Command result: ERROR: Invalid requirement: '/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.'
Hint: It looks like a path. File '/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.' does not exist.

Trying user site-packages
Command result: ERROR: Invalid requirement: '/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.'
Hint: It looks like a path. File '/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.' does not exist.
```

If execute `/volume1/@appstore/sickchill/env/bin/python -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools==xx.x.x` I can change the installed version of setuptools and then execute the `/volume1/@appstore/sickchill/env/bin/python -m poetry export -f requirements.txt --without-hashes`
that way I could test the many versions to see which gave the error and found setuptools < 60.0.0. such as 59.8.0 do not generate the two lines 
```
/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
   warnings.warn(
```
with the poetry call and are thus not in the string sent to pip.

### Expected behavior

No error lines generated with the `poetry` line of code.

### How to Reproduce

setuptools is loaded as one of SickChill packages.
1. fresh install SickChill
2. execute SickChill
3. error generated and stops package install `poetry`, `wheel`, and `setuptools`
4. when the code calls `python -m poetry export -f requirements.txt --without-hashes` the errors are generated and passed to pip for install and thus pip fails due to the error lines created. 

### Output

```
/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
   warnings.warn(
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Here are the [differences between Setuptools 59.8.0 and 60.0.0](https://github.com/pypa/setuptools/compare/v59.8.0...v60.0.0). The only change was to introduce SETUPTOOLS_USE_DISTUTILS=local as the default. What happens if you run with `SETUPTOOLS_USE_DISTUTILS=stdlib` instead?

I'm surprised the warning isn't issued with v59.8.0, as you can also observe that nothing around that warning changed between those versions.

I don't understand the internals of SickChill or poetry well enough to understand what expectation from Setuptools is being missed here. Someone with more expertise in those projects needs to investigate deeper and characterize the issue as it applies to Setuptools.

**Comment by BKSteve** [comment]
I am also at the bottom of the learning curve and don't understand the internals of poetry and there's lots of other threads with issues around setuptools 60.0.0+ so will wait a while and add some logging lines into the other packages to see if I can narrow down when and where the error is thrown.
I don't know where to put the `SETUPTOOLS_USE_DISTUTILS=stdlib` theres no real line which calls `setuptools` and just get a 'too many args' error if on the poetry export line.

As far as SickChill goes, it's just a user to update packages, doesn't have a setup.py and I've got a couple of re.sub lines for a dirty fix to filter the warning and error lines out of the poetry export string before passing to pip.
So still functional but intrigued, hooking in @miigotu who maintains SickChill.

**Comment by miigotu** [comment]
I need to make a warning period where people will have to start managing their own environment for SC and SC will not make the virtual env or update it itself. Maybe I will warn users when the environment is outdated.

Potentially it is by calling poetry that way which causes the error, rather than calling just "poetry ..."

**Comment by miigotu** [comment]
And you would put `SETUPTOOLS_USE_DISTUTILS=stdlib python -m poetry ... ` as it isn't an argument, it's and environment variable I think.

**Comment by BKSteve** [comment]
> And you would put `SETUPTOOLS_USE_DISTUTILS=stdlib python -m poetry ... ` as it isn't an argument, it's and environment variable I think.

OK, that fixes the error. 
`SETUPTOOLS_USE_DISTUTILS=stdlib /volume1/@appstore/sickchill/env/bin/python -m poetry export -f requirements.txt --without-hashes` gives a result without error.

**Comment by BKSteve** [comment]
[https://github.com/SickChill/SickChill/pull/7772](https://github.com/SickChill/SickChill/pull/7772)
