### ISSUE TITLE
[BUG] setuptools 60.3.0 breaks pip on Ubuntu 20.04.3

### ISSUE THREAD

**Issue by Patol75** [pypa/setuptools#3003]
### setuptools version

setuptools==60.3.0

### Python version

Python 3.9

### OS

Ubuntu 20.04.3 LTS

### Description

Updating `setuptools` from 60.2.0 to 60.3.0 yields the following error message after executing any `python3.9 -m pip` command:
`/usr/bin/python3.9: Error while finding module specification for 'pip' (AttributeError: module '__main__' has no attribute '__file__')`

### Expected behavior

Updating setuptools should not break pip.

### How to Reproduce

Simply update setuptools to the last release and attempt to use pip.

### Output

```console
python3.9 -m pip install --user --upgrade setuptools
/usr/bin/python3.9: Error while finding module specification for 'pip' (AttributeError: module '__main__' has no attribute '__file__')
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by matthewfeickert** [comment]
:wave: This is a duplicate of Issue #3002, so please follow along there for new information and consider closing this Issue to avoid confusion. :+1:

**Comment by Patol75** [comment]
Unfortunate timing on my side it seems, #3002 was not opened when I started writing this issue. Anyway, good to know I am not the only one and developers are aware of the issue. :)
