### ISSUE TITLE
[BUG] Setuptools is including test files in its own wheel

### ISSUE THREAD

**Issue by abravalheri** [pypa/setuptools#3017]
### setuptools version

main branch: 464568d

### Python version

Python 3.8

### OS

Ubuntu 20.04.3 LTS

### Description

Setuptools own wheel contain some test files, which is undesirable.
Moreover it indicates that either:
1. `find_namespace_packages` is struggling to handle the exclude patterns, OR
2. the exclude pattern configuration is insufficient
   https://github.com/pypa/setuptools/blob/464568d64469fb1ca9794ef26fe2288f16c15598/setup.cfg#L30-L37
---
**Side Note**

This issue appeared when I was investigating the failures in #3015 for PyPY.
I am speculating the following:
- When tox install setuptools from sdist, the build artifact contains a `setuptools/tests` folder
  - I suspect that works as an implicit namespace.
- When pytest tries to import things there is a path manipulation (or some importlib shenanigans), and suddenly `setuptools/tests` has a `__init__.py` file, which I suspect conflicts with the previous installed implicit namespace 

### Expected behavior

Setuptools should not include test files in the final wheel distribution.
These files should not be installed in the end user environment.

### How to Reproduce

```bash
cd /tmp
git clone --depth=1 https://github.com/pypa/setuptools.git
cd setuptools
virtualenv .venv -p python3.8

.venv/bin/python setup.py egg_info
.venv/bin/python setup.py bdist_wheel
unzip -l dist/setuptools*.whl | grep tests
      104  2022-01-09 00:19   pkg_resources/tests/data/my-test-package-source/setup.py
        0  2022-01-09 00:19   setuptools/tests/integration/__init__.py
     2134  2022-01-09 00:19   setuptools/tests/integration/helpers.py
     7938  2022-01-09 00:19   setuptools/tests/integration/test_pip_install_sdist.py


rm -rf dist build setuptools.egg-info
.venv/bin/python -m pip install build
.venv/bin/python -m build
unzip -l dist/setuptools*.whl | grep tests
      104  2022-01-09 00:19   pkg_resources/tests/data/my-test-package-source/setup.py
        0  2022-01-09 00:19   setuptools/tests/integration/__init__.py
     2134  2022-01-09 00:19   setuptools/tests/integration/helpers.py
     7938  2022-01-09 00:19   setuptools/tests/integration/test_pip_install_sdist.py


cd /tmp
wget https://files.pythonhosted.org/packages/eb/53/0dd4c7960579da8be13fa9b2c2591643d37f323e3d79f8bc8b1b6c8e6217/setuptools-60.5.0-py3-none-any.whl
unzip -l setuptools*.whl | grep tests
      104  2021-12-20 16:48   pkg_resources/tests/data/my-test-package-source/setup.py
        0  2022-01-08 01:39   setuptools/tests/integration/__init__.py
     2134  2022-01-08 01:39   setuptools/tests/integration/helpers.py
     7938  2022-01-08 01:39   setuptools/tests/integration/test_pip_install_sdist.py
```

### Output

Both distributions built locally and the file on PyPI contain the following files:

```console
pkg_resources/tests/data/my-test-package-source/setup.py
setuptools/tests/integration/__init__.py
setuptools/tests/integration/helpers.py
setuptools/tests/integration/test_pip_install_sdist.py
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Currently the code for the package finder has the following comment:

```python
# Keep searching subdirectories, as there may be more packages
# down there, even if the parent was excluded.
```
So I assume that if the `exclude` matches a parent module, its children are not automatically excluded... (this is a bit confusing, but definetely intentional)

Therefore the solution would be adding `*.tests.*` to the exclude patterns.

**Comment by abravalheri** [comment]
@jaraco I am curious now...

What was the factor motivating the decision of not excluding "children" packages whose parents where excluded. Do you have any thoughts about that?

I understand that it brings more flexibility... but it is also more error prone.

Is it something we would like to change? (In terms of implementation, it all boils down to the indentation level of this [code block](https://github.com/pypa/setuptools/blob/464568d64469fb1ca9794ef26fe2288f16c15598/setuptools/__init__.py#L95-L97))

**Comment by webknjaz** [comment]
> * When pytest tries to import things there is a path manipulation (or some importlib shenanigans), and suddenly `setuptools/tests` has a `__init__.py` file, which I suspect conflicts with the previous installed implicit namespace

pytest emulates this through import hooks and rewriting bytecode IIRC
