### ISSUE TITLE
Setuptools 8 strips leading zeros in packaging for date based releases

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#302]
Originally reported by: **mklein0 (Bitbucket: [mklein0](http://bitbucket.org/mklein0), GitHub: [mklein0](http://github.com/mklein0))**

---

I am currently date based release version numbers to manage releases.  After upgrading to setuptools 8, release segments with leading zeros in them are being striped.

The following setup.py example would generate a package name of:

```
dated_release-20140510.003458-cp27-none-macosx_10_9_intel.whl
```

After setuptools 8:

```
dated_release-20140510.3458-cp27-none-macosx_10_9_intel.whl
```

Along with the following warning:

```
/VirtualEnv/stools/lib/python2.7/site-packages/setuptools/dist.py:289: UserWarning: The version specified requires normalization, consider using '20140510.3458' instead of '20140510.003458'.
self.metadata.version,
```

I believe PEP440 allows for date based version identifiers, so this is unexpected.

Code to generate packages:

```
from setuptools import setup, find_packages

setup(
    name='dated_release',
    version='20140510.003458',
    description='Example of a dated release  %Y%m%d.%H%M%S',
    packages=find_packages(),
    )
```

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/302

**Comment by martinm82** [comment]
I know this issue is pretty old but I am totally confused about what PEP440 says and about how date based versions in reality work.

PEP 440 says

> Date based release segments are also permitted. An example of a date based release scheme using the year and month of the release:
And as examples shows this:

```
2012.04
2012.07
2012.10
2013.01
2013.06
```

When using for example `2019.07` as a version I receive a warning saying

```
setuptools/dist.py:472: UserWarning: Normalizing '2019.07' to '2019.7' normalized_version
```

I am using setuptools 41.0.1

**Comment by jaraco** [comment]
[PEP 440](https://www.python.org/dev/peps/pep-0440/)

**Comment by jaraco** [comment]
@dstufft, @ncoghlan How do you feel about updating the date examples in PEP 440 to elide the leading zeros?
