### ISSUE TITLE
[FR] Constrain requirements to extras

### ISSUE THREAD

**Issue by r-bird** [pypa/setuptools#3024]
### What's the problem this feature will solve?

Consider you are using `package-a` and `package-c` in `install_requires` of your `setup.py` and `package-b` in `extras_require` as requirement for your `tests`:
```py
setuptools.setup(
    install_requires=[
        "package-a",
        "package-c"
    ],
    extras_require={
        "tests": ["package-b >= 1.0.0"]
    },
```

`package-b` also requires `package-c`, but in a pinned down version `<=1.2.3` (because of a bug, removed feature, old python version, ...).

Now your project requires the awesome new feature implemented in `package-c >= 1.3.0` so you write:
```py
setuptools.setup(
    install_requires=[
        "package-a",
        "package-c >= 1.3.0"  # <= this line changed
    ],
    extras_require={
        "tests": ["package-b ~=1.0"]
    },
```

So the `METADATA` of your wheel contains these lines:
```
Requires-Dist: package-a
Requires-Dist: package-c (>=1.3.0)
Provides-Extra: tests
Requires-Dist: package-b (~=1.0) ; extra == 'tests'
```
The last line implies `package-c <= 1.2.3` - so you will never be able to install your test requirements. 😔

----

Another way to achieve this could be, that you have already defined a maximum version of `package-c`, e.g. `< 1.3` and `package-b` version `1.9.0` is released with the new lower boundary `package-c ~= 1.3`. This would be less dramatic, because you can (but have to) pin down `package-c` to run your tests.

### Describe the solution you'd like

When a package is added to `extras_require`, it is considered a constraint for the packages defined in `install_requires`. This way both requirement definitions cannot collide.

The same behavior already exists for `requirements.txt`:
```
-c requirements-tests.txt
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @r-bird thank you very much for bringing this topic to discussion.

I am afraid, I don't understand exactly what is the feature you expect from setuptools...
Is the approach you describe related to a change the way the METADATA file is generated? If that is the case, for the given example, what would be your suggestion on how to generate the METADATA file?

(Is there any clear solution for the problem of having colliding requirements? If we consider you are installing a package with `pip install your_package[tests]` the installation would fail anyway right?)
