### ISSUE TITLE
[BUG] PE wrappers missing Address Space Layout Randomization (ASLR) and Data Execution Prevention (DEP)

### ISSUE THREAD

**Issue by scdub** [pypa/setuptools#3029]
### setuptools version

60.5.0

### Python version

Version independent

### OS

Windows x64

### Description

The PE file wrappers (cli-32.exe, cli.exe, gui-32.exe
gui.exe) for [`launcher.c`](https://github.com/pypa/setuptools/blob/main/launcher.c) were built with Visual Studio 2008, and the current [`msvc-build-launcher.cmd`](https://github.com/pypa/setuptools/blob/main/msvc-build-launcher.cmd) build script still targets this compiler release. These old executables (presumably built when Python 2.7 support was required) do not enable ASLR or DEP, increasing their attack surface. 

Locally, I was able to update the compiler to VS2017 and recompile the executables with default settings which enabled DYNAMICBASE and NXCOMPAT without further steps. I can work on a patch, but wanted to check with the setuptools developers what the expected VS toolchain should be, and if there are any other considerations in making a patch for this issue.

### Expected behavior

ASLR and DEP are enabled for the shipped executables.

### How to Reproduce

On a Windows machine with Visual Studio installed:

1. Start a Visual Studio Native Tools Command Prompt session and navigate to setuptools directory in source or built distribution
2. Run `dumpbin /headers gui-64.exe`, and note the `DLL characteristics` under the `OPTIONAL HEADER VALUES` for the files:

```
            8000 DLL characteristics
                   Terminal Server Aware
```

An executable which has been built against a modern toolchain will instead display:
```
            8160 DLL characteristics
                   High Entropy Virtual Addresses
                   Dynamic base
                   NX compatible
                   Terminal Server Aware
```

### Output

```console

```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
I'm happy to update the script wrappers, although they're deprecated. I'd like to move to relying on distlib for script wrappers. There isn't any formal tool chain for building the wrappers. I do insist that I or one of the maintainers do the actual building, so what we need from you is (a) a PR with an update to the build scripts and (b) instructions or a Docker image that can build them.

**Comment by lazka** [comment]
This might be relevant: https://bitbucket.org/vinay.sajip/simple_launcher/issues/9/ci-and-meson-support

**Comment by scdub** [comment]
This has been completed with the work done on https://github.com/pypa/setuptools/pull/3760 and the subsequent executable rebuilds. Thanks!
