### ISSUE TITLE
Trouble with the packaging tutorial (Exit Speed)

### ISSUE THREAD

**Issue by djhedges** [pypa/setuptools#3030]
### OS version

Raspbian GNU/Linux 10 (buster)

### Python version

Python 3.7

### Pip version

pip 21.3.1

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

I'm attempting to package the project I've been working at https://github.com/djhedges/exit_speed.

This commit shows the pyproject.toml and setup.cfg I wrote as well as the directory structure.
https://github.com/djhedges/exit_speed/commit/7e0dd6f39e2ba2187c6c6aae217067b7139268d3#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52

I even created a symlink to mimic the src/package layout from the documentation.  I also tried setting package_dir and options.packages.find to `exit_speed` and `.` with no luck.
```
ls -l src/exit_speed
lrwxrwxrwx 1 pi pi 13 Jan 16 09:59 src/exit_speed -> ../exit_speed
ls -l src/exit_speed/__init__.py 
-rwxr-xr-x 1 pi pi 668 Jan 16 09:53 src/exit_speed/__init__.py
```

pyproject.toml
```
cat pyproject.toml 
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

```

setup.cfg
```
[metadata]
name = exit_speed
description = Race car telemetry with a Raspberry Pi
version = attr:exit_speed.__version__
author = Douglas Hedges
author_email = djhedges+exit-speed@gmail.com
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/djhedges/exit_speed
project_urls =
    Travis CL = https://app.travis-ci.com/github/djhedges/exit_speed
classifiers =
  Programming Language :: Python :: 3,
  Programming Language :: Python :: 3.7,
  License :: OSI Approved :: Apache Software License,
package_dir =
    = src
packages = find:
python_requires = >=3.7

[options.packages.find]
where = src
```

I'm sure I'm overlooking something silly but any help would be appreciated.

### Error message

```text
pi@exitspeed:~/git/exit_speed $ python3 -m build
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools>=42, wheel)
* Getting dependencies for sdist...
running egg_info
writing manifest file 'exit_speed.egg-info/SOURCES.txt'
* Building sdist...
running sdist
running egg_info
writing manifest file 'exit_speed.egg-info/SOURCES.txt'
running check
creating exit_speed-2022.1.16
creating exit_speed-2022.1.16/exit_speed.egg-info
copying LICENSE -> exit_speed-2022.1.16
copying README.md -> exit_speed-2022.1.16
copying pyproject.toml -> exit_speed-2022.1.16
copying setup.cfg -> exit_speed-2022.1.16
copying exit_speed.egg-info/PKG-INFO -> exit_speed-2022.1.16/exit_speed.egg-info
copying exit_speed.egg-info/SOURCES.txt -> exit_speed-2022.1.16/exit_speed.egg-info
copying exit_speed.egg-info/dependency_links.txt -> exit_speed-2022.1.16/exit_speed.egg-info
copying exit_speed.egg-info/top_level.txt -> exit_speed-2022.1.16/exit_speed.egg-info
Creating tar archive
removing 'exit_speed-2022.1.16' (and everything under it)
* Building wheel from sdist
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools>=42, wheel)
* Getting dependencies for wheel...
Traceback (most recent call last):
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/setuptools/config.py", line 419, in _parse_attr
    return getattr(StaticModule(module_name), attr_name)
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/setuptools/config.py", line 27, in __init__
    with open(spec.origin) as strm:
AttributeError: 'NoneType' object has no attribute 'origin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/home/pi/.local/lib/python3.7/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/pi/.local/lib/python3.7/site-packages/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/setuptools/build_meta.py", line 163, in get_requires_for_build_wheel
    config_settings, requirements=['wheel'])
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/setuptools/build_meta.py", line 158, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 1, in <module>
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/setuptools/__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 122, in setup
    dist.parse_config_files()
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/_virtualenv.py", line 21, in parse_config_files
    result = old_parse_config_files(self, *args, **kwargs)
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/setuptools/dist.py", line 805, in parse_config_files
    self, self.command_options, ignore_option_errors=ignore_option_errors
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/setuptools/config.py", line 158, in parse_configuration
    meta.parse()
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/setuptools/config.py", line 498, in parse
    section_parser_method(section_options)
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/setuptools/config.py", line 469, in parse_section
    self[name] = value
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/setuptools/config.py", line 222, in __setitem__
    value = parser(value)
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/setuptools/config.py", line 599, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/tmp/build-env-trakv3e2/lib/python3.7/site-packages/setuptools/config.py", line 422, in _parse_attr
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'exit_speed'

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_wheel
```

**Comment by merwok** [comment]
The repo is linked in the OP

Commenting out the unneeded package_dir and find options should work.  Package next to setup.py is the default scenario!
https://setuptools.pypa.io/en/latest/userguide/quickstart.html#automatic-package-discovery

**Comment by djhedges** [comment]
Feel free to transfer.
https://github.com/djhedges/exit_speed

**Comment by abravalheri** [comment]
If you do
```diff
- package_dir =
-    = exit_speed
[options.packages.find]
- where = exit_speed
+ exclude =
+    etc*
"    docs*
```
Then `python -m build --sdist` will work...
If you do `python -m build --wheel` after that, it should also work...

The weird part is why when you try to do the 2 at the same time, things don't work...

**Comment by abravalheri** [comment]
Ok @djhedges can you confirm that after the changes in `setup.cfg`, if you add a `MANIFEST.in` file with:

```
global-include *.py
global-exclude *.py[cod]
```

things work properly?
(this should not be necessary and `.py` files should be added by default, so I am still investigating).

**Comment by djhedges** [comment]
Yes to last two comments.  

- Making the changes to setup.cfg and running `--sdist` followed by `--wheel` was successful.
- Also adding the `MANIFEST.in` allows me to run `python3 -m build`.

I tried some other combinations and found after a successful build I could remove `MANIFEST.in` and `python3 -m build` succeeds.  I'm guessing theres an artifact of some sort left behind after the successful build.  If run `rm -rf dist/ exit_speed.egg-info/ __pycache__/` it'll fail again.

**Comment by merwok** [comment]
I’m sorry but the suggested MANIFEST.in entries don’t make sense to me, and just hide the issue.

The `packages` entry tells setuptools which files to include in a built distribution (with the same relative path for sdist, in the `lib` directory for wheels), and where to install them (directly from setup.cfg options or indirectly with wheel because they are in the right directory).  Adding them in MANIFEST.in seems to help because that file allows arbitrary files to be included in an sdist, but it’s not solving the real issue that setuptools should detect that there is a package `exit_speed` (with many subpackages and package data files) to be found here in the same directory.

**Comment by djhedges** [comment]
I was able to upload the package with twine and install it on another machine with pip3.
```
$ pip3 install exit_speed
Collecting exit_speed
  Downloading exit_speed-2022.1.16-py3-none-any.whl (10 kB)
Installing collected packages: exit-speed
Successfully installed exit-speed-2022.1.16
```

But I can load the module
```
python3 -c 'import exit_speed; print(exit_speed.__version__)'
 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'exit_speed'
```

This seems rather small
```
$ ls dist/ -sh
total 68K
12K exit_speed-2022.1.16-py3-none-any.whl  56K exit_speed-2022.1.16.tar.gz
```

**Comment by abravalheri** [comment]
> I’m sorry but the suggested MANIFEST.in entries don’t make sense to me, and just hide the issue.
> 
> The `packages` entry tells setuptools which files to include in a built distribution (with the same relative path for sdist, in the `lib` directory for wheels), and where to install them (directly from setup.cfg options or indirectly with wheel because they are in the right directory).  Adding python files in MANIFEST.in seems to help because that file allows arbitrary files to be included in an sdist, but it’s not solving the real issue that setuptools should detect that there is a package `exit_speed` (with many subpackages and package data files) to be found here in the same directory.

I completely agree with you @merwok. It is just part of the debugging process (which I am still investigating). It seems that at the center of the problem is the fact that setuptools is not able to find the files and adding a MANIFEST.in is a way of forcing that (also, I wanted to give  @djhedges  a quick workaround while we investigate the problem and find a final solution)..

**Comment by abravalheri** [comment]
Please note that if you open a REPL at the root of the project and run `setuptools.find_packages()`, setuptools seems to be able to find the packages correctly.  Given that adding a MANIFEST.in is a dirty workaround, my guess is that there is a problem with setuptools finding which files should be included in the distribution archive.

This theory is also helped by the fact that `python -m build --sdist` runs successfully (including finding out the correct version) but if you inspect the artifact all the files are missing. Since the wheel is built from the sdist, the wheel fails to find the file that is not actually there.

**Comment by abravalheri** [comment]
> But I can't load the module

Sorry to ask you again @djhedges , does this also happens for the MANIFEST.in hack (which should be seen just a temporary workaround to allow you to proceed with your work while we keep investigating the issue, but is by no means the definitive solution)?

**Comment by abravalheri** [comment]
I found the problem 😄 ... It is very difficult to spot but there is a problem in the configuration:

```diff
  License :: OSI Approved :: Apache Software License
- packages = find:
  python_requires = >=3.7

+ [options]
+ packages = find:
```

The packages configuration needs to be included inside the `[options]` section. That was the thing causing trouble. Please note that this is covered by the [Packaging tutorial example](https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata).

@djhedges could you please confirm if that works for you?
With this change the `MANIFEST.in` hack should not be necessary.

**Comment by djhedges** [comment]
Haha, I had a feeling I was doing something silly.   Thanks for your help!  That indeed was the needed fix.
