### ISSUE TITLE
[Docs] Update section about mailing list and bug tracker

### ISSUE THREAD

**Issue by ashemedai** [pypa/setuptools#3034]
### Summary

Reading https://setuptools.pypa.io/en/latest/setuptools.html there's a section at the bottom:

>Mailing List and Bug Tracker
>
>Please use the distutils-sig mailing list for questions and discussion about setuptools, and the setuptools bug tracker ONLY for issues you have confirmed via the list are actual bugs, and which you have reduced to a minimal set of steps to reproduce.

Clicking around shows the mailing list is now defunct. Happy to adjust the documentation, but I have no idea what the process is now? Straight to issues, search, then file if not found?

### Additional Information

N/A

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Thank you very much for spotting that @ashemedai!

I think the [`discussions`](https://github.com/pypa/setuptools/discussions) tab on GitHub are a good place to start, since it is specific to setuptools.

There are other channels, but this seems to be the more focused one in my opinion.

**Comment by ashemedai** [comment]
I can create a PR for the discussions pointer at least. Can integrate other suggestions as needed.
