### ISSUE TITLE
[BUG] Issue with local distutils override, duplicate module entries

### ISSUE THREAD

**Issue by dalcinl** [pypa/setuptools#3035]
### setuptools version

60.5.0

### Python version

3.9.9

### OS

macOS

### Additional environment information

edit(jaraco): ~~I explicitly state that I DO NOT AGREE with being forced to agree with the PSF Code of Conduct to submit this issue. I ticked the box just because I cannot continue otherwise. I hope this requirement for issue submission is an oversight. If not, please close this issue and ignore my report.~~

### Description

There are issues with the local `distutils` override leading to duplicated `distutils.log` module entries in `sys.modules`. As a side effect, the verbose flag (`-v`) to `setup.py` does not work (i.e passing `-v` DOES NOT increase verbosity).

### Expected behavior

1. After `import setuptools`, there should be no entries in `sys.modules` referring to `setuptools._distutils`.
2. Running `python setup.py -vv <command>` should increase verbosity.

### How to Reproduce

Run the following Python code:

```python
import setuptools
import sys
for k in sys.modules.keys():
    if 'distutils.log' in k:
        print(k)
```

### Output

```console
setuptools._distutils.log
distutils.log
```

Obviously, the first entry is bogus and should not be printed.

Adding `print(log)` after the `from distutils import log` import statement in `setuptools/_distutils/dist.py` will help with debugging the problem. You should get the bogus `setuptools._distutils.log` module.

I believe this module duplication issue happens with other distutils submodules, you can check with:

```python
import setuptools
import sys
for k in sys.modules.keys():
    if '_distutils' in k:
        print(k)
```

which produces

```console
_distutils_hack
setuptools._distutils
setuptools._distutils.log
setuptools._distutils.dir_util
setuptools._distutils.file_util
setuptools._distutils.archive_util
_distutils_hack.override
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Thanks for the report. Unfortunately, all participants are expected to accept the code of conduct. I don't have any reason to exempt you from that otherwise uniform requirement. Since you appear to have some objection to that process, I recommend to (a) provisionally accept the code of conduct long enough to (b) file an issue with the [packaging discourse](https://discuss.python.org/c/packaging/14) expressing your concerns about the policy and process. Alternately, you may post your concerns in a forum that does not have such a code of conduct.

Until such a time that you are willing to operate within the policies of this project, I respectfully ask that you refrain from engaging with this project.

**Comment by pradyunsg** [comment]
FWIW, for future reference, OP deleted their comment about refusing to follow the PSF CoC. You can see their comment quoted over on https://discuss.python.org/t/what-to-do-with-contributors-who-refuse-code-of-conduct/13287

**Comment by jaraco** [comment]
I've confirmed the issue and localized where the module appears:

```
diff --git a/_distutils_hack/__init__.py b/_distutils_hack/__init__.py
index c6f7de606..95c12d8a1 100644
--- a/_distutils_hack/__init__.py
+++ b/_distutils_hack/__init__.py
@@ -54,10 +54,14 @@ def ensure_local_distutils():
     with shim():
         importlib.import_module('distutils')
 
+    assert not any('_distutils.log' in mod for mod in sys.modules)
+
     # check that submodules load as expected
     core = importlib.import_module('distutils.core')
     assert '_distutils' in core.__file__, core.__file__
 
+    assert not any('_distutils.log' in mod for mod in sys.modules)
+
 
 def do_override():
     """
```

With those two asserts, the first one passes and the second one doesn't. It's interesting and a little surprising that `import distutils.core` triggers the creation of both `distutils.log` and `setuptools._distutils.log`.
