### ISSUE TITLE
[FR] Add `pkg_resources` metadata

### ISSUE THREAD

**Issue by kloczek** [pypa/setuptools#3037]
### What's the problem this feature will solve?

I think that it would be good to add build and install `pkg_resources` module metadata.

### Describe the solution you'd like

With separated `pkg_resources` it would possible to add `pkg_resources` to build, runtime or test suite dependencies which could improve visibility what needs that module.

### Alternative Solutions

Alternativelely `pkg_resources` could be moved to sseparated source tree and maintained as separated module.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @kloczek, thank you for opening this issue.

Is this FR related to https://github.com/pypa/setuptools/issues/863 ?

If it is not related, what would be your request exactly? (I am afraid I don't understand what adding `pkg_resources` metadata means...)

**Comment by kloczek** [comment]
Yes. Simple I found type `A` has build or run time/install time dependency on `setuptools` when in reality it needs is needed `pkg_resources`.
At the moment `pkg_resources` is installed with own metadata
```console
[tkloczko@ss-desktop SPECS]$ rpm -ql python-setuptools |grep dist-info$
/usr/lib/python3.8/site-packages/setuptools-60.5.4.post20220117.dist-info
```
Those metadata provides module name which can be used in metadata of other modiles `Requires` fileds. If `pkg_resources` would be installed with its separated .dist-info metadata that visibility would be better.

**Comment by abravalheri** [comment]
Thanks for the clarification @kloczek.

Creating a separated `.dist-info` directory for `pkg_resources` require distributing it as its own separated distribution archive (i.e. package file uploaded to PyPI), which is the request covered in #863. So I think we can consider this issue a duplicate.

Meanwhile if you are a maintainer of this package, please consider migrating over `importlib.metadata` (or the backport `importlib_metadata`).

**Comment by kloczek** [comment]
OK I understand.
Thank you.
