### ISSUE TITLE
Wrong Version detected with project_wheel_metadata 

### ISSUE THREAD

**Issue by finswimmer** [pypa/setuptools#3088]
Hello,

I'm not sure whether this is a problem with `build`, `pep517`, `importlib.metadata` or something different.

I triaged a potential bug in poetry 1.2.0a2 and realized the following:

When I build a wheel for the current `sqlalchemy` from it's [main branch](https://github.com/sqlalchemy/sqlalchemy) - after cloning the repo - by `python -m build` the `Version` field in `METADATA` is `2.0.0b1.dev0`.

But when I run this in a python console the result is different:

```py
import build.util
meta = build.util.project_wheel_metadata(".")
meta.get("Version")
'2.0.0b1.dev0dev'
```

As you can see there's an additional `dev` at the end of the version.

Any ideas what's going on?

Python: 3.10.2
build: 0.7.0

fin swimmer

**Comment by jaraco** [comment]
A similar issue was [reported in this comment](https://github.com/pypa/setuptools/pull/2872#issuecomment-966518478). There may already be a bug reported about it. I'd appreciate help to triage.
