### ISSUE TITLE
databricks cli is not installing with latest setuptools version

### ISSUE THREAD

**Issue by jitheshksn** [pypa/setuptools#3104]
Facing issue with latest version of setuptools. databricks cli (latest version released on 4th Feb 2022) is not getting installed properly with latest version of setuptools (latest version today - 14 Feb 2022). It was working fine till 9th Feb 2022. Please look into this. 
As a work around we are hardcoding the setuptool version to 60.8.1

**Comment by jiyongjung0** [comment]
We are facing the same issue with [tfx](https://github.com/tensorflow/tfx) CLI using setuptools 60.9.0. (60.8.2 is fine). I'm not sure this is related but I could find `ttx` instead of `tfx` in the expected binary directory.

**Comment by rsyring** [comment]
Dups? https://github.com/pypa/setuptools/issues/3103

**Comment by jaraco** [comment]
Likely duplicate. Assuming so until I find otherwise.
