### ISSUE TITLE
Barebones setuptool docs for "Using setuptools to package and distribute your project"

### ISSUE THREAD

**Issue by ketozhang** [pypa/setuptools#3105]
### Summary

This documentation page is barebones and leaves the user staring at a blank wall. Last this was updated was 2020 September.

* https://setuptools.pypa.io/en/latest/userguide/functionalities_rewrite.html#
* https://github.com/pypa/setuptools/blob/abbaacc62aa26c611d68b935363765af702c0861/docs/userguide/functionalities_rewrite.rst

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
I'm unsure the history of that doc. I welcome investigation or edits.

**Comment by ketozhang** [comment]
Good first issue?

**Comment by ketozhang** [comment]
Closing as the page doesn't exists and the user guide structure has been redesigned.
