### ISSUE TITLE
[BUG] build_scripts.py incorrectly handles shebang lines with DOS line endings

### ISSUE THREAD

**Issue by amalachow** [pypa/setuptools#3129]
### setuptools version

setuptools 60.9.3

### Python version

Python 3.8.10

### OS

NT-10.0-19042

### Description

shebang using DOS line endings causes the shebang regular expression to fail resulting in redirection to the python interpreter used for the installed script to not behave as expected.

### Expected behavior

The shebang is rewritten consistently for UNIX and DOS line endings.

### How to Reproduce

```shell
#!/bin/bash -eu
printf "[[System Info]]\n"
uname -srvmo
python3 --version
python3 -m virtualenv --version
rm -rf .venv
python3 -m virtualenv --quiet -p python3 .venv
.venv/Scripts/python -m pip install --quiet --upgrade pip &> /dev/null
.venv/Scripts/python -m pip install --quiet --upgrade setuptools &> /dev/null
.venv/Scripts/python -m pip list

rm -rf example
mkdir example
cat > example/example.py << END
#!/usr/bin/env python3

def main():
    print("Example script")

if __name__=="__main__":
    main()
END

cat > example/setup.py << END
from setuptools import setup
setup(name="example", scripts=["example.py"])
END

printf "\n[[Expected behavior]]\n"
file example/example.py
.venv/Scripts/pip install --quiet ./example
head -1 .venv/Scripts/example.py

printf "\n[[Issue]]\n"
sed -ie 's/\r*$/\r/g' example/example.py
file example/example.py
.venv/Scripts/pip install --quiet -I ./example
head -1 .venv/Scripts/example.py

fix="--- a/build_scripts.py
+++ b/build_scripts.py
@@ -15 +15 @@
-first_line_re = re.compile(b'^#!.*python[0-9.]*([ \t].*)?$')
+first_line_re = re.compile(b'^#!.*python[0-9.]*([ \t].*)?\r?$')"

printf "\n[[Proposed Fix]]\n"
echo "${fix}"
patch -u -p0 .venv/Lib/site-packages/setuptools/_distutils/command/build_scripts.py <<< ${fix}
file example/example.py
.venv/Scripts/pip install --quiet -I ./example
head -1 .venv/Scripts/example.py```

### Output

```console
[[System Info]]
MINGW64_NT-10.0-19042 3.1.7-340.x86_64 2021-03-26 22:17 UTC x86_64 Msys
Python 3.8.10
virtualenv 20.10.0 from C:\Python38\lib\site-packages\virtualenv\__init__.py
Package    Version
---------- -------
pip        22.0.3 
setuptools 60.9.3 
wheel      0.37.1 

[[Expected Behavior]]
example/example.py: Python script, ASCII text executable
#!C:\setuptools-issue\.venv\Scripts\python.exe

[[Issue]]
example/example.py: Python script, ASCII text executable, with CRLF line terminators
#!/usr/bin/env python3

[[Proposed Fix]]
--- a/build_scripts.py
+++ b/build_scripts.py
@@ -15 +15 @@
-first_line_re = re.compile(b'^#!.*python[0-9.]*([ \t].*)?$')   
+first_line_re = re.compile(b'^#!.*python[0-9.]*([ \t].*)?\r?$')
patching file .venv/Lib/site-packages/setuptools/_distutils/command/build_scripts.py
example/example.py: Python script, ASCII text executable, with CRLF line terminators
#!C:\setuptools-issue\.venv\Scripts\python.exe
```

**Comment by abravalheri** [comment]
Hi @amalachow, thank you very much for bringing this up.

Does this issue also happens when using the `console_scripts` [entry-point](https://setuptools.pypa.io/en/stable/userguide/entry_point.html)?

**Comment by amalachow** [comment]
@abravalheri took a quick look at this and on Windows the `console_scripts` entry-point is generating a Windows executable.

Taking much of the same logic in the original bug report and modifying setup.py to use and including an empty `__init__.py`
```python
setup(
    name="example",
    packages=["."],
    entry_points={
        "console_scripts":[
            "example = example:example.main"
        ]
    },
)
```
Does this align with what you were expecting?

**Comment by abravalheri** [comment]
Yes, exactly. Thank you very much for testing that! I was just wondering if `pip` also re-creates the script wrappers, but it seems that this is not the case.

@amalachow would you like to submit the proposed patch to https://github.com/pypa/distiutils? I think that repository would be the best place to address the error... From times to times it get merged in setuptools, if we change something directly in setuptools, there is the risk of "undoing" it next time distutils is merged..

**Comment by jaraco** [comment]
I'll move this issue to the distutils project.

**Comment by jaraco** [comment]
That's weird - I don't seem to have distutils access: 
![image](https://user-images.githubusercontent.com/308610/155823095-345d5f0e-32c4-4fd7-b9bf-dd66490ec9c2.png)

**Comment by amalachow** [comment]
Moved manually to https://github.com/pypa/distutils/issues/124
