### ISSUE TITLE
[BUG] Editable install has recently stopped working in Ubuntu 21.10 Impish when run from root

### ISSUE THREAD

**Issue by KOLANICH** [pypa/setuptools#3131]
### setuptools version

latest from git, but I have rolled back to ancient ones and the issue persists, the issue is likely not in setuptools itself

### Python version

CPython 3.9

### OS

Kubuntu 21.10 Impish

### Description

`sudo pip3 install --upgrade -e .` doesn't result in package becoming importable. Installing from a user works fine.

I have debugged the issue a bit, tried ancient (that I remember have been working fine) versions of `pip` and `setuptools`, and it turns out it doesn't work with them either.

It turned out that `install_dir` contains the wrong path, the one working must have `/usr/local/lib/python3.9/dist-packages`, but and `/usr/lib/python3.9/site-packages/` is used.

So the temporary fix for me was

```python
From 0f093e7a16ecd00eff72fc8961ac6ed3f310fb83 Mon Sep 17 00:00:00 2001
From: KOLANICH <KOLANICH@users.noreply.github.com>
Date: Mon, 21 Feb 2022 21:05:23 +0300
Subject: [PATCH] A temporary fix of wrong `install_dir` captured from some
 config, causing non-working editable installs from `root` on Ubuntu.

---
 setuptools/command/easy_install.py | 1 +
 1 file changed, 1 insertion(+)

diff --git a/setuptools/command/easy_install.py b/setuptools/command/easy_install.py
index 5b73e6e9..ac6b2623 100644
--- a/setuptools/command/easy_install.py
+++ b/setuptools/command/easy_install.py
@@ -285,6 +285,7 @@ class easy_install(Command):
             'install_dir', 'script_dir', 'build_directory',
             'site_dirs',
         )
+        self.install_dir = "/usr/local/lib/python3.9/dist-packages"
         # If a non-default installation directory was specified, default the
         # script directory to match it.
         if self.script_dir is None:
-- 
2.32.0
```

But I guess some of the configs that must be provided by distro and that `setuptools` takes the info from can be changed incorrectly in some recent updates. Can someone point where I should look?

### Expected behavior

Should work as expected out of the box.

### How to Reproduce

0. Use Ubuntu Impish, every packaging-related python package is of the latest version (except `pip`, they have introduced the change breaking my workflow recently, I guess it can be a sign of a bug) from git
1. Clone some project. I used https://github.com/KOLANICH-libs/JImageHash.py
2. `sudo pip3 install --upgrade -e .`
3. Go into other dir and open an (i)pythkn shell and try to import. The import will fail.
4. Check for `pth` files in the wrong locatikn
5. Apply the patch to `setuptools`
6. Try installation again.
7. Enjoy the package importable.

### Output

```console
KOLANICH@KOLANICH:~/JImageHash.py$ sudo pip3 install --upgrade -e .
Obtaining file:///home/KOLANICH/JImageHash.py
  Checking if build backend supports build_editable ... done
  Preparing metadata (pyproject.toml) ... done
Installing collected packages: JImageHash
  Running setup.py develop for JImageHash
Successfully installed JImageHash
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
KOLANICH@KOLANICH:~/ ipython
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.1.0.dev -- An enhanced Interactive Python. Type '?' for help.

In [1]: import JImageHash
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <module>
----> 1 import JImageHash

ModuleNotFoundError: No module named 'JImageHash'
KOLANICH@KOLANICH:~/ cat /usr/local/lib/python3.9/dist-packages/easy-install.pth | grep JImageHash.py
KOLANICH@KOLANICH:~/ cat /usr/lib/python3.9/site-packages/easy-install.pth 
/home/KOLANICH/JImageHash.py
KOLANICH@KOLANICH:~/ cat /usr/lib/python3.9/site-packages/JImageHash.egg-link
/home/KOLANICH/JImageHash.py
```

**Comment by jaraco** [comment]
Debian still needs to provide patches to support distutils as found in Setuptools. See #2996.
