### ISSUE TITLE
[BUG] Failed to install pathlib: 'PosixPath' object has no attribute 'read_text'

### ISSUE THREAD

**Issue by bartmao** [pypa/setuptools#3132]
### setuptools version

setuptools>=60.9.0

### Python version

3.7

### OS

Debian

### Additional environment information

pip 22.0.3

### Description

Failed to install pathlib in force mode

### Expected behavior

pathlib successfully installed

### How to Reproduce

```
pip install --force-reinstall  --no-cache-dir pathlib
```

### Output

```
Defaulting to user installation because normal site-packages is not writeable
Collecting pathlib
  Downloading pathlib-1.0.1.tar.gz (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 KB 64.1 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-um6pgzdc/pathlib_96ea0574b3694106a3e5ebed231d8a19/setup.py", line 30, in <module>
          url='https://pathlib.readthedocs.org/',
        File "/home/tiger/.local/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/tiger/.local/lib/python3.7/site-packages/setuptools/dist.py", line 456, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
        File "/home/tiger/.local/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 1003, in entry_points
          return SelectableGroups.load(eps).select(**params)
        File "/home/tiger/.local/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 453, in load
          ordered = sorted(eps, key=by_group)
        File "/home/tiger/.local/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 1001, in <genexpr>
          dist.entry_points for dist in unique(distributions())
        File "/home/tiger/.local/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 613, in entry_points
          return EntryPoints._from_text_for(self.read_text('entry_points.txt'), self)
        File "/home/tiger/.local/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 921, in read_text
          return self._path.joinpath(filename).read_text(encoding='utf-8')
      AttributeError: 'PosixPath' object has no attribute 'read_text'
      [end of output]
 ```

```

**Comment by abravalheri** [comment]
Hi @bartmao, I am under the impression that the package `pathlib` is *discontinued* and should not be used.

You can directly `import pathlib` in Python, because it is now part of the standard library.

You can also use [`pathlib2`](https://pypi.org/project/pathlib2/) instead.

**Comment by edmorley** [comment]
> The error is happening because by installing `pathlib` you are overwriting the implementation in the stdlib with some package that is not API-compatible. Therefore any code relying on the public/documented API of `pathlib` can break.

Hi! I don't believe this is correct. 

Under a normally configured Python installation, the `sys.path` precedence is such that the Python stdlib comes before any site-packages directories. As such, the stdlib `pathlib` should "win" over any legacy installed `pathlib` package. Therefore whilst `pathlib` is not technically needed, it shouldn't cause problems if it's installed (such as being pulled in via third party deps which we may have no control over).

For example, using `read_text()` works just fine outside of setuptools, even if the legacy `pathlib` package is installed:

```
$ docker run --rm -it python:3.9.12 bash
root@d447c570719c:/# pip install pathlib==1.0.1
...
Successfully installed pathlib-1.0.1
root@d447c570719c:/# echo 'hello!' > testcase.txt
root@d447c570719c:/# python -c 'import pathlib; print(pathlib.PosixPath("testcase.txt").read_text())'
hello!
```

As such, this issue seems more like a setuptools bug, whereby the normal `sys.path` precedence is being overridden.

I've encountered something similar to that described here, but have opened a new issue since (a) the steps to reproduce are slightly different, (b) this issue is closed. See: #3294.

**Comment by abravalheri** [comment]
When installing `pathlib`, the deprecated/outdated/discouraged implementation in PyPI will be available as the first entry on `sys.path`, because of the way `PYTHONPATH` works (the current working dir is automatically added).

Isn't it the case?

**Comment by abravalheri** [comment]
We can think about the installation process for `pathlib==1.0.1` as being roughly equivalent to:

```
cd /tmp
wget https://pypi.io/packages/source/p/pathlib/pathlib-1.0.1.tar.gz
tar xf pathlib-1.0.1.tar.gz
cd pathlib-1.0.1
python setup.py bdist_wheel  # suitable versions for both setuptools and wheel need to be installed
pip install dist/*.whl
```

The code running in the 5th line will try to load the `pathlib` from CWD, not from stdlib. If we replace the 5th, we can see that more clearly:

```
python -c 'import pathlib; print(pathlib)'
<module 'pathlib' from '/tmp/pathlib-1.0.1/pathlib.py'>
```
