### ISSUE TITLE
[FR] Default tag to install all extras

### ISSUE THREAD

**Issue by eggplants** [pypa/setuptools#3139]
### What's the problem this feature will solve?

I would like to install all extras by using default tag like `[all]`, or `[all_extras]`.

In many projects, this feature is often implemented like this in `setup.py`:

```python
from setuptools import setup

extras_require = {
    'dev': ['black', 'isort'],
    'test':  ['pytest']
}
extras_require['all'] = {
    v for v in for vs in extras_require.values()
}

setup(
    ...
    extra_requires=extra_requires,
    ...
)
```

But this way is not available in `setup.cfg`.
So, I would like to have a default tag that can install all extras.

### Describe the solution you'd like

- declare a default tag like `[all]`, or `[all_extras]` implicitly

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @eggplants, thank you very much for bringing this up.

I think that a better forum for discussing this change would be https://discuss.python.org/c/packaging, since it may involve other parts of the ecosystem and require standardisation.

**Comment by jack1142** [comment]
Personally, I use interpolation in setup.cfg as follows:
```ini
[options.extras_require]
dev =
    black
    isort
test =
    pytest
all =
    %(dev)
    %(test)
```
Note that this (probably, I have not verified this) does not work with the new pyproject.toml-based declarative metadata (PEP 621) as the interpolation is something that is provided by Python's configparser, not setuptools.

**Comment by eggplants** [comment]
@jack1142 Thanks! Your workaround is so useful!

**Comment by jack1142** [comment]
I'd like to add that as I found out few days ago, you can use recursive dependencies since pip 21.2 which allows you to i.e. declare `pkg_name[black,isort]` as a dependency for the `dev` extra:
https://hynek.me/articles/python-recursive-optional-dependencies/

This should also work in the PEP 621 scenario which can't use the interpolation I suggested earlier.
