### ISSUE TITLE
[BUG] sys.stderr is None when running generated exe in bash on Windows

### ISSUE THREAD

**Issue by charlieman** [pypa/setuptools#3140]
### setuptools version

setuptools===60.9.3

### Python version

Python 3.10

### OS

Windows 10

### Additional environment information

This is happening in Bash (using bash that comes with [git for windows](https://gitforwindows.org/)

### Description

On Windows running a terminal with bash, when I run the exe files generated from entry_point configurations (for example pip.exe or ipython.exe), `sys.stderr` is `None`. Running the same exe from cmd or powershell works as expected.

This was first reported in IPython [#13509](https://github.com/ipython/ipython/issues/13509). IPython works fine when running `python -m IPython` or when running `ipython.exe` from other shells like cmd or powershell.

I'm including a small example that prints `sys.stdout` and `sys.stderr` for comparison.

### Expected behavior

`sys.stderr` should not be `None` when running from bash.

### How to Reproduce

- Download and unzip the file: [bugexe.zip](https://github.com/pypa/setuptools/files/8159126/bugexe.zip)
- From bash:
  - `cd bugexe`
  - `python -m venv .venv`
  - `source .venv/Scripts/activate`
  - `python -m pip install --upgrade pip setuptools`
  - `pip install --use-feature=in-tree-build .`
  - `./.venv/Scripts/bugexe.exe`
- From cmd:
  - `cd bugexe`
  - `.venv\Scripts\activate`
  - `.venv\Scripts\bugexe.exe`

### Output

The output running the bugexe command from bash is:
```
sys.stdout=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
sys.stderr=None
```
The output from cmd:
```
sys.stdout=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
sys.stderr=<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
```

**Comment by grahamcarman** [comment]
I'm getting the same issue. Unfortunately, it prevents me from running `server.py`, which outputs logs via `stderr`. Thank you so much for posting this.

**Comment by abravalheri** [comment]
Hi @charlieman, @grahamcarman thank you very much for bringing this issue into discussion.

Currently when you install a package with `pip install .` the script wrappers are generated directly by `pip` using the functionality provided by [`distlib`](https://distlib.readthedocs.io/en/latest/tutorial.html#wrapping-callables-with-scripts).

Have you tried checking their issue tracker to see if anyone had a similar problem?

(For now, setuptools will only handle the wrappers for editable installs. In the future that is very likely to change and all the wrappers to be handled by `pip`)

**Comment by charlieman** [comment]
@abravalheri thanks for pointing me out to pip and distlib. I was trying this again and now it's working correctly so they probably made a fix. I am closing this ticket now, thanks again!
