### ISSUE TITLE
[BUG] Unable to import pkg_resources before setuptools

### ISSUE THREAD

**Issue by chrisburr** [pypa/setuptools#3165]
### setuptools version

60.9.3 (also affects the main branch)

### Python version

Python 3.7 from PyPy 7.3.7

### OS

macOS

### Additional environment information

Using packages from conda-forge.

### Description

Importing `pkg_resources` before `setuptools` results in `setuptools` being broken with `AttributeError: module 'setuptools' has no attribute 'version'`.

### Expected behavior

The import order doesn't matter.

### How to Reproduce

```bash
> conda create -c conda-forge --name test setuptools pypy
> conda activate test
> python -c 'import setuptools, pkg_resources; print("All good")'
All good
> python -c 'import pkg_resources, setuptools; print("All good")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/cburr/mambaforge/envs/test/site-packages/setuptools/__init__.py", line 35, in <module>
    __version__ = setuptools.version.__version__
AttributeError: module 'setuptools' has no attribute 'version'
```

### Output

```console
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/cburr/mambaforge/envs/test/site-packages/setuptools/__init__.py", line 35, in <module>
    __version__ = setuptools.version.__version__
AttributeError: module 'setuptools' has no attribute 'version'
```

**Comment by abravalheri** [comment]
I wonder if that could be related to the fact that PyPy 3.7 imports `distutils` in its `sysconfig`, which triggers `_distutils_hack` and potentially mess things around...

- https://foss.heptapod.net/pypy/pypy/-/blob/8301595a71447bbe58bb61c5ecd83d93cfda5eb0/lib-python/3/sysconfig.py#L461-473
- https://foss.heptapod.net/pypy/pypy/-/blob/8301595a71447bbe58bb61c5ecd83d93cfda5eb0/lib_pypy/_sysconfigdata.py#L5

**Comment by abravalheri** [comment]
@chrisburr, any chance you could try this quick change on `setuptools/version.py` to see if it works?

```diff
- import pkg_resources
+ from setuptools.extern import importlib_metadata

try:
-    __version__ = pkg_resources.get_distribution('setuptools').version
+    __version__ = importlib_metadata.version('setuptools')
except Exception:
    __version__ = 'unknown'
```

**Comment by chrisburr** [comment]
Thanks for the quick response! The proposed change to `setuptools/version.py` doesn't seem to help:

```python
> cat $CONDA_PREFIX/lib/python3.7/site-packages/setuptools/version.py
# import pkg_resources
from setuptools.extern import importlib_metadata

try:
    # __version__ = pkg_resources.get_distribution('setuptools').version
    __version__ = importlib_metadata.version('setuptools')
except Exception:
    __version__ = 'unknown'


> python -c 'import setuptools, pkg_resources; print("All good")'
All good

> python -c 'import pkg_resources, setuptools; print("All good")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/cburr/mambaforge/envs/test/site-packages/setuptools/__init__.py", line 35, in <module>
    __version__ = setuptools.version.__version__
AttributeError: module 'setuptools' has no attribute 'version'
```

**Comment by chrisburr** [comment]
I'm not very familiar with exactly how imports work but `setuptools.version` is in `sys.module` but `setuptools` isn't which seems odd...
```python
Python 3.7.12 | packaged by conda-forge | (44db2626, Nov 15 2021, 13:00:09)
[PyPy 7.3.7 with GCC Clang 11.1.0] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import pkg_resources
>>>> import sys
>>>> sys.modules["setuptools.version"]
<module 'setuptools.version' from '/Users/cburr/mambaforge/envs/test/site-packages/setuptools/version.py'>
>>>> sys.modules["setuptools.version"].__version__
'60.9.3.post20220310'
>>>> import setuptools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cburr/mambaforge/envs/test/site-packages/setuptools/__init__.py", line 35, in <module>
    __version__ = setuptools.version.__version__
AttributeError: module 'setuptools' has no attribute 'version'
>>>> dir(sys.modules["setuptools"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'setuptools'
```

**Comment by chrisburr** [comment]
I've added `print("dir(setuptools) before getting version =", dir(setuptools))` before `__version__ = setuptools.version.__version__` in `setuptools.__init__.py`:

```
dir(setuptools) before getting version = ['Distribution', 'DistutilsOptionError', 'Extension', 'Require', 'SetuptoolsDeprecationWarning', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_deprecation_warning', '_distutils', '_distutils_hack', '_entry_points', '_imp', '_importlib', '_itertools', '_reqs', '_vendor', 'command', 'config', 'convert_path', 'depends', 'dist', 'distutils', 'extension', 'extern', 'fnmatchcase', 'functools', 'logging', 'monkey', 'os', 'py34compat', 're', 'setuptools', 'version', 'windows_support']
All good
```

```
dir(setuptools) before getting version = ['Distribution', 'DistutilsOptionError', 'Extension', 'Require', 'SetuptoolsDeprecationWarning', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_distutils_hack', '_entry_points', '_imp', '_itertools', '_reqs', 'convert_path', 'depends', 'dist', 'distutils', 'fnmatchcase', 'functools', 'logging', 'monkey', 'os', 'py34compat', 're', 'setuptools']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/cburr/mambaforge/envs/test/site-packages/setuptools/__init__.py", line 35, in <module>
    __version__ = setuptools.version.__version__
AttributeError: module 'setuptools' has no attribute 'version'
```

The difference between the two lists is: `{'_deprecation_warning', '_distutils', '_importlib', '_vendor', 'command', 'config', 'extension', 'extern', 'version', 'windows_support'}`.

**Comment by chrisburr** [comment]
> I wonder if that could be related to the fact that PyPy 3.7 imports distutils in its sysconfig, which triggers _distutils_hack and potentially mess things around...

I've looked a little further and this line of reasoning seems correct. If I apply this change the problem goes away:

```diff
- from distutils.spawn import find_executable
+ from shutil import which as find_executable
```

https://foss.heptapod.net/pypy/pypy/-/blob/9d9c502f8f362f3b9862f3d91c5f5b13b240bbdb/lib_pypy/_sysconfigdata.py#L5

**Comment by abravalheri** [comment]
Hi @chrisburr thank you very much for investigating this!

I don't know if the PyPy community would be open to a patch, but that would definitely make things easier...

**Comment by chrisburr** [comment]
I've opened an issue for PyPy: https://foss.heptapod.net/pypy/pypy/-/issues/3703

I'll follow up here when there is a response.

**Comment by chrisburr** [comment]
PyPy has accepted the change [pypy/pypy!844](https://foss.heptapod.net/pypy/pypy/-/merge_requests/844) so I guess this can be closed?

**Comment by abravalheri** [comment]
Hi Cris, yes! Thank you very much for spotting the problem and coordinating a solution with the PyPy team! ❤️ 💚 💛 💙 

I can see that they are planning a release including the changes you proposed https://foss.heptapod.net/pypy/pypy/-/commit/a1b1b3169deb1d309c88c1ba3cfef6fb069ddc6a

Hopefully it will be out soon 🤞
