### ISSUE TITLE
easy_install documentation should promote (or mention) Pip

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#318]
Originally reported by: **hickford (Bitbucket: [hickford](http://bitbucket.org/hickford), GitHub: [hickford](http://github.com/hickford))**

---

Pip is preferred to `easy_install` for several [good reasons](http://stackoverflow.com/a/3220572/284795). Thus it's promoted by all the recent Python guides, and by Python itself now shipping with Pip.

Thus it might also make sense for the documentation at https://pythonhosted.org/setuptools/easy_install.html to encourage users to Pip. At the least, it should mention Pip and give a link to it.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/318

**Comment by pganssle** [comment]
I believe this is done in f4b320e5e3ec9c7e1ef4b90017050e029029d449
