### ISSUE TITLE
[BUG] Package data missing with Setuptools 61

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#3196]
I've been fighting building [one of my projects](/jaraco/recapturedocs) this evening, finding that all of the package data is missing.

```
$ pip-run -q recapturedocs==5.0.1 -- -c "import recapturedocs, os; assert 'prod.conf' in os.listdir(os.path.dirname(recapturedocs.__file__))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError
```

But if I instead build with `setuptools<61` (by changing the pyproject.toml), the content is present.

```
$ git -C ~/m/recapturedocs diff
diff --git a/pyproject.toml b/pyproject.toml
index 190b355..cfacc1a 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=56", "setuptools_scm[toml]>=3.4.1"]
+requires = ["setuptools>=56,<61", "setuptools_scm[toml]>=3.4.1"]
 build-backend = "setuptools.build_meta"
 
 [tool.black]
$ pip-run -q ~/m/recapturedocs -- -c "import recapturedocs, os; assert 'prod.conf' in os.listdir(os.path.dirname(recapturedocs.__file__))"
$
```

I haven't yet had a chance to investigate why, but I wanted to register this issue.

**Comment by nabobalis** [comment]
We have the same issue with out package and also use `setuptools_scm`. If I were to speculate, something has broken with the update to `setuptools` and the current version of `setuptools_scm`.

**Comment by domdfcoding** [comment]
I'm having a similar issue (presumably the same cause). I use `MANIFEST.in` to control which files are included in the sdist and wheel, but `MANIFEST.in` now seems to be ignored for the wheel.

Using `git bisect` I found that the behaviour changed after https://github.com/pypa/setuptools/commit/755e053ee6c3b82024a687082a164e1c4a88cfbb; if I install the previous commit (83d11a14) everything works as expected.
Specifically, commenting out these two lines makes it work for me, even on `main`:
https://github.com/pypa/setuptools/blob/4923d1139be9366b3010a6d6e56d4c4980a0ab6e/setuptools/config/setupcfg.py#L156-L157
Not sure why or what purpose those lines serve.

**Comment by abravalheri** [comment]
Hi Jason, thank you very much for reporting this. I will work on it.

**Comment by abravalheri** [comment]
Thank you very much @domdfcoding for investigating! That is very helpful.

These lines serve to ensure people can use `version = attr: module.__version__` with auto-discovery, I was not expecting them to have this side effect. I will investigate more in depth.

**Comment by jaraco** [comment]
Confirmed the fix works. Thanks for the quick response!
