### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by aragilar** [pypa/setuptools#3197]
### setuptools version

61.0.0

### Python version

3.9

### OS

Debian Unstable

### Description

kiwisolver 1.4.0 (I haven't checked earlier versions, but kiwisolver 1.4.0 did modernise their build, so issues with earlier versions will likely be to different code) can no build from source. I filed https://github.com/nucleic/kiwi/issues/130 with the kiwisolver developers, but it appears that setuptools 60.10.0 does work.  Based on looking at https://github.com/pypa/setuptools/compare/v60.10.0...v61.0.0 and the error message that appears (see output), I think this is related to the new(?) package discovery mechanism. I'm not a kiwisolver developer, so I can't answer questions about their build system (other than link you to the repository), but I'm filing this as it appears to be a regression (give setuptools 61 came out 10 hours ago when I wrote this).

### Expected behavior

I expect `pip install kiwisolver` would build a wheel and install it.

### How to Reproduce

1. Run `pip install kiwisolver` (given kiwisolver has wheels, you may need to disable using wheels to not download a pre-built wheel).

### Output

```console
      /tmp/pip-build-env-nwrt4o9m/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:100: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
        warnings.warn(msg, _ExperimentalProjectMetadata)
      Install ``trove-classifiers`` to ensure proper validation. Meanwhile a list of classifiers will be downloaded from PyPI.
      error: Multiple top-level packages discovered in a flat-layout: ['py', 'kiwi'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
      
      To find more information, look for "package discovery" on setuptools docs.
```

**Comment by MatthieuDartiailh** [comment]
I am a maintainer of kiwisolver. I guess that setuptools is confused because kiwisolver is a pure C extensions without any python source. Currently it does not specify a value for py_modules nor for packages. I would appreciate any advice on how to keep things working with the latest setuptools.

**Comment by abravalheri** [comment]
Thank you very much for reporting this.

My understanding is that unfortunately there is a clash of 2 behaviours:

To make these changes as backwards compatible as possible, I added a condition that only works for packages not using `pyproject.toml` that will check if `ext_modules` is given and then skip auto-discovery.

But, going forward my assumption was that it is very common for packages to mix both regular Python code with extensions. So if a project is using `pyproject.toml` for metadata, auto-discovery is always on.

I did not foresee that `kiwisolver` was providing metadata in both `pyproject.toml` and `setup.py` already before the latest change. Sorry for that.

@MatthieuDartiailh, one way to disable auto discovery is to explicitly set `py_modules=[]` in `setup.py` or `py-modules = []` in `pyproject.toml [tool.setuptools]`. Would that work for you?

If that is a viable alternative, it would help a lot! I was hopping to keep the auto-discovery always on for packages using `pyproject.toml`...

**Comment by MatthieuDartiailh** [comment]
It would work, but actually my setup is broken since in its current state it does not distribute type annotations which I recently added. So I will need to rework the overall structure. 

I had hoped to get rid of everything but the C extension building in setup.py however this warning is a bit frightening. Do you really think you may roll back support for PEP 621 ?

**Comment by abravalheri** [comment]
> Do you really think you may roll back support for PEP 621?

I hope not, but it is very early to say. It was just released yesterday, and if it break to many projects I might have to roll back before re-working on it again.

Given that we are not forced to roll back, usage the `[project]` table should change, after all it is defined in a PEP, but the shape of `[tool.setuptools]` might differ a bit in the future...

---
> my setup is broken since in its current state it does not distribute type annotations which I recently added.

Is this also caused by the latest release?

**Comment by MatthieuDartiailh** [comment]
No I added those in the last release and apparently I did not properly test apparently.

**Comment by MatthieuDartiailh** [comment]
> > Do you really think you may roll back support for PEP 621?
> 
> I hope not, but it is very early to say. It was just released yesterday, and if it break too many projects I might have to roll back before re-working on it again.
> 
> Given that we are not forced to roll back, usage the `[project]` table should change, after all it is defined in a PEP, but the shape of `[tool.setuptools]` might differ a bit in the future...

Here you mean "[project] table should not change", right ?

> 
> > my setup is broken since in its current state it does not distribute type annotations which I recently added.
> 
> Is this also caused by the latest release?

**Comment by tobni** [comment]
We observe a similar error (but with different warnings) with `scikit-fmm==2022.02.02` on python 3.10.2:

```
Collecting scikit-fmm==2022.02.02
  Downloading scikit-fmm-2022.2.2.tar.gz (434 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 434.5/434.5 KB 87.6 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-build-env-qhobckeh/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'configuration'
        warnings.warn(msg)
      /tmp/pip-build-env-qhobckeh/overlay/lib/python3.10/site-packages/setuptools/dist.py:511: UserWarning: Normalizing '2022.02.02' to '2022.2.2'
        warnings.warn(tmpl.format(**locals()))
      error: Multiple top-level packages discovered in a flat-layout: ['skfmm', 'profile'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
      
      To find more information, look for "package discovery" on setuptools docs.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

**Comment by abravalheri** [comment]
Hi @tobni, thank you very much for reporting this.
Am I correct in assume that `scikit-fmm` does not specify any of `py_modules`, `packages` or `ext_modules` keywords?

**Comment by abravalheri** [comment]
> Here you mean "[project] table should not change", right ?

Yes sorry @MatthieuDartiailh, I typed that too fast without checking 😅

**Comment by tobni** [comment]
@abravalheri Not in the pyproject.toml, no. I don't know exactly where to look in the setup.py file, the scikit-fmm package uses `numpy.distutils.misc_util import Configuration` which is hard to grok.

**Comment by abravalheri** [comment]
My question was more in the direction of `setup.py`. I will have a look on the `numpy.distutils.misc_util.Configuration`. Thank you very much @tobni.

**Comment by MatthieuDartiailh** [comment]
Experiment a bit I found another undesirable behavior. 

Kiwisolver uses setuptools-scm and after modifying the setup.py to include the following directives (which silences the previously reported error for setuptools 61) the installed package in site-packages includes all the C source files and the tests even though they are not requested. With Setuptools <= 60, the install contains just an `__init__.py` (added to allow accessing the C extension content), a .pyi file, py.typed and the built extension package.
```python
    package_dir={"kiwisolver": "py"},
    packages=["kiwisolver"],
    install_requires=["typing_extensions;python_version<'3.8'"],
    ext_modules=ext_modules,
    cmdclass={"build_ext": CppyBuildExt},
    package_data={"kiwisolver": ["py.typed", "*.pyi"]},
```

**Comment by abravalheri** [comment]
Thanks @MatthieuDartiailh, I will have a look on that too.

This is likely related to the fact that the presence of `[project]` in `pyproject.toml` will automatically flip the default value of `include_package_data` (in `setup.cfg/setup.py`-only projects it defaults to `False`, while with `pyproject.toml [project]` it defaults to `True`.

This should have been added to the CHANGELOG. Sorry I forgot that.

**Comment by MatthieuDartiailh** [comment]
It appears that through some re-organization of kiwi I managed to circumvent the issue (see the PR). But it may not apply to other packages out there.

**Comment by TimoRoth** [comment]
Not sure if this is the same issue, but building scipy with --no-build-isolation fails as well since the setuptools 61.0 update.
With build isolation their pin to setuptools<60 in pyproject.toml saves the day.

**Comment by MatthieuDartiailh** [comment]
Note that even though it does not break the build the issue of unwanted files being included can also be seen in https://github.com/nucleic/atom

**Comment by MatthieuDartiailh** [comment]
Basically all C source files found under atom/src end being installed. What I find confusing with the include_package_data explanation is that even if I set it to False manually in setup.py I still see the same weird behavior. Do you expect that ?

**Comment by abravalheri** [comment]
>  if I set it to False manually in setup.py I still see the same weird behavior. Do you expect that ?

I will work on that. The current code expects `include-package-data` to be set to false in `pyproject.toml [tool.setuptools]`, but I completely agree it should work also when it is set in `setup.py`.

**Comment by MatthieuDartiailh** [comment]
I can confirm that settings `include-package-data` in pyproject.toml does indeed work.

**Comment by sanderr** [comment]
I'm encountering this issue on packages that act solely as a meta package for distributing a collection of related packages via dependencies. The package does not have any source packages or modules. I can confirm that explicitly setting `packages=[]` resolves the issue.

I do still find it strange that what you call an experimental feature in the docs is enabled by default.

**Comment by sanderr** [comment]
To be fair, I see this behavior is mentioned in your changelog under "breaking changes". That's my bad for not checking there in the first place.

**Comment by TimoRoth** [comment]
Another package that fails to build now is cartopy:

```
#20 731.2 Collecting cartopy>=0.20.0
#20 731.2   Downloading Cartopy-0.20.2.tar.gz (10.8 MB)
#20 731.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 34.0 MB/s eta 0:00:00
#20 731.8   Installing build dependencies: started
#20 794.2   Installing build dependencies: still running...
#20 858.3   Installing build dependencies: still running...
#20 939.5   Installing build dependencies: still running...
#20 1007.0   Installing build dependencies: still running...
#20 1079.0   Installing build dependencies: still running...
#20 1080.7   Installing build dependencies: finished with status 'done'
#20 1080.7   Getting requirements to build wheel: started
#20 1080.8   Getting requirements to build wheel: finished with status 'error'
#20 1080.8   error: subprocess-exited-with-error
#20 1080.8
#20 1080.8   × Getting requirements to build wheel did not run successfully.
#20 1080.8   │ exit code: 1
#20 1080.8   ╰─> [16 lines of output]
#20 1080.8       Traceback (most recent call last):
#20 1080.8         File "/usr/local/pyenv/versions/3.10.4/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#20 1080.8           main()
#20 1080.8         File "/usr/local/pyenv/versions/3.10.4/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#20 1080.8           json_out['return_val'] = hook(**hook_input['kwargs'])
#20 1080.8         File "/usr/local/pyenv/versions/3.10.4/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
#20 1080.8           return hook(config_settings)
#20 1080.8         File "/tmp/pip-build-env-vso68_9c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
#20 1080.8           return self._get_build_requires(
#20 1080.8         File "/tmp/pip-build-env-vso68_9c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
#20 1080.8           self.run_setup()
#20 1080.8         File "/tmp/pip-build-env-vso68_9c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
#20 1080.8           exec(compile(code, __file__, 'exec'), locals())
#20 1080.8         File "setup.py", line 35, in <module>
#20 1080.8           from setuptools import Command, Extension, convert_path, setup
#20 1080.8       ImportError: cannot import name 'convert_path' from 'setuptools' (/tmp/pip-build-env-vso68_9c/overlay/lib/python3.10/site-packages/setuptools/__init__.py)
#20 1080.8       [end of output]
```

Looks unrelated on first glance, but it did start breaking with setuptools 61, so maybe it's not?

**Comment by abravalheri** [comment]
> Not in the pyproject.toml, no. I don't know exactly where to look in the setup.py file, the scikit-fmm package uses `numpy.distutils.misc_util.Configuration` which is hard to grok.

Hi @tobni, the fix that I am considering for this problem is to disable automatic discovery when the ``configuration=...`` parameter is set in ``setup()``. Would that work for you?

If no `packages`, `py_modules`, `ext_modules` and `configuration` are set, then for `setuptools` it will look to setuptools like it is asking for the auto-discovery to quick-in.

I understand that there are situations where the dev wants to have an empty distribution, but that is a breaking change covered in https://setuptools.pypa.io/en/latest/history.html#breaking-changes. The fix for that is to add a `packages=[]`.

**Comment by david-fortini** [comment]
Fixing it, in `setup.py`
```python
setuptools.setup(..,packages=[],..)
```
or
```python
setuptools.setup(..,py_modules=[],..)
```

**Comment by anarcat** [comment]
i have had the same problem in [undertime](https://gitlab.com/anarcat/undertime). suddenly, setuptools starting [failing my CI](https://gitlab.com/anarcat/undertime/-/jobs/2248347682) while everything worked fine literally [an hour earlier](https://gitlab.com/anarcat/undertime/-/jobs/2247069394). this is quite strange because the dependency list didn't change, the container image didn't change, and the commit (on my side) which introduced the problem (according to git bisect) happened [months ago](https://gitlab.com/anarcat/undertime/-/commit/7d1c6e093574742ddf80d2d467a49ae7f1c44bfc).

so i don't understand why this started failing all of  sudden.

i also don't understand the fix: #3211 mentions the `configuration` option, but I can't find documentation on that setting anywhere (and it's kind of hard to search for `configuration` in the documentation, because there's a lot of false positives). it's not documented [here](https://setuptools.pypa.io/en/latest/userguide/keywords.html) or [here](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html) or [here](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html).

in the end, I had to add this line to my `setup.cfg`:

```
[option]
packages =
```

... to, basically, disable autodiscovery. and yes, i have a weird-ish package (it only ships `scripts`) but I don't think it's a particularly strange one.

a little care about backwards compatibility would have been appreciated here. ;)

i hope this hack will be useful for others!

**Comment by abravalheri** [comment]
Hi @anarcat, sorry to hear you are facing problems with your package. 

> 3211 mentions the `configuration` option

`configuration` is something [provided by `numpy.distutils`](https://numpy.org/doc/stable/reference/distutils.html#configuration-class), that is why you cannot find it in `setuptools`.

If you are not using it, the fix to explicitly set either `packages` or `py_modules`. What you have done works well for a package with no Python code on it.

```ini
# setup.cfg
packages = # empty on purpose
# OR setup.py
packages=[]
```

Question: since you have an `undertime.py` wouldn't it be the case that instead of `packages = # nothing` you want to use `py_modules = undertime`?

**Comment by anarcat** [comment]
> Question: since you have an `undertime.py` wouldn't it be the case that instead of `packages = # nothing` you want to use `py_modules = undertime`?

because i want to keep things simple and not use an entry_point because those are traditionally slow.

it's just one script darn it! :)

so i ship it with `scripts = `

**Comment by abravalheri** [comment]
Ok, no problems, I just curious.

**Comment by xkszltl** [comment]
Hit this in numpy as well:
```
#9 529.2 Using pip 22.0.4 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)                                                                                                                                                                        
#9 529.3 Looking in indexes: https://mirrors.aliyun.com/pypi/simple                                                                                                                                                                                           
#9 529.3 Processing ./mirrored-pip-GRCQUK/numpy                                                                                                                                                                                                               
#9 529.5   Installing build dependencies: started                                                                                                                                                                                                             
#9 529.5   Running command pip subprocess to install build dependencies                                                                                                                                                                                       
#9 531.1   Looking in indexes: https://mirrors.aliyun.com/pypi/simple                                                                                                                                                                                         
#9 531.1   Ignoring packaging: markers 'platform_machine == "arm64"' don't match your environment                                                                                                                                                             
#9 531.7   Collecting setuptools==59.2.0                                                                                                                                                                                                                      
#9 531.8     Downloading https://mirrors.aliyun.com/pypi/packages/18/ad/ec41343a49a0371ea40daf37b1ba2c11333cdd121cb378161635d14b9750/setuptools-59.2.0-py3-none-any.whl (952 kB)                                                                              
#9 533.1        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 952.0/952.0 KB 734.9 kB/s eta 0:00:00                                                                                                                                                                   
#9 533.2   Collecting wheel==0.37.0                                                                                                                                                                                                                           
#9 533.2     Downloading https://mirrors.aliyun.com/pypi/packages/04/80/cad93b40262f5d09f6de82adbee452fd43cdff60830b56a74c5930f7e277/wheel-0.37.0-py2.py3-none-any.whl (35 kB)                                                                                
#9 534.0   Collecting Cython<3.0,>=0.29.24                                                                                                                                                                                                                    
#9 534.0     Downloading https://mirrors.aliyun.com/pypi/packages/9a/26/d2b6bc4cb7d716c82ebc89690cbd5ba0f547db364809cd42dad34d593182/Cython-0.29.28-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)                   
#9 536.6        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 761.3 kB/s eta 0:00:00                                                                                                                                                                    
#9 536.9   Installing collected packages: wheel, setuptools, Cython                                                                                                                                                                                           
#9 537.8   Successfully installed Cython-0.29.28 setuptools-59.2.0 wheel-0.37.0                                                                                                                                                                               
#9 537.8   WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv                      
#9 537.9   Installing build dependencies: finished with status 'done'                                                                                                                                                                                         
#9 537.9   Getting requirements to build wheel: started                                                                                                                                                                                                       
#9 537.9   Running command Getting requirements to build wheel                                                                                                                                                                                                
#9 538.3   Running from numpy source directory.                                                                                                                                                                                                               
#9 539.2   error: Multiple top-level packages discovered in a flat-layout: ['numpy', 'branding'].                                                                                                                                                             
#9 539.2                                                                                                                                                                                                                                                      
#9 539.2   To avoid accidental inclusion of unwanted files or directories,                                                                                                                                                                                    
#9 539.2   setuptools will not proceed with this build.                                                                                                                                                                                                       
#9 539.2                                                                                                                                                                                                                                                      
#9 539.2   If you are trying to create a single distribution with multiple packages                                                                                                                                                                           
#9 539.2   on purpose, you should not rely on automatic discovery.                                                                                                                                                                                            
#9 539.2   Instead, consider the following options:                                                                                                                                                                                                           
#9 539.2                                                                                                                                                                                                                                                      
#9 539.2   1. set up custom discovery (`find` directive with `include` or `exclude`)                                                                                                                                                                          
#9 539.2   2. use a `src-layout`                                                                                                                                                                                                                              
#9 539.2   3. explicitly set `py_modules` or `packages` with a list of names                                                                                                                                                                                  
#9 539.2                                                                                                                                                                                                                                                      
#9 539.2   To find more information, look for "package discovery" on setuptools docs.                                                                                                                                                                         
#9 539.3   error: subprocess-exited-with-error                                                                                                                                                                                                                
#9 539.3                                                                                                                                                                                                                                                      
#9 539.3   × Getting requirements to build wheel did not run successfully.                                                                                                                                                                                    
#9 539.3   │ exit code: 1                                                                                                                                                                                                                                     
#9 539.3   ╰─> See above for output.                                                                                                                                                                                                                          
#9 539.3                                                                                                                                                                                                                                                      
#9 539.3   note: This error originates from a subprocess, and is likely not a problem with pip.                                                                                                                                                               
#9 539.3   full command: /usr/bin/python3 /usr/local/lib/python3.9/dist-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpis1s8vl8                                                                                   
#9 539.3   cwd: /tmp/scratch/mirrored-pip-GRCQUK/numpy                                                                                                                                                                                                        
#9 539.3   Getting requirements to build wheel: finished with status 'error'                                                                                                                                                                                  
#9 539.3 error: subprocess-exited-with-error                                                                                                                                                                                                                  
#9 539.3                                                                                                                                                                                                                                                      
#9 539.3 × Getting requirements to build wheel did not run successfully.                                                                                                                                                                                      
#9 539.3 │ exit code: 1                                                                                                                                                                                                                                       
#9 539.3 ╰─> See above for output.                                                                                                                                                                                                                            
#9 539.3                                                                                                                                                                                                                                                      
#9 539.3 note: This error originates from a subprocess, and is likely not a problem with pip.                                                                                                                                                                 
```

OS has setuptools 61.3.1 installed.
Numpy askes for setuptools 59.2.0 inside its build environment but that's probably too late.

**Comment by abravalheri** [comment]
Hi @xkszltl, thanks for reporting this.
What are the commands you are running? Do you have minimal reproduction for that?

**Comment by xkszltl** [comment]
@abravalheri 
See details here:
https://github.com/numpy/numpy/issues/21288

**Comment by abravalheri** [comment]
@xkszltl, I don't seem to be able to replicate this problem inside of a container.
I posted my comments in https://github.com/numpy/numpy/issues/21288#issuecomment-1086866367.

**Comment by ilayn** [comment]
Not that I know what I am doing but I got bitten by this albeit my package is pure python in the attempt of adopting a `pyproject.toml` workflow. https://github.com/ilayn/harold/pull/80 . It started reading into my notebooks folder and getting confused though I don't quite get why it would do that. Should I pin setuptools to something earlier? 

I have to say I am quite lost in this packaging systems and thanks to people mentioning issue numbers in commit messages it is not very easy to follow the discussion above.

**Comment by abravalheri** [comment]
Hi @ilayn, I think what is happening is that you used to have `packages=['harold']` in your `setup.py`, but when updating to `pyproject.toml`, that information got left out[^1]. Setuptools can automatically infer for some scenarios what are the packages, but the `notebooks` folder is confusing for the auto-discovery. Please see more details in https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#flat-layout.

I think there is no need to pin setuptools, only add `packages` to your config. Does that work for you?

[^1]: I am seeing that your project has a `harold/__init__.py` file not a `harold.py`, so `packages` is more appropriate than `py-modules`.

**Comment by ilayn** [comment]
@abravalheri Thank you for your swift response. You are probably right in all that. Let me experiment a bit more.

 I am seriously struggling with understanding all these gotchas. While Python is probably the easiest tool to code, when it comes to packaging every other recommendation online is saying something else about using `toml` or `cfg` or `setup.py` including the official docs. This section for example is telling a lot but really not saying anything https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata

My point is apologies if I came to this issue before I did everything else right and bothering you. Either this stuff requires a much cleaner docs or this tool is getting complicated beyond regular user's understanding.

**Comment by abravalheri** [comment]
@ilayn no problems :)

Packaging in Python is a bit more difficult. I think the easiest for beginners is to use a package generator such as https://pyscaffold.org, https://github.com/ionelmc/cookiecutter-pylibrary or any other generator that you find suitable for your needs[^1].

[^1]: Sure, these generators might be a bit behind in terms of the `[project]` table inside `pyproject.toml`, but you don't need to rush to implement it right now...

**Comment by bersbersbers** [comment]
> one way to disable auto discovery is to explicitly set `py_modules=[]` in `setup.py` or `py-modules = []` in `pyproject.toml [tool.setuptools]`.

I may have misunderstood that workaround - @abravalheri, do you mean to literally write an empty list for `py-modules`? I tried it out, and while packages using that workaround are successfully installed, I cannot seem to import their modules (unless my working directory is the project directory, in which case installation is not required anyway).

Or was your recommended workaround to populate `py-modules` with the actual list of module names?

**Comment by abravalheri** [comment]
@bersbersbers the context for that is a distribution that does not contain any Python packages or modules.

If your project contains those, probably the best advice is to follow one of the suggestions in the error message.
