### ISSUE TITLE
Projects that contain `pyproject.toml` not compliant with standards are failing on v61.

### ISSUE THREAD

**Issue by deepika094** [pypa/setuptools#3199]
Hi,
We have been using pyproject.toml file in setup.py and when we build using setup.py sdist bdist_wheel it was always working. Suddenly it started complaining today-

/pyprojecttoml.py:100: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
[05:42:53]	[Step 3/5]   warnings.warn(msg, _ExperimentalProjectMetadata)
[05:42:53]	[Step 3/5] ERROR:setuptools.config.pyprojecttoml:configuration error: `project` must not contain {'python_requires'} properties
ValueError: invalid pyproject.toml config: `project`

**Comment by abravalheri** [comment]
Hi @deepika094, thank you very much for reporting this.

According to https://peps.python.org/pep-0621/#requires-python, the valid field for `pyproject.toml` is `requires-python` instead of `python_requires`. Would the build work if that change is made?

**Comment by deepika094** [comment]
let me try

**Comment by phillipsmjordan** [comment]
In the `pikepdf` project, `requires-python` is used, but it still fails because `[project]` doesn't have a `name` value apparently.

**Comment by deepika094** [comment]
> Hi @deepika094, thank you very much for reporting this.
> 
> According to https://peps.python.org/pep-0621/#requires-python, the valid field for `pyproject.toml` is `requires-python` instead of `python_requires`. Would the build work if that change is made?

yes it works but that would mean we will have to make changes to lots of our projects. I see that pep-0621 guidelines were not changed recently.. its same from 22-Jun-2020 but yet this was working before with setuptools <=60.10.0 however failed with new setuptools version. Is it possible to keep supporting python_requires as well with new version of setuptools?

**Comment by abravalheri** [comment]
I am sorry for the disruption @deepika094, I am trying to think in a alternative here...

I have a doubt here. Is there a tool using the value of `[project] python_requires` that you are relying on?
It would be good to understand that and also to know which version of PEP 621 such tools are using.

**Comment by deepika094** [comment]
@abravalheri  in setup.py of all our projects we have this-

setup(
    name=pyproject_toml['project']['name'],
    version=_determine_version(),
    python_requires=pyproject_toml['project']['python_requires'],
    packages=find_namespace_packages(where='src'),
    package_dir={'': 'src'},
    package_data={'': ['*.json','*.yaml', '*.csv']},
    install_requires=requires,
...

So we have been using python_requires from [project ] . We read the value of version from toml file and use that  python version to deploy with the application. we create the virtual env and then run setup.py sdist bdist_wheel to create .whl.

**Comment by abravalheri** [comment]
Hi @sabuhish thank you very much for reporting this.
I think this is related to the second part of the discussion: PEP 621 has some mandatory fields and it is kind of adamant about it:


https://peps.python.org/pep-0621/#dynamic
```
A build back-end MUST raise an error if the metadata specifies the name in dynamic.
If the [core metadata](https://packaging.python.org/specifications/core-metadata/) specification lists a field as “Required”, then the metadata MUST specify the field statically or list it in dynamic (build back-ends MUST raise an error otherwise, i.e. it should not be possible for a required field to not be listed somehow in the [project] table).
```

@sabuhish, @deepika094 would it help if setuptools detect an environment variable like `SETUPTOOLS_SKIP_PYPROJECT` and completely skip processing `pyproject.toml`?

**Comment by deepika094** [comment]
@abravalheri  we don't want to skip processing pyproject.toml. We are using it as I mentioned.
[project] 
name = "***"
python_requires = ">=3.7" #Python version

[build-system]
requires = [
    "setuptools >= 46.1.0",
    "wheel",
    "toml"
]
build-backend = "setuptools.build_meta"

Is it possible to keep supporting python_requires and requires-python both as it was till  setuptools 60.10.0? or with new upgrade of setuptools its intentional to stop supporting python_requires based on pep621 ?

**Comment by abravalheri** [comment]
> I have a doubt here. Is there a tool using the value of `[project] python_requires` that you are relying on?
> It would be good to understand that and also to know which version of PEP 621 such tools are using.

Ok so it seems that a lot of projects have a barely empty `[project]` with only `python_requires/requires-python` to use dependabot... Is that the case?

Since it is a common pattern, I can add a temporary exception for that (which is likely to be removed in the future).

**Comment by abravalheri** [comment]
No unfortunately I cannot implement the plan I suggested above, it will break a lot of other parts.

---

> we don't want to skip processing pyproject.toml. We are using it as I mentioned. I am not sure what all will it impact with this env variable ..

@deepika094, the only side-effect of that approach would be that setuptools itself will not use the `pyproject.toml` and still rely on the other classic files `setup.py`, `setup.cfg`. Your own scripts and all the other tools will still use it...

**Comment by abravalheri** [comment]
Update: it seems that the tool that is accidentally influencing users to add an almost empty `[project]` table with just `requires-python` is cbuildwheel via https://cibuildwheel.readthedocs.io/en/stable/options/#requires-python

**Comment by popescualex18** [comment]
Does it depends on the vmImage you are using?

**Comment by abravalheri** [comment]
Hi @popescualex18, I am not sure if I understood your question. Are you trying to install a specific package (please note that I don't have a computer with macOS in hand, so I am afraid cannot reproduce any macOS specific behaviour).
