### ISSUE TITLE
[Docs] Fix typo in quickstart section 

### ISSUE THREAD

**Issue by pablo-cardenas** [pypa/setuptools#3216]
### Summary

Hi,
There is a typo in the [Entry points and automatic script creation section](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#entry-points-and-automatic-script-creation), In the **pyproject.toml (EXPERIMENTAL)** tab.

```
[project.scripts]
cli-name = mypkg.mymodule:some_func
```

When I run that, I get
```
ERROR Failed to parse /home/user/project-path/pyproject.toml: Invalid value (at line 13, column 10) 
```

I think that the function should be between quotes like a string

```
cli-name = mypkg.mymodule:some_func    =>    cli-name = "mypkg.mymodule:some_func"
```

Thanks!

### OS / Environment

Archlinux, Firefox

### Additional Information

Fix a typo in documentation. Readers won't get an error when following the documentation.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Thank you very much @pablo-cardenas for spotting this error. Would you like to provide a PR? I think you can do it quickly via the `pencil` icon on top of the page 😄.

**Comment by pablo-cardenas** [comment]
Sure!
