### ISSUE TITLE
[BUG] module 'distutils.sysconfig' has no attribute '_init_posix'

### ISSUE THREAD

**Issue by arossert** [pypa/setuptools#3220]
### setuptools version

setuptools==61.x.x

### Python version

Python 3.8.10

### OS

Linux (probably all)

### Description

This is the error I'm getting when installing `pcapy`
```
Collecting pcapy
  Using cached pcapy-0.11.4.tar.gz (37 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3hwz7mz1/pcapy_78572af867a84aadad6f1c4be2d457c3/setup.py", line 49, in <module>
          save_init_posix = sysconfig._init_posix
      AttributeError: module 'distutils.sysconfig' has no attribute '_init_posix'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Expected behavior

Reverting to setuptools==60.x.x fixed this issue

### How to Reproduce

1. Install setuptools==61.x.x
2. pip install pcapy

### Output

```
Collecting pcapy
  Using cached pcapy-0.11.4.tar.gz (37 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3hwz7mz1/pcapy_78572af867a84aadad6f1c4be2d457c3/setup.py", line 49, in <module>
          save_init_posix = sysconfig._init_posix
      AttributeError: module 'distutils.sysconfig' has no attribute '_init_posix'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by abravalheri** [comment]
Hi @arossert, thank you very much for reporting this issue.

I think the reasons why it is occurring is the same one as the one reported in #3219, i.e. we recently updated the version of the bundled pypa/distutils library.

There is a catch however, the `setup.py` script is clearly trying to access a private attribute from `distutils.sysconfig`, so I cannot really classify this is a bug. Internal APIs are fragile and are not guaranteed to change overtime.

Is there any chance you can have a look on the updated implementation and check if you can modify your package accordingly? Otherwise I suggest you to open a ticket in pypa/distutils and discuss a possible solution for your use case there.

**Comment by abravalheri** [comment]
(Sorry, if you are not a maintainer of pcapy, I suggest discussing the alternatives with them instead of distutils)

**Comment by arossert** [comment]
@abravalheri Thank you for the detailed response, I notice that they used an internal function in the setup, I will try to contact `distutils` since I doubt that `pcapy` will release a fix (the latest commit was at 2019).

**Comment by abravalheri** [comment]
I see that it was fixed in the fork. Thank you very much for coordinating that @arossert. I will go ahead and close this issue.
