### ISSUE TITLE
Move `_validate_pyproject` out of `_vendor`

### ISSUE THREAD

**Issue by abravalheri** [pypa/setuptools#3225]
`_validate_pyproject` is not a vendored version of `validate_pyproject`. Instead it consists of new code generated from the JSON Schema files.

To help OS re-packagers it would be best to move them out of `_vendor`.

----
Context:

I think moving `_validate_pyproject` out of `_vendor` would also help us after all. Out unbundling logic is pretty much two regexps and while I suppose we could hack it around to exclude `_validate_pyproject`, it would be much easier if we didn't have to.

_Originally posted by @mgorny in https://github.com/pypa/setuptools/issues/2825#issuecomment-1079633713_

**Comment by mgorny** [comment]
For the record, setuptools has some `extern` logic that's also affected by this, I think.
