### ISSUE TITLE
[BUG] package-data in pyproject.toml not honored but same config in setup.py works

### ISSUE THREAD

**Issue by MatthieuDartiailh** [pypa/setuptools#3238]
### setuptools version

61.3.0

### Python version

3.9

### OS

Windows

### Description

Installing the main branch of https://github.com/nucleic/enaml fails to install the package-data. Moving the package-data specification from pyproject.toml to setup.py however works. This means i.e. removing the section from pyproject.toml and adding the following to setup.py
```python
package_data={
        'enaml.applib': ['*.enaml'],
        'enaml.stdlib': ['*.enaml'],
        'enaml.workbench.core': ['*.enaml'],
        'enaml.workbench.ui': ['*.enaml'],
        'enaml.qt.docking': [
            'dock_images/*.png',
            'dock_images/*.py',
            'enaml_dock_resources.qrc'
        ],
    },
```

### Expected behavior

I would expect both configurations to be fully equivalent.

### How to Reproduce

Run `pip install git+https://github.com/nucleic/enaml@main` 

### Output

Inspect the installed package in particular enaml stdlib which should contain several .enaml files but does not.

**Comment by abravalheri** [comment]
Hi @MatthieuDartiailh, thank you very much for reporting this.

I noticed that you have in the `pyproject.toml` `[tools.setuptools.package-data]`.
I am under the impression that the following would be required:
```diff
- [tools.setuptools.package-data]
+ [tool.setuptools.package-data]
```

Note the `tools => tool` differnce.

Does this work for you?

**Comment by MatthieuDartiailh** [comment]
Nice catch... I do feel quite stupid right now... Thanks for your help and sorry for the noise

**Comment by abravalheri** [comment]
No problems @MatthieuDartiailh 😄
(This kind of small confusion happens all the time for everyone)

Glad to know it works now!
