### ISSUE TITLE
Console script in windows can't take non ascii arguments

### ISSUE THREAD

**Issue by Deshdeepak1** [pypa/setuptools#3271]
In this case, maybe it is worthy to file this issue against pip.

To keep things cross platform, the script wrappers are not included in the wheel or sdist created by setuptools.

Instead, pip creates the script wrappers for console_scripts during the installation (with the help of distlib)[^1].

[^1]: Unless you are using the `-e` option .

_Originally posted by @abravalheri in https://github.com/pypa/setuptools/issues/3268#issuecomment-1099924217_

**Comment by abravalheri** [comment]
This is a duplication of #3268 right?
