### ISSUE TITLE
[BUG] dead link in "bad install directory or PYTHONPATH" error/warning message

### ISSUE THREAD

**Issue by alanfmw** [pypa/setuptools#3283]
### setuptools version

49.2.1

### Python version

3.10

### OS

Windows

### Description

Executing `python setup.py install --prefix=<path>`, when `<path>` is not in `PYTHONPATH` and is not a site dir, displays a "bad install directory or PYTHONPATH" message with a dead link: 

https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations

### Expected behavior

The link should be valid, or should not be displayed at all. 

### How to Reproduce

Execute `python setup.py install --prefix=<dir>` where `<dir>` is not in `PYTHONPATH` and is not a site dir.

### Output

In the following, I have replaced actual paths with `<path>`, `<path1>`, and `<path2>`.

```console
'From setuptools
 running build
 running build_py
 creating <path>
 creating <path>
 copying <path1> -> <path2>
 warning: build_py: byte-compiling is disabled, skipping.
 
 running install
 Checking .pth file support in <path>
 <path>\pythonw.exe -E -c pass
 TEST FAILED: <path>\Lib\site-packages\ does NOT support .pth files
 bad install directory or PYTHONPATH
 
 You are attempting to install a package to a directory that is not
 on PYTHONPATH and which Python does not read ".pth" files from.  The
 installation directory you specified (via --install-dir, --prefix, or
 the distutils default setting) was:
 
     <path>\Lib\site-packages\
 
 and your PYTHONPATH environment variable currently contains:
 
     ''
 
 Here are some of your options for correcting the problem:
 
 * You can choose a different installation directory, i.e., one that is
   on PYTHONPATH or supports .pth files
 
 * You can add the installation directory to the PYTHONPATH environment
   variable.  (It must then also be on PYTHONPATH whenever you run
   Python and want to use the package(s) you are installing.)
 
 * You can set up the installation directory to support ".pth" files by
   using one of the approaches described here:
 
   https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations
 
 
 Please make the appropriate changes for your system and try again.
```

**Comment by abravalheri** [comment]
Hi @alanfmw, thank you very much for reporting this problem.

The link was moved to https://setuptools.pypa.io/en/latest/deprecated/easy_install.html#custom-installation-locations because `python setup.py install` and `easy_install` are both deprecated now.

I think we can go with your suggestion of removing the link. Would you like to give it a try and submit a PR?

**Comment by abravalheri** [comment]
Sorry for the confusion, I mean any of the two sounds good to me.

**Comment by alanfmw** [comment]
It looks like the code was changed five months ago:

https://github.com/pypa/setuptools/commit/a65c4326c788cd9f6a81eb1754029751500f7721

Perhaps the version of setuptools that I'm using doesn't reflect the change.

**Comment by abravalheri** [comment]
I see!
Yes it does look like the link was changed to the updated URL.
Should we close this issue then?
