### ISSUE TITLE
[Docs]  Missing requires-python in "using pyproject.toml"

### ISSUE THREAD

**Issue by xsc27** [pypa/setuptools#3305]
### Summary

The field `requires-python` is undocumented on:
- https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
- https://github.com/pypa/setuptools/blob/main/docs/userguide/pyproject_config.rst

### OS / Environment

n/a

### Additional Information

n/a

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @xsc27, thank you very much for reporting this.

The linked document does not exhaustively list all the fields covered in the PEP 621 specification, instead it points out the following:

> The project table contains metadata fields as described by [Declaring project metadata](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/) guide.

Although we can argue that this is not the best approach, it at least prevents setuptools docs from drifting away when the standard changes[^1].

What are the changes you are suggesting?
Would you like to submit a PR to improve this documentation?

[^1]: The standards involving `pyproject.toml` are "living standards" and can be modified when the community reaches consensus about a particular topic or when a new PEP is approved.

**Comment by jacalata** [comment]
How about adding a comment line in the example toml file at about line 66, like this?
```
   # other project metadata fields as specified in PEP 621
```

**Comment by abravalheri** [comment]
Yeah, that sounds great. We can also add the requires-python to the example.

Would you like to submit a PR?
