### ISSUE TITLE
[FR] different requirements for different python versions 

### ISSUE THREAD

**Issue by se7enXF** [pypa/setuptools#3313]
### What's the problem this feature will solve?

I need to setup different requirements for different python versions in setup.py. Like [this issue](https://github.com/pypa/pipenv/issues/2171)  say. Python 3.7 includes the package contexvars, but Python3.6 does not. I want to install contexvars in setup.py when using Python3.6, but not in Python3.7. How do I make it happen？

### Describe the solution you'd like

The arg 'requires' in function setup() could be extended, accept not only List[str] but also List[dict('python version requires': List['package 1', 'package 2'])]. For example: 
```python
# base
setup(
    ...,
    requires=['contextvars']
)

# extend
setup(
    ...,
    requires=[
        {'3.6': ['contextvars']},
        {'>=3.7': []}
    ]
)
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
I believe this covers the functionality you are after, right?

**Comment by se7enXF** [comment]
@abravalheri Thanks for reply. I tried the follow: 

```python
setup(
    ...,
    python_requires = '>=3.6'
    install_requires = [
        'contextvars; python_version == "3.6"',
    ]
)
```

Then `python setup.py sdist` processed fine. But ModuleNotFoundError still raise in Python3.6 env when `pip install [my package]`. 

I also find another issue. Code as follow:  

```python
setup(
    ...,
    python_requires = '>=3.7',
)
```
Still, `python setup.py sdist` processed fine. But ModuleNotFoundError  still raise in Python3.6 env when `pip install [my package]`. 
Shouldn't the installation in a 3.6 environment indicate that the version is not supported, and then not be able to continue the installation?

It seems that the keywords `python_requires` and `install_requires` are not working. I check the setuptools source code in my python3.7 lib, and find that `python_requires` and `install_requires` are not in displayed specified parameters. It's too disturbing. 
My build env is python3.7 with setuptools62.2.0, test python3.6 env with setuptools59.6.0.

**Comment by abravalheri** [comment]
Hi @se7enXF, do you have an example to share? (It does not have to be your final project if that is private, just a toy example that emulates the problems you are having). I am trying to understand what you are doing.

If would have to guess, there might be a confusion with the different stages of the process.
The configurations for `install_requires` and `python_requires` are analysed during the installation phase, not during the build. Effectively they are metadata that only inform `pip` about runtime dependencies (this means that you cannot rely on them existing when your `setup.py` runs, for example).

I tried to create a very simplified diagram bellow[^1]:

```mermaid
graph LR
    src[fa:fa-laptop-code source code] --> b1(fa:fa-hammer)
    
    subgraph build process
      b1 --> sdist(fa:fa-file-code sdist) --> b2(fa:fa-hammer)
      b2 --> wheel(fa:fa-box wheel)
       
      build([build dependencies]) --> b1
      build([build dependencies]) --> b2
    end

    subgraph installation process
        wheel --> pkg
        pkg(fa:fa-box-open) --> inst[fa:fa-python installed packages]
        runtime([runtime dependencies]) --> inst
    end

    classDef deps fill:#2aa198,stroke:#333
    classDef env fill:#6c71c4,stroke:#333
    build:::deps
    runtime:::deps
```

Note that if you try to run `pip install` with an `sdist` (or from the source code), `pip` will run the relevant phases of the build process before proceeding with the installation process.

Based on your description, it would seem to me that some dependency is missing when creating the `wheel` file (which is the artefact that immediately precedes the installation). But I cannot be sure about that without having a look on the code or trying to run it myself...

---
Somethings that may help:

1. If you are not using a `pyproject.toml` file, you may consider adding one to your project. You can specify "build dependencies" on this file (in `[build-system] requires`), there is a very minimal example in our [docs](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use).
2. If you are already using `pyproject.toml`, you might consider populating `[build-system] requires` with any "build dependency".
3. Note that when you add a `pyproject.toml` with `build-backend = "setuptools.build_meta"`, your project directory is **not** automatically added to `sys.path`. This is a purposeful design choice.

---
Please ignore the `.egg-info` folder for now, this is an internal implementation detail and might not make sense without a very deep understanding on how setuptools and distutils work.

---

[^1]: The "build process" creates distribution artifacts/packages. `sdist` distributions are meant to be platform independent (but may contain varying levels of optimisation - e.g. compiling Python to C via Cython). `wheel` distributions contain the final files meant to be directly copied to the user's machine, and therefore may be platform specific.

**Comment by se7enXF** [comment]
Hi @abravalheri. I upload my code at [this repo](https://github.com/se7enXF/LogTrace). For some  private reasons, I delete function context, and only you can see the repo.    

I just want to build a package for team using. Some details:  
- The `contexvars` is needed.  
- Some one in my team is using python3.6 and most are using python3.7+. So Python 3.6 need to install `contextvars` but 3.7 not. 
- This package is used not only on windows but also on linux. That's why I use `python setup.py sdist` for build. 
- I build and push the package to private pypi repository by `python setup.py sdist upload -r local` in python3.7
- I install the package by `pip install package-name -i package-pypi`. Python3.7 installing is fine but 3.6 raise error I mentioned before. 
- I just use setup.py for build, no pyproject.toml or setup.cfg. 

Thank you again for your kind and detailed answers.

**Comment by abravalheri** [comment]
Thank you very much @se7enXF. I can see what is happening now.

I turns out that when you do `from <yourpkg> import *` inside the `setup.py` script you are effectively (also) turning all your runtime dependencies into build dependencies.

If you don't want to change anything on how your code is currently organised and how your `setup.py` script is currently written, adding the following should fix your dependency problems:

```toml
# pyproject.toml at the root of the repository
[build-system]
build-backend = "setuptools.build_meta:__legacy__"
requires = [
    "setuptools",
    "contextvars; python_version == '3.6'",
]
```

Please note, however, that this solution will require double bookkeeping of the `install_requires` in `setup.py` and `[build-system] requires` in `pyproject.toml`.

---

Regarding `python_requires`,  `pip` will compare the specified with the version of Python that is being used. If they are not compatible, `pip` will then try to install an older version of the package available in the package index. If that previously published version has a problem in the `setup.py` the user will see an error anyway... If `pip` cannot find any previous version compatible with `python_requires` the whole installation will fail because no distribution is found.

---

If you are importing your project inside `setup.py` just to have access to some metadata such as `__version__`, `__name__`, `__url__`, etc, you might consider doing the other way around, i.e. defining the `setup.py` (or `setup.cfg` or `pyproject.toml`) and using [`importlib-metadata`](https://importlib-metadata.readthedocs.io/en/latest/) to read the package information in runtime to fill out attributes.

**Comment by abravalheri** [comment]
@se7enXF, if your package is 100% Python, you should be able to create wheels that work for both Windows and Linux. That might also help.

Regardless, I think we can close this issue now, since it is not a problem with setuptools, but instead the lack of some `pyproject.toml` configuration...

**Comment by se7enXF** [comment]
Hi @abravalheri. Based on the advice you provided, this problem is solved. Thank you very much!
