### ISSUE TITLE
[BUG] Dotfiles are not included as packaga_data unless explicitly listed

### ISSUE THREAD

**Issue by comabrewer** [pypa/setuptools#3350]
### setuptools version

setuptools==62.3.3

### Python version

Python 3.9

### OS

Windows

### Description

Dotfiles (files with a leading `.` like `.gitignore`) are not packaged as datafiles unless they are explicitly listed.

So this all works for all non-dotfiles:
```ini
[options.package_data]
* = data/**
```

Or explicitly listing all levels (single-star):
```ini
[options.package_data]
* = 
  data/*
  data/*/*
```

But dotfiles have to be added explicitly:
```ini
[options.package_data]
* = 
  data/**
  data/.data.txt
```
Or with a special pattern with leading dot in the filename:
```ini
[options.package_data]
* = 
  data/**
  data/**/.*
```

### Expected behavior

If I specify patterns for `package_data` (either via single-star or the new double-star glob patterns), I would expect all files to be included.

### How to Reproduce

I have the following project structure:
```
example/
  src/
    example/
      data/
        data.txt
        .data.txt
      __init__.py
  pyproject.toml
  setup.cfg
```

With the following setup.cfg:
```ini
[metadata]
name = example
version = 0.0.0

[options]
package_dir =
    = src
packages = find:

[options.packages.find]
where = src

[options.package_data]
* = data/**
```

Inside a virtual environment, I install the package and list the contents:

```sh
rm -r build/
pip install .
ls -al .venv/Lib/site-packages/example/data
```

### Output

Only `data.txt` is contained, but not `.data.txt`:
```console
data.txt
```

**Comment by comabrewer** [comment]
Apparently setuptools uses `glob.glob` from the standard library. The observed behavior stems directly from `glob` and can be reproduced with `import glob; for p in glob.glob("*"): print(p)`.

The [Python documentation]() states that:
>If the directory contains files starting with . they won’t be matched by default. 

So if the behavior is only a surprise to me, please feel free to immediately close the issue.

Otherwise it might make sense to document the behavior in the setuptools docs on data files? The [section on exclude lists](https://setuptools.pypa.io/en/latest/userguide/datafiles.html#exclude-package-data) talks about excluding dotfiles, this might have lead to my imrepssion that they were captured by patterns automatically.

**Comment by abravalheri** [comment]
@comabrewer, this behaviour is not exclusive to Python. In general glob patterns have this behaviour everywhere. For example, in your behaviour you can try:
```console
$ ls -a src/example/data/*
src/example/data/data.txt
```
So I think for the time being we can close this issue.

Would you like to submit a PR with the suggested changes for the docs? That would be very useful.

**Comment by comabrewer** [comment]
@abravalheri thank you very much for your responses (which I saw just after my previous comment).
From my understanding I would also have expected `find_namespace` to be necessary, but it also seems to work correctly with `find:`. Anyway I will adapt the corresponding line.

Regarding the glob pattern I totally agree that it was because of my lack of understanding, sorry for that.
I would be glad to clarify this in the docs, if you feel that it adds value. Should I also mention the newly added support for recursive patterns, which isn't mentioned yet?

In any case many thanks for your great work on improving setuptools! It has become a real pleasure to use, with many long desired features being added lately.

**Comment by abravalheri** [comment]
Thank you very much for the kind words @comabrewer.

> From my understanding I would also have expected find_namespace to be necessary, but it also seems to work correctly with find:. Anyway I will adapt the corresponding line.

I will work for this particular example, but it is a bit clumsy (Python does not have the concept of a "data" directory... all directories are considered packages, so I am trying to get people to embrace that mindset).

I have mixed feelings about the `**` pattern to be sincere. It might be useful, but there is a change it can cause inconsistencies in the case of `[options.packages.find] exclude` (maybe we should add a note about that?).

**Comment by comabrewer** [comment]
As an additional remark, pathlib works differently, at least on Windows:
```py
from pathlib import Path

for p in Path.home().glob("*"): 
   print(p)
```
Also shows files starting in `.`

This behavior comes from `fnmatch`:
```py
from fnmatch import fnmatch
assert fnmatch(".gitignore", "*") is True
```

**Comment by abravalheri** [comment]
Ouch, I was not expecting from this difference...
