### ISSUE TITLE
[Docs] Provide fuller explanation of package_dir semantics

### ISSUE THREAD

**Issue by cdfarrow** [pypa/setuptools#3357]
### Summary

Overall, I'm impressed with the comprehensiveness of the setuptools and packaging documentation. However, I've been having a hard time understanding how `package_dir` works, and I've made some suggestions on [docs.python.org](https://github.com/python/cpython/issues/93666).

The setuptools [glossary](https://setuptools.pypa.io/en/latest/references/keywords.html) has a very minimal definition, which is not very helpful for new-comers: 
>A dictionary providing a mapping of package to directory names.

I suggest expanding it, along the lines of my suggestion in the issue above. 

One challenge I've had (as a newbie) is the overloading of the term 'package'. There are Python packages (defined with __init__.py files), and also [distribution packages](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#packages). Those distribution packages (such as a wheel) get installed into a site-packages directory where you get an installed Python package, which may have a different directory structure to that in the source directory tree.

`package_dir` is mapping source directories (Python packages + extra data/docs/etc.) onto directories (i.e. installed package names) in the wheel and hence the final site-packages directory. This means that in examples like
```
package_dir =
    mypkg = mypkg
```
the two strings 'mypkg' are actually referring to very different things. The first one is the directory name that will be created under site-packages (and hence imported with `import mypkg`), while the second one is referring to the source directory for the Python package, and thus the location of the files that will be copied into that mypkg installation.

I haven't seen the information in the previous paragraph expanded like that anywhere, and I think it would be helpful to have more information about how `package_dir` and other configuration parameters actually translate to the installation directory structure (i.e. structure inside the wheel). 

See also my question on the [discussion board](https://github.com/pypa/setuptools/discussions/3353) for more background.

### Additional Information

.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @cdfarrow, please let me know if this issue can be solved by #3357.

**Comment by cdfarrow** [comment]
Looks great. Thanks so much. I've added some small suggestions to the PR.
