### ISSUE TITLE
[FR] egg_info.writers on current installing package only

### ISSUE THREAD

**Issue by rayzchen** [pypa/setuptools#3360]
### What's the problem this feature will solve?

I want to add some package metadata into .egg-info by using egg_info.writers. However, that only affects future installations and not the current one.

### Describe the solution you'd like

Temporarily add a function to the `egg_info.writers` group before `setup()` is called.

### Alternative Solutions

I tried using other packages for custom metadata but none of them seem to work very well.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @rayzchen, thank you very much for the input.

I think this can be broadly categorized under the same umbrella as https://github.com/pypa/setuptools/issues/2900 right? I.e.: a way of using the entry-points for the build of the package itself.

**Comment by rayzchen** [comment]
I also want to avoid #2346 (aka only run the hook on the current package and not subsequent installs).

**Comment by abravalheri** [comment]
> I also want to avoid #2346 (ie only run the hook on the current package and not subsequent installs).

If we go for something like `entry_points_for_build` that I proposed in #2900, the idea is that the entry-points would be valid *only* for the build of the project itself and not available after it is installed...

If we also change [`build_meta`](https://github.com/pypa/setuptools/blob/fbe659b74cbccbb095dd469a15324eb73285b714/setuptools/build_meta.py#L166-L167) implementation to re-use the generated `egg-info`/`dist-info` directory between the hooks specified by PEP 518, we can avoid re-running the hook multiple times (and therefore overwriting the generated files).

I am very keen on implementing something towards this future, however it may take some time until we arrive there... (limited bandwidth 😝 + I am waiting for the feedback of the other setuptools maintainers on #2900).

**Comment by rayzchen** [comment]
I'd like the hook to be run every build so that it always refreshes in case something changes too, but #2900 does seem applicable.

**Comment by abravalheri** [comment]
Thank you very much Ray, let's consolidate this FR in 2900.
