### ISSUE TITLE
Sage CI failing in makefile loop

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#3389]
Sometime in the past month, the Sage CI builds have started failing:

![image](https://user-images.githubusercontent.com/308610/174441711-2bac4aba-35e1-4b9e-b092-368ce5bc608d.png)

Looking at them briefly, I see what looks like infinite recursion in make logic.

![image](https://user-images.githubusercontent.com/308610/174441750-80dc8c8f-10e4-4be1-8d0e-d92995877497.png)

@mkoeppe Can you investigate?

**Comment by mkoeppe** [comment]
Fixed by https://trac.sagemath.org/ticket/34017 via https://trac.sagemath.org/ticket/33288

**Comment by abravalheri** [comment]
Thank you very much @mkoeppe.

The tests run yesterday night again, but it seems that there is still something missing: https://github.com/pypa/setuptools/actions/runs/2524939058.

Do we need to change any workflow configuration to make the latest changes in the sagemath repository take effect?

**Comment by mkoeppe** [comment]
In Sage we dropped support for gcc < 6.3. I'll send a PR that updates the system configurations tested.
