### ISSUE TITLE
[BUG] Empty setup.py/cfg is not sufficient for editable installs to work with pyproject.toml/PEP 621

### ISSUE THREAD

**Issue by marktsuchida** [pypa/setuptools#3390]
### setuptools version

setuptools==62.5.0

### Python version

Python 3.9.13

### OS

macOS

### Description

The documentation [notes](https://github.com/pypa/setuptools/blob/9c7163bc6030e546ba1133de823d0b4ac06a02d9/docs/userguide/pyproject_config.rst) that "pip still might require a setup.py file to support editable installs" and shows an example `setup.py` with no configuration.

However, when the package is not in flat-layout (in my case it is in src-layout), having a minimal `setup.py` or empty `setup.cfg` is not enough: `pip install -e .` will install an `egg-link` to the project root directory, which is not where the package is.

The workaround of keeping a `setup.cfg` with this minimal config (and no `setup.py`) appears to work:
```ini
[options]
packages =
    my_package
package_dir =
    = src
```

### Expected behavior

Either the documented method should work, or the documentation should include the additional necessary workaround.

### How to Reproduce

Create a package with the Python source under `src/` and with `pyproject.toml` containing package metadata.
Add an empty `setup.cfg` or minimal `setup.py` with no settings.
Perform an editable install with `pip`.
Attempt to import the installed package; this will fail.
Inspect the installed `.egg-link` file; it points to the root directory, whereas it should point to `src`.

### Output

Setup:

```console
$ mkdir my-package
$ cd my-package
$ mkdir -p src/my_package
$ touch src/my_package/__init__.py
$ cat >pyproject.toml <<EOF
+ [build-system]
+ requires = ["setuptools>=42"]
+ build-backend = "setuptools.build_meta"
+
+ [project]
+ name = "my-package"
+ version = "0.1.0"
+
+ [tool.setuptools]
+ packages = ["my_package"]
+ package-dir = {my_package = "src/my_package"}
+ EOF
$ python -m venv venv
$ . venv/bin/activate
```

I edited out the `(venv) ` from the shell prompt from here on so that highlighting works; otherwise all text is a direct paste.

```console
$ pip install -U pip setuptools
Requirement already satisfied: pip in ./venv/lib/python3.9/site-packages (22.1.1)
Collecting pip
  Using cached pip-22.1.2-py3-none-any.whl (2.1 MB)
Requirement already satisfied: setuptools in ./venv/lib/python3.9/site-packages (62.3.2)
Collecting setuptools
  Using cached setuptools-62.5.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 62.3.2
    Uninstalling setuptools-62.3.2:
      Successfully uninstalled setuptools-62.3.2
  Attempting uninstall: pip
    Found existing installation: pip 22.1.1
    Uninstalling pip-22.1.1:
      Successfully uninstalled pip-22.1.1
Successfully installed pip-22.1.2 setuptools-62.5.0
```

Test 1: no `setup.py` or `setup.cfg`; expecting failure:
```console
$ pip install -e .
Obtaining file:///private/tmp/my-package
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
ERROR: Project file:///private/tmp/my-package has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
```

Test 2: empty `setup.cfg`:
```console
$ touch setup.cfg
$ pip install -e .
Obtaining file:///private/tmp/my-package
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Installing collected packages: my-package
  Running setup.py develop for my-package
Successfully installed my-package-0.1.0
$ cat venv/lib/python3.9/site-packages/my-package.egg-link
/private/tmp/my-package
.$ python -m my_package
/private/tmp/my-package/venv/bin/python3: No module named my_package
```
Import fails due to egg-link pointing to wrong directory.

```console
$ pip uninstall my-package
Found existing installation: my-package 0.1.0
Uninstalling my-package-0.1.0:
  Would remove:
    /private/tmp/my-package/venv/lib/python3.9/site-packages/my-package.egg-link
Proceed (Y/n)?
  Successfully uninstalled my-package-0.1.0
$ rm setup.cfg
```

Test 3: minimal `setup.py`:
```console
$ cat >setup.py <<EOF
+ from setuptools import setup
+ setup()
+ EOF
$ pip install -e .
Obtaining file:///private/tmp/my-package
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Installing collected packages: my-package
  Running setup.py develop for my-package
Successfully installed my-package-0.1.0
$ cat venv/lib/python3.9/site-packages/my-package.egg-link
/private/tmp/my-package
.$ python -m my_package
/private/tmp/my-package/venv/bin/python3: No module named my_package
```
Import fails due to egg-link pointing to wrong directory.

```console
$ pip uninstall my-package
Found existing installation: my-package 0.1.0
Uninstalling my-package-0.1.0:
  Would remove:
    /private/tmp/my-package/venv/lib/python3.9/site-packages/my-package.egg-link
Proceed (Y/n)?
  Successfully uninstalled my-package-0.1.0
$ rm setup.py
```

Test 4: `setup.cfg` with package directory workaround:
```console
$ cat >setup.cfg <<EOF
+ [options]
+ packages =
+     my_package
+ package_dir =
+     = src
+ EOF
$ pip install -e .
Obtaining file:///private/tmp/my-package
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Installing collected packages: my-package
  Running setup.py develop for my-package
Successfully installed my-package-0.1.0
$ cat venv/lib/python3.9/site-packages/my-package.egg-link
/private/tmp/my-package/src
../$ python -m my_package
/private/tmp/my-package/venv/bin/python3: No module named my_package.__main__; 'my_package' is a package and cannot be directly executed
$ python
Python 3.9.13 (main, May 24 2022, 21:13:51)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import my_package
>>>
$
```
This worked. The egg-link correctly points to the `src` directory.

**Comment by abravalheri** [comment]
Hi @marktsuchida thank you for reporting this.

I will try to have a look as soon as possible, but probably I will only have access to a desktop computer tomorrow. Meanwhile can you try something out?

a) setuptools doesn't not currently support arbitrary remappings in package_dir togheter with editable installs. The only thing it supports right now is remapping the special value `""` which represents the "root of all packages". Could you try `package-dir = {"": "src"}`? (I know that in the end the values are the same, but setuptools is not smart enough to realize).

b) Can you just remove the `[tool.setuptools]` table completely in pyproject.toml? Right now the src- layout should be automatically detected.

**Comment by abravalheri** [comment]
Hi @marktsuchida, I had another look at the issue this morning, and I can confirm that the problem is not related to `pyproject.toml` or the existence/absence of `setup.cfg`/`setup.py`.

This is a pre-existing limitation of setuptools. Editable installs will not work with arbitray package dir mappings. Only `{"" = ...}` is allowed.

The examples provided for `setup.cfg` and `pyproject.toml` are indeed not equivalent. That is why the example for `pyproject.toml` does not work. We can see the same problem happening with `setup.cfg` if we have the exact equivalent:

```bash
rm -rf /tmp/myproj
mkdir -p /tmp/myproj
cd /tmp/myproj
mkdir -p src/my_package
touch src/my_package/__init__.py
cat <<EOS > pyproject.toml
[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"
EOS
cat <<EOS > setup.cfg
[metadata]
name = my-package
version = 0.1.0

[options]
packages = my_package
package_dir =
    my_package = src/my_package
EOS
virtualenv .venv
.venv/bin/pip install -e .
.venv/bin/python -c 'import my_package'
# ...
# ModuleNotFoundError: No module named 'my_package'
```

The issue with `package_dir` and editable install was previously reported with:
- https://github.com/pypa/setuptools/issues/2662
- https://github.com/pypa/setuptools/issues/1801
- https://github.com/pypa/setuptools/issues/230

Should we close this issue as a duplicate?

**Comment by abravalheri** [comment]
(For the given example I just recommend not setting any `packages` or `package-dir` and letting setuptools do the auto-discovery. It should be very robust in the case of a src-layout, unless you have files under the `src` directory that you don't want to distribute).

**Comment by marktsuchida** [comment]
@abravalheri Thank you so much!

It did not occur to me that I could use `package-dir = {"": "src"}` in `pyproject.toml` (despite it making total sense) and that I was comparing apples to oranges. I also somehow missed the (very clearly documented) fact that src-layout is handled automatically.

I'm closing this issue because the root cause (which no longer affects me) is well described in the issues you cited.

Thanks again for the rapid response.
