### ISSUE TITLE
[Docs] clarify keyword "keywords" requirements

### ISSUE THREAD

**Issue by ynikitenko** [pypa/setuptools#3396]
### Summary

At https://setuptools.pypa.io/en/latest/references/keywords.html there is a keyword `keywords`:

> A list of strings or a comma-separated string providing descriptive meta-data. See: PEP 0314.

However, in [PEP 314](https://peps.python.org/pep-0314/#keywords-optional) there is no requirement for the string to be comma-separated (in fact, the example there is without commas, and I earlier used strings without commas):

> A list of additional keywords to be used to assist searching for the package in a larger catalog.

Please fix your documentation or refer to a proper source. 

### Additional Information

This makes documentation non self-contradictory: correct (in the case of fix) or understandable by users (in the case of a proper link).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ynikitenko** [comment]
I found that there were recent documentation changes, but this doesn't seem to be addressed by them. https://github.com/pypa/setuptools/pull/3307

**Comment by ynikitenko** [comment]
One more note: I really use a string without commas in my `setup.py`, and they seem to be automatically inserted on PyPI (https://pypi.org/project/lena/). So probably commas are still not required in the setup file.

**Comment by abravalheri** [comment]
Hi @ynikitenko thank you very much for the PR.

The core metadata standard is a live standard, it means that its most recent version can be found in: 
https://packaging.python.org/en/latest/specifications/core-metadata/#keywords.

That pages does mention commas.
Should we close this PR having in mind that the standard have changed since PEP 314?

**Comment by ynikitenko** [comment]
Hi @abravalheri , thanks for the quick update and for the link! Just out of curiosity, what happens if I don't use commas? As I wrote, PyPI separated all my keywords by commas (if I ever intended it to be one sentence :) .

**Comment by abravalheri** [comment]
I don't know if setuptools or PyPI has some fallback logic to handle that... It might be the case. But it is better to stick to the standard, since the fallback logic may be removed in the future.
