### ISSUE TITLE
[CI Problems] It seems that `pytest-perf` is failing for cygwin

### ISSUE THREAD

**Issue by abravalheri** [pypa/setuptools#3408]
I noticed that recent builds for documentation-only changes started failing for cygwin:

- https://github.com/pypa/setuptools/runs/7039869057?check_suite_focus=true#step:4:512
- https://github.com/pypa/setuptools/runs/7038552895?check_suite_focus=true#step:4:512

The relevant part of the error message seems to be:

```console
>               raise CalledProcessError(retcode, process.args,
                                         output=stdout, stderr=stderr)
E               subprocess.CalledProcessError: Command '['git', 'remote', 'get-url', 'origin']' returned non-zero exit status 128.
/usr/lib/python3.9/subprocess.py:528: CalledProcessError
----------------------------- Captured stderr call -----------------------------
fatal: unsafe repository ('/cygdrive/d/a/setuptools/setuptools' is owned by someone else)
To add an exception for this directory, call:
	git config --global --add safe.directory /cygdrive/d/a/setuptools/setuptools
```

If required, we can add a `git config` command before running the tests, but I am not exactly sure about the path for the directory that should be used. Would `git config --global --add safe.directory $PWD` work? (That looks like a weird workaround).

**Comment by abravalheri** [comment]
@jaraco, @lazka, do you have any information that could help to deal with this error?

**Comment by lazka** [comment]
I think you can set `safe.directory` to `*` too

**Comment by abravalheri** [comment]
Thank you very much @lazka, I am trying something first in https://github.com/pypa/setuptools/pull/3410, before using a wildcard. Hopefully it will work 🤞

**Comment by lazka** [comment]
GITHUB_WORKSPACE will be a Windows style path, so I'm not sure if that will work
