### ISSUE TITLE
Unloading of setuptools and distutils in run_setup leads to broken types in modules that reference setuptools directly

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#343]
Originally reported by: **jaraco (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

In #315, I added a function `hide_setuptools` to the `setup_context` in which dependency installation is run (f29ad5f78ef7).

As reported in that ticket, this monkeying of the `sys.modules` context has some serious consequences for packages that keep reference to setuptools or distutils objects.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/343

**Comment by jaraco** [comment]
I'm thinking that between declarative config superseding the d2to1 work and Python 2 going into sunset, there's little more to try to address here.

**Comment by embray** [comment]
Oh wow, I *vaguely* remember this issue :)  Agreed.
