### ISSUE TITLE
[BUG] Breaking change in setuptools 61.2

### ISSUE THREAD

**Issue by hauntsaninja** [pypa/setuptools#3455]
### setuptools version

61.2

### Python version

3.10.5

### OS

macOS

### Description

At work, we store some project metadata in pyproject.toml.

setuptools has started validating information in pyproject.toml, when it previously didn't. On it's own, this isn't a bad idea, but as it stands this is problematic because:
- setuptools insists on having a version field. PEP 621 does not require users to specify a version. For example, contrast to the phrasing PEP 621 uses for name, which is required, is "Tools MUST require users to statically define this field [name]."
- This is a breaking change in a point release

### Expected behavior

setuptools shouldn't require a version field. Especially since it doesn't require a version when calling `setuptools.setup`

No breaking changes in point releases.

### How to Reproduce

```
λ cat setup.py 
from setuptools import setup

setup(name="repro", install_requires=[])

λ cat pyproject.toml
[project]
name = "repro"
dependencies = []
```

### Output

```console
λ tree
.
├── pyproject.toml
└── setup.py

0 directories, 2 files

λ cat setup.py 
from setuptools import setup

setup(name="repro", install_requires=[])

λ cat pyproject.toml 
[project]
name = "repro"
dependencies = []

λ pip install --upgrade 'setuptools==61.1'
Collecting setuptools==61.1
  Using cached setuptools-61.1.0-py3-none-any.whl (1.1 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 61.2.0
    Uninstalling setuptools-61.2.0:
      Successfully uninstalled setuptools-61.2.0
Successfully installed setuptools-61.1.0

λ pip freeze --all
pip==22.1.2
setuptools==61.1.0
wheel==0.37.1

λ PIP_NO_BUILD_ISOLATION=no pip install -e .
Obtaining file:///Users/shantanu/tmp/repro
  Checking if build backend supports build_editable ... done
  Preparing metadata (pyproject.toml) ... done
Installing collected packages: repro
  Running setup.py develop for repro
Successfully installed repro-0.0.0

λ pip install --upgrade 'setuptools==61.2'
Collecting setuptools==61.2
  Using cached setuptools-61.2.0-py3-none-any.whl (1.1 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 61.1.0
    Uninstalling setuptools-61.1.0:
      Successfully uninstalled setuptools-61.1.0
Successfully installed setuptools-61.2.0

λ pip freeze --all
pip==22.1.2
# Editable install with no version control (repro==0.0.0)
-e /Users/shantanu/tmp/repro
setuptools==61.2.0
wheel==0.37.1

λ PIP_NO_BUILD_ISOLATION=no pip install -e .
Obtaining file:///Users/shantanu/tmp/repro
  Checking if build backend supports build_editable ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      /Users/shantanu/.virtualenvs/repro-xxxx/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:103: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
        warnings.warn(msg, _ExperimentalProjectMetadata)
      configuration error: `project` must contain ['version'] properties
      DESCRIPTION:
          version should be statically defined in the ``version`` field
      
      GIVEN VALUE:
          {
              "name": "repro",
              "dependencies": []
          }
      
      OFFENDING RULE: 'required'
      
      DEFINITION:
          {
              "required": [
                  "version"
              ]
          }
      Traceback (most recent call last):
        File "/Users/shantanu/.virtualenvs/repro-xxxx/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/shantanu/.virtualenvs/repro-xxxx/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/shantanu/.virtualenvs/repro-xxxx/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/Users/shantanu/.virtualenvs/repro-xxxx/lib/python3.10/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/Users/shantanu/.virtualenvs/repro-xxxx/lib/python3.10/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/Users/shantanu/.virtualenvs/repro-xxxx/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 3, in <module>
          setup(name="repro", install_requires=[])
        File "/Users/shantanu/.virtualenvs/repro-xxxx/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/shantanu/.virtualenvs/repro-xxxx/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 122, in setup
          dist.parse_config_files()
        File "/Users/shantanu/.virtualenvs/repro-xxxx/lib/python3.10/site-packages/_virtualenv.py", line 21, in parse_config_files
          result = old_parse_config_files(self, *args, **kwargs)
        File "/Users/shantanu/.virtualenvs/repro-xxxx/lib/python3.10/site-packages/setuptools/dist.py", line 854, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/Users/shantanu/.virtualenvs/repro-xxxx/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 55, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/Users/shantanu/.virtualenvs/repro-xxxx/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 121, in read_configuration
          validate(subset, filepath)
        File "/Users/shantanu/.virtualenvs/repro-xxxx/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 44, in validate
          raise error from None
      ValueError: invalid pyproject.toml config: `project`
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by hauntsaninja** [comment]
Looks like setuptools 61.2 was released a month or two ago, not sure why everything at work is only blowing up now...

**Comment by abravalheri** [comment]
Hi @hauntsaninja , thank you very much for bringing this discussion. 

My understanding is that [PEP 621](https://peps.python.org/pep-0621/) does require either:

1. The `version` field to be specified, or
2. The `dynamic` field to be specified containing `"version"` as one of the elements of the array.

The evidence of this requirement is given by the following paragraph: 

> If the core metadata specification lists a field as “Required”, then the metadata MUST specify the field statically or list it in dynamic (build back-ends MUST raise an error otherwise, i.e. it should not be possible for a required field to not be listed somehow in the [project] table).

The [core metadata spec]( https://packaging.python.org/en/latest/specifications/core-metadata/#dynamic-multiple-use), does require `Name` and `Version`.

If you don't want to fill in `version` (e.g. when using `setuptools-scm`), please try adding `dynamic = ["version"]`.

Does this solve your problem?

**Comment by hauntsaninja** [comment]
Thanks, that makes sense, missed that part of PEP 621.

I still have a question — why does setuptools seemingly give pyproject.toml precedence over setup.py? To me it seems user intent to use setuptools is more clearly expressed by a setup.py (possibly unless there's an explicit `[tool.setuptools]` in pyproject.toml). Maybe there's a link to discussion of this somewhere? :-)

**Comment by abravalheri** [comment]
> why does setuptools seemingly give pyproject.toml precedence over setup.py?

This is also motivated by the text in PEP 621:

> A build back-end MUST honour statically-specified metadata (which means the metadata did not list the field in dynamic).
> If the metadata does not list a field in dynamic, then a build back-end CANNOT fill in the requisite metadata on behalf of the user (i.e. dynamic is the only way to allow a tool to fill in metadata and the user must opt into the filling in).
Build back-ends MUST raise an error if the metadata specifies a field in dynamic but the build back-end was unable to provide the data for it.

The idea behind PEP 621 is to incentivise package authors to specify metadata statically as much as possible (to the point that you get in trouble if you don't add `dynamic` and forget a field). This is clear by this other part of the text:

> Rejected ideas: ... *Have the dynamic field only require specifying missing required fields*
>
> The authors considered the idea that the dynamic field would only require the listing of missing required fields and make listing optional fields optional. In the end, though, this went against the design goal of promoting specifying as much information statically as possible.

**Comment by abravalheri** [comment]
PEP 621 is very strict 😅!
