### ISSUE TITLE
[BUG] AttributeError: pakcage_dir typo breaks editable installs

### ISSUE THREAD

**Issue by agroszer** [pypa/setuptools#3498]
### setuptools version

64.0.0

### Python version

3.9

### OS

ubuntu

### Additional environment information

https://github.com/pypa/setuptools/commit/7ae5a6903c83eb43a96ad02c874990d02ee92672 introduced the typo

### Description

Doing the obvious
`bin/pip install --upgrade -r "data/versions/requirements.txt"`

where requirements.txt has:
`-e .`

### Expected behavior

.

### How to Reproduce

.

### Output

```
 Traceback (most recent call last):
        File "/tmp/pip-build-env-msencw5_/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 138, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-msencw5_/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 283, in _create_wheel_file
          self._install_namespaces(unpacked, dist_info.name)
        File "/tmp/pip-build-env-msencw5_/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 171, in _install_namespaces
          src_root = Path(self.project_dir, self.pakcage_dir.get("", ".")).resolve()
        File "/tmp/pip-build-env-msencw5_/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 105, in __getattr__
          raise AttributeError(attr)
      AttributeError: pakcage_dir
```

**Comment by abravalheri** [comment]
Thank you very much for reporting this @agroszer.

**Comment by synchronizing** [comment]
Unsure if related, but since this morning all of our packages have began breaking with the following:

```
distutils.errors.DistutilsSetupError: Error: setup script specifies an absolute path:
      
          /var/folders/r7/ggtlz3qs465bzrr2zjtf1h380000gp/T/tmpforaj_f1.build-temp/plethora_signals.egg-info/SOURCES.txt
      
      setup() arguments must *always* be /-separated paths relative to the
      setup.py directory, *never* absolute paths.
      
      error: Support for editable installs via PEP 660 was recently introduced
      in `setuptools`. If you are seeing this error, please report to:
      
      https://github.com/pypa/setuptools/issues
      
      Meanwhile you can try the legacy behavior by setting an
      environment variable and trying to install again:
      
      SETUPTOOLS_ENABLE_FEATURES="legacy-editable"
      [end of output]
```

**Comment by abravalheri** [comment]
Hi @synchronizing, probably a different problem, could you open a new issue with a reproducer?

Meanwhile we investigate/fix the problem you can try using `SETUPTOOLS_ENABLE_FEATURES="legacy-editable"` or relying on a non-editable installation.

**Comment by synchronizing** [comment]
Both the env, and non-editable installations work. The issue started this morning, however, and was not present pre-64.0.0. Will open new issue, thank you.

**Comment by leonixyz** [comment]
In my case, it was indeed an editable dep breaking my testing environment that led me to find the typo in #3497

**Comment by abravalheri** [comment]
Sorry for the inconvenient @leonixyz.
The tests for original behaviour in the `develop` command were scarce because of the deprecation, so the particular code path ended up untested (it does not help that we have some issues with the coverage report).

Thank you for providing the fix. If that is OK with you, I was planning to wait and see if we can also investigate and fix the second problem reported by `@synchronizing` quickly before cutting a bug fix release. If the second issue is difficult to solve, I will split them in separated releases.

**Comment by agroszer** [comment]
@abravalheri looks like a bunch of other issues arose.... please merge and release

**Comment by abravalheri** [comment]
@agroszer, sorry for the delay. Due to the time the CI takes to run, it is good to group all the fixes together.

Please let me know v64.0.1 solves your problem. I can re-open the ticket if necessary.

**Comment by agroszer** [comment]
thanks that fixes it
