### ISSUE TITLE
[BUG] setup.cfg + pyproject.toml + setup.py (with PBR) breaking.

### ISSUE THREAD

**Issue by synchronizing** [pypa/setuptools#3500]
### setuptools version

setuptools==64.0.0

### Python version

Python 3.8.5

### OS

macOS

### Description

Reported originally in #3498. Unsure what is going on, but after the latest setuptools the following is thrown when using editable installs:

```
      distutils.errors.DistutilsSetupError: Error: setup script specifies an absolute path:
      
          /var/folders/r7/ggtlz3qs465bzrr2zjtf1h380000gp/T/tmpbr2b9x3w.build-temp/test.egg-info/SOURCES.txt
      
      setup() arguments must *always* be /-separated paths relative to the
      setup.py directory, *never* absolute paths.
      
      error: Support for editable installs via PEP 660 was recently introduced
      in `setuptools`. If you are seeing this error, please report to:
      
      https://github.com/pypa/setuptools/issues
      
      Meanwhile you can try the legacy behavior by setting an
      environment variable and trying to install again:
      
      SETUPTOOLS_ENABLE_FEATURES="legacy-editable"
      [end of output]
```

### Expected behavior

No error should be thrown, and the package should be installed.

### How to Reproduce

Here is a reproducible repo: https://github.com/synchronizing/setuptools-error

Running `pip install -e .` inside the folder will cause the error seen above. A few points:

* `SETUPTOOLS_ENABLE_FEATURES` flag _fixes_ the issue.
* Installing it without being editable (`pip install .`) _fixes_ the issue.
* Removing `pyproject.toml` _fixes_ the issue.
* Removing `pbr` _fixes_ the issue.
* Removing the `other` folder _fixes_ the issue.

### Output

See above.

**Comment by abravalheri** [comment]
Thank you very much for reporting this and for the reproducer.

I will investigate the issue and try to get back to you as soon as I can.

**Comment by synchronizing** [comment]
An interesting find. On the repo linked above, I added the following `Dockerfile`:

```Dockerfile
FROM python:3.8

RUN pip install --upgrade setuptools

WORKDIR /opt/
COPY . test
WORKDIR /opt/test
RUN pip install -e .

CMD ["/bin/bash"]
```

The above errors out with the same issue noted. Changing version to 3.8.5 fixes the problem.

**Comment by synchronizing** [comment]
I added `Dockerfile` and `docker-compose.yml` to the repo linked. Doing `docker-compose up` should result in the issue noted.

**Comment by abravalheri** [comment]
I also can reproduce the error in my machine with Python 3.8.10

**Comment by synchronizing** [comment]
3.8.10 seems to be working with the Dockerfile above, weirdly enough.

**Comment by synchronizing** [comment]
It's dependent on the release, and which Python package is getting pulled based on the tag. Using Github Actions with the matrix functionality fails on all versions: https://github.com/synchronizing/setuptools-error/actions/runs/2841720491

**Comment by abravalheri** [comment]
Thank you very much for helping to investigate that. I really appreciate all the effort.

**Comment by synchronizing** [comment]
Of course. Version 3.6.x works due to it being tied to setuptools `59.6.0`. 
See: https://github.com/synchronizing/setuptools-error/actions/runs/2841783973

**Comment by abravalheri** [comment]
Felipe, please let me know if v64.0.1 works for you, otherwise we can re-open this issue.

**Comment by synchronizing** [comment]
Yup, fixed! Thank you. https://github.com/synchronizing/setuptools-error/actions/runs/2843387978
