### ISSUE TITLE
[BUG] Setuptools version number doesn't match in virtual environment

### ISSUE THREAD

**Issue by jonathanwang375** [pypa/setuptools#3514]
### setuptools version

setuptools==63.0.0

### Python version

3.10.4

### OS

Windows

### Additional environment information

This is running on Git Bash installed on a windows 10 laptop

### Description

Our repository requires the use of a virtual environment to run most of programs. Yesterday morning, we ran into the issue where setuptools version was 64.0.0 I believe and wheel wouldn't build, so we attached the `SETUPTOOLS_ENABLE_FEATURES="legacy-editable" flag to pip install -e .` and it worked. We then went in and changed the setuptools version in our pyproject.toml file to build with setuptools version 63.0.0. However both times when we went in to double check the version using `pip list | grep setuptools` the version number appears as 58.1.0. 

### Expected behavior

I expected the version of setuptools found by `pip list | grep setuptools` to match what was installed (63.0.0) because we have defined it as such

### How to Reproduce

1) Our pyproject.toml file:
```
[build-system]
requires = ["setuptools==63.0.0", "wheel", "versioneer-518"]
build-backend = "setuptools.build_meta"
```
2) Run `python -m venv .rempy && source .rempy/Scripts/activate && python -m pip install -e .`
3) Double check version with `pip list | grep setuptools`

### Output

```
$ pip list | grep setuptools
setuptools         58.1.0
WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Users\Jonathan\GitHub\Remora\rempy\.rempy\Scripts\python.exe -m pip install --upgrade pip' command.
(.rempy)

```

**Comment by abravalheri** [comment]
Hi @jonathanwang375, I don't think you can use the command `pip  list` to inspect the versions of the packages installed in the temporary venv `pip` creates. By the time the installation ends, the temporary venv that contains the specified version of setuptools is already gone...

When you run `pip list` you are listing the packages that were present in your initial (persistent) venv + the packages installed. The build dependencies are not going to show up, because they are installed to a different venv.

**Comment by abravalheri** [comment]
You can use `--no-build-isolation` with `pip` to force it to use the exact versions of the dependencies installed in the current virtual environment.

In you case, I guess it would be something like the following:

```bash
python -m venv .rempy
.rempy/bin/python -m pip install 'setuptools==63.0.0' 'wheel' 'versioneer-518' -U pip
.rempy/bin/python -m pip install -e . --no-build-isolation
```

Note that when you use `--no-build-isolation`, pip will not automatically download and install the build dependencies in the `requires` array, you have to do it yourself.

**Comment by edmorley** [comment]
@jonathanwang375 Hi! This section of the pip docs has some more information about what is happening here, that may make things clearer:
https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#build-isolation
