### ISSUE TITLE
CCompiler `self.include_dirs` modified during each `compile()`

### ISSUE THREAD

**Issue by mdavidsaver** [pypa/setuptools#3591]
cf. 9f9a3e57643cb49796c1b08b5b5afb2826ecd7f6

https://github.com/pypa/setuptools/blob/ba3995e5705a22e13bb5d2231ac22c77e4417747/setuptools/_distutils/ccompiler.py#L390-L398

https://github.com/pypa/setuptools/blob/ba3995e5705a22e13bb5d2231ac22c77e4417747/setuptools/_distutils/_msvccompiler.py#L228-L233

With msvc, the class `include_dirs` is not empty, and will be appended to the instance `include_dirs` for each `compile(..., include_dirs=None)` (which is the default).  With enough calls, an impressively long argument list accumulates, resulting in an error:

```
FileNotFoundError: [WinError 206] The filename or extension is too long
```

I think that one simple fix would be:

```py
 if include_dirs is None: 
     include_dirs = self.include_dirs[:] # make a copy
```

**Comment by mrbean-bremen** [comment]
This also broke our NumPy builds with Python 3.11 under Windows. The above-mentioned change fixes this. Would it help to make a PR with the fix?
