### ISSUE TITLE
[BUG] editable install not working when package_dir was used

### ISSUE THREAD

**Issue by wimglenn** [pypa/setuptools#3608]
### setuptools version

setuptools==65.3.0

### Python version

3.10

### OS

macOS

### Description

The project https://github.com/borisbabic/browser_cookie3 has an uncommon structure: `__init__.py` is in the source root, and the [package_dir](https://github.com/borisbabic/browser_cookie3/blob/0.13.0/setup.py#L7-L8) is redirected there. It's strange but not necessarily invalid. Somehow that structure seems to break editable installation.

### Expected behavior

after `pip install -e <path_to_source_root>`, then `import browser_cookie3` should work.

### How to Reproduce

1. clone the repo to ./src
2. pip install -e ./src
3. try to import the package top level name

### Output

```
$ pip freeze --all
pip==22.2.2
setuptools==65.3.0
wheel==0.37.1

$ git clone git@github.com:borisbabic/browser_cookie3.git src    
Cloning into 'src'...
remote: Enumerating objects: 355, done.
remote: Counting objects: 100% (162/162), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 355 (delta 139), reused 116 (delta 113), pack-reused 193
Receiving objects: 100% (355/355), 103.37 KiB | 1.88 MiB/s, done.
Resolving deltas: 100% (218/218), done.

$ pip install -e ./src
Obtaining file:///private/tmp/issue/src
  Preparing metadata (setup.py) ... done
...
Installing collected packages: pyaes, pbkdf2, pycryptodome, pycparser, more-itertools, lz4, jeepney, jaraco.classes, cffi, keyring, cryptography, SecretStorage, browser-cookie3
  Running setup.py develop for browser-cookie3
Successfully installed SecretStorage-3.3.3 browser-cookie3-0.16.0 cffi-1.15.1 cryptography-38.0.1 jaraco.classes-3.2.2 jeepney-0.8.0 keyring-23.9.3 lz4-4.0.2 more-itertools-8.14.0 pbkdf2-1.3 pyaes-1.6.1 pycparser-2.21 pycryptodome-3.15.0

$ cat .venv/lib/python3.10/site-packages/browser-cookie3.egg-link
/private/tmp/issue/src
.

$ cat .venv/lib/python3.10/site-packages/easy-install.pth        
/private/tmp/issue/src

$ python3 -c 'import browser_cookie3'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'browser_cookie3'
```

**Comment by abravalheri** [comment]
Hi @wimglenn, thank you very much for reporting this.

The `python setup.py develop` does not work with complex `package_dir`. This is a well known setuptools limitation.

Instead, you can use the newer PEP 660 support to achieve that.

Please note that the repository does not contain `pyproject.toml` so `pip` will not use any of the build backend hooks by default. You can try:

```bash
$ python3 -m pip install --use-pep517 -e .
$ python3 -c 'import browser_cookie3; print(browser_cookie3)'
<module 'browser_cookie3' from '/tmp/browser_cookie3/__init__.py'>
```

**Comment by wimglenn** [comment]
@abravalheri Thanks for your prompt response. The suggestion to apply `--use-pep517` is good. I suppose pip will move to that as default eventually (?)

**Comment by abravalheri** [comment]
Probably... But to be sincere, `pip` seems to be doing the right thing here. If the project does not have a `pyproject.toml`, it makes sense to use the legacy installation method...
