### ISSUE TITLE
[Question] `editable_wheel` and "simple layout" for package with complex package discovery settings.

### ISSUE THREAD

**Issue by debonte** [pypa/setuptools#3615]
### setuptools version

64.0.3

### Python version

3.10

### OS

Windows 11

### Description

@JacobHayes kindly provided [a repo](https://github.com/JacobHayes/editable-install-hooks-repro) in https://github.com/pypa/setuptools/issues/3518 that demonstrates the use of an import hook for editable installs.

While looking through the `editable_wheel` implementation, I saw that for packages with ["simple layouts"](https://github.com/pypa/setuptools/blob/main/setuptools/command/editable_wheel.py#L360), setuptools will use the legacy `.pth` strategy. Which got me wondering why setuptools instead uses import hooks for the example in the sample repo.

I think it may be an issue with `_parent_path` not properly handling subpackage names (`a.b` vs `a`). Consider the following two examples:
 
```python
_parent_path("a", "src/a")      # Returns "src"
_parent_path("a.b", "src/a/b")  # Returns "src/a/b"
```

If the second example returned "src", as I believe was intended, it appears that the package in the sample repo would install using the legacy `.pth` strategy (i.e. `_simple_layout` would return `True`).

@abravalheri, I work on the Pylance team and we've received several bugs lately stemming from our inability to handle import hook-based editable installs. And I'm wondering if setuptools may be inadvertently using the import hooks strategy more often than it needs to / intends to. I'm not sure how common the case described above is, but I wonder if changing this `_parent_path` behavior could help mitigate the impact of your PEP 660 changes on static analysis tools by reducing the number of packages that use the import hooks strategy.

Apologies if I'm off base here. I'm new to Python packaging.

### Expected behavior

"editable wheel" install of pkg1 in https://github.com/JacobHayes/editable-install-hooks-repro uses `.pth` strategy instead of import hook.

### How to Reproduce

1. git clone https://github.com/JacobHayes/editable-install-hooks-repro
2. cd editable-install-hooks-repro\pkg2
3. python -m venv .venv
4. .venv\scripts\activate
5. pip install --upgrade pip
6. pip install --force-reinstall setuptools==64.0.3
7. pip3 install -e ../pkg1/
8. Determine how `pkg1` was installed -- more .venv\lib\site-packages\__editable__.org_pkg1-0.0.1.pth

### Output

```console
C:\>git clone https://github.com/JacobHayes/editable-install-hooks-repro
Cloning into 'editable-install-hooks-repro'...
remote: Enumerating objects: 37, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 37 (delta 13), reused 23 (delta 5), pack-reused 0
Receiving objects: 100% (37/37), 6.43 KiB | 3.22 MiB/s, done.
Resolving deltas: 100% (13/13), done.

C:\>cd editable-install-hooks-repro\pkg2

C:\editable-install-hooks-repro\pkg2>python -m venv .venv

C:\editable-install-hooks-repro\pkg2>.venv\scripts\activate

(.venv) C:\editable-install-hooks-repro\pkg2>pip install --upgrade pip
Requirement already satisfied: pip in c:\editable-install-hooks-repro\pkg2\.venv\lib\site-packages (21.2.3)
Collecting pip
  Using cached pip-22.2.2-py3-none-any.whl (2.0 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.3
    Uninstalling pip-21.2.3:
      Successfully uninstalled pip-21.2.3
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\erikd\\AppData\\Local\\Temp\\pip-uninstall-xyhoktix\\pip.exe'
Check the permissions.


(.venv) C:\editable-install-hooks-repro\pkg2>pip install --upgrade pip
Requirement already satisfied: pip in c:\editable-install-hooks-repro\pkg2\.venv\lib\site-packages (22.2.2)

(.venv) C:\editable-install-hooks-repro\pkg2>pip install --force-reinstall setuptools==64.0.3
Collecting setuptools==64.0.3
  Using cached setuptools-64.0.3-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 57.4.0
    Uninstalling setuptools-57.4.0:
      Successfully uninstalled setuptools-57.4.0
Successfully installed setuptools-64.0.3

(.venv) C:\editable-install-hooks-repro\pkg2>pip3 install -e ../pkg1/
Obtaining file:///C:/editable-install-hooks-repro/pkg1
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: org-pkg1
  Building editable for org-pkg1 (pyproject.toml) ... done
  Created wheel for org-pkg1: filename=org_pkg1-0.0.1-0.editable-py3-none-any.whl size=2299 sha256=bcf519120c088efbcbab7e09038662d7d68c0db4d35100779869fcacd7254299
  Stored in directory: C:\Users\erikd\AppData\Local\Temp\pip-ephem-wheel-cache-kyfqsvqc\wheels\55\84\b8\c2647e59fd5b80ba1e7062c005c8ba698f80631dd1273e810c
Successfully built org-pkg1
Installing collected packages: org-pkg1
Successfully installed org-pkg1-0.0.1

(.venv) C:\editable-install-hooks-repro\pkg2>more .venv\lib\site-packages\__editable__.org_pkg1-0.0.1.pth
import __editable___org_pkg1_0_0_1_finder; __editable___org_pkg1_0_0_1_finder.install()
```

I'm not sure why upgrading pip claimed to have failed, but it doesn't seem relevant to the repro.

**Comment by abravalheri** [comment]
Hi @debonte thank you very much for opening a discussion for this.

This is a very subtle behaviour, but intentional (and I believe correct).

The configuration in the given examples purposefully exclude the parent package from the build:

```python
    packages=find_namespace_packages(include=["org.*"], where="src"),
```

What this line is doing is saying that all packages named `org.*` should be included, but not `org` itself (`org` does not match the glob pattern `org.*`).

The way setuptools can avoid files placed directly in the `org` folder from being importable while still allowing sub-folders to be imported is via import hooks.

Regarding `_parent_path`, this private function might have not the best name in the world (sorry, names are difficult), but there is some description of what it does:

> Infer the parent path containing a package, that if added to ``sys.path`` would allow importing that package. When ``pkg`` is directly mapped into a directory with a different name, return its own path.

In this particular case we are in the second branch: (due to the circumstances previously discussed) we cannot find a parent path that when added to `sys.path` will have the desired effect. Instead we have to assume that the package is mapped directly into a directory. (Please also noticed that this function cannot be interpreted out of context, it only works in conjunction with the logic in `_simple_layout`).

**Comment by debonte** [comment]
Thanks for the explanation.
