### ISSUE TITLE
[BUG] setuptools is using deprecated and slated to be removed APIs

### ISSUE THREAD

**Issue by warsaw** [pypa/setuptools#3631]
### setuptools version

65.4.1

### Python version

3.12

### OS

macOS

### Description

As described over in the [pip issue tracker](https://github.com/pypa/pip/issues/11501), several long-deprecated Python import related APIs are being removed in Python 3.12.  All of these have been documented as deprecated for years (in most cases, since Python 3.3).  Now is the time to remove them.

However, this is blocked on references to these old APIs in `pkg_resources` which, through twisty mazes, breaks Python 3.12's build because of its vendoring of pip, hence, setuptools, hence pkg_resources.

Here is the [upstream Python ticket](https://github.com/python/cpython/issues/98040) tracking these removals, which contains the APIs that are being removed.  The `pip` issue above has references to the places in `pkg_resources` where these APIs are still being used.

### Expected behavior

Nothing in `pkg_resources`, `setuptools`, or `pip` should reference these long deprecated APIs.

### How to Reproduce

See the description in the [pip issue description](https://github.com/pypa/pip/issues/11501#issue-1402421943).

### Output

See the description in the [pip issue description](https://github.com/pypa/pip/issues/11501#issue-1402421943).

**Comment by kdeldycke** [comment]
Also related: https://github.com/pypa/pip/issues/11688
