### ISSUE TITLE
[BUG] Editable installs not working with package_dir

### ISSUE THREAD

**Issue by rzats** [pypa/setuptools#3635]
### setuptools version

65.4.1

### Python version

3.9

### OS

macOS

### Description

Editable-mode installs do not work with custom, nonstandard `package_dir`.
Non-editable installs with the same config work fine.

https://github.com/pypa/setuptools/issues/3608 suggests this should be fixed with the newer PEP 660 implementation, but that doesn't seem to be the case.

I've created a small repo to mirror the structure of the project I'm trying this out on: https://github.com/rzats/setuptools-repro. It contains this `pyproject.toml`:

```
[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"
```

`setup.cfg`:

```
[metadata]
name = Local Package

[options]
packages =
    root.package

package_dir =
    root.package = root/package/src
```

and a Python file at `root/package/src/test.py`.

### Expected behavior

After a package is installed with `pip install -e`, it should recognize the mappings from `package_dir` in `pyproject.toml`.

### How to Reproduce

Verify that a non-editable install of the sample package works:
```console
$ git clone https://github.com/rzats/setuptools-repro.git
$ cd setuptools-repro
$ python3 -m pip install --use-pep517 .
$ python3 -c 'import root.package.test'
$ python3 -m pip uninstall Local-Package
```
But an editable one does not:
```console
$ python3 -m pip install --use-pep517 -e .
$ python3 -c 'import root.package.test'
```

### Output

```console
$ git clone https://github.com/rzats/setuptools-repro.git

$ cd setuptools-repro

$ python3 -m pip install --use-pep517 .
Defaulting to user installation because normal site-packages is not writeable
Processing /Users/work/Documents/setuptools-repro
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: Local-Package
  Building wheel for Local-Package (pyproject.toml) ... done
  Created wheel for Local-Package: filename=Local_Package-0.0.0-py3-none-any.whl size=1219 sha256=33a914cef0d8248c4d1023c7f8ed943f67d21e98b91f47b73e3db2459355752d
  Stored in directory: /Users/work/Library/Caches/pip/wheels/3b/f3/39/5146b860dfd91bd2fc9e945cd0e8f702410f76f413f67f7bf8
Successfully built Local-Package
Installing collected packages: Local-Package
Successfully installed Local-Package-0.0.0

$ python3 -c 'import root.package.test'

$ python3 -m pip uninstall Local-Package
Found existing installation: Local-Package 0.0.0
Uninstalling Local-Package-0.0.0:
  Would remove:
    /Users/work/Library/Python/3.9/lib/python/site-packages/Local_Package-0.0.0.dist-info/*
    /Users/work/Library/Python/3.9/lib/python/site-packages/root/package/test.py
Proceed (Y/n)? Y
  Successfully uninstalled Local-Package-0.0.0

$ python3 -m pip install --use-pep517 -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///Users/work/Documents/setuptools-repro
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Installing collected packages: Local-Package
  Running setup.py develop for Local-Package
Successfully installed Local-Package

$ python3 -c 'import root.package.test'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'root.package.test'```

**Comment by abravalheri** [comment]
Hello @rzats, I don't have access to a macOS machine to investigate this issue deeply, but by looking at the logs you provided I suspect somehow the installation process is using an outdated version of pip and/or setuptools.

This line: `Running setup.py develop for Local-Package` is what gives it away.
In newer versions of pip/setuptools you should be seen instead something like `reated wheel for Local-Package: filename=...`.

Can you try creating a local virtual env with the latest version of pip installed and let me know how it goes? For example:

```bash
git clone https://github.com/rzats/setuptools-repro.git
cd setuptools-repro
python3.9 -m venv .venv
.venv/bin/python -m pip install -U pip
.venv/bin/python -m pip install -e .
.venv/bin/python -c 'import root.package.test; print(root.package.test)
```

**Comment by rzats** [comment]
Indeed, after fully cleaning up my environment the issue was fixed (the imports still don't show up in any IDE I've tested, but that's an IDE problem and I'll take it to them.) Thanks for doublechecking!

**Comment by abravalheri** [comment]
@rzats, regarding IDE support, please have a look on https://github.com/pypa/setuptools/issues/3518.

This seems to be related to a well-known limitation of IDEs/static analysis. Python is a dynamic language, so it is natural and justifiable that not all features of the language are supported by IDEs/static analysis tools -- this is the case of the import hooks used to implement editable installs in projects that don't conform with a [`src-layout`](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/?highlight=src-layout) via PEP 660.

**Comment by rzats** [comment]
@abravalheri thanks for the pointer! looks like this is already a well-known issue and might not be fixed for some time, we'll keep that in mind 😄
