### ISSUE TITLE
Unclear how CCompiler.has_function works for functions with parameters

### ISSUE THREAD

**Issue by fweimer-rh** [pypa/setuptools#3648]
This issue is a continuation of python/cpython#98529.

`CCompiler.has_function` constructs the source code for a linking test for function availability like this:

https://github.com/pypa/setuptools/blob/1617a58ebb12a588d5272bef340c2596ce9c3997/setuptools/_distutils/ccompiler.py#L847-L857

Let's assume that the checked function actually exists and has one or more arguments. There are two cases to consider:

1. Include files are specified, and the function is declared in the include files (or a function-like macro is defined).
2. No include files are specified, or the function is not declared in the specified include files.

In the first case, compilation fails because not enough arguments are specified in the function call.  We never get to the linking stage.

In the second case, compilation still fails with strict C compilers (Clang 16, probably future GCC 14) because implicit function declarations are a C89 feature that was removed from C99 and future language standards.  Again, no link is attempted.

This means that `has_function` really can't detect functions successfully (at least if they expect more than one argument).

Autoconf works around this by supplying a `char foo();` declaration and calling that (still in a link-only test). That still does not allow the detection of alternative macro implementations. It is incompatible with the header file list that is allegedly supported by `has_function`: If you supply your own definition, you must not include any header files that potentially conflict with it.

(Found via the Fedora C99 porting project.)

**Comment by keszybz** [comment]
Yep, the current check won't work. Meson's [has_function() implementation](https://github.com/mesonbuild/meson/blob/master/mesonbuild/compilers/mixins/clike.py#L772) would be a good start.

**Comment by jaraco** [comment]
Yes, was merged in v67.2.0.
