### ISSUE TITLE
[FR] Detect semicolon `;` as end of URL when defining dependencies (in `pyproject.toml`)

### ISSUE THREAD

**Issue by EwoutH** [pypa/setuptools#3652]
### What's the problem this feature will solve?

A `pyproject.toml` file may crash when a semicolon is placed directly after an URL when defining dependencies, like in this case:
```toml
[project]
dependencies = [
    "statsmodels; python_version < '3.11'",
    "statsmodels @ git+https://github.com/statsmodels/statsmodels.git; python_version >= '3.11'",
]
```

### Describe the solution you'd like

If a semicolon `;` is detected as the end of an URL, this is interpreted as not part of the URL, so that the `pyproject.toml` above works.

The semicolon is a reserved symbol in the [URL specification](https://www.ietf.org/rfc/rfc1738.txt), so it won't naturally be included in an URL.

### Alternative Solutions

Adding a space between the URL and the semi-colon fixes the problem (see https://github.com/pypa/setuptools/discussions/3651). However, this is not clear and normally not needed in toml files.

An alternative solution is adding an improved warning message, such as: 

> The URL specified ends with a semicolon `;`. If this is not part of the URL, add a space between it and the URL.

### Additional context

See this discussion: https://github.com/pypa/setuptools/discussions/3651

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
I had a look on the chain of libraries, and for the time being, I think it is not possible to change the error message (unfortunately).

**Comment by EwoutH** [comment]
Unfortunate, but thanks for the extensive reply and investigating this issue!

**Comment by pradyunsg** [comment]
Wait, but it is. ;)

https://github.com/pypa/packaging/issues/529#issuecomment-1340224685

**Comment by abravalheri** [comment]
Thank you @pradyunsg . Yes exactly the error message has to be changed directly in packaging and it would be very difficult/convoluted to change it in setuptools. 

Right now we have a draft PR from Jason for the removal of LegacyVersion, I am waiting for it before considering updating the bundled copy of `packaging` (it seems that this would be the most backward incompatible change).
