### ISSUE TITLE
setuptools creates invalid versions with tag_svn_revision

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#367]
Originally reported by: **psuter (Bitbucket: [psuter](http://bitbucket.org/psuter), GitHub: [psuter](http://github.com/psuter))**

----------------------------------------

Version numbers are now standardised under PEP 440 since setuptools 8.0.
Versions like 2.0.dev-r123 are not valid anymore.

The setuptools documentation hasn't been updated. 
It presents such (actually invalid) versions as valid examples:
https://pythonhosted.org/setuptools/setuptools.html#managing-continuous-releases-using-subversion

setup.cfg options are recommended:

    [egg_info]
    tag_build = .dev
    tag_svn_revision = 1

 
But setuptools creates invalid versions when `tag_svn_revision` is used by adding `-r`.

There appears to be no way to make setuptools generate valid versions. At least the documentation does not mention any.

On the mailing list it was explained:
> 2.0.dev123 is the correct version number to use, setuptools might need additional updates to it to properly generate those though.

https://mail.python.org/pipermail/distutils-sig/2015-March/025967.html

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/367

**Comment by jaraco** [comment]
Rather than fix this issue, I'd prefer to deprecate the functionality (#619) in setuptools.
