### ISSUE TITLE
[BUG] set version=1.0.1.b101 but get whl version=1.0.1b101

### ISSUE THREAD

**Issue by qianyiwei** [pypa/setuptools#3677]
### setuptools version

setuptools == 65.5.1

### Python version

python 3.9

### OS

centos

### Description

in setup.py, set version== 1.0.1.b101
but after install whl ,pip list whl version=1.0.1b101

### Expected behavior

no

### How to Reproduce

set version=1.0.1.b101 and exec python setup.py bdist_wheel

### Output

```console
but after install whl ,pip list whl version=1.0.1b101
```

**Comment by abravalheri** [comment]
Hi @qianyiwei, thank you for reporting this.

Please note that PEP 440 define a few [normalization rules](https://peps.python.org/pep-0440/#normalization) used by setuptools. In particular I would like to highlight the following:


> [Pre-release separators](https://peps.python.org/pep-0440/#pre-release-separators)
Pre-releases should allow a ., -, or _ separator between the release segment and the pre-release segment. The normal form for this is without a separator. This allows versions such as 1.1.a1 or 1.1-a1 which would be normalized to 1.1a1. It should also allow a separator to be used between the pre-release signifier and the numeral. This allows versions such as 1.0a.1 which would be normalized to 1.0a1.


It is outside of the scope of this project to allow custom version normalization.
