### ISSUE TITLE
[BUG] Relative import paths not set correctly in __init__.py for setuptools >= 60.0.0

### ISSUE THREAD

**Issue by roehnan** [pypa/setuptools#3721]
### setuptools version

setuptools==60.10.0

### Python version

3.10.5 - 3.10.9, 3.11

### OS

Fedora Linux 37

### Description

For setuptools >= 60.0.0, installing amqplib==1.0.2 results in an invalid __init__.py file.

The client library cannot be imported because the relative imports are missing the initial '.'.

Under setuptools >= 60.0.0, the imports are written like:

```
from basic_message import *
from channel import *
from connection import *
from exceptions import *
```

Because of this, importing the client fails:

```
>>> import amqplib.client_0_8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/amqplib/client_0_8/__init__.py", line 24, in <module>
    from basic_message import *
ModuleNotFoundError: No module named 'basic_message'
```

### Expected behavior

The __init__.py contains proper relative imports:

```from .basic_message import *
from .channel import *
from .connection import *
from .exceptions import *
```

### How to Reproduce

1. Install setuptools>=60.0.0 (`python -m pip install 'setuptools>=60.0.0'`)
2. Install amqplib==1.0.2 (`python -m pip install 'amqplib==1.0.2'`)
3. From a Python interpreter, attempt to import `amqplib.client_0_8` (`import amqplib.client_0_8
`)

### Output

```console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/amqplib/client_0_8/__init__.py", line 24, in <module>
    from basic_message import *
ModuleNotFoundError: No module named 'basic_message'
```

**Comment by abravalheri** [comment]
Hi @roehnan , please note that, out of the box, setuptools does not rewrite Python code during the build process...

If the original code uses deprecated Python 2 implicit relative import conventions that changed with Python 3, it is the responsibility of the package authors to change it and make it compatible with Python 3.

I did not manage to find the original source code to double check that this is the case, but I suspect it is. Have you managed to make this work with Setuptools 59?

**Comment by roehnan** [comment]
Thank you for the response. Yes, it works with setuptools 59. Something must have changed in version 60.

We can pin our build process to version 59 but I wanted to note that the behavior did change.

**Comment by abravalheri** [comment]
Would it be the case you are refering to this project: https://github.com/barryp/py-amqplib/blob/master/amqplib/client_0_8/__init__.py, or a similar code base?

If that is the case, this is not a bug in setuptools. I recomend instead contacting the library author and reporting the problem there.

**Comment by abravalheri** [comment]
> Thank you for the response. Yes, it works with setuptools 59. Something must have changed in version 60.

Thank you, it might be the case this project is using a `"2to3"` transformation that was deprecated in May 2020 and removed late 2021.

**Comment by roehnan** [comment]
> Would it be the case you are refering to this project: https://github.com/barryp/py-amqplib/blob/master/amqplib/client_0_8/__init__.py, or a similar code base?
> 
> If that is the case, this is not a bug in setuptools. I recomend instead contacting the library author and reporting the problem there.

Yes that is the project. I can follow up with the project's maintainer. Thanks again for the helpful and quick responses!
