### ISSUE TITLE
[Docs] Unclear how to use `exclude-package-data`

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [pypa/setuptools#3733]
### Summary

The [docs](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#setuptools-specific-configuration) explain that the `exclude-package-data` config is a table, but has no notes or explanation of how to use the field.  I would've assumed it would be an array of glob patterns to exclude, so I don't know what keys/values of this table should be.

### Additional Information

This is a bit of an XY issue, where Y is "I don't understand the documentation for this option" and X is "I'm struggling to exclude `_version.py`, `pkg/tests/*`, and `pkg/data/.gitignore`.  Since it seemed automatic package discovery included these files, I'm trying to follow the instructions for [Custom discovery](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#custom-discovery)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @Jacob-Stevens-Haas you can findmkre information about his conifg in https://setuptools.pypa.io/en/latest/userguide/datafiles.html

**Comment by Jacob-Stevens-Haas** [comment]
Alas, it's that simple.  I found that page and somehow missed the connection when it came time to use `exclude-package-data`.
