### ISSUE TITLE
entrypoint and option to choose test command runner for setup.py test

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#374]
Originally reported by: **RonnyPfannschmidt (Bitbucket: [RonnyPfannschmidt](http://bitbucket.org/RonnyPfannschmidt), GitHub: [RonnyPfannschmidt](http://github.com/RonnyPfannschmidt))**

---

the current mechanism of requiring unittest based tests limits the usage

integrations that use other tools cant easily provide setup.py test without making a strange mess

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/374

**Comment by abravalheri** [comment]
I think it makes sense to close this issue now that `python setup.py test` is deprecated (and users are recommended to use something like tox/nox), right?

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
