### ISSUE TITLE
[FR] Symlinks to executable from installed packages via setuptools should work on windows

### ISSUE THREAD

**Issue by nanaceba** [pypa/setuptools#3759]
### What's the problem this feature will solve?

I am trying to use symlinks to executables that created when we installing packages via setuptools. However looks like executable is only able to run if `*-script.py` in a same folder.
Example
```
C:\>cd Snapchat\Dev\_nlo_\python\Scripts

C:\Snapchat\Dev\_nlo_\python\Scripts>conan_build_info.exe
usage: conan_build_info [-h] [--output OUTPUT] trace_path
conan_build_info: error: the following arguments are r
equired: trace_path

WARN: Use 'conan_build_info --v2' to see the usage of the new recommended way to generate build info using lockfiles

C:\Snapchat\Dev\_nlo_\python\Scripts>cd ..

C:\Snapchat\Dev\_nlo_\python>cd ..

C:\Snapchat\Dev\_nlo_>cd bin

C:\Snapchat\Dev\_nlo_\bin>mklink conan_build_info.exe C:\Snapchat\Dev\_nlo_\python\Scripts\conan_build_info.exe
symbolic link created for conan_build_info.exe <<===>> C:\Snapchat\Dev\_nlo_\python\Scripts\conan_build_info.exe

C:\Snapchat\Dev\_nlo_\bin>conan_build_info.exe
Cannot open C:\Snapchat\Dev\_nlo_\bin\conan_build_info-script.py

C:\Snapchat\Dev\_nlo_\bin>
```

I expect this symlink run correctly.

### Describe the solution you'd like

We could add symlink resolving logic to the exe wrapper that will allow to check final file destination/symlink destination.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @nanaceba, could you please provide a [complete minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by nanaceba** [comment]
I've added a very small `setup.py` package that installs itself and prints `hello`.
Steps to repro:

- `python -m pip uninstall wheel`
- `python -m pip install .` from the zip folder
- `mklink test.exe your_python_path/Scripts/test.exe`
- `execute symlink test.exe`

[test_package.zip](https://github.com/pypa/setuptools/files/10429633/test_package.zip)

**Comment by abravalheri** [comment]
Hi @nanaceba, thank you very much for providing an example.

I see that you are forcing pip to trigger the deprecated behaviour of `setup.py install` by uninstalling the `wheel` package.

If your environment don't have access to `wheel` or you cannot install it, I would suggest running `pip install --use-pep517 .` (this is what pip suggests). You also have another options: to add an appropriate `pyproject.toml` file to the package.

You can verify this approach works as expected with the following example (using a container for isolation/reproducibility):

```powershell
> docker run --rm -it python:3.10-windowsservercore powershell

cd $env:Temp
Invoke-WebRequest https://github.com/pypa/setuptools/files/10429633/test_package.zip -OutFile test_package.zip
Expand-Archive -LiteralPath test_package.zip
cd test_package
python -m pip uninstall wheel
python -m pip install -U pip
python -m pip install --use-pep517 .

cmd /c mklink test.exe  C:\Python\Scripts\test_wrapper.exe
.\test.exe  # => hello
```

**Comment by abravalheri** [comment]
Just for the sake of information, this is the warning message `pip` prints if you uninstall `wheel` and forget to add `--use-pep517`:

> DEPRECATION: test-hello is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
