### ISSUE TITLE
support wheels by considering them zip-unsafe eggs

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#376]
Originally reported by: **RonnyPfannschmidt (Bitbucket: [RonnyPfannschmidt](http://bitbucket.org/RonnyPfannschmidt), GitHub: [RonnyPfannschmidt](http://github.com/RonnyPfannschmidt))**

---

if they where just unpacked into a folder named like the wheel archive,
then adding them to sys.path seems like a completely normal and possible thing

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/376

**Comment by petsuter** [comment]
> [wheel 145](https://bitbucket.org/pypa/wheel/issue/145/support-installation-of-zipped-wheels-and) to track that possibility

https://github.com/pypa/wheel/issues/145

**Comment by webknjaz** [comment]
@jaraco should this be closed? https://github.com/pypa/wheel/issues/145#issuecomment-340494208

**Comment by jaraco** [comment]
Yeah, Setuptools is going to get out of the business of using eggs, through deprecating easy_install and setup_requires and by replacing most of pkg_resources with importlib.resources and importlib.metadata.
