### ISSUE TITLE
Cannot install local packages with editable_mode=compat with pure pyproject.toml package

### ISSUE THREAD

**Issue by mcrumiller** [pypa/setuptools#3767]
## Issue

Installing my local package (package name `python-toolbox`, module in package named `toolbox`) using the following to install:

```
pip install -e . --config-settings editable_mode=compat
```

results in the module being inaccessible despite a successful installation:

```
C:\Projects>pip install -e . --config-settings editable_mode=compat
<installation output>
Successfully installed python-toolbox-1.1.5

C:\Projects>python -c "import toolbox"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'toolbox'
```

I tried using `SETUPTOOLS_ENABLE_FEATURES="legacy-editable"` as suggested [here](https://setuptools.pypa.io/en/latest/userguide/development_mode.html), but now I get the following error:

```
ERROR: Project file:///C:/Projects/python-toolbox has a 'pyproject.toml' and its build backend is missing the
'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable
mode. Consider using a build backend that supports PEP 660.
```

## Configuration

Here is my `pyproject.toml` configuration (unneeded data removed):

```
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
authors = [
    { name = "me", email = "my.email@com.com" },
]
name = "python-toolbox"
description = "Python toolbox"
dynamic = ["version"]
dependencies = [
    "my_dependencies"
]

[project.scripts]
script_name = "module:function"

[tool.setuptools]
include-package-data = true
packages = [
    "toolbox",
    "toolbox.subpackages",
    "my_subpackages"
]

[tool.setuptools.package-dir]
toolbox = "src/python/toolbox"

[tool.setuptools.package-data]
    "toolbox" = "my_resource"
    "toolbox.subpackage" = "subpackage_resource"

[tool.setuptools.dynamic]
version = { attr = "toolbox.__version__" }
readme = { file = ["README.md"] }
```

My project has the following directory structure:

```
python-toolbox
 |--src
     |--python
         |--toolbox
             |--__init__.py
             |--other files
```

I would love if someone could help me diagnose. I can install with `editable_mode=strict`, but that leads to various issues and I would prefer compat mode if possible. Thank you!

**Comment by abravalheri** [comment]
Hi @mcrumiller, please note the approach `SETUPTOOLS_ENABLE_FEATURES="legacy-editable"` is conditional to `pip` defaulting to use `python setup.py develop`. If `pip` has removed this behaviour, there is nothing `setuptools` can do about it.

Regardless, both approaches `SETUPTOOLS_ENABLE_FEATURES="legacy-editable"` and `editable_mode=compat` work by adding an entry to `sys.path`. This means that no path remapping can be done via `package-dir` (that is why it works for static analysis tools... They don't support any dynamic behaviour).

Therefore `package-dir` *must be* either empty/unspecified or in the form of `package-dir = {"" = "somedirectory"}`.

You might have some luck if you do the following change:

```toml
[tool.setuptools.package-dir]
"" = "src/python"
```

(You might want to have a look in your `pyproject.toml`, e.g. it's missing `readme` in `project.dynamic`, and the values for `tool.setuptools.package-data.*` need to be an array)

**Comment by mcrumiller** [comment]
@abravalheri thank you so much! Your suggested change of:

```toml
[tool.setuptools.package-dir]
"" = "src/python"
```

Completely resolved the issue. Two other notes:

1. The `package-data` is correct in the original toml, I screwed it when removing sensitive data to post here. 😣 
2. why does `readme` need to be in `project.dynamic` when I have it in `[tool.setuptools.dynamic]`? Do I need to rename that section?

**Comment by mcrumiller** [comment]
Oh, and one other question: does `"" = "src/python"` simply instruct setuptools that all packages are located in `src/python`? Is there documentation on `package-dir` somewhere?
