### ISSUE TITLE
[BUG] distutils.ccompiler.CCompiler.has_function does not quote provided includes anymore

### ISSUE THREAD

**Issue by rokm** [pypa/setuptools#3820]
### setuptools version

67.2.0

### Python version

3.x

### OS

Linux (but presumably applicable to all)

### Description

As of 56a5b333b2a8064c000d18ac0629385100957db0 (setuptools 67.2.0), the `distutils.ccompiler.CCompiler.has_function` in the `setuptools`-provided `distutils` ceased to quote the provided `includes` in the generated test C file ([here](https://github.com/pypa/setuptools/blob/bfd92b008cbda2c1252eddd2f3e54b91f61969fb/setuptools/_distutils/ccompiler.py#L863)).

Therefore, the compilation of the generated test C file always fails.

### Expected behavior

The provided `includes` should be quoted ([as before the change](https://github.com/pypa/setuptools/blob/8032430d75cdfad9f9826d302d90cd7b23dea3ca/setuptools/_distutils/ccompiler.py#L848)) to retain compatibility with older code using this function.

### How to Reproduce

1. Run the following test code on Linux:

```python
# program.py
import distutils.ccompiler

# Check for `clock` function in the standard library
cc = distutils.ccompiler.new_compiler()
has_clock = cc.has_function('clock', includes=['time.h'])
print("Has clock:" , has_clock)
``` 

### Output

With `setuptools 67.2.0`:
```console
$ python program.py 
/tmp/clocku2l593gf.c:1:10: error: #include expects "FILENAME" or <FILENAME>
    1 | #include time.h
      |          ^~~~
/tmp/clocku2l593gf.c: In function ‘main’:
/tmp/clocku2l593gf.c:3:5: warning: implicit declaration of function ‘clock’ [-Wimplicit-function-declaration]
    3 |     clock();
      |     ^~~~~
/tmp/clocku2l593gf.c:1:1: note: ‘clock’ is defined in header ‘<time.h>’; did you forget to ‘#include <time.h>’?
  +++ |+#include <time.h>
    1 | #include time.h
Has clock: False
```

With `setuptools 67.1.0`:
```console
$ python program.py 
Has clock: True
```

**Comment by lazka** [comment]
@fweimer-rh

**Comment by abravalheri** [comment]
@fweimer-rh, would it be possible to add quotes if the argument does not starts with `"` either `<`?

**Comment by abravalheri** [comment]
> Should I send a PR to fix this?

I believe that a PR to pypa/distutils mentioning this bug in setuptools should be the way to go.
