### ISSUE TITLE
[BUG] PackageFinder unnecessarily traverses file system before filtering include/exclude packages

### ISSUE THREAD

**Issue by vkottler** [pypa/setuptools#3845]
### setuptools version

setuptools==67.5.1

### Python version

Python 3.7.4

### OS

Ubuntu 16.04 LTS

### Description

There's a warning about this in the documentation: https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#finding-namespace-packages

![image](https://user-images.githubusercontent.com/15205052/223291020-4fddbe5f-2107-4e67-865c-6c4add076e21.png)

The problem is that the "A simple way to fix this..." sentence isn't true, because something like a symbolic link to another part of the file system in the project root will brick package building unnecessarily.

### Expected behavior

When `find_namespace_packages` is provided `include` and/or `exclude` arguments, this information should be sufficient to avoid walking parts of the file system that are not part of the Python package project.

### How to Reproduce

Create a symbolic link to another part of a host's file system in the root of a Python package project and attempt to build the project.

If there are enough files, this will cause package building to hang, trying to compute what things are a part of the package in a foreign domain w.r.t what `setuptools` is told is the domain of the package's sources.

### Output

This results in e.g. `python -m build .` appearing to hang when `setup.py` is trying to compute "what are the packages", which is unexpected because the result is simple to compute.

**Comment by vkottler** [comment]
Part of the problem is the `followlinks=True` hard-code here: https://github.com/pypa/setuptools/blob/f51eccd769cab0297c64e4d007bef42544326431/setuptools/discovery.py#L145

**Comment by vkottler** [comment]
I posted in the Discord, but I'm willing to accept that this is "a feature" of how "flat" package-project building works, I'm interested in knowing more about how to make my dozens of maintained packages conform to something better.

**Comment by abravalheri** [comment]
Hi @vkottler, thank you very much for reporting this.

In your description and comments, you mention that this problem can be found with either symbolic links or even without them.

Could you please provide a [minimal example](https://stackoverflow.com/help/minimal-reproducible-example) with all the steps you are using to reproduce this problem in both situations?

**Comment by vkottler** [comment]
# Files

## `setup.py`

```
import setuptools  # type: ignore

setuptools.setup(
    name="project",
    version="0.0.0",
    packages=setuptools.find_namespace_packages(
        include=["project", "project.*"],
        exclude=["tests", "tests.*"],
    )
)
```

## `pyproject.toml`

```
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta:__legacy__"
```

## `project/__init__.py`

```
# This is a package.
```

# Commands

I'm in `bash` on Ubuntu 20.04.1.

```
$ python -m venv venv
$ ./venv/bin/pip install build
$ time ./venv/bin/python -m build .
```

My `time` results were:

```
real    0m10.969s
user    0m9.725s
sys     0m1.011s
```

Works fine. Now, create a symbolic link like `ln -s /usr`. Perform the last command again and observe results:

```
real    0m12.195s
user    0m10.604s
sys     0m1.386s
```

The problem statement I'm proposing is that `setuptools` should have enough information to not traverse those parts of the file system that a minimal configuration is telling it to look in.

**Comment by abravalheri** [comment]
I see... Thank you very much for the reproducer!

After running the example, I suspect that probably the problem comes from here:

https://github.com/pypa/setuptools/blob/v67.5.1/setuptools/discovery.py#L163-L165

I found this conceptual design a bit weird before (it is the same reason why you need the `exclude=["package", "package.*"]`), but it was added to the setuptools way back intentionally, so not sure if we can remove it.

But we might be able to optimize this code for an earlier prune if both `exclude=["package", "package.*"]` or `exclude=["package*"]` is specified...

Let me think a bit more about this...

**Comment by vkottler** [comment]
@abravalheri thanks for the reply. I agree, it's a bit precarious since you all likely don't want to change the overall behavior.

**Comment by abravalheri** [comment]
Hi @vkottler, I implemented a simple heuristic in https://github.com/pypa/setuptools/pull/3846, but it does require tuning a little bit your `exclude` block.

I did not manage to devise a backwards compatible pruning heuristic that considers `include` (imagine the edge case `include=["*.production"]`, how to tackle that? To me it seems that scanning all the directories would be needed for this one...).

If you can have a look on the PR and see if it is enough to support your use case it would be nice.

**Comment by vkottler** [comment]
I see, this would make it so an explicit `exclude` would skip recursing into directories.

One question: what if that iteration _did_ `yield package`? Maybe in that case an `include` could take precedence over an `exclude`?

Wondering because if so, I think it would be possible to `include=["project", "project.*"]` and maybe `exclude=["*"]`. Maybe not though, curious what you think!

**Comment by abravalheri** [comment]
> One question: what if that iteration did yield package? Maybe in that case an include could take precedence over an exclude?

I am not sure if I understood this suggestion. There is a `yield` already in place...

> (edit: I guess maybe that's not possible, because both include and not exclude must be satisfied)

Yes, both filters need to be satisfied.

**Comment by vkottler** [comment]
This seems like a useful change if you want to go forward with it. I appreciate you taking a look at this.

**Comment by abravalheri** [comment]
I will include this next time I cut a release (it might take a few days/weeks).
