### ISSUE TITLE
Problem building a setuptools dependent package on Manjaro

### ISSUE THREAD

**Issue by Ph-St** [pypa/setuptools#3854]
### setuptools version

62.1.0-1

### Python version

Python 3.10.9

### OS

Manjaro Linux

### Additional environment information

This seems to be a Manjaro specific problem (see below)

### Description

I'm trying to update python-eduvpn-client to new version 4.0.1-2.

In the process, I get the following error:

```
File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 253, in finalize_options
        if pd is not None and pd.key == self.egg_name.lower():
    AttributeError: 'PathDistribution' object has no attribute 'key'

    ERROR Backend subprocess exited when trying to invoke build_wheel
    ==> ERROR: An error occurred in build().
        Aborting...
    Error: can not build ‚python-eduvpn-client-4.0.0-1‘:
    Error: can not build package: python-eduvpn-client-4.0.0-1
```

According to the maintainer of python-eduvpn-client (https://aur.archlinux.org/packages/python-eduvpn-client#comment-904944), this points to a problem with setuptools, that's why I'm reporting this here.

### Expected behavior

Building of python-eduvpn-client completes with no errors.

### How to Reproduce

1. On current Manjaro, update python-eduvpn-client from 3.1.0-2 to 4.0.1-2.
2. Building fails with above error message

### Output

```
File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 253, in finalize_options
        if pd is not None and pd.key == self.egg_name.lower():
    AttributeError: 'PathDistribution' object has no attribute 'key'

    ERROR Backend subprocess exited when trying to invoke build_wheel
    ==> ERROR: An error occurred in build().
        Aborting...
    Error: can not build ‚python-eduvpn-client-4.0.0-1‘:
    Error: can not build package: python-eduvpn-client-4.0.0-1

```

**Comment by abravalheri** [comment]
Hi @Ph-St, have you tried using the latest version of setuptools?

I suspect that this problem might be already solved.

**Comment by Ph-St** [comment]
Hi @abravalheri!

Thanks for the suggestion. My package manager wasn't offering a new version, but I just installed it via pip and indeed it solves the problem!

Thanks again!

**Comment by Ph-St** [comment]
Update to setuptools 67.3.0 solves this problem.
