### ISSUE TITLE
[FR] When should we expect "manylinux2014" support for uploading aarch64 wheels?

### ISSUE THREAD

**Issue by Nir-Az** [pypa/setuptools#3857]
### What's the problem this feature will solve?

uploading aarch64 wheels

### Describe the solution you'd like

Supporting the manylinux2014 platform tag like mentioned [here](https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/): 

### Alternative Solutions

None

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @Nir-Az, the upload capabilities of setuptools are deprecated, if you are looking specifically for a tool to upload pre-built wheels to PyPI, please have a look on [`twine`](https://github.com/pypa/twine).

**Comment by Nir-Az** [comment]
Thanks. Will close.
