### ISSUE TITLE
[BUG] Wildcard specification is broken 

### ISSUE THREAD

**Issue by xbeastx** [pypa/setuptools#3867]
### setuptools version

setuptools>65.6.3

### Python version

python 3.x

### OS

Ubuntu

### Description

So in setuptools with version above 65.6.3 pip rise an error:
```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in my-pkg setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          requests>=2.18.*
                    ~~~~~^
      [end of output]
```

As I can see there is no any changes in PEP440 in terms of wildcard version matching: https://peps.python.org/pep-0440/#version-matching

### Expected behavior

Expecting support of wildcard matching version requirements as in 65.6.3 and below.

### How to Reproduce

Just create `requirements.txt` with wildcard like so:
```
requests>=2.18.*
```

And try to install

### Output

```console

```

**Comment by abravalheri** [comment]
Hi @xbeastx ,  in PEP 508 (I think), `*` is only defined for `==` and `!=` operators.
