### ISSUE TITLE
[FR] Add option for --extra-index-url

### ISSUE THREAD

**Issue by Erol444** [pypa/setuptools#3876]
### What's the problem this feature will solve?

If your package requires a package that's not hosted on pypi, there's currently no easy way to set the `--extra-index-url`. There's a stackoverflow thread [Using an extra python package index url with setup.py](https://stackoverflow.com/questions/24443583/using-an-extra-python-package-index-url-with-setup-py) discussing exactly this, but workarounds are based on Easy install, which is deprecated, and it's suggested to open an Issue here:)

### Describe the solution you'd like

To be able to easily set additional index url for a package. Specifically my library requires `sensor_msgs` package, which can be installed like:

`pip install --extra-index-url https://rospypi.github.io/simple/ sensor_msgs`.

### Alternative Solutions

Old workarounds are only available through Easy Install, which is now deprecated.

### Additional context

Stackoverflow thread suggested Easy Install, but since it's deprecated I haven't dug into it.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
If you need a dependency hosted outside of PyPI you can still use PEP 440 [direct url specs](https://peps.python.org/pep-0440/#direct-references), but please be aware that PyPI may block projects that do so from uploading distributions (for security reasons and/or philosophically to be self contained).
