### ISSUE TITLE
[BUG] Messages use dubious link shortener services instead of canonical URLs

### ISSUE THREAD

**Issue by uiopaubo** [pypa/setuptools#3879]
### setuptools version

40.8.0

### Python version

3.7.3

### OS

10.13

### Additional environment information

I encounter this when running the Debian packaging scripts, but it is not peculiar to Debian's patched version of setuptools.

### Description

A message of the following form may appear when setuptools is invoked:

```console
Note: Bypassing https://pypi.org/simple/setuptools_scm/ (disallowed host; see http://bit.ly/2hrImnY for details).
```

This text can be found in the following location in the sources:

https://github.com/pypa/setuptools/blob/main/setuptools/package_index.py#L405

### Expected behavior

Link-shortened URLs should not be used. The services involved may not remain available, they may not guarantee that the target URL remain the same, and such services may even be subverted by malicious parties. When someone uses setuptools, their screen space is generally not so limited that they cannot tolerate a full-length URL. Instead, canonical URLs referencing a trusted site should be employed.

### How to Reproduce

Examine the source code to "reproduce" the bug.

### Output

```console
Note: Bypassing https://pypi.org/simple/setuptools_scm/ (disallowed host; see http://bit.ly/2hrImnY for details).
```

**Comment by uiopaubo** [comment]
Bug #1197 rather makes my point about link stability.

**Comment by abravalheri** [comment]
Hi @uiopaubo thank you very much for reporting.
In #3902 I am updating the URL.

Note that in general fixes and improvements are made against setuptools' `main` branch and published as a new version in monotonic order.
