### ISSUE TITLE
[BUG] `pip list` duplicate package entries

### ISSUE THREAD

**Issue by AmeyaVS** [pypa/setuptools#3888]
### setuptools version

67.6.1

### Python version

Python 3.11.2

### OS

Fedora 37

### Description

Have reported same issue in pip package: https://github.com/pypa/pip/issues/11937.

While trying out example from scikit-build examples:
[hello-cpp](https://github.com/scikit-build/scikit-build-sample-projects/tree/master/projects/hello-cpp)

Duplicate entries of the C++ extension is displayed when installing package through `setup.py`.

### Expected behavior

Only a single instance of the C++ extension package should be listed.

### How to Reproduce

1. Get following source: [hello-cpp](https://github.com/scikit-build/scikit-build-sample-projects/tree/master/projects/hello-cpp)
2. Using python setup.py:
    2.1. Build C++ Extension Package:
    ```sh
    $  python setup.py build
    ```
    2.2. Install package in venv:
    ```sh
    $ python setup.py install
    ```

### Output

List packages:

```console
$ pip list
Package      Version
------------ -------
distro       1.8.0
hello-cpp    1.2.3
hello-cpp    1.2.3
hello-cpp    1.2.3
packaging    23.0
pip          23.0.1
scikit-build 0.16.7
setuptools   67.6.1
wheel        0.40.0
```

**Comment by abravalheri** [comment]
Hi @AmeyaVS , please be aware that, while `setup.py` is a perfectly valid configuration file,  executing it directly as a Python script is deprecated. Please use the equivalent `pip`/`python -m build` commands instead. See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for a reference. 


I can see in the related issue that using `pip` directly is not subject to the effect you consider that desirable. 

With that in mind, I think we can close this issue (if the users are executing the recommended tools, they will not see this behaviour).

**Comment by AmeyaVS** [comment]
Thank you, for the update.
Another reason I raised the issue was to try and build the C++ Extension in debug mode.
While trying to get it to build under pip seems to be only supported in release mode and could not get it to build in debug mode.

I will close this ticket for now.
