### ISSUE TITLE
./setup.py test does not support --find-links or --index-url

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#389]
Originally reported by: **miracle2k (Bitbucket: [miracle2k](http://bitbucket.org/miracle2k), GitHub: [miracle2k](http://github.com/miracle2k))**

---

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/389

**Comment by abravalheri** [comment]
Hello, since running tests with `python setup.py test` has been deprecated for a while, I think it should be OK to close this issue.

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
