### ISSUE TITLE
[BUG] setup.py set version=1.0.RC1,but pip list version is 1.0rc1

### ISSUE THREAD

**Issue by chenzeng8** [pypa/setuptools#3890]
### setuptools version

setuptools == 65.5.1

### Python version

python 3.9

### OS

centos

### Additional environment information

setup.py set version=1.0.RC1,but pip list version is 1.0rc1

### Description

the setup.py is 
![image](https://user-images.githubusercontent.com/122774235/230814511-7db4a8dc-0133-4df1-a5c6-e73d2526ee3f.png)
the whl file is 
![image](https://user-images.githubusercontent.com/122774235/230814547-f397995f-c835-49c8-a075-76207d711c0f.png)

### Expected behavior

pip install test_whl-1.0.RC1-py3-none-any.whl

### How to Reproduce

pip list

### Output

```console
pip list

```
![image](https://user-images.githubusercontent.com/122774235/230814491-4bc0c90b-7f13-4084-a1c8-fe9c7b927174.png)

**Comment by abravalheri** [comment]
Hi @chenzeng8, please note that in the Python ecosystem version strings are supposed to be normalized according to https://peps.python.org/pep-0440/.

So I think pip is providing a list completely inline with the spec...

**Comment by chenzeng8** [comment]
thanks anyway！
