### ISSUE TITLE
[BUG] Building C-extension raises #import error with relative paths

### ISSUE THREAD

**Issue by Djentmat** [pypa/setuptools#3891]
### setuptools version

setuptools === 67.6.1

### Python version

Python 3.8.7

### OS

Windows 10

### Description

I trying to build whl with 
"**python -m build**" and getting 
"**src/callback.cpp(6): fatal error C1083: Cannot open type library file: '../import/my_lib.tlb': No such file or directory**".

When i call 
"**python -m setup.py install**" 
this error isn't raises. 

If I change relative paths to absolute ones, then everything works.

setup.py contains:

```python
src_path = r'src'
import_path = r'import'
temporary_path = r'build\temp.win-amd64-cpython-38\Release\src'
module = Extension(module_name, sources=src_list,
                   include_dirs=['.', src_path, import_path, temporary_path],
                   language='c++')
``` 

My project  structure:
├───.vscode
├───bat
├───build
│   ├───bdist.win-amd64
│   ├───lib.win-amd64-cpython-38
│   └───temp.win-amd64-cpython-38
│       └───Release
│           └───src
├───dist
├───doc
│   └───doxygen
├───import
└───src
    └───my_progect.egg-info

### Expected behavior

Successful creation of the whl file is expected.

### How to Reproduce

Sorry , I can't create example now. I will add it later.

### Output

```console
PS C:\Users\User\Downloads\my_project> python -m build
D:\_programs\WPy64-3870\python-3.8.7.amd64\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools>=61.0)
* Getting build dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools>=61.0)
* Getting build dependencies for wheel...
* Installing packages in isolated environment... (wheel)
* Building wheel...
callback.cpp
src/callback.cpp(6): fatal error C1083: Cannot open type library file: '../import/my_lib.tlb': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2 
```

**Comment by abravalheri** [comment]
Hi @Djentmat, the way `python -m build` works by default is to create the wheel file (final binary distribution) from the sdist (a tar.gz file, uncompiled, containing source distribution).


First the `sdist` is created from the working directory, then it is extracted into a temporary directory and the `wheel` is created from there.

This explains why you are not able to use relative paths.

You can try to use `python -m build --wheel` to see if `build` skips the `sdist`.

I don't think there is an action point for setuptools here, since the process is part of the way the frontend works.

**Comment by abravalheri** [comment]
If that is not the case, please make sure to double check all the files are included in the `sdist`.
This is done either via a plugin that always adds everything under VCS control (e.g. `setuptools-scm`) or using a `MANIFEST.in` file. You can see more information on https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html.
