### ISSUE TITLE
Disable noisy _BetaConfiguration warnings using PYTHONWARNINGS=ignore:BetaConfiguration

### ISSUE THREAD

**Issue by bernhardkaindl** [pypa/setuptools#3918]
### Discussed in https://github.com/pypa/setuptools/discussions/3895

<div type='discussions-op-text'>

<sup>Originally posted by @ssbarnea April 18, 2023</sup>
Apparently setuptools is polluting the console logs with lots of unactionable warnings, like the one below:
```
_BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*
```

The reality is that there is nothing actionable about it as if the package maintainer decided to make use of the new standard, there is no point to spam them with every installation happening.

There are two other warnings that I find annoying but these might prove to be a little bit useful, especially as one of them seems to be have an open bug.

* Getting build dependencies for wheel...
/tmp/build-env-k3gfydhv/lib/python3.9/site-packages/setuptools_scm/git.py:295: UserWarning: git archive did not support describe output
  warnings.warn("git archive did not support describe output")
/tmp/build-env-k3gfydhv/lib/python3.9/site-packages/setuptools_scm/git.py:312: UserWarning: unexported git archival found
  warnings.warn("unexported git archival found")
/tmp/build-env-k3gfydhv/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
running egg_info
writing src/ansible_lint.egg-info/PKG-INFO
writing dependency_links to src/ansible_lint.egg-info/dependency_links.txt
writing entry points to src/ansible_lint.egg-info/entry_points.txt
writing requirements to src/ansible_lint.egg-info/requires.txt
writing top-level names to src/ansible_lint.egg-info/top_level.txt
listing git files failed - pretending there aren't any
reading manifest file 'src/ansible_lint.egg-info/SOURCES.txt'
adding license file 'COPYING'
writing manifest file 'src/ansible_lint.egg-info/SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
/tmp/build-env-k3gfydhv/lib/python3.9/site-packages/setuptools_scm/git.py:295: UserWarning: git archive did not support describe output
  warnings.warn("git archive did not support describe output")
/tmp/build-env-k3gfydhv/lib/python3.9/site-packages/setuptools_scm/git.py:312: UserWarning: unexported git archival found
  warnings.warn("unexported git archival found")
/tmp/build-env-k3gfydhv/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
running bdist_wheel
</div>

Proposal
========
Like with other warnings, a project maintainer should be allowed to disable this warning. The act of setting an environment variable like PYTHONWARNINGS=ignore:BetaConfiguration should be acknowledgement enough that the using project has accepted that it is using a beta feature.

**Comment by abravalheri** [comment]
`_BetaConfiguration` should be gone in the latest release.
