### ISSUE TITLE
'develop' command does not support --home option

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#392]
Originally reported by: **Anonymous**

---

The 'develop' command doesn't support the '--home' option. This gets used by pip when installing editable packages with '-t', yielding the following error:

```
$ pip2 install -e . -t www/lib/
Obtaining file:///Users/pgriess/src/pgriess-dallas-foodscores
Collecting tweepy>=3 (from foodscores==0.1)
  Using cached tweepy-3.3.0-py2.py3-none-any.whl
Collecting feedgen>=0.3 (from foodscores==0.1)
...
  Running setup.py develop for foodscores
    Complete output from command /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools, tokenize; __file__='/Users/pgriess/src/pgriess-dallas-foodscores/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps --home=/var/folders/lh/bdrw67kn04s7c7rdtsk50pg8f1dq3h/T/tmpyinatN:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --home not recognized
```

Not sure if this should be considered a bug in `setuptools` or `pip`; apologies in advance if this is expected behavior and `pip` should just be doing something different.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/392

**Comment by markfink** [comment]
same here. Any news?

**Comment by narJH27** [comment]
pip version 8.1.2 here too .... Any update on the possible workarounds for this or a patch that fixes the issue?

**Comment by markfink** [comment]
any ideas on how to deal with this? it is really bothering me

**Comment by guidedways** [comment]
Any update on this?

**Comment by ryegye24** [comment]
Any movement on this lately? It's still happening on version 9.0.1

**Comment by jakul** [comment]
I'm having the same issue

**Comment by dwt** [comment]
@maintainers: Any progress on this issue? Is there anything that can be done to get this moving forward? It seems implementing `--home` for `develop` could be entirely possible?

**Comment by abravalheri** [comment]
My understanding is that the discussion about this issue has been moved to #2589, so I will close this issue for the time being (everyone is welcome to continue the conversation there 😄)

The good news is that lately there have been several discussions on editable installs and PEP 660, so we might be able to address this issue 🤞
