### ISSUE TITLE
Make more use of setup.cfg

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#394]
Originally reported by: **Anonymous**

---

Right now setuptools uses setup.cfg only for configuration options of commands, e.g.

```
#!python

python setup.py build_ext --inplace 
```

is equal to 

```
#!python

[build_ext]
inplace=1
```

in setup.cfg. Why not allow users to define most of the configuration options to the _setup_ command inside setup.cfg? It seems there was some effort done in [disutils2](http://alexis.notmyidea.org/distutils2/setupcfg.html) to allow that. As the maintainer of [PyScaffold](pyscaffold.readthedocs.org), I implemented my own [logic](http://pyscaffold.readthedocs.org/en/v2.2/configuration.html) but have a strong feeling that setuptools should directly implement this. Having a purely declarative way of defining the settings for 95% of all use cases would help beginners and intermediate Python developers a lot. 

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/394

**Comment by jaraco** [comment]
This was released in 30.4.0.
