### ISSUE TITLE
Not finding README.md specified in pyproject.toml

### ISSUE THREAD

**Issue by afonsosalbrecht** [pypa/setuptools#3956]
### setuptools version

67.8.0

### Python version

3.10.2

### OS

windows

### Description

When building the wheel using only pyproject.toml file, the README.md file is not being found, and consequently not getting imported into PyPI as long_description.

my pyproject.toml content:
```
[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'


[project]
name = 'error-example'
version = '0.0.1'
dynamic = ['readme']

[tool.setuptools.dynamic]
readme = {file = "README", content-type = "text/markdown"}
```

### Expected behavior

setuptools to find README.md while building the wheel.

### How to Reproduce

1. `mkdir test; cd test`
2. `git clone https://github.com/afonsosalbrecht/setuptools_error_example.git`
3. `pip install -r requirements.txt`
4. `python -m build .`  ---> here you can see the console error
5. `python -m twine upload dist/*`  ---> it doesn't display the README in the front page of the package

### Output

Error from step 4.
```console
...
config = read_configuration(filepath, True, ignore_option_errors, dist)
C:\Users\#####\AppData\Local\Temp\build-env-0ujl2h99\lib\site-packages\setuptools\config\expand.py:132: SetuptoolsWarning: File 'C:\\Users\\#####\\codebases\\setuptools_error_example\\README' cannot be found
  return '\n'.join(
running egg_info
writing src\error_example.egg-info\PKG-INFO
writing dependency_links to src\error_example.egg-info\dependency_links.txt
writing top-level names to src\error_example.egg-info\top_level.txt
...
```

**Comment by afonsosalbrecht** [comment]
Hi @abravalheri 

According to the [documentation](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata), (although no very clear about .md files), I shouldn't add any extensions to the file when defining it in readme under [tool.setuptools.dynamic] section. 

If I add the extension to the filename, it works! Thanks!

I'd suggest improving the documentation in that section, at least add one example with a markdown readme.

**Comment by abravalheri** [comment]
Thank you @afonsosalbrecht.
Would you like to provide a PR with that improviment?

**Comment by afonsosalbrecht** [comment]
Sure, I can do that.

So, I did the example in the documentation using plain text, but it didn't work. I had to add the .txt extension to the README so that setuptools could find it. 

Also, I realised that if I just delete the `content-type` key (like below code), it works perfectly fine for both plain text and markdown files, as long as they have their extensions.

```
[project]
...
dynamic = ['readme']

[tool.setuptools.dynamic]
readme = {file = "README.md"}
```

Somehow the `content-type` key is not being read at all for this purpose.

**Comment by abravalheri** [comment]
There might be a misunderstanding on how the `content-type` works. The `content-type` is actually read and changes the outcome of the build process.

This is a quick experiment that demonstrate the difference:

```bash
rm -rf /tmp/with_content_type
mkdir -p /tmp/with_content_type
cd /tmp/with_content_type
echo "[Hello Markdown](https://www.example.com)" > README.md
cat <<EOF > pyproject.toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "experiment"
version = "0.42"
dynamic = ["readme"]

[tool.setuptools.dynamic]
readme = {file=["README.md"], content-type="text/markdown"}
EOF
pipx run build .
# ...
# Successfully built experiment-0.42.tar.gz and experiment-0.42-py3-none-any.whl

unzip -c dist/experiment-0.42-py3-none-any.whl experiment-0.42.dist-info/METADATA
# Archive:  dist/experiment-0.42-py3-none-any.whl
#   inflating: experiment-0.42.dist-info/METADATA
# Metadata-Version: 2.1
# Name: experiment
# Version: 0.42
# Description-Content-Type: text/markdown
# 
# [Hello Markdown](https://www.example.com)
```

```bash
rm -rf /tmp/with_content_type
mkdir -p /tmp/with_content_type
cd /tmp/with_content_type
echo "[Hello Markdown](https://www.example.com)" > README.md
cat <<EOF > pyproject.toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "experiment"
version = "0.42"
dynamic = ["readme"]

[tool.setuptools.dynamic]
readme = {file=["README.md"]}
EOF
pipx run build .
# ...
# Successfully built experiment-0.42.tar.gz and experiment-0.42-py3-none-any.whl

unzip -c dist/experiment-0.42-py3-none-any.whl experiment-0.42.dist-info/METADATA
♯ Archive:  dist/experiment-0.42-py3-none-any.whl
♯   inflating: experiment-0.42.dist-info/METADATA
♯ Metadata-Version: 2.1
♯ Name: experiment
♯ Version: 0.42
♯ Description-Content-Type: text/x-rst
♯ 
♯ [Hello Markdown](https://www.example.com)
```

In this example, you can see how the created wheels are going to differ in terms of the `Description-Content-Type` metadata (this is aligned with the behaviour that documented right now inhttps://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata).

**Comment by afonsosalbrecht** [comment]
I see it now the purpose of `content-type`. 
Good example, thanks!
