### ISSUE TITLE
[BUG] unexpected DeprecationWarning of pkg_resources from `script (dev).tmpl`

### ISSUE THREAD

**Issue by kenhkl** [pypa/setuptools#3981]
### setuptools version

setuptools===68.0.0

### Python version

Python 3.8

### OS

Linux

### Description

Since setuptools group has offically claimed that 'pkg_resources' package was deprecated at [here](https://github.com/pypa/setuptools/pull/3843), the use of pkg_resources by the users are reasonable to report a DeprecationWarning, however the use by setuptools itself should not report such warning as I think.

When I install by `pip install -e` with `-e` option, the installed script is generated by [setuptools/script (dev).tmpl](https://github.com/pypa/setuptools/blob/main/setuptools/script%20(dev).tmpl) where the following statement exists:
```
__import__('pkg_resources').require(%(spec)r)
```
Therefore, I get an unexpected warning when I run the installed script:
```
...: DeprecationWarning: pkg_resources is deprecated as an API. See ...
```

A possible solution is to remove
```
__import__('pkg_resources').require(%(spec)r)
```
in **setuptools/script (dev).tmpl** (and probably **setuptools/script.tmpl**).

### Expected behavior

When running a script installed by `pip install -e`, I expect no **DeprecationWarning** triggered by `__import__('pkg_resources').require` from **setuptools/script (dev).tmpl**.

### How to Reproduce

1. Create a project named `test_pkg_resources`, with two files:
```
test_pkg_resources
  |- setup.py
  |- testrun
```

where, `setup.py` is:
```python
import setuptools
from os.path import abspath, dirname, join
repo = dirname(abspath(__file__))
setuptools.setup(
    name = "test-proj",
    scripts=[join(repo, "testrun")],
    python_requires=">=3.7",
)
```

and `testrun` is:
```python
#!/usr/bin/env python3
if __name__ == "__main__":
    print("Hello!")
```

2. run command to install with option `-e`:
```shell
python3 -m pip install -e test_pkg_resources/ --user
```

3. run installed script:
```shell
testrun
```

4. then the unexpected warning appears.

### Output

```console
.../bin/testrun:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('test-proj==0.0.0')
Hello!
```

**Comment by abravalheri** [comment]
Hi @kenhkl, I believe that with a sufficiently updated version of `pip` will should not be seeing that message.

This is likely to be happening because `pip` is triggering a deprecated code path.
Since the implementation of PEP 660, editable installs are expected to trigger the `editable_wheel` command instead of `develop`.

You can also force `pip` to use the latest (and not deprecated) behaviour with `--use-pep517` flag for `pip` install.

**Comment by kenhkl** [comment]
Thanks @abravalheri, really looking forward to a new version of pip.
By the way, a confussion: since my occasion is to use pip to do editable installs, so your suggestion to use `--use-pep517` seems not helpful to avoid the pkg_resources DeprecationWarning mentioned above.

> You can also force `pip` to use the latest (and not deprecated) behaviour with `--use-pep517` flag for `pip` install.

**Comment by abravalheri** [comment]
Have you tried to use `pip install --use-pep517 -e .`? What is the output that pip provides if you run `pip -v install --use-pep517 -e .`?

**Comment by kenhkl** [comment]
@abravalheri Sorry, I did not present my point clearly.
Yes, the warning is missing when I run `python3 -m pip install --use-pep517 -e test_pkg_resources/ --user`. And the modification on other modules called by **testrun** can be performed on-the-fly. However, this way differs from using `python3 -m pip install -e test_pkg_resources/ --user` that the modification on **testrun** cannot be performed dynamically.

So, if one wants such **testrun** to be editable installed, then a new version of pip is needed.

> Have you tried to use `pip install --use-pep517 -e .`? What is the output that pip provides if you run `pip -v install --use-pep517 -e .`?

**Comment by abravalheri** [comment]
Hi @kenhkl, unfortunately I don't know how the `testrun` script works, but I would like to avoid touching the template that is used by easy-install, because it is hard to fully understand how that would unfold in the ecosystem (there might be old packages out there that depends on this behaviour).

There are other ways to convince `pip` to use the new APIs for build isolation (which will imply that the new `editable_wheel` command runs instead of the deprecated `develop`), would you consider trying one of the following:

- Add a `pyproject.toml` file with `[build-system]`, e.g. https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use
- Export a `PIP_USE_PEP517=1` environment variable (that should have the same effect as `--use-pep517`).

**Comment by kenhkl** [comment]
Thanks @abravalheri, I now have enough knowledge to deal with the unexpected warnings so far.

**Comment by jiasli** [comment]
> I believe that with a sufficiently updated version of `pip` will should not be seeing that message.

I am using the latest `pip`

```
$ pip -V
pip 23.2.1 from /home/user2/py310/lib/python3.10/site-packages/pip (python 3.10)
```

but our [script `az`](https://github.com/Azure/azure-cli/blob/caf5c2aba1698c4b9a45b1192a7a1b473953c5ac/src/azure-cli/setup.py#L170-L171) installed by `pip install -e src/azure-cli` still shows this warning:

```
$ az -v
/home/user2/py310/bin/az:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('azure-cli==2.51.0')
```

**Comment by abravalheri** [comment]
Hi @jiasli , I believe that pip 23.1 was supposed to use isolated builds by default (the new APIs that setuptools already implements), but they decided to post pone a little bit.

Please have a look on my previous comment for alternatives.

**Comment by myz540** [comment]
> Have you tried to use `pip install --use-pep517 -e .`? What is the output that pip provides if you run `pip -v install --use-pep517 -e .`?

This actually worked for me, thanks!

**Comment by krivadna** [comment]
> > Have you tried to use `pip install --use-pep517 -e .`? What is the output that pip provides if you run `pip -v install --use-pep517 -e .`?
> 
> This actually worked for me, thanks!

Pls help

~/dirsearch $ pip -v install --use-pep517 -e

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-e option requires 1 argument

**Comment by myz540** [comment]
> > > Have you tried to use `pip install --use-pep517 -e .`? What is the output that pip provides if you run `pip -v install --use-pep517 -e .`?
> > 
> > 
> > This actually worked for me, thanks!
> 
> Pls help
> 
> ~/dirsearch $ pip -v install --use-pep517 -e
> 
> Usage: pip install [options] [package-index-options] ... pip install [options] -r [package-index-options] ... pip install [options] [-e] ... pip install [options] [-e] ... pip install [options] <archive url/path> ...
> 
> -e option requires 1 argument

you're missing a `.`, `-e` shouldn't require any args but `pip install` definitely does
