### ISSUE TITLE
Config read from pyproject.toml and setting dist metadata

### ISSUE THREAD

**Issue by 3N4N** [pypa/setuptools#3983]
https://github.com/pypa/setuptools/blob/6083e18f4afc40316c0112134c205c336afbcdfd/setuptools/config/_apply_pyprojecttoml.py#L122-L125

Shouldn't `setter` be passed the `dist` object along with `value`?  Otherwise, what's it gonna do with only `value`?

**Comment by abravalheri** [comment]
I don't think so. I believe that `setter` is a bound method.

**Comment by 3N4N** [comment]
Oh.  I need to examine it further.  Please don't close the issue yet, even though it's probably just my misunderstanding and not a bug.

**Comment by 3N4N** [comment]
@abravalheri I am setting `dist.metadata.set_install_requires` in my custom setuptool extension (the reason is [here][1]).  Is this function not supposed to be set from an extension?

[1]: https://github.com/pypa/setuptools/discussions/3982
