### ISSUE TITLE
__del__ seems to have weird (wrong) environment in unittests performed w/ setuptools

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#399]
Originally reported by: **CrazyCasta (Bitbucket: [CrazyCasta](http://bitbucket.org/CrazyCasta), GitHub: [CrazyCasta](http://github.com/CrazyCasta))**

---

I'm writing a Lua wrapper and the top layer of abstraction needs to call lua_close on the underlying lua_State. Nothing pecular, but when I run python setup.py test, it fails, saying that essentially lib is a NoneType. lib is something that's imported from a cffi package and is never assigned to, so I'm unclear how it's becoming None. If I test the unittest outside of setuptools it seems to work fine.

I've reduced this to a sample that is very simple using sin imported from math instead of a cffi module. I've attached said example. setuptools_test.txt is the output of python setup.py test. unittest_test.txt is the output of python test2.py.

Python is CPython 2.7.9.

Expected result, something along the lines of:

testCallStuff (test.lua.RealCodeTestCase) ... ok

---

Ran 1 test in 0.002s

OK
0.841470984808

Actual result:

running test
running egg_info
writing PyLua.egg-info/PKG-INFO
writing top-level names to PyLua.egg-info/top_level.txt
writing dependency_links to PyLua.egg-info/dependency_links.txt
reading manifest file 'PyLua.egg-info/SOURCES.txt'
writing manifest file 'PyLua.egg-info/SOURCES.txt'
running build_ext
testCallStuff (test.lua.RealCodeTestCase) ... ok

---

Ran 1 test in 0.001s

OK
Exception TypeError: "'NoneType' object is not callable" in <bound method Test.__del__ of <lua.lua.Test object at 0x7fcbc85bd390>> ignored

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/399

**Comment by abravalheri** [comment]
Hello, since running tests with `python setup.py test` has been deprecated for a while, I think it should be OK to close this issue.

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
