### ISSUE TITLE
[BUG] version number check shortcoming in setuptools?

### ISSUE THREAD

**Issue by TabLand** [pypa/setuptools#3998]
### setuptools version

68

### Python version

3.10.6

### OS

Ubuntu 22.04.2 LTS

### Description

This issue was noticed whilst trying to build lumibot from source: https://github.com/Lumiwealth/lumibot/issues/262
Initially, setuptools attempts to download and build `aiohttp==4.0.0a1` as it's detected as the latest version; but it is not considered a stable release and does not compile.

I was able to trace that dependency to the following packages that lumibot requires:

| Direct Dependency | Version | Indirect Dependency | Version |
|--------|--------|--------|--------|
| ccxt | 3.0.61 | aiohttp | >=3.8 |
| alpaca-trade-api | 2.3.0 | aiohttp | ==3.8.1 |
| alpha-vantage | 2.3.1 | aiohttp | Not Specified |

### Expected behavior

I feel there is a version number check shortcoming in setuptools, because if the entire dependency tree were to be mapped out in the beginning; it will become obvious what the minimum and maximum supported version of a certain module or package is, and installing the newest available version as per the first package check is not always the most appropriate thing to do. 

I was able to fix this issue locally by specifying a new dependency for lumibot `aiohttp==3.8.1`. Unfortunately this quick-fix creates extra work for package maintainers as it's duplicating dependencies' version requirements.

By mapping out the full dependency tree; it will become possible to identify any clashing requirements. In my case, I'm able to build `aiohttp==3.8.2` but I get an error shortly after that: 
```
Installed /usr/local/lib/python3.10/dist-packages/aiohttp-3.8.2-py3.10-linux-x86_64.egg
error: aiohttp 3.8.2 is installed but aiohttp==3.8.1 is required by {'alpaca-trade-api'}
```

### How to Reproduce

```
git clone git@github.com:Lumiwealth/lumibot.git
cd lumibot
python3 setup.py build
sudo python3 setup.py install
```

### Output

```console
aiohttp/_http_parser.c: In function ‘__pyx_tp_dealloc_7aiohttp_12_http_parser_HttpParser’:
aiohttp/_http_parser.c:16227:5: error: lvalue required as increment operand
16227 |     ++Py_REFCNT(o);
      |     ^~
aiohttp/_http_parser.c:16229:5: error: lvalue required as decrement operand
16229 |     --Py_REFCNT(o);
      |     ^~
...
error: Setup script exited with error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

**Comment by abravalheri** [comment]
Hi @TabLand, thank you very much for reporting the problem.

Please note that running both `python3 setup.py build` and `python3 setup.py install` directly is considered deprecated (you can check more information about that in https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html), and therefore supported in a best effort scenario (basically "provided as it is").

Have you tried installing the package using `pip`?
I believe that once you run `cd lumibot` you can run `pip install .`. Does that work for you?

**Comment by TabLand** [comment]
Hi @abravalheri,

Thanks for pointing this out. I am able to build `lumibot` successfully without any further changes when I run `pip install .`
Reviewing the logs, I can see the correct version of `aiohttp==3.8.1` is installed to begin with. 

Marking this issue as closed - won't fix.
