### ISSUE TITLE
[BUG] No longer possible to have multiple py files at top level

### ISSUE THREAD

**Issue by raxod502-plaid** [pypa/setuptools#4013]
### setuptools version

setuptools==65.5.0

### Python version

Python 3.11.1

### OS

macOS 13.5

### Description

I have an existing Python project that defines two packages at the top level, [code here](https://github.com/radian-software/straight.el/tree/9b11112b2e7aedd994feb2d8f95bd66dbc5749a5/watcher).

The relevant directory structure is as follows:

```
/Users/rrosborough/.emacs.d/straight/repos/straight.el/watcher
├── setup.py
├── straight_watch.py
└── straight_watch_callback.py
```

The module is installed into a virtualenv using `pip3 install -e .` and then it is expected that you can `import straight_watch` and `import straight_watch_callback`.

The `setup.py` is:

```python
from setuptools import setup

# https://python-packaging.readthedocs.io/en/latest/minimal.html
setup(
    author="Radian LLC",
    author_email="contact+straight@radian.codes",
    description="Internal utilities for straight.el.",
    license="MIT",
    install_requires=["psutil==5.6.6"],
    name="straight-watcher",
    url="https://github.com/radian-software/straight.el",
    version="1.0-dev",
)
```

### Expected behavior

With setuptools <61.0.0, installation works fine and the imports described above work fine.

### How to Reproduce

With setuptools >=61.0.0, installation (`pip3 install -e .` on the [linked code](https://github.com/radian-software/straight.el/tree/9b11112b2e7aedd994feb2d8f95bd66dbc5749a5/watcher)) fails with the following error:

<details>
<summary><code>error: Multiple top-level modules discovered in a flat-layout: ['straight_watch_callback', 'straight_watch'].</code></summary>

```
% pip install -e ~/.emacs.d/straight/repos/straight.el/watcher
Obtaining file:///Users/rrosborough/.emacs.d/straight/repos/straight.el/watcher
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      /Users/rrosborough/.emacs.d/straight/watcher/virtualenv/lib/python3.11/site-packages/setuptools/dist.py:530: UserWarning: Normalizing '1.0-dev' to '1.0.dev0'
        warnings.warn(tmpl.format(**locals()))
      error: Multiple top-level modules discovered in a flat-layout: ['straight_watch_callback', 'straight_watch'].

      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.

      If you are trying to create a single distribution with multiple modules
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:

      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names

      To find more information, look for "package discovery" on setuptools docs.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
```

</details>

Documentation [here](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html) contains the note:

> If you are using auto-discovery with flat-layout, setuptools will refuse to create [distribution archives](https://packaging.python.org/en/latest/glossary/#term-Distribution-Package) with multiple top-level packages or modules.
> 
> This is done to prevent common errors such as accidentally publishing code not meant for distribution (e.g. maintenance-related scripts).
> 
> Users that purposefully want to create multi-package distributions are advised to use [Custom discovery](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#custom-discovery) or the src-layout.

However, as of yet I have been unable to find any combination of `setup.py` and `pyproject.toml` options that allows the package to be installed and both modules to be imported. Either installation fails with a different error, or the package is installed with the modules not being importable.

I know that it is probably possible to get things to work by changing the directory structure of the project, but this is not a desirable option. I filed this as a bug because the existing directory structure worked fine with setuptools<61.0.0, but there seems to be no support for it in setuptools>=61.0.0. Was support dropped intentionally, or was this a regression?

Or did I simply not find the right combination of configuration to make this work? (I tried different options for numerous hours and even looked through the setuptools source code.)

### Output

See above

**Comment by abravalheri** [comment]
Hi @raxod502-plaid, thank you very much for the report, please see some comments below

> With setuptools <61.0.0, installation works fine and the imports described above work fine.

This is probably related to the specific method that you were using for the installation (i.e. editable install). Editables installs are "complicated"™️:. Inherently they have to deal with a compromise "emulating the behaviour of a package installed normally" vs "allowing users to do changes like adding new files"[^1], so not necessarily what you observe in an editable install is what the package configuration you have written is actually doing.

For example, if you try to build the package using Setuptools<60 "for real" (see snippet below), you can see that the package configuration you are using results in an empty package with no `.py` file. This happens because in your configuration you do not specify `packages=[...]`[^2]; and before v61.0.0 setuptools would not attempt to derive that configuration option automatically.

```bash
> docker run --rm -it python:3.11-bullseye /bin/bash

git clone https://github.com/radian-software/straight.el/
cd straight.el
git reset --hard 9b11112b2e7aedd994feb2d8f95bd66dbc5749a5
cd watcher

python -m venv .venv
.venv/bin/python -m pip install 'setuptools==60.0.0' wheel build
.venv/bin/python -m build --no-isolation
unzip -l dist/*.whl
# Archive:  dist/straight_watcher-1.0.dev0-py3-none-any.whl
#   Length      Date    Time    Name
# ---------  ---------- -----   ----
#       300  2023-08-14 18:53   straight_watcher-1.0.dev0.dist-info/METADATA
#        92  2023-08-14 18:53   straight_watcher-1.0.dev0.dist-info/WHEEL
#         1  2023-08-14 18:53   straight_watcher-1.0.dev0.dist-info/top_level.txt
#       344  2023-08-14 18:53   straight_watcher-1.0.dev0.dist-info/RECORD
# ---------                     -------
#       737                     4 files
```

> However, as of yet I have been unable to find any combination of setup.py and pyproject.toml options that allows the package to be installed and both modules to be imported. Either installation fails with a different error, or the package is installed with the modules not being importable.

The error message says:
```
If you are trying to create a single distribution with multiple modules
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names
```

You said option 2 is not possible for you, but have you tried options 1 or 3? What are the problems with those options?

For example, I gave it a try for option 3 (re-using the same project directory from the snippet above):

```bash
.venv/bin/python -m pip install 'setuptools==68'
sed -i 's/)/    py_modules=["straight_watch", "straight_watch_callback"])/' setup.py  # add py_modules configuration.
.venv/bin/python -m build --no-isolation
# ...
# Successfully built straight-watcher-1.0.dev0.tar.gz and straight_watcher-1.0.dev0-py3-none-any.whl
unzip -l dist/*.whl
#   Length      Date    Time    Name
# ---------  ---------- -----   ----
#      2611  2023-08-14 18:53   straight_watch.py
#      2031  2023-08-14 18:53   straight_watch_callback.py
#       273  2023-08-14 19:09   straight_watcher-1.0.dev0.dist-info/METADATA
#        92  2023-08-14 19:09   straight_watcher-1.0.dev0.dist-info/WHEEL
#        39  2023-08-14 19:09   straight_watcher-1.0.dev0.dist-info/top_level.txt
#       502  2023-08-14 19:09   straight_watcher-1.0.dev0.dist-info/RECORD
# ---------                     -------
#      5548                     6 files
.venv/bin/python -m pip install -e .
# ...
# Successfully installed psutil-5.6.6 straight-watcher-1.0.dev0
.venv/bin/python -c 'import straight_watch_callback; print(straight_watch_callback)'
# <module 'straight_watch_callback' from '/straight.el/watcher/straight_watch_callback.py'>
.venv/bin/python -c 'import straight_watch; print(straight_watch)'
# <module 'straight_watch' from '/straight.el/watcher/straight_watch.py'>
```

> Or did I simply not find the right combination of configuration to make this work? (I tried different options for numerous hours and even looked through the setuptools source code.)

Not sure if I am understanding which would be the combinations that you are talking about.
The error message lists 3 possible solutions. All of them should work for the reproducer you have presented. Could you please clarify and/or provide a [minimal reproducer similar](https://stackoverflow.com/help/minimal-reproducible-example) to the snippet above?


[^1]: You can have an idea on how complicated this compromise is by reading the many threads in https://discuss.python.org/search?q=pep%20660.
[^2]: You can see more details of this configuration option in  https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

**Comment by raxod502-plaid** [comment]
Thanks for providing the solution, I can confirm that `py_modules` works. I had previously tried it with `packages=["straight_watch", "straight_watch_callback"]` instead of `py_modules=["straight_watch", "straight_watch_callback"]`, and that didn't work. I also had tried the suggested `packages=find_packages()` and `packages= find_namespace_packages()` and those had the same result. I had missed that `py_modules` was a separate option which would have different implications.

**Comment by abravalheri** [comment]
Oh, I see. Python nomenclature can be a bit tricky, modules are .py files and packages are directories.

Very easy to miss 😅

**Comment by ehkristen** [comment]
> Hi @raxod502-plaid, thank you very much for the report, please see some comments below
> 
> > With setuptools <61.0.0, installation works fine and the imports described above work fine.
> 
> This is probably related to the specific method that you were using for the installation (i.e. editable install). Editables installs are "complicated"™️:. Inherently they have to deal with a compromise "emulating the behaviour of a package installed normally" vs "allowing users to do changes like adding new files"[1](#user-content-fn-1-19b720d91095aa31d6fe2755fc4ffc1f), so not necessarily what you observe in an editable install is what the package configuration you have written is actually doing.
> 
> For example, if you try to build the package using Setuptools<60 "for real" (not in editable mode, see snippet below), you can see that the package configuration you are using results in an empty package with no `.py` file. This happens because in your configuration you do not specify `packages=[...]`[2](#user-content-fn-2-19b720d91095aa31d6fe2755fc4ffc1f); and before v61.0.0 setuptools would not attempt to derive that configuration option automatically.
> 
> ```shell
> > docker run --rm -it python:3.11-bullseye /bin/bash
> 
> git clone https://github.com/radian-software/straight.el/
> cd straight.el
> git reset --hard 9b11112b2e7aedd994feb2d8f95bd66dbc5749a5
> cd watcher
> 
> python -m venv .venv
> .venv/bin/python -m pip install 'setuptools==60.0.0' wheel build
> .venv/bin/python -m build --no-isolation
> unzip -l dist/*.whl
> # Archive:  dist/straight_watcher-1.0.dev0-py3-none-any.whl
> #   Length      Date    Time    Name
> # ---------  ---------- -----   ----
> #       300  2023-08-14 18:53   straight_watcher-1.0.dev0.dist-info/METADATA
> #        92  2023-08-14 18:53   straight_watcher-1.0.dev0.dist-info/WHEEL
> #         1  2023-08-14 18:53   straight_watcher-1.0.dev0.dist-info/top_level.txt
> #       344  2023-08-14 18:53   straight_watcher-1.0.dev0.dist-info/RECORD
> # ---------                     -------
> #       737                     4 files
> ```
> 
> Newer versions of `setuptools` will halt the build because this kind of wheel looks off (it is missing packages/modules), and it prefers to prompt the user to be explicit about it instead of creating a potentially problematic package.
> 
> > However, as of yet I have been unable to find any combination of setup.py and pyproject.toml options that allows the package to be installed and both modules to be imported. Either installation fails with a different error, or the package is installed with the modules not being importable.
> 
> The error message says:
> 
> ```
> If you are trying to create a single distribution with multiple modules
> on purpose, you should not rely on automatic discovery.
> Instead, consider the following options:
> 
> 1. set up custom discovery (`find` directive with `include` or `exclude`)
> 2. use a `src-layout`
> 3. explicitly set `py_modules` or `packages` with a list of names
> ```
> 
> You said option 2 is not possible for you, but have you tried options 1 or 3? What are the problems with those options?
> 
> For example, I gave it a try for option 3 (re-using the same project directory from the snippet above):
> 
> ```shell
> .venv/bin/python -m pip install 'setuptools==68'
> sed -i 's/)/    py_modules=["straight_watch", "straight_watch_callback"])/' setup.py  # add py_modules configuration.
> .venv/bin/python -m build --no-isolation
> # ...
> # Successfully built straight-watcher-1.0.dev0.tar.gz and straight_watcher-1.0.dev0-py3-none-any.whl
> unzip -l dist/*.whl
> #   Length      Date    Time    Name
> # ---------  ---------- -----   ----
> #      2611  2023-08-14 18:53   straight_watch.py
> #      2031  2023-08-14 18:53   straight_watch_callback.py
> #       273  2023-08-14 19:09   straight_watcher-1.0.dev0.dist-info/METADATA
> #        92  2023-08-14 19:09   straight_watcher-1.0.dev0.dist-info/WHEEL
> #        39  2023-08-14 19:09   straight_watcher-1.0.dev0.dist-info/top_level.txt
> #       502  2023-08-14 19:09   straight_watcher-1.0.dev0.dist-info/RECORD
> # ---------                     -------
> #      5548                     6 files
> .venv/bin/python -m pip install -e .
> # ...
> # Successfully installed psutil-5.6.6 straight-watcher-1.0.dev0
> .venv/bin/python -c 'import straight_watch_callback; print(straight_watch_callback)'
> # <module 'straight_watch_callback' from '/straight.el/watcher/straight_watch_callback.py'>
> .venv/bin/python -c 'import straight_watch; print(straight_watch)'
> # <module 'straight_watch' from '/straight.el/watcher/straight_watch.py'>
> ```
> 
>  > Or did I simply not find the right combination of configuration to make this work? (I tried different options for numerous hours and even looked through the setuptools source code.)
> 
> Not sure if I am understanding which would be the combinations that you are talking about. The error message lists 3 possible solutions. All of them should work for the reproducer you have presented. Could you please clarify and/or provide a [minimal reproducer similar](https://stackoverflow.com/help/minimal-reproducible-example) to the snippet above?
> 
> ## Footnotes
> 1. You can have an idea on how complicated this compromise is by reading the many threads in https://discuss.python.org/search?q=pep%20660. [↩](#user-content-fnref-1-19b720d91095aa31d6fe2755fc4ffc1f)
> 2. You can see more details of this configuration option in  https://setuptools.pypa.io/en/latest/userguide/package_discovery.html [↩](#user-content-fnref-2-19b720d91095aa31d6fe2755fc4ffc1f)

I’m experiencing a similar issue, but option 2 is not an option for me. I tried setting up custom discovery which did not work (it still complained about the layout and ignored the exclude call). I also tried explicitly listing out the packages and modules, but it seemingly still tries to use auto discovery regardless….

I had my script working setuptools (using setup.py) with Python 3.8, but this issue is now occurring after upgrading to 3.11
