### ISSUE TITLE
editable_wheel is broken in 68.1.0

### ISSUE THREAD

**Issue by emontnemery** [pypa/setuptools#4019]
### setuptools version

setuptools==68.1.0

### Python version

Python 3.11

### OS

Linux

### Description

setuptools 68.1.0 broke editable_wheels due to commit https://github.com/pypa/setuptools/commit/db3743a90b4948ca4d8435ed52bc76ca98152e57 from https://github.com/pypa/setuptools/pull/3995

To my understanding, the problem is that `_find_nested_spec` passes the wrong path to `PathFinder.find_spec(rest, path=[parent_path])`

### Expected behavior

Pass the full path to `PathFinder.find_spec`.
Doing that requires a lookup to happen first though, which pretty much defeats the purpose of db3743a90b4948ca4d8435ed52bc76ca98152e57 though as I understand it, which was to let Python handle the case insensitive lookup.

### How to Reproduce

This is how `PathFinder.find_spec` treats its input path, note how it only cares about the tail of the name to lookup:
```
python3 -vv
>>> from importlib.machinery import PathFinder
>>> PathFinder.find_spec("components.persistent_notification.loader", ["/home/erik/development/home-assistant_fork/"])
```

### Output

```
# trying /home/erik/development/home-assistant_fork/loader.cpython-311-x86_64-linux-gnu.so
# trying /home/erik/development/home-assistant_fork/loader.abi3.so
# trying /home/erik/development/home-assistant_fork/loader.so
# trying /home/erik/development/home-assistant_fork/loader.py
# trying /home/erik/development/home-assistant_fork/loader.pyc
```

**Comment by abravalheri** [comment]
Hi @emontnemery, thank you for opening the issue.

Could you please provide the [full reproducer](https://stackoverflow.com/help/minimal-reproducible-example)? In your example it is not clear where the `home-assistant_fork` comes from, or `components.persistent_notification.loader`...

**Comment by emontnemery** [comment]
I was trying to illustrate that the way in which `_find_nested_spec` calls `importlib.machinery.PathFinder.find_spec` does not seem to be correct.

Here's a reproduction of the actual error we see:
### Prerequisite:
Python 3.11 is the current interpreter, for example selected by pyenv
### Step by step
```
mkdir tmp
cd tmp
python3 -m venv .venv
source .venv/bin/activate
pip3 install setuptools==68.1.0
git clone https://github.com/home-assistant/core
pip3 install -e core
python3
>>> from homeassistant.components.persistent_notification import config
>>> config
<module 'homeassistant.components.persistent_notification.config' from '/home/erik/core/homeassistant/config.py'>
```

The problem is that, in this example, `_EditableFinder._find_nested_spec` calls `PathFinder.find_spec` like this:
```
PathFinder.find_spec("components.persistent_notification.config", ["/home/erik/tmp2/core/homeassistant/"])
```

Which makes `PathFinder.find_spec` look for `config.py` in `/home/erik/tmp2/core/homeassistant/` instead of in `/home/erik/tmp2/core/homeassistant/components/persistent_notification`

**Comment by emontnemery** [comment]
Thanks @abravalheri, that works!
