### ISSUE TITLE
zip-safe analysis isn't quiet

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#405]
Originally reported by: **jaraco (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

Consider this example installation run:

```
> python2.7 -m easy_install -q importlib2
zip_safe flag not set; analyzing archive contents...
importlib2.__init__: module references __path__
importlib2._bootstrap: module references __file__
importlib2._bootstrap: module references __path__
importlib2.util: module references __path__
importlib2._fixers._modules: module references __file__
importlib2._fixers._modules: module references __path__
importlib2._version.__init__: module references __file__
```

The `-q` option suppressed most of the output, but not the zip-safe analysis. That should be made quiet also.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/405

**Comment by abravalheri** [comment]
I suppose we can close this issue now that `easy_install` has been deprecated and widely replace by `pip` (there should be no much point in investing energy on it, right?)
