### ISSUE TITLE
[Docs] Preview pop-up on a link covers the link itself

### ISSUE THREAD

**Issue by Feuermurmel** [pypa/setuptools#4064]
### Summary

I've come across an issue with that breaks the online documentation completely for me. Whenever I move my mouse pointer over a link to a different part of the documentation, a pop-up appears that covers the link, making it near-impossible to click the link. See this screen recording of the situation that this has manifested first for me:

https://github.com/pypa/setuptools/assets/50332/af946044-7222-4e2d-b090-c771be758598

(On this page: https://setuptools.pypa.io/en/latest/pkg_resources.html)

### OS / Environment

Safari 16.6, macOS 12.6.8.

### Additional Information

IMHO, as it presents itself to me, this feature has downsides that are orders of magnitude bigger that it's upsides. My browser already allows me to preview a page by triple-tapping on the trackpad (macOS) or long-pressing (iOS), so it doesn't add a benefit on these platforms.

---

As an additional note: Even if this feature was implemented in a way where it wouldn't make it impossible to click on some links, it would still be an accessibility issue for me:

I'm on the ADD spectrum and I use my mouse pointer for focussing while reading. It's very natural for me to move my pointer along the text while reading. Such an unavoidable popup will draw my focus away from what I am reading (because it appears when I'm not expecting it and haven't performed an explicit action to make it appear). I'm having this issue also e.g. on GitHub, where some links have pop-ups that appear on mouse hovering.

If you intend on keeping these pop-ups, there is something that you could do to make it a bit less intrusive for people like me (I can't speak for everyone on the ADD spectrum of course): Make the pop-up appear immediately when entering the link's region _and also_ disappear immediately when leaving the region, instead of after a short delay. For example, buttons and links that change appearance while hovering or tool-tips in UIs that appear immediately are much less distracting to me. I think my brain is more likely to associate my action with the appearance of the pop-up and thus able to ignore the stimulus.

But hey, thanks for your work anyways!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @Feuermurmel thank you very much for the feedback and I am sorry to hear you are having usability problems.

In #4065 I am proposing to remove the plugin (I don't think we loose to much if we just remove this feature). I hope that is good enough.

What I would suggest in the name of "the betterment of the ecosystem" is to bring this feedback also to the authors of https://github.com/readthedocs/sphinx-hoverxref. This way they can try to incorporate suggestions or implement modifications that will improve more documentation websites (other than setuptools).
