### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by guitarmeetsscience** [pypa/setuptools#4067]
### setuptools version

setuptools >57

### Python version

python 3.9, 3.10 probably others

### OS

Linux, Win

### Description

I mean....seriously... 
error in googleads setup command: use_2to3 is invalid.
For anybody doing anything besides maybe coming up with LaTex equations this is a dealbreaker. setuptools - you know you're better than that. Bring back 2to3 already. Sheesh

### Expected behavior

it to work

### How to Reproduce

just try installing anything that wants the super-dumb googleads package

### Output

```console
<fart> error in googleads setup command: use_2to3 is invalid. <fart> <fart> <pffffft>
```

**Comment by abravalheri** [comment]
To implement such a feature, setuptools depends on the standard library, but Python itself has deprecated the functionality (https://bugs.python.org/issue40360 - it was supposed to go away in Python 3.10 when it was removed from setuptools - #2086 - but got postponed).

The removal of the feature in setuptools went through a deprecation cycle (#2096), with deprecation warnings being issued so the developers could take action before the removal (#2731).

I suggest contacting the package in question and informing them they should migrate the code base to Python 3.

Alternatively, you can try to find a setuptools plugin that backfills the functionality or create one yourself.
