### ISSUE TITLE
[BUG] `pip install -e .` uses `pyproject.toml` but the file doesn't exist

### ISSUE THREAD

**Issue by eight04** [pypa/setuptools#4077]
### setuptools version

68.2.2

### Python version

CPython (3.10.13)

### OS

Ubuntu 22.04.3

### Additional environment information

This only happens on Github action. I can't reproduce on my local machine (Windows 10)

### Description

Also reported at https://github.com/pypa/pip/issues/12339, @uranusjr said it belongs to setuptools.

I'm maintaining an old package using `setup.py`. There is a `pip install -e .` command when building on Github action.

However, the result of `pip install -e .` looks weird. It seems that it tries to build the wheel using `pyproject.toml` which doesn't exist at all:
```
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
```
And it seems that scripts written in `setup.py` doesn't run.

### Expected behavior

When running the same command on my local machine (Windows 10), it seems to use `setup.py` correctly:
```
C:\Users\eight04\dev\node_vm2>pip install -e .
Obtaining file:///C:/Users/eight04/dev/node_vm2
  Preparing metadata (setup.py) ... done
Installing collected packages: node-vm2
  Attempting uninstall: node-vm2
    Found existing installation: node-vm2 0.4.5
    Uninstalling node-vm2-0.4.5:
      Successfully uninstalled node-vm2-0.4.5
  Running setup.py develop for node-vm2
Successfully installed node-vm2-0.4.5
```

### How to Reproduce

This happens on Github action so you can view the workflow here:
https://github.com/eight04/node_vm2/actions/runs/6486910183/workflow

### Output

Full log:
https://github.com/eight04/node_vm2/actions/runs/6486910183/job/17616088836

**Comment by abravalheri** [comment]
Hi @eight04 , thanks for opening the issue...

> This only happens on Github action. I can't reproduce on my local machine (Windows 10).

Uuummm without a deterministic reproducer it is very difficult to investigate and help...

Could you please try to create a [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example) in a bran new virtual environment in your local machine? Also could you please update `pip` to its latest version and then `pip uninstall` both `setuptools` and `wheel` from this virtual environment before running your edutable installation?

Finally when running the editable install, could you please use `pip` in the verbose mode and pass the `-C verbose=true` flag? (E.g. `pip -vvv install -e . -C verbose=true`)

**Comment by eight04** [comment]
I'm going to close this since it works as intended.

I also found why I couldn't reproduce on my local machine. It seems that if `wheel` is installed in the environment, `pip install -e .` still runs `setup.py develop`. If `wheel` is not installed (e.g. on Github action), pip creates a "build-env" and use the new method.
