### ISSUE TITLE
[BUG] `setuptools._distutils.version.Version` - AttributeError: 'Version' object has no attribute 'parse'

### ISSUE THREAD

**Issue by Gadgetoid** [pypa/setuptools#4089]
### setuptools version

68.2.2

### Python version

3.11.2

### OS

Raspberry Pi OS (Bookworm)

### Description

It looks like `setuptools._distutils.version.Version` attempts to call `self.parse()` in `__init__` if a version string is supplied.

Since the `parse` method is not defined, it will:

1. Raise `AttributeError: 'Version' object has no attribute 'parse'`
2. Never emit the deprecation warning

Additionally calling `Version` with no arguments triggers a  `RecursionError: maximum recursion depth exceeded` exception, since the DeprecationWarning attempts to get a string representation of the class which causes a recursion since `__repr__` - in lieu of a `__str__` method - calls itself.

It's self evident from the source that something is wrong here- https://github.com/pypa/setuptools/blob/2384d915088b960999ca74fb81ce70bffd17b082/setuptools/_distutils/version.py#L45-L93

`Version` does not supply `parse` or `__str__` via a parent class or otherwise.

### Expected behavior

I know the answer is "don't use this, it's deprecated" but should `Version` not still work with a:

```
<stdin>:1: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```

And no errors.

Fail with an error?

Not exist at all?

### How to Reproduce

```python
from setuptools._distutils import version
version.Version("1.6.3")
```

Or

```python
from setuptools._distutils import version
version.Version()
```

### Output

```console
>>> from setuptools._distutils import version
>>> version.Version("1.6.3")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sandiska1/.virtualenvs/pimoroni/lib/python3.11/site-packages/setuptools/_distutils/version.py", line 54, in __init__
    self.parse(vstring)
    ^^^^^^^^^^
AttributeError: 'Version' object has no attribute 'parse'
```

```console
>>> version.Version()
<stdin>:1: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sandiska1/.virtualenvs/pimoroni/lib/python3.11/site-packages/setuptools/_distutils/version.py", line 63, in __repr__
    return "{} ('{}')".format(self.__class__.__name__, str(self))
                                                       ^^^^^^^^^
  File "/home/sandiska1/.virtualenvs/pimoroni/lib/python3.11/site-packages/setuptools/_distutils/version.py", line 63, in __repr__
    return "{} ('{}')".format(self.__class__.__name__, str(self))
                                                       ^^^^^^^^^
  File "/home/sandiska1/.virtualenvs/pimoroni/lib/python3.11/site-packages/setuptools/_distutils/version.py", line 63, in __repr__
    return "{} ('{}')".format(self.__class__.__name__, str(self))
                                                       ^^^^^^^^^
  [Previous line repeated 492 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by abravalheri** [comment]
Hi, can you reproduce this without importing from `setuptools._distutils`?

Imports from `setuptools._distutils` are not supported, and are know to cause problems.

The fact that there is a `_distutils` inside `setuptools` is a private implementation detail. The import is not supposed to work without passing through the `MetaPathFinder`. If you want to use `distutils` please import using the `distutils` name directly...

Please also note that the docstring for the class says that `distutils.version.Version` is an abstract class, so it will not work if used without the proper subclassing.

**Comment by abravalheri** [comment]
I think we should close this for now, having in mind that the class is abstract.

If anyone would like to change that, the best way would be to discuss the viability  and provide a follow-up PR in the `pypa/distutils` repository.

**Comment by Gadgetoid** [comment]
Agreed- if it's deprecated then there's no reason to change it. `LooseVersion` and `StrictVersion` both work as expected.

I was operating on a misunderstanding while trying to add version parsing in a legacy setup.py. It's been a long day. Sorry.
