### ISSUE TITLE
MinGW without vcruntime140 and without distutils

### ISSUE THREAD

**Issue by qwenger** [pypa/setuptools#4101]
Hi,

I maintain https://github.com/PetterS/quickjs. We target Linux, macOS and Windows. On Windows, we rely on the MinGW tooling (`python setup.py build -c mingw32`).

For years we have monkey-patched distutils for this to work (https://github.com/PetterS/quickjs/blob/master/setup.py#L18). If we don't, we get `C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lvcruntime140`.

We don't see why we would need to link with the vcruntime when building with MinGW in general, and in particular we have no use for it in quickjs.
And distutils is deprecated with removal planned for Python 3.12.

So: what is the official way to handle this situation, without vcruntime (unless you can point an actual reason for us to link it in), without using deprecated modules and without monkey-patching setuptools' internals?

Thanks in advance.

EDIT: bonus points if this official way allows us to drop setup.py completely in favor of the modern, declarative way. (setup.cfg? pyproject.toml? build.py?)

**Comment by abravalheri** [comment]
> So: what is the official way to handle this situation, without vcruntime (unless you can point an actual reason for us to link it in), without using deprecated modules and without monkey-patching setuptools' internals?

My personal opinion would be that the best course of action here would be contacting the [`pypa/distutils`](https://github.com/pypa/distutils) maintainers and discussing the shortcomings of the existing implementation and asking if they would accept a PR.

> And distutils is deprecated with removal planned for Python 3.12.

Please note that `distutils` is removed from the stdlib, but it has maintenance support via the `pypa/distutils` repository. In turn, `distutils` is effectively exposed to the Python import system when you install `setuptools`. Of course, the recommendation is whenever possible "import stuff" from the `setuptools` namespace. Please have a look on this related discussion https://github.com/pypa/setuptools/issues/2806 (specially these comments https://github.com/pypa/setuptools/issues/2806#issuecomment-1193138306 and https://github.com/pypa/setuptools/issues/2806#issuecomment-1193336591)

**Comment by qwenger** [comment]
I wasn't at all aware of that out-of-stdlib distutils project. You're right, I'll ask over there regarding vcruntime. It looks like there's already some talk regarding MinGW compiling going on.

Closing for now, we'll see once that distutils part is fixed how far we can standardize the setuptools side in our use-case, and if needed open a new issue on that specific topic.

Thanks a lot!
