### ISSUE TITLE
Doc "Building Extension Modules" doesn't have the attributes of class setuptools.Extension.

### ISSUE THREAD

**Issue by qqwqqw689** [pypa/setuptools#4140]
### Summary

Doc "Building Extension Modules" doesn't have the attributes of class setuptools.Extension.

https://setuptools.pypa.io/en/latest/userguide/ext_modules.html

### Additional Information

None.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
The attributes are not exposed via public API at this stage.
The docs mention the constructor parameters.
