### ISSUE TITLE
[BUG] Using find_namespace_packages(where=source) in combination with jupyter notebook

### ISSUE THREAD

**Issue by SimonRubenDrauz** [pypa/setuptools#4156]
### setuptools version

setuptools==69.0.2

### Python version

Python 3.10.11

### OS

Windows 10 Enterprise

### Description

My project root directory looks like this

project_root_directory
├── setup.cfg
├── setup.py
├── ...
└── source/
└── tutorials

My tests are under src. In src I have a data package which I integrate as namespace package. In order to find the namespace packages I use packages=find_namespace_packages(where="source"), package_dir={"": "source"} and include_package_data=True. 

If I then start a jupyter notebook in the tutorials folder and try to import source I get a ModuleNotFound Error. This does not happen if I just say packages=find_namespace_packages() and omit package_dir.

The tests under source tested by pytest work fine.

### Expected behavior

No matter if I use find_namespace_packages without or with passing _where_ and defining the package_dir, Jupyter notebooks should work. 

### How to Reproduce

1. Checkout the following repo https://github.com/e2nIEE/pandapipes/pull/578
2. python -m pip install --upgrade pip
3. python -m pip install pytest nbmake pytest-xdist pytest-split igraph 
4. python -m pip install -e .
5. Either run python -m pytest --nbmake -n=auto "./tutorials" or open a jupyter notebook and try to execute it. Source (pandapipes) cannot be imported. In case of pytest all tests fail as the source cannot be found.

### Output

import os
import pandas as pd
import pandapower.control as control
from pandapower.timeseries import DFData
from pandapower.timeseries import OutputWriter
from pandapipes.timeseries import run_timeseries
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 6
      4 from pandapower.timeseries import DFData
      5 from pandapower.timeseries import OutputWriter
----> 6 from pandapipes.timeseries import run_timeseries

ModuleNotFoundError: No module named 'pandapipes'
=============================================== short test summary info ===============================================
FAILED tutorials/Unterstanding pandapipes' core.ipynb::
FAILED tutorials/creating_a_simple_network.ipynb::
FAILED tutorials/height_difference_example.ipynb::
FAILED tutorials/circular_flow_in_a_district_heating_grid.ipynb::
FAILED tutorials/building_a_storage_controller.ipynb::
FAILED tutorials/ein_einfaches_netz_erstellen.ipynb::
FAILED tutorials/höhendifferenzen.ipynb::
FAILED tutorials/minimal_example.ipynb::
FAILED tutorials/coupled_nets_h2_p2g2p.ipynb::
FAILED tutorials/simple_plot.ipynb::
FAILED tutorials/multienergienetze.ipynb::
FAILED tutorials/standard_libraries.ipynb::
FAILED tutorials/temperature_calculation.ipynb::
FAILED tutorials/simple_time_series_example.ipynb::
================================================= 14 failed in 26.78s =================================================

**Comment by SimonRubenDrauz** [comment]
@abravalheri thanks a lot for your fast reply.

Following your questions and checking if your ideas solve the problem, I realised two things:
1. Locally it seemed that running pip install . solved the problem
2. On the CI/CD pipeline on github it was still not working. However, I now had the chance to compare the pip lists and adjust the installed packages accordingly. However, the tests are still failing. Therefore, I think it might be a win/linux problem. Do you have any suggestions?

The CI/CD pipeline I am talking about can be found here:
https://github.com/e2nIEE/pandapipes/actions/runs/7187195599/job/19574255923?pr=578

**Comment by abravalheri** [comment]
It is difficult to know...

Could you please try the other experiments I proposed?

Since you are using a "src-like" layout, I suppose the installation method for `pip install -e` is to use a `.pth` file to augment `sys.path`. So you can also try to print `sys.path` and check if the `site-packages` folder of your virtual environment contains the correct `.pth` file (once you localize those files  you can also read their contents to see if they contain the correct path for your project).

It might be the case the libraries you are using is not compatible with editable installs.

I believe the best is to stablish weather the installation is working fine outside of the context which runs the tests. For example, if you can run a regular Python REPL (the standard Python command, not Jupyther) and import your module, this means that the installation is correct and probably there is something in your test setup that is not working fine or is not compatible...

**Comment by SimonRubenDrauz** [comment]
Hey @abravalheri,

I just realized my mistake. Unfortunately I missed a further sublevel. Instead of taking src/source, I directly took source. I restructured my package now and now integrated a sublevel src. 

Sry for the trouble and thanks again for your fast help. 

I will close the issue now!
