### ISSUE TITLE
[BUG] posix_local KeyError loading distutils scheme, using setuptools over Debian 12 Bookworm

### ISSUE THREAD

**Issue by adiel91** [pypa/setuptools#4176]
### setuptools version

setuptools==69.0.3

### Python version

Python 3.11.4

### OS

Debian 12.4 Bookworm

### Description

We have a simple package with custom setup.py for it.
Until now we've used Debian 11 Bullseye with Python 3.11.4 and setuptools==68.2.2 and had no issues.

Moving to Debian 12 Bookworm with mentioned setuptools version 69.0.3 -
We observed issues loading scheme (See log below).

**Notes**

I've checked WA Suggested in:
https://github.com/pypa/setuptools/issues/2936
Of:
SETUPTOOLS_USE_DISTUTILS=stdlib
When installing setuptools, but that didn't help.

**Only thing worked was downgrading:**
`
python3 -m pip install --force-reinstall --no-cache-dir 'setuptools<59.7.0'
Collecting setuptools<59.7.0
  Downloading setuptools-59.6.0-py3-none-any.whl (952 kB)
`

* If any other env information required please let me know
* The package we're trying to install is a custom package (not traditional pypi package), that has custom setup.py.
if needed i'll share the setup.py content.
Not issues were observed with same implementation over Debian 11 Bullseye

### Expected behavior

No errors during load scheme

### How to Reproduce

Not sure, that package is a custom package in our env, not traditional "pypi" package
( but actually one we built setup.py explicitly )

### Output

```
Traceback (most recent call last):
  File "/usr/src/sx_sdk/BUILD/sys_sdk-4.6.2900-158/python_sdk_api/setup.py", line 456, in <module>
    setup(name=PACKAGE_NAME,
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/src/sx_sdk/BUILD/sys_sdk-4.6.2900-158/python_sdk_api/setup.py", line 351, in finalize_options
    super(python_sdk_api_install, self).finalize_options()
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 390, in finalize_options
    self.finalize_unix()
  File "/usr/lib/python3.11/_distutils_system_mod.py", line 60, in finalize_unix
    super().finalize_unix()
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 580, in finalize_unix
    self.select_scheme("posix_prefix")
  File "/usr/lib/python3.11/_distutils_system_mod.py", line 56, in select_scheme
    super().select_scheme(name)
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 605, in select_scheme
    _select_scheme(self, name)
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 131, in _select_scheme
    scheme = _inject_headers(name, _load_scheme(_resolve_scheme(name)))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 152, in _load_scheme
    return _load_schemes()[name]
           ~~~~~~~~~~~~~~~^^^^^^
KeyError: 'posix_local'
```

**Comment by adiel91** [comment]
Following more versions testing, i've found out the issue doesn't reproduce on setuptools==59.8.0, but starts reproducing on setuptools==60.0.0

**Comment by abravalheri** [comment]
Hi @adiel91 thank you very much for reporting this.

If I am not mistaken `posix_local` is a custom installation scheme introduced by Debian patches (possibly https://sources.debian.org/src/python3.11/3.11.2-6/Lib/_distutils_system_mod.py/#L152-L159).

This schema does not seem to be defined in the `sysconfig` for [CPython 3.11](https://github.com/python/cpython/blob/3.11/Lib/sysconfig.py#L26)[^1].

Probably the best people to advise on the way forward would be the Debian folks. Have you tried reporting it in the Debian relevant forums?

---

> I've checked WA Suggested in:
> #2936
> Of:
> SETUPTOOLS_USE_DISTUTILS=stdlib
> When installing setuptools, but that didn't help.

Please note that the suggestions is to set `SETUPTOOLS_USE_DISTUTILS` whenever `setuptools` code is executed, not only while installing `setuptools`. Also note that this is valid only for Python < 3.12.


[^1]: So it can only come from Debian patches...

**Comment by adiel91** [comment]
> Hi @adiel91 thank you very much for reporting this.
> 
> If I am not mistaken `posix_local` is a custom installation scheme introduced by Debian patches (possibly https://sources.debian.org/src/python3.11/3.11.2-6/Lib/_distutils_system_mod.py/#L152-L159).
> 
> This schema does not seem to be defined in the `sysconfig` for [CPython 3.11](https://github.com/python/cpython/blob/3.11/Lib/sysconfig.py#L26)[1](#user-content-fn-1-8f70619e5cfeb956be821dcf4d6ec490).
> 
> Probably the best people to advise on the way forward would be the Debian folks. Have you tried reporting it in the Debian relevant forums?
> 
> > I've checked WA Suggested in:
> > #2936
> > Of:
> > SETUPTOOLS_USE_DISTUTILS=stdlib
> > When installing setuptools, but that didn't help.
> 
> Please note that the suggestions is to set `SETUPTOOLS_USE_DISTUTILS` whenever `setuptools` code is executed, not only while installing `setuptools`. Also note that this workaround is valid only for Python < 3.12.
> 
> ## Footnotes
> 1. So it can only come from Debian patches... [↩](#user-content-fnref-1-8f70619e5cfeb956be821dcf4d6ec490)

Hi,
It might indeed be some Debian related issue, i'm not sure - The issue actually occurs,
If we replace the system interpreter from upstream (which is Python 3.11.2), with a compilation of Python3.11.4 from sources.

The reason we do that is that we need python compiled with full optimizations, thus we run:

`./configure --enable-optimizations --disable-test-modules --enable-shared --with-lto=full --prefix=/usr`

Followed by 
`make -j64 && make install`

(and not altinstall - since we want the system one to be replaced).

Questions:
1. Do you know where should I report such issue to debian?
2. I don't understand about posix_local not defined in CPython 3.11 as you mentioned.
If that's true - why with upstream python3.11.2 over debian, no such issue observed?
The CPython for it is the same..

**Comment by abravalheri** [comment]
> 1. Do you know where should I report such issue to debian?

Hi @adiel91, unfortunately I am not familiar with the Debian development cycle and forums either, so I will not be able to advise on that. All links I listed here I found using my google-fu 😅.


> 2\. I don't understand about posix_local not defined in CPython 3.11 as you mentioned.
>     If that's true - why with upstream python3.11.2 over debian, no such issue observed?
>     The CPython for it is the same. Or its maybe since upstream python doesn't try to use that posix_local scheme to begin with?

Debian also [patches](https://sources.debian.org/src/python3.11/3.11.2-6/debian/patches/sysconfig-debian-schemes.diff/) the `sysconfig` module and introduces their custom `posix_local` there. The copy of `distutils` distributed by `setuptools` [only augments the already existing info in `sysconfig`](https://github.com/pypa/setuptools/blob/v69.0.3/setuptools/_distutils/command/install.py#L107-L120). Therefore, if `sysconfig` contains the `posix_local` ([as happens in the Debian patch](https://sources.debian.org/src/python3.11/3.11.2-6/Lib/sysconfig.py/#L51-L62)), then no issue will be observed. In other words, Debian uses comprehensive patching of Python in multiple modules, in a way that they are interconnected. And they test these patches to make sure they work well together.


---

I have a question for you also:

Do the copy you use for compiling Python 3.11 contains the `_distutils_system_mod.py` file? (i.e. does this file get created once you install your Python version from scratch?)
   - Or is it a file that is already present in the file system due a pre-existing installation of Python? And then it gets picked up because its parent directory is listed under `sys.path` in the custom Python installation?
      - If the file is not present in your custom Python, it might be an interoperability/isolation issue between the version of Python you are using and the version of Python that comes pre-installed in the system... (i.e. an isolation leak between 2 conflicting Python installations).
      - So maybe it is not even the case of contacting Debian, but rather ensuring that the version you are installing of Python is properly isolated and does not accidentally loads directories provided by different installations (e.g. in `sys.path` or `site.PREFIXES/USER_SITE/USER_BASE` or `sitecustomize.py`)


---

> **I also found out some WA:** If I edit the file /usr/lib/python3.11/site-packages/setuptools/_distutils/command/install.py, adding a simple patch to add posix_local to install schemes, same as posix_prefix, everything seems to work correctly
> 
> `INSTALL_SCHEMES['posix_local'] = INSTALL_SCHEMES['posix_prefix']`

Unfortunately I also don't know how `posix_local` is intended to work, so I cannot assess if this patch is sound.

**Comment by adiel91** [comment]
Hi @abravalheri ,
Thanks for clarifying the patching behavior. I'll try to use my own google-fu to find out the proper place to report it to Debian.

Regarding your questions -

> Do the copy you use for compiling Python 3.11 contains the `_distutils_system_mod.py` file? (i.e. does this file get created once you install your Python version from scratch?)
> * Or is it a file that is already present in the file system due a pre-existing installation of Python?

I've checked 2 systems - One with upstream python 3.11.2 (No changes), one with our "custom" 3.11.4 which we compiled from sources retrieved from Python.org.

On both systems, file exists:
`root@localhost:~# find /usr -name '*system_mod.py*'
/usr/lib/python3.11/_distutils_system_mod.py
`
And has exact same content as the other system.

> And then it gets picked up because its parent directory is listed under `sys.path` or `site.PREFIXES/USER_SITE/USER_BASE` in the custom Python installation?
>

Not sure about "gets picked up", but sys.path in both cases is as follows:
`Python 3.11.4 (main, Jan  5 2024, 09:03:00) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.path
['', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/lib/python3.11/site-packages']
`
`Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.path
['', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/local/lib/python3.11/dist-packages', '/usr/lib/python3/dist-packages']
`

Is that information helpful to you in order to help me? :D

Thanks

**Comment by abravalheri** [comment]
Hi @adiel91, you mentioned that in both cases `/usr/lib/python3.11/_distutils_system_mod.py`. But was it written there by your custom installation of Python, or is this an already existing file before you install Python from the source code?

**Comment by adiel91** [comment]
> Hi @adiel91, you mentioned that in both cases `/usr/lib/python3.11/_distutils_system_mod.py` is present. But was it written there by your custom installation of Python, or is this an already existing file before you install Python from the source code?
> 
> I am trying to determine if your installation is attempting to add `_distutils_system_mod.py` purposefully (as part of the source code you are compiling), or if it is only accidentally "inheriting" something that was already there, and that is not meant to be interoperable with the version of Python you are compiling from scratch.

Hi @abravalheri 
I actually answered that :)

"
On both systems, file exists:
root@localhost:~# find /usr -name '*system_mod.py*' /usr/lib/python3.11/_distutils_system_mod.py 
And has exact same content as the other system.
"

both systems = 1 system with the upstream python, no custom python installation, 2nd system with the custom python installation.
Maybe the misunderstanding is with definition of 2nd system -
With custom python means - The system was identical to 1st one (had upstream python installed), and then we installed our custom python from sources.

So it seems the file was always there

**Comment by abravalheri** [comment]
> So it seems the file was always there

If the file was already there before you installed Python from scratch **and** installing Python from the source code according to the method you are using does not create any `_distutils_system_mod.py`, then I think you are falling into the problem that I previously referred to as "it[^1] gets picked up" or "accidentally inheriting something that was already there". I.e. effectively there is an isolation problem between the 2 distinct Python installations, and they are accidentally sharing incompatible files.

In that scenario, your installation of Python uses pre-existing directories for `sys.path` (and/or `sys.prefix` and/or `site.PREFIXES/USER_SITE/USER_BASE` etc ...) that contain files designed by the Debian folks to interoperate with their customised/patched codebase, and therefore are incompatible with the Python source code distributed by python.org (or any vanilla Python distribution).

Solutions for that problem include:

1. Completely uninstalling the pre-installed Python and ensuring that all modules are removed from all the locations as found in `sys.path`, `sys.prefix`, `site.PREFIXES/USER_SITE/USER_BASE`, etc... **before** installing a new Python.
2. Modifying the compilation parameters, configuration files, etc... (maybe even patching the source code) when compiling Python to make sure the new installation uses a completely different set of directories for  `sys.path`, `sys.prefix`, `site.PREFIXES/USER_SITE/USER_BASE`.

Alternatively you also can use a different base image that does not use custom patching for the Python packages distributed by the OS (differently from Debian).

[^1]: The `_distutils_system_mod.py` module.

**Comment by abravalheri** [comment]
Thank you @adiel91
