### ISSUE TITLE
[BUG] Building wheel with `ext_modules` on Windows 10 with VC throws linker error

### ISSUE THREAD

**Issue by charelstoncrabb** [pypa/setuptools#4180]
### setuptools version

63.2.0

### Python version

3.10

### OS

Windows 10 Pro 64-bit

### Additional environment information

Ran from within an `x64 Native Tools Command Prompt for VS 2022` terminal; using VS 2022 pro.

Venv setup:
```
(venv) C:\Users\me\source\setuptools-test>pip freeze
build==1.0.3
colorama==0.4.6
packaging==23.2
pyproject_hooks==1.0.0
tomli==2.0.1
```

### Description

I have a basic package as follows:

```
root/
├── setup.py
└── src
    └── foo
        └── bar.c
```

Content of `setup.py`:
```
from setuptools import Extension, setup, find_packages
setup(
    name="foo",
    version="0.0",
    packages=find_packages(where="src"),
    ext_modules=[
        Extension(
            name="foo.bar",
            sources=["src/foo/bar.c"],
        ),
    ],
)
```

Content of `bar.c`:
```
int foobar(int x)
{
    return x*2;
}
```

Now, the *first* time I run the command to build a wheel `python -m build --wheel` I get a linker error `LINK : error LNK2001: unresolved external symbol PyInit_bar` (full output below), but if I immediately rerun this command the *command* succeeds (`Successfully built foo-0.0-cp310-cp310-win_amd64.whl`) but on pip installing the resulting wheel it throws an import error that seems to point to the heart of the issue

```
(venv) C:\Users\me\source\setuptools-test>python -c "import foo.bar"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed while importing bar: %1 is not a valid Win32 application.
```

It seems as though, despite the fact that I'm running completely within the `x64 Native Tools Command Prompt` and using a 64-bit python distro (confirmed via [this](https://stackoverflow.com/questions/1405913/how-do-i-determine-if-my-python-shell-is-executing-in-32bit-or-64bit) method: `python -c "import sys;print(\"%x\" % sys.maxsize, sys.maxsize > 2**32)"` --> 
`7fffffffffffffff True`), the python package is expecting the compiled extension to be 32-bit?

The issue I'm seeing looks to be almost identical to [this SO question](https://stackoverflow.com/questions/42150189/linker-error-1120-when-trying-to-build-c-extension-for-python-using-setuptools):, however I am indeed running from within a 64-bit VS environment against a confirmed 64-bit version of python.

(Note I also tried using the `python setup.py bdist_wheel` command in case it was an issue with the `build` wrapper specifically, but I get the same results as well as a deprecation warning about using setup.py)

Any help/suggestions would be greatly appreciated if I'm overlooking something simple.

### Expected behavior

I would expect that running `python -m build --wheel` with 64-bit python from a 64-bit VS terminal will compile the extension as 64-bit and that the installed wheel will then expect a 64-bit DLL for the module.

### How to Reproduce

1. Set up the directory structure as above
2. Open an `x64 Native Tools Command Prompt for VS 2022` terminal
3. Create a virtual environment that has `build` installed
4. Run `python -m build --wheel` <--first time throws linker error
5. Run `python -m build --wheel` <--second time apparently succeeds
6. Pip install the wheel `foo-0.0-cp310-cp310-win_amd64.whl`
7. Run command `python -c "import foo.bar"` <-- throws import error `%1 is not a valid Win32 application`

**Note** that I am seeing the exact same linker error when running this same process on github actions' default `windows-latest` runner.

### Output

#
Output from **first** `python -m build --wheel` command:
```
(venv) C:\Users\me\source\setuptools-test>python -m build --wheel
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting build dependencies for wheel...
running egg_info
creating foo.egg-info
writing foo.egg-info\PKG-INFO
writing dependency_links to foo.egg-info\dependency_links.txt
writing top-level names to foo.egg-info\top_level.txt
writing manifest file 'foo.egg-info\SOURCES.txt'
reading manifest file 'foo.egg-info\SOURCES.txt'
writing manifest file 'foo.egg-info\SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
running bdist_wheel
running build
running build_ext
building 'foo.bar' extension
creating build
creating build\temp.win-amd64-cpython-310
creating build\temp.win-amd64-cpython-310\Release
creating build\temp.win-amd64-cpython-310\Release\src
creating build\temp.win-amd64-cpython-310\Release\src\foo
"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\me\AppData\Local\Temp\build-env-d_11j2_6\include -IC:\Users\me\AppData\Local\Programs\Python\Python310\include -IC:\Users\me\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.7.2\include\um" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.7.2\include\um" /Tcsrc/foo/bar.c /Fobuild\temp.win-amd64-cpython-310\Release\src/foo/bar.obj
bar.c
creating C:\Users\me\source\setuptools-test\build\lib.win-amd64-cpython-310
creating C:\Users\me\source\setuptools-test\build\lib.win-amd64-cpython-310\foo
"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\me\AppData\Local\Temp\build-env-d_11j2_6\libs /LIBPATH:C:\Users\me\AppData\Local\Programs\Python\Python310\libs /LIBPATH:C:\Users\me\AppData\Local\Programs\Python\Python310 /LIBPATH:C:\Users\me\AppData\Local\Temp\build-env-d_11j2_6\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.7.2\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.37.32822\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.7.2\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" /EXPORT:PyInit_bar build\temp.win-amd64-cpython-310\Release\src/foo/bar.obj /OUT:build\lib.win-amd64-cpython-310\foo\bar.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-310\Release\src/foo\bar.cp310-win_amd64.lib
LINK : error LNK2001: unresolved external symbol PyInit_bar
build\temp.win-amd64-cpython-310\Release\src/foo\bar.cp310-win_amd64.lib : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120

ERROR Backend subprocess exited when trying to invoke build_wheel
```

#
Output from **second** `python -m build --wheel` command:

```
(venv) C:\Users\me\source\setuptools-test>python -m build --wheel
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting build dependencies for wheel...
running egg_info
writing foo.egg-info\PKG-INFO
writing dependency_links to foo.egg-info\dependency_links.txt
writing top-level names to foo.egg-info\top_level.txt
reading manifest file 'foo.egg-info\SOURCES.txt'
writing manifest file 'foo.egg-info\SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
running bdist_wheel
running build
running build_ext
installing to build\bdist.win-amd64\wheel
running install
running install_lib
creating build\bdist.win-amd64
creating build\bdist.win-amd64\wheel
creating build\bdist.win-amd64\wheel\foo
copying build\lib.win-amd64-cpython-310\foo\bar.cp310-win_amd64.pyd -> build\bdist.win-amd64\wheel\.\foo
running install_egg_info
running egg_info
writing foo.egg-info\PKG-INFO
writing dependency_links to foo.egg-info\dependency_links.txt
writing top-level names to foo.egg-info\top_level.txt
reading manifest file 'foo.egg-info\SOURCES.txt'
writing manifest file 'foo.egg-info\SOURCES.txt'
Copying foo.egg-info to build\bdist.win-amd64\wheel\.\foo-0.0-py3.10.egg-info
running install_scripts
C:\Users\me\AppData\Local\Temp\build-env-qhg0holo\lib\site-packages\wheel\bdist_wheel.py:108: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  if get_flag("Py_DEBUG", hasattr(sys, "gettotalrefcount"), warn=(impl == "cp")):
creating build\bdist.win-amd64\wheel\foo-0.0.dist-info\WHEEL
creating 'C:\Users\me\source\setuptools-test\dist\.tmp-qy_o0f31\foo-0.0-cp310-cp310-win_amd64.whl' and adding 'build\bdist.win-amd64\wheel' to it
adding 'foo/bar.cp310-win_amd64.pyd'
adding 'foo-0.0.dist-info/METADATA'
adding 'foo-0.0.dist-info/WHEEL'
adding 'foo-0.0.dist-info/top_level.txt'
adding 'foo-0.0.dist-info/RECORD'
removing build\bdist.win-amd64\wheel
Successfully built foo-0.0-cp310-cp310-win_amd64.whl

```

**Comment by abravalheri** [comment]
Hi @charelstoncrabb, thanks for reporting the issue. Please see my comments below:

1. Regarding the difference between the first run and second run that probably is explained by some caching and/or maybe the linker producing a file even if it fails. Probably that could be improved if we have a contributor willing to tackle it, but I think we can agree this is not the core of the error. It should be easy to remove the cached files with `git clean -f -d`, as long as all the changes that matter have been properly committed into git.

2. In the error message `ImportError: DLL load failed while importing bar: %1 is not a valid Win32 application.`, the term "Win32" does not necessarily imply that you are using a 32-bit architecture for the compilation... Microsoft has this confusing nomenclature in which "Win32" is actually the name of a Windows API that is used for both 32-bit and 64-bit environments. See https://learn.microsoft.com/en-us/windows/win32/api/ and https://learn.microsoft.com/en-us/windows/win32/apiindex/windows-api-list.

3. The error message `LINK : error LNK2001: unresolved external symbol PyInit_bar` is more significative for debugging. And this happens because Python expects some specific contents inside of the `.c` file. For example, Python expects you to define `PyInit_bar` if you want to be able to import `bar`. Since your `.c` file is very simplified and does not contain such definitions, the error that you are seeing is normal. See Python docs on extensions: https://docs.python.org/3/extending/building.html.

Could you please confirm that after changing `bar.c` to have the appropriate C code as expected by Python the compilation works and the module can be imported correctly?

**Comment by charelstoncrabb** [comment]
Hi @abravalheri , thank you very much for your detailed response!
1. Can confirmed that indeed using the `--wheel` flag keeps the `build` folder on disk, and without it it fails every time 👍 
2. One of a loong list of reasons I cringe every time I have to deal with Windows. The links are helplful, thank you
3. *This is it*. I overlooked the fact that `PyInit_` has to be implemented.

Thank you very much for your help
