### ISSUE TITLE
develop_requires for specifying packages to install when running setup.py develop

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#420]
Originally reported by: **Godsmith (Bitbucket: [Godsmith](http://bitbucket.org/Godsmith), GitHub: [Godsmith](http://github.com/Godsmith))**

---

There should be a develop_requires argument to setup() that specifies which packages that should be installed when running setup.py develop.

Typical packages to specify there would be nose, coverage, sphinx, etc.

This would be a good solution to this StackOverflow question: http://stackoverflow.com/questions/28509965/setuptools-development-requirements

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/420

**Comment by pganssle** [comment]
I don't think this is a good idea, `python setup.py develop` is basically like `python setup.py install`, but it installs a "live updated" version. As such, only the `install_requires` dependencies should be automatically installed. The test-specific dependencies go elsewhere.

Most people have a `requirements-dev.txt` for the stuff you'll want to install when doing dev, and it doesn't go through `setup.py`.
