### ISSUE TITLE
Building wheels with a `-` produces wheels with `_`.

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#4214]
I think #4159 might have changed wheel building for projects with a `-` in the project name (from the project's `pyproject.toml`). Now the wheel filename for a project like `scipy-openblas64` will become `scipy_openblas64-0.3.26-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`. When using `twine` to upload to PyPI the name is converted back to `scipy-openblas64`, but the anaconda uploader will respect the `_` and try to upload to `scipy_openblas64`. See https://github.com/scientific-python/upload-nightly-action/issues/61

_Originally posted by @mattip in https://github.com/pypa/setuptools/issues/4159#issuecomment-1928850518_

**Comment by jaraco** [comment]
The wheel name `scipy_openblas64` is correct according to [the spec](https://peps.python.org/pep-0491/#escaping-and-unicode):

> Each component of the filename is escaped by replacing runs of non-alphanumeric characters with an underscore `_`

That expectation matches with the fact that the wheels have [underscores in the names of releases going back to September](https://pypi.org/project/scipy-openblas64/0.3.23.293.2/#files).

**Comment by jaraco** [comment]
@mattip Can you possibly distill the scipy-openblas64 build instructions into something I can replicate or even better provide a minimal reproducer (ideally something that doesn't rely on a compiler)? I'm struggling to see when/how the naming is no longer meeting expectations.

Could it be that the problem is that the uploader is assuming that the name in the wheel is correct when it in fact is not, and it should instead be extracted from the wheel metadata (where the dash is present)?

**Comment by mattip** [comment]
> Could it be that the problem is that the uploader is assuming that the name in the wheel is correct when it in fact is not, and it should instead be extracted from the wheel metadata (where the dash is present)?

That makes sense. The wheel created has the `_` in the filename and `-` in the metadata. Renaming the wheel file before invoking the uploader makes the upload succeed. So the problem lies with the uploader https://github.com/Anaconda-Platform/anaconda-client/issues

**Comment by mattip** [comment]
Feel free to close this, sorry for the noise.

**Comment by mattip** [comment]
I opened https://github.com/Anaconda-Platform/anaconda-client/issues/704
