### ISSUE TITLE
[BUG] build_meta: `prepare_metadata_for_build_wheel` hook does not honor `--build-option`

### ISSUE THREAD

**Issue by gotmax23** [pypa/setuptools#4293]
### setuptools version

setuptools==69.2.0 and wheel==0.43.0

### Python version

Python 3.12

### OS

Fedora Linux

### Description

I am trying to run the `prepare_metadata_for_build_wheel` hook for the https://github.com/Rogdham/pyzstd project as part of the Fedora Linux build process. The project requires passing `--dynamic-link-zstd` when building without the in-tree `zstd` copy or else it fails with `FileNotFoundError: [Errno 2] No such file or directory: 'zstd/lib/common/'`.

I ran

``` bash
python -c 'from setuptools.build_meta import *; prepare_metadata_for_build_wheel("dist", {"--build-option": "--dynamic-link-zstd"})'
```

and expected the build backend to pass `--dynamic-link-zstd` through to the internal `setup.py dist_info` subcommand that it calls to generate the metadata. Instead, it only passes `['dist_info', '--output-dir', 'dist', '--keep-egg-info']`.

Should pyzstd be changed to allow setting this option through a different mechanism (e.g., an environment variable) or can setuptools start honoring `--build-option` for the `prepare_metadata_for_build_wheel` hook?

Relates: https://github.com/pypa/setuptools/issues/3896

CC: @Rogdham

### Expected behavior

See above

### How to Reproduce

Checkout https://github.com/Rogdham/pyzstd without the `zstd` submodule and run the command mentioned above.

### Output

n/a

**Comment by abravalheri** [comment]
I will go ahead and close this issue now, since this is not a planed feature in `setuptools`.

If the solution mentioned in https://github.com/pypa/setuptools/issues/4293#issuecomment-2041579801 does not suit the use case, please consider contributing towards https://github.com/pypa/setuptools/discussions/4083.
