### ISSUE TITLE
Sync vendored version of `more_itertools` between `setuptools` and `pkg_resources`

### ISSUE THREAD

**Issue by abravalheri** [pypa/setuptools#4323]
> I added this (more_itertools) here because it was listed in `pkg_resources.extern.names`.
> The version corresponds to the version that already exists in the `pkg_resources/_vendor` the directory... But that is different from the version in `setuptools/_vendor/vendored.txt`. Maybe we should synchronise these versions so that it makes the life easier for downstream packagers "de-vendoring" setuptools?

_Originally posted by @abravalheri in https://github.com/pypa/setuptools/pull/4320#discussion_r1574750784_

Potentially other packages too.

**Comment by mgorny** [comment]
For the record, downstream packagers don't pin versions to whatever was vendored. That would be completely unmaintainable.

**Comment by Avasam** [comment]
This should already be resolved now that there's a single `_vendor` folder right ?

**Comment by jaraco** [comment]
> This should already be resolved now that there's a single `_vendor` folder right ?

Yes, I think so.
