### ISSUE TITLE
Re-evaluate if `typing_extensions` is still needed as a vendored dependency for `pkg_resources`

### ISSUE THREAD

**Issue by abravalheri** [pypa/setuptools#4324]
> This (`typing_extensions`) was not listed. The `vendored.txt` file says the following:
>
> ```
> # required for platformdirs on Python < 3.8
> typing_extensions==4.4.0
> ```
>
> But now we removed support to Python < 3.8, so I guess we can remove this vendored dependency?

_Originally posted by @abravalheri in https://github.com/pypa/setuptools/pull/4320#discussion_r1574742424_

**Comment by Avasam** [comment]
I'd be surprised if we can't just hide whatever usage of `typing_extensions` behind `TYPE_CHECKING` checks and `from __future__ import annotations`.

**Comment by Avasam** [comment]
`jaraco.text` is causing a chain of dependencies: `inflect` --> `typeguard` --> `typing_extensions`. These can all be removed with https://github.com/jaraco/jaraco.text/pull/16
