### ISSUE TITLE
Handling either/or requirements

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#434]
Originally reported by: **jakirkham (Bitbucket: [jakirkham](http://bitbucket.org/jakirkham), GitHub: [jakirkham](http://github.com/jakirkham))**

---

In some cases, I find that I need one out of a group of dependencies, but I don't need all of them. However, something in the group must be used to satisfy the dependency. For instance, selecting between `ipython<4` or `jupyter`. Is there some way to already do this with `setuptools`? If so great, but I haven't seen anything like this yet. If not, could this be added somehow?

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/434

**Comment by rjollos** [comment]
Similar issue now that [psycopg2-binary](https://pypi.org/project/psycopg2-binary/) is released. I'd like to write:

```
    extras_require = {
        'posgresql': ['psycopg2 >= 2.0' or 'psycopg2-binary'],
    }
```
