### ISSUE TITLE
Error installing scipy 0.16.0 with easy-install 2.7 setuptools==18.3.2

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#441]
Originally reported by: **papachoco (Bitbucket: [papachoco](http://bitbucket.org/papachoco), GitHub: [papachoco](http://github.com/papachoco))**

---

Hi..

I am trying to install scipy (latest version 0.16.0) and I get the attached file.

Not sure if this belong to scipy . 

I am running a MacOS 10.10.5 Python/MacPorts 2.7.10

Thanks

Carlos

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/441

**Comment by abravalheri** [comment]
Hello, I suppose we can close this issue now that `easy_install` has been deprecated and widely replace by other installation means, such as `pypa/pip`.

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
