### ISSUE TITLE
[BUG] Generated `.exe` from `console_scripts` not pointing to the right Python exe when Python is built in Debug mode

### ISSUE THREAD

**Issue by Holt59** [pypa/setuptools#4418]
### setuptools version

70.0.0

### Python version

3.12.3

### OS

Windows

### Description

I have Debug build of Python and I am trying to use `sip` with it (https://pypi.org/project/sip/). I install the package with the following command:

```bash
# this is a line generated by the build tool which is why there are many options
PCBuild/amd64/python_d.exe -X utf8 -m pip install --force --no-warn-script-location --disable-pip-version-check sip==6.8.3 
```

But when trying to execute `sip-module.exe`, it fails:

```bash
& .\Scripts\sip-module.exe
Fatal error in launcher: Unable to create process using '"XXX\PCbuild\amd64\python.exe"  "XXX\Scripts\sip-module.exe" ': The system cannot find the file specified.
```

As you can see, the generated .exe tries to use `python.exe` instead of `python_d.exe`.

### Expected behavior

I expect the console script to work.

### How to Reproduce

1. Build Python in Debug mode
2. Install `sip` with `pip`
3. Try to run `sip-module.exe`

### Output

See explanation above.

**Comment by abravalheri** [comment]
Hi @Holt59 , I am not sure `sip` uses setuptools... They seem to be doing their own thing...

Anyway, any non-deprecated method of installation using setuptools does not create script wrappers itself (i.e. it is delegated to `pip` in the moment of installation).

**Comment by Holt59** [comment]
> Hi @Holt59 , I am not sure `sip` uses setuptools... They seem to be doing their own thing...
> 
> Anyway, any non-deprecated method of installation using setuptools does not create script wrappers itself (i.e. it is delegated to `pip` in the moment of installation).

There is definitively a `setup.py` with `console_scripts` defined, so I think they do use it (at least to install `sip`). Can you redirect me to the relevant issue tracker and/or code I can look at for this if this is not the right place?

**Comment by Holt59** [comment]
> > Hi @Holt59 , I am not sure `sip` uses setuptools... They seem to be doing their own thing...
> > Anyway, any non-deprecated method of installation using setuptools does not create script wrappers itself (i.e. it is delegated to `pip` in the moment of installation).
> 
> There is definitively a `setup.py` with `console_scripts` defined, so I think they do use it (at least to install `sip`). Can you redirect me to the relevant issue tracker and/or code I can look at for this if this is not the right place?

**Comment by abravalheri** [comment]
Depending on the version you are using they might use a different backend:


https://inspector.pypi.io/project/sip/6.8.3/packages/99/85/261c41cc709f65d5b87669f42e502d05cc544c24884121bc594ab0329d8e/sip-6.8.3.tar.gz/sip-6.8.3/doc/html/_downloads/8d58d9205fb0122eeab92a9fcb9691fa/pyproject.toml

If internally they use setuptools I don't know.

Maybe the best is to contact sip maintainers? If they are not calling the deprecated `install` command from setuptools, then the program generating the wrapper is `pip`. But they will probably know better how the backend they selected in `pyproject.toml` works...

If you manage to create a [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example) that only uses setuptools and does not have the extra complexity added by the sip codebase, we can continue to analise this problem in this issue tracker until we isolate the root of the problem.

But again, only deprecated code paths in setuptools generate script wrappers...

**Comment by abravalheri** [comment]
Depending on the version you are using they might use a different backend:


https://inspector.pypi.io/project/sip/6.8.3/packages/99/85/261c41cc709f65d5b87669f42e502d05cc544c24884121bc594ab0329d8e/sip-6.8.3.tar.gz/sip-6.8.3/doc/html/_downloads/8d58d9205fb0122eeab92a9fcb9691fa/pyproject.toml

If internally they use setuptools I don't know.

Maybe the best is to contact sip maintainers? If they are not calling the deprecated `install` command from setuptools, then the program generating the wrapper is `pip`. But they will probably know better how the backend they selected in `pyproject.toml` works...

If you manage to create a [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example) that only uses setuptools and does not have the extra complexity added by the sip codebase, we can continue to analise this problem in this issue tracker until we isolate the root of the problem.

But again, only deprecated code paths in setuptools generate script wrappers...

**Comment by Holt59** [comment]
> If you manage to create a [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example) that only uses setuptools and does not have the extra complexity added by the sip codebase, we can continue to analise this problem in this issue tracker until we isolate the root of the problem.
> 
> But again, only deprecated code paths in setuptools generate script wrappers...

I made a small example where `setup.py` only contains:

```python
from setuptools import setup

setup(
    name="package",
    version="0.0.1",
    entry_points={"console_scripts": ["test_python_debug_main = package.main:main"]},
)
```

The file `package/main.py` contains a dummy `main()` function that prints "Hello World!".

I am installing using this command (test_python contains only the `setup.py` file and the `package/main.py` file):

```pwsh
& ".\build\python-3.12.3\PCBuild\amd64\python_d.exe" -X utf8 -m pip install --force .\test_python\
```

The package is installed correctly, but when I run the script it points to the wrong Python:

```pwsh
.\build\python-3.12.3\Scripts\test_python_debug_main.exe
Fatal error in launcher: Unable to create process using '"XXX\build\python-3.12.3\PCbuild\amd64\python.exe"  "XXX\build\python-3.12.3\Scripts\test_python_debug_main.exe" ': The system cannot find the file specified.
```

As you can see, even with this small example the wrapper points to the non-debug executable which obviously does not exist.

**Comment by Holt59** [comment]
@abravalheri I made a small example but maybe the issue is with `pip` actually since running `setup.py install` directly does create a wrapper for the right `python_d.exe`. Where should I redirect that issue?

**Comment by abravalheri** [comment]
Hi @Holt59 , could you please try adding `pyproject.toml` to the example? (This will force `pip` to use the newer build standard and not use the deprecated installation method).

**Comment by Holt59** [comment]
> Hi @Holt59 , could you please try adding `pyproject.toml` to the example? (This will force `pip` to use the newer build standard and not use the deprecated installation method).

Do you mean an empty `pyproject.toml` or a `pyproject.toml` build system?

```toml
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
```

I'll try later today, but `sip` has a `pyproject.toml` I think and it the problem is present with `sip`.

**Comment by abravalheri** [comment]
For the sake of completeness of the minimal reproducer (and to make sure no deprecated code paths is being triggered on `pip install`), I think it makes sense to add the `pyproject.toml`.

You can try something like (just removing `setuptools-scm`, to keep the reproducer minimal):

```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
```

(But an empty `pyproject.toml` will also work very similarly).

**Comment by Holt59** [comment]
@abravalheri I tested with the `pyproject.toml` you mentioned and the behavior is the same. `pip install .` generates incorrect wrappers while `python setup.py install` generates correct ones.

**Comment by abravalheri** [comment]
Thank you very much @Holt59.

I believe this reproducer rules out involvement of setuptools on the generation of the wrappers.

If I am not mistaken, `pip` is the one that generates the wrappers based on a vendored version of [`distlib`](https://pypi.org/project/distlib/). It might be worth discussing your expectations with `pip` maintainers (it is good to present the original motivation, but if asked to provide a reproducer, the simplified example with the `pyproject.toml` you provided would be a better approach in my opinion).

**Comment by Holt59** [comment]
@abravalheri Thanks for the help, I've already opened an issue on `pypa/packaging-problems` so I will close this one.
