### ISSUE TITLE
unable to install openai-whisper due to issue with setuptools 

### ISSUE THREAD

**Issue by dishantsharma1988** [pypa/setuptools#4419]
### setuptools version

69.5.0

### Python version

3.11.1

### OS

windows VS terminal

### Description

I am trying to install package of  openai-whispe using  pip install openai-whisper -i https://pypi.python.org/simple

I am already having a version of setuptools greater than what exception is complaining about but still not letting me install. Please see below    
Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000020969B6B410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000020969BF1CD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000020969BF26D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000020969BF3250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000020969BF3E50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Users\dishants\OneDrive - AMDOCS\Documents\GEN AI\Code Review tool> pip show setuptools
Name: setuptools
Version: 69.5.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License:
Location: C:\Users\dishants\AppData\Roaming\Python\Python311\site-packages
Requires:
Required-by: imageio-ffmpeg, setuptools-rust
PS C:\Users\dishants\OneDrive - AMDOCS\Documents\GEN AI\Code Review tool> python --version                      
Python 3.11.1

### Expected behavior

it should allow to install

### How to Reproduce

try installing openai-whisper using setuptools 69.5.0

### Output

```console

```
   ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by dishantsharma1988** [comment]
hi thanks for your reply but I am doing it on my local and I do have
setuptools   installed if you see below :
pip show setuptools
Name: setuptools
Version: 69.5.0
Summary: Easily download, build, install, upgrade, and uninstall Python
packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: ***@***.***
License:
Location: C:\Users\dishants\AppData\Roaming\Python\Python311\site-packages
Requires:
Required-by: imageio-ffmpeg, setuptools-rust

Regards,
Dishant Sharma

**Comment by abravalheri** [comment]
> I do have setuptools installed if you see below.

Hi @dishantsharma1988, please see my previous comment that mentions why that is not relevant for the way `pip` works.

**Comment by dishantsharma1988** [comment]
sorry I am not able to understand this point, can you explain it step by
step as I am trying it on my local

Thanks
Dishant Sharma
