### ISSUE TITLE
[FR] `[default: ]` vs. `(default: )`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [pypa/setuptools#4421]
### What's the problem this feature will solve?

Is there a reason why the command line help text sometimes displays default values of user options inside brackets `[]` (13 occurrences):
https://github.com/pypa/setuptools/blob/8aa9855fcdb605f216d3fb868e41b4aaea0a8f3b/setuptools/_distutils/text_file.py#L59
and sometimes inside parentheses `()` (10 occurrences):
https://github.com/pypa/setuptools/blob/8aa9855fcdb605f216d3fb868e41b4aaea0a8f3b/setuptools/_distutils/command/clean.py#L17

### Describe the solution you'd like

How about standardizing the help text syntax?

### Additional context

See also:
* https://github.com/pypa/wheel/issues/616
* https://github.com/pypa/distutils/issues/251

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
I don't think there is a particular reason for that. These things tend to happen if we don't have a tool that automatically enforces one option.

Also having the code maintained in different repositories helps with the problem.
I believe that in the future the development of `bdist_wheel` will be done in the setuptools repository. But it is very likely that `pypa/distutils` will be kept separated (at least until the oldest Python supported is 3.12).
