### ISSUE TITLE
AssertionError importing setuptools

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#4439]
I don't think that Python 3.11.2 is considered old.  However, I am unable to import setuptools without setting the environment variable that you want to remove.  Wouldn't it be better to fix setuptools first?

This is what I am seeing:

```
Python 3.11.2 (v3.11.2:878ead1ac1, Feb  7 2023, 10:02:41) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/culler/Library/Python/3.11/lib/python/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/culler/Library/Python/3.11/lib/python/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/Users/culler/Library/Python/3.11/lib/python/site-packages/_distutils_hack/__init__.py", line 77, in do_override
    ensure_local_distutils()
  File "/Users/culler/Library/Python/3.11/lib/python/site-packages/_distutils_hack/__init__.py", line 64, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/distutils/core.py
>>> import os
>>> os.environ['SETUPTOOLS_USE_DISTUTILS'] = 'stdlib'
>>> import setuptools
>>> setuptools.__version__
'67.6.0'
```

_Originally posted by @culler in https://github.com/pypa/setuptools/issues/3625#issuecomment-1475353188_

**Comment by culler** [comment]
My comment on #3625 was posted a long time ago.  In the meantime I have upgraded python on that system - including python 3.11, (even though I don't use it anymore).  So I no longer have a python 3.11.2 installation to test with.  My current python 3.11 is 3.11.6 with setuptools 68.1.0.  It seems to have no trouble importing setuptools.  I also have an installation of Python 3.11.0 on another machine, and it imports setuptools without issue.

So, I am sorry, but I can no longer reproduce the error that led to that comment.  Thanks for taking the time to look at that old comment and take it into consideration, though!

**Comment by Avasam** [comment]
Thanks for the response @culler , for what it's worth, I did test with the same Python and setuptools version you had (although on Windows) w/o causing issue.

I think there's still a valid edge-case that cas trigger that error I've been able to replicate, so I opened #4441

**Comment by jaraco** [comment]
Thanks for the suggestion @Avasam . I do want to avoid adopting ownership of that code path. It sounds like it was specific to this user's environment.
