### ISSUE TITLE
[BUG] 71.0.0 fails `PyInstaller` builds

### ISSUE THREAD

**Issue by amotl** [pypa/setuptools#4477]
### setuptools version

setuptools==71.0.0

### Python version

Python 3.12

### OS

Linux, macOS, Windows

### Description

CI jobs started tripping when using setuptools 71, released two hours ago.
- https://github.com/crate/cratedb-toolkit/pull/201

### Expected behavior

CI builds work as expected.

### How to Reproduce

No reproducer yet, but a stacktrace on GHA.

### Output

```python
PyInstaller.exceptions.ImportErrorWhenRunningHook: 
Failed to import module __PyInstaller_hooks_0_importlib_metadata required by hook for module 
/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/PyInstaller/hooks/hook-importlib_metadata.py.

Please check whether module __PyInstaller_hooks_0_importlib_metadata actually exists and whether
the hook is compatible with your version of 
/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/PyInstaller/hooks/hook-importlib_metadata.py:
You might want to read more about hooks in the manual and provide a pull-request to improve PyInstaller.
```
-- https://github.com/crate/cratedb-toolkit/actions/runs/9983011865/job/27589798960?pr=201#step:5:198

**Comment by jaraco** [comment]
It's quite possible that a pyinstaller build might need to be re-customized for Setuptools 71 with its new vendoring approach.

I'm not sure how to interpret that output. For example, where does `__PyInstaller_hooks_0_importlib_metadata` come from? I wouldn't know the first step in trying to replicate the issue. One possible workaround may be to "install" Setuptools' dependencies as [declared here](https://github.com/pypa/setuptools/blob/f2a6bb190202577595a45ceebdedb0016b7cf864/pyproject.toml#L109-L119).

**Comment by bashonly** [comment]
> One possible workaround may be to "install" Setuptools' dependencies as [declared here](https://github.com/pypa/setuptools/blob/f2a6bb190202577595a45ceebdedb0016b7cf864/pyproject.toml#L109-L119).

Installing `setuptools[core]` does indeed workaround the issue, at least in my workflow

**Comment by jaraco** [comment]
> > One possible workaround may be to "install" Setuptools' dependencies as [declared here](https://github.com/pypa/setuptools/blob/f2a6bb190202577595a45ceebdedb0016b7cf864/pyproject.toml#L109-L119).
> 
> Installing `setuptools[core]` does indeed workaround the issue, at least in my workflow

That's great news!

FYI - reliance on `setuptools[core]` directly is not supported. I expect that extra to be moved to default dependencies in the future. Just be aware that `core` is an internal detail that might change.

**Comment by bashonly** [comment]
71.0.2 resolves this for me. Seems like the root cause of the issue is what's described in https://github.com/pypa/setuptools/issues/4480#issuecomment-2236507819 and https://github.com/pypa/setuptools/issues/4482

**Comment by jaraco** [comment]
> FYI - reliance on `setuptools[core]` directly is not supported. I expect that extra to be moved to default dependencies in the future. Just be aware that `core` is an internal detail that might change.

Correction - `setuptools[core]` is fine for incidental use. It's just not to be used by package maintainers in the `build-requires`.

**Comment by Pjumpod** [comment]
@jaraco  I found similar error code on macos x86 but not sure if it totally same case.

here is the error code.

File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/PyInstaller/hooks/hook-setuptools.py", line 52, in <module>
    if setuptools_info.version < (71, 0):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
