### ISSUE TITLE
[FR] Add Path support to data-files

### ISSUE THREAD

**Issue by InvincibleRMC** [pypa/setuptools#4494]
### What's the problem this feature will solve?

Use Path objects to define locations for data_files in setup().

### Describe the solution you'd like

Allow passing in path objects into the data_files in setup()

### Alternative Solutions

Using standard os.path.join works fine but, having the option to use pathlib would be nice.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by InvincibleRMC** [comment]
This PR was moved [here](https://github.com/pypa/distutils/pull/272)

**Comment by twmr** [comment]
@InvincibleRMC since a PR in pypa/distutils was merged, can this gh issue be closed?
