### ISSUE TITLE
install_requires is not executed with custom install command

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#456]
Originally reported by: **andi0661 (Bitbucket: [andi0661](http://bitbucket.org/andi0661), GitHub: Unknown)**

---

When using install_requires in the input arguments to setup(), it is only executed when installing the package via "pip install", but it is ignored when installing via "python setup.py install".

It would be nice if "python setup.py install" could be made to do the same thing as "pip install ." (i.e. install from package unpack directory containing setup.py), as far as "install_requires" is concerned.

This is with setuptools v17.0, which is the latest setuptools I get with virtualenv for python 2.6 on RHEL 6.7.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/456

**Comment by prokopst** [comment]
@jaraco I hit the very same issue with custom install step. I overrode `_called_from_setup` in a derived class which represents the custom install to return True, which I found quite nasty. Would it be possible to fix it?

Apparently there are more people out there having the same problem:
http://stackoverflow.com/questions/14441955/how-to-perform-custom-build-steps-in-setup-py

**Comment by jaraco** [comment]
It may be possible to fix it, though I'm not sure when I will get into it. Next steps are for someone to deep analyze the problem, characterize the issue, and propose something that might fix it.

**Comment by matiaslaino** [comment]
Very annoying bug, but this solution works: https://stackoverflow.com/a/21196195/448776

**Comment by kasperschnack** [comment]
I'm hitting this issue - does anyone know of a workaround?
i have both install_requirements and setup_requires in my setuptools.setup method call. But they seem to simply be ignored 😓.

**Comment by svedel** [comment]
I am also facing the same issue. Any updates?

**Comment by webknjaz** [comment]
FWIW it's highly discouraged to use `setup.py install` directly because it breaks things in the pip ecosystem starting with the inability to uninstall packages installed like this. Implementing a proper dependency resolution mechanism is a lot of work and it would basically reimplementing what pip does and vendoring resolvelib. I think it's not worth it and better be deprecated.

**Comment by jaraco** [comment]
> Apparently there are more people out there having the same problem:
> http://stackoverflow.com/questions/14441955/how-to-perform-custom-build-steps-in-setup-py

I note that at least in this use-case, the user is attempting to alter the 'build' behavior and they're doing so by altering the 'install' command. My recommendation here would be to avoid altering the install behavior and instead try to alter the build behavior, in particular to alter the `build.subcommands` to include the additional behavior. I plan to work on a demo for this. I created #2591 to capture that idea.

In the meantime, I welcome those interested in working on this issue to consider a few approaches:

- Proper fix: delve into the implementation, add some test coverage to capture the current expectations, add some tests that capture the missed expectation when `install` is subclassed, and then devise a fix in `_called_from_setup`.
- Investigate: In any `install` subclass, override `_called_from_setup` to replace the `2` with `3`. Does that fix the issue?
- Redesign: The point of that check is to bypass egg-based installs for bdist_* commands. Perhaps those commands could explicitly set a flag on the install command to bypass egg-based installs.
- Redesign: Perhaps as a step toward deprecating egg-based installs, `install` could be separated into different commands, perhaps creating `install_egg` and `install_plain`... and callers like `bdist` could use `install_plain` and callers who really want eggs could use `install_egg`. 
- Bypass: Stop doing egg installs altogether and use pip-based installs, as egg-based installs are discouraged and will be deprecated (soon?).
