### ISSUE TITLE
Integration tests for `brotli` are failing

### ISSUE THREAD

**Issue by abravalheri** [pypa/setuptools#4564]
Details in https://github.com/pypa/setuptools/commit/76942cfe9ab14b6d30eac50b9b3dff8cc9241b76#commitcomment-145325568:

> It seems that this tag never got published to [PyPI](https://github.com/pypa/setuptools/actions/runs/10222324185) due to a [failure in the integration tests](https://github.com/pypa/setuptools/actions/runs/10222324185/job/28287095585#step:6:178).
> 
> The `brotli` package fails to build with the error:
> 
> ```
> Traceback (most recent call last):
>         File "/tmp/pytest-of-runner/pytest-0/popen-gw2/test_install_sdist_brotli_v_LA0/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/tmp/pytest-of-runner/pytest-0/popen-gw2/test_install_sdist_brotli_v_LA0/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "/tmp/pytest-of-runner/pytest-0/popen-gw2/test_install_sdist_brotli_v_LA0/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
>           return hook(metadata_directory, config_settings)
>         File "/tmp/pytest-of-runner/pytest-0/popen-gw2/test_install_sdist_brotli_v_LA0/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
>           self.run_setup()
>         File "/tmp/pytest-of-runner/pytest-0/popen-gw2/test_install_sdist_brotli_v_LA0/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
>           exec(code, locals())
>         File "<string>", line 282, in <module>
>         File "/tmp/pytest-of-runner/pytest-0/popen-gw2/test_install_sdist_brotli_v_LA0/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
>           return distutils.core.setup(**attrs)
>         File "/tmp/pytest-of-runner/pytest-0/popen-gw2/test_install_sdist_brotli_v_LA0/.venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 146, in setup
>           _setup_distribution = dist = klass(attrs)
>         File "/tmp/pytest-of-runner/pytest-0/popen-gw2/test_install_sdist_brotli_v_LA0/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 278, in __init__
>           _Distribution.__init__(self, dist_attrs)
>         File "/tmp/pytest-of-runner/pytest-0/popen-gw2/test_install_sdist_brotli_v_LA0/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 286, in __init__
>           self.finalize_options()
>         File "/tmp/pytest-of-runner/pytest-0/popen-gw2/test_install_sdist_brotli_v_LA0/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 630, in finalize_options
>           ep(self)
>         File "/tmp/pytest-of-runner/pytest-0/popen-gw2/test_install_sdist_brotli_v_LA0/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 650, in _finalize_setup_keywords
>           ep.load()(self, ep.name, value)
>         File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/importlib/metadata/__init__.py", line [173](https://github.com/pypa/setuptools/actions/runs/10222324185/job/28287095585#step:6:174), in load
>           return functools.reduce(getattr, attrs, module)
>       AttributeError: module 'setuptools.dist' has no attribute 'check_test_suite'
> ```
> 
> I suspect there might be an outdated `*.egg-info/entrypoints.txt` or `*.dist-info/entrypoints.txt` somewhere in `sys.path` of the CI worker?
> 
> In my local test I can see that there is a `/tmp/pytest-of-abravalheri/pytest-155/test_install_sdist_brotli_v_LA0/.venv/lib/python3.11/site-packages/setuptools-70.3.0.dist-info` file in the generated virtual environment for some reason. Isn't the `-I` option in `pip install` supposed to prevent this from happening?
> 
> Other information relevant is that `Brotli` also uses [the removed `test_suite` option](https://github.com/google/brotli/blob/39bcecf4559f9b0e75c6248a75d9c0db6b123d88/setup.py#L296).

**Comment by jaraco** [comment]
This issue happened previously in #4518.

**Comment by jaraco** [comment]
I re-ran the failed jobs for v72.2.0, since the release didn't go out as planned, and [it succeeded](https://github.com/pypa/setuptools/actions/runs/10222324185).
