### ISSUE TITLE
Incorrect sys.argv[0] for generated console scripts on Windows

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#459]
Originally reported by: **pombredanne (Bitbucket: [pombredanne](http://bitbucket.org/pombredanne), GitHub: [pombredanne](http://github.com/pombredanne))**

---

The code that generates entry point console script return an incorrect value for sys.argv[0] on windows:
https://bitbucket.org/pypa/setuptools/src/4ce518784af886e6977fa2dbe58359d0fe161d0d/setuptools/command/easy_install.py?at=default&fileviewer=file-view-default#easy_install.py-2008

Even if the script was called from the CLI as XXXX, sys.argv[0] will be XXXX-script.py
It should instead by XXXX.

pip handles this by fixing sys.argv[0] in the generated launcher script for wheels here https://github.com/pypa/pip/blob/1da0ea13f3f0ab789edd62012d09bf69be045f68/pip/wheel.py#L416

distlib fixes sys.argv[0] here in a similar way in the launcher script :
https://bitbucket.org/pypa/distlib/src/6ada86eea2700f10edcd81f831139c6ae20edb74/distlib/scripts.py?at=default&fileviewer=file-view-default#scripts.py-55

Setuptools does not and it should IMHO.

See also this issue: https://github.com/pypa/pip/issues/3233

And where this was discovered: https://github.com/mitsuhiko/click/issues/365

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/459

**Comment by ofek** [comment]
@jaraco This is fixed
