### ISSUE TITLE
setuptools doesn't install data_files correctly

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#460]
Originally reported by: **jdemeyer (Bitbucket: [jdemeyer](http://bitbucket.org/jdemeyer), GitHub: [jdemeyer](http://github.com/jdemeyer))**

---

NOTE 1: I have read the docs and know this is documented as a feature, but I think it's a bug anyway.

NOTE2: This might be related to #130, but I didn't quite understand what that bug is about.

When using

```
#!python

setup(...
    data_files=("some/relative/path", ["file1", ...])
)
```

and running `./setup.py install`, these `data_files` are installed in the egg, which makes them inaccessible to other programs. I think that `setuptools` should just do what `distutils` does here, which is to install the files in `sys.prefix/some/relative/path`. The egg might still be the correct location for `package_data`, I'm not arguing with that.

Wheel also installs data files in `sys.prefix`. It's annoying to have a package which works correctly when installed as a wheel, but which doesn't install correctly when using `./setup.py install` with setuptools.

The documentation http://pythonhosted.org/setuptools/setuptools.html#including-data-files starts with "the most common use case for data files distributed with a package is for use by the package, usually by including the data files in the package directory". This may be right, but it's not the only use case and the use case where `data_files` are needed by something else (which might not even be Python) isn't covered.

My particular use case is installing `kernel.json` files for Jupyter.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/460

**Comment by a1an77** [comment]
Duplicate of #130
