### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by aviv-marcjonot** [pypa/setuptools#4631]
### setuptools version

setuptools==74.1.1

### Python version

Python 3.10

### OS

linux

### Description

I face the following issue 
`canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'`

Solved by using older version
setuptools (74.1.1 -> 67.6.1)

### Expected behavior

run successfully on latest version

### How to Reproduce

run `poetry install --all-extras` with setuptools dependencies (>=74.1.0)

### Output

```console
`canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'`
```

**Comment by jaraco** [comment]
See #4483
