### ISSUE TITLE
[BUG] natural imports for vendors break package within site-packages.zip

### ISSUE THREAD

**Issue by gaborbernat** [pypa/setuptools#4640]
### setuptools version

setuptools 74.1

### Python version

Any

### OS

Any

### Description

https://github.com/pypa/setuptools/pull/4457 breaks the tool being zipped up in a `site-packages.zip`... The use case was originally submitted to virtualenv via https://github.com/pypa/virtualenv/issues/1715

### Expected behavior

It works.

### How to Reproduce

https://github.com/pypa/virtualenv/issues/1715

### Output

Discovered during https://github.com/pypa/virtualenv/pull/2760, see https://github.com/pypa/virtualenv/actions/runs/10752988428/job/29821925275?pr=2760

**Comment by FinnWoelm** [comment]
Hey @gaborbernat, thanks so much for filing this issue. Helped us debug why our Zappa deployment stopped working.

We are working around it for now by manually installing the last compatible version of `virtualenvs` and `setuptools`.

```
# GitHub action

jobs:
  build_and_deploy:
    steps:
    # ... more steps here ...

    # Note (Sep 9, 2024): setuptools 74.1.2 breaks imports within site-packages.zip, which causes the zappa deployment
    # to fail. Virtualenv 20.26.3 still uses a compatible version of setuptools. Once this issue gets fixed, we can
    # remove this step.
    # See issue: https://github.com/pypa/setuptools/issues/4640
    # See setuptools PR: https://github.com/pypa/setuptools/pull/4457
    # See virtualenv PR: https://github.com/pypa/virtualenv/pull/2760
    - name: Set fixed setuptools version
      run: pip3 install virtualenv==20.26.3 setuptools==70.1.0

    # ... more steps here ...
```

**Comment by jaraco** [comment]
Investigation happening in #4641.
