### ISSUE TITLE
[BUG] 75.x.x cannot import config from distutils

### ISSUE THREAD

**Issue by thehesiod** [pypa/setuptools#4654]
### setuptools version

75.0.0

### Python version

python3.11

### OS

Windows 11 WSL 2 Debian

### Description

all the recent 75.x.x versions introduced an error which prevents pipenv locking from working on projects which were setting the DEFAULT_REPOSITORY:
```python
from distutils import config
config.PyPIRCCommand.DEFAULT_REPOSITORY = 'internal'
```

with the error:
```
 "ImportError: cannot import name 'config' from 'distutils' (/home/amohr/venv/lib/python3.11/site-packages/setuptools/_distutils/__init__.py)\n"
```

I didn't see any release notes about 75.x stating this functionality had been removed.  Was this functionality removed on purpose?

### Expected behavior

no error

### How to Reproduce

create package with above source in the setup.py

### Output

```console
 "ImportError: cannot import name 'config' from 'distutils' (/home/amohr/venv/lib/python3.11/site-packages/setuptools/_distutils/__init__.py)\n"
```

**Comment by thehesiod** [comment]
fyi we use this to prevent devs from accidentally uploading packages to the public pypi repo

**Comment by abravalheri** [comment]
> I didn't see any release notes about 75.x stating this functionality had been removed. Was this functionality removed on purpose?

Thi @thehesiod , this is mentioned in the changelogs


> v75.0.0
> ...
> Deprecations and Removal
> ..
> 
> Merge with pypa/distutils@7283751. Removed the register and upload commands and the  ***config*** module that backs them (pypa/distutils#294). Removed the borland compiler. Replaced vendored dependencies with natural dependencies. Cygwin C compiler now gets compilers from sysconfig (pypa/distutils#296). (#4649)

Because setuptools and distutils no longer handle uploads (as deprecated for a while), this module no longer provides any functionality for setuptools/distutils themselves and was removed.

**Comment by abravalheri** [comment]
> I didn't see any release notes about 75.x stating this functionality had been removed. Was this functionality removed on purpose?

Thi @thehesiod , this is mentioned in the changelogs


> v75.0.0
> ...
> Deprecations and Removal
> ..
> 
> Merge with pypa/distutils@7283751. Removed the register and upload commands and the  ***config*** module that backs them (pypa/distutils#294). 

Because setuptools and distutils no longer handle uploads (as deprecated for a while), this module no longer provides any functionality for setuptools/distutils themselves and was removed.
