### ISSUE TITLE
[BUG] AttributeError: module 'distutils' has no attribute '_msvccompiler'

### ISSUE THREAD

**Issue by ratnampa** [pypa/setuptools#4657]
### setuptools version

setuptools>=74.0.0

### Python version

Python>=3.10

### OS

Windows 11

### Description

It looks like removing the monkeypatching of _msvccompiler, now results in an issue to use _msvccompiler from distutils. It is used in pytorch build [https://github.com/pytorch/pytorch/blob/274883083d99511d33a6b75af40c99f7613fe40d/tools/build_pytorch_libs.py#L37](https://github.com/pytorch/pytorch/blob/274883083d99511d33a6b75af40c99f7613fe40d/tools/build_pytorch_libs.py#L37) and it fails with setuptools>=74.0.0.

Currently it fails with error
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: module 'distutils' has no attribute '_msvccompiler'
```

### Expected behavior

from setuptools import distutils
distutils._msvccompiler
<module 'distutils._msvccompiler' from 'C:\\Users\\sdp\\miniforge3\\envs\\pytorch_build_new\\Lib\\site-packages\\setuptools\\_distutils\\_msvccompiler.py'>

### How to Reproduce

pip install setuptools
python
from setuptools import distutils
distutils._msvccompiler

### Output

```console
<module 'distutils._msvccompiler' from 'C:\\Users\\sdp\\miniforge3\\envs\\pytorch_build_new\\Lib\\site-packages\\setuptools\\_distutils\\_msvccompiler.py'>
```

**Comment by abravalheri** [comment]
Hi @ratnampa, that is a private module with no guarantees of stable APIs.

I suggest contacting the PyTorch developers because this seems to be a bug in their codebase (when a package uses a private function/module/class from a different 3rd party dependency, they are taking responsibility for the maintenance and to respond to non-public changes in that dependency).

**Comment by ratnampa** [comment]
But it looks like it was deprecated right? As it works for version<74.0.0
