### ISSUE TITLE
Creating FreeBSD packages

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#481]
Originally reported by: **alexandro (Bitbucket: [alexandro](http://bitbucket.org/alexandro), GitHub: [alexandro](http://github.com/alexandro))**

---

Hi good people.

Does anybody mind that implementing support for creating native FreeBSD packages by one command for setuptools would be a good idea?

Since deploying python projects with high complexity to FreeBSD platform is a strong headache I suppose automatic tools instead of hand operations would be highly appreciated.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/481

**Comment by kxepal** [comment]
You can check https://github.com/kxepal/setuptools-pkg where I'm solving this problem. There are quite a lot of questions, problems and ideas to apply, so it's good to have it as setuptools extension rather than builtin feature. At least for now.

Any feedback is welcome!
