### ISSUE TITLE
Consider hosting documentation at setuptools.pypa.io

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#495]
Originally reported by: **Ivoz (Bitbucket: [Ivoz](http://bitbucket.org/Ivoz), GitHub: [Ivoz](http://github.com/Ivoz))**

---

I just thought it might be nice for setuptools to be in the same playground as everyone else and also on RTD.

additionally @dstufft I'm guessing you would likely need to help set that up, sound like a good / bad / indifferent idea to you?

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/495

**Comment by abravalheri** [comment]
Setuptools docs have been moved to the pypa.io domain 👏
