### ISSUE TITLE
Installing pip for python 2.7 overwrites pip3 script (Mac OSX)

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#507]
Originally reported by: **neildhar (Bitbucket: [neildhar](http://bitbucket.org/neildhar), GitHub: [neildhar](http://github.com/neildhar))**

---

![Screen Shot 2016-02-28 at 2.01.19 PM.png](https://bitbucket.org/repo/AXpAxn/images/108057640-Screen%20Shot%202016-02-28%20at%202.01.19%20PM.png)

On attempting to install pip for my python 2.7 (installed via homebrew), easy_install creates executables at /usr/local/bin/pip3 and /usr/local/bin/pip3.5 overwriting the pip3 script installed by my actual python 3 install. See screenshot for details. This is easily corrected by using homebrew to unlink and relink python 3 (brew link --overwrite python3).

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/507

**Comment by sparr** [comment]
Also noting that this is a concern when pip3 is provided by the Catalina-included python3, as /usr/bin/pip3 if /usr/local/bin is earlier in the path.

This also seems to have created a /usr/local/bin/pip3.8

**Comment by abravalheri** [comment]
Hello, I suppose we can close this issue now that `easy_install` has been deprecated and widely replace by other installation means, such as `pypa/pip`. (... and Python 2.7 is no longer supported)

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
