### ISSUE TITLE
include_package_data should consider Git version control as well as CVS and SVN

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#515]
Originally reported by: **koterpillar (Bitbucket: [koterpillar](http://bitbucket.org/koterpillar), GitHub: [koterpillar](http://github.com/koterpillar))**

---

From the documentation:

> include_package_data
> 
> If set to True, this tells setuptools to automatically include any data files it finds inside your package directories, that are either under CVS or Subversion control, or which are specified by your MANIFEST.in file. For more information, see the section below on Including Data Files.

The "CVS or Subversion control" part makes little sense when Git is [at least no less popular](http://programmers.stackexchange.com/questions/136079/are-there-any-statistics-that-show-the-popularity-of-git-versus-svn).

The behavior of `include_package_data` should either be expanded to exclude Git and possibly Mercurial, or removed altogether, always requiring `MANIFEST.in`.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/515

**Comment by RonnyPfannschmidt** [comment]
setuptools_scm implements git and mercurial support
