### ISSUE TITLE
Operation not permitted while trying hard linking

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#516]
Originally reported by: **sorin (Bitbucket: [sorin](http://bitbucket.org/sorin), GitHub: [sorin](http://github.com/sorin))**

----------------------------------------

It seems that even current versions of setuptools to fail ugly when os.link cannot be performed, and this seems to be something more and more common, especially due to the virtualisation. 

Hard links are not supported in many network mounts and virtual environments. In my case I am using Parallels to share my home directory which also contains the python modules which I am developing, allowing me to run the same code on OS X, Ubuntu and Windows.

It seems that doing `python setup.py sdist` fails with the (in)famous error:

```
hard linking README.txt -> foo-0.1
error: Operation not permitted
```

Based on the thread from http://www.itsprite.com/pythonpython-setup-py-sdist-error-operation-not-permitted/ I tried to add `del os.link` to my setup.py and it started to work.

While this workaround seems ugly, it seems that's the only one that covers all failure cases.

Problem reproduces with both 5.5.x and 20.x versions of setuptools.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/516

**Comment by jamadden** [comment]
I just got bit by this using `setuptools-24.2.1`. I was trying to use docker to produce manylinux wheels in a more automated fashion using a mount point from the host machine (OS X).

The `del os.link` workaround fixed my problem.

**Comment by jamadden** [comment]
I spoke too soon: `del os.link` fixed my problem for Python 2.7, but I still fail with the same error for Python 3.

**Comment by jaraco** [comment]
This issue exists in Python (in distutils.command.sdist.sdist.make_release_tree and distutils.cmd.Command.copy_file), but it could be patched here.

**Comment by jaraco** [comment]
Release pending with v24.3.0.
