### ISSUE TITLE
`fixup_namespace_packages` may trigger `ValueError` in setuptools 19.4 and newer

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#520]
Originally reported by: **kehoste (Bitbucket: [kehoste](http://bitbucket.org/kehoste), GitHub: Unknown)**

----------------------------------------

We are hitting a problem with setuptools 19.4 and newer, while things are working fine with setuptools 19.3 and earlier. The problem was introduced with the changes in Pull Request #167 .

The problem is that a call to `fixup_namespace_packages` is triggering a `ValueError`, due to the way in which we 'flatten' our easybuild.easyblocks namespace (see [here](https://github.com/hpcugent/easybuild-easyblocks/blob/58741107bae181faee9670c59b3c935ab42df51d/easybuild/easyblocks/__init__.py#L75)).

More details about the issue we're hitting are available [here](https://github.com/hpcugent/easybuild-framework/issues/1678).

A test case is attached, the problem can be triggered with:

    export PYTHONPATH=/tmp/testcase/one:$PYTHONPATH
    python test.py

Correct output (which we obtain with setuptools 19.3 and earlier) would be:

    atlas
    boost
    blacs

With setuptools 19.4 and later we get:

    atlas
    Traceback (most recent call last):
      File "test.py", line 9, in <module>
        fixup_namespace_packages(os.path.join(testdir, 'two'))
      File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 2237, in fixup_namespace_packages
      File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 2235, in fixup_namespace_packages
      File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 2194, in _handle_ns
      File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 2192, in sort_key
    ValueError: '/private/tmp/testcase/one/easybuild' is not in list

The problem is that the way in which the parent location of the package is determined in the `sort_key` inner function is broken, basically because we 'rewrite' a package name like `easybuild.easyblocks.a.atlas` to `easybuild.easyblocks.atlas`.
So the 'depth' of the location at which the module is actually available (`easybuild/easyblocks/a/atlas.py`) doesn't match the depth of the package name it is imported with (`easybuild.easyblocks.atlas`).

Since this works fine with setuptools 19.3 and earlier, I consider this a bug introduced in setuptools 19.4.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/520

**Comment by Mekk** [comment]
I faced this problem (and found this bug) yesterday, after creating fresh virtualenv (which installed setuptools 35.0.1 (and resolved the case by downgrading to 19.3). The backtrace ended in:

```
      File "/home/marcink/.virtualenvs/sfx_3-0/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
      File "/home/marcink/.virtualenvs/sfx_3-0/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2064, in position_in_sys_path
        return sys_path.index(_normalize_cached(os.sep.join(parts)))
    ValueError: '/home/marcink/GAUSS/python/sfx__util/src' is not in list
```

Funny thing is that my virtualenv contains both lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py (which contains the fix) and lib/python2.7/site-packages/pkg_resources/__init__.py (which does not, and which fails). 

The thing above can be easily reproduced on my Ubuntu 16.04 by simple:
```
mkvirtualenv freshenv
```

Anyone has suggestion, who is to blame?
