### ISSUE TITLE
Easy_install would mess up the order of sys.path in develop install

### ISSUE THREAD

**Issue by Plypy** [pypa/setuptools#539]
Environment:

Setuptools 20.6.7
Ubuntu server 14.04 within VirtualBox

**Background**:

Debian alike has two paths for python packages, one is for packages managed by apt `/usr/lib/python*.*/dist-packages/`, the other is for packages managed by pip or other 3rd-party software `/usr/local/lib/python*.*/dist-packages/`. Usually, the latter holds newer packages, so it's placed before the former.

**Issue**
After performing a `python setup.py develop`, I found that all projects crashed with something like ImportError. After some research, it seems to me that in develop install easy_setup would add current project's and its dependencies' paths into an `easy_setup.pth` file in order to modify `sys.path`. However if a package is located in `/usr/lib/python*.*/dist-packages/`, easy_setup would still add this path into `easy_setup.pth`, which would cause this path place prior to `/usr/local/lib/python*.*/dist-packages/` and lead those disasters.

My temporary workaround  is to move dependencies located in `/usr/lib/python*.*/dist-packages/` to `/usr/local/lib/python*.*/dist-packages/`.

Hope you can fix this, it has spent me lots of time to discover where the problem is.

Regards.

**Comment by RonnyPfannschmidt** [comment]
im under the impression this is a case of a distribution breaking the worldd
