### ISSUE TITLE
setup() creating broken PKG-INFO if using unicode_literals in Python 2.7

### ISSUE THREAD

**Issue by pepoluan** [pypa/setuptools#540]
If I use `from __future__ import unicode_literals` in `setup.py`, the `keywords` parameter will be broken into a list of comma-separated characters in PKG-INFO when I invoke `python setup.py register`.

Example:

    keyword='multiprocessing parallel workers multiworker'

will result in the following line in PKG-INFO:

    Keywords: m,u,l,t,i,p,r,o,c,e,s,s,i,n,g, ,p,a,r,a,l,l,e,l, ,w,o,r,k,e,r,s, ,m,u,l,t,i,w,o,r,k,e,r

The workaround is to specify it as `bytes`, e.g., `b"enter some keywords"`.

So, this bug has a workaround, but kind of annoying to have to remember that.

I am using **Python 2.7.11** with **setuptools 20.6.7**

**Comment by jaraco** [comment]
There are other parameters to `setup()` that don't handle unicode values well, and unfortunately, the [code is in distutils](https://github.com/python/cpython/blob/master/Lib/distutils/dist.py#L606-L608) and not setuptools, so can't be readily fixed here.

I've taken to not using `from __future__ import unicode_literals` in my setup.py scripts, but you have other options:

1. Wrap your value in `str`, i.e. `keywords=str("multiprocessing,parallel,workers,...")`. Note that keyword values [should be separated by commas](https://docs.python.org/2/distutils/apiref.html#distutils.core.setup), despite setuptools' bad example.
2. Supply the values already split, i.e. `keywords=['multiprocessing', 'parallel', 'workers', ...]`. I'm not certain this approach won't have other consequences down the line.

I definitely don't recommend using `b''` as the workaround, as that will almost certainly cause you problems on Python 3, and though you may not be targetting Python 3 now, it's bad practice to be using bytes where text is intended.
