### ISSUE TITLE
Standard Dist for setuptools 20.9.0

### ISSUE THREAD

**Issue by papachoco** [pypa/setuptools#549]
Could we get a sdist for setuptools 20.9.0 in PyPI. This is for [legacy] buildout installations

Thanks 

Carlos

**Comment by jaraco** [comment]
Not sure why the release process didn't work. Short answer is yes.

**Comment by jaraco** [comment]
I just uploaded sdists for 20.9.0 manually. I also updated the auto-deploy scripts to I hope avoid this issue in the future.
