### ISSUE TITLE
upload command doesn't prompt for password; raises TypeError

### ISSUE THREAD

**Issue by brookskindle** [pypa/setuptools#554]
# Problem statement
If the `~/.pypirc` file does not contain a password like so:
```ini
[distutils]
index-servers = 
    pypitest

[pypitest]
repository = https://testpypi.python.org/pypi
username = my_username
; Note the lack of a password
```
Then uploading the package
```
python setup.py sdist upload -r pypitest
```
Fails to prompt the user for his password and instead raises a TypeError (output truncated)
```
running upload
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    keywords=["test", "hello"]
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/upload.py", line 60, in run
    self.upload_file(command, pyversion, filename)
  File "/usr/lib/python2.7/distutils/command/upload.py", line 135, in upload_file
    self.password)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```
**This is different** than the behavior of the `register` command, which prompts the user for a password before continuing.
```
python setup.py sdist register -r pypitest
```
(output truncated)
```
Creating tar archive
removing 'HelloPyPi-0.0.1.dev0' (and everything under it)
running register
Password: 
```

> Note that the `register` and the `upload` command exhibit the proper behavior **if you store your password in `~/.pypirc`**, but not if the password is omitted.

# Okay, so...?
I am aware that you can run
```
python setup.py sdist register -r pypitest upload -r pypitest
```
As a workaround, but it stands to reason that **if you can register a package without uploading it, then you should also be able to upload a package without registering it**, regardless of if a password has been specified in your `~/.pypirc` file.

# Steps to reproduce

1. Remove your pypi password from `~/.pypirc`
1. Find a project that you wish to upload to a pypi server (I used [my example repository](https://github.com/brookskindle/hellopypi) for this)
1. Run `python setup.py sdist upload -r target_pypi_server`

# Setuptools version
setuptools (20.9.0) -- from `pip list` in my virtualenv

**Comment by johnthagen** [comment]
This is failing for me in `setuptools 0.54.1`. The recommended solution is to use [`twine upload`](https://twine.readthedocs.io/en/latest/#twine-upload) instead, which prompts for password correctly.
