### ISSUE TITLE
setuptools ignores bdist_wheel files in dependency_links web pages

### ISSUE THREAD

**Issue by nolar** [pypa/setuptools#558]
Step 1. Deploy a local DevPI index (or make a static html page), which enlists href links to .whl files only, http://localhost/page.html:

```
mylib-0.5-py2-none-any.whl
mylib-0.4+1.g9eab5b7-py2-none-any.whl
mylib-0.4-py2-none-any.whl
mylib-0.2.1-py2-none-any.whl
mylib-0.2-py2-none-any.whl
```

Step 2. Add a link to `myapp/setup.py`:

```
from setuptools import setup, find_packages
setup(
    name='myapp',
    install_requires=[
        'mylib >= 0.5',
    ],
    dependency_links=[
        'http://localhost/page.html',
    ],
)
```

Step 3. Run ./setup.py develop.

```
Installed /.../myapp
Processing dependencies for myapp==0.0.0
Searching for mylib>=0.5
Reading http://localhost/page.html
Reading https://pypi.python.org/simple/mylib/
Couldn't find index page for 'mylib' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for mylib>=0.5
error: Could not find suitable distribution for Requirement.parse('mylib>=0.5')
```

PS: names myapp/mylib are replaced; maybe the actually exist on pypi.

Step 4. Now add an href to sdist/egg to page.html:

```
mylib-0.5.tar.gz
mylib-0.5-py2-none-any.whl
mylib-0.4+1.g9eab5b7-py2-none-any.whl
mylib-0.4-py2-none-any.whl
mylib-0.2.1-py2-none-any.whl
mylib-0.2-py2-none-any.whl
```

Step 5. Repeat: ./setup.py develop — it works!

```
...
Installed /.../myapp
Processing dependencies for myapp==0.0.0
Searching for mylib>=0.5
Reading http://localhost/page.html
Best match: mylib 0.5
Downloading http://localhost/mylib-0.5.tar.gz#sha256=4c49f7b8c9400174b36fccd85da3075a98e3c270ad33d01b7d013b31955f96a5
Processing mylib-0.5.tar.gz
Writing /tmp/.../mylib-0.5/setup.cfg
Running mylib-0.5/setup.py -q bdist_egg --dist-dir /tmp/.../mylib-0.5/egg-dist-tmp-i3SHPf
UPDATING build/lib/mylib/_version.py
set build/lib/mylib/_version.py to '0.5'
zip_safe flag not set; analyzing archive contents...
Copying mylib-0.5-py2.7.egg to /.../myapp/ENV/lib/python2.7/site-packages
Adding mylib 0.5 to easy-install.pth file

Installed /.../myapp/ENV/lib/python2.7/site-packages/mylib-0.5-py2.7.egg
...
```

This behaviour is as described in https://pythonhosted.org/setuptools/setuptools.html:

> The dependency_links option takes the form of a list of URL strings. For example, the below will cause EasyInstall to search the specified page for eggs or source distributions,...

But not as expected by a naive user who missed these few words in the whole manual. It is expected that if I prefer to have pure-format DevPI index with wheels only, it would work with setuptools, as it works with `pip install` (well, via `--extra-index-url`, not `--find-links`, but nevertheless).

Python-2.7.10 on Mac OS X.
Pip 8.1.1
Setuptools 20.10.1 (the most recent from PyPI).

**Comment by RonnyPfannschmidt** [comment]
setuptools does not support wheels, please use pip for that

the correct command is `pip install -e .`

**Comment by nolar** [comment]
@RonnyPfannschmidt:

`pip install -e .` does not work either, because it ignores `dependency_links` in `setup.py`. It tries to load local libraries from the official PyPI (and they are absent there in the best case).

If I add the intranet DevPI server to pip configs (via `devpi use --set-cfg`, or env vars, or so), `pip install -e .` still ignores git-based libraries specified as `dependency_links=['git+ssh://git@gitlab.../group/mylib.git@master#egg=mylib']` (it works with `setup.py develop`).

My intention is to add local dependencies (on an intranet DevPI server) to setup.py of a local company's library — i.e., neither the library, nor its dependencies are on PyPI, and sometimes are not on DevPI (but in GitLab).

Without wheels support in setuptools, I need to build totally different infrastructure, up to the level where setuptools is not needed at all, except for the container for meta-info.

The simplest way would be if setuptools support wheels. 

Are there plans to add support for wheels to setuptools?

**Comment by RonnyPfannschmidt** [comment]
I forgot the `--process-dependency-links` option

Also can't test atm

**Comment by benoit-pierre** [comment]
Wheels support was added in v38.2.0 (but pip dropped support for dependency links).
