### ISSUE TITLE
Setuptools/distutils and single-version-externally-managed

### ISSUE THREAD

**Issue by agjohnson** [pypa/setuptools#566]
So I'm not entirely sure if this is a setuptools bug, it very well may be a distutils bug, or perhaps something else.

This was uncovered in rtfd/readthedocs.org#1843 and Azure/azure-storage-python#78

The issue is that given a `setup.cfg` with the option `single-version-externally-managed`, pip install of anything fails:

```
% pyenv local 3.5.1
% pyenv rehash
% rehash
% python -c 'import setuptools; print(setuptools.__version__)'
20.10.1
% python -c 'import virtualenv; print(virtualenv.__version__)'
15.0.1
% virtualenv .
Using base prefix '/Users/anthony/.pyenv/versions/3.5.1'
New python executable in /Users/anthony/tmp/singleversion/bin/python3.5
Also creating executable in /Users/anthony/tmp/singleversion/bin/python
Installing setuptools, pip, wheel...done.
% source bin/activate.csh
[singleversion] % cat > setup.cfg
[install]
single-version-externally-managed=1
[singleversion] % pip install Django
Collecting Django
  Using cached Django-1.9.5-py2.py3-none-any.whl
Installing collected packages: Django
Exception:
Traceback (most recent call last):
  File "/Users/anthony/tmp/singleversion/lib/python3.5/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Users/anthony/tmp/singleversion/lib/python3.5/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Users/anthony/tmp/singleversion/lib/python3.5/site-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/Users/anthony/tmp/singleversion/lib/python3.5/site-packages/pip/req/req_install.py", line 835, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Users/anthony/tmp/singleversion/lib/python3.5/site-packages/pip/req/req_install.py", line 1030, in move_wheel_files
    isolated=self.isolated,
  File "/Users/anthony/tmp/singleversion/lib/python3.5/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/Users/anthony/tmp/singleversion/lib/python3.5/site-packages/pip/locations.py", line 142, in distutils_scheme
    i = d.get_command_obj('install', create=True)
  File "/Users/anthony/.pyenv/versions/3.5.1/lib/python3.5/distutils/dist.py", line 857, in get_command_obj
    self._set_command_options(cmd_obj, options)
  File "/Users/anthony/.pyenv/versions/3.5.1/lib/python3.5/distutils/dist.py", line 901, in _set_command_options
    % (source, command_name, option))
distutils.errors.DistutilsOptionError: error in setup.cfg: command 'install' has no such option 'single_version_externally_managed'
```

`2.7.6`, `2.7.8`, `2.711` fail with the same failure. I'm using `pyenv` locally, but in production we are not, and noticing the same effect. Is this something that setuptools is supposed to patch, does this fall down to distutils, or is there something else missing here? I've had some luck successfully building in the past, I'm not sure what I'm missing above.

As per rtfd/readthedocs.org#1843, this isn't a universal issue, there is something my environment is missing that allows other environments to install without issue.

cc @emgerner-msft @jotes

**Comment by jaraco** [comment]
The `install` command as supplied by setuptools does expose the `--single-version-externally-managed` option. If the setup command is invoked via setuptools, the install command that supports that command will be invoked [from here](https://github.com/pypa/setuptools/blob/master/setuptools/dist.py#L423). But looking at the traceback, it seems that pip is invoking `d.get_command_obj` which is getting the install command from distutils rather than from setuptools.

You'll notice that Setuptools doesn't appear in the traceback.

This looks like an issue with pip but also possibly due to the use of that option while setuptools is being bypassed.

@dstufft Is this something that should be filed with pip or do you have another suggestion?

**Comment by jakirkham** [comment]
That seems correct.

Though it would be really nice if there was a way to specify `single-version-externally-managed` for `setuptools` cases and somehow have this not appear if `distutils` is used. I don't know the right way one might do this, but I definitely have a need to.

I'm very interested in being able to absorb these options into a config file like `distutils.cfg` to simplify a growing packaging effort without having myself or other users worrying about whether things are proceeding through `distutils` or `setuptools`. At present, I can't seem to think of a clean way to go around this issue.

**Comment by agjohnson** [comment]
Sounds like this is safe to move to pip. I've opened pypa/pip#3698 if anyone has any other input.

**Comment by audiohacked** [comment]
Can anyone explain why running `setup.py install` produces one packaging format where as `setup.py install --root` produces a totally different packaging format?
