### ISSUE TITLE
ez_setup.py corrupt zip file (URL not found)

### ISSUE THREAD

**Issue by jtreminio** [pypa/setuptools#568]
# wget https://bootstrap.pypa.io/ez_setup.py -O - | python
    --2016-05-02 14:34:47--  https://bootstrap.pypa.io/ez_setup.py
    Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 23.235.44.175
    Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|23.235.44.175|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 12292 (12K) [text/x-python]
    Saving to: ‘STDOUT’
    
    100%[===============================================================================================================>] 12,292      --.-K/s   in 0s
    
    2016-05-02 14:34:47 (231 MB/s) - written to stdout [12292/12292]
    
    Extracting in /tmp/tmpdj_hrZ
    Traceback (most recent call last):
      File "<stdin>", line 422, in <module>
      File "<stdin>", line 419, in main
      File "<stdin>", line 54, in _install
      File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "<stdin>", line 105, in archive_context
      File "<stdin>", line 89, in __new__
      File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
        self._RealGetContents()
      File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
        raise BadZipfile, "File is not a zip file"
    zipfile.BadZipfile: File is not a zip file

**Comment by jaraco** [comment]
Yep. I'm seeing that in [failing tests too](https://travis-ci.org/pypa/setuptools/jobs/127231414).

**Comment by jaraco** [comment]
@dstufft Can you help? I see setuptools 21 [in pypi](https://pypi.python.org/pypi/setuptools/) but not [in warehouse](https://pypi.io/project/setuptools/#history).

**Comment by dstufft** [comment]
Oh, it's just the CDN cache. Uploading to PyPI itself doesn't issue a PURGE to Warehouse. I just manually purged it.

**Comment by jaraco** [comment]
Thanks @dstufft. That stopped the bleeding. Now we're set to encounter this issue on each new release of Setuptools. What do you recommend bootstrap script should do? I see a few options:

- Add some sort of purge logic to the PyPI/Warehouse pair to purge caches when new releases are made.
- Revert setuptools to use PyPI for retrieving files, but update the downloaders to honor redirects.
- Update the bootstrap script to use warehouse directly, avoiding discrepancies between two indexes.
- Bundle everything.

My preference is for the first or third options. @dstufft, what do you recommend.

**Comment by dstufft** [comment]
The third option is probably reasonable, in the near future pypi.io is going to be the real PyPI anyways.

**Comment by jtreminio** [comment]
Evening,

This seems to be happening again:

    # curl https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py | python
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 12059  100 12059    0     0  58470      0 --:--:-- --:--:-- --:--:-- 58538
    Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-21.0.0.zip
    Extracting in /tmp/tmp61JwRM
    Traceback (most recent call last):
      File "<stdin>", line 415, in <module>
      File "<stdin>", line 412, in main
      File "<stdin>", line 52, in _install
      File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "<stdin>", line 103, in archive_context
      File "<stdin>", line 87, in __new__
      File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
        self._RealGetContents()
      File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
        raise BadZipfile, "File is not a zip file"
    zipfile.BadZipfile: File is not a zip file

**Comment by jaraco** [comment]
@jtreminio You're  using an old reference to ez_setup. You need to grab the latest from bootstrap.io. See the README for details. I'll be removing the bookmarks from Bitbucket to prevent others from running into the same case.

**Comment by jtreminio** [comment]
@jaraco I used the bootstrap.pypa.io URL as well.

Was there a new release last night? If so, there seems to be a ~30 minute window where downloads are broken. I was busy spinning up severals tens of machines last night so I ran into the problem.

**Comment by jaraco** [comment]
@jtreminio: In your second attempt, you'll note that there's no 'Downloading' line in the output. The new ez_setup.py script you've run would have downloaded from the proper location except that it found a copy of setuptools already downloaded, so used that instead. You need to delete `setuptools-21.0.0.zip` and re-run against bootstrap.pypa.io and it will work.

**Comment by jaraco** [comment]
And no, there was not a release last night. `v21.0.0` was [released May 2](https://pythonhosted.org/setuptools/history.html#v21-0-0).

**Comment by chdiza** [comment]
I ran into this same problem, and found that the `ez_setup.py` from `bootstrap.pypa.io` fixed it.

**Comment by riccardomurri** [comment]
I'm seeing this error with older setuptools dists and latest
`ez_setup.py` file:

         $ rm -f setuptools-20.6.8.zip

         $ python setup.py --version
         Downloading https://pypi.io/packages/source/s/setuptools/setuptools-20.6.8.zip
         Extracting in /tmp/tmpmbIUWl
         Traceback (most recent call last):
           File "setup.py", line 40, in <module>
             use_setuptools(version='20.6.8')
           File "/home/rmurri/w/elasticluster/ez_setup.py", line 177, in use_setuptools
             return _do_download(version, download_base, to_dir, download_delay)
           File "/home/rmurri/w/elasticluster/ez_setup.py", line 128, in _do_download
             _build_egg(egg, archive, to_dir)
           File "/home/rmurri/w/elasticluster/ez_setup.py", line 68, in _build_egg
             with archive_context(archive_filename):
           File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
             return self.gen.next()
           File "/home/rmurri/w/elasticluster/ez_setup.py", line 107, in archive_context
             with ContextualZipFile(filename) as archive:
           File "/home/rmurri/w/elasticluster/ez_setup.py", line 91, in __new__
             return zipfile.ZipFile(*args, **kwargs)
           File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
             self._RealGetContents()
           File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
             raise BadZipfile, "File is not a zip file"
         zipfile.BadZipfile: File is not a zip file

Note the `ez_setup.py` is the latest version, at the time of writing::

         $ wget -N https://bootstrap.pypa.io/ez_setup.py
         --2016-05-09 17:55:40--  https://bootstrap.pypa.io/ez_setup.py
         Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 185.31.17.175
         Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|185.31.17.175|:443... connected.
         HTTP request sent, awaiting response... 200 OK
         Length: 12385 (12K) [text/x-python]
         Server file no newer than local file ‘ez_setup.py’ -- not retrieving.

         $ md5sum ez_setup.py
         ce2f1224d50f529b6093e3feb0799f09  ez_setup.py

Am I doing something wrong here?

**Comment by jaraco** [comment]
@riccardomurri I opened a separate ticket #579 for your issue, which I was able to replicate.

**Comment by jaraco** [comment]
Hmm. I see this ticket is still open. It should have closed with the commit above, but did not because the commit was in the bootstrap branch rather than the master branch.
