### ISSUE TITLE
Passing --user option to easy_install when called programmatically

### ISSUE THREAD

**Issue by astrofrog** [pypa/setuptools#574]
I am using an application which doesn't expose the Python interpreter and only an IPython console, so I want to install packages from inside IPython. To do this, I thought the easiest way would be:

```
In [1]: from setuptools.command import easy_install

In [2]: easy_install.main(['numpy', '--user'])
```

However, this doesn't work, as it seems to want to interpret all items in the list as a package name:

```
SystemExit: error: Not a URL, existing file, or requirement spec: '--user'
```

Is there an easy way to pass the ``--user`` flag to the ``easy_install`` command in this way?

**Comment by jaraco** [comment]
Hi @astrofrog. You'll get the same error if you invoke the `easy_install` command with those parameters. Order of options is important (an artifact of being a distutils command), so `--user` must precede dist names.
