### ISSUE TITLE
Automated release process fails to upload some artifacts

### ISSUE THREAD

**Issue by yan12125** [pypa/setuptools#589]
There's only setuptools-21.2.0-py2.py3-none-any.whl on https://pypi.python.org/pypi/setuptools but no setuptools-21.2.0.tar.gz. The latter is necessary for building the unofficial package pypy-setuptools for Arch Linux. Could you upload it?

**Comment by jaraco** [comment]
The tarballs are meant to be uploaded by the [Python 3.5 build](https://travis-ci.org/pypa/setuptools/jobs/131934703). As you can see in that log, the deploy condition was run, but it failed to upload with an internal server error.

I've seen this message before. The Internal Server Errors are intermittent, and when they occur, the file is still uploaded. However, as you've noticed, only the wheel got uploaded and the error caused the process to fail to upload the other dists (tar and zip). I suspect this issue is also causing problems with the bootstrap script which will attempt to get the zip archive.

**Comment by jaraco** [comment]
The failure is probably due to [PyPI 262](https://bitbucket.org/pypa/pypi/issues/262/getting-500-error-when-uploading-python).

**Comment by yan12125** [comment]
How about re-uploading files on receiving HTTP 500? Given it's a rare case.

**Comment by jaraco** [comment]
I've re-uploaded by the sdists by checking out the v21.2.0 code and running `setup.py clean_egg_info sdist upload` to work around this specific incident.

> How about re-uploading files on receiving HTTP 500? Given it's a rare case.

As I'm using Travis CI integration, I'm largely dependent on their implementation. There's no hook to retry. Also, retry is awkward, as the request that errors actually succeeds and it's only the subsequent requests that fail.

I'm not sure it's a rare case either. In my experience, it happens at least 1% of the time, and probably more like 10% of the time.

**Comment by yan12125** [comment]
> probably more like 10% of the time.

Sounds bad. Seems the only way is waiting for PyPI 262. Anyway thanks for manaul uploading.

**Comment by projekt01** [comment]
Can you please deactive the partial release on pypi.and set the latest working version as active and enable again if the zip an rar get released? I'm sure this missing files will get many People into trouble tomorow.

**Comment by jaraco** [comment]
> Can you please deactive the partial release on pypi.and set the latest working version as active and enable again if the zip an rar get released?

The files [were previously uploaded](https://github.com/pypa/setuptools/issues/589#issuecomment-220838879).

![screen shot 2016-05-22 at 13 23 15](https://cloud.githubusercontent.com/assets/308610/15455385/8be008fe-2020-11e6-8c2f-c2789c4868fd.png)

**Comment by projekt01** [comment]
Sorry I didn't see that. My bad,I was reading the other issue and answered to late. Many thanks!

**Comment by jaraco** [comment]
That didn't fix it - Travis uses Twine to upload, which doesn't honor setup.cfg for the upload repository.

**Comment by yan12125** [comment]
The old pypi.python.org still shows 22.0.2: https://pypi.python.org/pypi/setuptools. Seems it's not synchronized with pypi.io?

**Comment by yan12125** [comment]
https://pypi.python.org/pypi/setuptools/json indicates the latest version is 22.0.4, so pip users are not affected :)

And now I can download the package directly from https://pypi.io/packages/source/s/setuptools/setuptools-22.0.4.tar.gz. Many thanks!
