### ISSUE TITLE
missing egg release breaks automated zc.buildout and probably easy_install releases

### ISSUE THREAD

**Issue by projekt01** [pypa/setuptools#590]
The missing egg release on pypi breaks most automated python release which depend on easy install or zc.buildout. Because they can't use wheels and will end in a download error because of the missing egg.
Can you please release eggs for the newest release? Thanks a lot.

**Comment by yan12125** [comment]
Seems we're both victims. #589

**Comment by jaraco** [comment]
This report fits somewhere between a duplicate and invalid. Setuptools has not produced eggs for a long time, but does intend to make source releases, which apparently are suitable for zc.buildout to create eggs. Someone needs to devise a solution for #589 to avoid this unfortunate behavior for the future.
