### ISSUE TITLE
Tests install project under test as dependency

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#602]
When running the `test` command on a project that has circular dependencies such that the project under test is also depended on by one of the project's dependencies, setuptools will install the depended project onto sys.path, causing problems with import mismatches or tests that run not against the current project, but against a released version.

This issue was reported in jaraco/jaraco.collections#1 as a circular dependency exists between `jaraco.text` <-> `jaraco.collections`.

The issue can be worked around by first running egg_info on the project under test, which because it's in the current working directory allows it to be resolved as the dependency for the dependencies.

It's possible this issue only affects namespace packages and that the [sys.path.insert(0, ...)](https://github.com/pypa/setuptools/blob/e726680/setuptools/command/test.py#L145) is sufficient to give simple packages precedence.

**Comment by abravalheri** [comment]
Since `python setup.py test` and `tests_require` have been deprecated for a while, it should be safe to close this issue, right?

We can always reopen it if there is some other information that should be considered...
