### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jakirkham** [pypa/setuptools#612]
Sorry, I think I'm missing something really obvious and could use some help understanding. I think `setuptools` use to be licensed with PSF or ZPL. However, I do not actually see a license file here. All I see is a [classifier]( https://github.com/pypa/setuptools/blob/cb0a2aeb86953d6b3cf6f039bb887fb8c7e8d1e9/setup.py#L132 ) that suggests this is MIT. Is this MIT or something else? Also could we please have a license file here to make that a bit clearer? Thanks.

**Comment by jaraco** [comment]
See #132. The classifier isn't a suggestion but a declaration and follows the distutils guide for declaring a license. I consider inclusion of a license file redundant and error prone.

**Comment by jakirkham** [comment]
Thanks for clarifying.

I'm sure that you guys do a good job of keeping the classifiers up-to-date, not all Python software does though. So that's why I wanted to double check.

Ultimately, it is your call what you do in terms of a license file. IMHO it makes this information easier to find and clearer. For example, who has the copyright on `setuptools`? While I can take a decent guess, this is not something I want to be doing when it comes to licensing.

-------------------------------------------------------------------------------------------------------------------------------------------
As you are higher up in the community and have a chance of influencing this, I figure I should raise this somewhat orthogonal point. Trove classifiers for licenses can be a bit vague in some case. While this doesn't affect MIT so much, it does matter when someone adds the BSD trove classifier, which appears to be totally unversioned AFAICT. Someone could be using this for a BSD 4-Clause license and we would have no way of knowing. While this could be specified with the `license` field, this is sadly rarely the case. It might be nice to clear these up a bit.

**Comment by jakirkham** [comment]
Also would like to point out issue ( https://github.com/pypa/setuptools/issues/357 ). Technically our packaging at conda-forge is non-compliant with the MIT license terms, but I really don't know what to do other than create our own copy of the MIT license and assign the copyright to...PyPA?

**Comment by glyph** [comment]
One of the other issues with licensing under the MIT license but leaving out the MIT license itself is that the _main point_ of the MIT license is this provision:

```
The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.
```

If you don't actually include the license file, then it's not clear how anyone distributing it is supposed to comply.

**Comment by sigmavirus24** [comment]
In addition to @glyph's point, there is a lot of automation (for legal departments especially) that check only for LICENSE files given the common usage of that file to include the license under which the software is distributed. Redistributors often look for the license as well as part of their assessing whether to package something or not, so while you might find the file redundant @jaraco, you will be helping end users trying to use setuptools in a corporate environment as well as redistributors to those end-users. See also [this distutils thread](https://mail.python.org/pipermail/distutils-sig/2016-August/029368.html).

**Comment by jaraco** [comment]
Send a PR. Please include a change log entry.
