### ISSUE TITLE
Typo in class argument name in msvc.py

### ISSUE THREAD

**Issue by inklesspen** [pypa/setuptools#625]
`EnvironmentInfo` takes an optional argument named `vc_min_ver`. However, on line 206, it is instantiated with an `vc_ver_min`, which will cause an exception.

This was reported in the `#sqlalchemy` freenode channel with [this traceback](http://pastebin.com/bsR5igKZ).

**Comment by jaraco** [comment]
Fixed in #627 and release pending for 24.0.1 release.
