### ISSUE TITLE
pypi.python.org documentation is out of date.

### ISSUE THREAD

**Issue by jstrength** [pypa/setuptools#645]
https://pypi.python.org/pypi/setuptools/3.4#unix-wget

As you can see it is still pointing to bitbucket instead of github.

**Comment by jaraco** [comment]
The link you provided is to Setuptools 3.4. At the time Setuptools 3.4 was released, those links were correct. Looking at the latest documentation, the steps no longer reference bitbucket. I can't think of any good way to update old documentation.
