### ISSUE TITLE
Ignores nested install_requires of setuptools

### ISSUE THREAD

**Issue by cdosborn** [pypa/setuptools#657]
I have the following dependency structure:

```
ansible=2.1.0.0 -> paramiko -> cryptography -> setuptools>=11.3
```

In `ansible setup.py`:
```
install_requires = [setuptools, ...]
```

in `cryptography setup.py`:
```
install_requires = [setuptools>=11.3, ...]
```

The **good** case:
I create a venv. By default it uses `setuptools==2.2`. A pip install of paramiko properly upgrades setuptools, because of cryptography's version dependency.

The **bad** case:
I create another venv. Same default version `setuptools==2.2`. A pip install of ansible does not upgrade my setuptools. It **ignores** cryptography's setuptools dependency.

The catch. If I modify ansible's setup.py and remove its dependency of `setuptools` (currently any version) then setuptools gets updated to match cryptography's version dependency.

**Comment by cdosborn** [comment]
This [issue comment](https://github.com/pypa/setuptools/issues/457#issue-144282141) seems very relevant.

**Comment by jaraco** [comment]
Also #391

**Comment by cdosborn** [comment]
This is not an issue with `setuptools` this issue is in pip's resolver. Very relevant thread: https://github.com/pypa/pip/issues/988
