### ISSUE TITLE
setuptools 25.1.4 adds extra quotes on LIBPATH

### ISSUE THREAD

**Issue by minrk** [pypa/setuptools#722]
#715's quoting has caused my appveyor builds to start failing with 25.1.4, due to some extra quoting.

With setuptools 25.1.3, builds [succeed](https://ci.appveyor.com/project/minrk/pyzmq/build/master+97/job/b5xoge86se10eh3a), and with 25.1.4 they [fail](https://ci.appveyor.com/project/minrk/pyzmq/build/master+98/job/80o5mu31egb6s946).

The key difference:

on 25.1.3, the link command had args like:

    "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB"

on 25.1.4, they look like:

    "/LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB""

(note the extra quotes).

These are CPython 3.5 x86 builds on appveyor; I don't know what other versions are affected.

**Comment by ft1337** [comment]
CPython 3.5 amd64 builds on Windows fail, too.

**Comment by anthrotype** [comment]
sorry, I was too fast. It's actually still not working for me either, even after #723.
I probably had incorrectly installed setuptools from the PR branch.

Before #723 was merged, I would get something like this:
```
"/LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB""
```

after #723 I get this:
```
""/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB""
```

**Comment by vallsv** [comment]
Then maybe i have to try on my side why it is not the behaviour on my project.
I only check if my `os.name` is `nt` and if i have more or less the same distutils.spawn.py file. Both are true.
Then, work for monday.
