### ISSUE TITLE
Package dependencies within install_requires

### ISSUE THREAD

**Issue by sivakhno** [pypa/setuptools#724]
I have a the following list of required packages in my setup.py: install_requires=['cython', 'numpy', 'pysam', 'bx-python', 'HTSeq'] After successfully running python setup.py sdist I run into depdnecy problem when trying to install resulting *.tar.gz with pip install

From pip.log:

Downloading numpy-1.11.1.zip (4.7MB): 4.7MB downloaded
Running setup.py (path:/tmp/pip_build_ubuntu/numpy/setup.py) egg_info for package numpy
Running from numpy source directory 
…
Downloading HTSeq-0.6.1p1.tar.gz (226kB): 226kB downloaded
Running setup.py (path:/tmp/pip_build_ubuntu/HTSeq/setup.py) egg_info for package HTSeq
Setup script for HTSeq: Failed to import 'numpy'.
Please install numpy and then try again to install HTSeq.
Complete output from command python setup.py egg_info:
I would have thought that dependencies would be installed sequentially, i.e. 'numpy' would be installed first and then 'HTSeq', but it seems that 'numpy' is being installed at the same time as 'HTSeq'. Also, I wasn’t able to figure out if one can specify dependencies within install_requires http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies , i.e. install_requires=['cython', 'numpy', 'pysam', 'bx-python', 'HTSeq['numpy']'] doesn’t make any difference.

Any suggestions would be most appreciated!

Versions: pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by abravalheri** [comment]
Hi @sivakhno, thank you very much for reporting this issue.

Does this problem still persist with the most updated versions of pip and setuptools?
