### ISSUE TITLE
Option to drop Python versioned entrypoints scripts

### ISSUE THREAD

**Issue by jakirkham** [pypa/setuptools#726]
Seems there is a copy of `easy_install` with the Python version embedded in the name (e.g. `easy_install-3.5`). It would be nice if there was a build option to disable this versioned entrypoint script from being installed. If there is already such an option, it would be nice to know what it is.

**Comment by jaraco** [comment]
https://github.com/pypa/setuptools/blob/master/setup.py#L40

**Comment by jakirkham** [comment]
Right, thanks. Sorry for the noise.
