### ISSUE TITLE
"launcher manifest.xml" should not have a space

### ISSUE THREAD

**Issue by owal-gitter** [pypa/setuptools#746]
Why on earth does the launcher manifest file have to have a space? Nothing else does.

**Comment by jaraco** [comment]
See [this comment](https://github.com/pypa/setuptools/issues/134#issuecomment-202911616) explaining why the use of spaces is preferable.

**Comment by owal-gitter** [comment]
Is this about aesthetics or functionality? Tools are supposed to be functional first, pretty second.

**Comment by jayeye** [comment]
I can't believe this has not been fixed in so long. Just admit you made a bad call and fix it already!

**Comment by jayeye** [comment]
@jaraco: you are trying to come up for excuses for a bad decision you made, and you are refusing to admit you were wrong. Nobody should ever use spaces in filenames. Most unix tools, starting with the shell, can fail miserably and in subtle ways.  Bazel fails (which is what led me here). Code is not written to please liberal arts majors; code is written to get work done. Just like you have accepted that you cannot use a slash in a filename, you should accept that you should not use a space in a filename. You could, in TENEX, and it was an infinite source of pranks when we were undergrads, but that was a long time ago.

There are also natural languages that do not separate words with spaces; Thai is an example, so your argument about using spaces in written text is already invalid.
