### ISSUE TITLE
entry_point scripts doesn't pass command line arguments to module:main

### ISSUE THREAD

**Issue by sria91** [pypa/setuptools#757]
`entry_point` console (and gui) scripts created using setuptools doesn't pass command line arguments to `module:main`.

Below is the relevant code snippet from `setup.py`

```
...
	entry_points={
		'console_scripts': [
			'module = module:main',
		],
	},
...
```

**Comment by anthrotype** [comment]
you need to use `sys.argv` inside `main` to access command line arguments.

```python
import sys

def main(args=None):
    if args is None:
        args = sys.argv[1:]
    print(args)

if __name__ == "__main__":
    main()
```

**Comment by jaraco** [comment]
Or use [autocommand](https://pypi.org/project/autocommand):

```
from autocommand import autocommand

@autocommand(__name__)
def main(arg):
    print(arg)
```
