### ISSUE TITLE
get_default_cache writes to a roaming profile directory in recent Windows by default

### ISSUE THREAD

**Issue by jonmoore** [pypa/setuptools#763]
In get_default_cache the first choice of directory to write to on Windows is given by %APPDATA%.  In Windows Vista this is part of the roaming profile for the user, not the local one, i.e. it writes to C:\Users\username\AppData\Roaming, not C:\Users\username\AppData\Local - see https://msdn.microsoft.com/en-us/library/dd378457(v=vs.85).aspx.

This increases the roaming profile size and causes Windows login delays for users.

It may be best to add %LOCALAPPDATA% as the first possible directory to write to.

**Comment by jaraco** [comment]
Yes, that's right. It's not obvious to me that LOCALAPPDATA would be preferable, though my instinct is the same. As far as I can tell, the reference you passed doesn't give any guidance on which profile directory to use. Following [appdirs](https://pypi.python.org/pypi/appdirs) as a guide, it does seem to prefer 'local' for cache. Perhaps pkg_resources should simply use appdirs.
