### ISSUE TITLE
python setup.py bdist --format=rpm

### ISSUE THREAD

**Issue by 0xHM** [pypa/setuptools#767]
running install_scripts
Installing easy_install script to /home/builder/tmp/setuptools-26.0.0/build/bdist.linux-x86_64/rpm/BUILDROOT/setuptools-26.0.0-1.x86_64/usr/bin
Installing easy_install-2.7 script to /home/builder/tmp/setuptools-26.0.0/build/bdist.linux-x86_64/rpm/BUILDROOT/setuptools-26.0.0-1.x86_64/usr/bin
writing list of installed files to 'INSTALLED_FILES'
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 /home/builder/tmp/setuptools-26.0.0/build/bdist.linux-x86_64/rpm/BUILD/setuptools-26.0.0
/usr/lib/rpm/sepdebugcrcfix: Updated 0 CRC32s, 0 CRC32s did match.
find: ‘debug’: No such file or directory
+ /usr/lib/rpm/check-rpaths /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Bytecompiling .py files below /home/builder/tmp/setuptools-26.0.0/build/bdist.linux-x86_64/rpm/BUILDROOT/setuptools-26.0.0-1.x86_64/usr/lib/python2.7 using /usr/bin/python2.7
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: setuptools-26.0.0-1.noarch
error: File must begin with "/": (dev).tmpl

RPM build errors:
    File must begin with "/": (dev).tmpl
error: command 'rpmbuild' failed with exit status 1

**Comment by 0xHM** [comment]
The reason is the space you have space in file name:

setuptools/script (dev).tmpl

**Comment by jaraco** [comment]
Setuptools does have spaces in some of the filenames in the package. I believe it generates everything properly.

I'm a little surprised that rpm can't handle spaces properly. I'm pretty sure this issue would have been reported before if RPM had issues handling spaces in package filenames.

If there's something Setuptools could do to better support RPM, we can consider that, but renaming the files will only be considered as a last resort.
