### ISSUE TITLE
Requirements using PEP 508 direct references ignore the URL

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [pypa/setuptools#787]
Specifying a requirement with a PEP 508 direct reference -- that is, "foo @http://example.com/pkg/foo.tar.gz" and then installing with easy_install will ignore the URL specified and go and find foo from pypi.

Hacking a local copy of unittest2 to contain an extra dependency on bzr with a direct reference:

Processing dependencies for unittest2==1.1.0
Searching for bzr@ http://example.com/foo/bzr-2.7.0.tar.gz
Reading https://pypi.python.org/simple/bzr/
Downloading https://pypi.python.org/packages/62/3a/81325e34bcc78f67cc33dfac64f44e7c8329d4481dec1b789267b98644c3/bzr-2.7.0.tar.gz#md5=a601e465d323b916dcf025d05486e604

I'm not quite certain what setuptools with out benefit of easy_install does in this case.

**Comment by MaxNoe** [comment]
Just ran into this issue. Support for PEP 508 would be really aprreciated!

**Comment by abravalheri** [comment]
Hello, I suppose we can close this issue now that `easy_install` has been deprecated and widely replace by other installation means, such as `pypa/pip`.

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
