### ISSUE TITLE
Compatible releases are not compatible with Semantic Versions less than 1.0.0.

### ISSUE THREAD

**Issue by dmtucker** [pypa/setuptools#793]
According to [PEP440](https://www.python.org/dev/peps/pep-0440/#semantic-versioning),
> The "Major.Minor.Patch" (described in this PEP as "major.minor.micro") aspects of semantic versioning (clauses 1-9 in the 2.0.0-rc-1 specification) are fully compatible with the version scheme defined in this PEP

Also, 
> A compatible release clause consists of the compatible release operator ~= and a version identifier. It matches any candidate version that is expected to be compatible with the specified version.

According to [Semantic Versioning clause 4](http://semver.org/#spec-item-4),
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

By this logic, I would not expect `pkgdep ~= 0.1` to be satisfied, for example, by 0.2.0, since there is no guarantee that 0.2.0 will be backwards-compatible with 0.1.x; however, this seems to be the current behavior when using the compatible release operator in `install_requires`.

Strictly speaking, I'm not even sure `pkgdep ~= 0.1.0` should imply 0.1.1, although I suspect that is divergent from de facto expectations.

**Comment by jaraco** [comment]
but imho the semver spec is a bad design in that regard. In any case, there's little Setuptools can do about it. If the spec should be updated, that's with semver. If the pep should be clarified, that's with the pep process. If the implementation should change, that's with packaging, maybe with an update here following that release.

Good luck.

**Comment by dmtucker** [comment]
Oops, ya I suppose this is more of a `pip` issue... Moving to https://github.com/pypa/pip/issues/3982
