### ISSUE TITLE
Switching from Bitbucket to GitHub, Installing Setuptools documentation not updated

### ISSUE THREAD

**Issue by zoomx** [pypa/setuptools#799]
The installation shell commands here
[https://pypi.python.org/pypi/setuptools/3.4.1](url)
have links to bitbucket but now the repository is on GitHub. You get a 404 error.

[https://bootstrap.pypa.io/ez_setup.py](url) is the new URL.
I believe that the documentation should be updated.

**Comment by jaraco** [comment]
Your link references an old version of Setuptools. I believe the current releases include current references. I'm sorry the old notes contain old, broken references, but I don't believe it's possible to update those references, and even if it was, I don't think we have the resources to update all of them. Thanks anyhow for the report.

**Comment by zoomx** [comment]
This was the first result on Google. But I was so stupid not to read carefully "Latest Version: 27.3.0!" on the top.
