### ISSUE TITLE
ez_setup should remove bad downloaded tar file if there was a failure

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#81]
Originally reported by: **sureshvv (Bitbucket: [sureshvv](http://bitbucket.org/sureshvv), GitHub: [sureshvv](http://github.com/sureshvv))**

---

It leaves behind a zero length file. Subsequent runs assume the file is good and fail at a different point.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/81

**Comment by abravalheri** [comment]
Hello, I think we can close this issue now, since `ez_setup` is no longer used by setuptools and the standard way of installing packages is now via `pip`.

If anyone would like to re-open this issue, please feel free to write a comment bellow and we will be gladly consider the new information 😄.
