### ISSUE TITLE
pkg_resources should present an interface for reporting installed packages

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#817]
In pypa/pip#3710, I identified an issue where pip would simultaneously uninstall a present but not installed package while simultaneously failing to uninstall the installed version.

The proposed way forward is for `pkg_resources` to present another call, similar to get_distributions, but that only returns those that are installed.

I welcome contributions to implement this functionality (presuming it doesn't already exist).

**Comment by piotr-dobrogost** [comment]
Does this have to be another call? What about adding `installed=False` parameter?

**Comment by jaraco** [comment]
> Does this have to be another call?

Not necessarily.

> What about adding installed=False parameter?

My opinion is that a boolean parameter is [generally an anti-pattern](http://blog.iannelson.systems/back-to-basics-on-the-use-and-abuse-of-the-humble-boolean/), though it really depends on the implementation. If the two functions are essentially doing the same thing with the selector happening deep in a loop, then the burden of copy-pasting most of that logic into two separate functions is worse than having a boolean parameter. The best implementation, however, will have good separation of concerns and without repetition.

That said, I'd be happy with any implementation that works and has tests, and we can refine the approach later if necessary.

**Comment by jaraco** [comment]
At this point, pkg_resources is largely deprecated. As a result, I'd like to see this functionality implemented elsewhere, possibly leveraging `packaging` and `importlib.metadata`.
