### ISSUE TITLE
setup.py: incorrect dependency link 

### ISSUE THREAD

**Issue by dairiki** [pypa/setuptools#827]
Setuptools’ setup.py adds a link for ``certifi`` to ``dependency_links``.  The link it adds (``https://pypi.python.org/packages/source/c/certifi/certifi-2016.9.26.tar.gz``) is broken (404.)

I'm not totally sure what's going on here.  My guess is that PyPI has changed how downloads are filed.  (Older packages seem to still be available under ``/packages/source``, but recently released packages appear not to be.)

In any case, this breaks ``zc.buildout`` — at least for me.  Buildout picks up the broken dependency link from the setuptools egg and uses it (unsuccessfully) if an attempt is made to install ``certifi==2016.9.26``.

**Comment by dairiki** [comment]
Work-around for ``zc.buildout``: Assuming that the use of ``dependency_links`` is not required for your project, set ``use-depedency-links = false`` in buildout.cfg.

**Comment by jaraco** [comment]
@dstufft Do you know what URL setuptools should use for these dependency links?

**Comment by dstufft** [comment]
``https://files.pythonhosted.org/packages/source/c/certifi/certifi-2016.9.26.tar.gz``

**Comment by dairiki** [comment]
Thank you!
