### ISSUE TITLE
`setuptools.extension.Extension` is old-style class

### ISSUE THREAD

**Issue by johnyf** [pypa/setuptools#835]
As of `setuptools == 28.7.0`, [`setuptools.extension.Extension`](https://github.com/pypa/setuptools/blob/6d05b8dce90985455dce0649e04955985f336b04/setuptools/extension.py#L32) is an old-style class.
In Python 2.7, this raises an `AttributeError` with `cython == 0.25.1` when an `Extension` instance is passed to `collections.Iterable`, as described here: https://github.com/cython/cython/issues/1507.

I would like to ask whether this is intentional (I suspect that yes), and whether it can be avoided.
The root cause is that [`distutils.extension.Extension`](https://github.com/python/cpython/blob/ee324a8f516318e84914ebd18f3e8068faec14f9/Lib/distutils/extension.py#L26) is an old-style class.

**Comment by jaraco** [comment]
That's right - because Setuptools intentionally derives from `distutils.extension.Extension`, it must be an old style class. I can think of no way to avoid it other than to upgrade to Python 3.

**Comment by johnyf** [comment]
Thanks for the clarification. The package where this arose supports both Python 2 and 3, so for the Python 2 case a possible workaround is to subclass it:

```python
class Extension(setuptools.extension.Extension,object):
    pass
```

and pass an instance of this subclass to `cythonize`. This ensures that a new-style class propagates around.

For the Cython issue mentioned in the OP, this proved unnecessary, because `cythonize` is supposed to receive an iterable of `Extension` instances, so passing a singleton `list` avoids the issue. But I noted the workaround here, in case someone is looking for a solution, and cannot avoid this (clumsy) one.
