### ISSUE TITLE
ez_setup should not fail if current directory is not writable

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#84]
Originally reported by: **plemarre (Bitbucket: [plemarre](http://bitbucket.org/plemarre), GitHub: [plemarre](http://github.com/plemarre))**

---

Hi, running ez_setup.py script will download the installation file in the same location than the script by default. It can be a problem if the script is located in a directory that is not writable, e.g. a DVD for example.

I propose to use tempfile.mkdtemp to use a more reliable temporary location.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/84

**Comment by abravalheri** [comment]
Hello, I think we can also close this issue based on the fact that `ez_setup` is deprecated and no longer used.

If anyone involved in this discussion would like to reopen the issue with some other facts that we are not considering, please don't hesitate in posting a comment in this thread.
