### ISSUE TITLE
Missing tag for v29.0.0

### ISSUE THREAD

**Issue by nicoddemus** [pypa/setuptools#856]
Probably forgot to push it?

**Comment by jaraco** [comment]
v29.0.0 has not been released, but I've gone ahead and released it just now. I expect there are still outstanding test failures that need to be addressed, but I'm fairly confident those failures aren't related to the changes in v29.0.0, so I'll plan to deal with those later.

**Comment by nicoddemus** [comment]
Strange, now I don't remember where I've seen a v29.0.0 release which prompted me to take a look at the tag... if that was not the case and I'm was mistaken, sorry for the noise!

**Comment by jaraco** [comment]
My guess is you were reading the changelog in the repo. I'm not aware it was referenced elsewhere. No worries, though.

**Comment by nicoddemus** [comment]
> My guess is you were reading the changelog in the repo.

Oh right, that was it. 😅

**Comment by nicoddemus** [comment]
I now see that `29.0.0` has been released, but I don't see the tag here on GitHub. (I would reopen the issue but it seems that I can't).

**Comment by jaraco** [comment]
Heh. Seems your ticket was prescient. Yes, I failed to push the tags, as I'm for the first time using git to push the tags and because I had to make a manual release (due to #860), where an automatic release would not have been cut without the proper tags. I've just pushed the tag now.

**Comment by nicoddemus** [comment]
Thanks! 😁
