### ISSUE TITLE
--tag-time option

### ISSUE THREAD

**Issue by mar10** [pypa/setuptools#858]
I use s.th. like this to upload daily- or test-builds to PyPI (I don't want to bump the version number each time):

setup.cfg:
```
[aliases]
pypi_daily = egg_info --tag-build=.dev --tag-date sdist bdist_wheel register upload
```
Problem is, that this only works once a day, since the releases are named `foo-0.0.3.dev20161121`.

I would like to suggest a way to add hours, minutes, and seconds to the tag. Possible approaches could be
  - a new option `--tag-time`
  - allow to pass args to the existing option, e.g. `--tag-date="%Y%m%d-%H%M%S"`

**Comment by jaraco** [comment]
This request seems reasonable. I'm more inclined toward the latter approach, though that may have compatibility implications.

I wonder if there isn't an even more general option, something like `tag-format`, which accepts format strings like `{date}` or `{time}` or possibly other factors.

Before we go down that route, I wonder if there's not a better solution in [setuptools_scm](https://pypi.org/project/setuptools_scm). It uses scm details to provide unique distribution tags for non-tagged commits on the repo. Might this work for your needs?

**Comment by mar10** [comment]
Probably - thanks for the pointer, I will give it a try.
