### ISSUE TITLE
python bytecode not included in egg for capitalised extensions "*.Py"

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#87]
Originally reported by: **bryancole (Bitbucket: [bryancole](http://bitbucket.org/bryancole), GitHub: [bryancole](http://github.com/bryancole))**

---

I have a package which I distribute as a zipped egg. One of the python modules within the egg happens to have the extension ".Py" (capitalised, rather than lowercase ".py"). This doesn't not cause python any problems in importing the module. Nor does it prevent setuptools from creating an egg. The setuptools output for bdist_egg indicates that it find the module and even compiles it to a .pyc file. However, while the source code gets included in the egg, the bytecode file is omitted. This causes the module import to fail when the packages is installed in zipped egg form (because there is no bytecode and python can't add bytecode to a zip archive).

I think this is a bug in setuptools. It doesn't seem like there's any reason why the .pyc file shouldn't be included in the egg. If there is some reason, then setuptools should fail with an exception during the egg build process.

BTW. This is occuring on Windows. I haven't tested on linux or other platforms.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/87

**Comment by silkentrance** [comment]
This is nonsense. Windows filesystems are case sensitive. Fixing that would require special casing the extension, but why?

**Comment by abravalheri** [comment]
It's been a while that setuptools have this issue open but unfortunately all the attempts made to reproduce this problem seem to indicate it might be already solved in recent versions.

If anyone has more information on the undesired behaviour reported here, please feel free to comment bellow (preferably with an example and steps that would help to reproduce the result 😅), or open a new issue.
