### ISSUE TITLE
Namespace package zope cannot find modules during testing

### ISSUE THREAD

**Issue by FRidh** [pypa/setuptools#870]
In Nixpkgs we recently updated setuptools from 26.1.1 to 28.8.0 (and the issue also occurs with the latest 30.2.0). This seemed to break the testing of several zope modules for us. The modules do actually work, its just that when running `python setup.py test` we get import errors. Note that at this point we populate `PYTHONPATH` with all the dependencies. Any idea what could have caused this?

https://github.com/NixOS/nixpkgs/issues/20791

**Comment by jaraco** [comment]
I suspect the offending release is [v28.3.0](http://setuptools.readthedocs.io/en/latest/history.html#v28-3-0), and in particular the work for #805. Can you confirm the issue only occurs on Python 3.3+? If so, that's almost certainly the cause.

The good news is that in #250, I'm making some progress in a better technique that will fully and properly address the behavior for Python 3.5+, and based on this ticket, I'll probably opt to revert the behavior from #805 for Python 3.3 and 3.4.

**Comment by FRidh** [comment]
Thanks for looking into this. The issue doesn't occur on 2.7, but it does indeed show up on 3.3, 3.4 and 3.5.

**Comment by jaraco** [comment]
Can you please retry with setuptools v31.0.0? One caution to consider is that any namespace packages must be installed from source or from wheels generated with setuptools 31 or later (or older than 28.3.0) due to #845.

**Comment by FRidh** [comment]
Now we get `AttributeError: '_NamespacePath' object has no attribute 'sort'`.

**Comment by FRidh** [comment]
so `AttributeError: '_NamespacePath' object has no attribute 'sort'` happens only with 3.5, not 2.7, 3.3 or 3.4.

**Comment by tseaver** [comment]
@jaraco We are seeing the 3.5-only failures as well in `google-cloud-python`.

**Comment by tseaver** [comment]
Looks like that has been opened as #885.

**Comment by FRidh** [comment]
This is broken again with 32.0.0.

**Comment by FRidh** [comment]
To be more precise, it is only broken like this with 3.5.

**Comment by ManuelGysin** [comment]
With 34.1.1 still broken.

**Comment by jaraco** [comment]
This discussion continues in #912.
