### ISSUE TITLE
meatdate

### ISSUE THREAD

**Issue by siminghua** [pypa/setuptools#874]
Traceback (most recent call last):
  File "setup.py", line 180, in <module>
    require_metadata()
  File "setup.py", line 20, in require_metadata
    raise RuntimeError(msg)
RuntimeError: Cannot build setuptools without metadata. Run bootstrap.py

**Comment by siminghua** [comment]
thanks.

**Comment by jaraco** [comment]
Yep. Setuptools has a bootstrapping issue. You have to do as the error message says and run bootstrap.py before running setup.py.
