### ISSUE TITLE
Support requiring from developmental releases

### ISSUE THREAD

**Issue by tuukkamustonen** [pypa/setuptools#875]
With following in `setup.py`:

    install_requires=[
        'mypackage==1.0.0.dev1'
    ]

`python setup.py develop`:

```
Installed /home/musttu/XXX
Processing dependencies for wires-aws==2.2.1.dev0+ng42323d9.d20161208
Searching for mypackage==1.0.0.dev1
Reading https://INTRA-PYPI/index/+simple/mypackage/
Authenticating as musttu for https://INTRA-PYPI/index/+simple/mypackage/ (from .pypirc)
No local packages or working download links found for mypackage==1.0.0.dev1
error: Could not find suitable distribution for Requirement.parse('mypackage==1.0.0dev1')
```

Looks like it searches PyPI (or our company-devpi in this case) for matching version, but just doesn't find/accept one when you use developmental release as version identifier.

https://www.python.org/dev/peps/pep-0440/#developmental-releases

**Comment by jaraco** [comment]
Your usage should work (and has worked for me in the past). 

What happens when you run `easy_install -i https://INTRA-PYPI/index/+simple/mypackage/ mypackage==1.0.0.dev1`? What links appear on that page for mypackage?

**Comment by tuukkamustonen** [comment]
Hmm, it's the same output (btw. I'm on `30.2.0`):

```bash
09:06 $ easy_install -i https://INTRA-PYPI/index/+simple/ mypackage==1.0.0.dev1
Searching for mypackage==1.0.0.dev1
Reading https://INTRA-PYPI/index/+simple/mypackage/
Authenticating as musttu for https://INTRA-PYPI/index/+simple/mypackage/ (from .pypirc)
No local packages or working download links found for mypackage==1.0.0.dev1
error: Could not find suitable distribution for Requirement.parse('mypackage==1.0.0.dev1')
```

`pip install -i https://INTRA-PYPI/index/+simple/ mypackage==1.0.0.dev1` installs the package successfully.

We are running `devpi` as internal PyPI mirror, do you think there's some conflict with it?

**Comment by tuukkamustonen** [comment]
Thanks. And interesting. Our devpi indeed does not require authentication, but looks like setuptools uses it (from `~/.pypirc`) even when reading, if username is set. I don't actually have password set in `~/.pypirc`, but that makes no difference, so I assume even though setuptools reports `Authenticating as musttu` it actually doesn't (because there is no password available, it cannot). So, there's no functional impact in that, but I think that the logging is misleading and should be clarified (in another ticket). Agree?

It seems my problems pour in from something else - I cannot install any in-house packages through `easy_install` (but can using `pip`). I'll investigate.

**Comment by tuukkamustonen** [comment]
Uhh, how stupid am I? I forgot `easy_install` does not support wheel packages! Oh jeez...

So, false alarm, I will close this and just stick with `pip install -e .`.

However, do you want me to open another ticket about this bit below?

> Looks like setuptools uses username (from ~/.pypirc) even when reading, if username is set. I don't actually have password set in ~/.pypirc, but that makes no difference, so I assume even though setuptools reports `Authenticating as musttu` it actually doesn't (because there is no password available, it cannot). So, there's no functional impact in that, but I think that the logging is misleading and should be clarified (in another ticket).

Also, if you omit `username` from `~/.pypirc` then `easy_install` will log just `Authenticating as  for ...`.

**Comment by tuukkamustonen** [comment]
And offtopic: any plans to merge `pip` and `easy_install` (or rather, `pip` and `setuptools`) now that `pip` is even included in py3 releases?

**Comment by jaraco** [comment]
> any plans to merge pip and easy_install

[Yes](https://github.com/pypa/setuptools/issues/855#issuecomment-265727260)

> do you want me to open another ticket about this bit below

Not really, since it doesn't appear to be causing any problems... and will likely be replaced. Thanks.
