### ISSUE TITLE
Not working with the keyring

### ISSUE THREAD

**Issue by diogobaeder** [pypa/setuptools#880]
Hi,
Although the `upload` command from the package has a condition to use the `keyring` (see https://github.com/pypa/setuptools/blob/9d12348e26d8c143d0b675ed147094a9e54e1c97/setuptools/command/upload.py#L17 ), this condition is never reached; no matter if I comment out the `password` config from `~/.pypirc` or just put an empty value there, the `upload` command always prompts for the password.
Thanks,
Diogo

**Comment by jaraco** [comment]
As you can see in the [load from keyring call](https://github.com/pypa/setuptools/blob/9d12348e26d8c143d0b675ed147094a9e54e1c97/setuptools/command/upload.py#L21-L29), you will be prompted for a password under a number of conditions:

1. The keyring module raises an error on import.
2. The password is not found.
3. The password resolves to blank.

Also, any other exception.

You should first double-check that your password is in the keyring. Do you see the password when you invoke `keyring get <url_for_repository> <username>`? Double-check that <url_for_repository> is an exact match for the URL as indicated in .pypirc or setup.cfg.

Failing that, you could use pdb to inspect your environment to better understand why the keyring is not resolving.

```
$ python -m pdb setup.py -q sdist upload
> /Users/jaraco/Dropbox/code/main/setuptools/setup.py(4)<module>()
-> """
(Pdb) break setuptools/command/upload.py:27
Breakpoint 1 at /Users/jaraco/Dropbox/code/main/setuptools/setuptools/command/upload.py:27
(Pdb) continue
warning: no files found matching '*' under directory 'setuptools/_vendor'
> /Users/jaraco/Dropbox/code/main/setuptools/setuptools/command/upload.py(27)_load_password_from_keyring()
-> return keyring.get_password(self.repository, self.username)
(Pdb) self.repository
'https://upload.pypi.org/legacy/'
(Pdb) self.username
'jaraco'
(Pdb) keyring.get_password(self.repository, self.username)
'<elided>'
(Pdb) quit
Password: 
```

If the code doesn't stop at line 27, you probably don't have a working keyring library installed. If `get_password` returns an empty string, it may not be configured for the backend you expect. Call `keyring.core.get_keyring()` to ensure that you're connecting to the backend you expect.

Hope that helps. Let us know what you find.

**Comment by diogobaeder** [comment]
Sorry, my bad. I didn't know I had to use the full repository URL as the service name for the keyring. Working fine for me now. :-)
