### ISSUE TITLE
setuptools.compat

### ISSUE THREAD

**Issue by Zitrax** [pypa/setuptools#881]
Hi, this is a question - not an issue.

I have some older code that use the following import:

    from setuptools.compat import reraise

which now gives:

    ImportError: No module named 'setuptools.compat'

This code did work earlier so I assume something has changed in setuptools - or is there something else missing ? Searching this project I see a `def reraise` in _setuptools/pkg_resources/_vendor/six.py_. The path made it seemed a bit "internal". What is the correct way to import this now ?

**Comment by jaraco** [comment]
Yeah, compat was an internal module and was never meant for external consumption. Your best bet is to depend on [six](https://pypi.org/project/six) and use re-raise from there.
