### ISSUE TITLE
MANIFEST.in `recursive-include` seems to be ignored.

### ISSUE THREAD

**Issue by idlesign** [pypa/setuptools#886]
Regression since v28.5.0
Reported at idlesign/django-sitetree#222
Related to #764
Manifest example: https://github.com/idlesign/django-sitetree/blob/v1.6.0/MANIFEST.in

`sdist` creates a package without files mentioned in MANIFEST.in.

**Comment by idlesign** [comment]
The reason is that the following doesn't include `*`, so

```
recursive-include sitetree/templates .html
```

should rather be
```
recursive-include sitetree/templates *.html
```

I'll fix that in my packages, yet I have a suspicion that I'm not the only one.

@jaraco This one could be closed I think, but kept in mind.

**Comment by jaraco** [comment]
This seems to be another manifestation of #849. @timheap, it seems we're now in an awkward situation where we're half-compatible with the old behavior (supporting partial matches for global-exclude but not recursive-include).

It seems everybody's instinct is that the old behavior was undesirable. My temptation is to roll back the changes in #853 and clarify the change in behavior in the changelog for 28.5.0 (and of course the new version).

@timheap, how does that sound to you? Would you be willing to put together the patch?

**Comment by timheap** [comment]
@jaraco I agree that the old behaviour was undesirable. PR #890 reverts the changes in #853, and adds a note to the changelog about the change in behaviour.

**Comment by jaraco** [comment]
Excellent. Thanks @timheap for the fix, released in Setuptools 32.
