### ISSUE TITLE
Namespace .pth file breaks module execution 

### ISSUE THREAD

**Issue by robagar** [pypa/setuptools#888]
I have a package _foo_ which I can execute with `python3 -m foo`

But if I install a second package which has _foo_ as a namespace package (installing files in _foo.bar.baz_), the _.pth_ file inserts a dummy `ModuleType` object into `sys.modules['foo']`. The object has the namespace name but nothing else.

Now when I run `python3 -m foo` I get a cryptic error complaining that `foo.__spec__ is None`

Looking at the _.pth_ file, it probably only happens for Python < 3.5

**Comment by jaraco** [comment]
Hi robagar. I suspect there's no solution for this, as the stdlib for Python 3.3 and 3.4 doesn't have the necessary APIs to properly populate `__spec__` for namespace packages. See [this comment](https://github.com/pypa/setuptools/issues/250#issuecomment-265633984).

I'm tempted to add additional support to setuptools to backport the Python 3.5 behavior and to use it if available in the `-nspkg.pth` handler.

**Comment by matham** [comment]
We just ran into this in the kivy project. We package its dependencies as separate kivy.deps.xxx projects but now that breaks on import https://github.com/kivy/kivy/issues/4829 because of the mentioned issue.

**Comment by matham** [comment]
Actually, I'm not sure if it's the same issue since it was reported for 3.5 as well for us. Although I only reproduced it for 3.4. Should I open a different issue?

**Comment by jaraco** [comment]
@matham : I think your issue is different, though related in that it involves namespace packages. Please file a separate ticket, and try to describe as minimal an example as possible where I can replicate your issue.

**Comment by jaraco** [comment]
@robagar Can you provide an example that describes the behavior you're seeing that you think should work?

**Comment by jerryz1982** [comment]
https://bugs.launchpad.net/devstack/+bug/1651292
i noticed a recent failure caused by openstack.nose-plugin and openstacksdk sharing same namespace maybe related to the bug.
definitions in __init__.py in openstacksdk didn't take effect after openstack.nose-plugin was installed.

**Comment by jaraco** [comment]
@jerryz1982 I think your issue is more like that of mathams, as found in #895.

**Comment by jaraco** [comment]
I don't believe there's anything to be done here. The [pmxbot](/yougov/pmxbot) package demonstrates a namespace package (`pmxbot`) which can be executed with `-m`.
