### ISSUE TITLE
Disable interpolation on config file parsing

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#889]
In [Python 20754](http://bugs.python.org/issue20754), we've observed that interpolation was inadvertently turned on for setup.cfg parsing in the update to Python 3. A patch is being drafted to fix the issue for bugfix versions of Python 3.5 and 3.6 and for Python 3.7, but the issue will persist for older Pythons. Setuptools can provide forward compatibility.

**Comment by jaraco** [comment]
Looks like maybe I shouldn't have merged this functionality quite yet. The tests aren't passing on Python 3.

**Comment by jaraco** [comment]
The test that's failing is an integration test where the unpatched Distribution class isn't being resolved correctly now that Distribution has multiple bases.

**Comment by jaraco** [comment]
Aha. The tests would have been failing on Python 2 except that the integration tests are skipped in environments with pbr installed... and since setuptools depends on mock on those older pythons and mock depends on pbr, those tests are skipped regularly.

**Comment by jaraco** [comment]
That latest commit addresses the issue. I've re-tagged v32.3.0 and the release is pending now.

**Comment by jaraco** [comment]
I'm re-opening this issue. After correcting the two issues with the implementation, I see (due to [failing tests](https://travis-ci.org/pypa/setuptools/builds/257986137)) that interpolation has been enabled for setup.cfg parsing even in Python 2. So disabling config parsing is a backward-incompatible change and not merely a re-alignment with past expectations as I'd originally thought.

**Comment by jaraco** [comment]
I've done a force-push of master back to de05e931 while this issue gets resolved in the issue-889 branch.

**Comment by jaraco** [comment]
I've also deleted the v36.2.5 tag as it was [never released](https://travis-ci.org/pypa/setuptools/builds/257988967). Big thanks to Sviatoslav and Travis-CI for setting up build stages and preventing a broken release.

**Comment by jaraco** [comment]
Based on my new understanding, I've updated the changelog in 4688a68 to reflect a backward-incompatible release. I'm reluctant to make this release because I'm unsure of the impact it will have, and more importantly, it will break existing packages that contain a setup.cfg that either depends on interpolation or escapes percent characters... and for those projects to be compatible, they'll become incompatible with prior releases of setuptools.

Without more data or feedback, I'm not sure what to do.

**Comment by benoit-pierre** [comment]
With the change in fbcbb510 to disable interpolation for `.pypirc`, I'd expect `setup.cfg` (and others) to be handled the same. But I agree that if interpolation has been allowed all this time, there are bound to be some projects that will break because they worked-around this by doubling %.

**Comment by jaraco** [comment]
As [suggested by @henryiii](https://github.com/pypa/setuptools/issues/1260#issuecomment-1044771738), we're accepting this behavior as a feature. See #1648 for the effort to document the support for interpolation in setup.cfg. I've moved the `issue-889` branch to `refs/archive/issue-889`. Same for `refs/archive/revert-1180-fix_889_and_non-ascii_in_setup.cfg_take_2`.
