### ISSUE TITLE
test command does not return failure code

### ISSUE THREAD

**Issue by cedk** [pypa/setuptools#891]
Since version 30.2.1, when running the command "python setup.py test" if the tests fails, the exit code is always 0.
I tracked the change of behavior to 53b47e1dfa9dfb1e8b94172a4650409fc03d4048
We found the issue because our CI is no more reporting failure because we run  the test with this command.
About #850, I think it is an expected behavior that if a command in a list fails that the following are not executed. So I think the revision should be reverted.

**Comment by cedk** [comment]
Also I think the new behaviour is in contradiction of the documentation:

>  running automated builds that need testing before they are deployed

from https://setuptools.readthedocs.io/en/latest/setuptools.html#test-build-package-and-run-a-unittest-suite

**Comment by jaraco** [comment]
I welcome someone to put together a pull request.

**Comment by pokoli** [comment]
About  #850 with the current behaviour running

>  python setup.py test build

 will still build the packages with the test failing. The previous behaviour the packages where not build as they first step failed. 

For me the previous behaviour is better as it will avoid the build of broken packages. 

Don't know if the right solution is to return the exit code correctly for the test command and keep the current behaviour for others. But that's one idea.

**Comment by cedk** [comment]
OK, I will work on a PR that will stop only on failure.
