### ISSUE TITLE
setuptools 32.1.1 brakes when bootstrapping with buildout

### ISSUE THREAD

**Issue by papachoco** [pypa/setuptools#893]
Hello,

I am getting the error below while bootstrapping with zc.buildout (zc.buildout-2.5.3).  setuptools-32.1.0 works fine

Thanks

Carlos

```
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-32.1.1.zip
Extracting in /tmp/tmpiaJsLJ
Traceback (most recent call last):
  File "./bootstrap.py", line 117, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 179, in use_setuptools
  File "<string>", line 130, in _do_download
  File "<string>", line 70, in _build_egg
  File "/home/ntiuser/.local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "<string>", line 109, in archive_context
  File "<string>", line 93, in __new__
  File "/home/ntiuser/.local/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/tmp/bootstrap-sdYL4z/setuptools-32.1.1.zip'
```

**Comment by myw** [comment]
this also breaks the bootstrap scripts on `bootstrap.pypa.io`, and, presumably, everyone and their mother's python Docker image builds. ಠ_ಠ

**Comment by eliaskousk** [comment]
Latest version 32.1.1 doesn't have a .zip archive to download (only tar.gz) and thus the [ez_zetup.py ](https://github.com/pypa/setuptools/blob/bootstrap/ez_setup.py)fails to download the file. As @myw says this is serious and everything that relies on this is now broken.

**Comment by jaraco** [comment]
Oh joy. I guess that's what I get for trusting the robots.

**Comment by jaraco** [comment]
It appears to be a regression in pypi itself. It now only allows one sdist per release:

```
Uploading distributions to https://upload.pypi.org/legacy/

Uploading setuptools-32.1.1-py2.py3-none-any.whl

[================================] 492690/492690 - 00:00:02

Uploading setuptools-32.1.1.tar.gz

[================================] 671841/671841 - 00:00:02

Uploading setuptools-32.1.1.zip

[================================] 725633/725633 - 00:00:00

HTTPError: 400 Client Error: Only one sdist may be uploaded per release. for url: https://upload.pypi.org/legacy/
```

**Comment by jaraco** [comment]
New release v32.1.2 drops tarball sdist, so should fix this issue.

**Comment by eliaskousk** [comment]
Thank you for the quick fix, everything seems fine now.

**Comment by papachoco** [comment]
Sadly pypi start reports 32.1.1

(nti.dataserver) hnic:nti.dataserver csanchez$ easy_install-2.7 -U setuptools
Searching for setuptools
Reading https://pypi.python.org/simple/setuptools/
Best match: setuptools 32.1.1
Processing setuptools-32.1.1-py2.7.egg
setuptools 32.1.1 is already the active version in easy-install.pth
Installing easy_install script to /Users/csanchez/VirtualEnvs/nti.dataserver/bin
Installing easy_install-2.7 script to /Users/csanchez/VirtualEnvs/nti.dataserver/bin

Using /Users/csanchez/VirtualEnvs/nti.dataserver/lib/python2.7/site-packages/setuptools-32.1.1-py2.7.egg
Processing dependencies for setuptools
Finished processing dependencies for setuptools
(nti.dataserver) hnic:nti.dataserver csanchez$

**Comment by jaraco** [comment]
I'm not sure what to tell you. Perhaps you got a cached index page or something, but I see 32.1.2 on that index page. It'll probably just start working but if not, I'll need you to chase the problem deeper.
