### ISSUE TITLE
Scripts parameter not working on Linux

### ISSUE THREAD

**Issue by cocodevienne** [pypa/setuptools#896]
I noticed when I used the scripts parameter in the  setup.py for my Python Wheel and I installed the Wheel on Windows I could call the program from the command line but I couldnt do that on Linux.
What am I doing wrong?

And another question I have is how do you do it so that you add a program to the path of any operating system?

**Comment by jaraco** [comment]
@cocodevienne Hard to say exactly what you're doing wrong. You probably don't have your PATH set to include a directory to which your scripts are being installed. First double-check that the file is being installed and that the directory to which it's being installed is in your $PATH environment variable.

> And another question I have is how do you do it so that you add a program to the path of any operating system?

I'm not sure what you're asking. See [distutils.command.install](https://github.com/python/cpython/blob/master/Lib/distutils/command/install.py#L22-L65) for the structures that distutils (and thus Setuptools) use as a basis for determining where to install scripts on a given platform.

**Comment by jaraco** [comment]
I've closed this ticket, but feel free to provide more details about what you're doing, what you observe, and what you expect to happen differently.

**Comment by cocodevienne** [comment]
No I read in an online article that you can use either the scripts parameter in the setup.py of a python wheel to add the main script of a systems $PATH and this approach workjs on windows but not on linux. 
Now my extra question was this: If I want to write a program that adds python scripts or any kind of executable to the path of the system on which the program is installed, what pythonic ways are there that are also cross_platform to add some executable to the system path using only Python? And the env variable created through this should be then available at all times and not only while python is running. @jaraco

**Comment by jaraco** [comment]
@cocodevienne I'm not aware of any cross-platform libraries to achieve what you're seeking. I might have thought [distlib](https://pypi.io/project/distlib) would have had what you need, but looking at the docs, it doesn't seem to. Your next stop may be to ask on the [distutils-sig mailing list](https://mail.python.org/mailman/listinfo/distutils-sig) or StackOverflow, where you may get a better answer. Best of luck.

**Comment by cocodevienne** [comment]
I asked the guys in the official Python IRC channel and they said I should use the tools and functions that setuptools provides. Is there a way to use setup() by itself and just use the entry_points paramater in a script and not specifically a setup.py? Like i use a str() function for instance? @jaraco

**Comment by jaraco** [comment]
@cocodevienne Setuptools doesn't manage $PATH, but relies on the system implementer (or user) to configure the paths on their system to be on $PATH. For example, if you configure a console_script in your project, and you install that project with `--user`, the console script will be installed in ~/.local/bin/ on Unix systems and ~/Application Data/Python 3.6/Scripts (or similar) on Windows. Therefore, you'll need for those paths to be in your $PATH on the given system for the scripts installed by setuptools to be executable.

But if the answer you got from the Python IRC channel was to use Setuptools, then you probably didn't successfully communicate to them what you're trying to achieve (setting PATH environment variables in a cross-platform way).
