### ISSUE TITLE
backports.unittest_mock not used in code

### ISSUE THREAD

**Issue by felixonmars** [pypa/setuptools#897]
I didn't find any mention of backports.unittest_mock in the code. Given that it only takes effect when explicitly importing and calling `.install()`, I think the dependency defined in tests/requirements.txt is redundant.

**Comment by jaraco** [comment]
The package supplies a pytest plugin, so is invoked implicitly when tests are run by pytest.

**Comment by felixonmars** [comment]
Ah, I overlooked that. Sorry for the noise!

**Comment by jaraco** [comment]
Not to worry. It is a bit magical.
