### ISSUE TITLE
ez_setup.py incorrectly detect charset

### ISSUE THREAD

**Issue by anton-tagunov** [pypa/setuptools#898]
The problem is reproduced when I am trying to init buildout by run bootstrap:
```
python bootstrap-buildout.py
Traceback (most recent call last):
  File "bootstrap-buildout.py", line 119, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 160, in use_setuptools
  File "<string>", line 375, in _resolve_version
  File "D:\bin\python35\lib\codecs.py", line 998, in getreader
    return lookup(encoding).streamreader
TypeError: lookup() argument must be str, not None

```

The bootstrap get latest ez_setup.py from https://bootstrap.pypa.io/ez_setup.py and try to exec it.

The real problem in the _resolve_version in ez_setup.py:
```
def _resolve_version(version):
...
    resp = urlopen(meta_url)  # https://pypi.org/pypi/setuptools/json
...
        try:
            charset = resp.info().get_content_charset()   #  returns None
        except Exception:
            # Python 2 compat; assume UTF-8
            charset = 'UTF-8'
        reader = codecs.getreader(charset) # fail here because charset is None
```
Possible last days Content-Type header was changed for https://pypi.org/pypi/setuptools/json.

Also I don't found repository for ez_setup.py. Only changelog contains info that it was removed from this repo, but there are no info about new location.

**Comment by kdeldycke** [comment]
Same issue here: https://travis-ci.org/kdeldycke/meta-package-manager/jobs/186461490#L243

**Comment by jaraco** [comment]
ez_setup.py can be found in [the bootstrap branch of setuptools](https://github.com/pypa/setuptools/tree/bootstrap).

**Comment by jaraco** [comment]
This issue is easily fixed by passing the fallback parameter to get_content_charset.

**Comment by jaraco** [comment]
Let me know if that doesn't fix the issue.

**Comment by kdeldycke** [comment]
I confirm https://github.com/pypa/setuptools/commit/044375318681ee22638271b9fab32225ec23a3ae is fixing the issue. Proof: https://travis-ci.org/kdeldycke/meta-package-manager/jobs/186547684#L246

Thanks @jaraco for the quick fix! 👍
