### ISSUE TITLE
self test problems

### ISSUE THREAD

**Issue by 0-wiz-0** [pypa/setuptools#904]
I wanted to run the self tests for setuptools (using the pypi distfile), but had a couple of problems:

* `setup.py test` complains about `error: invalid command pytest`

* next I tried using `pytest`, but that reported 18 errors, all having to do with `pkg_resources.tests` not being found.

* finally, I tried `tox`, but that complained about a missing  `tox.ini` 

Additionally, I think that relying on `tox` (or `pytest`) for the tests is not a good idea, since both of these need `setuptools` for installation.

**Comment by geier** [comment]
I see the same issues on FreeBSD, with the latest release as well as current master.

**Comment by jaraco** [comment]
Hmm. The test run on Travis using Tox. See .travis.yml for the specifics. How is it that tests run in CI but not in your Environment?

**Comment by jaraco** [comment]
Tests are run with tox. I'm guessing you're using a download of the sdist, which didn't have the tox.ini. Future releases should include the tox.ini. In the meantime, use a git checkout to run tests.
