### ISSUE TITLE
Runtime warning about missing wheel support

### ISSUE THREAD

**Issue by chrullrich** [pypa/setuptools#905]
setuptools should issue a giant warning that it does not support installing wheels when all potentially matching distributions in a PyPI result (or other collection of installation sources) are wheels. If it does not get to this point because it excludes all wheels first and then ends up with an empty set of distributions, it might as well warn then, too.

Currently, all the user gets to see is this:

    > python setup.py install
    [...]
    Processing dependencies for [internal package name elided]
    Searching for PyQt5>=5.7
    Reading https://pypi.python.org/simple/PyQt5/
    No local packages or working download links found for PyQt5>=5.7
    error: Could not find suitable distribution for Requirement.parse('PyQt5>=5.7')

There is no indication whatsoever of _why_ no suitable distribution is found. A look at the PyPI web site will show at least one matching package, and pip _will_ install it. For a user who does not know about the lack of wheel support in setuptools, it is then not exactly trivial to find out why this command does not work.

Googling the error message does not (at this time) return any helpful hits. Not even googling "setuptools wheel" does, and this query is far more targeted, if very unlikely to occur to an unaware user.

Finally, even for a user who is familiar with the wheel package format, it is not obvious at all that setuptools cannot _install_ wheels, when it is the centrally important tool for _building_ them.

Perhaps setuptools could delegate installation to pip instead of easy_install.

**Comment by jaraco** [comment]
This project is open to relying on pip for installing packages.

**Comment by FRidh** [comment]
Could probably close this in favor of https://github.com/pypa/setuptools/issues/917.

**Comment by benoit-pierre** [comment]
Wheels support was added in v38.2.0.
