### ISSUE TITLE
pip uninstall does not remove *-nspkg.pth for packages installed in editable mode

### ISSUE THREAD

**Issue by sbidoul** [pypa/setuptools#907]
Reporting here as this is related to the updated *-nspkg.pth mechanism, although I'm not sure if it is a pip or setuptools issue.

I'm working in a virtualenv with pip (9.0.1) and setuptools (32.3.1) with python 2.7.

I have a package `a1` which declares a namespace package.

`pip install -e a1/` creates `a1-nspkg.pth` in site-packages as well as `a1.egg-link`.

`pip uninstall a1` removes `a1.egg-link` but leaves `a1-nspkg.pth` behind.

I could find a previous mention of this issue in https://github.com/pypa/setuptools/issues/250#issuecomment-258714212 by @jaraco

**Comment by jaraco** [comment]
I had meant to file this as a ticket with pip. I don't think there's anything that Setuptools can do to signal which files get removed, so I believe it's strictly a pip issue.

**Comment by sbidoul** [comment]
@jaraco thanks for the feedback. I filed pip https://github.com/pypa/pip/issues/4213
