### ISSUE TITLE
question about "install_requires"  PEP 508  support in a setup.py

### ISSUE THREAD

**Issue by stonebig** [pypa/setuptools#908]
Hi,

I would like to know if, in a setup.py, used to prepare a wheel, the PEP 508 applies fully.

Case at hand: 
- an universal wheel is being prepared for Distributed, where the line "futures; python_version < '3.0'" is added from a requirements.txt file into the "install_requires" section of setup.py,
- when installing the universal  wheel in Python-3.6, the wheel apparently wrongly claims the "futures" package  "Collecting futures (from distributed>=1.14; extra == "complete"->dask[complete] ..."
 
https://github.com/dask/distributed/issues/771#issuecomment-269864639

(pip-9.0.1, setuptools-32.3.1)

**Comment by jaraco** [comment]
I should think this is supported, assuming you're using the latest versions. Next step would be to trace the cause; namely, check that the wheel has the environment marker to see if the issue lies in the build or the install. Then trace the issue in the relevant program to find out where the assumption fails.

**Comment by stonebig** [comment]
METADATA of distributed-1.15.0rc1-py2.py3-none-any.whl:
 ````Metadata-Version: 2.0
Name: distributed
Version: 1.15.0rc1
Summary: Distributed computing
Home-page: https://distributed.readthedocs.io/en/latest/
Author: Matthew Rocklin
Author-email: mrocklin@gmail.com
License: BSD
Platform: UNKNOWN
Requires-Dist: click (>=6.6)
Requires-Dist: cloudpickle (>=0.2.1)
Requires-Dist: dask (>=0.12.0)
Requires-Dist: futures
Requires-Dist: locket
Requires-Dist: msgpack-python
Requires-Dist: psutil
Requires-Dist: six
Requires-Dist: sortedcollections
Requires-Dist: tblib
Requires-Dist: toolz (>=0.7.4)
Requires-Dist: tornado (>=4.2)
Requires-Dist: zict (>=0.1.1)

UNKNOWN
````

==> apparently the "python_version" spefication gets lost... unless this is because it is in a line before in the install_requires list.

**Comment by jaraco** [comment]
Possibly related: #470

**Comment by stonebig** [comment]
reading 470, it's not written that it passes the information into the METADATA of the universal wheel.

**Comment by stonebig** [comment]
This morning, I check with my own library:
- in the setup.py 
`install_requires=["singledispatch; python_version < '3.4'"],`
- building from python 3.6:
`python setup.py sdist bdist_wheel  --universal`
- result in METADATA:
`Requires-Dist: singledispatch`

==> The wheel format looses the PEP 508 conditional information on python_version

It would make sense to have PEP 508 kept and supported all the way down from requirements.txt, setup.py (install_requires), to wheel final files.

**Comment by stonebig** [comment]
hum: it's not written in wheel format 1.9 PEP 491, so it's at best a long term wheel 2.0 format thing.... sad discovery, closing

**Comment by stonebig** [comment]
it may have help that, while respecting wheel format, the setup.py could transform the "python__version" PEP 508 specification in PEP 426  specification for the wheel format, when possible.
