### ISSUE TITLE
extras_require documentation doesn't that it can be used to install a dependency based on the python version being used

### ISSUE THREAD

**Issue by plannigan** [pypa/setuptools#909]
When using newer features of python, it is necessary to install the back port packages of that feature in order to support older python versions. ``setuptools`` supports this in ``extra_requires``, but it is not mentioned in the documentation.

See this [stackoverflow answer](http://stackoverflow.com/a/32643122/210526) explains the basics, but a more detailed description should appear in the official documentation.

**Comment by jaraco** [comment]
Yes, I agree. Would you be willing to draft the documentation in a pull request?
