### ISSUE TITLE
Using environment markers in install_requires fails

### ISSUE THREAD

**Issue by plannigan** [pypa/setuptools#911]
The changelog for 20.5 seems to indicate that environment markers should be supported in install_requires, but I was not able to get that to work. Specifically, the [example from PEP 496](https://www.python.org/dev/peps/pep-0496/#examples) causes an error.

Environment:
```pip list
pip (9.0.1)
pkg-resources (0.0.0)
setuptools (32.3.1)
wheel (0.30.0a0)
```
Procedure to reproduce:
```
python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from setuptools import setup
>>> setup(install_requires=["pywin32 > 1.0 : sys.platform == 'win32'"])
error in setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "': sys.pl'"
```
The same error occurs when the argument is passed to `setup_requires`, but the exception is not caught.

**Comment by xavfernandez** [comment]
`PEP 496` is a draft. The relevant (and accepted PEP) is [PEP 508](https://www.python.org/dev/peps/pep-0508/).
You need to use `;` and not `:`.
