### ISSUE TITLE
Trying to install on a shared host server

### ISSUE THREAD

**Issue by aidinzolghadr** [pypa/setuptools#920]
Hi,

I have a shared host server (Debian) that I compiled python 2.7.10 on it and added it to bash so it's now default python rather than systm's one which I don't have write permission.

So, next step was to install ez_setup (I do know this is setuptools but I've read they are the same) so I did this:

```
wget https://bootstrap.pypa.io/ez_setup.py
python ez_setup.py
```

But it returns an error after running python command:

Traceback (most recent call last):
  File "ez_setup.py", line 437, in <module>
    sys.exit(main())
  File "ez_setup.py", line 433, in main
    archive = download_setuptools(**_download_args(options))
  File "ez_setup.py", line 347, in download_setuptools
    version = _resolve_version(version)
  File "ez_setup.py", line 368, in _resolve_version
    resp = urlopen(meta_url)
  File "/user/python27/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/user/python27/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/user/python27/lib/python2.7/urllib2.py", line 454, in _open
    'unknown_open', req)
  File "/user/python27/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/user/python27/lib/python2.7/urllib2.py", line 1265, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: https>

Thanks

**Comment by jaraco** [comment]
I suspect you've built Python without SSL, so the https URL isn't recognized. You should either build with SSL or specify a download URL without SSL.

**Comment by aidinzolghadr** [comment]
That's the problem, I can't build with SSL. My host has openssl installed but python installer won't pick it up and changing Modules/Setup.dist won't help.

**Comment by jaraco** [comment]
I should have suggested this before - instead of using `ez_setup.py`, you should simply install pip [according to the instructions](https://packaging.python.org/installing/) and use pip to install setuptools.

**Comment by jaraco** [comment]
I suspect pip has options to bypass the requirement for SSL, but you really should find a way to get Python with SSL.
