### ISSUE TITLE
Setting DISTRIBUTE_DISABLE_VERSIONED_EASY_INSTALL_SCRIPT not working

### ISSUE THREAD

**Issue by jakirkham** [pypa/setuptools#932]
Appears when setting `DISTRIBUTE_DISABLE_VERSIONED_EASY_INSTALL_SCRIPT`, we still end up getting Python versioned `easy_install` scripts installed (e.g. `easy_install-3.6`). Not entirely sure where this is coming from when glancing at the code. Hoping someone else has a better idea of what is going on.

**Comment by jaraco** [comment]
I suspect support for the Distribute naming was removed in a recent release of Setuptools. Just change Distribute to Setuptools and you should be good. Let us know what you find.

**Comment by jakirkham** [comment]
We're doing both.

**Comment by jaraco** [comment]
And checking the code, it does honor both of those variables as well. Maybe you're using a runner that filters environment variables. Or maybe there's something weird about Python 3.6.

I suggest you trace the code and troubleshoot. Or at least put together a few steps that will replicate the issue.

**Comment by jakirkham** [comment]
Sure. We are building using this [script]( https://github.com/conda-forge/setuptools-feedstock/blob/d7693974eafbc16f288f2c441249379318e685bd/recipe/build.sh ) on Mac and Linux or this [script]( https://github.com/conda-forge/setuptools-feedstock/blob/d7693974eafbc16f288f2c441249379318e685bd/recipe/bld.bat ) on Windows. We are just using the code from the GitHub archive tarballs. If you or someone else wanted, changes can be tested out on CIs with a PR against this [repo]( https://github.com/conda-forge/setuptools-feedstock ).

This problem is not unique to Python 3.6. We also see it with Python 3.5 and Python 2.7. We also saw it with Python 3.4 when we were still building for that Python version. As far as I can remember, we have had this issue since adding those flags. Something like `25.1.3` was when we first started using them.

Hope that helps. Please let me know if you need any more information.

**Comment by jaraco** [comment]
The problem is that you're setting the value to 0. You need `SETUPTOOLS_DISABLE_VERSIONED_EASY_INSTALL_SCRIPT=1`.

**Comment by jakirkham** [comment]
Oops. 😳 Sorry that was foolish.

**Comment by jaraco** [comment]
No worries. Thanks for using Setuptools.
