### ISSUE TITLE
Graft with Asterisk broken after 28.4.0

### ISSUE THREAD

**Issue by pykler** [pypa/setuptools#935]
28.4.0 is the last release where `graft */data` as an example, was working. After that release, there is a warning that `warning: no directories found matching '*/data'`

**Comment by jaraco** [comment]
Probably related to #764. @timheap, can you investigate?

**Comment by pykler** [comment]
This seems correct, I was able to isolate the issue to this commit

commit bb45468d27615c2ce9f9c9757a367c44d6ee80d2
| | Author: Tim Heap
| | Date:   Tue Aug 16 16:40:10 2016 +1000
| |
| |     Much faster implementation of FileList, for big egg_info speedups
