### ISSUE TITLE
setuptools 34.0.1 fails on python 2.7 

### ISSUE THREAD

**Issue by projekt01** [pypa/setuptools#939]
setuptools 34.0.1 with python 2.7.11 on Windows 64 bit fails if used with zc.buildout with the following error after "auto" upgrade to the newest setutools version 34.0.1 with the following traceback:

```
bin\buildout.exe
Upgraded:
  setuptools version 34.0.1;
restarting.
Generated script 'D:\\...\\bin\\buildout'.
Develop: 'D:\\...\\trunk\\.'
Traceback (most recent call last):
  File "c:\tmp\tmpqbbwgz", line 6, in <module>
    import os, setuptools
  File "d:\home\.buildout\eggs\setuptools-34.0.1-py2.7.egg\setuptools\__init__.py", line 12, in <module>
    import setuptools.version
  File "d:\home\.buildout\eggs\setuptools-34.0.1-py2.7.egg\setuptools\version.py", line 1, in <module>
    import pkg_resources
  File "d:\home\.buildout\eggs\setuptools-34.0.1-py2.7.egg\pkg_resources\__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named packaging.version
While:
  Installing.
  Processing develop directory ...\\trunk\\.'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "d:\home\.buildout\eggs\zc.buildout-2.5.3-py2.7.egg\zc\buildout\buildout.py", line 1995, in main
    getattr(buildout, command)(args)
  File "d:\home\.buildout\eggs\zc.buildout-2.5.3-py2.7.egg\zc\buildout\buildout.py", line 528, in install
    installed_develop_eggs = self._develop()
  File "d:\home\.buildout\eggs\zc.buildout-2.5.3-py2.7.egg\zc\buildout\buildout.py", line 770, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "d:\home\.buildout\eggs\zc.buildout-2.5.3-py2.7.egg\zc\buildout\easy_install.py", line 996, in develop
    call_subprocess(args)
  File "d:\home\.buildout\eggs\zc.buildout-2.5.3-py2.7.egg\zc\buildout\easy_install.py", line 160, in call_subprocess
    % repr(args)[1:-1])
Exception: Failed to run command:
'C:\\Python27\\python.exe', 'c:\\tmp\\tmpqbbwgz', '-q', 'develop', '-mN', '-d', 'D:\\..\\trunk\\develop-eggs\\tmpa7ydv3build'
```

**Comment by jaraco** [comment]
I'm pretty sure this is a buildout issue that will need to be addressed there. I'm not sure what steps an auto upgrade of setuptools does, but it will probably need to pre-install the dependencies of setuptools or use pip to uninstall/install setuptools.

**Comment by projekt01** [comment]
Hi jaraco, Thanks, I guess your are right. I didn't see the new dependencies in setuptools. Hm, I'm not sure if it's a good idea to require other packages for install setuptools which is used for install packages. 
What do you think about vendoring the required packages like in distlib? It seems that using virtual env or mess up the system python will be the only two options to install packages in the future. 

I'm not really happy with the direction that the package management goes with python. To me, it seems that pip, setuptools and probably others do things which shouldn't be done just for a better end user experience. The cost we pay is a list of preconditions for installl the installler tools and package in python we don't need in our applications. 
Probably I missed something. If so, can you explain how a clean python setup should look like without to get any other package into the python runtime except our own source code and our code dependencies? Don't take that as personal criticque. I'm sure you know what you are doing. I just didn't understand the reason why.
Regards Roger

**Comment by jaraco** [comment]
This work is part of simplifying the ecosystem. See #581 for more background on why I made this change.

The [recommended usage to install packages](https://packaging.python.org/installing/) is to simply use pip. The Python Packaging Users Guide is where we'll put our best recommendations, so you can consider that authoritative (although it's subject to error and critique as well).

Hope that helps.
