### ISSUE TITLE
Module Interdependence

### ISSUE THREAD

**Issue by coneagoe** [pypa/setuptools#948]
# Version
setuptools-34.0.2
pyparsing-2.1.10
appdirs-1.4.0

# Description
setuptools depends on the modules pyparsing and appdirs, while these modules interdepend on setuptools. Suppose a clean environment without these modules above and you want to build them from source, then the issue comes out.

**Comment by jaraco** [comment]
I just had a quick look at the source code for pyparsing, and it doesn't reference setuptools in the setup.py and doesn't reference setuptools nor pkg_resources in the code. Same with appdirs.

If you are encountering an error, please include the error you're encountering.

**Comment by coneagoe** [comment]
I'm afraid you missed them.

``` Shell
$ grep -n -H 'setuptools' appdirs-1.4.0/setup.py packaging-16.8/setup.py
appdirs-1.4.0/setup.py:5:from setuptools import setup
packaging-16.8/setup.py:11:# setuptools and distutils with a single setup.py, in this specific instance
packaging-16.8/setup.py:12:# where packaging is a dependency of setuptools, it can create a circular
packaging-16.8/setup.py:13:# dependency when projects attempt to unbundle stuff from setuptools and pip.
packaging-16.8/setup.py:17:    from setuptools import setup
```

**Comment by jaraco** [comment]
What you describe there are build dependencies, which must be present to build but not to install/run. So it's true that you need Setuptools to build pyparaing. But you don't need to build it to install it. You have a couple of choices. You can either install an old Setuptools and then build pyparsing, or you can use a tool like pip to install a prebuilt pyparsing (wheel).
