### ISSUE TITLE
Classifiers do not make a good config section

### ISSUE THREAD

**Issue by jwodder** [pypa/setuptools#952]
So I see that Setuptools 30.3.0 added support for defining package metadata in `setup.cfg` instead of `setup.py`.  Neat!  The documentation even gives an example of how you could define a package's classifiers in a section of their own:

```
[metadata.classifiers]
Framework :: Django
Programming Language :: Python :: 3.5
```

Let me try!  I'll just create a fresh virtualenv with Setuptools 34.1.0 already installed, using either Python 2.7.12 or 3.5.2 (same results either way).  Now if I move my classifiers to `setup.cfg` like so:

```
[metadata.classifiers]
Development Status :: 3 - Alpha
Programming Language :: Python :: 2
Programming Language :: Python :: 2.6
Programming Language :: Python :: 2.7
Programming Language :: Python :: 3
Programming Language :: Python :: 3.3
Programming Language :: Python :: 3.4
Programming Language :: Python :: 3.5
Programming Language :: Python :: 3.6
Programming Language :: Python :: Implementation :: CPython
Programming Language :: Python :: Implementation :: PyPy
License :: OSI Approved :: MIT License
Intended Audience :: Developers
Topic :: Communications :: Email
Topic :: Communications :: Usenet News
Topic :: Internet :: WWW/HTTP
Topic :: Text Processing
```

... and then run `python setup.py --classifiers` to test:

```
Intended Audience :: Developers
Topic :: Text Processing
Development Status :: 3 - Alpha
License :: OSI Approved :: MIT License
Programming Language :: Python :: Implementation :: PyPy
```

That's... not right.  It appears that the configuration parser is treating the first colon in each classifier as an assignment operator (so that `Development Status :: 3 - Alpha` is parsed the same way as `Development = : 3 - Alpha`) and then Setuptools joins the key & value back together with `:`. (This theory is supported by the fact that I get the exact same output if I replace the first colon on each line with `=`.)  Because of this, any classifier with the same initial component as a previous classifier will overwrite the previous one, and so Setuptools will only see the last `Programming Language` line, the last `Topic` line, etc.

It might be possible to fix this by initializing the `configparser` object with `delimiters=('=',), allow_no_value=True`, but this wouldn't work in Python 2, and it'd affect all other config sections as well (but how many people use colons as the delimiter in `setup.cfg`, anyway?).

**Comment by jaraco** [comment]
@idlesign - any chance you can help with this issue?

**Comment by idlesign** [comment]
Sure. I've stumbled upon this issue the other day too. Classifiers in a subsection was a hack that looked nice, and I was glad as it seemed to be working but I've missed the issue.
The only solution I see for now that won't be another hack is to use only list notation or separate file for classifiers, and to deprecate a didicated section syntax.

@jaraco If no other other option I'll update the docs, and drop support for the subsection.

**Comment by xavfernandez** [comment]
The solution used in flit seems ok, cf http://flit.readthedocs.io/en/latest/flit_ini.html

**Comment by jaraco** [comment]
@idlesign: I can't think of a better option. Plus, consistency with other systems is worthwhile, so recommending list notation seems like the best option.

**Comment by idlesign** [comment]
@jaraco Should we drop support with deprecation warning phase or at once?

**Comment by jaraco** [comment]
At once is fine given the limited period of release and the unlikely adoption given the issue.

**Comment by idlesign** [comment]
Done.

**Comment by idlesign** [comment]
Should be closed, I think.
