### ISSUE TITLE
Provide *.tar.gz on PyPI

### ISSUE THREAD

**Issue by yegorich** [pypa/setuptools#963]
Could you provide *.tar.gz on PyPI as it was made earlier? The recipes in Buildroot are tailored to this format and handling *.zip files requires extra actions with folder renaming etc.

**Comment by jaraco** [comment]
We can't easily. PyPI now restricts install of sdists to only one form, and the canonical form for historical reasons is .zip. To distribute with a tarball, we would have to drop zip files.
