### ISSUE TITLE
setuptools: ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by 0-wiz-0** [pypa/setuptools#964]
Building setuptools in the standard way I've used forever fails:
````
# /usr/pkg/bin/python3.6  setup.py  build
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File ".../setuptools-34.1.1/setuptools/__init__.py", line 10, in <module>
    from six.moves import filter, map
ModuleNotFoundError: No module named 'six'
````
It looks like setuptools now added a six dependency, which breaks distributions that build from scratch, because six uses setuptools for installation (dependency cycle).

**Comment by jaraco** [comment]
That's right. This change was made intentionally as part of the Setuptools 34 release - dropping support for self install and upgrade. We've removed the hack that vendors setuptools dependencies. You'll want to install the dependencies with pip first. See bootstrap.py for one technique for installing the dependencies.

**Comment by 0-wiz-0** [comment]
I'm sorry if I'm slow to understand, but I have more questions. I don't see `bootstrap.py` documented, and reading it, it imports `pip`. `pip` also needs setuptools to install.

What is the recommended packaging procedure if you only have python installed to get to packages for pip and setuptools?

**Comment by jaraco** [comment]
https://python-packaging-user-guide.readthedocs.io/installing/#install-pip-setuptools-and-wheel

**Comment by 0-wiz-0** [comment]
For anyone else stumbling over this issue, my solution was:

* install the setuptools version that is coming with python, using `python -m ensurepip --user`
* build and install appdirs, six, pyparsing, and packaging with this version
* build setuptools
* delete the --user installation of the old version

**Comment by maxguxiao** [comment]
I got the same problem after I upgrade python2.7.10 to python2.7.13.

None of the above works for me.
Finally, I fixed this by download six package directly from [pypi](https://pypi.python.org/pypi/six#downloads), 
then go to the download directory,
and manually installed it by using python set-up.py install.

**Comment by Kentzo** [comment]
I wish that dependency would be lifted when Python 3 is being used.

**Comment by jaraco** [comment]
That dependency will be lifted when Python 2.7 support is dropped. Until then, `six` is the library that enables a unified codebase for all versions.
