### ISSUE TITLE
Please revert breaking changes

### ISSUE THREAD

**Issue by philtay** [pypa/setuptools#970]
I just want to share my opinion on the recent breaking changes. Please revert them. An utility to install packages cannot directly depend from other packages which in turn depends from it. To me is simple logic. The dependency chain must stop somewhere. `setuptools` dependencies must be vendored. This is the root cause of all problems.

**Comment by jaraco** [comment]
> Please revert breaking changes.

I presume you mean the changes introduced in [Setuptools 34](http://setuptools.readthedocs.io/en/latest/history.html#v34-0-0), and not the other breaking changes in the 33 other major releases of Setuptools.

I do apologize for the inconvenience and disruption this change has caused. It's a necessary change to simplify the package and move it toward a better design. There are other important changes, such as moving pkg_resources into its own package, that depend on this change.

> The dependency chain must stop somewhere.

We recommend that you use pip to install packages, including setuptools, in which case the inherent dependency issue goes away. That's where the dependency chain stops. Pip does vendor its depnedencies, had a robust bootstrapping mechanism, and comes installed by default with some distributions. It's redundant to continue supporting bootstrapping in another, deprecated tool.

The PyPA is dedicated to help the community transition away from easy_install.

> This is the root cause of all problems.

If this statement were true, then I would certainly revert the changes. On the whole, this change has been well received and has caused only some problems in specific, isolated scenarios. I'm aggressively working to tackle those scenarios. I've addressed #947 and I've invested a great deal of effort investigating #951 with a fix pending in pypa/pip#4285.

Of course, you're welcome to pin to older versions of setuptools to avoid the issues until you're able to work through them or until the underlying issues are addressed upstream.
