### ISSUE TITLE
Where can the source code of the packaged EXEs in the setuptools folder.

### ISSUE THREAD

**Issue by momashi** [pypa/setuptools#972]
Hello lovely pypa-lz,

 I'm trying to find the source code for the exes that are bundled into the source code of setuptools. Namely gui-32/64.exe and cli-32/64.exe in the  the \setuptools folder. Can someone please tell me where I can find it?

**Comment by bb-migration** [comment]
There's a script in the root for the repo for building those exes. That should refer to the source.

**Comment by momashi** [comment]
Hi bb-migration, thanks for getting back to me. I'm trouble finding it, did you have a specific script in mind that I could look at? 

I did a text search through all the setup-tools source for cli-32.exe, cli-64.exe gui-32.exe etc but the only reference to them I could find was in **test_windows_wrapper.py**:

> There are 2 wrappers, one for command-line programs, cli.exe, and one for graphical programs, gui.exe.  These programs are almost identical, function pretty much the same way, and are generated from the same source file.

It doesn't say where I can find the source though...

**Comment by jaraco** [comment]
That's funny. I responded on my phone, and apparently github thinks my e-mail address is better associated with that account. The file of which I speak is at https://github.com/pypa/setuptools/blob/master/msvc-build-launcher.cmd.

**Comment by momashi** [comment]
Oh, that's so awesome. Thanks for your help!
