### ISSUE TITLE
It says "ImportError: No module named appdirs" while install setuptools via cmd “python setup.py install “ in Win7 system.

### ISSUE THREAD

**Issue by piaoransk** [pypa/setuptools#974]
ENV:
python:python-2.7.6.amd64.1394777203.msi
OS:win7-64(VMware Workstation)

It says "ImportError: No module named appdirs" while installing setuptools via cmd “python setup.py install “ in Win7 system.
But it says "ImportError: No module named setuptools" after "D:\Test\appdirs-1.4.0>python setup.py install".
How can i fix it ?
Thanks!
![2](https://cloud.githubusercontent.com/assets/10584839/23003179/e3660e38-f429-11e6-8af1-2aba7de3ff31.png)

**Comment by piaoransk** [comment]
fixed.
switch to the latest python 2.7.13.

**Comment by AraHaan** [comment]
You could also use Python 3.6 as well for things like coroutines and stuff.
