### ISSUE TITLE
Still looking for six as depency

### ISSUE THREAD

**Issue by rudyvogt** [pypa/setuptools#979]
Hi,

I have installed six, pyparsing/packaging and appdirs, but setuptools still looks for it. 
I install all the packages from the network, due to firewall/proxy blocks.

```
Requirement already satisfied: six==1.10.0 from file:///M:/Production/ApplicationSupport/Utility/PythonSrc/pipInstall/wheel/six-1.10.0-py2.py3-none-any.whl in c:\program files (x86)\python27\arcgis10.4\lib\site-packages
Requirement already satisfied: pyparsing==2.1.10 from file:///M:/Production/ApplicationSupport/Utility/PythonSrc/pipInstall/wheel/pyparsing-2.1.10-py2.py3-none-any.whl in c:\program files (x86)\python27\arcgis10.4\lib\site-packages
Requirement already satisfied: packaging==16.8 from file:///M:/Production/ApplicationSupport/Utility/PythonSrc/pipInstall/wheel/packaging-16.8-py2.py3-none-any.whl in c:\program files (x86)\python27\arcgis10.4\lib\site-packages
Requirement already satisfied: pyparsing in c:\program files (x86)\python27\arcgis10.4\lib\site-packages (from packaging==16.8)
Requirement already satisfied: six in c:\program files (x86)\python27\arcgis10.4\lib\site-packages (from packaging==16.8)
Requirement already satisfied: appdirs==1.4.0 from file:///M:/Production/ApplicationSupport/Utility/PythonSrc/pipInstall/wheel/appdirs-1.4.0-py2.py3-none-any.whl in c:\program files (x86)\python27\arcgis10.4\lib\site-packages
Processing m:\production\applicationsupport\utility\pythonsrc\pipinstall\wheel\setuptools-34.2.0-py2.py3-none-any.whl

**←[33mRetrying (Retry(total=4, connect=None, read=None, redirect=None)) after con
nection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.co
nnection.VerifiedHTTPSConnection object at 0x031BDF70>, 'Connection to pypi.pyth
on.org timed out. (connect timeout=15)')': /simple/six/←[0m**
←[33mRetrying (Retry(total=3, connect=None, read=None, redirect=None)) after con
nection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.co
nnection.VerifiedHTTPSConnection object at 0x031E4050>, 'Connection to pypi.pyth
on.org timed out. (connect timeout=15)')': /simple/six/←[0m

```

**Comment by jaraco** [comment]
It's pip that's looking for it, so the issue likely lies with pip. What commands are you running? How have you set up the environment?

**Comment by laapsaap** [comment]
The solutions given here is do upgrade pip etc or preinstall six before running setuptools.

I am in a situation where I have no **pip**, so to install **pip** I need to use **easy_install**, but **easy_install** needs **six**, to install *six** I need **pip**.  Yeah...

**Comment by jaraco** [comment]
> to install pip I need to use easy_install

Actually, the [recommended way to install pip](https://python-packaging-user-guide.readthedocs.io/installing/#install-pip-setuptools-and-wheel) is to run `pip -m ensurepip` or `get-pip.py`. Neither of those techniques require setuptools or easy_install. From there, pip will install six or setuptools or other packages.

**Comment by jaraco** [comment]
@rudyvogt See [this section](https://python-packaging-user-guide.readthedocs.io/installing/#installing-from-local-archives) in the packaging users guide. If you need help installing pip in that environment, please reach out to the pip project. I don't know a way to install pip if you don't already have it installed.

**Comment by rudyvogt** [comment]
yes it is working now i have added 
-U --no-index 	\\%uncpath%l\setuptools-34.2.0-py2.py3-none-any.whl
and is working fine

Requirement already satisfied: six==1.10.0 from file:///M:/Production/ApplicationSupport/Utility/Python/wheel/six-1.10.0-py2.py3-none-any.whl in d:\apps\python27\arcgis10.4\lib\site-packages
Requirement already satisfied: pyparsing==2.1.10 from file:///M:/Production/ApplicationSupport/Utility/Python/wheel/pyparsing-2.1.10-py2.py3-none-any.whl in d:\apps\python27\arcgis10.4\lib\site-packages
Requirement already satisfied: packaging==16.8 from file:///M:/Production/ApplicationSupport/Utility/Python/wheel/packaging-16.8-py2.py3-none-any.whl in d:\apps\python27\arcgis10.4\lib\site-packages
Requirement already satisfied: pyparsing in d:\apps\python27\arcgis10.4\lib\site-packages (from packaging==16.8)
Requirement already satisfied: six in d:\apps\python27\arcgis10.4\lib\site-packages (from packaging==16.8)
Requirement already satisfied: appdirs==1.4.0 from file:///M:/Production/ApplicationSupport/Utility/Python/wheel/appdirs-1.4.0-py2.py3-none-any.whl in d:\apps\python27\arcgis10.4\lib\site-packages
Processing m:\production\applicationsupport\utility\python\wheel\setuptools-34.2.0-py2.py3-none-any.whl
Requirement already up-to-date: six>=1.6.0 in d:\apps\python27\arcgis10.4\lib\site-packages (from setuptools==34.2.0)
Requirement already up-to-date: appdirs>=1.4.0 in d:\apps\python27\arcgis10.4\lib\site-packages (from setuptools==34.2.0)
Requirement already up-to-date: packaging>=16.8 in d:\apps\python27\arcgis10.4\lib\site-packages (from setuptools==34.2.0)
Requirement already up-to-date: pyparsing in d:\apps\python27\arcgis10.4\lib\site-packages (from packaging>=16.8->setuptools==34.2.0)
Installing collected packages: setuptools
  Found existing installation: setuptools 34.2.0
    Uninstalling setuptools-34.2.0:
      Successfully uninstalled setuptools-34.2.0
Successfully installed setuptools-34.2.0
