### ISSUE TITLE
Encoding problems with pkg_file on 2.7

### ISSUE THREAD

**Issue by cmutel** [pypa/setuptools#984]
In `dist.py`, the function `write_pkg_info` [specifies an encoding](https://github.com/pypa/setuptools/blob/master/setuptools/dist.py#L79) when opening the `PKG-INFO` file for writes. However, the function `write_pkg_file` uses [string interpolation](https://github.com/pypa/setuptools/blob/master/setuptools/dist.py#L44) when writing metadata, e.g. 

    file.write('Metadata-Version: %s\n' % version)

On 2.7, `'Metadata-Version: %s\n'` is a `str`, not `unicode`. If the Python package is 2/3 compatible, then the name, version, and especially data often read from files such as the license will be unicode strings. As such, they can raise a `UnicodeEncodeError` when encoded to the default 2.7 ascii encoding.

There is a test repository showing this behaviour here: https://github.com/cmutel/setuptools_encoding_pkg_file_bug

I can't think of a way to fix this without breaking existing code except for a wrapper function that would try to figure out the right thing to do with different types of strings (and different python versions). Note that this issue can occur any time there is string interpolation of data read from `setup.py`.

**Comment by jaraco** [comment]
I suspect dist.py should use a `from __future__ import unicode_literals`, especially given that those functions were taken from Python 3. How much would that break existing code?

**Comment by abravalheri** [comment]
Since now Python 2 reached its EoL, I suspect it is safe for us to close this issue... (but please let me know if I am wrong here).
