### ISSUE TITLE
Kubuntu 14.04 sudo easy_install -U setuptools fails

### ISSUE THREAD

**Issue by ouboub** [pypa/setuptools#996]
Hi

when running this command I obtain errors like
 a lot of messages and then

File "/usr/lib/python2.7/pkgutil.py", line 394, in get_importer
    importer = ImpImporter(path_item)
RuntimeError: maximum recursion depth exceeded while calling a Python object

I upgraded dist succesfully, but now I am stuck

thanks

Uwe Brauer

**Comment by jaraco** [comment]
In Setuptools 34, it dropped support for self install/upgrade. Don't use easy_install; use pip. That should help.

**Comment by ouboub** [comment]
Yes you are right, that solved the problem. thanks
