### ISSUE TITLE
setuptools.dist imports packaging, but check_specifier accesses packaging.specifiers

### ISSUE THREAD

**Issue by jimfulton** [pypa/setuptools#997]
This causes an attribute error in check_specifier.

**Comment by jimfulton** [comment]
FWIW, this is breaking a deployment I'm dealing with.

**Comment by jaraco** [comment]
This issue probably emerged in Setuptools 34 when the vendoring was removed (ff371f1), as dist no longer imports pkg_resources to get the externs (which would import these submodules).

**Comment by jimfulton** [comment]
The bug became effective then. :)

**Comment by jaraco** [comment]
I believe this report is a duplicate of #967.

**Comment by jimfulton** [comment]
Yup
